javadoc/pom.xml
https://issues.redhat.com/browse/ISPN-13934
=> ISPN-13934 Fix hibernate-core version in javadoc modules

core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
https://issues.redhat.com/browse/ISPN-13940
=> ISPN-13940 BlockingManager#runBlockingOperation doesn't return stage

server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfigurationBuilder.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/LdapIdentityMappingConfiguration.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/LdapIdentityMappingConfigurationBuilder.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/LdapRealmConfiguration.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/LdapRealmConfigurationBuilder.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/LdapUserPasswordMapperConfiguration.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/LdapUserPasswordMapperConfigurationBuilder.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/PropertiesRealmConfiguration.java, server/runtime/src/main/java/org/infinispan/server/logging/Log.java, server/runtime/src/main/java/org/infinispan/server/security/ServerSecurityRealm.java
https://issues.redhat.com/browse/ISPN-13757
=> ISPN-13757 Tweak valid auth mechanisms based on LDAP configuration

build/configuration/pom.xml, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/JsonKeyValueRawEventsTest.java, core/src/test/java/org/infinispan/test/data/Person.java, server/core/src/test/java/org/infinispan/server/core/dataconversion/JsonTranscoderTest.java
https://issues.redhat.com/browse/ISPN-13917
=> ISPN-13917 Protostream 4.5.0.Dev02

server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/RespDetector.java, server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java, server/runtime/src/main/server/server/conf/infinispan-local.xml
https://issues.redhat.com/browse/ISPN-13943
https://issues.redhat.com/browse/ISPN-13942
=> ISPN-13943 Enable the RESP connector by default

pom.xml
https://issues.redhat.com/browse/ISPN-13945
=> ISPN-13945 Blocked call to docker API after stopping containers

client/rest-client/src/main/java/org/infinispan/client/rest/RestResponse.java, server/core/src/main/java/org/infinispan/server/core/backup/BackupManagerImpl.java, server/tests/src/test/java/org/infinispan/server/functional/AbstractMultiClusterIT.java, server/tests/src/test/java/org/infinispan/server/functional/BackupManagerIT.java, server/tests/src/test/java/org/infinispan/server/functional/CloudEventsIntegrationIT.java, server/tests/src/test/java/org/infinispan/server/functional/ConcurrentShutdownRestIT.java, server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java, server/tests/src/test/java/org/infinispan/server/functional/RestLoggingResource.java, server/tests/src/test/java/org/infinispan/server/functional/RestMetricsResource.java, server/tests/src/test/java/org/infinispan/server/functional/RestOperations.java, server/tests/src/test/java/org/infinispan/server/functional/RestRouter.java, server/tests/src/test/java/org/infinispan/server/functional/RestServerResource.java, server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeDynamicStoreIT.java, server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeIT.java, server/tests/src/test/java/org/infinispan/server/functional/ShutdownContainerIT.java, server/tests/src/test/java/org/infinispan/server/functional/ShutdownRestIT.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteHotRodCacheOperations.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteRestCacheOperations.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteRestMetricsOperations.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java, server/tests/src/test/java/org/infinispan/server/test/core/Common.java
https://issues.redhat.com/browse/ISPN-13963
=> ISPN-13963 Close RestResources

client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/auth/DigestAuthenticator.java
https://issues.redhat.com/browse/ISPN-13966
=> ISPN-13966 Fix parsing of HTTP auth headers

core/src/main/java/org/infinispan/util/concurrent/CommandAckCollector.java, core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.redhat.com/browse/ISPN-13958
=> ISPN-13958 Add destination in ISPN000427 - Timeout after 60 seconds waiting for acks

core/src/test/resources/configs/xsite/bridge.xml
https://issues.redhat.com/browse/ISPN-13965
=> ISPN-13965 Set bind_port=0 for cross-site tests

javadoc/pom.xml
* fix javadoc build
CI failure: https://ci.infinispan.org/job/Infinispan/job/main/550/
https://issues.redhat.com/browse/ISPN-13971
=> ISPN-13971 Add the Netty IOUring transport

documentation/src/main/asciidoc/topics/ref_server_realm_property.adoc
JIRA: https://issues.redhat.com/browse/ISPN-13972
=> ISPN-13972: Update property realm note in Security realms doc

documentation/src/main/asciidoc/topics/hotrod_protocol.adoc
=> Fixed hotrod PING response format

distribution/src/main/resources/template/licenses.xsl
https://issues.redhat.com/browse/ISPN-13980
=> ISPN-13980 Licenses: check for CC0 word before public domain

build/configuration/pom.xml, core/src/test/java/org/infinispan/expiration/impl/ExpirationManagerTest.java, core/src/test/java/org/infinispan/notifications/cachelistener/BaseCacheNotifierImplInitialTransferTest.java, core/src/test/java/org/infinispan/notifications/cachelistener/CacheNotifierTest.java, core/src/test/java/org/infinispan/notifications/cachelistener/CacheNotifierTxTest.java, core/src/test/java/org/infinispan/notifications/cachelistener/SimpleCacheNotifierTest.java, core/src/test/java/org/infinispan/remoting/jgroups/ChannelLookupTest.java, core/src/test/java/org/infinispan/replication/ForceSyncAsyncFlagsTest.java, core/src/test/java/org/infinispan/replication/SyncReplTest.java, core/src/test/java/org/infinispan/stream/DistributedStreamIteratorWithPassivationTest.java, core/src/test/java/org/infinispan/stream/LocalStreamIteratorWithPassivationTest.java, core/src/test/java/org/infinispan/util/concurrent/BlockingManagerTest.java, documentation/pom.xml, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/AbstractRegionAccessStrategyTest.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/collection/CollectionRegionAccessStrategyTest.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/EntityCollectionInvalidationTest.java, lock/src/test/java/org/infinispan/lock/impl/lock/RequestExpirationSchedulerTest.java, persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeSynchronizerTest.java, pom.xml, server/runtime/pom.xml
Dependencies
* jboss-parent 39
* jboss-logging 3.4.3.Final
* jboss-logging-processor 2.2.1.Final
* junit 4.13.2
* mockito 4.3.1
https://issues.redhat.com/browse/ISPN-13978
While looking at downstream reports, found some divergences between versions of Infinispan and protostream, infinispan-quarkus and wildfly. I've updated some of them. :crossed_fingers:
=> ISPN-13978 Align dependencies between projects

build/bom/pom.xml, documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc, server/runtime/src/main/java/org/infinispan/server/Bootstrap.java, server/runtime/src/main/java/org/infinispan/server/Server.java, server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java, server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointsConfiguration.java, server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointsConfigurationBuilder.java, server/runtime/src/main/java/org/infinispan/server/loader/LogManager.java, server/runtime/src/main/java/org/infinispan/server/loader/ServerLoginModule.java, server/runtime/src/main/java/org/infinispan/server/logging/Log.java, server/runtime/src/main/java/org/infinispan/server/security/ElytronJMXAuthenticator.java, server/runtime/src/main/server/bin/common.sh, server/runtime/src/main/server/bin/server-jaas.config, server/runtime/src/main/server/bin/server.sh, server/testdriver/core/pom.xml
https://issues.redhat.com/browse/ISPN-13979
=> ISPN-13979 Simple JMX remoting

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SslTest.java
https://issues.redhat.com/browse/ISPN-13922
=> ISPN-13922 Fix SslTest on Windows

core/src/test/java/org/infinispan/util/AbstractControlledLocalTopologyManager.java, core/src/test/java/org/infinispan/util/BlockingLocalTopologyManager.java
https://issues.redhat.com/browse/ISPN-13990
=> ISPN-13990 Do not block threads in BlockingLocalTopologyManager

documentation/src/main/asciidoc/topics/yaml/infinispan_authz_custom_roles.yaml, documentation/src/main/asciidoc/topics/yaml/server_client_certificate_authz.yaml
https://issues.redhat.com/browse/ISPN-13976
=> [13.0.x]ISPN-13976 fix indentation in sec roles examples

core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java, query/src/main/java/org/infinispan/query/impl/LifecycleManager.java, query/src/test/java/org/infinispan/query/encoding/ProtobufEncodedIndexedCacheTest.java, query/src/test/java/org/infinispan/query/model/Game.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java
https://issues.redhat.com/browse/ISPN-13923
=> ISPN-13923 Support embedded query with Protobuf-encoded caches

server/tests/src/test/java/org/infinispan/server/persistence/TableManipulation.java
https://issues.redhat.com/browse/ISPN-13993
=> Fix server/tests persistence - MySQL table name

etc/log4j2.xml
* Do not log  network traffic in docker
=> Reduce logging verbosity for dockerjava

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14001
=> ISPN-14001 Update console 14.0.0.Dev04

client/rest-client/src/main/java/org/infinispan/client/rest/RestSchemaClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestSchemasClientOkHttp.java, documentation/src/main/asciidoc/topics/json/rest_protobuf_types_response.json, documentation/src/main/asciidoc/topics/ref_rest_protobuf.adoc, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java, server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java, server/rest/src/main/java/org/infinispan/rest/resources/ProtobufResource.java, server/rest/src/test/java/org/infinispan/rest/resources/ProtobufResourceTest.java
https://issues.redhat.com/browse/ISPN-12785
=> ISPN-12785 List protobuf types in the REST API

documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc, query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java, query/src/test/java/org/infinispan/query/startup/IndexStartupModeTest.java
https://issues.redhat.com/browse/ISPN-14003
=> ISPN-14003 Document differences between the purge and reindex

client/hotrod/src/main/java/org/infinispan/hotrod/impl/cache/RemoteCacheImpl.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/GetAndRemoveOperation.java
https://issues.redhat.com/browse/ISPN-14005
=> ISPN-14005 Add some non performant implementations

build/configuration/pom.xml, pom.xml
found in https://issues.sonatype.org/browse/OSSRH-26970
=> Disable autoReleaseAfterClose to possibly workaround issue

server/core/src/main/java/org/infinispan/server/core/telemetry/TelemetryServiceFactory.java
Follow up of https://issues.redhat.com/browse/ISPN-13725
=> ISPN-13725 Disable any metrics export from server

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14022
=> ISPN-14022 Upgrade log4j to 2.18.0

documentation/src/main/asciidoc/topics/con_hotrod_client_intelligence.adoc
JIRA: https://issues.redhat.com/browse/ISPN-13248
Backport: https://github.com/infinispan/infinispan/pull/10200
=> ISPN-13248

server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
https://issues.redhat.com/browse/ISPN-14025
=> ISPN-14025 WARN ISPN000287 thrown when consuming container events

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/ProtocolVersion.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/AuthMechListOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/AuthOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/NeutralVersionHotRodOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/PingOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/PingResponse.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec40.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, server/tests/src/test/java/org/infinispan/server/functional/VersionsInteropTest.java
https://issues.redhat.com/browse/ISPN-14018
In order to keep to support the handshake with 3.x clients
=> ISPN-13725 Use safe codec version for ping operations

core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/main/resources/default-configs/default-jgroups-udp.xml, core/src/test/java/org/infinispan/stress/LargeCluster2StressTest.java, core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java, core/src/test/java/org/infinispan/test/fwk/TcpMPingEnvironmentTest.java, core/src/test/resources/configs/all/10.0.xml, core/src/test/resources/configs/all/10.1.xml, core/src/test/resources/configs/all/11.0.xml, core/src/test/resources/configs/all/12.0.xml, core/src/test/resources/configs/all/12.1.xml, core/src/test/resources/configs/all/13.0.xml, core/src/test/resources/configs/all/14.0.xml, core/src/test/resources/configs/config-with-jgroups-stack.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/tcp_mping/tcp1.xml, core/src/test/resources/stacks/tcp_mping/tcp2.xml, core/src/test/resources/stacks/udp.xml, documentation/src/main/asciidoc/topics/ref_jgroups_system_properties.adoc, documentation/src/main/asciidoc/topics/xml/jgroups_custom_udp.xml, documentation/src/main/asciidoc/topics/xml/jgroups_inline_stack.xml, documentation/src/main/asciidoc/topics/xml/mping.xml, server/testdriver/junit5/src/test/resources/jgroups/xsite-stacks.xml, server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml, tools/src/test/resources/udp.xml
https://issues.redhat.com/browse/ISPN-14033
=> ISPN-14033 Change multicast address to private network

build/configuration/pom.xml, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsRaftManager.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsStateMachineAdapter.java
https://issues.redhat.com/browse/ISPN-13984
=> ISPN-13984 Upgrade JGroups to 5.2.4.Final and Raft to 1.0.10.Final

cli/src/main/java/org/infinispan/cli/Context.java, cli/src/main/java/org/infinispan/cli/commands/CLI.java, cli/src/main/java/org/infinispan/cli/commands/Connect.java, cli/src/main/java/org/infinispan/cli/commands/kubernetes/Shell.java, cli/src/main/java/org/infinispan/cli/logging/Messages.java, cli/src/main/resources/help/config.adoc, cli/src/main/resources/help/connect.adoc, documentation/src/main/asciidoc/topics/proc_cli_configuring_tls_properties.adoc, server/tests/src/test/java/org/infinispan/server/cli/CliCertIT.java
https://issues.redhat.com/browse/ISPN-13999
=> ISPN-13999 CLI client certificate

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14041
=> ISPN-14041 Upgrade Protostream to 4.5.0.Dev05

build/configuration/pom.xml, pom.xml
https://issues.redhat.com/browse/ISPN-14042
=> ISPN-14042 Upgrade to WildFly Elytron 1.20.0.Final

core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/persistence/PersistenceManagerAvailabilityTest.java, core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/impl/BaseJdbcStore.java
https://issues.redhat.com/browse/ISPN-13863
=> ISPN-13863 PersistenceManager availability check permanently fails with uncaught exception

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14053
=> ISPN-14053 Upgrade WildFly OpenSSL 2.2.5.Final

build/component-processor/src/main/java/org/infinispan/component/processor/Generator.java, build/component-processor/src/main/java/org/infinispan/component/processor/external/JGroupsComponentProcessor.java, pom.xml, spring/spring-boot/remote/pom.xml, spring/spring5/spring5-embedded/pom.xml
https://issues.redhat.com/browse/ISPN-14038
=> ISPN-14038 Use javax.annotation.processing.Generated

build/configuration/pom.xml, cli/pom.xml, pom.xml
https://issues.redhat.com/browse/ISPN-14058
=> ISPN-14058 Aesh Readline 2.3

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14065
=> ISPN-14065 Upgrade JGroups to 5.2.5.Final

server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/RespDetector.java
https://issues.redhat.com/browse/ISPN-14063
https://issues.redhat.com/browse/ISPN-14064
https://issues.redhat.com/browse/ISPN-14066
=> Various RESP bugs encountered

core/src/main/resources/default-configs/default-jgroups-azure.xml, core/src/main/resources/default-configs/default-jgroups-ec2.xml, core/src/main/resources/default-configs/default-jgroups-google.xml, core/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/main/resources/default-configs/default-jgroups-udp.xml, documentation/src/main/asciidoc/topics/ref_jgroups_system_properties.adoc
* Use the JGroups default value.
* Added new property to configure them without having to create a custom
stack.
https://issues.redhat.com/browse/ISPN-14056
@infinispan/docs if you have time, pls review the changes in `ref_jgroups_system_properties.adoc` :+1: 
Thanks!
=> ISPN-14056 Increase default frag and bundle size

server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/JBossLoggingConsumer.java, server/tests/src/test/resources/log/log4j2-trace.xml
https://issues.redhat.com/browse/ISPN-13970
https://issues.redhat.com/browse/ISPN-14031
=> ISPN-14031 Create a logger category for container tests

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14078
=> ISPN-14078 Upgrade to Elytron 1.20.1.Final

integrationtests/server-integration/wildfly-modules/src/test/resources/as-config/standalone/configuration/standalone-test.xml
https://issues.redhat.com/browse/ISPN-14074
Needed to update the configuration. This update in the configuration was generated via a script.
=> ISPN-14074 integrationtests/server-integration are broken with JDK17

core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
https://issues.redhat.com/browse/ISPN-14071
=> ISPN-14071 Start defined caches in a determinstic order

server/runtime/src/main/java/org/infinispan/server/SecurityActions.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/KeyStoreConfiguration.java
https://issues.redhat.com/browse/ISPN-13737
=> ISPN-13737 Fallback to default provider when obtaining KeyManagerFactory

documentation/src/main/asciidoc/stories/assembly_configuring_statistics_jmx.adoc, documentation/src/main/asciidoc/topics/proc_exporting_metrics_state_transfer.adoc
Jira: https://issues.redhat.com/browse/ISPN-13992
=> ISPN-13992-a: Document cache rebalancing metrics

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14106
=> ISPN-14106 Netty 4.1.80.Final

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14099
=> ISPN-14099 Bump JGroups to 5.2.6.Final

server/runtime/src/main/server/bin/common.sh
https://issues.redhat.com/browse/ISPN-14102
=> ISPN-14102 JVM GC Logs never set on the server

documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc
https://issues.redhat.com/browse/ISPN-14028
needs backport to 13 and 12
=> ISPN-14028 docs updates to remote jmx connections

core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/EntryHeader.java, core/src/main/java/org/infinispan/persistence/sifs/EntryInfo.java, core/src/main/java/org/infinispan/persistence/sifs/EntryRecord.java, core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java, core/src/main/java/org/infinispan/persistence/sifs/IndexRequest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java
* Make sure numRecords is always updated
* Drop index has previous file to ensure count update
* Added more logging around visibility of which key is which for the
index messages
https://issues.redhat.com/browse/ISPN-14104
=> ISPN-14104 SoftIndexFileStore - Compactor.compactSingleFile - NPE

documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc
=> [13.0.x]ISPN-14028 docs updates to remote jmx connections

query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java, query/src/test/java/org/infinispan/query/api/PutAllTest.java
https://issues.redhat.com/browse/ISPN-14115
Backport to 13.0.x of https://github.com/infinispan/infinispan/pull/10292
=> [13.0.x] ISPN-14115 Potential deadlock in index writer threads under heavy load

cli/src/main/java/org/infinispan/cli/commands/rest/Index.java
https://issues.redhat.com/browse/ISPN-13648
=> ISPN-13648 Add update-schema to index CLI command

core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java, core/src/test/java/org/infinispan/test/data/Person.java, persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/TwoWayPersonKey2StringMapper.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcJoinTest.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcStoreFunctionalTest.java
https://issues.redhat.com/browse/ISPN-13515
https://issues.redhat.com/browse/ISPN-13516
=> [13.0.x] SQL Store backports

pom.xml
https://issues.redhat.com/browse/ISPN-14139
=> ISPN-14139 Upgrade SnakeYAML to 1.31

build/configuration/pom.xml, cdi/common-jakarta/pom.xml, cdi/embedded-jakarta/pom.xml, cdi/remote-jakarta/pom.xml, client/hotrod-client-jakarta/pom.xml, client/hotrod-jakarta/pom.xml, commons/all-jakarta/pom.xml, core-jakarta/pom.xml, core/pom.xml, extended-statistics/pom.xml, persistence/jdbc-common-jakarta/pom.xml, persistence/jdbc-jakarta/pom.xml, pom.xml, query-jakarta/pom.xml, server/hotrod-jakarta/pom.xml, server/tests/pom.xml, tools-jakarta/pom.xml
https://issues.redhat.com/browse/ISPN-14079
=> ISPN-14079 Attach sources and javadoc to Jakarta artifacts

core/src/main/resources/default-configs/default-jgroups-azure.xml, core/src/main/resources/default-configs/default-jgroups-ec2.xml, core/src/main/resources/default-configs/default-jgroups-google.xml, core/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/main/resources/default-configs/default-jgroups-udp.xml
https://issues.redhat.com/browse/ISPN-14141
=> ISPN-14141 FD_ALL3: use default timeout

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14133
=> ISPN-14133 Netty 4.1.81.Final

commons-test/src/main/java/org/infinispan/commons/test/annotation/TestForIssue.java, query/src/test/java/org/infinispan/query/api/PutAllTest.java
https://issues.redhat.com/browse/ISPN-14116
=> ISPN-14116 Create @TestForIssue annotation for the project

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14147
=> ISPN-14147 Console updated to 14.0.0.CR2

pom.xml, query/pom.xml, server/runtime/pom.xml
https://issues.redhat.com/browse/ISPN-14146
=> ISPN-14146 Exclude HdrHistogram from LatencyUtils

build/configuration/pom.xml, pom.xml
https://issues.redhat.com/browse/ISPN-14149
=> ISPN-14149 Set maven-deploy-plugin version to 3.0.0

commons/all/src/main/java/org/infinispan/commons/marshall/ProtoStreamTypeIds.java, core/src/main/java/org/infinispan/manager/impl/AllClusterExecutor.java, core/src/main/java/org/infinispan/manager/impl/ReplicableManagerFunctionCommand.java, core/src/main/java/org/infinispan/manager/impl/SingleClusterExecutor.java, core/src/main/java/org/infinispan/marshall/persistence/impl/PersistenceContextInitializer.java, core/src/main/java/org/infinispan/security/impl/SubjectAdapter.java, core/src/test/java/org/infinispan/security/BaseAuthorizationTest.java, core/src/test/java/org/infinispan/security/ClusteredSecureCacheTest.java, core/src/test/java/org/infinispan/test/TestingUtil.java, server/runtime/src/main/java/org/infinispan/server/tasks/SecurityActions.java, server/runtime/src/main/java/org/infinispan/server/tasks/ServerTaskEngine.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationCertIT.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationLDAPIT.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationPropertiesIT.java
https://issues.redhat.com/browse/ISPN-14143
https://issues.redhat.com/browse/ISPN-14144
=> ISPN-14143 + ISPN-14144 Task authorization 

server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespChannelInitializer.java, server/resp/src/main/java/org/infinispan/server/resp/RespLettuceHandler.java, server/resp/src/test/java/org/infinispan/server/resp/RespAuthSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/test/RespTestingUtil.java
https://issues.redhat.com/browse/ISPN-14151
=> ISPN-14151 Create an auth handler for RESP

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14153
=> ISPN-14153 Upgrade RxJava to 3.1.4

build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14135
=> [13.0] ISPN-14135 Protostream 4.4.4.Final

core/src/main/resources/default-configs/default-jgroups-azure.xml, core/src/main/resources/default-configs/default-jgroups-ec2.xml, core/src/main/resources/default-configs/default-jgroups-google.xml, core/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/main/resources/default-configs/default-jgroups-udp.xml
https://issues.redhat.com/browse/ISPN-14157
=> ISPN-14157 Tune UFC and MFC max credits

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14160
=> ISPN-14160 Upgrade Kafka client to version 3.2.3

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14165 
Do not close the jira
=> ISPN-14165 Downgrade surefire to 3.0.0-M5

integrationtests/server-integration/third-party-server/pom.xml, integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml, integrationtests/server-integration/third-party-server/src/test/resources/wildfly/standalone-test.xml
https://issues.redhat.com/browse/ISPN-14074
=> ISPN-14074 Use JDK17-compatible config for WildFly integration tests

core/src/main/java/org/infinispan/cache/impl/CacheImpl.java, core/src/test/java/org/infinispan/statetransfer/StateTransferFunctionalTest.java
https://issues.redhat.com/browse/ISPN-13461
=> ISPN-13461 Cache should stop if the initial state transfer times out

build/bom/pom.xml, server/hotrod-jakarta/pom.xml
https://issues.redhat.com/browse/ISPN-14174
=> ISPN-14174 Add missing modules to Infinispan bom

build/configuration/pom.xml, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/JsonKeyValueRawEventsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/transcoding/DataFormatTest.java, spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheTest.java
https://issues.redhat.com/browse/ISPN-14176
=> ISPN-14176 Protostream 4.5.0.Final

server/rest/src/test/java/org/infinispan/rest/assertion/ResponseAssertion.java
I don't know if we need to open an issue just for this very small change
=> Expose the error/cause messages in case of error

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14177
=> ISPN-14177 Netty 4.1.82.Final

server/runtime/src/main/java/org/infinispan/server/Bootstrap.java, server/runtime/src/main/java/org/infinispan/server/BootstrapLogging.java
https://issues.redhat.com/browse/ISPN-14179
=> ISPN-14179 Update for Infinispan Quarkus

server/runtime/src/main/server/bin/common.sh
https://issues.redhat.com/browse/ISPN-14158
=> ISPN-14158 Add --enable-preview when running on JDK 19

documentation/src/main/asciidoc/topics/json/server_client_certificate_authn.json, documentation/src/main/asciidoc/topics/json/server_distributed_realm.json, documentation/src/main/asciidoc/topics/json/server_identities_kerberos.json, documentation/src/main/asciidoc/topics/json/server_ldap_realm.json, documentation/src/main/asciidoc/topics/json/server_ldap_realm_rewriter.json, documentation/src/main/asciidoc/topics/json/server_multiple_property_realms.json, documentation/src/main/asciidoc/topics/json/server_ssl_identity_generated.json, documentation/src/main/asciidoc/topics/json/server_token_realm_oauth.json, documentation/src/main/asciidoc/topics/json/server_truststore_realm.json, documentation/src/main/asciidoc/topics/proc_creating_server_security_realms.adoc, documentation/src/main/asciidoc/topics/xml/server_client_certificate_authn.xml, documentation/src/main/asciidoc/topics/xml/server_distributed_realm.xml, documentation/src/main/asciidoc/topics/xml/server_identities_kerberos.xml, documentation/src/main/asciidoc/topics/xml/server_ldap_realm.xml, documentation/src/main/asciidoc/topics/xml/server_ldap_realm_rewriter.xml, documentation/src/main/asciidoc/topics/xml/server_multiple_property_realms.xml, documentation/src/main/asciidoc/topics/xml/server_ssl_identity_generated.xml, documentation/src/main/asciidoc/topics/xml/server_token_realm_oauth.xml, documentation/src/main/asciidoc/topics/xml/server_truststore_realm.xml, documentation/src/main/asciidoc/topics/yaml/server_client_certificate_authn.yaml, documentation/src/main/asciidoc/topics/yaml/server_distributed_realm.yaml, documentation/src/main/asciidoc/topics/yaml/server_identities_kerberos.yaml, documentation/src/main/asciidoc/topics/yaml/server_ldap_realm.yaml, documentation/src/main/asciidoc/topics/yaml/server_ldap_realm_rewriter.yaml, documentation/src/main/asciidoc/topics/yaml/server_multiple_property_realms.yaml, documentation/src/main/asciidoc/topics/yaml/server_ssl_identity_generated.yaml, documentation/src/main/asciidoc/topics/yaml/server_token_realm_oauth.yaml, documentation/src/main/asciidoc/topics/yaml/server_truststore_realm.yaml
JIRA: https://issues.redhat.com/browse/ISPN-13975
=> ISPN-13975: Update property realm note in Security realms doc

core/src/main/java/org/infinispan/cache/impl/CacheImpl.java, core/src/test/java/org/infinispan/statetransfer/StateTransferFunctionalTest.java
https://issues.redhat.com/browse/ISPN-13461
=> [11.0.x] ISPN-13461 Cache should stop if the initial state transfer times out

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14180
=> ISPN-14180 Update console to 14.0.0.Final release

hibernate/cache-v60/pom.xml
https://issues.redhat.com/browse/ISPN-14181
=> ISPN-14181 Use jakarta.transaction 2.0.1 in hibernate cache 6

documentation/src/main/asciidoc/topics/dependencies_maven/protostream-processor.xml
https://issues.redhat.com/browse/ISPN-14188
=> ISPN-14188 Add the missing <scope>import</scope> description in the documentation

server/core/src/main/java/org/infinispan/server/core/transport/NettyTransportConnectionStats.java
* Part 2
https://issues.redhat.com/browse/ISPN-14190
=> ISPN-14190 NullPointerException when computing Netty global connections

core/src/main/java/org/infinispan/configuration/global/AllowListConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/parsing/Attribute.java, core/src/main/java/org/infinispan/configuration/parsing/Parser.java, core/src/test/java/org/infinispan/configuration/JsonParsingTest.java, core/src/test/java/org/infinispan/configuration/YamlParsingTest.java, core/src/test/resources/configs/serialization-test.json, core/src/test/resources/configs/serialization-test.yaml
https://issues.redhat.com/browse/ISPN-14196
=> ISPN-14196 Correctly parse serialization allow list in YAML and JSON

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/Essay.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/test/PoemTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/size/HugeProtobufMessageTest.java
https://issues.redhat.com/browse/ISPN-14183
This very use case already works with the recent Infinispan versions. Thus we're adding only the test and no changes are required on the main code.
=> ISPN-14183 Test protobuf message having size > 64M

commons/all/src/test/java/org/infinispan/commons/time/ControlledTimeService.java, core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/EntryRecord.java, core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFileStatsTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFunctionalTest.java, core/src/test/java/org/infinispan/util/concurrent/BlockingManagerTestUtil.java
* Unset schedule flag when completing file - set from expiration
* Make sure nextExpirationTime is set properly if stats already exist
https://issues.redhat.com/browse/ISPN-14187
=> ISPN-14187 SoftIndexFileStore not removing log files with expiration

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14206
=> ISPN-14206 Update console to 14.0.1.Final

build-configuration/pom.xml, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/Essay.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/EssayMarshaller.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/size/HugeProtobufMessageTest.java
https://issues.redhat.com/browse/ISPN-14183
=> [9.4] ISPN-14183 Support protobuf message having size > 64M

server/core/src/main/java/org/infinispan/server/core/transport/NettyTransport.java
https://issues.redhat.com/browse/ISPN-14221
=> ISPN-14221 Expose the number of io-thread for endpoints

documentation/src/main/asciidoc/topics/ref_endpoints_authentication_mechanisms.adoc
JIRA: https://issues.redhat.com/browse/ISPN-14072
=> ISPN-14072: Document incompatible mechanisms with LDAP realms

commons/all/src/test/java/org/infinispan/commons/time/ControlledTimeService.java, core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/EntryRecord.java, core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFileStatsTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFunctionalTest.java, core/src/test/java/org/infinispan/util/concurrent/BlockingManagerTestUtil.java
* Unset schedule flag when completing file - set from expiration
* Make sure nextExpirationTime is set properly if stats already exist
https://issues.redhat.com/browse/ISPN-14187
=> [13.0] ISPN-14187 SoftIndexFileStore not removing log files with expiration

core/src/main/java/org/infinispan/cache/impl/CacheImpl.java, core/src/test/java/org/infinispan/statetransfer/StateTransferFunctionalTest.java
https://issues.redhat.com/browse/ISPN-13461
=> [13.0] ISPN-13461 Cache should stop if the initial state transfer times out

commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReader.java, commons/all/src/test/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReaderTest.java, commons/all/src/test/resources/yaml.yaml
https://issues.redhat.com/browse/ISPN-14226
=> ISPN-14226 Respect Yaml line breaks

server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoder.java
* concurrent operation may send the responses out of order
https://issues.redhat.com/browse/ISPN-14238
=> ISPN-14238 Memcached server: corrupted response

server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoder.java
* concurrent operation may send the responses out of order
https://issues.redhat.com/browse/ISPN-14238
=> [14.0] ISPN-14238 Memcached server: corrupted response

server/rest/src/main/java/org/infinispan/rest/ALPNHandler.java, server/runtime/src/main/java/org/infinispan/server/security/HttpServerRequestAdapter.java, server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
https://issues.redhat.com/browse/ISPN-14240
=> ISPN-14240 Use parent channel to obtain SslHandler when using HTTP/2

server/rest/src/main/java/org/infinispan/rest/ALPNHandler.java, server/runtime/src/main/java/org/infinispan/server/security/HttpServerRequestAdapter.java, server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
https://issues.redhat.com/browse/ISPN-14240
=> [14.0] ISPN-14240 Use parent channel to obtain SslHandler when using HTTP/2

server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanXSiteServerTestMethodRule.java, server/testdriver/junit5/src/test/java/org/infinispan/server/test/junit5/InfinispanXSiteServerTest.java, server/tests/src/test/java/org/infinispan/server/cli/XSiteCliOperations.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteHotRodCacheOperations.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteRestCacheOperations.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteRestMetricsOperations.java
https://issues.redhat.com/browse/ISPN-14204
=> ISPN-14204 Standardize NYC and LON for XSite tests

cli/pom.xml, cli/src/main/java/org/infinispan/cli/commands/kubernetes/Kube.java, cli/src/main/java/org/infinispan/cli/util/Utils.java, commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReader.java, commons/all/src/test/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReaderTest.java, commons/all/src/test/resources/identities.yaml, pom.xml, server/rest/pom.xml, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14247
=> ISPN-14247 Drop snakeyaml dependency from the CLI

cli/pom.xml, cli/src/main/java/org/infinispan/cli/commands/kubernetes/Kube.java, cli/src/main/java/org/infinispan/cli/util/Utils.java, commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReader.java, commons/all/src/test/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReaderTest.java, commons/all/src/test/resources/identities.yaml, pom.xml, server/rest/pom.xml, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14247
=> [14.0] ISPN-14247 Drop snakeyaml dependency from everywhere

server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/RestTestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanGenericContainer.java
https://issues.redhat.com/browse/ISPN-14205
=> ISPN-14205 InfinispanGenericContainer::getNetworkIpAddress fail fast if container is not running

documentation/src/main/asciidoc/stories/assembly_deployment_planning.adoc, documentation/src/main/asciidoc/topics/con_performance_metric_considerations.adoc
JIRA: https://issues.redhat.com/browse/ISPN-14213
=> ISPN-14213: Add a statement why we provide no performance numbers

cli/src/main/java/org/infinispan/cli/commands/Batch.java
https://issues.redhat.com/browse/ISPN-14259
=> ISPN-14259 Support benchmark CLI as a batch command

documentation/src/main/asciidoc/stories/assembly_deployment_planning.adoc, documentation/src/main/asciidoc/topics/con_performance_metric_considerations.adoc
ISPN: https://issues.redhat.com/browse/ISPN-14257
Backport for https://github.com/infinispan/infinispan/pull/10380
=> [13.0.x] ISPN-14257: Add a statement why we provide no performance numbers

commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationWriter.java, core/src/test/java/org/infinispan/util/EventLogSerializerTest.java, documentation/src/main/asciidoc/topics/json/rest_full_cache_detail.json, documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/main/java/org/infinispan/rest/resources/ClusterResource.java, server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java, server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java, server/rest/src/main/java/org/infinispan/rest/resources/LoggingResource.java, server/rest/src/main/java/org/infinispan/rest/resources/ProtobufResource.java, server/rest/src/main/java/org/infinispan/rest/resources/ResourceUtil.java, server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java, server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java, server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java, server/rest/src/main/java/org/infinispan/rest/resources/TasksResource.java, server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
https://issues.redhat.com/browse/ISPN-14244
Still need to document the `pretty` API parameter
=> ISPN-14244 Don't pretty print by default

documentation/src/main/asciidoc/topics/ref_rest_servers.adoc
https://issues.redhat.com/browse/ISPN-14267
=> ISPN-14267 fix duplicated id

documentation/src/main/asciidoc/topics/ref_rest_servers.adoc
#10418 
https://issues.redhat.com/browse/ISPN-14267
=> ISPN-14267 fix duplicated id 

cli/src/main/java/org/infinispan/cli/commands/CLI.java, cli/src/main/java/org/infinispan/cli/commands/Run.java, cli/src/main/java/org/infinispan/cli/commands/kubernetes/Shell.java, cli/src/main/java/org/infinispan/cli/impl/CliShell.java, cli/src/main/java/org/infinispan/cli/impl/KubeShell.java, cli/src/main/java/org/infinispan/cli/impl/StreamShell.java, cli/src/main/java/org/infinispan/cli/logging/Messages.java, cli/src/test/java/org/infinispan/cli/CliPipeTest.java
https://issues.redhat.com/browse/ISPN-14256
=> ISPN-14256 CLI should work with piped input

documentation/src/main/asciidoc/titles/embedding/stories.adoc, documentation/src/main/asciidoc/topics/proc_cli_statistics.adoc, documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc
add assembly_authorization_embedded.adoc in embedded doc
fix formatting in the server doc
=> ISPN-14267 docs fixes

persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
https://issues.redhat.com/browse/ISPN-14210
=> ISPN-14210 Stores that do not return the EXPIRATION Characteristic should not allow expiration

documentation/src/main/asciidoc/stories/assembly_deployment_planning.adoc
JIRA: https://issues.redhat.com/browse/ISPN-14213
=> ISPN-14213-fix-filename: Fix filename for con_performance_metrics_considerations

documentation/src/main/asciidoc/topics/proc_cli_statistics.adoc, documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc
fixes formatting in the server doc
=> [14.0.x]ISPN-14267 fixes to formatting in the server doc

documentation/src/main/asciidoc/topics/json/distributed_cache.json, documentation/src/main/asciidoc/topics/json/replicated_cache.json, documentation/src/main/asciidoc/topics/proc_creating_caches_cli.adoc, documentation/src/main/asciidoc/topics/ref_cli_resource_tree.adoc, documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc, documentation/src/main/asciidoc/topics/ref_listeners_synchronicity.adoc, documentation/src/main/asciidoc/topics/xml/distributed_cache.xml, documentation/src/main/asciidoc/topics/xml/replicated_cache.xml, documentation/src/main/asciidoc/topics/yaml/distributed_cache.yaml, documentation/src/main/asciidoc/topics/yaml/replicated_cache.yaml
https://issues.redhat.com/browse/ISPN-14273
needs backport to 14.0.x
- Fixes docs errors
- updates config examples for distributed and replicated caches
=> ISPN-14273 fixes docs errors and config examples in the CLI guide

documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_query.adoc, documentation/src/main/asciidoc/topics/protobuf/person-db-table.proto, documentation/src/main/asciidoc/topics/ref_sql_store_query_configuration.adoc, documentation/src/main/asciidoc/topics/sql/person.sql, documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
https://issues.redhat.com/browse/ISPN-14278
Updates examples in the sql store docs
Based on feedback from @gustavolira
Backports #10434
=> [14.0.x]ISPN-14278 fix erros in the SQL store examples

documentation/src/main/asciidoc/topics/yaml/server_ldap_realm.yaml
https://issues.redhat.com/browse/ISPN-14290 
Remove apostrophe from the ldap config example
Backports #10441
=> [13.0.x]ISPN-14290 fix ldap yaml config example

documentation/src/main/asciidoc/topics/yaml/server_ldap_realm.yaml
https://issues.redhat.com/browse/ISPN-14290
Remove apostrophe from the ldap config example
Backports #10441
=> [14.0.x]ISPN-14290 fix ldap yaml config example

server/testdriver/junit5/src/test/resources/jgroups/xsite-stacks.xml, server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml
https://issues.redhat.com/browse/ISPN-14313
=> ISPN-14313 Set different properties and port for cross-site testdriver

etc/log4j2-trace.xml, etc/log4j2.xml
https://issues.redhat.com/browse/log_abbreviated_packages
=> ISPN-14296 Use abbreviated package names in test logs

documentation/src/main/asciidoc/topics/con_jvm_heap_memory_allocation.adoc
Jira: https://issues.redhat.com/browse/ISPN-14024
=> ISPN-14024: Expand upon JVM heap space allocation content

client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationBuilder.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestServer.java, server/tests/src/test/java/org/infinispan/server/functional/AbstractMultiClusterIT.java, server/tests/src/test/java/org/infinispan/server/security/AuthenticationKerberosIT.java, server/tests/src/test/java/org/infinispan/server/security/authentication/RespAuthentication.java, server/tests/src/test/java/org/infinispan/server/security/authentication/RestAuthentication.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationKerberosIT.java
https://issues.redhat.com/browse/ISPN-14319
=> ISPN-14319 Use InetSocketAddress.getHostString() instead of .getHostName()

documentation/src/main/asciidoc/topics/con_jvm_heap_memory_allocation.adoc
https://issues.redhat.com/browse/ISPN-14024
=> ISPN-14024-14:Expand upon JVM heap space allocation content

core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/test/java/org/infinispan/stats/ClusteredStatsTest.java
https://issues.redhat.com/browse/ISPN-14279
=> ISPN-14279 "Divide by 0"-Exception on Cache.getStats()

commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationWriter.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14315
=> ISPN-14315 ConfigurationWriter should ignore media type parameters

server/rest/src/main/java/org/infinispan/rest/resources/BackupManagerResource.java
https://issues.redhat.com/browse/ISPN-14317
=> ISPN-14317 Server Backup creation should work even without JSON content

server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-14316
=> ISPN-14316 Correctly pass arguments to report script

server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
https://issues.redhat.com/browse/ISPN-14256
=> ISPN-14256 Fix the CLI batch test

documentation/src/main/asciidoc/topics/proc_cli_batching_interactive.adoc, documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc, documentation/src/main/asciidoc/topics/upgrading.adoc, documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
https://issues.redhat.com/browse/ISPN-14324 address multiple docs issues that were discovered during QE review
Update pom.xml about Jakarta EE dependencies in the upgrading doc
Update SQL store example
Temporarily remove pipe command form the CLI quide
specify that controlRole and monitorRole are jmx roles
backports #10463
=> [14.0.x] ISPN-14324 docs updates and fixes

documentation/src/main/asciidoc/topics/proc_cli_batching_interactive.adoc, documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc, documentation/src/main/asciidoc/topics/upgrading.adoc, documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
https://issues.redhat.com/browse/ISPN-14324 address multiple docs issues that were discovered during QE review
- Update pom.xml about Jakarta EE dependencies in the upgrading doc
- Update SQL store example
- Temporarily remove pipe command form the CLI quide
- specify that controlRole and monitorRole are jmx roles
=> ISPN-14324 docs updates

core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/test/java/org/infinispan/stats/ClusteredStatsTest.java
https://issues.redhat.com/browse/ISPN-14279
=> [14.0] ISPN-14279 "Divide by 0"-Exception on Cache.getStats()

documentation/src/main/asciidoc/topics/ref_tech_preview.adoc
https://issues.redhat.com/browse/ISPN-14331
need to add tech preview module to the topics/
downstream only
=> [14.0.x]ISPN-14331 add tech preview module

server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-14328
=> ISPN-14328 Server DEBUG logs should pretty print configuration

server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-14328
=> [14.0.x] ISPN-14328 Server DEBUG logs should pretty print configuration

documentation/src/main/asciidoc/topics/code_examples/GlobalAuthorizationConfiguration.java, documentation/src/main/asciidoc/topics/code_examples/MutableRolePermissionMapper.java, documentation/src/main/asciidoc/topics/proc_adding_authorization_roles.adoc, documentation/src/main/asciidoc/topics/proc_configuring_authorization_embedded.adoc, documentation/src/main/asciidoc/topics/proc_executing_secure_caches.adoc
https://issues.redhat.com/browse/ISPN-14333
Fixes code snippets in the embedded doc.
Needs backport to 14.0.x
=> ISPN-14333 fix code snippets in the embedded doc

documentation/src/main/asciidoc/topics/code_examples/GlobalAuthorizationConfiguration.java, documentation/src/main/asciidoc/topics/code_examples/MutableRolePermissionMapper.java, documentation/src/main/asciidoc/topics/proc_adding_authorization_roles.adoc, documentation/src/main/asciidoc/topics/proc_configuring_authorization_embedded.adoc, documentation/src/main/asciidoc/topics/proc_executing_secure_caches.adoc
https://issues.redhat.com/browse/ISPN-14333
Fixes code snippets in the embedded doc.
Backports #10477
=> [14.0.x] ISPN-14333 fix code snippets in the embedded doc

build-configuration/pom.xml, pom.xml, server/rest/pom.xml, server/router/pom.xml
https://issues.redhat.com/browse/ISPN-14053
=> [13.0] ISPN-14053 Use WildFly OpenSSL 2.2.5

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14343
=> ISPN-14343 Jackson 2.14.1

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14343
=> [14.0] ISPN-14343 Jackson 2.14.1

documentation/src/main/asciidoc/topics/ref_tech_preview.adoc
https://issues.redhat.com/browse/ISPN-14331
need to add tech preview module to the topics/
downstream only
=> ISPN-14331 add tech preview module

commons/all/src/main/java/org/infinispan/commons/configuration/io/json/JsonConfigurationReader.java, commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReader.java, commons/all/src/main/java/org/infinispan/commons/dataconversion/internal/Json.java, commons/all/src/test/java/org/infinispan/commons/configuration/io/json/JsonConfigurationReaderTest.java, core/src/main/java/org/infinispan/configuration/parsing/ParserRegistry.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/configuration/parsing/JsonParsingTest.java, core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java, core/src/test/java/org/infinispan/configuration/parsing/YamlParsingTest.java, core/src/test/resources/configs/broken.json, core/src/test/resources/configs/broken.xml, core/src/test/resources/configs/broken.yaml
https://issues.redhat.com/browse/ISPN-14280
=> ISPN-14280 Correctly report JSON parsing location

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14346
=> ISPN-14346 Upgrade JGroups to 5.2.10.Final

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14346
=> [14.x] ISPN-14346 Upgrade JGroups to 5.2.10.Final

spring/spring-boot/embedded/src/main/java/org/infinispan/spring/starter/embedded/actuator/InfinispanCacheMeterBinder.java
https://issues.redhat.com/browse/ISPN-14282
=> ISPN-14282 Spring Boot actuator embedded metrics use deprecated code

build/configuration/pom.xml, pom.xml
https://issues.redhat.com/browse/ISPN-14342
=> ISPN-14342 Apache SSHD commons 2.9.2

server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointsConfigurationBuilder.java, server/runtime/src/main/java/org/infinispan/server/logging/Log.java
https://issues.redhat.com/browse/ISPN-14327
=> ISPN-14327 Allow overriding server endpoint

build/configuration/pom.xml, pom.xml
https://issues.redhat.com/browse/ISPN-14342
=> [14.0] ISPN-14342 Apache SSHD commons 2.9.2

query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java, query/src/test/java/org/infinispan/query/expiration/DistributedQueryExpiredEntitiesTest.java, server/rest/pom.xml, server/rest/src/test/java/org/infinispan/rest/expiration/DistributedQueryExpiredEntitiesTest.java
https://issues.redhat.com/browse/ISPN-14119
Backport of https://github.com/infinispan/infinispan/pull/10396 to 14.0.x branch
=> [14.0.x] ISPN-14119 Filter null from evicted entities for distributed queries

server/testdriver/junit5/src/test/resources/jgroups/xsite-stacks.xml, server/tests/src/test/resources/configuration/jgroups/authz-stacks.xml, server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml
https://issues.redhat.com/browse/ISPN-14313
=> [14.0] ISPN-14313 Set different properties and port for cross-site testdriver

server/runtime/src/main/java/org/infinispan/server/configuration/DataSourceConfiguration.java, server/runtime/src/main/resources/schema/infinispan-server-14.0.xsd
https://issues.redhat.com/browse/ISPN-14356
=> [14.0] ISPN-14356 Set default datasource max-size

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.redhat.com/browse/ISPN-14263
=> ISPN-14263 Restrict most JGroupsTransport INFO logging when using a ForkChannel.

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14365
=> ISPN-14365 Upgrade JBoss Marshalling to 2.1.1.Final

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14365
=> [14.x] ISPN-14365 Upgrade JBoss Marshalling to 2.1.1.Final

core/src/main/java/org/infinispan/marshall/core/BytesObjectOutput.java
https://issues.redhat.com/browse/ISPN-14348
=> [14.0.x] ISPN-14348 BytesObjectOutput.writeUTF performance improvements

core/src/main/java/org/infinispan/marshall/core/BytesObjectOutput.java
https://issues.redhat.com/browse/ISPN-14348
=> [13.0.x] ISPN-14348 BytesObjectOutput.writeUTF performance improvements

spring/spring-boot/embedded/src/main/java/org/infinispan/spring/starter/embedded/actuator/InfinispanCacheMeterBinder.java
https://issues.redhat.com/browse/ISPN-14282
=>  [14.x] ISPN-14282 Spring Boot actuator embedded metrics use deprecated code  

spring/spring-boot/embedded/src/main/java/org/infinispan/spring/starter/embedded/actuator/InfinispanCacheMeterBinder.java
https://issues.redhat.com/browse/ISPN-14282
=> [13.x] ISPN-14282 Spring Boot actuator embedded metrics use deprecated code

commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReader.java, commons/all/src/test/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReaderTest.java, commons/all/src/test/resources/identities.yaml, commons/all/src/test/resources/yaml.yaml
https://issues.redhat.com/browse/ISPN-14364
=> [14.0] ISPN-14364 Fix YAML parsing of maps in arrays

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.redhat.com/browse/ISPN-14263
Port of https://github.com/infinispan/infinispan/pull/10498 from main
=> [14.0.x] ISPN-14263 Restrict most JGroupsTransport INFO logging when using a ForkChannel.

build-configuration/pom.xml, pom.xml
https://issues.redhat.com/browse/ISPN-14342
=> [12.1] ISPN-14342 & ISPN-14343

build-configuration/pom.xml, pom.xml
https://issues.redhat.com/browse/ISPN-14342
=> [13.0] ISPN-14342 ISPN-14343 

server/rest/src/main/java/org/infinispan/rest/RestServer.java, server/rest/src/test/java/org/infinispan/rest/resources/StaticResourceTest.java
=> [14.x] ISPN-14376 Retrieve console on any cache detail

client/hotrod/src/main/java/org/infinispan/hotrod/HotRodMutinyCaches.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/HotRodTransport.java
https://issues.redhat.com/browse/ISPN-14016
Only adding the methods here. The backport of tests is not easy, as we have a few commits creating all the structure.
=> [14.0] ISPN-14016 Implement HotRodMutinyCaches methods

client/hotrod/src/main/java/org/infinispan/hotrod/HotRodMutinyCaches.java
https://issues.redhat.com/browse/ISPN-14016
Syncing main and 14.0.x with #10529
=> ISPN-14016 Implement HotRodMutinyCaches methods

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14391
=> [14.x] ISPN-14391 Update console version to 14.0.3.Final

core/src/main/java/org/infinispan/configuration/cache/AbstractStoreConfigurationBuilder.java, core/src/main/java/org/infinispan/marshall/persistence/impl/MarshalledEntryFactoryImpl.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/main/java/org/infinispan/persistence/spi/MarshallableEntryFactory.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/configuration/ConfigurationUnitTest.java, core/src/test/java/org/infinispan/persistence/IgnoreModificationsStoreTest.java, core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
https://issues.redhat.com/browse/ISPN-14390
=> ISPN-14390 When reading entries from read only store apply expiration

core/src/main/java/org/infinispan/configuration/cache/AbstractStoreConfigurationBuilder.java, core/src/main/java/org/infinispan/marshall/persistence/impl/MarshalledEntryFactoryImpl.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/main/java/org/infinispan/persistence/spi/MarshallableEntryFactory.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/configuration/ConfigurationUnitTest.java, core/src/test/java/org/infinispan/persistence/IgnoreModificationsStoreTest.java, core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
https://issues.redhat.com/browse/ISPN-14390
=> [14.0.x] ISPN-14390 When reading entries from read only store apply expiration

documentation/src/main/asciidoc/stories/assembly_deployment_planning.adoc, documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc, documentation/src/main/asciidoc/topics/con_performance_metric_considerations.adoc
Jira: https://issues.redhat.com/browse/JDG-5418
Original PR: https://github.com/infinispan/infinispan/pull/10380
needs backport to 14.0.x
=> ISPN-14213-re Add a statement why we provide no performance numbers

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/ServerStatistics.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodStatisticsTest.java, core/src/main/java/org/infinispan/stats/Stats.java, core/src/main/java/org/infinispan/stats/impl/CacheContainerStatsImpl.java, core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java, core/src/main/java/org/infinispan/stats/impl/StatsCollector.java, core/src/main/java/org/infinispan/stats/impl/StatsImpl.java, core/src/test/java/org/infinispan/stats/ClusteredStatsTest.java, core/src/test/java/org/infinispan/stats/SingleStatsTest.java, documentation/src/main/asciidoc/topics/json/cli_stats_cache.json, documentation/src/main/asciidoc/topics/json/cli_stats_container.json, documentation/src/main/asciidoc/topics/json/rest_cache_stats_response.json, documentation/src/main/asciidoc/topics/json/rest_full_cache_detail.json, documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc, server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodFunctionalTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodStatsClusterTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodStatsTest.java
https://issues.redhat.com/browse/ISPN-14377
=> ISPN-14377 Stats command inaccurate results

query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
https://issues.redhat.com/browse/ISPN-14406
Backport to 14.0 of #10536
=> [14.0.x] ISPN-14406 Synchronize the partial reindex with refresh and flush

build/configuration/pom.xml, integrationtests/security-it/src/test/java/org/infinispan/test/integration/security/utils/Deployments.java, pom.xml, wildfly/feature-pack/pom.xml, wildfly/feature-pack/src/main/resources/modules/org/infinispan/slot/module.xml
https://issues.redhat.com/browse/ISPN-14401
=> ISPN-14401 Protostream 4.6.0.Final

build/configuration/pom.xml, integrationtests/security-it/src/test/java/org/infinispan/test/integration/security/utils/Deployments.java, pom.xml, wildfly/feature-pack/pom.xml, wildfly/feature-pack/src/main/resources/modules/org/infinispan/slot/module.xml
https://issues.redhat.com/browse/ISPN-14401
=> [14.0] ISPN-14401 Protostream 4.6.0.Final

client/rest-client/src/main/java/org/infinispan/client/rest/RestRawClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestRawClientOkHttp.java, documentation/src/main/asciidoc/topics/ref_rest_caches.adoc, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14415
=> ISPN-14415 Cache config comparison REST API

client/rest-client/src/main/java/org/infinispan/client/rest/RestRawClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestRawClientOkHttp.java, documentation/src/main/asciidoc/topics/ref_rest_caches.adoc, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14415
=> [14.0] ISPN-14415 Cache config comparison REST API

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14421
=> ISPN-14421 Netty 4.1.86.Final

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14421
=> [14.0] ISPN-14421 Netty 4.1.86.Final

documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc, documentation/src/main/asciidoc/topics/ref_rest_caches.adoc, documentation/src/main/asciidoc/topics/ref_rest_caches_query.adoc, documentation/src/main/asciidoc/topics/ref_rest_counters.adoc, documentation/src/main/asciidoc/topics/ref_rest_data_formats.adoc, documentation/src/main/asciidoc/topics/ref_rest_rolling.adoc, documentation/src/main/asciidoc/topics/ref_rest_security.adoc, documentation/src/main/asciidoc/topics/ref_rest_servers.adoc, documentation/src/main/asciidoc/topics/ref_rest_xsite.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_principal_deny.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_principal_grant.adoc
https://issues.redhat.com/browse/ISPN-14424
Docs fixes:
- urls
- missing /rest/ in the commands
Needs backport to 14 and 13
=> ISPN-14424 fix errors in the rest commands

documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc, documentation/src/main/asciidoc/topics/ref_rest_caches.adoc, documentation/src/main/asciidoc/topics/ref_rest_caches_query.adoc, documentation/src/main/asciidoc/topics/ref_rest_counters.adoc, documentation/src/main/asciidoc/topics/ref_rest_data_formats.adoc, documentation/src/main/asciidoc/topics/ref_rest_rolling.adoc, documentation/src/main/asciidoc/topics/ref_rest_security.adoc, documentation/src/main/asciidoc/topics/ref_rest_servers.adoc, documentation/src/main/asciidoc/topics/ref_rest_xsite.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_principal_deny.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_principal_grant.adoc
https://issues.redhat.com/browse/ISPN-14424 
Docs fixes
- urls
- missing /rest/ in the commands
Needs backport 13
Backports #10551
=> [14.0.x]ISPN-14424 fix errors in the rest commands

documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc, documentation/src/main/asciidoc/topics/ref_rest_caches.adoc, documentation/src/main/asciidoc/topics/ref_rest_caches_query.adoc, documentation/src/main/asciidoc/topics/ref_rest_counters.adoc, documentation/src/main/asciidoc/topics/ref_rest_data_formats.adoc, documentation/src/main/asciidoc/topics/ref_rest_rolling.adoc, documentation/src/main/asciidoc/topics/ref_rest_security.adoc, documentation/src/main/asciidoc/topics/ref_rest_servers.adoc, documentation/src/main/asciidoc/topics/ref_rest_xsite.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_principal_deny.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_principal_grant.adoc
https://issues.redhat.com/browse/ISPN-14424
Docs fixes
- urls
- missing /rest/ in the commands
Backports #10551
=> [13.0.x]ISPN-14424 fix errors in the rest commands

build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14421
=> [13.0] ISPN-14421 Netty 4.1.86.Final

build/configuration/pom.xml
=> ISPN-14437 XStream 1.4.20

build/configuration/pom.xml
=> [14.0] ISPN-14437 XStream 1.4.20

build-configuration/pom.xml
=> [13.0] ISPN-14437 XStream 1.4.20

build-configuration/pom.xml
=> [12.1] ISPN-14437 XStream 1.4.20

documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc, documentation/src/main/asciidoc/topics/counters.adoc, documentation/src/main/asciidoc/topics/proc_adding_server_tasks.adoc, documentation/src/main/asciidoc/topics/proc_enforcing_sb_versions.adoc, documentation/src/main/asciidoc/topics/ref_rest_security.adoc
https://issues.redhat.com/browse/ISPN-14432
Fix various broken links in the docs, add reference to the code tutorials and RH spring boot documentation in the Spring doc
backports #10566
=> [14.0.x] ISPN-14432 Fix broken links in the docs

client/hotrod/src/main/java/org/infinispan/hotrod/impl/cache/RemoteCacheImpl.java
https://issues.redhat.com/browse/ISPN-14440
=> fix, FQCN for ToEmptyBytesKeyValueFilterConverter specified as filterConverterFactory

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14442
Backport #10572
=> ISPN-14442 Updates to log4j 2.19.0

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14442
=> [14.x] ISPN-14442 Updates to log4j 2.19.0

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/OpenTelemetryClient.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/TracingDisabledTest.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/HotRodConfiguration.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/HotRodConfigurationBuilder.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/package-info.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/ConfigurationProperties.java
https://issues.redhat.com/browse/ISPN-14426
Backporting of https://github.com/infinispan/infinispan/pull/10552
=> [14.0.x] ISPN-14426 Allow to disable tracing propagation on HotRod client

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/ProtocolVersion.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/ProtocolVersion.java
https://issues.redhat.com/browse/ISPN-14451
=> ISPN-14451 Parse Hot Rod "AUTO" version

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/ProtocolVersion.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/ProtocolVersion.java
https://issues.redhat.com/browse/ISPN-14451
=> [14.0] ISPN-14451 Parse Hot Rod "AUTO" version

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14448
Backport #10578
=> ISPN-14448 Surefire 3.0.0-M8

build/configuration/pom.xml
=> [14.x] ISPN-14448 Updates Maven surefire plugin version to 3.0.0-M8

server/runtime/build.xml
https://issues.redhat.com/browse/ISPN-14461
=> ISPN-14461 Add missing licence: MPL-1.1

server/runtime/build.xml
https://issues.redhat.com/browse/ISPN-14461
=> [14.x] ISPN-14461 Add missing licence: MPL-1.1

pom.xml, query/src/test/java/org/infinispan/query/startup/IndexStartupModeTest.java
https://issues.redhat.com/browse/ISPN-14462
Backport #10582
=> ISPN-14462 Updates to assertj-core 3.24.1

commons/all/src/main/java/org/infinispan/commons/util/Util.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14466
=> ISPN-14466 Correctly report cache update errors in the REST API

commons/all/src/main/java/org/infinispan/commons/util/Util.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14466
=> [14.0] ISPN-14466 Correctly report cache update errors in the REST API

commons/all/src/main/java/org/infinispan/commons/util/Util.java, core/src/main/java/org/infinispan/marshall/exts/ThrowableExternalizer.java, core/src/test/java/org/infinispan/marshall/exts/RemoteExceptionExternalizerTest.java
https://issues.redhat.com/browse/ISPN-14467
=> [14.0.x] ISPN-14467 Suppressed exceptions should be sent over the wire

commons/all/src/main/java/org/infinispan/commons/util/Util.java, core/src/main/java/org/infinispan/marshall/exts/ThrowableExternalizer.java, core/src/test/java/org/infinispan/marshall/exts/RemoteExceptionExternalizerTest.java
https://issues.redhat.com/browse/ISPN-14467
=> ISPN-14467 Suppressed exceptions should be sent over the wire

server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14466
=> ISPN-14466 Correctly report cache update errors in the REST API (test fix)

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14472
Makes the build work with Maven 4.0 alpha and mvnd
=> ISPN-14472 Maven Shade 3.4.1

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14472
=>  [14.0] ISPN-14472 Maven Shade 3.4.1

pom.xml, query/src/test/java/org/infinispan/query/startup/IndexStartupModeTest.java
=> [14.x] ISPN-14462 Updates to assertj-core 3.24.1

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14476
=> ISPN-14476: Bump JGroups to 5.2.12.Final

core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java, core/src/test/java/org/infinispan/test/data/Address.java, core/src/test/java/org/infinispan/test/data/Person.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
https://issues.redhat.com/browse/ISPN-14479
=> ISPN-14479 SQL Cache store initiation fails on Sql type CHAR

integrationtests/security-it/pom.xml, integrationtests/security-it/src/test/resources/arquillian.xml
https://issues.redhat.com/browse/ISPN-14471
=> ISPN-14471 WF Security integration tests are failing with Java 17

integrationtests/security-it/pom.xml, integrationtests/security-it/src/test/resources/arquillian.xml
Reverts infinispan/infinispan#10592
=> Revert "ISPN-14471 WF Security integration tests are failing with Java 17"

documentation/src/main/asciidoc/cheat-sheets/cache-configuration.asciidoc
https://issues.redhat.com/browse/ISPN-14083
=> ISPN-14083 Cache configuration cheat sheet

documentation/src/main/asciidoc/cheat-sheets/cache-configuration.asciidoc
Add cache configuration cheat sheet
https://issues.redhat.com/browse/ISPN-14083
backports #10392
=> [14.0.x] ISPN-14083 - Cache configuration cheat sheet

server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java, server/rest/src/test/java/org/infinispan/rest/resources/CounterResourceTest.java
Return status code 304 (not modified) if the counter exists or if is unable to create
https://issues.redhat.com/browse/ISPN-14468
=> ISPN-14468 REST: return error if failed to create counter

server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
https://issues.redhat.com/browse/ISPN-14486
=> ISPN-14486 Startup might be blocked by statistic requests

server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespLettuceHandler.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14495
https://issues.redhat.com/browse/ISPN-14496
=> ISPN-14495 RESP endpoint cannot parse request larger than packet size

core/src/main/java/org/infinispan/util/concurrent/BlockingManager.java, core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java, core/src/main/java/org/infinispan/util/concurrent/NonBlockingManagerImpl.java, core/src/main/java/org/infinispan/util/concurrent/ScheduledCompletableStage.java
https://issues.redhat.com/browse/ISPN-14490
=> ISPN-14490 Add blocking scheduled tasks to BlockingManager

Jenkinsfile, Jenkinsfile-release, build/configuration/pom.xml, documentation/src/main/asciidoc/topics/contributing/basics.adoc, documentation/src/main/asciidoc/topics/contributing/building.adoc, documentation/src/main/asciidoc/topics/proc_adding_hotrod_client_dependencies.adoc, documentation/src/main/asciidoc/topics/ref_quick_start.adoc
https://issues.redhat.com/browse/ISPN-14492
Backport #10613
=> ISPN-14492 Java 17 instead of 11

Jenkinsfile, Jenkinsfile-release, build/configuration/pom.xml, documentation/src/main/asciidoc/topics/contributing/basics.adoc, documentation/src/main/asciidoc/topics/contributing/building.adoc, documentation/src/main/asciidoc/topics/proc_adding_hotrod_client_dependencies.adoc, documentation/src/main/asciidoc/topics/ref_quick_start.adoc
https://issues.redhat.com/browse/ISPN-14492
=> [14.0] ISPN-14492 Java 17 instead of 11

server/resp/src/main/java/org/infinispan/server/resp/RespLettuceHandler.java
There are a few things fixed here:
1. No longer create a String per request in the trace message with Util.toStr. Instead uses an if to avoid that allocation
2. Close state machine when channel is closed. Prevents a WARN message from Netty about not closing the direct memory buffer
3. Reuse CommandOutput between requests (prevents allocations of 1 ArrayDeque, 2 ArrayList as well as the PushObject itself
4. Change CommandOutput implementation to not store the type as the first argument. Prevents sublist allocation.
Overall performance is not much better but allocations per invocation should be reduced a decent amount (percentile based on request size)
=> ISPN-14501 RESP protocol parser can be a bit more efficient

core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java, core/src/test/java/org/infinispan/test/data/Address.java, core/src/test/java/org/infinispan/test/data/Person.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
https://issues.redhat.com/browse/ISPN-14479
=> [14.0.x] ISPN-14479 SQL Cache store initiation fails on Sql type CHAR

build/configuration/pom.xml, pom.xml, spring/spring-boot-3/pom.xml, spring/spring6/pom.xml
https://issues.redhat.com/browse/ISPN-14513
=> [14.x] ISPN-14513 Upgrade Narayana to 5.13.1.Final

server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
https://issues.redhat.com/browse/ISPN-14510
=> ISPN-14510 Fix CliIT.testCliInteractive failure

server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
https://issues.redhat.com/browse/ISPN-14510
=> [14.0] ISPN-14510 Fix CliIT.testCliInteractive failure

build/component-annotations/pom.xml, build/component-processor/pom.xml, build/configuration/pom.xml, build/logging-annotations/pom.xml, build/logging-processor/pom.xml, commons/all/pom.xml, commons/jdk19/pom.xml, javadoc/pom.xml, pom.xml, spring/spring-boot-3/embedded/pom.xml, spring/spring-boot-3/pom.xml, spring/spring-boot-3/remote/pom.xml, spring/spring-boot-3/tests/pom.xml, spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/embedded/EmbeddedSessionApp.java, spring/spring6/pom.xml
This PR contains minor fixes
* Added maven.compiler.release property to set the compiler --release flag
* Disabled global-state for testing (not required and generates files in working directory)
* Remove unnecessary properties
* Changed names on new modules
follow up for https://issues.redhat.com/browse/ISPN-13424 and https://issues.redhat.com/browse/ISPN-14270
=> ISPN-14270 & ISPN-13424 Spring Boot 3 & Spring 6

build/configuration/pom.xml, hibernate/cache-commons/pom.xml, hibernate/cache-v60/pom.xml, pom.xml, spring/spring-boot-3/pom.xml, spring/spring6/pom.xml
https://issues.redhat.com/browse/ISPN-14512
=> ISPN-14512 Fix *-jakarta modules

build/configuration/pom.xml, hibernate/cache-commons/pom.xml, hibernate/cache-v60/pom.xml, pom.xml, spring/spring-boot-3/pom.xml, spring/spring6/pom.xml
https://issues.redhat.com/browse/ISPN-14512
=> [14.x] ISPN-14512 Fix *-jakarta modules

build/component-annotations/pom.xml, build/component-processor/pom.xml, build/configuration/pom.xml, build/logging-annotations/pom.xml, build/logging-processor/pom.xml, commons/all/pom.xml, commons/jdk19/pom.xml, javadoc/pom.xml, pom.xml, spring/spring-boot-3/embedded/pom.xml, spring/spring-boot-3/pom.xml, spring/spring-boot-3/remote/pom.xml, spring/spring-boot-3/tests/pom.xml, spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/embedded/EmbeddedSessionApp.java, spring/spring6/pom.xml
This PR contains minor fixes
* Added maven.compiler.release property to set the compiler --release flag
* Disabled global-state for testing (not required and generates files in working directory)
* Remove unnecessary properties
* Changed names on new modules
=> [14.x] ISPN-14270 & ISPN-13424 Spring Boot 3 & Spring 6

server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestClientDriver.java, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestMethodRule.java, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerExtension.java, server/tests/src/test/java/org/infinispan/server/functional/RestOperations.java
https://issues.redhat.com/browse/ISPN-14511
=> ISPN-14511 Fix RestOperations.testCounter[HTTP_20]

server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestClientDriver.java, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestMethodRule.java, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerExtension.java, server/tests/src/test/java/org/infinispan/server/functional/RestOperations.java
https://issues.redhat.com/browse/ISPN-14511
=> [14.0] ISPN-14511 Fix RestOperations.testCounter[HTTP_20]

spring/spring-boot-3/embedded/pom.xml, spring/spring-boot-3/remote/pom.xml, spring/spring-boot-3/tests/pom.xml, spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/remote/RemoteSpringSessionTest.java
https://issues.redhat.com/browse/ISPN-14516
=> [14.x] ISPN-14516 Wrong versions in spring-boot-3-tests module

spring/spring-boot-3/embedded/pom.xml, spring/spring-boot-3/remote/pom.xml, spring/spring-boot-3/tests/pom.xml, spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/remote/RemoteSpringSessionTest.java
https://issues.redhat.com/browse/ISPN-14516
=> ISPN-14516 Wrong versions in spring-boot-3-tests module

server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespLettuceHandler.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14495
https://issues.redhat.com/browse/ISPN-14496
=> [14.0] ISPN-14495 RESP endpoint cannot pares request larger than packet size

spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/remote/RemoteSpringSessionTest.java
=> ISPN-13424 RemoteSession test fix

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14520
=> ISPN-14520 Upgrade Protostream to 4.6.1.Final

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14520
=> [14.x] ISPN-14520 Upgrade Protostream to 4.6.1.Final

build/configuration/pom.xml, server/runtime/src/main/server/server/conf/log4j2.xml, server/runtime/src/test/resources/configuration/log4j2.xml, server/tests/src/test/resources/configuration/log4j2-trace.xml
https://issues.redhat.com/browse/ISPN-14523
=> ISPN-14523 Log4j 2.20.0

build/configuration/pom.xml, core/src/main/java/org/infinispan/util/concurrent/BlockingManager.java, core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java, query/src/main/java/org/infinispan/query/concurrent/InfinispanIndexingExecutorProvider.java, query/src/main/java/org/infinispan/query/impl/LifecycleManager.java, query/src/main/java/org/infinispan/search/mapper/impl/InfinispanEntityTypeContributor.java, query/src/main/java/org/infinispan/search/mapper/mapping/SearchMappingCommonBuilding.java, query/src/main/java/org/infinispan/search/mapper/mapping/impl/InfinispanIndexedTypeContextImpl.java, query/src/main/java/org/infinispan/search/mapper/mapping/impl/InfinispanMapping.java, query/src/main/java/org/infinispan/search/mapper/model/impl/InfinispanBootstrapIntrospector.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/model/ProtobufBootstrapIntrospector.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/model/ProtobufRawTypeModel.java
https://issues.redhat.com/browse/ISPN-14482
Draft since:
1. Waiting for Hibernate Search 6.2.Alpha2. In particular for https://hibernate.atlassian.net/browse/HSEARCH-3910
2. Based on https://github.com/infinispan/infinispan/pull/10610 that 
Tested locally compiling a snapshot of Hibernate Search from the branch https://github.com/hibernate/hibernate-search/pull/3369 ✌🏻
=> ISPN-14482 Pass global blocking scheduled executor to Hibernate Search

build/configuration/pom.xml, pom.xml, server/runtime/pom.xml
https://issues.redhat.com/browse/ISPN-14525
=> ISPN-14525 Elytron 2.1.0.Final

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/CalculusAuto.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/CalculusIndexed.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/CalculusManual.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/LongAuto.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Product.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/marshallers/CalculusManualMarshaller.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/marshallers/CalculusManualSCI.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/type/BigIntegerAdapterTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/type/BigIntegerAutoTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/type/BigIntegerBigDecimalIndexedTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/type/BigIntegerManualTest.java, client/hotrod-client/src/test/resources/protostream/calculus-manual.proto, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ProtobufPropertyHelper.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadata.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMessageContext.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingTagHandler.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/aggregator/BigDecimalAggregator.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/aggregator/BigIntegerAggregator.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/aggregator/TypeAggregator.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/FieldReferenceProvider.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/MessageReferenceProvider.java
https://issues.redhat.com/browse/ISPN-14453
Backport of #10645
=> [14.0.x] ISPN-14453 Ickl Queries should support BigInteger and BigDecimal

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/CalculusAuto.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/CalculusIndexed.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/CalculusManual.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/LongAuto.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Product.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/marshallers/CalculusManualMarshaller.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/marshallers/CalculusManualSCI.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/type/BigIntegerAdapterTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/type/BigIntegerAutoTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/type/BigIntegerBigDecimalIndexedTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/type/BigIntegerManualTest.java, client/hotrod-client/src/test/resources/protostream/calculus-manual.proto, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ProtobufPropertyHelper.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadata.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMessageContext.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingTagHandler.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/aggregator/BigDecimalAggregator.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/aggregator/BigIntegerAggregator.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/aggregator/TypeAggregator.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/FieldReferenceProvider.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/MessageReferenceProvider.java
https://issues.redhat.com/browse/ISPN-14453
* ~~Based on https://github.com/infinispan/protostream/pull/188, so we need a new ProtoStream release in order to support that.~~ done!
* ~~We need a new ProtoStream release containing the IPROTO-260 fix in order to merge it.~~ done!
=> ISPN-14453 Ickl Queries should support BigInteger and BigDecimal

documentation/src/main/asciidoc/stories/assembly_migrating_data.adoc, documentation/src/main/asciidoc/titles/upgrading/upgrading.asciidoc, documentation/src/main/asciidoc/topics/con_store_migrator.adoc, documentation/src/main/asciidoc/topics/proc_configuring_store_migrator.adoc, documentation/src/main/asciidoc/topics/proc_migrating_cache_stores.adoc, documentation/src/main/asciidoc/topics/ref_store_migrator_properties.adoc
Backports  #10656 
https://issues.redhat.com/browse/ISPN-14522
Docs revision for the store migrator
Add information about configuring the number of segments for segmented cache stores
=> [14.0.x]ISPN-14522 store migrator docs updates

core/pom.xml, query/pom.xml
https://issues.redhat.com/browse/ISPN-14543
=> ISPN-14543 Don't filter binary resources

core/pom.xml, query/pom.xml
https://issues.redhat.com/browse/ISPN-14543
=> [12.1] ISPN-14543 Don't filter binary resources

core/pom.xml, query/pom.xml
https://issues.redhat.com/browse/ISPN-14543
=> [14.0] ISPN-14543 Don't filter binary resources

build/configuration/pom.xml
* Update to 6.2.CR3
https://issues.redhat.com/browse/ISPN-14361
=> ISPN-14361 Create Hibernate 2LC implementation for Hibernate 6.2.x

.github/workflows/sync_docs.yml
Update stable version in the docs sync workflow
=> GH actions update stable version

.github/workflows/sync_docs.yml
Synchronize changes to the website fail https://github.com/infinispan/infinispan/actions/runs/4304636434/jobs/7506095517#step:5:3763 
Update Java to 17 
Update stable branch to 14
=> ISPN-14539 update docs sync to use Java 17

core/pom.xml, query/pom.xml
https://issues.redhat.com/browse/ISPN-14543
=> [13.0] ISPN-14543 Don't filter binary resources

documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
https://issues.redhat.com/browse/ISPN-14507
minor docs updates
=> [14.0]ISPN-14507 docs revision rest comparing two configs

documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
Docs edits to the rest updates
https://issues.redhat.com/browse/ISPN-14507
#10246 & #10539
=> ISPN-14507 docs review rest

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14553
=> ISPN-14553 Upgrades all Spring and Spring Boot dependencies

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14553
=> [14.0] ISPN-14553 Upgrades all Spring and Spring Boot dependencies

api/src/main/java/org/infinispan/api/Infinispan.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/GetCounterNamesOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/multimap/operations/GetKeyMultimapOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/IterationNextOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientEventsOOMTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/TestChannelFactory.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/multimap/RemoteMultimapCacheAPITWithDuplicatesTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/InternalRemoteCacheManager.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java, client/hotrod/src/main/java/org/infinispan/hotrod/HotRod.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/HotRodTransport.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/counter/operation/GetCounterNamesOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/multimap/operations/GetKeyMultimapOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/IterationNextOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod/src/test/java/org/infinispan/hotrod/HotRodServerExtension.java, client/hotrod/src/test/java/org/infinispan/hotrod/impl/transport/netty/HotRodTestTransport.java
https://issues.redhat.com/browse/ISPN-14532
https://issues.redhat.com/browse/ISPN-14535
https://issues.redhat.com/browse/ISPN-14536
=> ISPN-14532 Multimap failing with huge value

api/src/main/java/org/infinispan/api/Infinispan.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/GetCounterNamesOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/multimap/operations/GetKeyMultimapOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/IterationNextOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientEventsOOMTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/TestChannelFactory.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/multimap/RemoteMultimapCacheAPITWithDuplicatesTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/InternalRemoteCacheManager.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java, client/hotrod/src/main/java/org/infinispan/hotrod/HotRod.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/HotRodTransport.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/counter/operation/GetCounterNamesOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/multimap/operations/GetKeyMultimapOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/IterationNextOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod/src/test/java/org/infinispan/hotrod/HotRodServerExtension.java, client/hotrod/src/test/java/org/infinispan/hotrod/impl/transport/netty/HotRodTestTransport.java
https://issues.redhat.com/browse/ISPN-14532
https://issues.redhat.com/browse/ISPN-14535
https://issues.redhat.com/browse/ISPN-14536
Backport of #10664 without the changes to the tests.
=> [14.0.x] ISPN-14532 Multimap failing with huge value

core/src/main/java/org/infinispan/configuration/cache/Configuration.java, core/src/main/java/org/infinispan/configuration/cache/ConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java, core/src/main/java/org/infinispan/configuration/parsing/ConfigurationBuilderHolder.java, core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java, core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14528
=> ISPN-14528 Enable configuration conversion for templates

core/src/main/java/org/infinispan/configuration/cache/Configuration.java, core/src/main/java/org/infinispan/configuration/cache/ConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java, core/src/main/java/org/infinispan/configuration/parsing/ConfigurationBuilderHolder.java, core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java, core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14528
=> [14.0] ISPN-14528 Enable configuration conversion for templates

core/src/main/resources/schema/infinispan-config-15.0.xsd
https://issues.redhat.com/browse/ISPN-13446
=> ISPN-13446 Fix schema

core/src/main/resources/schema/infinispan-config-14.0.xsd
https://issues.redhat.com/browse/ISPN-13446
=> [14.0] ISPN-13446 Fix schema

pom.xml
=> [9.4] ISPN-14437 XStream 1.4.20

build/checkstyle/src/main/resources/checkstyle.xml, server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java, server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
https://issues.redhat.com/browse/ISPN-14578
=> ISPN-14578 We should never be using CompletableFuture.completionStage

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdmin.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheManagerAdminImpl.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/SchemaIndexUpdateTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/Image.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/ModelC.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/SchemaC.java, commons/all/src/main/java/org/infinispan/commons/util/Util.java, core/src/main/java/org/infinispan/configuration/cache/Configuration.java, core/src/main/java/org/infinispan/configuration/cache/IndexingConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/QueryConfiguration.java, server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/CacheUpdateConfigurationAttributeTask.java, server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/EmbeddedServerAdminOperationHandler.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14085
Rework of #10447 
~~draft => not done~~ ready!
=> ISPN-14085 Allow to pass new list of indexed entities in update schema API

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdmin.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheManagerAdminImpl.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/SchemaIndexUpdateTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/Image.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/ModelC.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/SchemaC.java, commons/all/src/main/java/org/infinispan/commons/util/Util.java, core/src/main/java/org/infinispan/configuration/cache/Configuration.java, core/src/main/java/org/infinispan/configuration/cache/IndexingConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/QueryConfiguration.java, server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/CacheUpdateConfigurationAttributeTask.java, server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/EmbeddedServerAdminOperationHandler.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14085
https://issues.redhat.com/browse/JDG-5977
Backport of https://github.com/infinispan/infinispan/pull/10686
=> [14.0.x] ISPN-14085 Allow to pass new list of indexed entities in update schema API

server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java
https://issues.redhat.com/browse/ISPN-14504
Note this PR is based on #10704 and that should be reviewed first
=> ISPN-14504 Optimize RESP GET and SET operations

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/schema/SchemaUpdateMetadataTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Programmer.java, client/hotrod-client/src/test/resources/proto/pro-sortable.proto, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java
https://issues.redhat.com/browse/ISPN-14527
https://issues.redhat.com/browse/JDG-5997
Backport of #10659
=> [14.0.x] ISPN-14527 Meta model may not reflect some schema changes

server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java, server/runtime/src/main/java/org/infinispan/server/Server.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-14573
Is not the fix yet, but I added a way to detect better if the report script is failing.
=> ISPN-14573 AbstractAuthorization.testRestServerNodeReport is failing

cli/src/test/java/org/infinispan/cli/commands/kubernetes/KubeTest.java, commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReader.java
https://issues.redhat.com/browse/ISPN-14574
=> ISPN-14574 Fix CCE with Kube CLI get clusters -s

cli/src/test/java/org/infinispan/cli/commands/kubernetes/KubeTest.java, commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReader.java
https://issues.redhat.com/browse/ISPN-14574
=> [14.0] ISPN-14574 Fix CCE with Kube CLI get clusters -s

client/rest-client/src/main/java/org/infinispan/client/rest/RestTaskClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestTaskClientOkHttp.java, documentation/src/main/asciidoc/topics/ref_rest_server_tasks.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_tasks_download.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_tasks_exec.adoc, server/rest/src/main/java/org/infinispan/rest/logging/Log.java, server/rest/src/main/java/org/infinispan/rest/resources/TasksResource.java, server/rest/src/test/java/org/infinispan/rest/resources/TasksResourceTest.java, server/runtime/src/main/java/org/infinispan/server/tasks/DistributedServerTask.java, server/runtime/src/main/java/org/infinispan/server/tasks/DistributedServerTaskRunner.java, tasks/manager/src/test/java/org/infinispan/tasks/DummyTaskEngine.java, tasks/manager/src/test/java/org/infinispan/tasks/TaskManagerTest.java
https://issues.redhat.com/browse/ISPN-14488
https://issues.redhat.com/browse/ISPN-14489
=> [14.0] ISPN-14488 + ISPN-14489 REST Task Exec w/Cache + Script Download API

cli/src/main/java/org/infinispan/cli/commands/rest/Index.java, client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java, documentation/src/main/asciidoc/topics/json/rest_indexes_metamodel.json, documentation/src/main/asciidoc/topics/ref_rest_caches_query.adoc, query/src/main/java/org/infinispan/search/mapper/mapping/SearchMapping.java, query/src/main/java/org/infinispan/search/mapper/mapping/impl/InfinispanMapping.java, query/src/main/java/org/infinispan/search/mapper/mapping/metamodel/IndexMetamodel.java, query/src/main/java/org/infinispan/search/mapper/mapping/metamodel/ObjectFieldMetamodel.java, query/src/main/java/org/infinispan/search/mapper/mapping/metamodel/ValueFieldMetamodel.java, query/src/test/java/org/infinispan/query/queries/phrases/EmbeddedQueryTest.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java, server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-13946
=> ISPN-13946 Expose indexes metamodel

cli/src/main/java/org/infinispan/cli/commands/rest/Index.java, client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java, documentation/src/main/asciidoc/topics/json/rest_indexes_metamodel.json, documentation/src/main/asciidoc/topics/ref_rest_caches_query.adoc, query/src/main/java/org/infinispan/search/mapper/mapping/SearchMapping.java, query/src/main/java/org/infinispan/search/mapper/mapping/impl/InfinispanMapping.java, query/src/main/java/org/infinispan/search/mapper/mapping/metamodel/IndexMetamodel.java, query/src/main/java/org/infinispan/search/mapper/mapping/metamodel/ObjectFieldMetamodel.java, query/src/main/java/org/infinispan/search/mapper/mapping/metamodel/ValueFieldMetamodel.java, query/src/test/java/org/infinispan/query/queries/phrases/EmbeddedQueryTest.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java, server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-13946
https://issues.redhat.com/browse/JDG-5980
Backport of #10717
=> [14.0.x] ISPN-13946 Expose indexes metamodel

cli/src/main/java/org/infinispan/cli/commands/rest/Schema.java, cli/src/main/java/org/infinispan/cli/logging/Messages.java, server/rest/src/main/java/org/infinispan/rest/ByteBufContentSource.java, server/rest/src/main/java/org/infinispan/rest/framework/ContentSource.java, server/rest/src/main/java/org/infinispan/rest/resources/ProtobufResource.java, server/rest/src/test/java/org/infinispan/rest/resources/ProtobufResourceTest.java
https://issues.redhat.com/browse/ISPN-14112
=> ISPN-14112 Prevent creation of schemas from empty content

cli/src/main/java/org/infinispan/cli/commands/rest/Schema.java, cli/src/main/java/org/infinispan/cli/logging/Messages.java, server/rest/src/main/java/org/infinispan/rest/ByteBufContentSource.java, server/rest/src/main/java/org/infinispan/rest/framework/ContentSource.java, server/rest/src/main/java/org/infinispan/rest/resources/ProtobufResource.java, server/rest/src/test/java/org/infinispan/rest/resources/ProtobufResourceTest.java
https://issues.redhat.com/browse/ISPN-14112
=> [14.0] ISPN-14112 Prevent creation of schemas from empty content

commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationReader.java
https://issues.redhat.com/browse/ISPN-14683
=> ISPN-14683 ConfigurationReader media type CAN be null

core/src/main/java/org/infinispan/configuration/cache/EncodingConfiguration.java, core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java
https://issues.redhat.com/browse/ISPN-14685
=> [14.0] ISPN-14685 Relax EncodingConfiguration.matches

build/configuration/pom.xml, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/CircularReferencesMarshallTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/company/FootballSchema.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/company/FootballTeam.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/company/Player.java
https://issues.redhat.com/browse/ISPN-14687
Draft => Depends on https://github.com/infinispan/protostream/pull/189, that should be merged first and a new release of ProtoStream with this patch is necessary.
=> ISPN-14687 Detect circular references on marshalling

build/configuration/pom.xml, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/CircularReferencesMarshallTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/company/FootballSchema.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/company/FootballTeam.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/company/Player.java
https://issues.redhat.com/browse/ISPN-14687
Draft => Depends on https://github.com/infinispan/protostream/pull/189, that should be merged first and a new release of ProtoStream with this patch is necessary.
Backport to 14.0.x of https://github.com/infinispan/infinispan/pull/10738
=> [14.0.x] ISPN-14687 Detect circular references on marshalling

.gitignore, server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java, spring/spring-boot-3/remote/src/main/java/org/infinispan/spring/starter/remote/actuator/RemoteInfinispanCacheMeterBinder.java, spring/spring-boot-3/remote/src/test/java/io/micrometer/core/instrument/binder/cache/NotAuthorizedRemoteCacheMetricBinderTest.java, spring/spring-boot-3/remote/src/test/java/test/org/infinispan/spring/starter/remote/actuator/RemoteCacheMetricBinderTest.java, spring/spring-boot/remote/src/main/java/org/infinispan/spring/starter/remote/actuator/RemoteInfinispanCacheMeterBinder.java, spring/spring-boot/remote/src/test/java/io/micrometer/core/instrument/binder/cache/NotAuthorizedRemoteCacheMetricBinderTest.java, spring/spring-boot/remote/src/test/java/test/org/infinispan/spring/starter/remote/actuator/RemoteCacheMetricBinderTest.java
https://issues.redhat.com/browse/ISPN-14691
=> [14.0] ISPN-14691 Fix actuator metrics load for unauthorized users

.gitignore, server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java, spring/spring-boot-3/remote/src/main/java/org/infinispan/spring/starter/remote/actuator/RemoteInfinispanCacheMeterBinder.java, spring/spring-boot-3/remote/src/test/java/io/micrometer/core/instrument/binder/cache/NotAuthorizedRemoteCacheMetricBinderTest.java, spring/spring-boot-3/remote/src/test/java/test/org/infinispan/spring/starter/remote/actuator/RemoteCacheMetricBinderTest.java, spring/spring-boot/remote/src/main/java/org/infinispan/spring/starter/remote/actuator/RemoteInfinispanCacheMeterBinder.java, spring/spring-boot/remote/src/test/java/io/micrometer/core/instrument/binder/cache/NotAuthorizedRemoteCacheMetricBinderTest.java, spring/spring-boot/remote/src/test/java/test/org/infinispan/spring/starter/remote/actuator/RemoteCacheMetricBinderTest.java
https://issues.redhat.com/browse/ISPN-14691
Backport #10743 
Relates to the issue https://github.com/infinispan/infinispan-operator/issues/1789
=> ISPN-14691 Fix actuator metrics load for unauthorized users

commons/all/src/main/java/org/infinispan/commons/CacheConfigurationException.java, commons/all/src/main/java/org/infinispan/commons/CacheException.java, commons/all/src/main/java/org/infinispan/commons/CacheListenerException.java, commons/all/src/main/java/org/infinispan/commons/IllegalLifecycleStateException.java, commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationReaderException.java, commons/all/src/main/java/org/infinispan/commons/logging/Log.java, commons/all/src/main/java/org/infinispan/commons/util/Util.java, core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java, core/src/test/java/org/infinispan/configuration/module/ExtendedParserTest.java, core/src/test/java/org/infinispan/factories/impl/BasicComponentRegistryImplTest.java, core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java, core/src/test/java/org/infinispan/tx/ExceptionDuringGetTest.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14473
=> ISPN-14473 Leaner REST errors

commons/all/src/main/java/org/infinispan/commons/CacheConfigurationException.java, commons/all/src/main/java/org/infinispan/commons/CacheException.java, commons/all/src/main/java/org/infinispan/commons/CacheListenerException.java, commons/all/src/main/java/org/infinispan/commons/IllegalLifecycleStateException.java, commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationReaderException.java, commons/all/src/main/java/org/infinispan/commons/logging/Log.java, commons/all/src/main/java/org/infinispan/commons/util/Util.java, core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java, core/src/test/java/org/infinispan/configuration/module/ExtendedParserTest.java, core/src/test/java/org/infinispan/factories/impl/BasicComponentRegistryImplTest.java, core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java, core/src/test/java/org/infinispan/tx/ExceptionDuringGetTest.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14473
=> [14.0] ISPN-14473 Leaner REST errors

client/hotrod/pom.xml, client/hotrod/src/main/java/org/infinispan/hotrod/impl/counter/operation/AddListenerOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/AbstractKeyOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/AbstractPutOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/AddBloomNearCacheClientListenerOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/AddClientListenerOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/ClientListenerOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/FaultTolerantPingOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/GetOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/HotRodOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/PingOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/PingResponse.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/PutOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/SetOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/StatsAffectingRetryingOperation.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/protocol/HeaderParams.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/handler/CacheRequestProcessor.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ByteBufUtil.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelInitializer.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelPool.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ClientBaseDecoder.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/HeaderDecoder.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/HintedReplayingDecoder.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/HintingByteBuf.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/Intrinsics.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ParserUtils.java, client/hotrod/src/main/resources/hotrod.gr
https://issues.redhat.com/browse/ISPN-14592
The parser can live with the already existing parser. Currently, it can handle the parsing of topology, exceptions, and ping.
=> ISPN-14592 Hot Rod client uses generated parser

spring/spring-boot-3/embedded/pom.xml, spring/spring-boot-3/remote/pom.xml
https://issues.redhat.com/browse/ISPN-14713
=> ISPN-14713 Include new api dependencies in Spring Boot 3 modules

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14711
=> ISPN-14711 Updates Spring Dependencies to latest minors

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14711
=> [14.0] ISPN-14711 Updates Spring Dependencies to latest minors

documentation/src/main/asciidoc/stories/assembly_create_spring_boot_project.adoc, documentation/src/main/asciidoc/topics/dependencies_maven/sb_bom.xml, documentation/src/main/asciidoc/topics/dependencies_maven/sb_embedded.xml, documentation/src/main/asciidoc/topics/dependencies_maven/sb_remote.xml, documentation/src/main/asciidoc/topics/dependencies_maven/spring6_session_dependencies.xml, documentation/src/main/asciidoc/topics/dependencies_maven/spring_cache_embedded.xml, documentation/src/main/asciidoc/topics/dependencies_maven/spring_cache_remote.xml, documentation/src/main/asciidoc/topics/proc_adding_embeddedcm_bean.adoc, documentation/src/main/asciidoc/topics/proc_externalizing_sessions_spring.adoc, documentation/src/main/asciidoc/topics/proc_setting_up_spring_cache.adoc, documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
backports #10747 
https://issues.redhat.com/browse/ISPN-14572
- update dependencies
- add info that spring 6 and SB 3 require Java 17
- fix rendering issue in the REST guide
=> [14.0]ISPN-14572 Spring 6 and SB 3 docs

documentation/src/main/asciidoc/stories/assembly_create_spring_boot_project.adoc, documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc, documentation/src/main/asciidoc/topics/dependencies_maven/sb_bom.xml, documentation/src/main/asciidoc/topics/dependencies_maven/sb_embedded.xml, documentation/src/main/asciidoc/topics/dependencies_maven/sb_remote.xml, documentation/src/main/asciidoc/topics/dependencies_maven/spring6_session_dependencies.xml, documentation/src/main/asciidoc/topics/dependencies_maven/spring_cache_embedded.xml, documentation/src/main/asciidoc/topics/dependencies_maven/spring_cache_remote.xml, documentation/src/main/asciidoc/topics/proc_adding_embeddedcm_bean.adoc, documentation/src/main/asciidoc/topics/proc_externalizing_sessions_spring.adoc, documentation/src/main/asciidoc/topics/proc_setting_up_spring_cache.adoc, documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
https://issues.redhat.com/browse/ISPN-14572
- update dependencies
- add info that spring 6 and SB 3 require Java 17
- fix rendering issue in the REST guide
=> ISPN-14572 Spring 6 and SB 3 docs

spring/spring-boot-3/remote/pom.xml
https://issues.redhat.com/browse/ISPN-14730
=> [14.0] ISPN-14730 exclude infinispan-commons from remote spring boot 3

server/resp/src/main/java/org/infinispan/server/resp/CacheRespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java
https://issues.redhat.com/browse/ISPN-14738
=> ISPN-14738 RESP endpoint commands don't require previous value

server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java
https://issues.redhat.com/browse/ISPN-14738
=> [14.0] ISPN-14738 RESP endpoint commands don't require previous value

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14681
=> ISPN-14681 Surefire 3.0.0

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14754
=> [14.0] ISPN-14754 Updates console to 14.0.8.Final

core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java, core/src/main/java/org/infinispan/util/concurrent/NonBlockingManager.java, core/src/main/java/org/infinispan/util/concurrent/NonBlockingManagerImpl.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFileStatsTest.java, core/src/test/java/org/infinispan/util/concurrent/BlockingManagerTestUtil.java
https://issues.redhat.com/browse/ISPN-14737
=> ISPN-14737 SoftIndexFileStore Index can become corrupted

core/src/main/java/org/infinispan/marshall/persistence/impl/MarshalledEntryFactoryImpl.java, core/src/main/java/org/infinispan/metadata/EmbeddedMetadata.java, core/src/test/java/org/infinispan/persistence/CacheLoaderFunctionalTest.java, core/src/test/java/org/infinispan/persistence/WriteSkewCacheLoaderFunctionalTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFileStatsTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java
Somehow these two commits got pushed from https://github.com/infinispan/infinispan/pull/10780 that shouldn't have. Reverting them.
=> ISPN-14740 Revert undesired commits

core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java, core/src/main/java/org/infinispan/util/concurrent/NonBlockingManager.java, core/src/main/java/org/infinispan/util/concurrent/NonBlockingManagerImpl.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFileStatsTest.java, core/src/test/java/org/infinispan/util/concurrent/BlockingManagerTestUtil.java
https://issues.redhat.com/browse/ISPN-14737
https://issues.redhat.com/browse/ISPN-14753
=> [14.0] ISPN-14737 SoftIndexFileStore Index can become corrupted

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14743
=> ISPN-14743 Netty 4.1.91.Final

core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java
https://issues.redhat.com/browse/ISPN-14759
Unfortunately, these do not affect the biggest offender for index updates which is calls to `IndexNode.store` for adding new entries or removing. Overwriting an existing entry is already optimized in `IndexNode.updateFileOffsetInFile` which just updates the file, offset and number of records.
=> ISPN-14759 SoftIndexFileStore Index can lag behind LogAppender under heavy load

Jenkinsfile, build/configuration/pom.xml, pom.xml, server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/Containers.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java, server/testdriver/core/src/main/resources/testcontainers.properties, server/testdriver/junit4/pom.xml, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerRule.java, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestListener.java, server/testdriver/junit5/pom.xml, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerTestListener.java, server/testdriver/junit5/src/test/java/org/infinispan/server/test/junit5/InfinispanXSiteServerTest.java, server/tests/pom.xml, server/tests/src/test/java/org/infinispan/server/extensions/ExtensionsIT.java, server/tests/src/test/resources/configuration/log4j2-trace.xml, server/tests/src/test/resources/configuration/log4j2.xml, server/tests/src/test/resources/log/log4j2-trace.xml, tasks/scripting/src/main/java/org/infinispan/scripting/utils/JSArrays.java
https://issues.redhat.com/browse/ISPN-14680
=> ISPN-14680 Reuse server image as a base for all tests

integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
https://issues.redhat.com/browse/ISPN-14760
=> ISPN-14760 Infinispan thirdparty integration tests failure with JDK17

integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
https://issues.redhat.com/browse/ISPN-14760
Backport of #10800
=> [14.0.x] ISPN-14760 Infinispan thirdparty integration tests failure with JDK17

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdmin.java, commons/all/src/main/java/org/infinispan/commons/configuration/StringConfiguration.java
https://issues.redhat.com/browse/ISPN-14744
=> ISPN-14744 RemoteCacheManagerAdmin supports XML, JSON and YAML

Jenkinsfile, build/configuration/pom.xml, pom.xml, server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/Containers.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java, server/testdriver/core/src/main/resources/testcontainers.properties, server/testdriver/junit4/pom.xml, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerRule.java, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestListener.java, server/testdriver/junit5/pom.xml, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerTestListener.java, server/testdriver/junit5/src/test/java/org/infinispan/server/test/junit5/InfinispanXSiteServerTest.java, server/tests/pom.xml, server/tests/src/test/java/org/infinispan/server/extensions/ExtensionsIT.java, server/tests/src/test/resources/configuration/log4j2-trace.xml, server/tests/src/test/resources/configuration/log4j2.xml, server/tests/src/test/resources/log/log4j2-trace.xml, tasks/scripting/src/main/java/org/infinispan/scripting/utils/JSArrays.java
https://issues.redhat.com/browse/ISPN-14680
=> [14.0] ISPN-14680 Reuse server image as a base for all tests

pom.xml, server/tests/pom.xml, server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java
=> [14.0.x] Remove Jaeger test containers dependency

core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java, core/src/test/java/org/infinispan/configuration/ConfigurationConversionTest.java
https://issues.redhat.com/browse/ISPN-14755
=> ISPN-14755 Don't serialize empty role arrays

client/hotrod-client/pom.xml, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/TransportFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/DnsResolver.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/DefaultTransportFactory.java, client/hotrod/pom.xml, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/AbstractConfigurationChildBuilder.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/ConfigurationChildBuilder.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/DnsResolver.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/HotRodConfiguration.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/HotRodConfigurationBuilder.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/TransportFactory.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/logging/Log.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/DefaultTransportFactory.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/IOURingNativeTransport.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/NativeTransport.java, pom.xml
https://issues.redhat.com/browse/ISPN-14731
=> ISPN-14731 Hot Rod client DNS Resolver

cli/src/main/java/org/infinispan/cli/commands/rest/Get.java, cli/src/main/resources/help/get.adoc, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java, server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
https://issues.redhat.com/browse/ISPN-14758
=> ISPN-14758 CLI: get command flag to retrieve extended information

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
https://issues.redhat.com/browse/ISPN-14774
=> ISPN-14774 enable configuration of tracing.propagation_enabled

remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/RemoteQueryServerBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-14591
=> ISPN-14591 Add BlockHound exception for registering proto file

server/runtime/pom.xml
https://issues.redhat.com/browse/ISPN-11701
=> ISPN-11701 Fix license generation issue

documentation/src/main/asciidoc/topics/ref_spring_boot_properties.adoc
https://issues.redhat.com/browse/ISPN-14789
Fix port number in the properties file
needs backport to 14 and 13
=> ISPN-14789 fix port number in config example

documentation/src/main/asciidoc/topics/ref_spring_boot_properties.adoc
https://issues.redhat.com/browse/ISPN-14789
Fix port number in the properties file
backports #10842
=> [13.0.x]ISPN-14789 fix port number in config example

documentation/src/main/asciidoc/topics/ref_spring_boot_properties.adoc
https://issues.redhat.com/browse/ISPN-14789
Fix port number in the properties file
backports #10842
=> [14.0.x] ISPN-14789-14 Fix port number in the properties file

remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/RemoteQueryServerBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-14591
Backport of #10829
=> [14.0.x] ISPN-14591 Add BlockHound exception for registering proto file

core/src/main/java/org/infinispan/util/logging/Log.java, server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java, server/core/src/main/java/org/infinispan/server/core/dataconversion/deserializer/Deserializer.java, server/core/src/main/java/org/infinispan/server/core/dataconversion/deserializer/SArray.java, server/core/src/main/java/org/infinispan/server/core/dataconversion/deserializer/SBlockData.java, server/core/src/main/java/org/infinispan/server/core/dataconversion/deserializer/SEntity.java, server/core/src/main/java/org/infinispan/server/core/dataconversion/deserializer/SObject.java, server/core/src/main/java/org/infinispan/server/core/dataconversion/deserializer/SPrim.java, server/core/src/main/java/org/infinispan/server/core/dataconversion/deserializer/SString.java, server/core/src/test/java/org/infinispan/server/core/dataconversion/DeserializerTest.java, server/core/src/test/java/org/infinispan/server/core/dataconversion/JsonTranscoderTest.java
https://issues.redhat.com/browse/ISPN-14765
=> ISPN-14765 Java Serialization to JSON transcoder

pom.xml
https://issues.redhat.com/browse/ISPN-14792
=> ISPN-14792 Add wildfly-commons back

documentation/src/main/asciidoc/topics/json/rest_caches_all_entries.json, documentation/src/main/asciidoc/topics/ref_rest_caches.adoc, server/rest/src/main/java/org/infinispan/rest/stream/CacheEntryStreamProcessor.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14788
=> ISPN-14788 Allow to retrieve cache entry metadata version using the REST API

commons-test/src/main/java/org/infinispan/commons/test/CommonsTestBlockHoundIntegration.java, commons/all/src/main/java/org/infinispan/commons/internal/CommonsBlockHoundIntegration.java, core/src/test/java/org/infinispan/util/CoreTestBlockHoundIntegration.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/internal/RocksDBBlockHoundIntegration.java, server/core/src/main/java/org/infinispan/server/core/ServerCoreBlockHoundIntegration.java, server/runtime/pom.xml, server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
https://issues.redhat.com/browse/ISPN-14803
=> ISPN-14803 Make sure block hound works in a server

server/runtime/src/main/java/org/infinispan/server/LifecycleCallbacks.java, server/runtime/src/main/java/org/infinispan/server/logging/events/ServerEventLogger.java
https://issues.redhat.com/browse/ISPN-14814
=> ISPN-14814 ServerEventLogger blocks when creating a cache

core/src/main/java/org/infinispan/util/concurrent/locks/impl/InfinispanLock.java, core/src/main/java/org/infinispan/util/concurrent/locks/impl/PerKeyLockContainer.java, core/src/test/java/org/infinispan/lock/InfinispanLockTest.java
https://issues.redhat.com/browse/ISPN-14794
=> ISPN-14794 Create locked InfinispanLock

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14821
=> ISPN-14821 Agroal 2.1

documentation/src/main/asciidoc/topics/con_restarting_clusters.adoc
https://issues.redhat.com/browse/ISPN-14773 
Revision of shutdown cluster and server. Add recommendations for different configuration option to prevent data loss and ensure data consistency
=> ISPN-14773 docs revision for cluster shutdown

documentation/src/main/asciidoc/topics/con_restarting_clusters.adoc
https://issues.redhat.com/browse/ISPN-14773 
Revision of shutdown cluster and server. Add recommendations for different configuration option to prevent data loss and ensure data consistency
backports #10824
=> [14.0.x]ISPN-14773 docs revision shutdown cluster and shutdown server

server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/CounterIncOrDec.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/DECRBY.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/INCRBY.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
Implementation and test.
Based on #10855
=> RESP Incrby decrby operations

build/configuration/pom.xml, jboss-marshalling/pom.xml, object-filter/pom.xml, pom.xml, quarkus/server/runtime/pom.xml, server/runtime/src/main/server/bin/common.sh
https://issues.redhat.com/browse/ISPN-14824
=> ISPN-14824 Open packages required by JBoss Marshalling River

server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java
https://issues.redhat.com/browse/ISPN-14833
=> ISPN-14833 RESP commands are checked in order

server/runtime/src/main/server/server/conf/infinispan-dev-mode.xml
https://issues.redhat.com/browse/ISPN-14815
=> ISPN-14815 Add an infinispan-dev-mode.xml configuration

server/runtime/src/main/java/org/infinispan/server/tasks/admin/ServerAdminOperationsHandler.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
https://issues.redhat.com/browse/ISPN-14823
=> ISPN-14823 Enable HR task for configuration attribute update

build/bom/pom.xml
https://issues.redhat.com/browse/ISPN-14841
=> ISPN-14841 Add infinispan-hibernate-cache-v62 to BOM

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14838
=> ISPN-14838 Updates to Mutiny 2.2.0

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14844
=> Quarkus 3.0.2.Final

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14836
=> ISPN-14836 Updates Spring 6 and Spring Boot 3 dependencies

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/protostream/validation/ProtobufValidationTest.java, client/hotrod-client/src/test/resources/proto/ciao-wrong.proto, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerInterceptor.java
https://issues.redhat.com/browse/ISPN-14816
=> ISPN-14816 Replacing Protobuf schema does not report validation errors

server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/CounterIncOrDec.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/INCRBYFLOAT.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14828
=> ISPN-14828 INCRBYFLOAT command

server/tests/pom.xml, server/tests/src/test/java/org/infinispan/server/persistence/PersistenceIT.java, server/tests/src/test/resources/database/jdbc-drivers.txt
https://issues.redhat.com/browse/ISPN-14817
=> ISPN-14817 Fix PersistenceIT

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14839
=> ISPN-14839 Updates console to 15.0.0.Dev01

core/src/main/java/org/infinispan/configuration/cache/SitesConfiguration.java, core/src/test/java/org/infinispan/xsite/CustomXSiteEntryMergePolicy.java, core/src/test/resources/configs/all/12.0.xml, core/src/test/resources/configs/all/12.1.xml, core/src/test/resources/configs/all/13.0.xml, core/src/test/resources/configs/all/14.0.xml, core/src/test/resources/configs/all/15.0.xml
https://issues.redhat.com/browse/ISPN-14851
=> ISPN-14851 Add cross-site merge-policy serializer

build/bom/pom.xml
https://issues.redhat.com/browse/ISPN-14841
=> [14.x] ISPN-14841 Add infinispan-hibernate-cache-v62 to BOM

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14836
=> [14.0] ISPN-14836 Updates Spring 6 and Spring Boot 3 dependencies

core/src/main/java/org/infinispan/configuration/cache/SitesConfiguration.java, core/src/test/java/org/infinispan/xsite/CustomXSiteEntryMergePolicy.java, core/src/test/resources/configs/all/12.0.xml, core/src/test/resources/configs/all/12.1.xml, core/src/test/resources/configs/all/13.0.xml, core/src/test/resources/configs/all/14.0.xml
https://issues.redhat.com/browse/ISPN-14851
=> [14.x] ISPN-14851 Add cross-site merge-policy serializer

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14818
=> [14.0] ISPN-14818 Update console to 14.0.9.Final

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
https://issues.redhat.com/browse/ISPN-14774
=> [14.0] ISPN-14774 enable configuration of tracing.propagation_enabled

server/runtime/src/main/server/server/conf/infinispan-dev-mode.xml
https://issues.redhat.com/browse/ISPN-14815
=> [14.0] ISPN-14815 Add an infinispan-dev-mode.xml configuration

core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java
https://issues.redhat.com/browse/ISPN-14848
=> [14.0] ISPN-14848 Deadlock during expiration of entries with LOCAL cache

core/src/main/resources/schema/infinispan-config-14.0.xsd, documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc, query/src/main/java/org/infinispan/query/impl/LifecycleManager.java, query/src/main/java/org/infinispan/query/impl/config/SearchPropertyExtractor.java, query/src/test/java/org/infinispan/query/config/EngineConfigTest.java, query/src/test/java/org/infinispan/query/indexing/DefaultIndexPathTest.java
https://issues.redhat.com/browse/ISPN-14109
https://issues.redhat.com/browse/JDG-6234
Backport of https://github.com/infinispan/infinispan/pull/10902
=> [14.0.x] ISPN-14109 Use the cache name in the default name of the index file path

server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LPUSH.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LPUSHX.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/internal/PUSH.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/internal/PUSHX.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
https://issues.redhat.com/browse/ISPN-14633
=> ISPN-14633 LPUSH and LPUSHX commands

server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java, server/tests/src/test/java/org/infinispan/server/functional/hotrod/XSiteHotRodCacheOperations.java, server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestCacheOperations.java
=> Reduce the number of keys for xsite test

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/protostream/validation/ProtobufValidationTest.java, client/hotrod-client/src/test/resources/proto/ciao-wrong.proto, client/hotrod-client/src/test/resources/proto/ciao.proto, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerInterceptor.java
https://issues.redhat.com/browse/ISPN-14816
https://issues.redhat.com/browse/JDG-6228
Backport of https://github.com/infinispan/infinispan/pull/10867
=> [14.0.x] ISPN-14816 Replacing Protobuf schema does not report validation errors

server/tests/src/test/java/org/infinispan/server/functional/XSiteHotRodCacheOperations.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteRestCacheOperations.java
=> [14.x] ISPN-14873 Reduce the number of keys for xsite test

core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java
https://issues.redhat.com/browse/ISPN-14848
=> ISPN-14848 Deadlock during expiration of entries with LOCAL cache

server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14882
=> ISPN-14882 Fix handling of lowercase commands

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapListCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/ListBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/function/IndexFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapListCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapListCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Resp3Command.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LINDEX.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/internal/PUSH.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
https://issues.redhat.com/browse/ISPN-14626
=> ISPN-14626 LINDEX command

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14879
=> [14.0] Upgrade console 14.0.10.final

documentation/src/main/asciidoc/topics/code_examples/AnalyzerDefinitions.java, documentation/src/main/asciidoc/topics/code_examples/BookIndexed.java, documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc, documentation/src/main/asciidoc/topics/proc_indexing_rebuilding.adoc, documentation/src/main/asciidoc/topics/proc_query_querying_hot_rod.adoc, documentation/src/main/asciidoc/topics/proc_query_using_analyzers.adoc, documentation/src/main/asciidoc/topics/protobuf/indexed_field.protobuf, documentation/src/main/asciidoc/topics/protobuf/indexed_text.protobuf, documentation/src/main/asciidoc/topics/protobuf/indexedperson.proto, documentation/src/main/asciidoc/topics/protobuf/testentity.proto, documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc
https://issues.redhat.com/browse/ISPN-14008
Infinispan indexing annotations
=> WIP:ISPN-14008 Docs indexing annotations

documentation/src/main/asciidoc/topics/code_examples/AnalyzerDefinitions.java, documentation/src/main/asciidoc/topics/code_examples/BookIndexed.java, documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc, documentation/src/main/asciidoc/topics/proc_indexing_rebuilding.adoc, documentation/src/main/asciidoc/topics/proc_query_querying_hot_rod.adoc, documentation/src/main/asciidoc/topics/proc_query_using_analyzers.adoc, documentation/src/main/asciidoc/topics/protobuf/indexed_field.protobuf, documentation/src/main/asciidoc/topics/protobuf/indexed_text.protobuf, documentation/src/main/asciidoc/topics/protobuf/indexedperson.proto, documentation/src/main/asciidoc/topics/protobuf/testentity.proto, documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc
backports #10785
https://issues.redhat.com/browse/ISPN-14008
=> [14.0.x] ISPN-14008 indexing annotations, query updates

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConnectionPoolConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/LockingTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/ClientListenerRetryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/size/HugeProtobufMessageTest.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/ConfigurationChildBuilder.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/ConnectionPoolConfiguration.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/ConnectionPoolConfigurationBuilder.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/HotRodConfiguration.java, documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/ISPN-14728
=> ISPN-14728 Hot Rod clients defaults modifications

query-core/src/main/java/org/infinispan/query/core/stats/IndexInfo.java, query/src/main/java/org/infinispan/query/stats/impl/LocalIndexStatistics.java, query/src/test/java/org/infinispan/query/reindex/LocalIndexerRemoveTest.java, server/rest/src/test/java/org/infinispan/rest/search/reindex/LocalRestIndexerRemoveTest.java
https://issues.redhat.com/browse/ISPN-14189
=> ISPN-14189 Wrong numbers are shown after clear/rebuild index action

server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MODULE.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14884
=> ISPN-14884 RESP MODULE

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CloseBeforeEnqueuingTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CrashMidOperationTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/AbstractRetryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/ClientListenerFailoverBusyTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/DistributionRetryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/InternalRemoteCacheManager.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelPool.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/HeaderDecoder.java
https://issues.redhat.com/browse/ISPN-14831
https://issues.redhat.com/browse/ISPN-14832
https://issues.redhat.com/browse/ISPN-14846
Backport #10892.
=> [14.0.x] ISPN-14832 Hot Rod client issues

core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java, core/src/test/java/org/infinispan/configuration/ConfigurationConversionTest.java
https://issues.redhat.com/browse/ISPN-14755
=> [14.0] ISPN-14755 Don't serialize empty role arrays

build/configuration/pom.xml, jboss-marshalling/pom.xml, object-filter/pom.xml, pom.xml, server/runtime/src/main/server/bin/common.sh, wildfly/feature-pack/pom.xml, wildfly/feature-pack/src/main/resources/modules/org/infinispan/slot/module.xml
https://issues.redhat.com/browse/ISPN-14824
=> [14.0] ISPN-14824 Open packages required by JBoss Marshalling River

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/TransactionalRemoteCacheImpl.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/APITest.java
https://issues.redhat.com/browse/ISPN-12142
Backport of #10967.
=> [14.0.x] ISPN-12142 Implement conditional methods for RemoteCache compute

core/src/main/java/org/infinispan/cache/impl/EncoderCache.java, core/src/main/java/org/infinispan/metadata/Metadata.java
https://issues.redhat.com/browse/ISPN-14530
=> [14.0] ISPN-14530 Override all wrapping methods in EncoderCache

core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceStatus.java, core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java, core/src/main/java/org/infinispan/reactive/publisher/impl/LocalPublisherManagerImpl.java, core/src/main/java/org/infinispan/reactive/publisher/impl/Notifications.java, core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java, core/src/test/java/org/infinispan/stream/LocalStreamIteratorExceptionTest.java
* Local target when shared store in use
* Reduce delivery guarantee for REPL and shared store on local node
https://issues.redhat.com/browse/ISPN-14887
=> ISPN-14887 Publisher prefer to stay local with shared store or REPL

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapListCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/ListBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/function/PollFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapListCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapListCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/ByteBufferUtils.java, server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java, server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LPOP.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/RPOP.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/internal/POP.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/MGET.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
https://issues.redhat.com/browse/ISPN-14638
=> ISPN-14638 RPOP and LPOP commands

client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfiguration.java
https://issues.redhat.com/browse/ISPN-14876
=> [14.0] ISPN-14876 Return proper value for context path property

core/src/main/java/org/infinispan/cache/impl/EncoderCache.java, documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXISTS.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14858
=> ISPN-14858 EXISTS command

server/resp/src/main/java/org/infinispan/server/resp/ByteBufferUtils.java, server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/STRALGO.java, server/resp/src/main/java/org/infinispan/server/resp/operation/LCSOperation.java, server/resp/src/main/java/org/infinispan/server/resp/response/LCSResponse.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/operation/OperationTest.java
https://issues.redhat.com/browse/ISPN-14653
This version is compatible with lettuce 6.x, syntax is:
STRALGO LCS KEYS key1 key2
=> ISPN-14653 LCS command

core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/main/java/org/infinispan/manager/EmbeddedCacheManager.java, core/src/main/java/org/infinispan/manager/impl/AbstractDelegatingEmbeddedCacheManager.java, core/src/main/java/org/infinispan/security/AuthorizationManager.java, core/src/main/java/org/infinispan/security/impl/AuthorizationManagerImpl.java, core/src/main/java/org/infinispan/security/impl/Authorizer.java, core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java, core/src/test/java/org/infinispan/security/RolePermissionNoACLCacheTest.java, core/src/test/java/org/infinispan/security/RolePermissionTest.java, server/core/src/main/java/org/infinispan/server/core/admin/AdminOperationsHandler.java, server/core/src/main/java/org/infinispan/server/core/admin/AdminServerTask.java, server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/CacheNamesTask.java, server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
https://issues.redhat.com/browse/ISPN-14718
=> ISPN-14718 Add EmbeddedCacheManager.getAccessibleCacheNames()

core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/main/java/org/infinispan/manager/EmbeddedCacheManager.java, core/src/main/java/org/infinispan/manager/impl/AbstractDelegatingEmbeddedCacheManager.java, core/src/main/java/org/infinispan/security/AuthorizationManager.java, core/src/main/java/org/infinispan/security/impl/AuthorizationManagerImpl.java, core/src/main/java/org/infinispan/security/impl/Authorizer.java, core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java, core/src/test/java/org/infinispan/security/RolePermissionNoACLCacheTest.java, core/src/test/java/org/infinispan/security/RolePermissionTest.java, server/core/src/main/java/org/infinispan/server/core/admin/AdminOperationsHandler.java, server/core/src/main/java/org/infinispan/server/core/admin/AdminServerTask.java, server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/CacheNamesTask.java, server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
https://issues.redhat.com/browse/ISPN-14718
=> [14.0] ISPN-14718 Add EmbeddedCacheManager.getAccessibleCacheNames()

server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespStringCommandsTest.java
https://issues.redhat.com/browse/ISPN-14898
=> ISPN-14898 Moved string tests on new file

.github/workflows/sync_docs.yml
Backport of https://github.com/infinispan/infinispan/pull/10984
=> [14.0.x] Docs: use setup mvn action in docs sync workflow

core/src/main/java/org/infinispan/globalstate/impl/OverlayLocalConfigurationStorage.java, core/src/main/java/org/infinispan/globalstate/impl/VolatileLocalConfigurationStorage.java, core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.redhat.com/browse/ISPN-14901
IMPORTANT NOTE:
The log severity of the class `org.infinispan.globalstate.impl.OverlayLocalConfigurationStorage` needs to be lowered to DEBUG in order to produce a log for the case where addressing here.
=> ISPN-14901 Check configuration present before to add

documentation/src/main/asciidoc/topics/code_examples/BookEmbedded.java, documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc, documentation/src/main/asciidoc/topics/proc_indexing_configuring.adoc, documentation/src/main/asciidoc/topics/proc_indexing_rebuilding.adoc, documentation/src/main/asciidoc/topics/proc_query_using_analyzers.adoc, documentation/src/main/asciidoc/topics/protobuf/library.proto, documentation/src/main/asciidoc/topics/ref_query_default_analyzers.adoc
=> [14.0.x]ISPN-14008 query and annotations docs review

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapListCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/ListBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/function/SetFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapListCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapListCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/MultimapTestUtils.java, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Resp3Command.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LSET.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
https://issues.redhat.com/browse/ISPN-14636
=> ISPN-14636 LSET command

documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc
=> [14.0.x]fix toc in the query guide

server/testdriver/core/src/main/java/org/infinispan/server/test/api/RespTestClientDriver.java, server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheQueries.java, server/tests/src/test/java/org/infinispan/server/functional/rest/RestLoggingResource.java, server/tests/src/test/java/org/infinispan/server/resilience/GracefulShutdownRestartIT.java, server/tests/src/test/java/org/infinispan/server/resilience/StatefulSetRollingUpgradeIT.java, server/tests/src/test/java/org/infinispan/server/security/AbstractAuthenticationKeyCloak.java, server/tests/src/test/java/org/infinispan/server/security/AuthenticationImplicitIT.java, server/tests/src/test/java/org/infinispan/server/security/AuthenticationKerberosIT.java, server/tests/src/test/java/org/infinispan/server/security/AuthenticationMultiEndpointIT.java, server/tests/src/test/java/org/infinispan/server/security/authentication/RestAuthentication.java
https://issues.redhat.com/browse/ISPN-14940
Added a timeout for closing the Lettuce client connection. And reducing the OkHttp threads leaking.
=> ISPN-14940 IT test suite failing in some executions

documentation/src/main/asciidoc/topics/code_examples/BookEmbedded.java, documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc, documentation/src/main/asciidoc/topics/proc_indexing_configuring.adoc, documentation/src/main/asciidoc/topics/proc_indexing_rebuilding.adoc, documentation/src/main/asciidoc/topics/proc_query_using_analyzers.adoc, documentation/src/main/asciidoc/topics/protobuf/library.proto, documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc, documentation/src/main/asciidoc/topics/ref_query_default_analyzers.adoc
Docs review of the query and indexing updates. Revision of indexing mode and index sharding (Infinispan 15 only)
=> ISPN-14008 query and annotations docs review

build/configuration/pom.xml, documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapListCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/ListBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/function/IndexOfFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapListCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapListCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LPOS.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
https://issues.redhat.com/browse/ISPN-14632
=> ISPN-14632 LPOS command

server/resp/src/main/java/org/infinispan/server/resp/BaseRespDecoder.java, server/resp/src/main/java/org/infinispan/server/resp/RespChannelInitializer.java, server/resp/src/main/java/org/infinispan/server/resp/RespHandler.java, server/resp/src/main/resources/resp.gr, server/resp/src/test/java/org/infinispan/server/resp/RespDecoderTest.java
* Decoder still needs to check auto read for multiple bytes in same read
https://issues.redhat.com/browse/ISPN-14809
=> ISPN-14809 RESP backpressure support

server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
https://issues.redhat.com/browse/ISPN-14718
=> [14.0] ISPN-14718 Also filter accessible cache names in REST endpoint

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapListCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/ListBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/function/InsertFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapListCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapListCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LINSERT.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
https://issues.redhat.com/browse/ISPN-14627
=> ISPN-14627 LINSERT command

server/hotrod/src/main/java/org/infinispan/server/hotrod/MultiHomedServerAddress.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/InetAddressWithNetMaskTest.java
https://issues.redhat.com/browse/ISPN-14854
=> [14.0] ISPN-14854 Do not bother matching addresses with different sizes

core/src/main/java/org/infinispan/container/versioning/irac/DefaultIracTombstoneManager.java, core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java, core/src/main/java/org/infinispan/factories/IracComponentFactory.java, core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java, core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyChangedState.java, core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyState.java, core/src/main/java/org/infinispan/xsite/irac/IracManagerStateTransferState.java, core/src/main/java/org/infinispan/xsite/irac/IracXSiteBackup.java, core/src/test/java/org/infinispan/xsite/irac/IracTombstoneUnitTest.java, core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java
https://issues.redhat.com/browse/ISPN-14960
=> ISPN-14960 IRAC: use BitSet to track updates

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapListCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/ListBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/function/RemoveCountFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapListCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapListCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LREM.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
https://issues.redhat.com/browse/ISPN-14635
=> ISPN-14635 LREM command

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/GETRANGE.java, server/resp/src/test/java/org/infinispan/server/resp/RespStringCommandsTest.java
continuation for
https://issues.redhat.com/browse/ISPN-14650
based on #10931
=> ISPN-14650 RESP GETRANGE

build/bom/pom.xml, cli-jakarta/pom.xml, cli-jakarta/src/main/java/org/infinispan/cli/package-info.java, client/rest-client-jakarta/pom.xml, client/rest-client-jakarta/src/main/java/org/infinispan/client/rest/package-info.java, pom.xml, server/testdriver/core-jakarta/pom.xml
https://issues.redhat.com/browse/ISPN-14736
=> [14.0] ISPN-14736 cli jakarta

client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java, core/src/main/java/org/infinispan/health/impl/CacheHealthImpl.java, documentation/src/main/asciidoc/topics/ref_rest_caches.adoc, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14958
=> ISPN-14958 Add health endpoint per cache

core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/persistence/PersistenceManagerAvailabilityTest.java, core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/impl/BaseJdbcStore.java
https://issues.redhat.com/browse/ISPN-13863
=> [13.0.x] PersistenceManager availability check fixes

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/ByteBufferUtils.java, server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespConstants.java, server/resp/src/main/java/org/infinispan/server/resp/RespTypes.java, server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/INFO.java, server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/SHARDS.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/COMMAND.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/ECHO.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/HELLO.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MEMORY.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/PTTL.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/SCAN.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TTL.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TYPE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LPOS.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/DEL.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14946 MEMORY USAGE
https://issues.redhat.com/browse/ISPN-14947 MEMORY STATS
https://issues.redhat.com/browse/ISPN-14951 TYPE
https://issues.redhat.com/browse/ISPN-14952 TTL
https://issues.redhat.com/browse/ISPN-14953 PTTL
This allows RedisInsight to work.
=> ISPN-14946/47/51/52/53 RESP MEMORY USAGE|STATS, TYPE, TTL, PTTL

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/SETRANGE.java, server/resp/src/test/java/org/infinispan/server/resp/RespStringCommandsTest.java
https://issues.redhat.com/browse/ISPN-14658
~~depends on #10966 and #10931~~
=> ISPN-14658 SETRANGE resp command

client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestServerClientOkHttp.java, documentation/src/main/asciidoc/topics/ref_rest_servers.adoc, server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java, server/tests/src/test/java/org/infinispan/server/functional/rest/RestServerResource.java
https://issues.redhat.com/browse/ISPN-14088
=> ISPN-14088 Endpoint to expose cache configuration default values

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapListCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/ListBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/function/TrimFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapListCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapListCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LTRIM.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
https://issues.redhat.com/browse/ISPN-14955
=>  ISPN-14955 LTRIM

build/configuration/pom.xml, client/rest-client-jakarta/pom.xml
https://issues.redhat.com/browse/ISPN-14969
=> [14.0] ISPN-14969 Elytron 1.20.4.Final

server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/FamilyCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/PING.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/FLUSHDB.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/SCAN.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LINDEX.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LINSERT.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LLEN.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LPOS.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LRANGE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LREM.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LSET.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LTRIM.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/internal/POP.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/internal/PUSH.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/internal/PUSHX.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SADD.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/APPEND.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/GETRANGE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/SETRANGE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/STRALGO.java
https://issues.redhat.com/browse/ISPN-14896
=> ISPN-14896 Validate argument size with arity

multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCache.java, multimap/src/main/java/org/infinispan/multimap/impl/HashMapBucket.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapPairCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HGET.java, server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java, server/tests/src/test/java/org/infinispan/server/security/authorization/RESPAuthorizationTest.java
https://issues.redhat.com/browse/ISPN-14663
=> ISPN-14663 HGET

query/src/main/java/org/infinispan/query/logging/Log.java, query/src/main/java/org/infinispan/query/stats/impl/LocalIndexStatistics.java, query/src/main/java/org/infinispan/search/mapper/mapping/SearchMapping.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/util/LazyRef.java, server/rest/src/test/java/org/infinispan/rest/search/reindex/RestReindexRemoveAndStatisticsTest.java
https://issues.redhat.com/browse/ISPN-14902
https://issues.redhat.com/browse/JDG-6256
=> ISPN-14902 Exception is thrown while rebuilding an index

multimap/proto.lock, multimap/src/main/java/org/infinispan/multimap/impl/SetBucket.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java
Fixes https://issues.redhat.com/browse/ISPN-14976
=> ISPN-14976 fix protostream serializer

multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/function/set/AddFunction.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/AddManyFunction.java
=> fix ids clash

multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/HashMapBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/function/hmap/HashMapKeySetFunction.java, multimap/src/main/java/org/infinispan/multimap/impl/function/hmap/HashMapValuesFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapPairCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HKEYS.java, server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HVALS.java, server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
https://issues.redhat.com/browse/ISPN-14666
https://issues.redhat.com/browse/ISPN-14674
=> ISPN-14666 + ISPN-14674 HKEYS and HVALS

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/AddManyFunction.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZCARD.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14609
=> ISPN-14609 ZCARD command

documentation/src/main/asciidoc/stories/assembly_hotrod_client_configuration.adoc, documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
[ISPN-14484](https://issues.redhat.com/browse/ISPN-14484)
mark opentelementry docs as community only in Infinispan14
=> [14.0.x]ISPN-14484 opentelemetry docs updates

documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
fix conditional, remove line breaks
=> [14.0.x]ISPN-14484 docs, fix conditional

documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
expand content that is community only
=> fix conditional

multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCache.java, multimap/src/main/java/org/infinispan/multimap/impl/HashMapBucket.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapPairCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HEXISTS.java, server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
https://issues.redhat.com/browse/ISPN-14662
=> ISPN-14662 HEXISTS

server/testdriver/core/src/main/java/org/infinispan/server/test/api/RespTestClientDriver.java
https://issues.redhat.com/browse/ISPN-15001
The `shutdown` method in Lettuce calls an unbounded `.get()` in the CF. https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/AbstractRedisClient.java#L521
Updating so we can call get with a timeout.
=> ISPN-15001 RespTestClientDriver blocks on shutdown

client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestClientOkHttp.java, server/runtime/src/main/java/org/infinispan/server/network/NetworkAddress.java, server/runtime/src/main/java/org/infinispan/server/state/ServerStateManagerImpl.java, server/tests/src/test/java/org/infinispan/server/functional/ProtocolManagementIT.java
https://issues.redhat.com/browse/ISPN-15010
=> ISPN-15010 Make ProtocolManagementIT more robust

build/configuration/pom.xml, cdi/remote/pom.xml, pom.xml
https://issues.redhat.com/browse/ISPN-15011
=> ISPN-15011 Remove Shrinkwrap resolver

cli/src/main/java/org/infinispan/cli/commands/rest/Principals.java, cli/src/main/java/org/infinispan/cli/commands/rest/Server.java, cli/src/main/resources/help/server.adoc, client/rest-client/src/main/java/org/infinispan/client/rest/RestSecurityClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestSecurityClientOkHttp.java, commons/all/src/main/java/org/infinispan/commons/dataconversion/internal/Json.java, documentation/src/main/asciidoc/topics/json/rest_security_principals.json, documentation/src/main/asciidoc/topics/ref_rest_server_security.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_list_principals.adoc, server/core/src/main/java/org/infinispan/server/core/ServerManagement.java, server/core/src/test/java/org/infinispan/server/core/DummyServerManagement.java, server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java, server/runtime/src/main/java/org/infinispan/server/Server.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/DistributedRealmConfiguration.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/RealmConfiguration.java, server/runtime/src/main/java/org/infinispan/server/security/realm/EncryptedPropertiesSecurityRealm.java, server/runtime/src/main/java/org/infinispan/server/security/realm/PropertiesSecurityRealm.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationPropertiesIT.java
https://issues.redhat.com/browse/ISPN-14709
=> ISPN-14709 REST API: /v2/security/principals

server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TYPE.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14951
=> ISPN-14951 RESP TYPE for list, hash, set, zset

server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/resp/src/main/java/org/infinispan/server/resp/Util.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIRE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIREAT.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIRETIME.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/PEXPIRETIME.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/PTTL.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TTL.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/SET.java, server/resp/src/main/java/org/infinispan/server/resp/operation/RespExpiration.java, server/resp/src/main/java/org/infinispan/server/resp/operation/SetOperation.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/SingleNodeRespBaseTest.java
https://issues.redhat.com/browse/ISPN-14978 EXPIRE
https://issues.redhat.com/browse/ISPN-14979 EXPIREAT
https://issues.redhat.com/browse/ISPN-14980 EXPIRETIME
https://issues.redhat.com/browse/ISPN-14981 PEXPIRETIME
Also use TimeService instead of relying on system time for more reliable testing
=> ISPN-14978 EXPIRE / ISPN-14979 EXPIREAT / ISPN-14980 EXPIRETIME / ISPN-14981 PEXPIRETIME

core/src/main/java/org/infinispan/metrics/impl/VendorAdditionalMetrics.java, core/src/test/java/org/infinispan/metrics/impl/VendorAdditionalMetricsTest.java
I've tested this with a locally build SNAPSHOT release and it works for me. I also added a test. Note that the metric names generated depend on the garbage collection algorithm used.
=> ISPN-14997 Filter illegal chars in pool names

core/src/test/resources/configs/xsite/bridge.xml
https://issues.redhat.com/browse/ISPN-15017
=> ISPN-15017 Configure FD protocols in test bridge.xml

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14992
=> [14.0] ISPN-14992 Spring Boot 3.1.1 and Spring Session 3.1.1

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14972
=> [14.0] ISPN-14972 Updates to console 14.0.11.Final

core/src/main/java/org/infinispan/marshall/core/EncoderRegistryImpl.java
Eliminate stream creation in EncoderRegistryImpl.getEncoder.
https://issues.redhat.com/browse/ISPN-14991
=> ISPN-14991 Eliminate stream from getEncoder

core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java
https://issues.redhat.com/browse/ISPN-14982
Note for the reviewer, the `StateConsumerTest` was refactored to extract common code to static methods. The method `test2` replicates the issue.
=> ISPN-14982 State transfer never completes

documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc, documentation/src/main/asciidoc/topics/protobuf/indexed_field.protobuf
https://issues.redhat.com/browse/ISPN-14529
=> ISPN-14529 query docs: clarify attributes for sorting queries

server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14957
=> ISPN-14957 Allow to get internal cache info using rest

server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14957
Backport of #11041
=> [14.0] ISPN-14957 Allow to get internal cache info using rest

core/src/main/java/org/infinispan/metrics/impl/VendorAdditionalMetrics.java, core/src/test/java/org/infinispan/metrics/impl/VendorAdditionalMetricsTest.java
This is a backport of #11064 to 14.0.x
@fax4ever - I'd be happy if you could review this as well. Thanks!
=> [14.0] ISPN-14997 Filter illegal chars in pool names

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15020
=> ISPN-15020 Updates server console to dev02

server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceQueryAction.java
=> ISPN-14195 Fix security action getting query configuration

core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java
https://issues.redhat.com/browse/ISPN-14982
Note for the reviewer, the `StateConsumerTest` was refactored to extract common code to static methods. The method `test2` replicates the issue.
=> [14.x] ISPN-14982 State transfer never completes

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/PopFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapSortedSetCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZPOPMAX.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZPOPMIN.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/internal/POP.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14615
=>  ISPN-14615 ZPOPMAX, ZPOPMIN

query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java, query/src/main/java/org/infinispan/query/logging/Log.java, query/src/main/java/org/infinispan/query/stats/impl/LocalIndexStatistics.java, query/src/main/java/org/infinispan/search/mapper/mapping/SearchMapping.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/util/LazyRef.java, server/rest/src/test/java/org/infinispan/rest/search/reindex/RestReindexRemoveAndStatisticsTest.java
https://issues.redhat.com/browse/ISPN-14902
https://issues.redhat.com/browse/JDG-6256
Backport of https://github.com/infinispan/infinispan/pull/10992
=> [14.0.x] ISPN-14902 Exception is thrown while rebuilding an index

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/test/java/org/infinispan/multimap/impl/DistributedSetTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/GETEX.java, server/resp/src/main/java/org/infinispan/server/resp/operation/GetexOperation.java, server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
GETEX operation
https://issues.redhat.com/browse/ISPN-14649
=> ISPN-14649 GETEX operation.

build/configuration/pom.xml, pom.xml
https://issues.redhat.com/browse/ISPN-15028
=> ISPN-15028 Use an alternate mirror for the owasp-dependency-check plugin

multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/HashMapBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/function/hmap/HashMapRemoveFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapPairCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HDEL.java, server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HGETALL.java, server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
https://issues.redhat.com/browse/ISPN-14664
https://issues.redhat.com/browse/ISPN-14661
=> ISPN-14664 + ISPN-14661 HGETALL and HDEL

query/src/main/java/org/infinispan/query/impl/massindex/IndexUpdater.java, query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java, query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerProgressMonitor.java, query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerProgressNotifier.java, query/src/main/java/org/infinispan/query/logging/Log.java
https://issues.redhat.com/browse/ISPN-14977
https://issues.redhat.com/browse/JDG-5994
=> ISPN-14977 Log ProtoStream entities on reindexing operations

query/src/main/java/org/infinispan/query/impl/massindex/IndexUpdater.java, query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java, query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerProgressMonitor.java, query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerProgressNotifier.java, query/src/main/java/org/infinispan/query/logging/Log.java
https://issues.redhat.com/browse/ISPN-14977
https://issues.redhat.com/browse/JDG-5994
Backport of #11044
=> [14.0] ISPN-14977 Log ProtoStream entities on reindexing operations

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/ScoreFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapSortedSetCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZSCORE.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14623
=> ISPN-14623 ZSCORE

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/consistenthash/CRC16ConsistentHashV2.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/consistenthash/ConsistentHashV2.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ConsistentHashFactoryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ConsistentHashPerformanceTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ConsistentHashV2Test.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/consistenthash/CRC16ConsistentHashV2.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/consistenthash/ConsistentHash.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/consistenthash/ConsistentHashV2.java, core/src/main/java/org/infinispan/configuration/cache/HashConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/HashConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java, core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java, core/src/main/java/org/infinispan/distribution/ch/impl/CRC16HashFunctionPartitioner.java, core/src/main/java/org/infinispan/distribution/ch/impl/HashFunctionPartitioner.java, core/src/main/resources/schema/infinispan-config-15.0.xsd, core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java, core/src/test/resources/configs/all/15.0.xml, graalvm/core/src/main/java/org/infinispan/graalvm/NativeMetadataProvider.java, server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/resp/src/test/java/org/infinispan/server/resp/BaseMultipleRespTest.java, server/resp/src/test/java/org/infinispan/server/resp/SingleNodeRespBaseTest.java
https://issues.redhat.com/browse/ISPN-14834
Applying suggestions from #10901.
We provide a new key partitioner implementation, `CRC16HashFunctionPartitioner`.
=> ISPN-14834 Implement CRC16 for hash function option

documentation/src/main/asciidoc/topics/proc_configuring_server_fips.adoc, documentation/src/main/asciidoc/topics/streams.adoc
=> Docs broken links fix

documentation/src/main/asciidoc/topics/proc_configuring_server_fips.adoc, documentation/src/main/asciidoc/topics/streams.adoc
=> [14.0.x] Docs broken links fix

documentation/src/main/asciidoc/topics/proc_configuring_server_fips.adoc, documentation/src/main/asciidoc/topics/streams.adoc
=> [13.0.x] Docs broken links fix

Jenkinsfile, Jenkinsfile-release, build/configuration/pom.xml, etc/dependency-check-suppressions.xml, pom.xml
=> Maven deploy settings 14.0.x

core/src/main/java/org/infinispan/configuration/global/GlobalStateConfiguration.java, core/src/main/java/org/infinispan/configuration/global/GlobalStateConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/global/UncleanShutdownAction.java, core/src/main/java/org/infinispan/configuration/parsing/Attribute.java, core/src/main/java/org/infinispan/configuration/parsing/Parser.java, core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java, core/src/main/java/org/infinispan/globalstate/impl/GlobalStateManagerImpl.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/main/resources/schema/infinispan-config-15.0.xsd, core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java, core/src/test/resources/configs/all/15.0.xml, documentation/src/main/asciidoc/topics/con_global_persistent_location.adoc, documentation/src/main/asciidoc/topics/upgrading.adoc, server/tests/src/test/resources/configuration/PersistenceTest.xml, server/tests/src/test/resources/configuration/cache-container/clustered-ignore-unclean.xml
https://issues.redhat.com/browse/ISPN-15059
=> ISPN-15059 Support different ways to handle unclean shutdowns

documentation/src/main/asciidoc/topics/xml/jgroups_stack_extends.xml
https://issues.redhat.com/browse/ISPN-15062
=> [14.0] ISPN-15062 Customizing JGroups stack example xml is invalid

cli/src/main/java/org/infinispan/cli/commands/rest/Roles.java, cli/src/main/resources/help/user.adoc, client/rest-client/src/main/java/org/infinispan/client/rest/RestSecurityClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestSecurityClientOkHttp.java, documentation/src/main/asciidoc/topics/json/rest_security_roles_permissions.json, documentation/src/main/asciidoc/topics/ref_rest_server_security.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_create.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_delete.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_get.adoc, server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java, server/tests/src/test/java/org/infinispan/server/security/authorization/RESTAuthorizationTest.java, server/tests/src/test/resources/configuration/cache-container/clustered-authz.xml
https://issues.redhat.com/browse/ISPN-15043
=> ISPN-15043 REST/CLI describe role

core/src/main/java/org/infinispan/stats/impl/AbstractClusterStats.java, core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java, core/src/main/java/org/infinispan/stats/impl/ClusterContainerStatsImpl.java
https://issues.redhat.com/browse/ISPN-15042
=> ISPN-15042 Do not collect clustered stats in some conditions

persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
https://issues.redhat.com/browse/ISPN-13666
=> ISPN-13666 RemoteStore leaks out netty event loop client threads

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetSubsetArgs.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/CountFunction.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/SubsetFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapSortedSetCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/MultimapTestUtils.java, server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/SortedSetArgumentsUtils.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZADD.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZCOUNT.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZRANGE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZRANGEBYLEX.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZRANGEBYSCORE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZREVRANGE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZREVRANGEBYLEX.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZREVRANGEBYSCORE.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14618
=> ISPN-14618 ZRANGE

persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
https://issues.redhat.com/browse/ISPN-13666
=> [14.0] ISPN-13666 RemoteStore leaks out netty event loop client threads

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/Util.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/Util.java
I found similar code in two places, so I updated both. Please comment if only one of them should have been updated.
=> ISPN-15041 Preserve stack traces to caller to simplify debugging

documentation/src/main/asciidoc/topics/con_server_directory_structure.adoc, documentation/src/main/asciidoc/topics/proc_downloading_server.adoc
Fix attribute for linking to server readme
=> [13.0.x]fix server readme link

documentation/src/main/asciidoc/stories/assembly_server_statistics.adoc, documentation/src/main/asciidoc/topics/con_server_directory_structure.adoc, documentation/src/main/asciidoc/topics/proc_downloading_server.adoc
* fix build for server guide - remove reference to content that was removed
* fix link to server readme
=> [12.1.x]Fixes broken links in docs 12

documentation/src/main/asciidoc/topics/con_server_directory_structure.adoc, documentation/src/main/asciidoc/topics/proc_downloading_server.adoc
=> [11.0.x]fix server readme link

core/src/main/resources/schema/infinispan-config-14.0.xsd, documentation/src/main/asciidoc/topics/con_performance_indexing_querying.adoc, documentation/src/main/asciidoc/topics/ref_query_ickle.adoc, documentation/src/main/asciidoc/topics/ref_rest_caches_query.adoc
Docs review of
https://issues.redhat.com/browse/ISPN-14195
backports #11146
=> [14.0.x] Docs review Query hit count efficiency

core/src/main/resources/schema/infinispan-config-15.0.xsd, documentation/src/main/asciidoc/topics/con_performance_indexing_querying.adoc, documentation/src/main/asciidoc/topics/hotrod_protocol.adoc, documentation/src/main/asciidoc/topics/ref_query_ickle.adoc, documentation/src/main/asciidoc/topics/ref_rest_caches_query.adoc
Docs review of 
https://issues.redhat.com/browse/ISPN-14195
https://issues.redhat.com/browse/ISPN-14203
=> Docs review Query hit count accuracy

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetAddArgs.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetSubsetArgs.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/AddManyFunction.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/CountFunction.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/SubsetFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapSortedSetCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZADD.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZRANGE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZRANGESTORE.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-15047
=> ISPN-15047 ZRANGESTORE

multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/IndexOfSortedSetFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZRANK.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZREVRANK.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14619
=> ISPN-14619 ZRANK and ZREVRANK

multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/ScoreFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZMSCORE.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14616
=> ISPN-14616 ZMSCORE

documentation/src/main/asciidoc/topics/con_declarative_cache_configuration.adoc, documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc
https://issues.redhat.com/browse/ISPN-14744
=> ISPN-14744 docs follow up

documentation/src/main/asciidoc/topics/con_declarative_cache_configuration.adoc, documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc
https://issues.redhat.com/browse/ISPN-14744 
backports #11157
=> [14.x]ISPN-14744-14

documentation/src/main/asciidoc/stories/assembly_hotrod_client_configuration.adoc, documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
This reverts commit 30ac15f6e77f0846db5f525915935d78311dedfb. #11068
=> Revert "ISPN-14484 mark opentelementry as community only in ispn 14

documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
https://issues.redhat.com/browse/ISPN-15009
Follow up on https://issues.redhat.com/browse/ISPN-14718 
=> ISPN-15009 docs update mask secured caches by role

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZCOUNT.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZDIFF.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZDIFFSTORE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZRANGE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZSetCommonUtils.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/internal/DIFF.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14611
=> ISPN-14611 ZDIFF and ZDIFFSTORE

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15014
https://issues.redhat.com/browse/ISPN-15013
=> [14.0] ISPN-15014 CVE fix netty and jackson upgrade

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetAddArgs.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/IncrFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapSortedSetCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZADD.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZINCRBY.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14612
=> ISPN-14612 ZINCRBY + ZADD INCR option

server/resp/src/main/java/org/infinispan/server/resp/ByteBufferUtils.java, server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java, server/resp/src/main/java/org/infinispan/server/resp/commands/CONFIG.java, server/resp/src/main/java/org/infinispan/server/resp/commands/INFO.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/CLIENT.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/COMMAND.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/HELLO.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MEMORY.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MODULE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/PING.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/RESET.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/SELECT.java, server/resp/src/main/java/org/infinispan/server/resp/commands/iteration/BaseIterationCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/pubsub/PSUBSCRIBE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/pubsub/PUBLISH.java, server/resp/src/main/java/org/infinispan/server/resp/commands/pubsub/PUNSUBSCRIBE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/DEL.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/MGET.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/MSET.java
https://issues.redhat.com/browse/ISPN-15067
Also made some changes to prevent String concatenation for integer using more efficient write
=> ISPN-15067 All RESP handlers should use ASCII string whenever possible

core/src/main/resources/schema/infinispan-config-15.0.xsd
https://issues.redhat.com/browse/ISPN-15080
=> ISPN-15080 Fix name-as-tags default in XSD

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14994
=> ISPN-14994 JGroups 5.2.17.Final

build/configuration/pom.xml, core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
https://issues.redhat.com/browse/ISPN-14780
Depends on https://github.com/infinispan/infinispan/pull/11181
=> ISPN-14780 JGroups config of nested values are not applied

commons/all/src/main/java/org/infinispan/commons/logging/Log.java, documentation/src/main/asciidoc/topics/proc_server_enabling_resp.adoc, documentation/src/main/asciidoc/topics/upgrading.adoc, server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/resp/src/test/java/org/infinispan/server/resp/RespMediaTypesTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespServerTest.java, server/resp/src/test/java/org/infinispan/server/resp/SingleNodeRespBaseTest.java
https://issues.redhat.com/browse/ISPN-15068
=> ISPN-15068 RESP Server should always use OCTET key media type storage

core/src/main/java/org/infinispan/configuration/parsing/ParserRegistry.java
https://issues.redhat.com/browse/ISPN-15078
=> ISPN-15078 ParserRegistry.parse(InputStream is, MediaType mediaType)

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15092
=> ISPN-15092 Apache SSHD 2.10.0

core/src/main/java/org/infinispan/distribution/ch/ConsistentHash.java, core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHash.java, core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHash.java, core/src/main/java/org/infinispan/distribution/ch/impl/ScatteredConsistentHash.java, core/src/main/java/org/infinispan/scattered/impl/BiasManagerImpl.java, core/src/main/java/org/infinispan/scattered/impl/ScatteredStateProviderImpl.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
https://issues.redhat.com/browse/ISPN-13105
=> [9.4] ISPN-13105 ConsistentHash.getPrimarySegmentsForOwner() throws an IAE

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15092
=> [14.0.x] ISPN-15092 Apache SSHD 2.10.0

Jenkinsfile, Jenkinsfile-release, distribution/pom.xml
* Increased memory to 1.5G
* Added URL to maven-deploy-plugin:deploy-file
=> Jenkins changes

build/configuration/pom.xml, graalvm/core/pom.xml
https://issues.redhat.com/browse/ISPN-15101
CI also upgraded to use GraalVM community edition 20.0.2.
=> ISPN-15101 Quarkus 3.2.3.Final

Jenkinsfile, Jenkinsfile-release, distribution/pom.xml
* ~~Use JDK 21~~
* Increased memory from 1G to 1.5G
* Removed old stage
Using JDK 21 requires some code changes for another time :+1:
=> [14.0x.] Jenkins changes

build/bom/pom.xml, multimap-jakarta/pom.xml, multimap-jakarta/src/main/java/org/infinispan/multimap/package-info.java, pom.xml, server/hotrod-jakarta/pom.xml
https://issues.redhat.com/browse/ISPN-15106
=> [14.0] ISPN-15106 Multimap Jakarta

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/DISCARD.java, server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java
https://issues.redhat.com/browse/ISPN-14642
The last command.
=> ISPN-14642 DISCARD

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZINTERCARD.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14613
=> ISPN-14613 ZINTERCARD

core/src/main/java/org/infinispan/factories/impl/MBeanMetadata.java, core/src/main/java/org/infinispan/metrics/Constants.java, core/src/main/java/org/infinispan/metrics/impl/AbstractMetricsRegistration.java, core/src/main/java/org/infinispan/metrics/impl/CustomMetricsSupplier.java, core/src/main/java/org/infinispan/metrics/impl/MetricUtils.java, core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java, core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java, core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java, core/src/main/java/org/infinispan/xsite/status/TakeOfflineManager.java, documentation/src/main/asciidoc/topics/upgrading.adoc
Backport (and more info): https://github.com/infinispan/infinispan/pull/11194
Depends on https://github.com/infinispan/infinispan/pull/11228 due to conflicts.
https://issues.redhat.com/browse/ISPN-15032
=> [14.x] ISPN-15032 Use site and channel names as tag for metrics

core/src/main/java/org/infinispan/interceptors/impl/BaseStateTransferInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/ClusteringInterceptor.java, core/src/test/java/org/infinispan/remoting/RemoteShutdownDuringOperationTest.java
https://issues.redhat.com/browse/ISPN-15126
=> ISPN-15126 Touch command not handling SuspectException

documentation/src/main/asciidoc/topics/con_server_endpoints.adoc
https://issues.redhat.com/browse/ISPN-15134
Update statement about future memcached implementation
=> [14.0.x]ISPN-15134 update statement about memcached in Infinispan 15

server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/CounterIncOrDec.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/DECRBY.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/INCRBY.java
https://issues.redhat.com/browse/ISPN-15133
=> ISPN-15133 Avoid parsing strings on incr operations

build/configuration/pom.xml, core/src/test/java/org/infinispan/stats/SingleStatsTest.java
https://issues.redhat.com/browse/ISPN-15132
=> ISPN-15132 Updates to protostream 4.6.4.Final

server/runtime/src/main/server/README.adoc, server/runtime/src/main/server/server/conf/infinispan-dev-mode.xml, server/runtime/src/main/server/server/conf/infinispan-xsite.xml
https://issues.redhat.com/browse/ISPN-15008
=> ISPN-15008 add overview of config files in the server README

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/SetBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/function/set/SRemoveFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedSetTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SADD.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SMEMBERS.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SMOVE.java, server/resp/src/main/java/org/infinispan/server/resp/logging/Log.java, server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
SMOVE. https://issues.redhat.com/browse/ISPN-14599
based on SINTER #11035
=> Smove 14599

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15144
=> [14.0] ISPN-15144 Protostream 4.6.5.Final

core/src/test/java/org/infinispan/stats/SingleStatsTest.java
* Change test back to a lower size estimate|
https://issues.redhat.com/browse/ISPN-15144
=> ISPN-15144 Protostream 4.6.5

core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java, server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestMetricsOperations.java, server/tests/src/test/resources/configuration/XSiteServerTest.xml, server/tests/src/test/resources/configuration/cache-container/clustered-metric-names-as-tags.xml
* avoid name clashing
* 
https://issues.redhat.com/browse/ISPN-15155
=> ISPN-15155 Missing cross-site metrics

core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java, server/runtime/src/main/java/org/infinispan/server/Server.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractServerConfigBuilder.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanServerTestConfiguration.java, server/tests/src/test/java/org/infinispan/server/functional/AbstractMultiClusterIT.java, server/tests/src/test/java/org/infinispan/server/functional/DuplicateTemplateIT.java, server/tests/src/test/resources/data/templates.xml
https://issues.redhat.com/browse/ISPN-15151
=> [14.0.x]  ISPN-15151 Unable to upgrade if a backup has been restored on the older server

core/src/main/java/org/infinispan/executors/DefaultExecutorFactory.java
https://issues.redhat.com/browse/ISPN-15147
=> ISPN-15147 DefaultExecutorFactory can create multiple ThreadGroups

build/configuration/pom.xml, quarkus/cli/pom.xml
~Let's see what breaks :slightly_smiling_face:~
Good to go!
https://issues.redhat.com/browse/ISPN-15159
=> Quarkus 3.3.1

core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteRestMetricsOperations.java, server/tests/src/test/resources/configuration/XSiteServerTest.xml, server/tests/src/test/resources/configuration/cache-container/clustered-metric-names-as-tags.xml
* avoid name clashing
https://issues.redhat.com/browse/ISPN-15155
=> [14.x] ISPN-15155 Missing cross-site metrics

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/SetBucket.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedSetTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SINTER.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SUNION.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SUNIONSTORE.java, server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14603
based on ~~#11048~~
=> ISPN-14603 SUNION SUNIONSTORE commands

documentation/src/main/asciidoc/stories/assembly_migrating_data.adoc, documentation/src/main/asciidoc/topics/upgrading.adoc
Add information about mapping HS5 annotations to Infinispan native annotations
=> ISPN-15111 mapping of HS5 annotations to Infinispan native

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/function/set/SPopFunction.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SPOP.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SRANDMEMBER.java, server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14600
based on ~~#11239~~
=> ISPN-14600 SPOP SRANDMEMBER

documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc, quarkus/server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/SubstituteElytronClasses.java, server/runtime/src/main/java/org/infinispan/server/Server.java, server/runtime/src/main/java/org/infinispan/server/security/ElytronJMXAuthenticator.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/JmxTestClient.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedServer.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestClient.java, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestMethodRule.java, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanXSiteServerTestMethodRule.java, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/AbstractServerExtension.java, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerExtension.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationJMXIT.java, server/tests/src/test/resources/configuration/AuthorizationJMXTest.xml, server/tests/src/test/resources/configuration/cache-container/clustered-authz-jmx.xml
https://issues.redhat.com/browse/ISPN-15026
Missing tests and docs. @ryanemerson see if this works for your needs
=> ISPN-15026 Automatically map ADMIN and MONITOR permissions to JMX roles

documentation/src/main/asciidoc/topics/con_cache_store_sql.adoc
https://issues.redhat.com/browse/ISPN-15124
=> ISPN-15124 Better describe SQL store limitations

core/src/main/java/org/infinispan/interceptors/distribution/L1NonTxInterceptor.java, core/src/main/java/org/infinispan/util/concurrent/CompletionStages.java
https://issues.redhat.com/browse/ISPN-11125
=> ISPN-11125 Convert L1 to be non blocking

core/src/main/java/org/infinispan/persistence/sifs/FileProvider.java
https://issues.redhat.com/browse/ISPN-15169
=> ISPN-15169 SIFS PMEM logs exception every file opening in dev

core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java
https://issues.redhat.com/browse/ISPN-15166
=> ISPN-15166 SIFS rebuild index cannot compact file

quarkus/embedded/runtime/pom.xml
https://issues.redhat.com/browse/ISPN-15178
=> ISPN-15178 Add ProtoStream dependencies

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/core/src/main/java/org/infinispan/server/iteration/list/ListIterationInitializationContext.java, server/core/src/main/java/org/infinispan/server/iteration/list/ListStreamSupplier.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZSCAN.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14622
=> ISPN-14622 ZSCAN

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15182
=> ISPN-15182 Quarkus 3.3.3

core/src/main/java/org/infinispan/notifications/cachemanagerlistener/CacheManagerNotifier.java, core/src/main/java/org/infinispan/notifications/cachemanagerlistener/CacheManagerNotifierImpl.java, core/src/main/java/org/infinispan/notifications/cachemanagerlistener/annotation/SiteViewChanged.java, core/src/main/java/org/infinispan/notifications/cachemanagerlistener/event/Event.java, core/src/main/java/org/infinispan/notifications/cachemanagerlistener/event/SitesViewChangedEvent.java, core/src/main/java/org/infinispan/notifications/cachemanagerlistener/event/impl/EventImpl.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/xsite/GlobalXSiteAdminOperations.java, core/src/test/java/org/infinispan/notifications/cachemanagerlistener/CacheManagerListener.java, core/src/test/java/org/infinispan/notifications/cachemanagerlistener/CacheManagerNotifierImplTest.java, core/src/test/java/org/infinispan/xsite/statetransfer/XSiteAutoStateTransferTest.java
https://issues.redhat.com/browse/ISPN-15179
=> ISPN-15179 Create cross-site view cache manager event

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SSCAN.java, server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14601
Based on HSCAN, the content set is turned into a map to respect the iterator framwrk style
=> ISPN-14601 SSCAN resp command

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15185
=> ISPN-15185 Updates console to 15.0.0.Dev03

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SDIFF.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SDIFFSTORE.java, server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14596
=> SDIFF-14596 SDIFF resp command

commons/all/src/main/java/org/infinispan/commons/hash/CRC16.java, core/src/main/java/org/infinispan/distribution/ch/impl/CRC16HashFunctionPartitioner.java, core/src/main/java/org/infinispan/distribution/ch/impl/HashFunctionPartitioner.java, server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java, server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java, server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/INFO.java, server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/CLUSTER.java, server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/KEYSLOT.java, server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/SLOTS.java, server/resp/src/main/java/org/infinispan/server/resp/commands/pubsub/SUBSCRIBE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/WATCH.java, server/resp/src/main/java/org/infinispan/server/resp/filter/EventListenerKeysFilter.java, server/resp/src/test/java/org/infinispan/server/resp/RespMediaTypesTest.java, server/resp/src/test/java/org/infinispan/server/resp/SlotDistributionTest.java, server/resp/src/test/java/org/infinispan/server/resp/types/DataStructuresMediaTypesTest.java, server/resp/src/test/java/org/infinispan/server/resp/types/TransactionMediaTypeTest.java, server/tests/src/test/java/org/infinispan/server/functional/resp/RespTransactionTest.java, server/tests/src/test/java/org/infinispan/server/security/authorization/RESPAuthorizationTest.java
https://issues.redhat.com/browse/ISPN-15075
* Including fixes and tests for CRC16;
* Added cluster keyslot command for verification;
* Added distributed tests and all fixes.
=> ISPN-15075 Cluster mode for tx commands

core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFileStatsTest.java
https://issues.redhat.com/browse/ISPN-15184
=> ISPN-15184 SIFS can leave many data files left around

core/src/main/java/org/infinispan/factories/AuthorizationManagerFactory.java, core/src/main/java/org/infinispan/security/AuthorizationManager.java, core/src/main/java/org/infinispan/security/impl/AuthorizationManagerImpl.java, core/src/main/java/org/infinispan/security/impl/PermissiveAuthorizationManager.java, core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java, server/runtime/src/main/java/org/infinispan/server/tasks/ServerTaskEngine.java, server/tests/src/test/java/org/infinispan/server/security/authorization/HotRodAuthorizationTest.java, server/tests/src/test/java/org/infinispan/server/security/authorization/RESTAuthorizationTest.java, tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingManagerImpl.java, tasks/scripting/src/test/java/org/infinispan/scripting/SecureScriptingTest.java
https://issues.redhat.com/browse/ISPN-14985
https://issues.redhat.com/browse/ISPN-14986
=> ISPN-14985 CVE-2023-3628 / ISPN-14986 CVE-2023-3629

build/configuration/pom.xml, javadoc/pom.xml
https://issues.redhat.com/browse/ISPN-15192
=> ISPN-15192 Brand JavaDoc header and window title

server/testdriver/core/src/main/java/org/infinispan/server/test/core/Containers.java
https://issues.redhat.com/browse/ISPN-15195
=>  ISPN-15195  Support x86_64 for mac

core/src/main/java/org/infinispan/factories/AuthorizationManagerFactory.java, core/src/main/java/org/infinispan/security/AuthorizationManager.java, core/src/main/java/org/infinispan/security/impl/AuthorizationManagerImpl.java, core/src/main/java/org/infinispan/security/impl/PermissiveAuthorizationManager.java, core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/main/java/org/infinispan/rest/resources/SecurityActions.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java, server/runtime/src/main/java/org/infinispan/server/tasks/ServerTaskEngine.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java, tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingManagerImpl.java, tasks/scripting/src/test/java/org/infinispan/scripting/SecureScriptingTest.java
https://issues.redhat.com/browse/ISPN-14985
https://issues.redhat.com/browse/ISPN-14986
=> [14.0] ISPN-14985 CVE-2023-3628 / ISPN-14986 CVE-2023-3629

core/src/main/java/org/infinispan/interceptors/distribution/L1NonTxInterceptor.java, core/src/main/java/org/infinispan/util/concurrent/CompletionStages.java
https://issues.redhat.com/browse/ISPN-11125
=> [14.0] ISPN-11125 Convert L1 to be non blocking

server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/resp/src/main/java/org/infinispan/server/resp/RespTypes.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TYPE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/iteration/BaseIterationCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/iteration/IterationArguments.java, server/resp/src/main/java/org/infinispan/server/resp/filter/ComposedFilterConverter.java, server/resp/src/main/java/org/infinispan/server/resp/filter/ComposedFilterConverterFactory.java, server/resp/src/main/java/org/infinispan/server/resp/filter/GlobMatchFilterConverterFactory.java, server/resp/src/main/java/org/infinispan/server/resp/filter/RespTypeFilterConverter.java, server/resp/src/main/java/org/infinispan/server/resp/filter/RespTypeFilterConverterFactory.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-15188
* Created a filter by RESP type;
* Created a composite filter, so we can aggregate the existing filters.
=> ISPN-15188 SCAN should be able to filter by type

persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreConfigTest.java, persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreConfigWithContainersTest.java, persistence/remote/src/test/resources/remotestore-with-containers.xml
https://issues.redhat.com/browse/ISPN-15205
Using a random free port instead.
=> ISPN-15205 RemoteStoreConfigWithContainersTest test failure

core/src/main/java/org/infinispan/factories/threads/BlockingThreadFactory.java, core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadFactory.java
https://issues.redhat.com/browse/ISPN-15147
=> [11.0] ISPN-15147 DefaultExecutorFactory can create multiple ThreadGroups

documentation/src/main/asciidoc/topics/json/rest_full_cache_detail.json, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-15199
=> ISPN-15199 Expose needed parameters for the console

core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java, core/src/main/java/org/infinispan/xsite/XSiteCacheMapper.java, core/src/main/java/org/infinispan/xsite/events/XSiteEvent.java, core/src/main/java/org/infinispan/xsite/events/XSiteEventSender.java, core/src/main/java/org/infinispan/xsite/events/XSiteEventType.java, core/src/main/java/org/infinispan/xsite/events/XSiteEventsManagerImpl.java, core/src/main/java/org/infinispan/xsite/response/AutoStateTransferResponseCollector.java, core/src/main/java/org/infinispan/xsite/statetransfer/NoOpXSiteStateTransferManager.java, core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferManager.java, core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferManagerImpl.java, core/src/test/java/org/infinispan/xsite/statetransfer/AbstractDelegatingXSiteStateTransferManager.java, core/src/test/java/org/infinispan/xsite/statetransfer/ControlledXSiteStateTransferManager.java, core/src/test/java/org/infinispan/xsite/statetransfer/XSiteAutoStateTransferTest.java, documentation/src/main/asciidoc/topics/con_xsite_state_transfer.adoc
Listens to CacheStarted events and if the cache has an async backup to SiteB, then it requests state.
https://issues.redhat.com/browse/ISPN-12989
=> ISPN-12989 Initial state transfer for cross-site replication

integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/remote/RemoteSpringSessionTest.java
=> [14.0] RemoteSpringSessionTest fix

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15223
=> [14.0] ISPN-15223 updates console to 14.0.12.Final

core/src/main/java/org/infinispan/configuration/parsing/SFSToSIFSStore.java, core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java, core/src/main/java/org/infinispan/persistence/sifs/TemporaryTable.java, core/src/main/java/org/infinispan/util/concurrent/CompletionStages.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreStressTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreTest.java, core/src/test/java/org/infinispan/test/Mocks.java
https://issues.redhat.com/browse/ISPN-15186
https://issues.redhat.com/browse/ISPN-15196
https://issues.redhat.com/browse/ISPN-15222
Also includes the issue where the compactor can attempt to compact an entry that does not have an index yet due to timing.
=> ISPN-15186 SIFS may not shut down properly with compactor still running

core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
https://issues.redhat.com/browse/ISPN-15208
=> [14.0.x] ISPN-15208 IRAC state transfer may skip data

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15228
=> [14.0] ISPN-15223 updates console to 14.0.13.Final

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15229
=> [14.0] ISPN-15229 CVE-2023-4487 HTTP/2 Rapid Reset Attack

build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15229
=> [13.0] ISPN-15229 CVE-2023-4487 HTTP/2 Rapid Reset Attack

build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15229
=> [12.0] ISPN-15229 CVE-2023-4487 HTTP/2 Rapid Reset Attack

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15229
=> ISPN-15229 CVE-2023-4487 HTTP/2 Rapid Reset Attack

build-configuration/pom.xml, cloudevents-integration/pom.xml
https://issues.redhat.com/browse/ISPN-15092
https://issues.redhat.com/browse/ISPN-15235
https://issues.redhat.com/browse/ISPN-15234
=> [12.1] Various CVEs

server/core/src/main/java/org/infinispan/server/core/dataconversion/XMLTranscoder.java
https://issues.redhat.com/browse/ISPN-15236
=> ISPN-15236 Lazily instantiate XStream in XMLTranscoder

core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java
https://issues.redhat.com/browse/ISPN-15214
Cleanup some IDE warnings from `StateConsumerImpl`.
=> ISPN-15214 Do not instantiate TriangleOrderManager if not required.

cli/src/main/java/org/infinispan/cli/commands/rest/Roles.java, client/rest-client/src/main/java/org/infinispan/client/rest/RestSecurityClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestSecurityClientOkHttp.java, core/src/main/java/org/infinispan/configuration/global/GlobalAuthorizationConfiguration.java, core/src/main/java/org/infinispan/configuration/global/GlobalRoleConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/global/GlobalRolesConfigurationChildBuilder.java, core/src/main/java/org/infinispan/configuration/parsing/Attribute.java, core/src/main/java/org/infinispan/configuration/parsing/Parser.java, core/src/main/java/org/infinispan/security/Role.java, core/src/main/java/org/infinispan/security/impl/CacheRoleImpl.java, core/src/main/java/org/infinispan/util/logging/events/Messages.java, core/src/main/resources/schema/infinispan-config-15.0.xsd, core/src/test/java/org/infinispan/security/DynamicRBACRestartTest.java, core/src/test/java/org/infinispan/security/DynamicRBACTest.java, core/src/test/resources/configs/security-role-mapper-rewriter.xml, documentation/src/main/asciidoc/topics/xml/authorization_roles_custom.xml, server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java, server/tests/src/test/java/org/infinispan/server/security/authorization/RESTAuthorizationTest.java, server/tests/src/test/resources/configuration/cache-container/clustered-authz-common-name.xml
https://issues.redhat.com/browse/ISPN-14706
=> ISPN-14706 Roles annotations

core/src/main/java/org/infinispan/factories/EmptyConstructorFactory.java, core/src/main/java/org/infinispan/xsite/events/NoOpXSiteEventsManager.java
https://issues.redhat.com/browse/ISPN-15226
=> ISPN-15226 Create XSiteEventsManagerImpl for clustered environments

core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java
https://issues.redhat.com/browse/ISPN-15214
=> [14.x] ISPN-15214 Do not instantiate TriangleOrderManager if not required.

core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java
https://issues.redhat.com/browse/ISPN-15238
=> ISPN-15238 Backup write operations should ignore previous value

core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java
https://issues.redhat.com/browse/ISPN-15232
I was unable to create a reproducer as it has to have a specific order of index updates I was not able to reproduce. I can try later maybe to get a reproducer for this explicitly at a later point if time is willing.
=> ISPN-15232 Index may receive NegativeArraySizeException

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/pom.xml, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIRE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/RENAME.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/RENAMENX.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TTL.java, server/resp/src/main/java/org/infinispan/server/resp/filter/EventListenerKeysFilter.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
RENAME RENAMENX commands
https://issues.redhat.com/browse/ISPN-15200
~TODO: missing tests on different data types~ added, comment below
=> ISPN-15200 RENAME RENAMENX 

server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TOUCH.java
https://issues.redhat.com/browse/ISPN-15212
=> ISPN-15212 TOUCH with CompletionStages.performSequentially

client/rest-client/src/main/java/org/infinispan/client/rest/RestSecurityClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestSecurityClientOkHttp.java, core/src/main/java/org/infinispan/configuration/global/GlobalRoleConfigurationBuilder.java, core/src/main/java/org/infinispan/security/impl/CacheRoleImpl.java, core/src/test/java/org/infinispan/security/DynamicRBACTest.java, documentation/src/main/asciidoc/topics/json/rest_security_roles_detailed.json, documentation/src/main/asciidoc/topics/json/rest_security_roles_permissions.json, documentation/src/main/asciidoc/topics/ref_rest_server_security.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_detailed.adoc, server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java, server/rest/src/test/java/org/infinispan/rest/assertion/ResponseAssertion.java, server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java, server/rest/src/test/java/org/infinispan/rest/resources/AccessManagementResourceTest.java, server/tests/src/test/java/org/infinispan/server/security/authorization/RESTAuthorizationTest.java
https://issues.redhat.com/browse/ISPN-14924
=> ISPN-14924 Retrieve roles and permissions

build/checkstyle/src/main/resources/checkstyle-junit5.xml, server/tests/pom.xml, server/tests/src/test/java/org/infinispan/server/functional/JCacheOperations.java, server/tests/src/test/java/org/infinispan/server/functional/memcached/MemcachedOperations.java, server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestMetricsOperations.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationCertIT.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationKerberosIT.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationLDAPIT.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationPropertiesIT.java, spring/spring-boot-3/remote/pom.xml
https://issues.redhat.com/browse/ISPN-15230
=> [14.0.x] ISPN-15230 Server tests unable to run due to use of JUnit 4 imports

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TIME.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
Resp TIME command
https://issues.redhat.com/browse/ISPN-15251
=> ISPN-15351 Resp TIME command

documentation/src/main/asciidoc/topics/proc_making_caches_available.adoc, documentation/src/main/asciidoc/topics/proc_query_getting_statistics.adoc, documentation/src/main/asciidoc/topics/proc_setting_up_target_clusters.adoc, documentation/src/main/asciidoc/topics/proc_synchronizing_data_target_clusters.adoc, documentation/src/main/asciidoc/topics/ref_rest_caches_query.adoc, documentation/src/main/asciidoc/topics/upgrading.adoc
Docs fixes based on customer/user feedback
=> fixing rest path in the docs

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedSetCache.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SISMEMBER.java, server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
fixes https://issues.redhat.com/browse/ISPN-15252
=> ISPN-15252 SISMEMBER resp command

core/src/test/java/org/infinispan/stats/SingleStatsTest.java
https://issues.redhat.com/browse/ISPN-15260
=> [14.0] ISPN-15260 SingleStatsTest failure

core/src/test/java/org/infinispan/stats/SingleStatsTest.java
https://issues.redhat.com/browse/ISPN-15260
=> ISPN-15260 SingleStatsTest failure

build/configuration/pom.xml, core/src/test/java/org/infinispan/remoting/jgroups/ChannelLookupTest.java
https://issues.redhat.com/browse/ISPN-14849
=> [14.0] ISPN-14849 ChannelLookupTest is failing

core/src/test/java/org/infinispan/container/versioning/WriteSkewConsistencyTest.java
https://issues.redhat.com/browse/ISPN-15270
=> ISPN-15270 WriteSkewConsistencyTest random failures

core/src/test/java/org/infinispan/jmx/XSiteMBeanTest.java
https://issues.redhat.com/browse/ISPN-15273
=> ISPN-15273 XSiteMBeanTest fails randomly

core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-15262
=> ISPN-15262 IndexedTests can fail on clear due to blocking call

commons/all/src/main/java/org/infinispan/commons/internal/CommonsBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-15275
=> ISPN-15275 StampedLock#unlockRead blockhound exception

core/src/main/java/org/infinispan/stats/Stats.java, core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java, core/src/main/java/org/infinispan/stats/impl/StatsImpl.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
https://issues.redhat.com/browse/ISPN-15255
=> ISPN-15255 Use clustered stats component

multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapListCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ListBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/function/list/OfferFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapListCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/internal/PUSH.java
PUSH must generate only one event even in variadic mode.
https://issues.redhat.com/browse/ISPN-15281
=> ISPN-15281 PUSH must generate one event

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15093
=> ISPN-15093 Elytron 2.2.2.Final

multimap/src/main/java/org/infinispan/multimap/impl/function/list/OfferFunction.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
fixes https://issues.redhat.com/browse/ISPN-15288
=> ISPN-15288 LPUSH creates with wrong order

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15293
=> ISPN-15293 Upgrade JGroups to 5.3.0.Final

cli/src/main/java/org/infinispan/cli/Context.java, cli/src/main/java/org/infinispan/cli/commands/Connect.java, cli/src/main/java/org/infinispan/cli/connection/ConnectionFactory.java, cli/src/main/java/org/infinispan/cli/connection/Connector.java, cli/src/main/java/org/infinispan/cli/connection/rest/RestConnector.java, cli/src/main/java/org/infinispan/cli/impl/ContextImpl.java, cli/src/main/resources/help/connect.adoc, cli/src/test/java/org/infinispan/cli/connection/rest/RestConnectorTest.java, client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationBuilder.java, client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationProperties.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestClientOkHttp.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/RestTestClientDriver.java, server/tests/src/test/java/org/infinispan/server/cli/CliIT.java, server/tests/src/test/java/org/infinispan/server/security/AuthenticationMultiEndpointIT.java, server/tests/src/test/resources/configuration/AuthorizationImplicitTest.xml, server/tests/src/test/resources/configuration/endpoints/alternate-hotrod.xml
https://issues.redhat.com/browse/ISPN-14877
Replaces https://github.com/infinispan/infinispan/pull/10950
=> ISPN-14877 Added possibility to configure REST client using properties

client/rest-client/src/main/java/org/infinispan/client/rest/RestSecurityClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestSecurityClientOkHttp.java, core/src/main/java/org/infinispan/security/MutablePrincipalRoleMapper.java, core/src/main/java/org/infinispan/security/mappers/ClusterRoleMapper.java, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_detailed.adoc, server/core/src/main/java/org/infinispan/server/core/ServerManagement.java, server/core/src/test/java/org/infinispan/server/core/DummyServerManagement.java, server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java, server/runtime/src/main/java/org/infinispan/server/Server.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationPropertiesIT.java, server/tests/src/test/java/org/infinispan/server/security/authorization/RESTAuthorizationTest.java
https://issues.redhat.com/browse/ISPN-14925
=> ISPN-14925 Principals by role

build/configuration/pom.xml, pom.xml, server/runtime/pom.xml
https://issues.redhat.com/browse/ISPN-15093
=> [14.0] ISPN-15093 Elytron 2.2.2.Final

query/src/main/java/org/infinispan/query/internal/QueryBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-15298
=> ISPN-15298 Add block hound exception for index submitToQueue

.github/workflows/pull_request.yml, .github/workflows/release.yml, build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15296
=> Quarkus 3.5.0

build/configuration/pom.xml, pom.xml, server/runtime/pom.xml
https://issues.redhat.com/browse/ISPN-15093
=> ISPN-15093 Fix Jakarta JSON dependency as required by Elytron 2.x

cli/src/main/java/org/infinispan/cli/Context.java, cli/src/main/java/org/infinispan/cli/commands/Connect.java, cli/src/main/java/org/infinispan/cli/connection/ConnectionFactory.java, cli/src/main/java/org/infinispan/cli/connection/Connector.java, cli/src/main/java/org/infinispan/cli/connection/rest/RestConnector.java, cli/src/main/java/org/infinispan/cli/impl/ContextImpl.java, cli/src/main/resources/help/connect.adoc, cli/src/test/java/org/infinispan/cli/connection/rest/RestConnectorTest.java, client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationBuilder.java, client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationProperties.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestClientOkHttp.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/RestTestClientDriver.java, server/tests/src/test/java/org/infinispan/server/cli/CliIT.java, server/tests/src/test/java/org/infinispan/server/security/AuthenticationMultiEndpointIT.java, server/tests/src/test/resources/configuration/AuthorizationImplicitTest.xml, server/tests/src/test/resources/configuration/endpoints/alternate-hotrod.xml
https://issues.redhat.com/browse/ISPN-14877
Replaces https://github.com/infinispan/infinispan/pull/11457
=> [14.0] ISPN-14877 Added possibility to configure REST client using properties

cli/src/main/java/org/infinispan/cli/commands/rest/Roles.java, cli/src/main/resources/help/user.adoc, client/rest-client/src/main/java/org/infinispan/client/rest/RestSecurityClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestSecurityClientOkHttp.java, documentation/src/main/asciidoc/topics/ref_rest_server_security.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_security_roles_update.adoc, server/rest/src/main/java/org/infinispan/rest/logging/Log.java, server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java, server/rest/src/test/java/org/infinispan/rest/resources/AccessManagementResourceTest.java
https://issues.redhat.com/browse/ISPN-15269
=> ISPN-15269 Create or Update a role

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/evolution/IndexSchemaNoDowntimeUpgradeTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/aggregation/RemoteQueryAggregationCountTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/maxresult/RemoteDefaultMaxResultTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/maxresult/RemoteHitCountAccuracyTest.java, object-filter/src/main/antlr3/org/infinispan/objectfilter/impl/ql/parse/QueryRenderer.g, object-filter/src/main/java/org/infinispan/objectfilter/impl/ql/QueryRendererDelegate.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/BooleShannonExpansion.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/IndexedFieldProvider.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/AggregationPropertyPath.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/CacheValueAggregationPropertyPath.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/QueryRendererDelegateImpl.java, object-filter/src/test/java/org/infinispan/objectfilter/impl/syntax/BooleShannonExpansionTest.java, query/src/main/java/org/infinispan/query/clustered/AggregationDistributedIterator.java, query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java, query/src/main/java/org/infinispan/query/clustered/commandworkers/CQCreateEagerQuery.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelper.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/InfinispanAggregation.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryAnalyzer.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryBuilder.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryMaker.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryParsingResult.java, query/src/main/java/org/infinispan/query/impl/IndexedQueryImpl.java, query/src/test/java/org/infinispan/query/aggregation/QueryAggregationBroadcastTest.java, query/src/test/java/org/infinispan/query/aggregation/QueryAggregationCountTest.java, query/src/test/java/org/infinispan/query/model/Sale.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadata.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadata.java, remote-query/remote-query-server/src/test/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadataTest.java
https://issues.redhat.com/browse/ISPN-15254
Based on #11410 that should merged first.
=> ISPN-15254 Support count(*) other than count(someField) on aggregation queries

persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java, persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreConfigUriTest.java, persistence/remote/src/test/resources/remote-cl-uri-config-2.xml
https://issues.redhat.com/browse/ISPN-15292
https://issues.redhat.com/browse/ISPN-15294
=> [14.0.x] Remote store uri fixes

core/src/main/java/org/infinispan/commands/write/PutMapCommand.java, core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java, core/src/test/java/org/infinispan/statetransfer/PutAllDuringJoinTest.java
https://issues.redhat.com/browse/ISPN-15299
=> ISPN-15299 PutAll during rebalance can get a ClassCastException

server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java, server/tests/src/test/resources/configuration/Footprint.xml
https://issues.redhat.com/browse/ISPN-15225
=> ISPN-15225 Server Footprint

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/aggregation/RemoteQueryAggregationCountTest.java
https://issues.redhat.com/browse/ISPN-13986
Fix a test for it on 14 branch only
=> [14.0] ISPN-13986 Fix test to search on remote query

build/configuration/pom.xml, commons/all/src/main/java/org/infinispan/commons/logging/Log.java, documentation/src/main/asciidoc/topics/proc_configuring_tracing.adoc, documentation/src/main/asciidoc/topics/properties/tracing.properties, pom.xml, server/core/pom.xml, server/core/src/main/java/org/infinispan/server/core/telemetry/TelemetryServiceFactory.java, server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java
https://issues.redhat.com/browse/ISPN-15286
=> ISPN-15286 Upgrade OpenTelemetry to 1.31 and remove okhttp in favour or the JDK lib

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15306
=> ISPN-15306 Quarkus 3.5.1

server/tests/src/test/java/org/infinispan/server/functional/ClusteredIT.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java, server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java, server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestMetricsOperations.java
* Reduced the number of containers in XSiteIT suite
* Removed RestMetricsResource from ClusteredIT suite
https://issues.redhat.com/browse/ISPN-15307
=> ISPN-15307 Reduce the number of servers in cross-site IT tests

build/configuration/pom.xml, object-filter/pom.xml
https://issues.redhat.com/browse/ISPN-15310
=> ISPN-15310 Fix object-filter shaded dependencies

documentation/src/main/asciidoc/topics/ref_rest_caches.adoc, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-15313
=> ISPN-15313 Fix bug in caches by role REST API

server/core/src/main/java/org/infinispan/server/core/transport/NettyTransport.java
https://issues.redhat.com/browse/ISPN-15072
=> ISPN-15072 Exclude global connections from Micrometer

server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java, server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java, server/resp/src/main/java/org/infinispan/server/resp/commands/pubsub/SUBSCRIBE.java, server/resp/src/main/java/org/infinispan/server/resp/filter/EventListenerConverter.java, server/resp/src/test/java/org/infinispan/server/resp/RespTwoNodeTest.java
https://issues.redhat.com/browse/ISPN-15311
=> ISPN-15311 Listener converter in SUBSCRIBE must be externalizable

pom.xml
https://issues.redhat.com/browse/ISPN-15323
=> [14.0.x] ISPN-15323 Upgrade os-maven-plugin to 1.7.1.Final

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/telemetry/impl/TelemetryService.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/telemetry/impl/TelemetryServiceFactory.java
https://issues.redhat.com/browse/ISPN-15156
Backport of #11463
=> [14.0.x] ISPN-15156 Fix logging of tracing enabled

build/configuration/pom.xml, core/src/main/java/org/infinispan/metrics/impl/BaseOperatingSystemAdditionalMetrics.java
https://issues.redhat.com/browse/ISPN-15326
=> Quarkus 3.5.2

build/configuration/pom.xml, cli/pom.xml, cli/src/main/java/org/infinispan/cli/commands/CLI.java, cli/src/main/java/org/infinispan/cli/util/aesh/graal/NativeMetadataProvider.java, commons/all/pom.xml, commons/all/src/main/java/org/infinispan/commons/logging/log4j/XmlConfiguration.java, commons/all/src/main/java/org/infinispan/commons/logging/log4j/XmlConfigurationFactory.java, commons/all/src/test/java/org/infinispan/commons/logging/log4j/XmlConfigurationTest.java, commons/all/src/test/resources/log4j2-test.xml, quarkus/cli/pom.xml, quarkus/pom.xml, server/runtime/src/main/java/org/infinispan/server/BootstrapLogging.java, server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
https://issues.redhat.com/browse/ISPN-15325
=> ISPN-15325 Log4j 2.22.0

server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/BLPOP.java, server/resp/src/test/java/org/infinispan/server/resp/RespBlockingCommandsTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespBlockingMediaTypesTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespTwoNodeTest.java
https://issues.redhat.com/browse/ISPN-15148
this is the first implementation of a blocking command.
Is still a WIP.
DONE:
- listener registration
- event loop
- listener de-registration 
- timeout management
MISSING:
~~- timeout management~~
TO BE VERIFIED:
- marshalling of event data
TEST:
- tests for sync connection ~~(usually they pass)~~
- tests for async ~~(lpush fails for wrong password ???)~~
- tests for cleanup and exception handling
=> BLPOP Resp command

server/resp/pom.xml
removed unneeded lifecycle metadata from pom
https://issues.redhat.com/browse/ISPN-15327
=> ISPN-15327 Cleanup server/resp/pom.xml from metadata

commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java, commons/all/src/main/java/org/infinispan/commons/CrossSiteIllegalLifecycleStateException.java, core/src/main/java/org/infinispan/commands/irac/IracCleanupKeysCommand.java, core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java, core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java, core/src/main/java/org/infinispan/remoting/transport/ResponseCollectors.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/main/java/org/infinispan/xsite/commands/remote/XSiteCacheRequest.java, core/src/main/java/org/infinispan/xsite/events/XSiteEventSender.java, core/src/main/java/org/infinispan/xsite/events/XSiteEventsManagerImpl.java, core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java, core/src/test/java/org/infinispan/util/ControlledRpcManager.java, core/src/test/java/org/infinispan/xsite/offline/InvalidConfigurationOfflineTest.java, core/src/test/java/org/infinispan/xsite/statetransfer/XSiteAutoStateTransferTest.java
https://issues.redhat.com/browse/ISPN-15240
=> ISPN-15240 Improve cross-site message handling

build/configuration/pom.xml, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/evolution/IndexSchemaNoDowntimeUpgradeTest.java, query/src/main/java/org/infinispan/query/clustered/DistributedIterator.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryMaker.java, query/src/main/java/org/infinispan/query/impl/externalizers/LuceneSortExternalizer.java, query/src/main/java/org/infinispan/search/mapper/mapping/impl/DefaultAnalysisConfigurer.java, query/src/main/java/org/infinispan/search/mapper/model/impl/InfinispanBootstrapIntrospector.java, server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheQueries.java
https://issues.redhat.com/browse/ISPN-15331
=> ISPN-15331 Upgrade Hibernate Search to 7.0.0.CR1

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/telemetry/impl/TelemetryService.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/telemetry/impl/TelemetryServiceFactory.java
https://issues.redhat.com/browse/ISPN-15156
=> ISPN-15156 Fix logging of tracing enabled

documentation/src/main/asciidoc/topics/upgrading.adoc
Documentation review of Upgrading content
https://issues.redhat.com/browse/ISPN-15315
=> ISPN-15315 docs refinement to upgraidng guide, HR property defaults

build/configuration/pom.xml, server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java, server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/AUTH.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/CLIENT.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/HELLO.java, server/resp/src/test/java/org/infinispan/server/resp/RespAuthSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespDecoderTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/SingleNodeRespBaseTest.java, server/resp/src/test/java/org/infinispan/server/resp/logging/RespAccessLoggingTest.java, server/resp/src/test/java/org/infinispan/server/resp/test/RespTestingUtil.java, server/tests/src/test/java/org/infinispan/server/security/authentication/RespAuthentication.java
https://issues.redhat.com/browse/ISPN-15332
* Updates `HELLO` to require authentication parameters if needed;
* Updates `HELLO` version returned;
* Updates `CLIENT` to return for `SETINFO` sub-command;
* Update the tests to pass when updating to Lettuce 6.3.0.
I ran everything with 6.3.0 to assert it would work after the update in #11491.
=> ISPN-15332 Require AUTH during HELLO if authentication is enabled

core/src/main/java/org/infinispan/security/MutablePrincipalRoleMapper.java, core/src/main/java/org/infinispan/security/mappers/ClusterRoleMapper.java, server/rest/src/main/java/org/infinispan/rest/resources/SecurityResource.java
https://issues.redhat.com/browse/ISPN-15316
=> ISPN-15316 Security issue overriding existing users names with mappers and other roles

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15338
=> ISPN-15338 Updates to console 15.0.0.Dev04

quarkus/server-runner/src/main/docker/Dockerfile.native, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/testdriver/core/src/main/resources/testcontainers.properties
https://issues.redhat.com/browse/ISPN-15337
=> ISPN-15337 Upgrade testsuite base images to use ubi9

pom.xml
https://issues.redhat.com/browse/ISPN-15328
=> ISPN-15328 Use -XX:EnableDynamicAgentLoading on JDK 21 for ByteBuddy

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/core/src/main/java/org/infinispan/server/iteration/DefaultIterationManager.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/KEYS.java, server/resp/src/main/java/org/infinispan/server/resp/commands/iteration/BaseIterationCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/iteration/IterationArguments.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-15160
=> ISPN-15160 KEYS command

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, core/src/main/java/org/infinispan/manager/CacheManagerInfo.java, core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/test/java/org/infinispan/jmx/HealthJmxTest.java, server/tests/src/test/java/org/infinispan/server/functional/BackupManagerIT.java
https://issues.redhat.com/browse/ISPN-15343
https://issues.redhat.com/browse/ISPN-15344
=> ISPN-15344 Return Cache names in alphabetical order

documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/ISPN-15315 
fix property names for sni_host_name and connect_timeout
=> ISPN-15315 fix property names in upgrading doc

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/test/java/org/infinispan/test/transport/DelayedViewJGroupsTransport.java
https://issues.redhat.com/browse/ISPN-15117
=> ISPN-15117 Cache local address after connect

documentation/src/main/asciidoc/stories/assembly_embedding.adoc
remove reference to content that was removed
@tristantarrant necessary to fix the downstream build
=> [12.1.x]fix documentation build for Embedded guide

server/resp/src/main/java/org/infinispan/server/resp/commands/string/DEL.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
fixes https://issues.redhat.com/browse/ISPN-15347
=> ISPN-15347 DEL must work on all types

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/multimap/RemoteMultimapStateTransferTest.java, core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java
https://issues.redhat.com/browse/ISPN-15349
=> ISPN-15349 NPE from stats with multimap in server mode

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZMPOP.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZRANDMEMBER.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-15016
=> ISPN-15016 ZMPOP

.github/workflows/pull_request.yml, .github/workflows/release.yml, build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15353
https://issues.redhat.com/browse/ISPN-15354
=> ISPN-15353 Quarkus 3.6.0

persistence/jdbc-common/pom.xml, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/AbstractJdbcStoreConfigurationBuilder.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/AbstractJdbcStoreConfigurationChildBuilder.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/AbstractJdbcStoreConfigurationParser.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/AbstractJdbcStoreConfigurationSerializer.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/AbstractUnmanagedConnectionFactoryConfiguration.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/Attribute.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/CDIConnectionFactoryConfiguration.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/CDIConnectionFactoryConfigurationBuilder.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/Element.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/JdbcStoreConfigurationChildBuilder.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/ManagedConnectionFactoryConfiguration.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/impl/connectionfactory/CDIConnectionFactory.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/impl/connectionfactory/ManagedConnectionFactory.java, persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/logging/Log.java, persistence/jdbc-common/src/main/resources/schema/infinispan-cachestore-jdbc-common-config-15.0.xsd, persistence/jdbc/src/test/resources/configs/all/string-based-cdi.xml, quarkus/embedded/deployment/src/main/java/org/infinispan/quarkus/embedded/deployment/InfinispanEmbeddedProcessor.java, quarkus/embedded/runtime/pom.xml, quarkus/integration-tests/embedded/pom.xml, quarkus/integration-tests/embedded/src/main/java/org/infinispan/quarkus/embedded/TestServlet.java, quarkus/integration-tests/embedded/src/main/resources/application.properties, quarkus/integration-tests/embedded/src/main/resources/dist.xml, quarkus/integration-tests/embedded/src/main/resources/embedded.xml, quarkus/integration-tests/embedded/src/main/resources/import.sql, quarkus/integration-tests/embedded/src/test/java/org/infinispan/quarkus/embedded/InfinispanEmbeddedFunctionalityTest.java, quarkus/integration-tests/embedded/src/test/java/org/infinispan/quarkus/embedded/InfinispanEmbeddedTestResource.java
https://issues.redhat.com/browse/ISPN-15320
=> ISPN-15320 JDBC datasource lookup via CDI

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15364
=> ISPN-15364 Updates console to 15.0.0.Dev05

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15364
=> [14.0.x] ISPN-15364 Updates console to 14.0.14.Final

build/configuration/pom.xml, cli/pom.xml, cli/src/main/java/org/infinispan/cli/commands/CLI.java, commons/all/pom.xml, commons/all/src/main/java/org/infinispan/commons/logging/log4j/XmlConfiguration.java, commons/all/src/main/java/org/infinispan/commons/logging/log4j/XmlConfigurationFactory.java, commons/all/src/test/java/org/infinispan/commons/logging/log4j/XmlConfigurationTest.java, commons/all/src/test/resources/log4j2-test.xml, server/core/src/main/java/org/infinispan/server/core/dataconversion/XMLTranscoder.java, server/runtime/src/main/java/org/infinispan/server/BootstrapLogging.java
https://issues.redhat.com/browse/ISPN-15325
=> [14.0] ISPN-15325 Log4j 2.22.0

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/async/DefaultAsyncExecutorFactory.java, commons/all/src/main/java/org/infinispan/commons/ThreadGroups.java, core/src/main/java/org/infinispan/executors/DefaultExecutorFactory.java, core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java, core/src/main/java/org/infinispan/factories/threads/BlockingThreadFactory.java, core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadFactory.java, core/src/test/java/org/infinispan/stress/AsyncStoreStressTest.java, persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/MigrationTask.java, server/core/src/main/java/org/infinispan/server/core/factories/NettyEventLoopFactory.java
https://issues.redhat.com/browse/ISPN-15368
This is a follow-up PR to https://github.com/infinispan/infinispan/pull/11262 handling couple more places where ThreadGroups leak.
=> ISPN-15368 Prevent repetitive ThreadGroup creation
