- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
- commons/all/src/main/java/org/infinispan/commons/CrossSiteIllegalLifecycleStateException.java
- core/src/main/java/org/infinispan/commands/irac/IracCleanupKeysCommand.java
- core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/transport/ResponseCollectors.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/java/org/infinispan/xsite/commands/remote/XSiteCacheRequest.java
- core/src/main/java/org/infinispan/xsite/events/XSiteEventSender.java
- core/src/main/java/org/infinispan/xsite/events/XSiteEventsManagerImpl.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
- core/src/test/java/org/infinispan/util/ControlledRpcManager.java
- core/src/test/java/org/infinispan/xsite/offline/InvalidConfigurationOfflineTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/XSiteAutoStateTransferTest.java
https://issues.redhat.com/browse/ISPN-15240
> [14.0.x] ISPN-15240 Improve cross-site message handling

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15364
> [14.0.x] ISPN-15364 update to console 14.0.15.Final

- pom.xml
https://issues.redhat.com/browse/ISPN-14974
This should fix the CI. I hope so
> ISPN-14974 Fix opentelemetry-sdk-common dep version

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15374
> ISPN-15374 Update console to 15.0.0.Final

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/async/DefaultAsyncExecutorFactory.java
- commons/all/src/main/java/org/infinispan/commons/ThreadGroups.java
- core/src/main/java/org/infinispan/executors/DefaultExecutorFactory.java
- core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java
- core/src/main/java/org/infinispan/factories/threads/BlockingThreadFactory.java
- core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadFactory.java
- core/src/test/java/org/infinispan/stress/AsyncStoreStressTest.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/MigrationTask.java
- server/core/src/main/java/org/infinispan/server/core/factories/NettyEventLoopFactory.java
https://issues.redhat.com/browse/ISPN-15368
Upstream PR: https://github.com/infinispan/infinispan/pull/11553
This is a follow-up PR to https://github.com/infinispan/infinispan/pull/11277 handling couple more places where ThreadGroups leak.
> [14.0] ISPN-15368 Prevent repetitive ThreadGroup creation

- quarkus/pom.xml
- quarkus/server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/DeleteOpenTelemetryUnused.java
https://issues.redhat.com/browse/ISPN-14974
> ISPN-14974 Try to remove AndroidFriendlyRandomHolder from native

- core/src/main/java/org/infinispan/reactive/RxJavaInterop.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/LocalClusterPublisherManagerImpl.java
- core/src/test/java/org/infinispan/stream/BaseStreamTest.java
- core/src/test/java/org/infinispan/stream/LocalTxStreamTest.java
https://issues.redhat.com/browse/ISPN-15076
> ISPN-15076 CacheStream NPE in a tx with entryReduction

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15382
> ISPN-15382 Quarkus 3.6.2

- server/resp/src/main/java/org/infinispan/server/resp/commands/string/GETRANGE.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/string/SETRANGE.java
- server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
https://issues.redhat.com/browse/ISPN-15387
> ISPN-15387 RESP GETRANGE command handle end > length correctly

- quarkus/pom.xml
https://issues.redhat.com/browse/ISPN-15391
> ISPN-15391 CI fails due to GraalVM OOM

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15397
> ISPN-15397 Jackson 2.16.0

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15399
> ISPN-15399 Spring Boot 3.2.0 and Spring Framework 6.1.2

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTopologyAwareAddress.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- server/runtime/src/main/server/server/conf/infinispan-xsite.xml
https://issues.redhat.com/browse/ISPN-15403
Off-topic change: I updated `infinispan-xsite.xml` to match the most recent version of `infnispan.xml` shipped with the server zip file. Also cleanup some warnings in `JGroupsTopologyAwareAddress`.
> ISPN-15403 JGroupsTransport: address generator impl misses method

- pom.xml
- server/testdriver/core/src/main/resources/testcontainers.properties
https://issues.redhat.com/browse/ISPN-15411
Supersedes https://github.com/infinispan/infinispan/pull/11607
> ISPN-15411 Bump testcontainers from 1.18.0 to 1.19.3

- server/insights/src/main/java/org/infinispan/server/insights/InsightsModule.java
- server/insights/src/test/java/org/infinispan/server/insights/BasicInsightsTest.java
- server/insights/src/test/java/org/infinispan/server/insights/InsightsActivationTest.java
https://issues.redhat.com/browse/ISPN-15356
And introduce env variable corresponding to infinispan.insights.activation
~~Draft => we still need to evaluate this change~~ we're ready to review and merge it
> ISPN-15356 Active report exporting by default

- Jenkinsfile
- Jenkinsfile-release
- build/configuration/pom.xml
- cli/pom.xml
- documentation/src/main/asciidoc/topics/contributing/basics.adoc
- graalvm/client-hotrod/pom.xml
- graalvm/core/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-15061
> ISPN-15061 JDK 17 Baseline

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/vector/VectorSearchRemoteTest.java
- core/src/main/java/org/infinispan/marshall/protostream/impl/SerializationContextRegistryImpl.java
- graalvm/client-hotrod/src/test/resources/resource-config.json
- query/src/test/java/org/infinispan/query/vector/VectorSearchBroadcastTest.java
- server/rest/src/test/java/org/infinispan/rest/search/RestVectorSearchTest.java
- server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheQueries.java
- test-support/proto-sample-domain-implementation/pom.xml
- test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/Image.java
- test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/marshallers/MarshallerRegistration.java
https://issues.redhat.com/browse/ISPN-15400
~~Draft => I want to test more!~~ done
> ISPN-15400 Support collection parameter serialization

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15396
> ISPN-15396 Netty 4.1.104.Final

- archetypes/custom-module/pom.xml
- archetypes/custom-module/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetypes/custom-module/src/main/resources/archetype-resources/pom.xml
- archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/Attribute.java
- archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/CustomModule.java
- archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/CustomModuleConfiguration.java
- archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/CustomModuleConfigurationBuilder.java
- archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/CustomModuleParser.java
- archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/CustomModuleSerializer.java
- archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/Element.java
- archetypes/custom-module/src/test/resources/projects/test/archetype.properties
- archetypes/custom-module/src/test/resources/projects/test/goal.txt
- archetypes/pom.xml
- documentation/src/main/asciidoc/topics/contributing/building.adoc
https://issues.redhat.com/browse/ISPN-15405
> ISPN-15405 Add archetype for custom Infinispan module

- pom.xml
https://issues.redhat.com/browse/ISPN-14786
> ISPN-14786 Clean up leftovers from the WF modules removal

- server/runtime/pom.xml
https://issues.redhat.com/browse/ISPN-15440
Necessary after #11648.
> ISPN-15440 Update runtime lifecycles

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15455
> ISPN-15455 Spring Session and Lettuce update

- pom.xml
https://issues.redhat.com/browse/ISPN-15459
> ISPN-15459 Memcached client 1.2.3

- core/src/main/resources/default-configs/default-jgroups-azure.xml
- core/src/main/resources/default-configs/default-jgroups-ec2.xml
- core/src/main/resources/default-configs/default-jgroups-google.xml
- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/main/resources/default-configs/default-jgroups-udp.xml
* Using tranfer-queue by default
* SO_LINGER is disabled by default
> ISPN-15501 Add options to configure JGroups bundler and TCP SO_LINGER

- core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
https://issues.redhat.com/browse/ISPN-15504
We mark the local cache information to identify it is waiting for the cluster to recover. We can then safely ignore the topology updates until the cache joins.
> ISPN-15504 Fix testFailedRestartWithExtraneousNode failures

- build/configuration/pom.xml
- quarkus/embedded/deployment/src/main/java/org/infinispan/quarkus/embedded/deployment/InfinispanEmbeddedProcessor.java
- quarkus/pom.xml
- quarkus/server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java
- server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
https://issues.redhat.com/browse/ISPN-15427
> ISPN-15427 Upgrade JGroups to 5.3.1.Final

- commons/all/src/main/java/org/infinispan/commons/logging/log4j/XmlConfiguration.java
https://issues.redhat.com/browse/ISPN-15507
> ISPN-15507 Make log4j xml parser more robust

- build/configuration/pom.xml
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/MultiTenancyTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/NoOpSessionFactoryImplementor.java
- hibernate/cache-v62/pom.xml
- hibernate/cache-v62/src/test/java/org/infinispan/test/hibernate/cache/v62/util/TestSessionAccessImpl.java
https://issues.redhat.com/browse/ISPN-15521
> Update Hibernate to version 6.4.2.Final

- core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java
https://issues.redhat.com/browse/ISPN-13969
> ISPN-13969 Fix SoftIndexFileStoreRestartTest#testStatsUponRestart test

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15570
> ISPN-15570 RocksDB 8.10.0

- build/configuration/pom.xml
- documentation/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-15565
https://issues.redhat.com/browse/ISPN-15583
https://issues.redhat.com/browse/ISPN-15581
https://issues.redhat.com/browse/ISPN-15580
https://issues.redhat.com/browse/ISPN-15577
https://issues.redhat.com/browse/ISPN-15576
https://issues.redhat.com/browse/ISPN-15574
https://issues.redhat.com/browse/ISPN-15561
> Dependabot batch

- build/configuration/pom.xml
- jcache/commons/src/test/java/org/infinispan/jcache/AbstractTwoCachesBasicOpsTest.java
- jcache/embedded/src/main/java/org/infinispan/jcache/embedded/JCacheListenerAdapter.java
https://issues.redhat.com/browse/ISPN-8652
https://issues.redhat.com/browse/ISPN-15563
> ISPN-8652 Embedded JCache listener does not correctly return the previous value

- server/hotrod/src/main/java/org/infinispan/server/hotrod/LifecycleCallbacks.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/PrepareCoordinator.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/BaseCompleteTransactionOperation.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/CommitTransactionOperation.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/RollbackTransactionOperation.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/TxState.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/ConditionalMarkAsRollbackFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/CreateStateFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/PreparingDecisionFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetCompletedTransactionFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetDecisionFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetPreparedFunction.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/ServerHotRodTestBlockHoundIntegration.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/tx/TopologyChangeFunctionalTest.java
https://issues.redhat.com/browse/ISPN-15425
> [14.0x] ISPN-15425 TopologyChangeFunctionalTest random failures

- build/configuration/pom.xml
- pom.xml
- server/insights/src/main/java/org/infinispan/server/insights/InsightsService.java
- server/insights/src/main/java/org/infinispan/server/insights/report/InfinispanSubReportSerializer.java
- server/insights/src/main/java/org/infinispan/server/insights/report/InfinispanSubreport.java
- server/insights/src/main/java/org/infinispan/server/insights/report/InfinispanTopReport.java
- server/insights/src/test/java/org/infinispan/server/insights/BasicInsightsTest.java
- server/insights/src/test/java/org/infinispan/server/insights/InsightsActivationTest.java
https://issues.redhat.com/browse/ISPN-15571
https://issues.redhat.com/browse/ISPN-15585
> ISPN-15571 Enable by default Insights profile

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15428
> [14.x] ISPN-15428 Upgrade JGroups to 5.2.21.Final

- core/src/main/java/org/infinispan/util/concurrent/DataOperationOrderer.java
- core/src/test/java/org/infinispan/stats/SingleStatsTest.java
- server/tests/src/test/java/org/infinispan/server/persistence/JdbcStringBasedCacheStorePassivation.java
https://issues.redhat.com/browse/ISPN-15555
> ISPN-15555 Update com.github.ben-manes.caffeine:caffeine to 3.1.8

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
https://issues.redhat.com/browse/ISPN-15606
> ISPN-15606 Prevent leaking MBean for the HotRodClient

- build/configuration/pom.xml
- core/src/main/java/org/infinispan/util/concurrent/DataOperationOrderer.java
- core/src/test/java/org/infinispan/stats/SingleStatsTest.java
- server/tests/src/test/java/org/infinispan/server/persistence/JdbcStringBasedCacheStorePassivation.java
https://issues.redhat.com/browse/ISPN-15555
> [14.0] ISPN-15555 Update com.github.ben-manes.caffeine:caffeine to 3.1.8

- server/resp/src/main/java/org/infinispan/server/resp/Util.java
https://issues.redhat.com/browse/ISPN-15636
> ISPN-15636 Fix RESP command case-insensitive handling

- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedServer.java
- server/resp/src/main/java/org/infinispan/server/resp/RespServer.java
https://issues.redhat.com/browse/ISPN-15622
> ISPN-15622 Enable stats in RESP and Memcached by default

- server/resp/src/main/java/org/infinispan/server/resp/RespServer.java
- server/resp/src/test/java/org/infinispan/server/resp/RespServerTest.java
https://issues.redhat.com/browse/ISPN-15637
> ISPN-15637 Make the respCache distributed by default

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15650
> ISPN-15650 Quarkus 3.7.1

- server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java
- server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java
- server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
- server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
- server/tests/src/test/java/org/infinispan/server/functional/resp/RespHashTest.java
- server/tests/src/test/java/org/infinispan/server/functional/resp/RespListTest.java
- server/tests/src/test/java/org/infinispan/server/functional/resp/RespSetTest.java
- server/tests/src/test/java/org/infinispan/server/functional/resp/RespSortedSetTest.java
https://issues.redhat.com/browse/ISPN-15638
> ISPN-15638 Handle ClassCastException when RESP commands mix types

- build/configuration/pom.xml
- graalvm/core/src/main/java/org/infinispan/graalvm/substitutions/graal/SubstituteJGroups.java
- quarkus/embedded/deployment/src/main/java/org/infinispan/quarkus/embedded/deployment/InfinispanEmbeddedProcessor.java
- quarkus/server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java
- server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
https://issues.redhat.com/browse/ISPN-15639
> ISPN-15639 Upgrade JGroups to 5.3.2.Final

- build/configuration/pom.xml
- cli/src/main/java/org/infinispan/cli/commands/kubernetes/Delete.java
- cli/src/main/java/org/infinispan/cli/commands/kubernetes/Get.java
- cli/src/main/java/org/infinispan/cli/commands/rest/RestCliCommand.java
- cli/src/main/java/org/infinispan/cli/impl/ContextAwareCommandInvocation.java
- cli/src/main/java/org/infinispan/cli/impl/StreamShell.java
- commons/all/src/main/java/org/infinispan/commons/util/ServiceFinder.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AeshTestShell.java
https://issues.redhat.com/browse/ISPN-15631
> [14.0] ISPN-15631 Aesh 2.7

- Jenkinsfile
https://issues.redhat.com/browse/ISPN-15658
> ISPN-15658 Do no fail build if snapshot deployment fails

- documentation/pom.xml
- documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_query.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_table.adoc
- documentation/src/main/asciidoc/topics/proc_server_configuring_datasources.adoc
https://issues.redhat.com/browse/ISPN-15478
> ISPN-15478 Data Grid Caches documentation refers to old Postgresql

- persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/SslConfiguration.java
https://issues.redhat.com/browse/ISPN-15665
> ISPN-15665 SSLContext ignored by RemoteStore

- cli/src/main/java/org/infinispan/cli/commands/Batch.java
- cli/src/main/java/org/infinispan/cli/commands/CLI.java
- cli/src/main/java/org/infinispan/cli/commands/rest/Topology.java
- client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
- core/src/main/java/org/infinispan/commands/topology/TopologyUpdateStableCommand.java
- core/src/main/java/org/infinispan/distribution/ch/ConsistentHash.java
- core/src/main/java/org/infinispan/distribution/ch/impl/AbstractConsistentHash.java
- core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHash.java
- core/src/main/java/org/infinispan/distribution/ch/impl/ScatteredConsistentHash.java
- core/src/main/java/org/infinispan/statetransfer/InboundTransferTask.java
- core/src/main/java/org/infinispan/topology/CacheTopology.java
- core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java
- core/src/main/java/org/infinispan/topology/ClusterTopologyManager.java
- core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
- core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
- core/src/test/java/org/infinispan/globalstate/AbstractGlobalStateRestartTest.java
- core/src/test/java/org/infinispan/globalstate/ThreeNodeTopologyReinstallTest.java
- documentation/src/main/asciidoc/stories/assembly_cli_cache_operations.adoc
- documentation/src/main/asciidoc/topics/con_restarting_clusters.adoc
- documentation/src/main/asciidoc/topics/proc_cli_set_topology_caches.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
A batch with fixes I failed to backport.
https://issues.redhat.com/browse/ISPN-14418 (#10733)
https://issues.redhat.com/browse/ISPN-15504 (#11739)
https://issues.redhat.com/browse/ISPN-15432 (#11672)
> [14.0.x] ISPN-14418 Stable topology recovery after shutdown backports

- commons/all/src/main/java/org/infinispan/commons/stat/TimerTracker.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheMgmtInterceptor.java
- core/src/main/java/org/infinispan/jmx/ResourceDMBean.java
- core/src/main/java/org/infinispan/metrics/impl/AbstractMetricsRegistration.java
- core/src/main/java/org/infinispan/metrics/impl/CustomMetricsSupplier.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
- core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
- core/src/main/java/org/infinispan/xsite/status/TakeOfflineManager.java
Includes a fix for ISPN-14330 (NullPointerException)
https://issues.redhat.com/browse/ISPN-14330
https://issues.redhat.com/browse/ISPN-15657
> ISPN-15657 NullPointerException in MBeans without getters

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15700
> ISPN-15700 Updates console to 15.0.1.Final

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/projection/RemoteProjectionTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/JsonQuerySerializer.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/EntityProjection.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/Hit.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/JsonProjection.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/JsonQueryResponse.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/ProjectedJsonResult.java
- server/rest/src/test/java/org/infinispan/rest/search/projection/RestProjectionTest.java
- server/rest/src/test/java/org/infinispan/rest/search/vector/RestVectorSearchTest.java
https://issues.redhat.com/browse/ISPN-15685
> ISPN-15685 Error using identity or vector projections on REST remote vector queries

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15673
> ISPN-15673 Quarkus 3.7.2

- core/src/main/java/org/infinispan/util/logging/Log.java
- documentation/src/main/asciidoc/topics/proc_using_jboss_marshaller.adoc
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/JbossMarshallingModule.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/AbstractJBossMarshaller.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/CheckedClassResolver.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/DefaultContextClassResolver.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/ExtendedRiverMarshaller.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/ExtendedRiverUnmarshaller.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/JBossExternalizerAdapter.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/JBossMarshallerFactory.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/RiverCloseListener.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/SerializeWithExtFactory.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/core/JBossMarshaller.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/core/JBossUserMarshaller.java
https://issues.redhat.com/browse/ISPN-15674
> ISPN-15674 Undeprecate JBoss Marshalling

- distribution/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-15702
> ISPN-15702 Remove jgroups-kubernetes dependency

- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIRE.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIREAT.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/PEXPIREAT.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
- server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
https://issues.redhat.com/browse/ISPN-15718
> ISPN-15718 EXPIREAT, PEXPIREAT

- core/src/main/java/org/infinispan/configuration/cache/TracingConfiguration.java
- core/src/test/java/org/infinispan/configuration/ConfigurationConversionTest.java
https://issues.redhat.com/browse/ISPN-15725
> ISPN-15725 TracingConfiguration categories always serialized

- query/src/main/java/org/infinispan/query/clustered/ClusteredQueryInvoker.java
- query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java
https://issues.redhat.com/browse/ISPN-15736
https://issues.redhat.com/browse/JDG-6871
> ISPN-15736 Log broadcast queries and loading

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/projection/RemoteProjectionTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/JsonQuerySerializer.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/EntityProjection.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/Hit.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/JsonProjection.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/JsonQueryResponse.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/ProjectedJsonResult.java
- server/rest/src/test/java/org/infinispan/rest/search/projection/RestProjectionTest.java
https://issues.redhat.com/browse/ISPN-15685
https://issues.redhat.com/browse/JDG-6720
Backport of https://github.com/infinispan/infinispan/pull/11973.
> [14.0] ISPN-15685 Fix projection names with Rest client

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- closed the table 
- fixed brandname attributes
- text formatting from bold to monospace
> fix ascii syntax to prevent renderring issues

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/transaction/lookup/GenericTransactionManagerLookup.java
- client/hotrod/src/main/java/org/infinispan/hotrod/transaction/lookup/GenericTransactionManagerLookup.java
- commons/all/src/main/java/org/infinispan/commons/logging/Log.java
- commons/all/src/main/java/org/infinispan/commons/tx/lookup/LookupNames.java
- core/src/main/java/org/infinispan/transaction/lookup/GenericTransactionManagerLookup.java
https://issues.redhat.com/browse/ISPN-15755
> ISPN-15755 Add WebSphere Liberty TransactionManager

- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- core/src/main/java/org/infinispan/metrics/impl/BaseOperatingSystemAdditionalMetrics.java
- server/core/src/main/java/org/infinispan/server/core/BaseServerManagement.java
- server/rest/src/test/java/org/infinispan/rest/resources/OverviewReportResourceTest.java
https://issues.redhat.com/browse/ISPN-15744
The new report looks like:
``` json
{
"version": "1.0.0",
"product-version": "15.0.0-SNAPSHOT",
"node-id": "53722a5e-705f-4240-a0d1-0e21764fb8ee",
"coordinator-id": "53722a5e-705f-4240-a0d1-0e21764fb8ee",
"cluster-size": 2,
"sites": 0,
"relay-node": false,
"cache-cardinalities": [
"K",
"K",
"K"
],
"cache-features": {
"no-features": 3
},
"cache-stores": [],
"proto-schemas": 0,
"used-encodings": [
"application/octet-stream",
"text/plain"
],
"clients": {
"Memcached": {
"protocol-versions": [
"MCTXT"
]
},
"SinglePort": {
"protocol-versions": [
"HOTROD/4.0"
]
}
},
"security": {
"security-realms": {
"default": {
"server-ssl": false,
"client-ssl": false
}
},
"tls-endpoints": []
}
}
```
> ISPN-15744 Remove metric data from the overview report

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsMetricsManagerImpl.java
- server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
https://issues.redhat.com/browse/ISPN-15769
> ISPN-15769 Response time between nodes is not correctly computed

- .github/workflows/supported_jdks.yaml
- build/bom/pom.xml
- build/component-processor/pom.xml
- build/component-processor/src/main/java/org/infinispan/component/processor/ComponentAnnotationProcessor.java
- build/component-processor/src/main/java/org/infinispan/component/processor/external/JGroupsComponentProcessor.java
- build/configuration/pom.xml
- build/logging-processor/pom.xml
- build/logging-processor/src/main/java/org/infinispan/logging/processor/InfinispanLoggingProcessor.java
- documentation/src/main/asciidoc/topics/dependencies_maven/protostream-processor.xml
- documentation/src/main/asciidoc/topics/proc_adding_protostream_processor.adoc
- hibernate/cache-commons/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-15757
This is required in order to compile with JDK 22
> ISPN-15757 explicit annotation processors

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15777
> ISPN-15777 Updates Console to 15.0.2.Final

- build/configuration/pom.xml
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/ProtoStreamMarshallerWithAnnotationsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/MultiServerStoreQueryTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryProtostreamAnnotationsDisableIndexingTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryWithProtostreamAnnotationsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/ReplicationIndexTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/KeywordEntity.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Reviewer.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Revision.java
- core/src/main/java/org/infinispan/marshall/persistence/impl/PersistenceContextInitializer.java
- core/src/test/java/org/infinispan/test/data/Sex.java
- persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java
- query/src/test/java/org/infinispan/query/test/Person.java
- remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/impl/ContinuousQueryResult.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/search5/Search5MetadataCreator.java
- server/rest/src/test/java/org/infinispan/rest/resources/ProtobufResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/search/entity/Gender.java
- server/runtime/src/main/java/org/infinispan/server/logging/events/ServerEventImpl.java
- spring/spring6/spring6-common/src/main/java/org/infinispan/spring/common/session/MapSessionProtoAdapter.java
- test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/Account.java
- test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/User.java
https://issues.redhat.com/browse/ISPN-15775
> ISPN-15775 Protostream 5.0.0.CR2

- server/insights/src/main/java/org/infinispan/server/insights/InfinispanInsightsConfiguration.java
- server/insights/src/main/java/org/infinispan/server/insights/InsightsService.java
- server/insights/src/main/java/org/infinispan/server/insights/logging/Log.java
- server/insights/src/test/java/org/infinispan/server/insights/InsightsActivationTest.java
https://issues.redhat.com/browse/ISPN-15772
> ISPN-15772 Allow report file writing on cert exception

- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/tests/src/test/java/org/infinispan/server/functional/overview/OverviewReportIT.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
- server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
https://issues.redhat.com/browse/ISPN-15823
https://issues.redhat.com/browse/ISPN-15824
> ISPN-15824 Collect tls endpoint from protocol servers

- Jenkinsfile
- bin/jira/add_comment.sh
- bin/jira/add_fix_version.sh
- bin/jira/add_pull_request.sh
- bin/jira/assign_issue.sh
- bin/jira/common.sh
- bin/jira/track_flaky_tests.sh
- bin/jira/transition.sh
- bin/jira/upsert.sh
https://issues.redhat.com/browse/ISPN-15735
> [14.0.x] ISPN-15735 Report flaky infinispan tests to Jira

- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/tests/src/test/java/org/infinispan/server/functional/overview/OverviewReportIT.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
- server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
https://issues.redhat.com/browse/JDG-6897
https://issues.redhat.com/browse/JDG-6898
Backport of https://github.com/infinispan/infinispan/pull/12089
> [14.0.x] ISPN-15824 Collect tls endpoing from protocol servers

- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfiguration.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
- server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
https://issues.redhat.com/browse/ISPN-15838
> ISPN-15838 Add realm to tls-endpoint for Insights

- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfiguration.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
- server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
https://issues.redhat.com/browse/ISPN-15838
> [14.0.x] ISPN-15838 Add realm to tls-endpoint for Insights

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCache.java
- multimap/src/main/java/org/infinispan/multimap/impl/HashMapBucket.java
- multimap/src/main/java/org/infinispan/multimap/impl/function/hmap/HashMapPutFunction.java
- multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCacheTest.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/PEXPIRE.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/RANDOMKEY.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HSETNX.java
- server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-15835
https://issues.redhat.com/browse/ISPN-15834
https://issues.redhat.com/browse/ISPN-15216
> ISPN-15835 Additional RESP data commands

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/TracingClusterTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/TracingXSiteTest.java
- core/src/main/java/org/infinispan/configuration/global/GlobalConfigurationBuilder.java
- core/src/main/java/org/infinispan/telemetry/SpanCategory.java
- core/src/test/java/org/infinispan/configuration/clone/GlobalTracingConfigCloneTest.java
- server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java
https://issues.redhat.com/browse/ISPN-15839
> ISPN-15839 Fix Tracing X-Site cache configuration

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15849
> ISPN-15489 ProtoStream 5.0.1.Final

- server/insights/src/main/java/org/infinispan/server/insights/InsightsModule.java
https://issues.redhat.com/browse/ISPN-15881
> ISPN-15881 Check null service at cache manager stopping

- server/insights/src/main/java/org/infinispan/server/insights/InsightsModule.java
https://issues.redhat.com/browse/ISPN-15881
Backport of https://github.com/infinispan/infinispan/pull/12156
> [14.0] ISPN-15881 Check null service at cache manager stopping

- core/src/main/java/org/infinispan/factories/EmptyConstructorFactory.java
- core/src/test/java/org/infinispan/manager/CacheDependencyTest.java
https://issues.redhat.com/browse/ISPN-15896
> ISPN-15896 Do not autostart authorization components when disabled

- query-core/src/main/java/org/infinispan/query/core/impl/QueryEngine.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java
https://issues.redhat.com/browse/ISPN-15898
> ISPN-15898 QueryEngine logs a DEBUG message for every query executed

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
[ISPN-15882](https://issues.redhat.com/browse/ISPN-15882)
> ISPN-15882 fixed command name in documentation for RESP endpoint

- core/src/main/java/org/infinispan/persistence/async/AsyncNonBlockingStore.java
- core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
- core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStoreConfiguration.java
- core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStoreConfigurationBuilder.java
- core/src/test/java/org/infinispan/persistence/support/AsyncStoreTest.java
https://issues.redhat.com/browse/ISPN-15860
> ISPN-15860 Exception with async store when not segmented

- Jenkinsfile
> Quiet jenkins warning plugin

- server/resp/src/main/java/org/infinispan/server/resp/Consumers.java
- server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java
- server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/BLMPOP.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/BLPOP.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/BRPOP.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/PopConfiguration.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/SingleBlockingPop.java
- server/resp/src/test/java/org/infinispan/server/resp/RespBxPOPTest.java
https://issues.redhat.com/browse/ISPN-15792
Adapted the existing blocking pop abstraction to pop a variable number of elements.
> ISPN-15792 BLMPOP

- core/src/main/resources/schema/infinispan-config-15.0.xsd
- tools/src/main/resources/xsd/xsdoc.xslt
https://issues.redhat.com/browse/ISPN-15915
> ISPN-15915 Fix configdocs

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/Search.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/event/impl/ContinuousQueryImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/DelegatingRemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/query/RemoteQueryFactory.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ContinuousQueryObjectStorageTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/RemoteContinuousQueryLeavingRemoteCacheManagerTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/RemoteContinuousQueryTest.java
- commons/all/src/main/java/org/infinispan/commons/api/BasicCache.java
- commons/all/src/main/java/org/infinispan/commons/api/query/ContinuousQuery.java
- commons/all/src/main/java/org/infinispan/commons/api/query/ContinuousQueryListener.java
- core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingCache.java
- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/main/java/org/infinispan/cache/impl/QueryProducer.java
- core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
- core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java
- core/src/test/java/org/infinispan/functional/decorators/FunctionalAdvancedCache.java
- core/src/test/java/org/infinispan/security/SecureCacheTestDriver.java
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
- query-core/src/main/java/org/infinispan/query/core/QueryProducerImpl.java
- query-core/src/main/java/org/infinispan/query/core/Search.java
- query-core/src/main/java/org/infinispan/query/core/impl/continuous/ContinuousQueryImpl.java
- query-dsl/src/main/java/org/infinispan/query/api/continuous/ContinuousQuery.java
- query-dsl/src/main/java/org/infinispan/query/api/continuous/ContinuousQueryListener.java
- query/src/main/java/org/infinispan/query/Search.java
- query/src/test/java/org/infinispan/query/continuous/AbstractCQMultipleCachesTest.java
- query/src/test/java/org/infinispan/query/continuous/ContinuousQueryProfilingTest.java
- query/src/test/java/org/infinispan/query/continuous/ContinuousQueryTest.java
- server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheContinuousQueries.java
https://issues.redhat.com/browse/ISPN-15880
> ISPN-15880 Make compatible Continuous Query with commons.Query

- pom.xml
https://issues.redhat.com/browse/ISPN-15539
For some reason, dependabot never opened this update to 14.0.x.
> [14.0.x] ISPN-15539 commons-io:commons-io 2.15.1

- documentation/src/main/asciidoc/topics/code_examples/RegisteringContinuousQuery.java
- documentation/src/main/asciidoc/topics/ref_query_ickle.adoc
[ISPN-15909](https://issues.redhat.com/browse/ISPN-15909)
> ISPN-15909 fix code example for create Query

- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/AggregationExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/AndExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/BetweenExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/ComparisonExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/ConstantBooleanExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/ConstantValueExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/FullTextBoostExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/FullTextOccurExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/FullTextRangeExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/FullTextRegexpExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/FullTextTermExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/IsNullExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/KnnPredicate.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/LikeExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/NotExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/OrExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/PropertyValueExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/SyntaxTreePrinter.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/ToQueryString.java
- query/src/test/java/org/infinispan/query/vector/VectorSearchBroadcastTest.java
https://issues.redhat.com/browse/ISPN-15925
https://issues.redhat.com/browse/ISPN-15932
> ISPN-15925 Serialize correctly knn single param array

- commons/all/src/main/java/org/infinispan/commons/stat/CounterTracker.java
- commons/all/src/main/java/org/infinispan/commons/stat/FunctionTimerMetricInfo.java
- commons/all/src/main/java/org/infinispan/commons/stat/TimerTracker.java
- core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
- core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheMgmtInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/TxInterceptor.java
- core/src/main/java/org/infinispan/metrics/impl/FunctionTimerTrackerImpl.java
- core/src/main/java/org/infinispan/metrics/impl/MetricUtils.java
- core/src/main/java/org/infinispan/metrics/impl/MetricsRegistryImpl.java
- core/src/main/java/org/infinispan/metrics/impl/TimerTrackerImpl.java
- core/src/main/java/org/infinispan/metrics/impl/helper/KeyMetrics.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsMetricsManagerImpl.java
- server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
* Add counters for single key operations by ownership
* Add transaction prepare/commit/rollback operation times
https://issues.redhat.com/browse/ISPN-15923
> ISPN-15923 More detailed metrics in CacheMgmtInterceptor

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/vector/VectorSearchRemoteTest.java
- documentation/src/main/asciidoc/topics/ref_query_vector_search.adoc
- object-filter/src/main/antlr3/org/infinispan/objectfilter/impl/ql/parse/IckleLexer.g
- object-filter/src/main/antlr3/org/infinispan/objectfilter/impl/ql/parse/IckleParser.g
- object-filter/src/main/antlr3/org/infinispan/objectfilter/impl/ql/parse/QueryRenderer.g
- object-filter/src/main/antlr3/org/infinispan/objectfilter/impl/ql/parse/QueryResolver.g
- object-filter/src/main/java/org/infinispan/objectfilter/impl/logging/Log.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/ql/QueryRendererDelegate.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/SyntaxTreePrinter.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/IckleParsingResult.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/QueryRendererDelegateImpl.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/VirtualExpressionBuilder.java
- object-filter/src/test/java/org/infinispan/objectfilter/impl/syntax/BooleShannonExpansionTest.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryMaker.java
- query/src/test/java/org/infinispan/query/vector/VectorSearchBroadcastTest.java
- query/src/test/java/org/infinispan/query/vector/VectorSearchWithPreFilteringTest.java
- server/rest/src/test/java/org/infinispan/rest/search/vector/RestVectorSearchTest.java
https://issues.redhat.com/browse/ISPN-15383
~~Based on top of https://github.com/infinispan/infinispan/pull/12211~~ done!
> ISPN-15383 Support vector search filtering elements

- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java
https://issues.redhat.com/browse/ISPN-15523
Some logs I've missed to revert.
> ISPN-15523 Revert excessive logging

- query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
- query/src/main/java/org/infinispan/query/backend/SegmentListener.java
- query/src/main/java/org/infinispan/query/logging/Log.java
- query/src/main/java/org/infinispan/search/mapper/mapping/SearchMapping.java
- query/src/main/java/org/infinispan/search/mapper/mapping/impl/InfinispanMapping.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java
- remote-query/remote-query-server/src/test/java/org/infinispan/query/remote/impl/indexing/NoSchemaTest.java
- server/rest/src/test/java/org/infinispan/rest/ServerRestTestBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-15940
> ISPN-15940 Avoid indexes creation on purge and stop/close

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15963
> ISPN-15963 Protostream 5.0.2.Final

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15962
> ISPN-15962 Quarkus 3.8.3

- remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/impl/Externalizers.java
https://issues.redhat.com/browse/ISPN-15964
Draft => I just removed the externalizer and see if CI passes
> ISPN-15964 Fix out-of-order query request serialization

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15976
> ISPN-15976 WildFly Elytron 2.4.0.Final

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ServerHintingTest.java
https://issues.redhat.com/browse/ISPN-15921
> ISPN-15921 Add Server Hinting unit test

- build/component-processor/src/main/java/org/infinispan/component/processor/ComponentAnnotationProcessor.java
https://issues.redhat.com/browse/ISPN-15977
> ISPN-15977 Record fails to compile on ComponentAnnotationProcessor

- tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingInterceptor.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingManagerImpl.java
https://issues.redhat.com/browse/ISPN-15981
> ISPN-15981 Wrap ScriptEngine init in blocking call

- core/src/main/java/org/infinispan/marshall/exts/ThrowableExternalizer.java
https://issues.redhat.com/browse/ISPN-15984
> ISPN-15984 OutdatedTopologyException is not properly marshalled

- remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/impl/Externalizers.java
- remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/impl/QueryRequest.java
https://issues.redhat.com/browse/ISPN-15964
Backport of https://github.com/infinispan/infinispan/pull/12267
> [14.0.x] ISPN-15964 Fix out-of-order query request serialization

- core/src/main/java/org/infinispan/util/concurrent/CompletionStages.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java
- server/core/src/test/java/org/infinispan/server/core/backup/BackupManagerImplTest.java
- server/tests/src/test/java/org/infinispan/server/functional/BackupManagerIT.java
- server/tests/src/test/java/org/infinispan/server/functional/LargeBackupManagerIT.java
https://issues.redhat.com/browse/ISPN-15523
Backport of #12093.
> [14.0.x] ISPN-15523 Restore procedure performance regression

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15998
> ISPN-15998 Quarkus 3.8.4

- commons/all/src/main/java/org/infinispan/commons/util/concurrent/CompletableFutures.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/manager/impl/AbstractClusterExecutor.java
- core/src/main/java/org/infinispan/manager/impl/AllClusterExecutor.java
- core/src/main/java/org/infinispan/manager/impl/ClusterExecutors.java
- core/src/main/java/org/infinispan/manager/impl/LocalClusterExecutor.java
- core/src/main/java/org/infinispan/manager/impl/ReplicableManagerFunctionCommand.java
- core/src/main/java/org/infinispan/manager/impl/SingleClusterExecutor.java
- server/runtime/src/main/java/org/infinispan/server/tasks/DistributedServerTaskRunner.java
- server/runtime/src/main/java/org/infinispan/server/tasks/LocalServerTaskRunner.java
- server/runtime/src/main/java/org/infinispan/server/tasks/ServerTaskEngine.java
- server/runtime/src/main/java/org/infinispan/server/tasks/ServerTaskRunner.java
- server/runtime/src/test/java/org/infinispan/server/task/ServerTaskEngineBlockingTest.java
https://issues.redhat.com/browse/ISPN-16002
I've split it into two commits. I am unsure about the cluster executor changes. It was supposed to be running on the blocking executor already.
> ISPN-16002 ServerTask and ClusterExecutor should run user code in the blocking thread pool

- build/configuration/pom.xml
- cli/pom.xml
- client/hotrod-client/pom.xml
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- client/hotrod/pom.xml
- commons/all/pom.xml
- commons/all/src/main/java/org/infinispan/commons/logging/Log.java
- commons/all/src/main/java/org/infinispan/commons/util/SslContextFactory.java
- documentation/src/main/asciidoc/topics/con_performance_security.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_server_fips.adoc
- documentation/src/main/asciidoc/topics/ref_performance_tuning.adoc
- documentation/src/main/asciidoc/topics/ref_rest_protocols.adoc
- documentation/src/main/asciidoc/topics/ref_server_ports_protocols.adoc
- etc/dependency-check-suppressions.xml
- javadoc/pom.xml
- pom.xml
- server/hotrod/pom.xml
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ServerHotRodBlockHoundIntegration.java
- server/rest/pom.xml
- server/router/pom.xml
- server/router/src/test/java/org/infinispan/server/router/integration/SinglePortTest.java
- server/runtime/pom.xml
- server/runtime/src/main/java/org/infinispan/server/configuration/security/SSLConfiguration.java
- server/runtime/src/main/resources/schema/infinispan-server-15.0.xsd
- server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
https://issues.redhat.com/browse/ISPN-16017
> ISPN-16017 Drop OpenSSL

- server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZADD.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
fixes https://issues.redhat.com/browse/ISPN-15994
> ISPN-15994 ZADD with lowercase options

- server/resp/src/main/java/org/infinispan/server/resp/commands/connection/PING.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
fixes https://issues.redhat.com/browse/ISPN-15983
ping command now sends the argument back
> ISPN-15983 fix PING command with args

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HSTRLEN.java
- server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
fixes https://issues.redhat.com/browse/ISPN-14673
HSTRLEN resp command implementation
> ISPN-14673 HSTRLEN RESP command

- server/tests/src/test/java/org/infinispan/server/functional/CloudEventsIntegrationIT.java
https://issues.redhat.com/browse/ISPN-16025
> [14.0.x] ISPN-16025 Disable CloudEventsIntegrationIT in 14.0.x branch

- server/resp/src/main/java/org/infinispan/server/resp/ByteBufferUtils.java
- server/resp/src/main/java/org/infinispan/server/resp/Consumers.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TYPE.java
Fixes https://issues.redhat.com/browse/ISPN-16005
TYPE command must return simple string not bulk
> ISPN-16005 fix TYPE command

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
https://issues.redhat.com/browse/ISPN-16034
> ISPN-16034 Cache REST release resource is blocking

- core/src/main/java/org/infinispan/security/audit/LoggingAuditLogger.java
https://issues.redhat.com/browse/ISPN-16050
> ISPN-16050 Tracing: NullPointerException checking for permission

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/TracingXSiteTest.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/telemetry/InfinispanTelemetry.java
- core/src/main/java/org/infinispan/telemetry/impl/DisabledInfinispanTelemetry.java
- server/core/src/main/java/org/infinispan/server/core/telemetry/OpenTelemetryService.java
https://issues.redhat.com/browse/ISPN-16049
> ISPN-16049 Tracing: add node name to the spans

- pom.xml
- server/rest/src/test/java/org/infinispan/rest/logging/RestAccessLoggingTest.java
https://issues.redhat.com/browse/ISPN-16047
> ISPN-16047 Check user agent with branding

- server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/resp/RespServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/security/ServerSecurityRealm.java
- server/runtime/src/main/resources/schema/infinispan-server-15.0.xsd
- server/runtime/src/main/server/README.adoc
- server/runtime/src/main/server/server/conf/infinispan-memcached.xml
- server/runtime/src/main/server/server/conf/infinispan-resp.xml
https://issues.redhat.com/browse/ISPN-16058
> ISPN-16058 Include simple redis-compatbile configuration

- server/runtime/src/main/java/org/infinispan/server/configuration/security/GroupsPropertiesConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/PropertiesRealmConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/UserPropertiesConfiguration.java
- server/runtime/src/main/resources/schema/infinispan-server-15.0.xsd
- server/runtime/src/main/server/server/conf/infinispan-dev-mode.xml
- server/runtime/src/main/server/server/conf/infinispan-local.xml
- server/runtime/src/main/server/server/conf/infinispan-xsite.xml
- server/runtime/src/main/server/server/conf/infinispan.xml
https://issues.redhat.com/browse/ISPN-16062
> ISPN-16062 Simplify default server configuration files

- server/runtime/src/main/server/server/conf/infinispan-memcached.xml
- server/runtime/src/main/server/server/conf/infinispan-resp.xml
https://issues.redhat.com/browse/ISPN-16062
@ryanemerson I wasn't fast enough in updating this PR to also fix the newly introduced -resp and -memcached configs
> ISPN-16062 Simplify default server configuration files (#2)

- core/src/main/java/org/infinispan/configuration/cache/MemoryConfiguration.java
- core/src/test/java/org/infinispan/configuration/cache/MemoryConfigurationTest.java
https://issues.redhat.com/browse/ISPN-16066
> ISPN-16066 Convert max-size to bytes before comparing

- graalvm/client-hotrod/pom.xml
- graalvm/commons/pom.xml
- graalvm/core/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-16079
> ISPN-16079 update maven coordinates for jandex

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/TracingSecurityTest.java
https://issues.redhat.com/browse/ISPN-16084
> ISPN-16084 Fix TracingSecurityTest flaky test

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16085
> ISPN-16085 Updates Console to 15.0.3.Final

- build/configuration/pom.xml
- commons/all/pom.xml
- core/pom.xml
- counter/pom.xml
- multimap/pom.xml
- persistence/rocksdb/pom.xml
- pom.xml
- query/pom.xml
- remote-query/remote-query-server/pom.xml
- server/core/pom.xml
- server/memcached/pom.xml
- server/resp/pom.xml
- server/rest/pom.xml
- server/runtime/pom.xml
- tasks/scripting/pom.xml
https://issues.redhat.com/browse/ISPN-16080
> ISPN-16080 Use ProtoStream's ProtoLock

- server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
https://issues.redhat.com/browse/ISPN-16085
> ISPN-16085 Adjust FootprintIT for smaller console size

- core/src/main/java/org/infinispan/Cache.java
https://issues.redhat.com/browse/ISPN-16099
> ISPN-16099 Align computeIfAbsent javadoc with Map#computeIfAbsent

- core/src/main/java/org/infinispan/globalstate/impl/ConfigCacheLock.java
- quarkus/server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java
- quarkus/server/runtime/pom.xml
- query/pom.xml
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- query/src/main/java/org/infinispan/query/impl/massindex/DistributedIndexerLock.java
- server/core/src/main/java/org/infinispan/server/core/backup/BackupManagerImpl.java
- server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
- server/tests/src/test/java/org/infinispan/server/resilience/GracefulShutdownRestartIT.java
- server/tests/src/test/resources/cli/qcache.xml
- server/tests/src/test/resources/configuration/ClusteredServerIspn13Test.xml
- server/tests/src/test/resources/configuration/cache-container/clustered-datasource.xml
- server/tests/src/test/resources/configuration/cache-container/clustered-ignore-unclean.xml
- server/tests/src/test/resources/configuration/cache-container/clustered-metric-names-as-tags.xml
- server/tests/src/test/resources/configuration/cache-container/clustered-tls.xml
- server/tests/src/test/resources/configuration/cache-container/clustered.xml
https://issues.redhat.com/browse/ISPN-16070
https://issues.redhat.com/browse/ISPN-16071
https://issues.redhat.com/browse/ISPN-16072
> ISPN-16070 Remove clustered-locks from the server

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
https://issues.redhat.com/browse/ISPN-16101
> Revise Redis commands layout in Infinispan docs

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
- client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelFactory.java
https://issues.redhat.com/browse/ISPN-16093
> ISPN-16093 Hot Rod client should PING servers added on topology update

- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
https://issues.redhat.com/browse/ISPN-16107
> ISPN-16107 RocksDBStore: wait for batch to complete before writing

- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/remote/AbstractHotRodQueryIT.java
https://issues.redhat.com/browse/ISPN-16143
> ISPN-16143 HotRodQueryIT fix

- server/runtime/src/main/resources/infinispan-defaults.xml
- server/tests/src/test/resources/data/templates.xml
https://issues.redhat.com/browse/ISPN-13839
> ISPN-13839 Remove invalidation templates from internal server config

- build/configuration/pom.xml
- server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
https://issues.redhat.com/browse/ISPN-16138
> ISPN-16138 Update Console to 15.0.6.Final

- distribution/src/main/resources/licenses/mit-0.txt
- distribution/src/main/resources/template/licenses.xsl
- server/runtime/build.xml
https://issues.redhat.com/browse/ISPN-16148
> ISPN-16148 Add missing licenses for ISPN 15

- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/remote/AbstractHotRodQueryIT.java
https://issues.redhat.com/browse/ISPN-16143
> [14.0] ISPN-16143 HotRodQueryIT fix

- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/store/AbstractInfinispanStoreRocksDBIT.java
https://issues.redhat.com/browse/ISPN-16152
> ISPN-16152 Clean up RockDB directory before starting tests

- .github/workflows/dependabot_pull_request.yml
- .github/workflows/pull_request_merged.yml
- .github/workflows/pull_request_open.yml
- .github/workflows/sync_docs.yml
@tristantarrant I think I have got all the missing pieces, but please double check the changes to the docs publishing workflow as I'm not 100% on how that works.
> Update GH actions to take into account 15.0.x and main

- documentation/src/main/asciidoc/stories/assembly_spring_boot_embedded.adoc
- documentation/src/main/asciidoc/stories/assembly_spring_boot_remote.adoc
- documentation/src/main/asciidoc/topics/proc_spring_boot_embedded_reactive.adoc
- documentation/src/main/asciidoc/topics/proc_spring_boot_remote_reactive.adoc
- spring/spring-boot-3/embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanEmbeddedCacheManagerAutoConfiguration.java
- spring/spring-boot-3/embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanEmbeddedConfigurationProperties.java
- spring/spring-boot-3/remote/pom.xml
- spring/spring-boot-3/remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteCacheManagerAutoConfiguration.java
- spring/spring-boot-3/remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteConfigurationProperties.java
- spring/spring6/spring6-common/src/main/java/org/infinispan/spring/common/provider/SpringCache.java
- spring/spring6/spring6-embedded/src/main/java/org/infinispan/spring/embedded/provider/ContainerEmbeddedCacheManagerFactoryBean.java
- spring/spring6/spring6-embedded/src/main/java/org/infinispan/spring/embedded/provider/SpringEmbeddedCacheManager.java
- spring/spring6/spring6-remote/src/main/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManager.java
- spring/spring6/spring6-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheTest.java
https://issues.redhat.com/browse/ISPN-16140
> ISPN-16140 Spring Cache reactive methods fix

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/java/org/infinispan/xsite/events/XSiteEventsManagerImpl.java
- core/src/main/java/org/infinispan/xsite/events/XSiteViewMetrics.java
https://issues.redhat.com/browse/ISPN-16154
> ISPN-16154 Cross site view change event logs stale view

- documentation/src/main/asciidoc/topics/json/tracing_cache_config.json
- documentation/src/main/asciidoc/topics/json/tracing_cache_container.json
- documentation/src/main/asciidoc/topics/xml/tracing_cache_config.xml
- documentation/src/main/asciidoc/topics/xml/tracing_cache_container.xml
- documentation/src/main/asciidoc/topics/yaml/tracing_cache_config.yaml
- documentation/src/main/asciidoc/topics/yaml/tracing_cache_container.yaml
https://issues.redhat.com/browse/ISPN-13725
> ISPN-13725 Fixes some docs issues

- commons/all/src/main/java/org/infinispan/commons/marshall/ProtoStreamMarshaller.java
- core/src/main/java/org/infinispan/marshall/protostream/impl/SerializationContextRegistryImpl.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java
* Enable collection wrapping by default to fix IPROTO-273
https://issues.redhat.com/browse/ISPN-16177
> ISPN-16177 Enable collection wrapping for Protostream

- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- documentation/src/main/asciidoc/topics/json/rest_caches_info_response.json
- documentation/src/main/asciidoc/topics/json/rest_container_response.json
- documentation/src/main/asciidoc/topics/json/rest_full_cache_detail.json
- documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
- server/rest/src/test/java/org/infinispan/rest/resources/ContainerResourceTest.java
https://issues.redhat.com/browse/ISPN-16170
> ISPN-16170 Expose if tracing is enabled in the server

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
https://issues.redhat.com/browse/ISPN-16170
> ISPN-16170 Return true y global is also enabled

- documentation/src/main/asciidoc/topics/proc_spring_boot_embedded_reactive.adoc
- documentation/src/main/asciidoc/topics/proc_spring_boot_remote_reactive.adoc
https://issues.redhat.com/browse/ISPN-16189
> ISPN-16189: Doc fix for Spring Cache reactive methods

- persistence/jdbc/pom.xml
- query-core/pom.xml
- remote-query/remote-query-client/pom.xml
- spring/spring6/spring6-common/pom.xml
- spring/spring6/spring6-embedded/pom.xml
https://issues.redhat.com/browse/ISPN-16186
> ISPN-16186 Modules missing proto-schema-compatibility-check

- server/rest/src/main/java/org/infinispan/rest/framework/impl/ResourceManagerImpl.java
- server/rest/src/main/java/org/infinispan/rest/framework/impl/ResourceNode.java
https://issues.redhat.com/browse/ISPN-16165
Makes the method 4x faster and allocate less
> ISPN-16165 ResourceManagerImpl.lookupResource micro-optimization

- documentation/src/main/asciidoc/topics/proc_executing_secure_caches.adoc
https://issues.redhat.com/browse/ISPN-14375
> ISPN-14375 Remove all references to Subject.doAs from docs

- documentation/src/main/asciidoc/topics/json/rest_cache_health_response.json
- documentation/src/main/asciidoc/topics/proc_spring_boot_embedded_reactive.adoc
- documentation/src/main/asciidoc/topics/proc_spring_boot_remote_reactive.adoc
- documentation/src/main/asciidoc/topics/ref_rest_server_security.adoc
https://issues.redhat.com/browse/ISPN-16188
> ISPN-16188: Documentation fixes for various guides

- core/src/main/java/org/infinispan/configuration/cache/IndexWriterConfiguration.java
- documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- query/src/test/java/org/infinispan/query/api/PutAllTest.java
https://issues.redhat.com/browse/ISPN-16194
~Based on https://github.com/infinispan/infinispan/pull/12503, that should be merged first!~ done we can merge it!
I also added the documentation.
> ISPN-16194 Change index writer queue config

- server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-16156
> ISPN-16156 Life easier for mac and windows

- documentation/src/main/asciidoc/topics/proc_enabling_jmx.adoc
https://issues.redhat.com/browse/ISPN-16228
> ISPN-16228: [doc] Add a statement for JMX limitations for server

- documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/upgrading_docs_cleanup
> Fix Upgrading Guide doc issues

- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationSerializer.java
- server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfigurationBuilder.java
- server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationSerializerTest.java
- server/runtime/src/test/resources/configuration/versions/15.0.xml
- server/runtime/src/test/resources/configuration/versions/15.1.xml
https://issues.redhat.com/browse/ISPN-16240
> ISPN-16240 ServerConfigurationSerializer should include the RESP endpoint

- documentation/src/main/asciidoc/topics/proc_cli_set_topology_caches.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
https://issues.redhat.com/browse/ISPN-16235
> ISPN-16235: Doc edits for topology set-stable command

- server/resp/src/main/java/org/infinispan/server/resp/ByteBufferUtils.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HINCRBY.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HINCRBYFLOAT.java
- server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
- server/resp/src/test/java/org/infinispan/server/resp/util/ArgumentUtilsTest.java
- server/resp/src/test/java/org/infinispan/server/resp/util/ByteBufferUtilsTest.java
https://issues.redhat.com/browse/ISPN-16250
> ISPN-16250 [RESP] Fixes HINCRBY and HINCRBYFLOAT

- documentation/src/main/asciidoc/topics/ref_hotrod_client_transactions.adoc
https://issues.redhat.com/browse/ISPN-16247
> ISPN-16247: Add more info about pessimistic transactions locking mode

- server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HRANDFIELD.java
- server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
https://issues.redhat.com/browse/ISPN-16241
> ISPN-16241 [RESP] "HRANDFIELD key count withvalues" should return map

- server/runtime/build.xml
https://issues.redhat.com/browse/ISPN-16172
> ISPN-16172 Exclude META-INF directory from unpacked console

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
https://issues.redhat.com/browse/ISPN-16263
> ISPN-16239: Add missing RESP commands to documentation

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16265
> ISPN-16265 Updates Console to 15.1.0.Final

- build/configuration/pom.xml
- commons/all/src/main/java/org/infinispan/commons/util/Version.java
- commons/all/src/main/resources/META-INF/infinispan-version.properties
https://issues.redhat.com/browse/ISPN-16221
> ISPN-16221 Add a Version method that is stable across builds

- server/resp/src/main/java/org/infinispan/server/resp/operation/SetOperation.java
- server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
https://issues.redhat.com/browse/ISPN-16276
fixes setting ttl with xx
> ISPN-16276 set ttl with xx

- documentation/src/main/asciidoc/topics/json/resp_cache.json
- documentation/src/main/asciidoc/topics/proc_server_configuring_resp.adoc
- documentation/src/main/asciidoc/topics/xml/resp_cache.xml
- documentation/src/main/asciidoc/topics/yaml/resp_cache.yaml
Documentation for resp cache explicit configuration
> [DOC] ISPN-16229 Added docs for explicit resp cache config

- integrationtests/endpoints-interop-it/pom.xml
- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointsCacheFactory.java
- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/ProtoCacheRestHotRodTest.java
https://issues.redhat.com/browse/ISPN-16213
https://issues.redhat.com/browse/JDG-7111
Based on https://github.com/infinispan/protostream/pull/284 => draft
> ISPN-16213 Test endpoint it root list strings

- server/resp/src/main/java/org/infinispan/server/resp/commands/string/GETRANGE.java
- server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
https://issues.redhat.com/browse/ISPN-16272
> ISPN-16272 [RESP] GETRANGE can't handle huge ranges

- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/string/LCS.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/string/STRALGO.java
- server/resp/src/main/java/org/infinispan/server/resp/operation/LCSOperation.java
- server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java
- server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
https://issues.redhat.com/browse/ISPN-14653
No tests because Lettuce doesn't have an API for LCS.
> ISPN-14653 LCS

- multimap/src/main/java/org/infinispan/multimap/impl/function/set/SPopFunction.java
- multimap/src/main/java/org/infinispan/multimap/impl/function/set/SSetFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
fixes [ISPN-16283](https://issues.redhat.com/browse/ISPN-16283)
> ISPN-16283 Remove set if empty after operation

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedSetCache.java
- multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java
- multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java
- multimap/src/main/java/org/infinispan/multimap/impl/function/set/SMIsMember.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/set/SMISMEMBER.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
fixes [ISPN-16282](https://issues.redhat.com/browse/ISPN-16282)
> ISPN-16282 SMISMEMBER implementation

- documentation/src/main/asciidoc/topics/proc_cli_set_topology_caches.adoc
https://issues.redhat.com/browse/ISPN-16235
> ISPN-16235: Doc edits for topology set-stable command review

- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-16294
> ISPN-16294 Don't force the server port in the code

- commons/all/src/main/java/org/infinispan/commons/util/GlobMatcher.java
- commons/all/src/test/java/org/infinispan/commons/util/GlobMatcherTest.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/pubsub/CHANNELS.java
- server/resp/src/main/java/org/infinispan/server/resp/filter/GlobMatchFilterConverter.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-16296
Created a glob matcher inspired by Valkey's implementation and then replaced every conversion of a glob to a pattern on the RESP module.
> ISPN-16296 [RESP] KEYS may cause server to get stuck

- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationSerializer.java
- server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfigurationBuilder.java
- server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationSerializerTest.java
- server/runtime/src/test/resources/configuration/versions/15.0.xml
https://issues.redhat.com/browse/ISPN-16240
Backport of #12576.
> [15.0.x] ISPN-16240 ServerConfigurationSerializer should include the RESP endpoint

- server/resp/src/main/java/org/infinispan/server/resp/RespDetector.java
https://issues.redhat.com/browse/ISPN-16308
> ISPN-16308 Auto-detect RESP when SELECT is the first command

- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
- pom.xml
- server/rest/src/main/java/org/infinispan/rest/resources/BackupManagerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/NettyLeakDetectionLoggingConsumer.java
https://issues.redhat.com/browse/ISPN-16233
I've added code that fails the server testsuite if a leak is detected
> ISPN-16233 Fix Netty buffer leaks

- server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java
- server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java
- server/resp/src/test/java/org/infinispan/server/resp/test/RespTestingUtil.java
- server/tests/src/test/java/org/infinispan/server/functional/resp/RespHashTest.java
- server/tests/src/test/java/org/infinispan/server/functional/resp/RespListTest.java
- server/tests/src/test/java/org/infinispan/server/functional/resp/RespSetTest.java
- server/tests/src/test/java/org/infinispan/server/functional/resp/RespSortedSetTest.java
- server/tests/src/test/java/org/infinispan/server/functional/resp/RespTransactionTest.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/RESPAuthorizationTest.java
Fixes [ISPN-16311](https://issues.redhat.com/browse/ISPN-16311)
> ISPN-16311 [RESP] Inconsistent error type

- core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
- core/src/main/java/org/infinispan/configuration/parsing/ParseUtils.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/test/java/org/infinispan/configuration/parsing/JsonParsingTest.java
- core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java
- core/src/test/resources/configs/aliases-test.json
- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
https://issues.redhat.com/browse/ISPN-16307
> ISPN-16307 Fix parsing of multi-value attributes

- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedBaseDecoder.java
- server/memcached/src/test/java/org/infinispan/server/memcached/test/MemcachedFunctionalTest.java
https://issues.redhat.com/browse/ISPN-16310
> ISPN-16310 Handle Memcached touch with 0 expiration

- server/memcached/src/main/java/org/infinispan/server/memcached/text/TextDecoder.java
https://issues.redhat.com/browse/ISPN-16233
> ISPN-16233 Fix Memcached text buffer leak

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/DelegatingRemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InternalRemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
- documentation/src/main/asciidoc/topics/upgrading.adoc
- jcache/remote/src/main/java/org/infinispan/jcache/remote/JCache.java
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWithStats.java
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWithSyncListeners.java
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
https://issues.redhat.com/browse/ISPN-16334
> ISPN-16334 RemoteCache flags should not rely upon thread local

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16333
> ISPN-16333 Updates console to 15.1.1.Final

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/query/RemoteQuery.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/embedded/RemoteQueryAccessTest.java
- commons/all/src/main/java/org/infinispan/commons/api/query/Query.java
- commons/all/src/main/java/org/infinispan/commons/api/query/impl/QueryPublisher.java
- commons/all/src/main/java/org/infinispan/commons/api/query/impl/QuerySubscription.java
- commons/all/src/main/java/org/infinispan/commons/reactive/AbstractAsyncPublisherHandler.java
- object-filter/src/test/java/org/infinispan/objectfilter/test/FilterQueryFactory.java
- query-core/src/main/java/org/infinispan/query/core/impl/BaseEmbeddedQuery.java
- query-core/src/main/java/org/infinispan/query/core/impl/DelegatingQuery.java
- query-dsl/src/main/java/org/infinispan/query/dsl/Query.java
- query-dsl/src/test/java/org/infinispan/query/dsl/impl/DummyQuery.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/EmbeddedLuceneQuery.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/access/RemoteQueryAccessQuery.java
* Add reactive list method
https://issues.redhat.com/browse/ISPN-16279
> ISPN-16279 Non blocking methods for Query API

- server/resp/src/main/java/org/infinispan/server/resp/commands/string/MSETNX.java
- server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java
- server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
> [15.0.x] [RESP] ISPN-16278 Fix msetnx behavior with same key

- .github/workflows/on_propen_push_do_test.yml
> fixing trivial format in gh action

- core/src/main/java/org/infinispan/configuration/cache/PersistenceConfiguration.java
- core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheWriterInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/DistCacheWriterInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/IsMarshallableInterceptor.java
- core/src/test/java/org/infinispan/xsite/irac/persistence/IracAsyncStoreTest.java
Fixes NPE with async store
Fixes remove operations not removing the entry from the cache store
https://issues.redhat.com/browse/ISPN-16319
> ISPN-16319 NPE thrown when attempting to remove entry with xsite.

- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
https://issues.redhat.com/browse/ISPN-16231
Check on the CacheRequestProcessor so we can avoid creating a copy for every operation.
> ISPN-16231 Skip return value internally if Hot Rod request does not force return value.

- bin/jira/track_flaky_tests.sh
fixes flaky test report when one class has multiple tests failure
See [ISPN-16395](https://issues.redhat.com/browse/ISPN-16395)
> ISPN-16395 Fix track_flaky_tests.sh

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16413
> [15.0] ISPN-16413 Upgrade Console 15.0.7.Final

- documentation/src/main/asciidoc/topics/properties/server_users_structure.properties
- documentation/src/main/asciidoc/topics/ref_server_realm_property.adoc
https://issues.redhat.com/browse/ISPN-16339
> ISPN-16339 User properties format documentation

- pom.xml
- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/LdapRealmConfigurationBuilder.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
- server/tests/pom.xml
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationLDAPSIT.java
- server/tests/src/test/java/org/infinispan/server/test/core/ldap/ApacheLdapServer.java
- server/tests/src/test/resources/configuration/AuthenticationLDAPSTest.xml
- server/tests/src/test/resources/configuration/security/ldap-ssl.xml
https://issues.redhat.com/browse/ISPN-16120
> ISPN-16120 LDAP SSL

- commons/all/src/main/java/org/infinispan/commons/configuration/io/xml/MXParser.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/xml/XmlConfigurationWriter.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/xml/XmlPullParserException.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReader.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationWriter.java
- commons/all/src/test/java/org/infinispan/commons/configuration/io/json/JsonConfigurationReaderTest.java
- commons/all/src/test/java/org/infinispan/commons/configuration/io/xml/XmlConfigurationReaderTest.java
- commons/all/src/test/java/org/infinispan/commons/configuration/io/xml/XmlConfigurationWriterTest.java
- commons/all/src/test/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReaderTest.java
- commons/all/src/test/resources/json.json
- commons/all/src/test/resources/yaml.yaml
https://issues.redhat.com/browse/ISPN-16354
> ISPN-16354 Correctly handle escape sequences in XML and YAML

- integrationtests/endpoints-interop-it/pom.xml
- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointsCacheFactory.java
- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/ProtoCacheRestHotRodTest.java
https://issues.redhat.com/browse/ISPN-16213
https://issues.redhat.com/browse/JDG-7111
Backport of #12567
> [15.0] ISPN-16213 Test endpoint it root list strings

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16390
> ISPN-16390 ProtoStream 5.0.8.Final

- bin/jira/track_flaky_tests.sh
https://issues.redhat.com/browse/ISPN-16395
> ISPN-16395 Fix flaky test extraction

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetAddArgs.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-16416
> ISPN-16416 ZADD catch proper validation error for incopatible options

- server/resp/src/main/java/org/infinispan/server/resp/commands/string/SETRANGE.java
- server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
https://issues.redhat.com/browse/ISPN-16425
> ISPN-16425 Setrange should not create empty entries

- server/resp/src/main/java/org/infinispan/server/resp/commands/string/GETRANGE.java
- server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
https://issues.redhat.com/browse/ISPN-16424
> ISPN-16424 GETRANGE single character

- server/resp/src/main/java/org/infinispan/server/resp/commands/list/LMPOP.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZRANK.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZSetCommonUtils.java
- server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
- server/resp/src/test/java/org/infinispan/server/resp/commands/sortedset/ZSetCommonUtilsTest.java
https://issues.redhat.com/browse/ISPN-16419
> ISPN-16419 Fixes LMPOP and WITHSCORES case sensitive

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-16418
> ISPN-16418 Fixes Sorted Set XX option with LT or GT option

- core/src/test/java/org/infinispan/test/data/Numerics.java
- persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java
- persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
- persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcStoreFunctionalTest.java
https://issues.redhat.com/browse/ISPN-16383
> ISPN-16383 SQL store numeric precision throwing in acceptable values

- core/src/main/resources/schema/infinispan-config-15.1.xsd
https://issues.redhat.com/browse/ISPN-16417
> ISPN-16417 Fix maxOccurs in XSD schema for index-sharding

- commons/all/src/main/java/org/infinispan/commons/configuration/io/xml/MXParser.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/xml/XmlConfigurationWriter.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/xml/XmlPullParserException.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReader.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationWriter.java
- commons/all/src/test/java/org/infinispan/commons/configuration/io/json/JsonConfigurationReaderTest.java
- commons/all/src/test/java/org/infinispan/commons/configuration/io/xml/XmlConfigurationReaderTest.java
- commons/all/src/test/java/org/infinispan/commons/configuration/io/xml/XmlConfigurationWriterTest.java
- commons/all/src/test/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReaderTest.java
- commons/all/src/test/resources/json.json
- commons/all/src/test/resources/yaml.yaml
https://issues.redhat.com/browse/ISPN-16354
> [15.0] ISPN-16354 Correctly handle escape sequences in XML and YAML

- multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java
https://issues.redhat.com/browse/ISPN-16416
> ISPN-16416 Assert IllegalArgumentException

- server/resp/src/main/java/org/infinispan/server/resp/commands/list/LMPOP.java
- server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
https://issues.redhat.com/browse/ISPN-16422
> ISPN-16419 LMPOP Raise syntax error with extra args

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/aggregation/RemoteQueryAggregationCountTest.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/AggregationPropertyPath.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/IckleParsingResult.java
- query/src/test/java/org/infinispan/query/aggregation/QueryAggregationBroadcastTest.java
- query/src/test/java/org/infinispan/query/aggregation/QueryAggregationCountTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/JsonQuerySerializer.java
- server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
- server/rest/src/test/java/org/infinispan/rest/search/SearchCountClusteredTest.java
- server/rest/src/test/java/org/infinispan/rest/search/aggregation/RestQueryAggregationCountTest.java
https://issues.redhat.com/browse/ISPN-15336
~~Draft => regression should have been fixed, but the labels for the aggregations are still not good~~ done
Based on top of => https://github.com/infinispan/infinispan/pull/12764
> ISPN-15336 Non-understandable column names in case of running count(*) on aggregation queries

- server/rest/src/main/java/org/infinispan/rest/resources/ProtobufResource.java
https://issues.redhat.com/browse/ISPN-16410
> ISPN-16410 Capture an exception if the put schema fails

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/aggregation/RemoteQueryAggregationCountTest.java
- query/src/test/java/org/infinispan/query/aggregation/QueryAggregationBroadcastTest.java
- query/src/test/java/org/infinispan/query/aggregation/QueryAggregationCountTest.java
https://issues.redhat.com/browse/ISPN-16349
This should reduce the chance of timing out...
> ISPN-16349 Reduce put-all chuck size from 1000 to 100

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/key/tutorial/Author.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/key/tutorial/Person.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/key/tutorial/PersonKey.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/key/tutorial/QueryByKeyTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/key/tutorial/TutorialSchema.java
https://issues.redhat.com/browse/ISPN-10957
Adding this PR more tests. The main code looks good so far...
> ISPN-10957 Test more query by key cases

- core/src/main/java/org/infinispan/interceptors/impl/AbstractIracLocalSiteInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/NonTxIracLocalSiteInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/OptimisticTxIracLocalSiteInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/PessimisticTxIracLocalInterceptor.java
https://issues.redhat.com/browse/ISPN-15776
> ISPN-15776 Flaky test: IracAlwaysRemoveConflictTest#testRemove

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/Message.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/map/MapStringTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingTagHandler.java
https://issues.redhat.com/browse/ISPN-16473
> ISPN-16473 Skip indexing of map fields

- server/resp/src/main/java/org/infinispan/server/resp/commands/set/SINTERCARD.java
- server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
Fix for [ISPN-16377](https://issues.redhat.com/browse/ISPN-16377)
> ISPN-16377 [RESP] SINTERCARD Fixed error message

- query-core/src/main/java/org/infinispan/query/core/impl/BaseEmbeddedQuery.java
- query-core/src/main/java/org/infinispan/query/core/impl/EmbeddedQuery.java
- query-core/src/main/java/org/infinispan/query/core/impl/HybridQuery.java
Fix query duration computation and record delete statements
https://issues.redhat.com/browse/ISPN-16481
> ISPN-16481 Hybrid remote queries statistics seem incorrect

- core/src/main/java/org/infinispan/configuration/cache/IndexReaderConfiguration.java
- core/src/main/java/org/infinispan/configuration/cache/IndexReaderConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/cache/IndexWriterConfiguration.java
- core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java
- query/src/main/java/org/infinispan/query/impl/config/SearchPropertyExtractor.java
https://issues.redhat.com/browse/ISPN-16522
> ISPN-16522 Refresh interval to TimeQuantity

- .github/workflows/on_propen_push_do_test.yml
flaky test must not be reported in failed test report.
[ISPN-16517](https://issues.redhat.com/browse/ISPN-16517)
> ISPN-16517 don't publish flaky in failed test report

- documentation/src/main/asciidoc/topics/proc_configuring_server_keystores.adoc
- documentation/src/main/asciidoc/topics/proc_server_require_client_cert.adoc
https://issues.redhat.com/browse/ISPN-16526
> ISPN-16526: Doc edits for Certificate reloading documentation

- documentation/src/main/asciidoc/topics/proc_query_queries_by_keys.adoc
https://issues.redhat.com/browse/ISPN-16527
> ISPN-16527: Doc edits for index/query by key for remote queries docs

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-16579
> ISPN-16579 Expose aliases in the caches list and detail

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/pressure/LargePutAllPressureTest.java
- query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
https://issues.redhat.com/browse/ISPN-16514
Fix made by @wburns. I only added the test.
> ISPN-16514 Limit concurrency for indexing putall to 100

- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/test/java/org/infinispan/api/MetadataAPIDefaultExpiryTest.java
- core/src/test/java/org/infinispan/expiry/ExpiryTest.java
https://issues.redhat.com/browse/ISPN-16586
> ISPN-16586 Fix modification of default expiration at runtime

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-16537
> ISPN-16537 Cache health and config do not respond 404 for non running caches

- .github/workflows/on_propen_push_do_test.yml
> Fixed artifact name in github action

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/LargeTermTest.java
https://issues.redhat.com/browse/ISPN-16366
> ISPN-16366 Increase LargeTermTest socket timeout

- .github/workflows/on_run_create_jira_flaky_test.yml
- .github/workflows/on_run_publish_surefire_report.yml
Skip subsequent steps when build fails.
> ISPN-16628 CI Skip following step on build failure

- .github/workflows/on_run_publish_surefire_report.yml
fail if too few tests have been run
see [ISPN-16629](https://issues.redhat.com/browse/ISPN-16629)
> ISPN-16629 Ensure that at least 30000 have been run

- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/AggregationPropertyPath.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/IckleParsingResult.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/JsonQuerySerializer.java
- server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
- server/rest/src/test/java/org/infinispan/rest/search/SearchCountClusteredTest.java
- server/rest/src/test/java/org/infinispan/rest/search/aggregation/RestQueryAggregationCountTest.java
https://issues.redhat.com/browse/ISPN-15336
Backport of https://github.com/infinispan/infinispan/pull/12764
> [15.0] ISPN-15336 Non-understandable column names in case of running count(*) on aggregation queries

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdmin.java
- commons/all/src/main/java/org/infinispan/commons/api/CacheContainerAdmin.java
- commons/all/src/main/java/org/infinispan/commons/configuration/attributes/Attribute.java
- commons/all/src/main/java/org/infinispan/commons/util/Util.java
- commons/all/src/test/java/org/infinispan/commons/configuration/attributes/AttributeTest.java
- core/src/main/java/org/infinispan/cache/impl/AliasCache.java
- core/src/main/java/org/infinispan/configuration/ConfigurationManager.java
- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManagerAdmin.java
- core/src/main/java/org/infinispan/manager/EmbeddedCacheManagerAdmin.java
- server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/CacheUpdateConfigurationAttributeTask.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
- server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodAdmin.java
https://issues.redhat.com/browse/ISPN-16578
> ISPN-16578 Fix cache aliases with Hot Rod

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16612
> ISPN-16612 Elytron 2.6.0.Final

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16646
> ISPN-16646 Update Console to 15.1.2.Final

- build/configuration/pom.xml
- client/hotrod/pom.xml
- graalvm/client-hotrod/pom.xml
- graalvm/core/pom.xml
- pom.xml
- quarkus/integration-tests/server/pom.xml
- server/testdriver/junit5/pom.xml
- server/tests/pom.xml
https://issues.redhat.com/browse/ISPN-16642
> ISPN-16642 Utilise JUnit5 bom to align dependencies

- .github/workflows/on_run_publish_surefire_report.yml
Some xml test report files doesn't end with `Test.xml` or contain spaces.
[ISPN-16641](https://issues.redhat.com/browse/ISPN-16641)
> ISPN-16641 Fix test runs count

- server/resp/src/main/java/org/infinispan/server/resp/commands/set/SINTERCARD.java
- server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
> [15.0.x] ISPN-16377 SINTERCARD Fixed error message

- .github/workflows/operator_upgrade.yaml
> Bump action-setup-cekit 1.1.6

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16614
Replaces https://github.com/infinispan/infinispan/pull/12892
> ISPN-16614 Remove all traces of the transformer plugin

- client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/query/pressure/LargePutAllPressureTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/pressure/LargePutAllPressureTest.java
https://issues.redhat.com/browse/ISPN-16533
@tristantarrant I increased the socket timeout to 5 min, logging the actual time.
The output of the log is not present on the Maven process log, but on the `target/infinispan-infinispan-client-hotrod.log`.
On my machine for instance, I have:
```
11:34:31,517 INFO  (testng-LargePutAllPressureTest:[]) [o.i.c.h.AuthenticationTest] test executed in 9776ms
```
> ISPN-16533 Increase the socket timeout logging time

- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
* Ensure operation timeouts are cancelled on channel close
https://issues.redhat.com/browse/ISPN-14868
> ISPN-14868 Remove and refactor Client Connection Pool

- server/resp/src/main/java/org/infinispan/server/resp/RespHandler.java
- server/resp/src/main/java/org/infinispan/server/resp/RespServer.java
- server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/INFO.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/pubsub/SUBSCRIBE.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/pubsub/UNSUBSCRIBE.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/tx/UNWATCH.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/tx/WATCH.java
- server/resp/src/main/java/org/infinispan/server/resp/meta/ClientMetadata.java
- server/resp/src/main/java/org/infinispan/server/resp/meta/MetadataRepository.java
- server/resp/src/main/java/org/infinispan/server/resp/tx/RespTransactionHandler.java
- server/resp/src/test/java/org/infinispan/server/resp/metadata/InfoClientsTests.java
https://issues.redhat.com/browse/ISPN-16454
> ISPN-16454 [RESP] Track local client connection information

- client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/query/pressure/LargePutAllPressureTest.java
- client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/query/pressure/TransactionalLargePutAllPressureTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/pressure/LargePutAllPressureTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/pressure/TransactionalLargePutAllPressureTest.java
- commons/all/src/main/java/org/infinispan/commons/util/concurrent/CompletionStages.java
- query/src/main/java/org/infinispan/query/backend/TxQueryInterceptor.java
https://issues.redhat.com/browse/ISPN-16635
Based on https://github.com/infinispan/infinispan/pull/12905
> ISPN-16635 Limit the indexing concurrency of large put all transactional

- server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/list/LPOS.java
- server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java
- server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
- server/resp/src/test/java/org/infinispan/server/resp/util/ArgumentUtilsTest.java
Fixes [ISPN-16372](https://issues.redhat.com/browse/ISPN-16372)
changed ArgumentUtils.toLong to handle long overflow
> ISPN-16372 [RESP] LPOS and fix long overflow

- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
* Remove log number from assertion
https://issues.redhat.com/browse/ISPN-12358
> ISPN-12358 Fix log ranges

- client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/query/projection/RemoteMetaProjectionTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/projection/RemoteMetaProjectionTest.java
- commons/all/src/main/java/org/infinispan/commons/api/query/ClosableIteratorWithCount.java
- commons/all/src/main/java/org/infinispan/commons/api/query/Query.java
- commons/all/src/main/java/org/infinispan/commons/util/Closeables.java
- query-core/src/main/java/org/infinispan/query/core/impl/AggregatingQuery.java
- query-core/src/main/java/org/infinispan/query/core/impl/BaseEmbeddedQuery.java
- query-core/src/main/java/org/infinispan/query/core/impl/DelegatingQuery.java
- query-core/src/main/java/org/infinispan/query/core/impl/EmbeddedQuery.java
- query-core/src/main/java/org/infinispan/query/core/impl/EmptyResultQuery.java
- query-core/src/main/java/org/infinispan/query/core/impl/HybridQuery.java
- query-core/src/main/java/org/infinispan/query/core/impl/MappingEntryIterator.java
- query-core/src/main/java/org/infinispan/query/core/impl/MappingIterator.java
- query-core/src/main/java/org/infinispan/query/core/impl/MetadataHybridQuery.java
- query-core/src/main/java/org/infinispan/query/core/impl/QueryEngine.java
- query-core/src/main/java/org/infinispan/query/core/impl/QueryResultImpl.java
- query-dsl/src/main/java/org/infinispan/query/dsl/QueryResult.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/BaseQuery.java
- query-dsl/src/test/java/org/infinispan/query/dsl/impl/DummyQuery.java
- query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java
- query/src/main/java/org/infinispan/query/clustered/DistributedIterator.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/EmbeddedLuceneQuery.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java
- query/src/main/java/org/infinispan/query/impl/IndexedQuery.java
- query/src/main/java/org/infinispan/query/impl/IndexedQueryImpl.java
- query/src/main/java/org/infinispan/query/impl/ScrollerIteratorAdaptor.java
- query/src/test/java/org/infinispan/pagination/DistributedPaginationTest.java
- query/src/test/java/org/infinispan/pagination/PaginationTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/access/RemoteQueryAccessQuery.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-16585
Based on https://github.com/infinispan/infinispan/pull/12860 that should be merged first!
> ISPN-16585 Apply max result on (projection-only-hybrid) queries

- server/runtime/src/main/server/bin/common.sh
Resolves
https://issues.redhat.com/browse/ISPN-16703
14 - https://github.com/infinispan/infinispan/pull/12954
15 - https://github.com/infinispan/infinispan/pull/12956
> ISPN-16703 Server startup script consults java from PATH instead of configured JAVA or JAVA_HOME for version consultation

- server/runtime/src/main/server/bin/common.sh
Resolves
https://issues.redhat.com/browse/ISPN-16703
> [15.0.x] ISPN-16703 Server startup script consults java from PATH instead of configured JAVA or JAVA_HOME for version consultation #12954

- server/runtime/src/main/server/bin/common.sh
Resolves
https://issues.redhat.com/browse/ISPN-16703
> [14.0.x] ISPN-16703 Server startup script consults java from PATH instead of configured JAVA or JAVA_HOME for version consultation

- server/resp/src/main/java/org/infinispan/server/resp/logging/AccessLoggerManager.java
- server/resp/src/test/java/org/infinispan/server/resp/logging/RespAccessLoggingTest.java
https://issues.redhat.com/browse/ISPN-16692
> ISPN-16692 RESP not tracking unknown commands

- build/configuration/pom.xml
- quarkus/integration-tests/server/pom.xml
https://issues.redhat.com/browse/ISPN-16612
> ISPN-16612 Elytron 2.6.0

- client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/tracing/TracingAttributeChangeTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/TracingAttributeChangeTest.java
- core/src/main/java/org/infinispan/configuration/cache/TracingConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
- server/rest/src/test/java/org/infinispan/rest/tracing/RestTracingAttributeChangeTest.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/RESTAuthorizationTest.java
https://issues.redhat.com/browse/ISPN-16667
> ISPN-16667 Fix tracing categories config parsing

- core/src/main/java/org/infinispan/configuration/ConfigurationManager.java
- core/src/main/java/org/infinispan/configuration/cache/ContentTypeConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/cache/EncodingConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/test/java/org/infinispan/api/StaticCacheAliasTest.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/resources/configs/all/10.0.xml
- core/src/test/resources/configs/all/10.1.xml
- core/src/test/resources/configs/all/11.0.xml
- core/src/test/resources/configs/all/12.0.xml
- core/src/test/resources/configs/all/12.1.xml
- core/src/test/resources/configs/all/13.0.xml
- core/src/test/resources/configs/all/14.0.xml
- core/src/test/resources/configs/all/15.0.xml
- core/src/test/resources/configs/all/15.1.xml
https://issues.redhat.com/browse/ISPN-16709
https://issues.redhat.com/browse/ISPN-16710
https://issues.redhat.com/browse/ISPN-14798
> ISPN-16709 Static alias config

- core/src/main/java/org/infinispan/cache/impl/StatsCollectingCache.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheMgmtInterceptor.java
- core/src/main/java/org/infinispan/metrics/impl/helper/KeyMetrics.java
- core/src/main/java/org/infinispan/stats/impl/StatsCollector.java
https://issues.redhat.com/browse/ISPN-16636
> ISPN-16636 SimpleCache metrics

- core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
https://issues.redhat.com/browse/ISPN-16699
> ISPN-16699 RESP blocking during get with expiration in simple cache

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16706
> ISPN-16706 Quarkus 3.8.6

- server/core/src/main/java/org/infinispan/server/core/transport/FlushConsolidationInitializer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
* Add FlushConsolidationHandler
https://issues.redhat.com/browse/ISPN-14874
> ISPN-14874 Ensure HotRod server has proper pipelining support

- core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
https://issues.redhat.com/browse/ISPN-16699
Backport of #12947
> [15.0.x] ISPN-16699 RESP blocking during get with expiration in simple cache

- core/src/main/java/org/infinispan/configuration/ConfigurationManager.java
- core/src/main/java/org/infinispan/configuration/cache/ContentTypeConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/cache/EncodingConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/test/java/org/infinispan/api/StaticCacheAliasTest.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/resources/configs/all/10.0.xml
- core/src/test/resources/configs/all/10.1.xml
- core/src/test/resources/configs/all/11.0.xml
- core/src/test/resources/configs/all/12.0.xml
- core/src/test/resources/configs/all/12.1.xml
- core/src/test/resources/configs/all/13.0.xml
- core/src/test/resources/configs/all/14.0.xml
- core/src/test/resources/configs/all/15.0.xml
https://issues.redhat.com/browse/ISPN-16709
https://issues.redhat.com/browse/ISPN-16710
https://issues.redhat.com/browse/ISPN-14798
> [15.0] ISPN-16709 Static alias config

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16721
> ISPN-16721 ProtoStream 5.0.10.Final

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16721
> [15.0] ISPN-16721 ProtoStream 5.0.10.Final

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16724
> ISPN-16274 ProtoStream 5.0.11.Final

- documentation/src/main/asciidoc/topics/hotrod_protocol.adoc
https://issues.redhat.com/browse/ISPN-16662
> ISPN-16662 Stream Cache Command Docs

- core/src/test/java/org/infinispan/distribution/rehash/PessimisticStateTransferLocksTest.java
- core/src/test/java/org/infinispan/remoting/inboundhandler/OffloadInboundInvocationHandler.java
The response is being blocked the by StateSequencer when delivered in a MessageBatch
https://issues.redhat.com/browse/ISPN-15788
https://issues.redhat.com/browse/ISPN-15825
> ISPN-15788 Flaky test: PessimisticStateTransferLocksTest

- client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/query/MultiHotRodServerQueryTest.java
- client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/query/pressure/LargePutAllPressureTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/MultiHotRodServerQueryTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/pressure/LargePutAllPressureTest.java
- core/src/main/java/org/infinispan/configuration/parsing/Attribute.java
- query/src/main/java/org/infinispan/configuration/cache/PrivateIndexingConfiguration.java
- query/src/main/java/org/infinispan/configuration/cache/PrivateIndexingConfigurationBuilder.java
- query/src/main/java/org/infinispan/query/impl/IndexerConfig.java
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- query/src/main/java/org/infinispan/search/mapper/impl/InfinispanMappingInitiator.java
- query/src/main/java/org/infinispan/search/mapper/mapping/SearchMapping.java
- query/src/main/java/org/infinispan/search/mapper/mapping/SearchMappingBuilder.java
- query/src/main/java/org/infinispan/search/mapper/mapping/SearchMappingCommonBuilding.java
- query/src/main/java/org/infinispan/search/mapper/mapping/impl/InfinispanMapperDelegate.java
- query/src/main/java/org/infinispan/search/mapper/mapping/impl/InfinispanMapping.java
- query/src/main/java/org/infinispan/search/mapper/mapping/impl/InfinispanMappingPartialBuildState.java
- query/src/main/java/org/infinispan/search/mapper/work/impl/SearchIndexerImpl.java
- query/src/test/java/org/infinispan/query/aggregation/QueryAggregationCountTest.java
- query/src/test/java/org/infinispan/query/helper/SearchMappingHelper.java
- server/rest/src/test/java/org/infinispan/rest/search/aggregation/RestQueryAggregationCountTest.java
https://issues.redhat.com/browse/ISPN-16533
It seems that we didn't fix this flaky test.
At this point I vote for reintroducing the @wburns's idea about adding some private index configuration to reproduce the case without needing to have a very massive test.
What does the team think of it?
> ISPN-16533 Reduce test volumes - Introducing PrivateIndexingConfiguration

- core/src/main/java/org/infinispan/configuration/cache/ContentTypeConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/cache/EncodingConfigurationBuilder.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/resources/configs/all/10.0.xml
- core/src/test/resources/configs/all/10.1.xml
- core/src/test/resources/configs/all/11.0.xml
- core/src/test/resources/configs/all/12.0.xml
- core/src/test/resources/configs/all/12.1.xml
- core/src/test/resources/configs/all/13.0.xml
- core/src/test/resources/configs/all/14.0.xml
https://issues.redhat.com/browse/ISPN-16710
> [14.0] ISPN-16710 Fix encoding inheritance

- core/src/main/java/org/infinispan/marshall/exts/CollectionExternalizer.java
- core/src/test/java/org/infinispan/marshall/exts/AbstractExternalizerTest.java
- core/src/test/java/org/infinispan/marshall/exts/CollectionExternalizerTest.java
https://issues.redhat.com/browse/ISPN-16262
> ISPN-16262 Marshall some additional private list classes

- spring/spring-boot-3/remote/src/main/java/org/infinispan/spring/starter/remote/actuator/RemoteInfinispanCacheMeterBinder.java
- spring/spring-boot-3/remote/src/test/java/test/org/infinispan/spring/starter/remote/actuator/RemoteCacheMetricBinderTest.java
https://issues.redhat.com/browse/ISPN-16645
> ISPN-16645 Fix RemoteCacheMetricBinderTest flaky test

- core/src/main/java/org/infinispan/security/actions/GetCacheComponentAction.java
- core/src/main/java/org/infinispan/security/actions/SecurityActions.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-12335
> ISPN-12335 Expose rebalancing inflight segments in REST cache info

- query-core/src/main/java/org/infinispan/query/core/impl/Log.java
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
https://issues.redhat.com/browse/ISPN-16738
> ISPN-16738 Reduce log severity for query interceptor

- Jenkinsfile
- build/configuration/pom.xml
- hibernate/cache-v62/pom.xml
https://issues.redhat.com/browse/ISPN-16733
Unfortunately this makes testing a bit longer, so the full matrix is included only in branch builds
> ISPN-16733 Test with Hibernate 6.2, 6.4, 6.5, 6.6

- server/runtime/src/main/server/bin/report-osx.sh
- server/runtime/src/main/server/bin/report.sh
https://issues.redhat.com/browse/ISPN-16672
> ISPN-16672 Avoid blocking calls in lsof in server report

- README-Build.md
change asciidoc syntax to markdown syntax
> fix broken link in README-Build.md

- client/hotrod-client-new/pom.xml
- client/hotrod-client/pom.xml
- server/rest/pom.xml
https://issues.redhat.com/browse/ISPN-16643
> ISPN-16643 Use different log file for serial execution

- query/src/test/java/org/infinispan/query/distributed/AsyncMassIndexPerfTest.java
- query/src/test/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelperTest.java
- query/src/test/java/org/infinispan/query/dsl/embedded/impl/LuceneTransformationTest.java
- query/src/test/java/org/infinispan/query/helper/SearchMappingHelper.java
https://issues.redhat.com/browse/ISPN-16737
> ISPN-16737 Re-add 2 query tests to the CI

- documentation/src/main/asciidoc/topics/code_examples/HotRodMetrics.java
- documentation/src/main/asciidoc/topics/code_examples/HotRodMicrometerMetrics.java
- documentation/src/main/asciidoc/topics/proc_configuring_hotrod_metrics.adoc
https://issues.redhat.com/browse/ISPN-16734
> ISPN-16734: Docs edits for Hot Rod micrometer metrics

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
- multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/IncrFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-16739
> ISPN-16739 [RESP] ZINCRBY allow create with infinite score

- CODEOWNERS
- CODE_OF_CONDUCT.md
- README.md
- dco.txt
https://issues.redhat.com/browse/ISPN-15035
> ISPN-15035 Add community docs

- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIRETIME.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/PEXPIRETIME.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/PTTL.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TTL.java
- server/resp/src/test/java/org/infinispan/server/resp/AbstractRespTest.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-16740
> ISPN-16740 [RESP] TTL/PTTL should return remaining time

- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIRE.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-16744
https://issues.redhat.com/browse/ISPN-16746
> ISPN-16744 [RESP] EXPIRE delete on negative expiration

- server/runtime/src/main/server/bin/report-osx.sh
- server/runtime/src/main/server/bin/report.sh
**Backport:** https://github.com/infinispan/infinispan/pull/13006
https://issues.redhat.com/browse/ISPN-16672
> [15.0.x] ISPN-16672 Avoid blocking calls in lsof in server report

- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/operations/AbstractHotRodOperation.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/operations/DelegatingHotRodOperation.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelHandler.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationDispatcher.java
- client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/ServerErrorTest.java
- commons/all/src/main/java/org/infinispan/commons/util/ArrayRingBuffer.java
- commons/all/src/test/java/org/infinispan/commons/util/ArrayRingBufferTest.java
* Add ArrayRingBuffer to store operations
https://issues.redhat.com/browse/ISPN-16735
> ISPN-16735 New client operation registration can be optimized

- documentation/src/main/asciidoc/topics/code_examples/HotRodMetrics.java
- documentation/src/main/asciidoc/topics/code_examples/HotRodMicrometerMetrics.java
- documentation/src/main/asciidoc/topics/proc_configuring_hotrod_metrics.adoc
**Backport:** https://github.com/infinispan/infinispan/pull/13021
https://issues.redhat.com/browse/ISPN-16734
> [15.0.x] ISPN-16734: Docs edits for Hot Rod micrometer metrics

- server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java
- server/resp/src/main/java/org/infinispan/server/resp/tx/RespTransactionHandler.java
- server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java
https://issues.redhat.com/browse/ISPN-16747
> ISPN-16747 [RESP] MULTI does not discard for unknown command

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
https://issues.redhat.com/browse/ISPN-16739
Fixing the addition I didn't notice before :/
I already fixed this in the open backport PR (#13029).
> ISPN-16739 SortedSetBucket fix validation

- server/resp/src/main/java/org/infinispan/server/resp/commands/set/SRANDMEMBER.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
fixed error message when srandmember count arg = Long.MIN_VALUE
see [ISPN-16752](https://issues.redhat.com/browse/ISPN-16752)
> ISPN-16752 SRANDMEMBER incorrect error message

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
- multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/IncrFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13013
https://issues.redhat.com/browse/ISPN-16739
> [15.0.x] ISPN-16739 [RESP] ZINCRBY allow create with infinite score

- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIRE.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13024
https://issues.redhat.com/browse/ISPN-16744
https://issues.redhat.com/browse/ISPN-16746
> [15.0.x] ISPN-16744 [RESP] EXPIRE delete on negative expiration

- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIRETIME.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/PEXPIRETIME.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/PTTL.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TTL.java
- server/resp/src/test/java/org/infinispan/server/resp/AbstractRespTest.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13014
https://issues.redhat.com/browse/ISPN-16740
> [15.0.x] ISPN-16740 [RESP] TTL/PTTL should return remaining time

- server/tests/src/test/java/org/infinispan/server/persistence/JGroupsJdbcPing2IT.java
https://issues.redhat.com/browse/ISPN-16749
> ISPN-16749 JGroupsJdbcPing2IT#testDBConnectionLost flaky test

- server/tests/src/test/java/org/infinispan/server/persistence/JGroupsJdbcPing2IT.java
**Backport:** https://github.com/infinispan/infinispan/pull/13033
https://issues.redhat.com/browse/ISPN-16749
> [15.0.x] ISPN-16749 JGroupsJdbcPing2IT#testDBConnectionLost flaky test

- server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodHeader.java
https://issues.redhat.com/browse/ISPN-16753
There are 3 distinct changes here
1. Don't allocate channel promises when not using access log
2. Allocate less CompletableFuture from telemetry (reduced by about 40% in my case)
3. Don't allocate EnumSet or Flag[] per invocation when no flags are provided
> ISPN-16753 Simple Server allocation rate reductions

- core/src/main/resources/default-configs/default-jgroups-azure.xml
- core/src/main/resources/default-configs/default-jgroups-ec2.xml
- core/src/main/resources/default-configs/default-jgroups-google.xml
- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/main/resources/default-configs/default-jgroups-tunnel.xml
- core/src/main/resources/default-configs/default-jgroups-udp.xml
* jgroups.diag.enable_tcp
* jgroups.diag.enable_udp
* jgroups.tcp_nodelay
https://issues.redhat.com/browse/ISPN-15954
> ISPN-15954 Add more properties to JGroups options

- server/resp/src/main/java/org/infinispan/server/resp/commands/set/SRANDMEMBER.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13036
fixed error message when srandmember count arg = Long.MIN_VALUE
see [ISPN-16752](https://issues.redhat.com/browse/ISPN-16752)
> [15.0.x] ISPN-16752 SRANDMEMBER incorrect error message

- server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZSetCommonUtils.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-16682
> ISPN-16682 Null DIFF return empty array

- server/resp/src/main/java/org/infinispan/server/resp/Util.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/SORT.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-16741
> ISPN-16741 [RESP] SORT operation does not retrieve hash fields

- server/resp/src/main/java/org/infinispan/server/resp/RespHandler.java
- server/resp/src/main/java/org/infinispan/server/resp/RespServer.java
- server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/INFO.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/pubsub/SUBSCRIBE.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/pubsub/UNSUBSCRIBE.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/tx/UNWATCH.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/tx/WATCH.java
- server/resp/src/main/java/org/infinispan/server/resp/meta/ClientMetadata.java
- server/resp/src/main/java/org/infinispan/server/resp/meta/MetadataRepository.java
- server/resp/src/main/java/org/infinispan/server/resp/tx/RespTransactionHandler.java
- server/resp/src/test/java/org/infinispan/server/resp/metadata/InfoClientsTests.java
https://issues.redhat.com/browse/ISPN-16454
Backport of #12799
> [15.0.x] ISPN-16454 [RESP] Track local client connection information

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/SORT.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-16769
> ISPN-16769 [RESP] SORT should return sorted set with BY non-existing key

- server/resp/src/main/java/org/infinispan/server/resp/commands/set/SINTER.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/set/SINTERSTORE.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
Missing keys should be treated as empty set.
Fixes [ISPN-16771](https://issues.redhat.com/browse/ISPN-16771)
> ISPN-16771 [RESP] Fix sinterstore with missing keys

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-16685
> ISPN-16685 Weight 0 is 0

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13068
https://issues.redhat.com/browse/ISPN-16685
> [15.0.x] ISPN-16685 Weight 0 is 0

- server/resp/src/main/java/org/infinispan/server/resp/Util.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/SORT.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13022
https://issues.redhat.com/browse/ISPN-16741
> [15.0.x] ISPN-16741 [RESP] SORT operation does not retrieve hash fields

- server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java
- server/resp/src/main/java/org/infinispan/server/resp/tx/RespTransactionHandler.java
- server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13025
https://issues.redhat.com/browse/ISPN-16747
> [15.0.x] ISPN-16747 [RESP] MULTI does not discard for unknown command

- server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZSetCommonUtils.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13057
https://issues.redhat.com/browse/ISPN-16682
> [15.0.x] ISPN-16682 Null DIFF return empty array

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/generic/SORT.java
- server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13067
https://issues.redhat.com/browse/ISPN-16769
> [15.0.x] ISPN-16769 [RESP] SORT should return sorted set with BY non-existing key

- .github/workflows/on_build_do_test.yml
- .github/workflows/on_test_publish_surefire_report.yml
if mvn verify fails, then fail the Test Report Result check just after
> ISPN-16781 [GITHUB CI] Fail Test Result Report if mvn verify fails

- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/xsite/OfflineStatus.java
- core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/ClusteredOfflineStatusTest.java
- core/src/test/java/org/infinispan/xsite/offline/OfflineStatusTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
https://issues.redhat.com/browse/ISPN-14558
> ISPN-14558 Global site's status

- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/xsite/OfflineStatus.java
- core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/ClusteredOfflineStatusTest.java
- core/src/test/java/org/infinispan/xsite/offline/OfflineStatusTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13060
https://issues.redhat.com/browse/ISPN-14558
> [15.0.x] ISPN-14558 Global site's status

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
- server/resp/src/test/java/org/infinispan/server/resp/types/DataStructuresMediaTypesTest.java
https://issues.redhat.com/browse/ISPN-16793
> ISPN-16793 [RESP] ZADD score restrictions with LT/GT +/-INF

- server/rest/src/main/java/org/infinispan/rest/resources/ProtobufResource.java
https://issues.redhat.com/browse/ISPN-16766
> ISPN-16766 Catch error when trying to interact protocache

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
- server/resp/src/test/java/org/infinispan/server/resp/types/DataStructuresMediaTypesTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13094
https://issues.redhat.com/browse/ISPN-16793
> [15.0.x] ISPN-16793 [RESP] ZADD score restrictions with LT/GT +/-INF

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-16788
> ISPN-16788 Return error when setting topology of non-existing cache

- core/src/main/java/org/infinispan/security/mappers/ClusterPermissionMapper.java
- core/src/main/java/org/infinispan/security/mappers/ClusterRoleMapper.java
https://issues.redhat.com/browse/ISPN-16776
> ISPN-16776 Cache org.infinispan.ROLES should wait initial state transfer

- documentation/src/main/asciidoc/topics/con_performance_partition_handling.adoc
https://issues.redhat.com/browse/ISPN-16765
> ISPN-16765: Incorrect note about GC pause in performance documentation

- quarkus/server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/SubstituteIndexClasses.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelper.java
https://issues.redhat.com/browse/ISPN-16778
> ISPN-16778 Use index field traits

- core/src/main/java/org/infinispan/security/mappers/ClusterPermissionMapper.java
- core/src/main/java/org/infinispan/security/mappers/ClusterRoleMapper.java
**Backport:** https://github.com/infinispan/infinispan/pull/13090
https://issues.redhat.com/browse/ISPN-16776
> [15.0.x] ISPN-16776 Cache org.infinispan.ROLES should wait initial state transfer

- server/rest/src/main/java/org/infinispan/rest/resources/ProtobufResource.java
**Backport:** https://github.com/infinispan/infinispan/pull/13074
https://issues.redhat.com/browse/ISPN-16766
> [15.0.x] ISPN-16766 Catch error when trying to interact protocache

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-16689
> ISPN-16689 Fix ranges with max

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
**Backport:** https://github.com/infinispan/infinispan/pull/13088
https://issues.redhat.com/browse/ISPN-16788
> [15.0.x] ISPN-16788 Return error when setting topology of non-existing cache

- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/test/java/org/infinispan/api/MetadataAPIDefaultExpiryTest.java
- core/src/test/java/org/infinispan/expiry/ExpiryTest.java
https://issues.redhat.com/browse/ISPN-16586
> [15.0] ISPN-16586 Fix modification of default expiration at runtime

- multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
- server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13082
https://issues.redhat.com/browse/ISPN-16689
> [15.0.x] ISPN-16689 Fix ranges with max

- server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
https://issues.redhat.com/browse/ISPN-14590
> ISPN-14590 Stricter CSP headers

- documentation/src/main/asciidoc/topics/json/server_client_certificate_authz.json
- documentation/src/main/asciidoc/topics/proc_configuring_client_cert_authz.adoc
- documentation/src/main/asciidoc/topics/ref_role_permission_mappers.adoc
- documentation/src/main/asciidoc/topics/xml/server_client_certificate_authz.xml
- documentation/src/main/asciidoc/topics/yaml/server_client_certificate_authz.yaml
https://issues.redhat.com/browse/ISPN-16799
> ISPN-16799 Clearer documentation for group-only-mapping

- documentation/src/main/asciidoc/topics/json/server_client_certificate_authz.json
- documentation/src/main/asciidoc/topics/proc_configuring_client_cert_authz.adoc
- documentation/src/main/asciidoc/topics/ref_role_permission_mappers.adoc
- documentation/src/main/asciidoc/topics/xml/server_client_certificate_authz.xml
- documentation/src/main/asciidoc/topics/yaml/server_client_certificate_authz.yaml
**Backport:** https://github.com/infinispan/infinispan/pull/13103
https://issues.redhat.com/browse/ISPN-16799
> [15.0.x] ISPN-16799 Clearer documentation for group-only-mapping

- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/configuration/ConnectionPoolConfigurationBuilder.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationDispatcher.java
- client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/BasicClientIntelligenceTest.java
- client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/BasicClientIntelligenceTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/hash/ConsistentHashTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CloseBeforeEnqueuingTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/TestChannelFactory.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/InternalRemoteCacheManager.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java
- documentation/src/main/asciidoc/topics/code_examples/HotRodClientFailedServerTimeout.java
- documentation/src/main/asciidoc/topics/con_hotrod_client_intelligence.adoc
- documentation/src/main/asciidoc/topics/properties/hotrod-client-failed-server-timeout.properties
* Added expiration for failed server
https://issues.redhat.com/browse/ISPN-16670
> ISPN-16670 Retry server failed on client after timeout

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/BasicClientIntelligenceTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/hash/ConsistentHashTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CloseBeforeEnqueuingTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/TestChannelFactory.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/InternalRemoteCacheManager.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java
- documentation/src/main/asciidoc/topics/code_examples/HotRodClientFailedServerTimeout.java
- documentation/src/main/asciidoc/topics/con_hotrod_client_intelligence.adoc
- documentation/src/main/asciidoc/topics/properties/hotrod-client-failed-server-timeout.properties
https://issues.redhat.com/browse/ISPN-16670
> [15.0] ISPN-16670 Retry server failed on client after timeout

- server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
**Backport:** https://github.com/infinispan/infinispan/pull/13050
https://issues.redhat.com/browse/ISPN-14590
> [15.0.x] ISPN-14590 Stricter CSP headers

- build/configuration/pom.xml
> [15.0] Updates Console to 15.0.10.Final

- .github/workflows/on_build_do_publish_image.yml
- .github/workflows/on_build_do_test.yml
- .github/workflows/on_test_publish_surefire_report.yml
- .github/workflows/on_test_update_jira_flaky_test.yml
there's no way to attach a check-run to the correct workflow.
Replacing check-run with commit status
> ISPN-16806 Using commit status instead of check run

- documentation/src/main/asciidoc/topics/ref_discovery_jdbc.adoc
https://issues.redhat.com/browse/ISPN-16801
> ISPN-16801: Docs updates related to JDBC_PING2 protocol

- graalvm/client-hotrod/src/test/java/org/infinispan/client/hotrod/graalvm/GraalClusteredTest.java
https://issues.redhat.com/browse/ISPN-16813
> Do not fail on no tests with GraalVM Client Hotrod testsuite

- graalvm/client-hotrod/src/test/java/org/infinispan/client/hotrod/graalvm/GraalClusteredTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13143
https://issues.redhat.com/browse/ISPN-16813
> [15.0.x] Do not fail on no tests with GraalVM Client Hotrod testsuite

- server/tests/src/test/java/org/infinispan/server/persistence/AsyncJdbcStringBasedCacheStore.java
Additional fix for https://issues.redhat.com/browse/ISPN-16587
> Forgotten Database tag on AsyncJdbcStringBasedCacheStore

- documentation/src/main/asciidoc/topics/ref_discovery_jdbc.adoc
**Backport:** https://github.com/infinispan/infinispan/pull/13114
https://issues.redhat.com/browse/ISPN-16801
> [15.0.x] ISPN-16801: Docs updates related to JDBC_PING2 protocol

- server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
- server/core/src/main/java/org/infinispan/server/core/ProtocolServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodTestingUtil.java
- server/runtime/src/main/java/org/infinispan/server/SecurityActions.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-12828
> [15.0] ISPN-12828 HotRod client receives a server topology before the server started

- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
- query/src/test/java/org/infinispan/query/maxresult/DistributedMaxResultTest.java
https://issues.redhat.com/browse/ISPN-16808
Co-authored-by: Pedro Ruivo <pruivo@redhat.com>
Pedro found the issue. I added the test.
> ISPN-16808 Do not limit delete cq command

- server/tests/pom.xml
- server/tests/src/test/resources/database/mariadb.properties
https://issues.redhat.com/browse/ISPN-16816
> ISPN-16816 Attempt to run @Database tests with MariaDB fails

- .github/workflows/on_build_do_publish_image.yml
- .github/workflows/on_build_do_test.yml
Cancel concurrent jobs with same head_branch same repo
see [ISPN-16812](https://issues.redhat.com/browse/ISPN-16812)
> [GitHub CI/CD] ISPN-16812 Concurrency group for PR

- pom.xml
**Backport:** https://github.com/infinispan/infinispan/pull/13144
https://issues.redhat.com/browse/ISPN-16814
> [15.0.x] ISPN-16814 Fix JDK flags for alternate JDK tests

- server/tests/pom.xml
- server/tests/src/test/resources/database/mariadb.properties
**Backport:** https://github.com/infinispan/infinispan/pull/13149
https://issues.redhat.com/browse/ISPN-16816
> [15.0.x] ISPN-16816 Attempt to run @Database tests with MariaDB fails

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16824
> [15.0] ISPN-16824 Bump com.thoughtworks.xstream:xstream from 1.4.20 to 1.4.21

- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
https://issues.redhat.com/browse/ISPN-16821
> Run in a blocking thread the CQDelete command's cache removes

- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
**Backport:** https://github.com/infinispan/infinispan/pull/13156
https://issues.redhat.com/browse/ISPN-16821
> [15.0.x] ISPN-16821 Run in a blocking thread the CQDelete command's cache removes

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-16824
> [14.0] ISPN-16284 Bump com.thoughtworks.xstream:xstream from 1.4.20 to 1.4.21

- integrationtests/server-integration/third-party-server/pom.xml
adding jboss repo to third-party-server testsuite
[ISPN-16825](https://issues.redhat.com/browse/ISPN-16825)
> ISPN-16825 jboss repo for third-party-server tests

- .github/workflows/on_build_do_test.yml
- .github/workflows/on_test_publish_surefire_report.yml
re-adding lost `if`
[ISPN-16828](https://issues.redhat.com/browse/ISPN-16828)
> [Github CI] ISPN-16828 fix check on number of text executed

- core/src/main/java/org/infinispan/metrics/impl/MetricsRegistryImpl.java
- server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
- server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsWithoutGaugeResourceIT.java
- server/tests/src/test/resources/configuration/ClusteredServerWithoutGaugeTest.xml
- server/tests/src/test/resources/configuration/cache-container/clustered-without-gauge.xml
https://issues.redhat.com/browse/ISPN-16795
> ISPN-16795 NullPointerException when gauges is set to false

- .github/workflows/on_build_do_publish_image.yml
- .github/workflows/on_build_do_test.yml
- .github/workflows/on_propen_push_do_build.yml
- .github/workflows/operator_upgrade.yaml
- .github/workflows/pull_request_native_cli.yml
- .github/workflows/supported_jdks.yaml
Added check on origin workflow result to skip subsequent workflow
added more concurrency check on pull_request/push event
> [Github CI] ISPN-16820 Check origin wf conclusion, more concurrency check

- build/configuration/pom.xml
- query/src/main/java/org/infinispan/search/mapper/impl/InfinispanMappingInitiator.java
- query/src/main/java/org/infinispan/search/mapper/impl/InfinispanSearchMapperHints.java
- query/src/main/java/org/infinispan/search/mapper/mapping/impl/InfinispanMapping.java
- query/src/main/java/org/infinispan/search/mapper/scope/impl/SearchScopeImpl.java
- query/src/main/java/org/infinispan/search/mapper/session/impl/InfinispanSearchSession.java
https://issues.redhat.com/browse/ISPN-16843
https://issues.redhat.com/browse/ISPN-16844
> ISPN-16844 Update JBossLogging 3.6.1 Search 7.2.1

- .mvn/jvm.config
removed jvm.config 
see [ISPN-16849](https://issues.redhat.com/browse/ISPN-16849)
> ISPN-16849 remove .mvn/jvm.config

- commons/all/src/main/java/org/infinispan/commons/util/concurrent/CompletionStages.java
- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
https://issues.redhat.com/browse/ISPN-16826
> ISPN-16826 PerformConcurrently with collector

- client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java
- core/src/main/resources/default-configs/default-jgroups-udp.xml
- core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
- core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
- core/src/test/java/org/infinispan/test/fwk/TransportFlags.java
- documentation/src/main/asciidoc/topics/ref_jgroups_ports.adoc
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiNodeTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodStatsClusterTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/event/AbstractHotRodClusterEventsTest.java
https://issues.redhat.com/browse/ISPN-16827
> ISPN-16827 Set fixed ports in the UDP stack

- documentation/src/main/asciidoc/stories/assembly_query_creating_ickle_queries.adoc
https://issues.redhat.com/browse/ISPN-16852
> ISPN-16852: Vector Search is not supported feature

- server/memcached/pom.xml
memcached tests should not run in parallel.
Fixes #13215
> No parallelism for memcached test. Fixes #13215

- build/configuration/pom.xml
Latest release with keycloak js fix
> Updates to Console 15.1.4.Final

- documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
- documentation/src/main/asciidoc/topics/proc_server_configuring_resp.adoc
- documentation/src/main/asciidoc/topics/proc_server_resp_differences.adoc
- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
I've added a few sections about our clustering capabilities and the differences in multi-key/transactional operations. Let me know if you think some additional subjects would be interesting to include.
Closes #13197.
> Update Resp connector documentation

- server/runtime/build.xml
- server/runtime/pom.xml
Additional fixes for #13217 since previous pr (#13218) doesn't copy all the runtime jar.
This PR adds an ant target to copy missing file at package phase.
Now server starts,  but licenses.html file has additional entries, (unwanted?):
```
<tr>
<td>@patternfly/react-charts</td><td></td><td>7.4.0</td><td><a href="http://www.opensource.org/licenses/MIT">MIT License</a>
<br>
</td><td><a href="mit license.txt">mit license.txt</a>
<br>
</td>
</tr>
<tr>
<td>@patternfly/react-code-editor</td><td></td><td>5.4.0</td><td><a href="http://www.opensource.org/licenses/MIT">MIT License</a>
<br>
</td><td><a href="mit license.txt">mit license.txt</a>
<br>
</td>
</tr>
<tr>
<td>@patternfly/react-core</td><td></td><td>5.4.0</td><td><a href="http://www.opensource.org/licenses/MIT">MIT License</a>
<br> …
```
> Server start fixed. Fixes #13271

- commons/all/src/main/java/org/infinispan/commons/util/concurrent/CompletionStages.java
- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
**Backport:** https://github.com/infinispan/infinispan/pull/13170
https://issues.redhat.com/browse/ISPN-16826
> [15.0.x] ISPN-16826 PerformConcurrently with collector

- documentation/src/main/asciidoc/stories/assembly_cli_starting.adoc
- documentation/src/main/asciidoc/topics/proc_cli_connecting_container.adoc
> Explain how to connect to the server with the CLI running in a container

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/aggregation/RemoteClusteredAggregationExpiringTest.java
- commons-test/src/main/java/org/infinispan/commons/test/annotation/TestForIssue.java
- query-core/src/main/java/org/infinispan/query/core/impl/MetadataHybridQuery.java
- query/src/test/java/org/infinispan/query/aggregation/QueryAggregationExpiringTest.java
- query/src/test/java/org/infinispan/query/model/Task.java
> Fix hybrid query loading of expired entities (#13194)

- client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/HotRodIntegrationTest.java
- client/hotrod-client-test/src/test/java/org/infinispan/client/hotrod/CacheEntryAssertions.java
- client/hotrod-client-test/src/test/java/org/infinispan/client/hotrod/HotRodAsyncCacheTest.java
- client/hotrod-client-test/src/test/java/org/infinispan/client/hotrod/HotRodMutinyCacheTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodIntegrationTest.java
- core/src/main/java/org/infinispan/container/versioning/RandomVersionGenerator.java
- core/src/main/java/org/infinispan/factories/VersionGeneratorFactory.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
> New VersionGenerator for the Hot Rod protocol

- .github/workflows/pull_request_open.yml
backport: #13226 
Closes #13299
> [15.0.x] Auto label target/<branch> for PR.

- .github/workflows/pull_request_open.yml
backport of: #13226 
Fixes #13299
> [14.0.x] Auto label target/<branch> for PR.

- documentation/src/main/asciidoc/topics/ref_query_ickle.adoc
> documentation correction

- .github/workflows/dependabot_pull_request.yml
> [#13317] Auto merge Dependabot PRs

- .github/workflows/dependabot_pull_request.yml
**Backport:** https://github.com/infinispan/infinispan/pull/13318
Closes #13317
> [14.0.x] [#13317] Auto merge Dependabot PRs

- .github/workflows/dependabot_pull_request.yml
**Backport:** https://github.com/infinispan/infinispan/pull/13318
Closes #13317
> [15.0.x] [#13317] Auto merge Dependabot PRs

- .github/workflows/pull_request_open.yml
> [14.0.x][backport] Paginate gh get labels call.

- .github/workflows/pull_request_open.yml
> [15.0.x][backport] Paginate gh get labels call. 

- .github/workflows/dependabot_pull_request.yml
> [#13318] Auto merge Dependabot utilise PR URL

- .github/workflows/dependabot_pull_request.yml
**Backport:** https://github.com/infinispan/infinispan/pull/13334
Closes #13318
> [14.0.x] [#13318] Auto merge Dependabot utilise PR URL

- .github/workflows/dependabot_pull_request.yml
**Backport:** https://github.com/infinispan/infinispan/pull/13334
Closes #13318
> [15.0.x] [#13318] Auto merge Dependabot utilise PR URL

- .github/workflows/on_propen_push_do_build.yml
- .github/workflows/pull_request_native_cli.yml
Closes #13332
@rigazilla Are there any actions that I have missed? We're only interested in running tests on these branches, other automations are not applicable.
> [#13332] Allow feature/* branches to be tested

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/geo/RemoteGeoLocalQueryTest.java
- documentation/src/main/asciidoc/topics/code_examples/GeoQueries.java
- documentation/src/main/asciidoc/topics/ref_query_spatial_search.adoc
- object-filter/src/main/antlr3/org/infinispan/objectfilter/impl/ql/parse/IckleLexer.g
- object-filter/src/main/antlr3/org/infinispan/objectfilter/impl/ql/parse/IckleParser.g
- object-filter/src/main/antlr3/org/infinispan/objectfilter/impl/ql/parse/QueryRenderer.g
- object-filter/src/main/antlr3/org/infinispan/objectfilter/impl/ql/parse/QueryResolver.g
- object-filter/src/main/java/org/infinispan/objectfilter/impl/ql/QueryRendererDelegate.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/SpatialWithinCircleExpr.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ExpressionBuilder.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/QueryRendererDelegateImpl.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/DistanceUnitHelper.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryMaker.java
- query/src/test/java/org/infinispan/query/geo/GeoLocalQueryTest.java
Closes #13204 
Draft - remaining tasks: => done!
1. ~~Support different unit measures in spatial predicates~~ done!
2. ~~Support different unit measures in spatial projections~~ done!
3. ~~Document unit measures in spatial queries~~ done!
4. ~~Improve the parsing of the units as soft keys~~ done!
> Support different unit measures in spatial queries (#13204)

- bin/gh/track_flaky_tests.sh
fixes #13383 
Old label `Flaky Test` must be changed when this is merged
> New flaky test label. Closes #13383

- build/configuration/pom.xml
> [15.0] Upgrades to Console 15.0.11.Final

- documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
- documentation/src/main/asciidoc/topics/proc_server_configuring_resp.adoc
- documentation/src/main/asciidoc/topics/proc_server_resp_differences.adoc
- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
**Backport:** https://github.com/infinispan/infinispan/pull/13198
I've added a few sections about our clustering capabilities and the differences in multi-key/transactional operations. Let me know if you think some additional subjects would be interesting to include.
Closes #13197.
> [15.0.x] Update Resp connector documentation

- documentation/src/main/asciidoc/stories/assembly_query_creating_ickle_queries.adoc
**Backport:** https://github.com/infinispan/infinispan/pull/13196
https://issues.redhat.com/browse/ISPN-16852
> [15.0.x] ISPN-16852: Vector Search is not supported feature

- quarkus/README.md
- quarkus/integration-tests/server/pom.xml
- quarkus/integration-tests/server/src/test/resources/configuration/log4j2.xml
> [#13338] Enable server logs when running quarkus integration-tests

- build/configuration/pom.xml
- core/src/main/java/org/infinispan/metrics/config/MicrometerMeterRegisterConfigurationBuilder.java
- core/src/main/java/org/infinispan/metrics/impl/MetricsRegistryImpl.java
- pom.xml
- quarkus/embedded/runtime/src/main/java/org/infinispan/quarkus/embedded/runtime/InfinispanEmbeddedProducer.java
- quarkus/embedded/runtime/src/main/java/org/infinispan/quarkus/embedded/runtime/InfinispanEmbeddedRuntimeConfig.java
- quarkus/embedded/runtime/src/main/java/org/infinispan/quarkus/embedded/runtime/SubstituteMicrometerMetrics.java
- quarkus/embedded/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- quarkus/integration-tests/embedded/src/main/resources/import.sql
- quarkus/server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java
- quarkus/server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/SubstituteIndexClasses.java
- server/core/pom.xml
- server/rest/pom.xml
- server/rest/src/main/java/org/infinispan/rest/resources/MetricsResource.java
- server/runtime/pom.xml
- server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
- server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodClientMetrics.java
- server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
- spring/spring-boot-3/pom.xml
> Updates to Quarkus 3.15 Closes #13223

- documentation/src/main/asciidoc/stories/assembly_cli_starting.adoc
- documentation/src/main/asciidoc/topics/proc_cli_connecting_container.adoc
**Backport:** https://github.com/infinispan/infinispan/pull/12931
Closes #13269
> [15.0.x] Explain how to connect to the server with the CLI running in a container

- server/testdriver/core/src/main/resources/testcontainers.properties
> [#13475] Upgrade to ryuk 0.11.0

- .github/workflows/on_build_do_publish_image.yml
- .github/workflows/on_build_do_test.yml
- .github/workflows/on_test_publish_surefire_report.yml
- .github/workflows/on_test_update_gh_flaky_test.yml
propagate run-name down the CI pipeline.
See #13449
> Propagate run-name, through whole CI pipeline. Closes #13449

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java
- core/src/main/resources/default-configs/default-jgroups-udp.xml
- core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
- core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
- core/src/test/java/org/infinispan/test/fwk/TransportFlags.java
- documentation/src/main/asciidoc/topics/ref_jgroups_ports.adoc
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiNodeTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodStatsClusterTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/event/AbstractHotRodClusterEventsTest.java
https://issues.redhat.com/browse/ISPN-16827
> [15.0] ISPN-16827 Set fixed ports in the UDP stack

- .github/workflows/on_build_do_publish_image.yml
- .github/workflows/on_build_do_test.yml
- .github/workflows/on_test_publish_surefire_report.yml
- .github/workflows/on_test_update_gh_flaky_test.yml
> [15.1.x][#13449] Propagate run-name, through whole CI pipeline.

- .githooks/commit-msg
- .githooks/configure-hooks
- .githooks/configure-hooks.bat
- .gitmessage
- Jenkinsfile-release
- build.xml
- pom.xml
> [#13477] Git commit message template and validation

- .github/dependabot.yml
> [#13499] Configure dependabot to update minor version

- build/configuration/pom.xml
- pom.xml
- server/core/pom.xml
- server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java
> [#13489] Add opentelemetry api incubator

- build/configuration/pom.xml
- pom.xml
- server/core/pom.xml
- server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java
**Backport:** https://github.com/infinispan/infinispan/pull/13514
Closes #13489
> [15.1.x] [#13489] Add opentelemetry api incubator

- .github/workflows/operator_upgrade.yaml
> [#13604] Only test server upgrades on CI with the latest Operator release

- .github/scripts/pr-find-issues.sh
- .github/scripts/pr-label-issues.sh
- .github/workflows/label.yml
> [#13515] Automatic release labels

- commons/all/src/main/java/org/infinispan/commons/api/CacheContainerAdmin.java
> [#13650] Remove deprecated CacheContainerAdmin#AdminFlag values

- .github/workflows/operator_upgrade.yaml
> [#13645] Ensure correct server version is associated with operand during testing

- .github/workflows/on_test_update_gh_flaky_test.yml
Fixes link to the workflow run in the flaky test issue comments
> [#13644] Fix run id in flaky test issue link

- .github/scripts/pr-find-issues.sh
- .github/scripts/pr-label-issues.sh
- .github/workflows/label.yml
**Backport:** https://github.com/infinispan/infinispan/pull/13518
Closes #13515
> [15.1.x] [#13515] Automatic release labels

- .github/workflows/operator_upgrade.yaml
> [14.0.x] Operand upgrade test fixes

- .github/workflows/operator_upgrade.yaml
> [15.0.x] Operand upgrade test fixes

- server/runtime/src/main/server/bin/common.sh
> [#13671] Silence native access warning on JDK 24+

- .github/workflows/supported_jdks.yaml
> [#13717] JDK Compatibility Tests not executed on 15.1.x branch

- .github/workflows/on_build_do_publish_image.yml
- .github/workflows/on_build_do_test.yml
- .github/workflows/on_propen_push_do_build.yml
- .github/workflows/operator_upgrade.yaml
- .github/workflows/pull_request_native_cli.yml
- .github/workflows/supported_jdks.yaml
Cancel concurrent job only on pull request
> [#13715] Do not cancel concurrent jobs on push

- cli/src/main/resources/help/benchmark.adoc
- documentation/src/main/asciidoc/stories/assembly_server_troubleshooting.adoc
- documentation/src/main/asciidoc/topics/proc_cli_benchmark.adoc
- documentation/src/main/asciidoc/topics/proc_cli_getting_server_reports.adoc
- documentation/src/main/asciidoc/topics/proc_cli_logging.adoc
* Describe the files contained in the report file;
* Include a section about parsing access log files;
* Include a section suggesting the benchmark command;
> Expand troubleshooting documentation

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/AuthenticationTest.java
> [#13734] Client topology installed during authentication can cause

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/HotRodClientTestingUtil.java
- tasks/scripting/pom.xml
- tasks/scripting/src/main/java/org/infinispan/scripting/ScriptingManager.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/PersistenceContextInitializer.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptMetadata.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptMetadataParser.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptWithMetadata.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingInterceptor.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingManagerImpl.java
- tasks/scripting/src/main/java/org/infinispan/scripting/logging/Log.java
- tasks/scripting/src/test/java/org/infinispan/scripting/ClusteredScriptingTest.java
- tasks/scripting/src/test/java/org/infinispan/scripting/ScriptMetadataTest.java
- tasks/scripting/src/test/java/org/infinispan/scripting/ScriptingTest.java
- tasks/scripting/src/test/java/org/infinispan/scripting/utils/ScriptingUtils.java
> Support custom properties in script metadata

- query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
Closes #13714
Backport of #13719
> [15.1] Limit reindexing concurrency pressure to 100

- query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
Closes #13714
Backport of #13719
> [15.0] Limit reindexing concurrency pressure to 100

- build/configuration/pom.xml
Reverts infinispan/infinispan#13576
> Revert "Bump version.log4j from 2.23.1 to 2.24.3"

- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationSerializer.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/RealmConfiguration.java
- server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationSerializerTest.java
- server/runtime/src/test/resources/configuration/versions/15.2.xml
> [#13752] Serialize server truststore realm config correctly

- client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java
- client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
- client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java
- client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
- client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CloseBeforeEnqueuingTest.java
> [15.1.x] [#13648] Retry operations submitted to closing channel

- .github/workflows/on_build_do_test.yml
- .github/workflows/on_test_publish_surefire_report.yml
Publish test report for DB test suite.
Bump ScaCap/action-surefire-report to 1.9.0 to exclude flaky test
> [#13768] Publish DBs test report

- javadoc/pom.xml
> [#13783] Set maven-javadoc-plugin output directory

- build/configuration/pom.xml
Closes #13775 update-quarkus-3.8.6
> [#13775][15.0] Upgrade Quarkus 3.8.6

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/ContainerDatabase.java
> [#13750] Log regex for database tests ignored on container startup

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
> [#13829] Don't include protocol stack in transport exceptions

- build/configuration/pom.xml
- server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
> [#13832] Update Server with PT6 Console

- server/core/src/main/java/org/infinispan/server/core/ServerManagement.java
- server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
> [#13814] Add token auth URL to Content-Security-Policy header

- documentation/src/main/asciidoc/topics/xml/jdbc_ping.xml
- documentation/src/main/asciidoc/topics/xml/server-transport-datasource.xml
> ISPN-16801: Follow-up to JDBC_PING doc updates for some fixes

- documentation/src/main/asciidoc/topics/xml/jdbc_ping.xml
- documentation/src/main/asciidoc/topics/xml/server-transport-datasource.xml
**Backport:** https://github.com/infinispan/infinispan/pull/13266
Closes #13885
> [15.0.x] ISPN-16801: Follow-up to JDBC_PING doc updates for some fixes

- server/core/src/main/java/org/infinispan/server/core/ServerManagement.java
- server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
**Backport:** https://github.com/infinispan/infinispan/pull/13816
Closes #13814
> [15.0.x] [#13814] Add token auth URL to Content-Security-Policy header

- server/core/src/main/java/org/infinispan/server/core/ServerManagement.java
- server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
**Backport:** https://github.com/infinispan/infinispan/pull/13816
Closes #13814
> [15.1.x] [#13814] Add token auth URL to Content-Security-Policy header

- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
> [#13872] Remap removeAsync future to boolean

- core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
- core/src/main/java/org/infinispan/configuration/parsing/ParseUtils.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java
- core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStoreConfigurationParser.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/JdbcStoreConfigurationParser.java
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
> [#13864] Correctly report removed/ignored attributes when parsing

- documentation/pom.xml
> [#13882] Documentation code highlighting

- core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java
> [#13864] Fix XmlFileParsingTest.testRemovedAttribute failure

- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
**Backport:** https://github.com/infinispan/infinispan/pull/13879
Closes #13872
> [15.1.x] [#13872] Remap removeAsync future to boolean

- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
**Backport:** https://github.com/infinispan/infinispan/pull/13879
Closes #13872
> [15.0.x] [#13872] Remap removeAsync future to boolean

- Jenkinsfile
> [#13935] Disable Jenkins Warnings for JavaDocs

- .github/workflows/sync_docs.yml
> [#13931] Sync docs to specific version on website

- .github/workflows/label.yml
Add label.yml to enable workflow on 15.0.x
> [#13914] [15.0.x] Enable label.yaml workflow

- .github/workflows/label.yml
Backport label.yml to enable workflow on 14.0.x
> [#13914] [14.0.x] Enable label.yaml workflow

- build/bom/pom.xml
- commons/all/pom.xml
- commons/all/src/main/java/org/infinispan/commons/jdkspecific/OffHeapMemory.java
- commons/all/src/main/java/org/infinispan/commons/jdkspecific/UnsafeHolder.java
- commons/all/src/main/java/org/infinispan/commons/jdkspecific/UnsafeOffHeapMemory.java
- commons/jdk22/pom.xml
- commons/jdk22/src/main/java/org/infinispan/commons/jdk22/UnsafeMemoryAddressOffHeapMemory.java
- commons/jdk22/src/main/java/org/infinispan/commons/jdk22/logging/Jdk22Log.java
- commons/jdk22/src/main/java/org/infinispan/commons/jdk22/logging/Jdk22LogFactory.java
- commons/jdk22/src/main/java/org/infinispan/commons/jdkspecific/OffHeapMemory.java
- commons/pom.xml
- commons/spi/src/main/java/org/infinispan/commons/spi/OffHeapMemory.java
- core/pom.xml
- core/src/main/java/org/infinispan/container/offheap/MemoryAddressHash.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactoryImpl.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapLruNode.java
- core/src/main/java/org/infinispan/container/offheap/UnpooledOffHeapMemoryAllocator.java
- pom.xml
https://issues.redhat.com/browse/ISPN-16775
Closes https://github.com/infinispan/infinispan/issues/13480
> Support Foreign Memory API

- documentation/src/main/asciidoc/topics/dependencies_maven/hibernate_v6.2.xml
- documentation/src/main/asciidoc/topics/ref_hibernate_second_level_cache.adoc
> [#13947] Document Hibernate 2LC 6.2+ artifacts

- client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_nix.adoc
- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_win.adoc
- documentation/src/main/asciidoc/topics/code_examples/HotRodExternal.java
- documentation/src/main/asciidoc/topics/code_examples/HotRodTLS.java
- documentation/src/main/asciidoc/topics/proc_cli_user_create.adoc
- documentation/src/main/asciidoc/topics/properties/hotrod-client-tls.properties
> [#13928] CLI user create examples should add group

- documentation/src/main/asciidoc/topics/upgrading.adoc
> [#13605] Fix FQN of IsolationLevel in upgrade docs

- server/runtime/src/main/java/org/infinispan/server/configuration/InterfaceConfigurationBuilder.java
- server/runtime/src/main/resources/schema/infinispan-server-15.2.xsd
- server/runtime/src/test/resources/configuration/versions/15.2.xml
- tools/src/main/resources/xsd/xsdoc.xslt
> [#13854] Fix several issues with the server configuration schema

- documentation/src/main/asciidoc/topics/dependencies_maven/hibernate_v6.2.xml
- documentation/src/main/asciidoc/topics/ref_hibernate_second_level_cache.adoc
**Backport:** https://github.com/infinispan/infinispan/pull/13949
Closes #13947
> [15.1.x] [#13947] Document Hibernate 2LC 6.2+ artifacts

- documentation/src/main/asciidoc/topics/dependencies_maven/hibernate_v6.2.xml
- documentation/src/main/asciidoc/topics/ref_hibernate_second_level_cache.adoc
**Backport:** https://github.com/infinispan/infinispan/pull/13949
Closes #13947
> [15.0.x] [#13947] Document Hibernate 2LC 6.2+ artifacts

- client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_nix.adoc
- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_win.adoc
- documentation/src/main/asciidoc/topics/code_examples/HotRodExternal.java
- documentation/src/main/asciidoc/topics/code_examples/HotRodTLS.java
- documentation/src/main/asciidoc/topics/proc_cli_user_create.adoc
- documentation/src/main/asciidoc/topics/properties/hotrod-client-tls.properties
**Backport:** https://github.com/infinispan/infinispan/pull/13929
Closes #13928
> [15.1.x] [#13928] CLI user create examples should add group

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java
- server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONTYPE.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonTypeFunction.java
- server/resp/src/main/java/org/infinispan/server/resp/serialization/ResponseWriter.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
> [#13474] JSON.TYPE command

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java
- server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONDEL.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/InfinispanJacksonJsonNodeProvider.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JSONUtil.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonDelFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
Implementation for RESP json.del command.
Fixes #13428
> RESP json.del command

- quarkus/cli/pom.xml
- quarkus/integration-tests/cli/pom.xml
- quarkus/integration-tests/cli/src/test/java/org/infinispan/quarkus/server/NativeCliIT.java
> [#13788] Don't install native cli into local repo

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONARRLEN.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONLEN.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONOBJLEN.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONSTRLEN.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONTYPE.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonLenFunction.java
- server/resp/src/main/java/org/infinispan/server/resp/json/LenType.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
> [#13422] JSON.ARRLEN command

- server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java
- server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONTOGGLE.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonAppendFunction.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonDelFunction.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonToggleFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
> [#13473] JSON.TOGGLE command

- commons/all/src/main/java/org/infinispan/commons/marshall/AbstractMarshaller.java
> [#14047] Utilise InputStream#transferTo in AbstractMarshaller#objectFromInputStream

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java
- server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONOBJKEYS.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonObjkeysFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
RESP json.objkeys implementation
Fixes #13468
> [#13468] RESP json.objkeys command

- core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java
- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
Closes #14028
This is my attempt to resolve this thread pinning. 
It would be great to have that eventually in 15.0.x - thanks!
> Avoid thread pinning in ClusterCacheStatus

- core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java
- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
**Backport:** https://github.com/infinispan/infinispan/pull/14029
Closes #14028
This is my attempt to resolve this thread pinning. 
It would be great to have that eventually in 15.0.x - thanks!
> [15.0.x] Avoid thread pinning in ClusterCacheStatus

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java
- server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONAPPEND.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONARRAPPEND.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONCommandArgumentReader.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONDEL.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONLEN.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONNUMINCRBY.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONOBJKEYS.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONSTRAPPEND.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONTOGGLE.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONTYPE.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JSONUtil.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonNumIncrByFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
> [#13466] JSON.NUMINCRBY command

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java
- server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONARRINDEX.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonArrindexFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
RESP json.arrindex implementation
fixes #13420
> [#13420] RESP json.arrindex command

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/pressure/LargePutAllPressureTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/pressure/TransactionalLargePutAllPressureTest.java
- commons/all/src/main/java/org/infinispan/commons/util/concurrent/CompletionStages.java
- query/src/main/java/org/infinispan/query/backend/TxQueryInterceptor.java
https://issues.redhat.com/browse/ISPN-16635
Backport of https://github.com/infinispan/infinispan/pull/12906
> [15.0] ISPN-16635 Limit concurrency for indexing trx to 100

- core/src/main/java/org/infinispan/commands/topology/CacheLeaveCommand.java
- core/src/main/java/org/infinispan/commands/topology/RebalancePhaseConfirmCommand.java
- core/src/main/java/org/infinispan/topology/ClusterTopologyManager.java
- core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
- core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
- core/src/test/java/org/infinispan/distribution/rehash/BaseTxStateTransferOverwriteTest.java
- core/src/test/java/org/infinispan/distribution/rehash/NonTxStateTransferOverwritingValue2Test.java
- core/src/test/java/org/infinispan/distribution/rehash/StateTransferOverwritingValueTest.java
- core/src/test/java/org/infinispan/topology/ClusterTopologyManagerImplTest.java
> [#14086] Remove unused viewId from commands

- query/src/main/java/org/infinispan/query/impl/InfinispanQueryStatisticsInfo.java
> [#14113] Add descriptions to InfinispanQueryStatisticsInfo

- documentation/pom.xml
- documentation/src/main/asciidoc/stories/assembly_upgrading.adoc
> [#13284] Fix upgrading guide + [#13882] Fix highlighting

- server/runtime/src/main/server/server/conf/infinispan-memcached.xml
- server/runtime/src/main/server/server/conf/infinispan-resp.xml
> [#14100] Make mimic server configs local

- build/configuration/pom.xml
- graalvm/client-hotrod/pom.xml
- graalvm/core/pom.xml
- pom.xml
Run just to see if CI gets the same thing or not.
Closes #14172
> Update Quarkus to 3.15.3

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java
- server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONARRAPPEND.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONARRINSERT.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonArrinsertFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
RESP json.arrinsert command
closes #13421
> [#13421] RESP json.arrinsert command

- documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_jgroups_asym_encrypt.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_jgroups_sym_encrypt.adoc
Done for issue: https://github.com/infinispan/infinispan/issues/14148
> [#14148] Update JGroups Manual and Schema links

- documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_jgroups_asym_encrypt.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_jgroups_sym_encrypt.adoc
Done for https://github.com/infinispan/infinispan/issues/14148
> [#14148] Update JGroups Manual and Schema links #14179

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InvalidatedNearRemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCacheService.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedNearCacheTest.java
> [#14141] Near cache config doesn't work with pattern cache name builder

- server/tests/src/test/java/org/infinispan/server/functional/overview/OverviewReportIT.java
> [#14181] Make Insights report IT container based

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java
- server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONCLEAR.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonClearFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
> [#13425] JSON.CLEAR command

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodServerStartStopTest.java
> [#14031] Check connection future immediately for event loop failure

- documentation/src/main/asciidoc/topics/contributing/tests.adoc
- pom.xml
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanGenericContainer.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
- server/testdriver/junit4/pom.xml
- server/testdriver/junit5/pom.xml
- server/tests/pom.xml
**Backport:** https://github.com/infinispan/infinispan/pull/13978
> [15.1.x] [#13977] Fix the code coverage impl to work with integration tests

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java
- server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONARRPOP.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonArrpopFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
RESP json.arrpop command
closes #13423
> [#13423] RESP json.arrpop command

- core/src/main/java/org/infinispan/commands/CommandsFactory.java
- core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
- core/src/main/java/org/infinispan/xsite/BackupReceiver.java
- core/src/main/java/org/infinispan/xsite/ClusteredCacheBackupReceiver.java
- core/src/main/java/org/infinispan/xsite/commands/remote/XSiteStatePushRequest.java
- core/src/main/java/org/infinispan/xsite/statetransfer/SyncProviderState.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateConsumer.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateConsumerImpl.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStatePushCommand.java
- core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
- core/src/test/java/org/infinispan/xsite/BackupReceiverDelegator.java
- core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/failures/RetryMechanismTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/failures/SiteConsumerTopologyChangeTest.java
> [#14109] Convert XSite state commands to use List instead of array for XSiteState

- documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc
- documentation/src/main/asciidoc/topics/ref_query_ickle_syntax.adoc
> [#14218] Document parent nested join

- .github/workflows/on_build_do_test.yml
> [#14229] Checkout only .github for test + enable hibernate-matrix

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONMSET.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
RESP json.mset command
closes #13465
> [#13465] RESP json.mset command

- .github/workflows/on_build_do_test.yml
**Backport:** https://github.com/infinispan/infinispan/pull/14230
closes #14229
> [15.1.x] [#14229] Checkout only .github for test + enable hibernate-matrix

- server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java
- server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONMERGE.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONMSET.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JSONUtil.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonMergeFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
RESP json.merge commmand
closes #13430
> [#13430] RESP json.merge command

- server/resp/src/main/java/org/infinispan/server/resp/json/JsonToggleFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
> [#13473] JSON.TOGGLE root fix

- query-core/src/main/java/org/infinispan/query/core/impl/QueryCache.java
>  [#14304] Avoid locking with query cache 

- documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONMGET.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
RESP json.mget implementation
closes #13464
> [#13464] RESP json.mget command

- server/resp/src/main/java/org/infinispan/server/resp/ExternalizerIds.java
- server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONRESP.java
- server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonRespFunction.java
- server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
json.resp command
closes #13470
> [#13470] RESP json.resp command

- query-core/src/main/java/org/infinispan/query/core/impl/QueryCache.java
**Backport:** https://github.com/infinispan/infinispan/pull/14320
Closes #14304
> [15.0.x]  [#14304] Avoid locking with query cache 

- bin/gh/track_flaky_tests.sh
> [#14270] Flaky test comment, limit gh search to current repo

- bin/gh/track_flaky_tests.sh
**Backport:** https://github.com/infinispan/infinispan/pull/14280
fixes #14270
> [15.1.x] [#14270] Flaky test comment, limit gh search to current repo

- core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadPoolExecutorFactory.java
> [#14334] Replace non-blocking executor with virtual thread executor

- spring/spring6/spring6-common/src/main/resources/schema/infinispan-spring-15.2.xsd
- spring/spring6/spring6-embedded/src/test/resources/org/infinispan/spring/embedded/config/CacheLoaderNotFoundTest-context.xml
- spring/spring6/spring6-embedded/src/test/resources/org/infinispan/spring/embedded/config/InfinispanContainerCacheManagerDefinitionTest-context.xml
- spring/spring6/spring6-embedded/src/test/resources/org/infinispan/spring/embedded/config/InfinispanEmbeddedCacheManagerDefinitionTest-context.xml
- spring/spring6/spring6-embedded/src/test/resources/org/infinispan/spring/embedded/config/NonTransactionalCacheTest-context.xml
- spring/spring6/spring6-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleEmbeddedCacheTestConfig.xml
- spring/spring6/spring6-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleTransactionIntegrationTestConfig.xml
- spring/spring6/spring6-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleXmlConfigurationTestConfig.xml
- spring/spring6/spring6-remote/src/test/resources/org/infinispan/spring/remote/config/InfinispanRemoteCacheManagerDefinitionTest-context.xml
> [#14345] Fix spring schema namespace

- core/src/main/java/org/infinispan/metrics/impl/MetricsComponentFactory.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsMetricsManagerImpl.java
Closes https://github.com/infinispan/infinispan/issues/14347
> [#14347] JGroups metrics ignore the configured prefix

- query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
- query/src/main/java/org/infinispan/search/mapper/scope/SearchWorkspace.java
- query/src/main/java/org/infinispan/search/mapper/scope/impl/SearchWorkspaceImpl.java
> [#14350] Make query clear non blocking

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/async/DefaultAsyncExecutorFactory.java
* Use the `DefaultThreadFactory` from Netty. This changes how the thread name is created.
Closes #14366.
> [#14366] Use Netty default thread factory

- build/configuration/pom.xml
> [#14381] Operator Upgrade Tests fail due to incorrect TCP sock_conn_timeout

- server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
**Backport:** https://github.com/infinispan/infinispan/pull/14394
Closes #14393
> [15.0.x] [#14393] Fix RestMetricsResourceIT.testDetailedKeyMetrics2

- server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
**Backport:** https://github.com/infinispan/infinispan/pull/14394
Closes #14393
> [15.1.x] [#14393] Fix RestMetricsResourceIT.testDetailedKeyMetrics2

- query-core/src/main/java/org/infinispan/query/core/impl/LifecycleManager.java
- query-core/src/main/java/org/infinispan/query/core/impl/QueryCache.java
- query/src/test/java/org/infinispan/query/impl/QueryCacheEmbeddedTest.java
Closes #14304 
Further fix I left to add yesterday...
> [#14304] Simplify query cache

- documentation/src/main/asciidoc/topics/contributing/tests.adoc
- pom.xml
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanGenericContainer.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
- server/testdriver/junit4/pom.xml
- server/testdriver/junit5/pom.xml
- server/tests/pom.xml
**Backport:** https://github.com/infinispan/infinispan/pull/13978
> [15.0.x] [#13977] Fix the code coverage impl to work with integration tests

- server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
- server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
> [#14293] Let InfinispanServerExtension auto close the clients

- query-core/src/main/java/org/infinispan/query/core/impl/LifecycleManager.java
- query-core/src/main/java/org/infinispan/query/core/impl/QueryCache.java
- query/src/test/java/org/infinispan/query/impl/QueryCacheEmbeddedTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/14343
Closes #14304 
Further fix I left to add yesterday...
> [15.0.x] [#14304] Simplify query cache

- server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
- server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
**Backport:** https://github.com/infinispan/infinispan/pull/14294
Closes #14293
> [15.0.x] [#14293] Let InfinispanServerExtension auto close the clients

- core/src/main/java/org/infinispan/commands/CommandsFactory.java
- core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
- core/src/main/java/org/infinispan/commands/RemoteCommandsFactory.java
- core/src/main/java/org/infinispan/commands/irac/IracPrimaryPendingKeyCheckCommand.java
- core/src/main/java/org/infinispan/commands/irac/IracStateResponseCommand.java
- core/src/main/java/org/infinispan/container/versioning/irac/DefaultIracTombstoneManager.java
- core/src/main/java/org/infinispan/marshall/exts/CacheRpcCommandExternalizer.java
- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/main/java/org/infinispan/xsite/irac/IracManager.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyChangedState.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyInfo.java
- core/src/main/java/org/infinispan/xsite/irac/NoOpIracManager.java
- core/src/test/java/org/infinispan/jmx/XSiteMBeanTest.java
- core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
- core/src/test/java/org/infinispan/xsite/AbstractMultipleSitesTest.java
- core/src/test/java/org/infinispan/xsite/irac/ControlledIracManager.java
- core/src/test/java/org/infinispan/xsite/irac/Irac3SitesConflictTest.java
- core/src/test/java/org/infinispan/xsite/irac/Irac3SitesExponentialBackOffTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracAlwaysRemoveConflictTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracCustomConflictTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracExponentialBackOffTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracTombstoneUnitTest.java
- core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java
- core/src/test/java/org/infinispan/xsite/irac/persistence/BaseIracPersistenceTest.java
- core/src/test/java/org/infinispan/xsite/irac/statetransfer/IracStateTransferTest.java
> [#14360] Remove stale data from IracManager backup owners

- core/src/test/java/org/infinispan/jmx/XSiteMBeanTest.java
- core/src/test/java/org/infinispan/xsite/irac/Irac3SitesConflictTest.java
- core/src/test/java/org/infinispan/xsite/irac/Irac3SitesExponentialBackOffTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracAlwaysRemoveConflictTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracCustomConflictTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracExponentialBackOffTest.java
- core/src/test/java/org/infinispan/xsite/irac/persistence/BaseIracPersistenceTest.java
- core/src/test/java/org/infinispan/xsite/irac/statetransfer/IracStateTransferTest.java
> [15.0] [#14432] Cleanup resources after cross-site tests

- core/src/test/java/org/infinispan/xsite/AsyncBackupTest.java
Closes https://github.com/infinispan/infinispan/issues/14412 
Closes https://github.com/infinispan/infinispan/issues/13415
Closes https://github.com/infinispan/infinispan/issues/13359
Closes https://github.com/infinispan/infinispan/issues/13354
Closes https://github.com/infinispan/infinispan/issues/13347
> [#14412] Fix flaky test AsyncBackupTest

- server/core/src/main/java/org/infinispan/server/core/factories/NettyEventLoopFactory.java
- server/core/src/main/java/org/infinispan/server/core/logging/Log.java
* Wrap the default threads in Netty's thread factory to take advantage of optimizations.
Closes #14425.
> [#14425] Use Netty threads in server

- core/src/test/java/org/infinispan/jmx/XSiteMBeanTest.java
- core/src/test/java/org/infinispan/xsite/irac/Irac3SitesConflictTest.java
- core/src/test/java/org/infinispan/xsite/irac/Irac3SitesExponentialBackOffTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracAlwaysRemoveConflictTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracCustomConflictTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracExponentialBackOffTest.java
- core/src/test/java/org/infinispan/xsite/irac/persistence/BaseIracPersistenceTest.java
- core/src/test/java/org/infinispan/xsite/irac/statetransfer/IracStateTransferTest.java
> [15.1] [#14432] Cleanup resources after cross-site tests

- query-core/src/main/java/org/infinispan/query/core/impl/QueryCache.java
> [#14441] Reintroduce cache instance variable

- commons/all/src/main/java/org/infinispan/commons/io/FileWatcher.java
Closes #13351
Some details: the `SslContextFactoryTest.testSslContextFactoryWatch` method was occasionally failing because it found an empty/incomplete certificate file (while it was being recreated). Unfortunately the `IOException` was rethrown, causing the watcher thread to terminate
> [#13351] Don't abort FileWatcher.run() on errors

- server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/LOAD.java
- server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaTaskEngine.java
- server/tests/src/test/java/org/infinispan/server/functional/resp/RespScriptTest.java
> [#14459] Fix RESP script load authorization

- pom.xml
Fixes #13729
Fixes #14002
Fixes #14483 
Fixes #14484
> [#13729] Out of space in CodeCache for adapters

- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
> [#14486] Handle reflection exceptions in ThreadLeakChecker

- core/src/main/java/org/infinispan/configuration/parsing/ParserRegistry.java
- server/runtime/src/main/resources/infinispan-server-templates.xml
- server/tests/src/test/resources/configuration/security/keycloak-oauth2.xml
> [#14516] Use unsigned version comparison in the parser registry

- client/rest-client/src/main/java/org/infinispan/client/rest/RestClusterClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestClusterClientJDK.java
- documentation/src/main/asciidoc/topics/json/rest_cluster_members_response.json
- documentation/src/main/asciidoc/topics/ref_rest_clusters.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/ClusterResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/ClusterResourceTest.java
> [#13894] Cluster membership endpoint

- .github/workflows/on_build_do_test.yml
> [#14496] GH-CI JAVA_HOME set to use openjdk

- server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MemoryEntrySizeUtils.java
- server/resp/src/main/java/org/infinispan/server/resp/json/JsonBucket.java
special handling for JsonBucket memory sizeof.
closes #14506
> [#14506] Ad-hoc JsonBucket mem size

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
> [#14549] Fix the HotRodCompCacheOperationsIT test failing in GHA\n

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
- commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java
- commons/all/src/test/java/org/infinispan/commons/util/TypedPropertiesTest.java
> [#14510] Properties can containt Integer values

- .github/workflows/on_build_do_test.yml
> [#14525] Fix repository in wrkflw link

- .github/workflows/on_build_do_test.yml
- commons-test/src/main/java/org/infinispan/commons/test/skip/SkipTestNG.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiHomedAddressTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleClusteredNonLoopbackTest.java
> [#14556] Workaround network interface test failures on GitHub Actions

- cli/src/main/java/org/infinispan/cli/commands/rest/Create.java
- cli/src/main/java/org/infinispan/cli/logging/Messages.java
- cli/src/main/resources/help/create.adoc
- client/rest-client/src/main/java/org/infinispan/client/rest/RestEntity.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationReader.java
- documentation/src/main/asciidoc/topics/proc_creating_caches_cli.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
> [#14546] CLI create cache with configuration argument

- .github/workflows/on_build_do_test.yml
- .github/workflows/on_test_publish_surefire_report.yml
closes #14571 
also fix check run status in case of mvn verify error
> [#14571] Renew token after mvn verify

- server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/SHARDS.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/connection/COMMAND.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/connection/HELLO.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MEMORY.java
- server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MODULE.java
- server/resp/src/main/java/org/infinispan/server/resp/serialization/Resp3Type.java
- server/resp/src/test/java/org/infinispan/server/resp/RespServerTest.java
> [#14559] Use bulk strings in RESP HELLO response

- core/src/main/java/org/infinispan/remoting/transport/AbstractDelegatingTransport.java
- core/src/main/java/org/infinispan/remoting/transport/Transport.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/test/java/org/infinispan/remoting/transport/MockTransport.java
- core/src/test/java/org/infinispan/util/ControlledTransport.java
> [#14859] Remove deprecated methods from Transport

- server/core/src/main/java/org/infinispan/server/core/ServerCoreBlockHoundIntegration.java
**Backport:** https://github.com/infinispan/infinispan/pull/14601
Fixes #14600
> [15.0.x] [#14600] Test can fail on shutdown due to netty thread blocking

- client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
- core/src/main/java/org/infinispan/configuration/cache/ExpirationConfigurationBuilder.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/configuration/ConfigurationUnitTest.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java
- core/src/test/java/org/infinispan/container/offheap/OffHeapSingleNodeExpirationEvictionTest.java
- core/src/test/resources/configs/all/10.0.xml
- core/src/test/resources/configs/all/10.1.xml
- core/src/test/resources/configs/all/11.0.xml
- core/src/test/resources/configs/all/12.0.xml
- core/src/test/resources/configs/all/12.1.xml
- core/src/test/resources/configs/all/13.0.xml
- core/src/test/resources/configs/all/14.0.xml
- core/src/test/resources/configs/all/15.0.xml
- core/src/test/resources/configs/all/15.1.xml
- core/src/test/resources/configs/all/15.2.xml
- core/src/test/resources/configs/all/16.0.xml
- core/src/test/resources/configs/includes/include-expiration.xml
- documentation/src/main/asciidoc/topics/changes.adoc
- documentation/src/main/asciidoc/topics/con_expiration_maxidle.adoc
- jcache/embedded/src/test/java/org/infinispan/jcache/JCacheConfigurationTest.java
- jcache/embedded/src/test/resources/infinispan_uri.xml
- server/rest/src/test/java/org/infinispan/rest/expiration/DistributedQueryExpiredEntitiesTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/BaseCacheResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
> [#14527] Max idle should not be greater than or equal to lifespan

- .github/workflows/on_build_do_publish_image.yml
> [#14648] Remove gh- prefix tag from infinispan-test/server image

- server/tests/src/test/java/org/infinispan/server/persistence/JGroupsJdbcPing2IT.java
* Only fallback to DriverManager if needed.
Closes #13908
> [#13908] Manually load JDBC driver

- client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/event/RemoteContinuousQueryLeavingRemoteCacheManagerTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/RemoteContinuousQueryLeavingRemoteCacheManagerTest.java
* Use auto-closeable to always close the extra remote cache manager.
Closes #14655
> [#14655] Close cache manager to avoid thread leak

- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsExtractorMojo.java
- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsResolver.java
- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/InfinispanDefaultsResolver.java
- persistence/jdbc-common/src/main/resources/schema/infinispan-cachestore-jdbc-common-config-16.0.xsd
- persistence/jdbc/src/main/resources/schema/infinispan-cachestore-jdbc-config-16.0.xsd
- persistence/remote/src/main/resources/schema/infinispan-cachestore-remote-config-16.0.xsd
- persistence/rocksdb/src/main/resources/schema/infinispan-cachestore-rocksdb-config-16.0.xsd
- server/runtime/src/main/resources/schema/infinispan-server-16.0.xsd
> [#14674] Fix unreplaced XSD placeholders

- .github/workflows/backport.yaml
> [#14659] Adding backport main->15.2.x

- build/configuration/pom.xml
- build/infinispan-defaults-maven-plugin/pom.xml
- core/pom.xml
- pom.xml
- quarkus/pom.xml
Includes a maven enforcer plugin rule to ban duplicate classes so this won't happen in the future
Closes #14654
> [#14654] Remove commons-spi dependency from core

- server/tests/src/test/java/org/infinispan/server/persistence/JGroupsJdbcPing2IT.java
* Only fallback to DriverManager if needed.
Backport of #14642.
> [15.0.x] [#13908] Manually load JDBC driver

- server/tests/src/test/java/org/infinispan/server/persistence/JGroupsJdbcPing2IT.java
* Only fallback to DriverManager if needed.
Backport of #14642.
> [15.2.x] [#13908] Manually load JDBC driver

- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsExtractorMojo.java
- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsResolver.java
- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/InfinispanDefaultsResolver.java
- persistence/jdbc-common/src/main/resources/schema/infinispan-cachestore-jdbc-common-config-15.2.xsd
- persistence/jdbc/src/main/resources/schema/infinispan-cachestore-jdbc-config-15.2.xsd
- persistence/remote/src/main/resources/schema/infinispan-cachestore-remote-config-15.2.xsd
- persistence/rocksdb/src/main/resources/schema/infinispan-cachestore-rocksdb-config-15.2.xsd
- server/runtime/src/main/resources/schema/infinispan-server-15.2.xsd
> [15.2] [#14674] Fix unreplaced XSD placeholders

- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsExtractorMojo.java
- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsResolver.java
- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/InfinispanDefaultsResolver.java
- persistence/jdbc-common/src/main/resources/schema/infinispan-cachestore-jdbc-common-config-15.0.xsd
- persistence/jdbc/src/main/resources/schema/infinispan-cachestore-jdbc-config-15.0.xsd
- persistence/remote/src/main/resources/schema/infinispan-cachestore-remote-config-15.0.xsd
- persistence/rocksdb/src/main/resources/schema/infinispan-cachestore-rocksdb-config-15.0.xsd
- server/runtime/src/main/resources/schema/infinispan-server-15.0.xsd
> [15.0] [#14674] Fix unreplaced XSD placeholders

- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsExtractorMojo.java
- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsResolver.java
- build/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/InfinispanDefaultsResolver.java
- persistence/jdbc-common/src/main/resources/schema/infinispan-cachestore-jdbc-common-config-14.0.xsd
- persistence/jdbc/src/main/resources/schema/infinispan-cachestore-jdbc-config-14.0.xsd
- persistence/remote/src/main/resources/schema/infinispan-cachestore-remote-config-14.0.xsd
- persistence/rocksdb/src/main/resources/schema/infinispan-cachestore-rocksdb-config-14.0.xsd
- server/runtime/src/main/resources/schema/infinispan-server-14.0.xsd
> [14.0] [#14674] Fix unreplaced XSD placeholders

- server/insights/src/main/java/org/infinispan/server/insights/InfinispanInsightsConfiguration.java
> [#14662] Return fixed id in case of shutdown

- server/insights/src/main/java/org/infinispan/server/insights/InfinispanInsightsConfiguration.java
**Backport:** https://github.com/infinispan/infinispan/pull/14673
Closes #14662
> [15.0.x] [#14662] Return fixed id in case of shutdown

- .github/workflows/operator_upgrade.yaml
> [#14712] Disable op upgrade test on main

- core/src/main/resources/default-configs/default-jgroups-azure.xml
- core/src/main/resources/default-configs/default-jgroups-ec2.xml
- core/src/main/resources/default-configs/default-jgroups-google.xml
- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/main/resources/default-configs/default-jgroups-tunnel.xml
- core/src/main/resources/default-configs/default-jgroups-udp.xml
> [#14725] Add port_range back to the default stacks

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java
- server/tests/src/test/java/org/infinispan/server/rollingupgrade/DefaultRollingUpgradeTest.java
The Lettuce client supports a clustered version that updates the topology on demand.
The Memcached client does accept multiple servers to establish a connection, but I don't see a way to update the topology dynamically. To workaround that, I am doing something similar to the REST client and connecting to a specific server.
> [#14562] Memcached and RESP client for rolling upgrades

- server/insights/src/main/java/org/infinispan/server/insights/InfinispanInsightsConfiguration.java
**Backport:** https://github.com/infinispan/infinispan/pull/14673
Closes #14662
> [15.2.x] [#14662] Return fixed id in case of shutdown

- build/configuration/pom.xml
> [#14753]  upgrade graalvm to 24.0.1

- core/src/main/java/org/infinispan/security/mappers/CommonNameRoleMapper.java
- core/src/test/java/org/infinispan/security/RoleMapperTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/14760
Closes #14760
> [15.0.x] [#14759] CommonNameRoleMapper support for bare names

- build/configuration/pom.xml
**Backport:** https://github.com/infinispan/infinispan/pull/14754
Closes #14753
> [15.0.x] [#14753]  upgrade graalvm to 24.0.1

- core/src/main/java/org/infinispan/distribution/ch/ConsistentHash.java
- core/src/main/java/org/infinispan/distribution/ch/impl/AbstractConsistentHash.java
- core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHash.java
- core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHash.java
- core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
- core/src/test/java/org/infinispan/distribution/ch/BaseCHPersistenceTest.java
> [#14785] Add mapper to ConsistentHash.toScopedState method

- documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
> [#14815] RESP documentation page fix

- core/src/main/java/org/infinispan/remoting/transport/AbstractDelegatingTransport.java
- core/src/main/java/org/infinispan/remoting/transport/Transport.java
- core/src/main/java/org/infinispan/remoting/transport/impl/FilterMapResponseCollector.java
- core/src/main/java/org/infinispan/remoting/transport/impl/MapResponseCollector.java
- core/src/main/java/org/infinispan/remoting/transport/impl/SingletonMapResponseCollector.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/test/java/org/infinispan/remoting/transport/MockTransport.java
- core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsTransportTest.java
- core/src/test/java/org/infinispan/util/ControlledTransport.java
> [#14832] Remove unused parameter in Transport

- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/persistence/sifs/Index.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
> [#14820] Size method with a local cache and store is not optimized

- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/persistence/sifs/Index.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
**Backport:** https://github.com/infinispan/infinispan/pull/14823
Fixes #14820
> [15.0.x] [#14820] Size method with a local cache and store is not optimized

- client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestServerClientJDK.java
- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/HealthCheckResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/HealthCheckResourceTest.java
* Live always returns OK.
* Ready verify if at least one cache is not failed.
Closes #14802
> [#14802] Add resource for health check

- client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestServerClientJDK.java
- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/resources/HealthCheckResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/HealthCheckResourceTest.java
> [15.2.x] Add resource for health check

- integrationtests/server-integration/pom.xml
- integrationtests/server-integration/server-integration-commons/pom.xml
- integrationtests/server-integration/third-party-server/pom.xml
> [15.0.x] [#14863] infinispan-server-integration tests missing file cause GH Action CI to fail

- core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java
Close #14709 
Virtual thread accesses the index file inside a synchronized block. It pins the virtual thread to the carrier thread.
> [15.2] [#14709] Replace synchronized block with lock in SoftIndexFileStore

- core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java
Close #14709
Virtual thread accesses the index file inside a synchronized block. It pins the virtual thread to the carrier thread.
> [15.0] [#14709] Replace synchronized block with lock in SoftIndexFileStore

- client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestServerClientJDK.java
- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/resources/HealthCheckResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/HealthCheckResourceTest.java
> [15.0.x] Add resource for health check

- .github/workflows/on_build_do_test.yml
- commons-test/src/main/java/org/infinispan/commons/test/skip/SkipTestNG.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiHomedAddressTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleClusteredNonLoopbackTest.java
> [15.2] [#14556] Workaround network interface test failures on GitHub Actions

- pom.xml
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanGenericContainer.java
- server/tests/pom.xml
> [15.0.x] [#14132] Report jacoco coverage using GitHub actions

- build/configuration/pom.xml
**Backport:** https://github.com/infinispan/infinispan/pull/14889
Closes #14888
> [15.2.x] [#14888] Wait for Maven Central publish completion

- core/src/main/java/org/infinispan/util/logging/Log.java
> [#14922] Log method commandNotYeySupportedByAllClusterMembers is missing an id attribute

- .github/scripts/pr-label-issues.sh
- .github/workflows/label.yml
> [#14790] Add correct label on closed issue for main

- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/test/java/org/infinispan/xsite/irac/IracMaxIdleTest.java
- core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java
**Backport:** https://github.com/infinispan/infinispan/pull/14880
Closes #14865
> [15.2.x] [#14865] NullPointerException while expiring entry with cross-site

- core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
**Backport:** https://github.com/infinispan/infinispan/pull/15004
* Correctly notifies the tracker about completed work.
Relates to #14804
> [15.0.x] [#14804] Fix state transfer progress tracking

- core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
**Backport:** https://github.com/infinispan/infinispan/pull/15004
* Correctly notifies the tracker about completed work.
Relates to #14804
> [15.2.x] [#14804] Fix state transfer progress tracking

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/nested/ParentJoinNestedRemoteTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/vector/VectorSearchRemoteTest.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java
- query/src/test/java/org/infinispan/query/model/Item.java
- query/src/test/java/org/infinispan/query/model/Metadata.java
- query/src/test/java/org/infinispan/query/nested/ParentJoinNestedTest.java
- query/src/test/java/org/infinispan/query/projection/ScoreProjectionBroadcastTest.java
- query/src/test/java/org/infinispan/query/vector/VectorSearchBroadcastTest.java
- query/src/test/java/org/infinispan/query/vector/VectorSearchTest.java
- query/src/test/java/org/infinispan/query/vector/VectorSearchWithPreFilteringTest.java
- server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheQueries.java
- test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/KeywordVector.java
- test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/Metadata.java
- test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/TestDomainSCI.java
> [#14564] Query bug (hotrod) - projection and filtering in nested lists not working 

- core/src/test/java/org/infinispan/partitionhandling/PreferConsistencyRestartTest.java
* Need to wait until cluster topology manager moves to coordinator
Closes #14621
Closes #14635
Closes #14652
> [#14621] Fix PreferConsistencyRestartTest

- client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/query/vector/VectorSearchRemoteTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/nested/ParentJoinNestedRemoteTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/vector/VectorSearchRemoteTest.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java
- query/src/test/java/org/infinispan/query/model/Item.java
- query/src/test/java/org/infinispan/query/model/Metadata.java
- query/src/test/java/org/infinispan/query/nested/ParentJoinNestedTest.java
- query/src/test/java/org/infinispan/query/projection/ScoreProjectionBroadcastTest.java
- query/src/test/java/org/infinispan/query/vector/VectorSearchBroadcastTest.java
- query/src/test/java/org/infinispan/query/vector/VectorSearchTest.java
- query/src/test/java/org/infinispan/query/vector/VectorSearchWithPreFilteringTest.java
- server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheQueries.java
- test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/KeywordVector.java
- test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/Metadata.java
- test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/TestDomainSCI.java
**Backport:** https://github.com/infinispan/infinispan/pull/14602
Closes #14564
> [15.2.x] [#14564] Query bug (hotrod) - projection and filtering in nested lists not working 

- .github/workflows/needs_rebase.yaml
> [#15046] Allow needs_rebase to add/rm labels on PR

- .github/workflows/needs_rebase.yaml
**Backport:** https://github.com/infinispan/infinispan/pull/15047
closes #15046
> [14.0.x] [#15046] Allow needs_rebase to add/rm labels on PR

- .github/workflows/needs_rebase.yaml
**Backport:** https://github.com/infinispan/infinispan/pull/15047
closes #15046
> [15.0.x] [#15046] Allow needs_rebase to add/rm labels on PR

- .github/workflows/needs_rebase.yaml
**Backport:** https://github.com/infinispan/infinispan/pull/15047
closes #15046
> [15.2.x] [#15046] Allow needs_rebase to add/rm labels on PR

- .github/workflows/on_test_publish_surefire_report.yml
> [#15052] Reduced test number threshold to 33500

- core/src/test/java/org/infinispan/partitionhandling/PreferConsistencyRestartTest.java
Missed these checks.
Closes #14621
Closes #14635
> [#14621] Flaky PreferConsistencyRestartTest fixes

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
> [#15126] Fixes mapping bug in Cache Full detail

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
**Backport:** https://github.com/infinispan/infinispan/pull/15127
Fixes #15126
> [15.2.x] [#15126] Fixes mapping bug in Cache Full detail

- hibernate/cache-v62/pom.xml
> [#15135] Do not exclude jboss-logging in test deps

- server/memcached/src/main/java/org/infinispan/server/memcached/text/TextOpDecoder.java
- server/memcached/src/test/java/org/infinispan/server/memcached/test/MemcachedFunctionalTest.java
> [#15156] Memcached multi get with non existent keys

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
> [#15107] Refactor JGroupsTransport send logic

- persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/CDIConnectionFactoryConfigurationBuilder.java
- persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/ManagedConnectionFactoryConfiguration.java
- persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/ManagedConnectionFactoryConfigurationBuilder.java
- persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/impl/connectionfactory/ManagedConnectionFactory.java
- persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/logging/Log.java
> [#15036] Allow specifying DataSource when configuring JDBC store programmatically

- commons/all/src/main/java/org/infinispan/commons/marshall/ProtoStreamTypeIds.java
- core/src/main/java/org/infinispan/commands/CommandInvocationId.java
- core/src/main/java/org/infinispan/commands/RequestUUID.java
- core/src/main/java/org/infinispan/interceptors/xsite/BaseBackupInterceptor.java
- core/src/main/java/org/infinispan/interceptors/xsite/NonTransactionalBackupInterceptor.java
- core/src/main/java/org/infinispan/interceptors/xsite/OptimisticBackupInterceptor.java
- core/src/main/java/org/infinispan/interceptors/xsite/PessimisticBackupInterceptor.java
- core/src/main/java/org/infinispan/marshall/persistence/impl/PersistenceContextInitializer.java
- core/src/main/java/org/infinispan/marshall/protostream/impl/GlobalContextInitializer.java
- core/src/main/java/org/infinispan/remoting/transport/Address.java
- core/src/main/java/org/infinispan/transaction/xa/GlobalTransaction.java
- core/src/main/java/org/infinispan/transaction/xa/recovery/RecoveryInfoKey.java
- core/src/main/java/org/infinispan/transaction/xa/recovery/RecoveryManagerImpl.java
- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/main/java/org/infinispan/xsite/irac/IracManager.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyChangedState.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyInfo.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyState.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerStateTransferState.java
- core/src/main/java/org/infinispan/xsite/irac/NoOpIracManager.java
- core/src/test/java/org/infinispan/tx/NoLockLostOnLongTxTest.java
- core/src/test/java/org/infinispan/xsite/irac/ControlledIracManager.java
- core/src/test/java/org/infinispan/xsite/irac/IracMaxIdleTest.java
- core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java
> [#15093] Create new class to identify requests

- core/src/main/java/org/infinispan/manager/DefaultCacheManagerAdmin.java
- core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
* The configuration is updated automatically by the listener.
* The entry is `org.infinispan.CONFIG` needs to be updated as well.
The issue happens because the entry in the cache wasn't updated. I am doing just the easiest thing of submitting another operation to update the previous cache. In theory, there is still a time window where both caches have the same alias and a new node will fail to join. To fix that, we would need to make `org.infinispan.CONFIG` transactional and submit both operations in a single TX.
Closes #15190.
> [#15190] Remove old assigned alias

- anchored-keys/pom.xml
- cdi/embedded/pom.xml
- cdi/remote/pom.xml
- client/hotrod-client/pom.xml
- core/pom.xml
- counter/pom.xml
- gridfs/pom.xml
- integrationtests/cdi-weld-se-it/pom.xml
- integrationtests/endpoints-interop-it/pom.xml
- integrationtests/jboss-marshalling-it/pom.xml
- jcache/embedded/pom.xml
- jcache/remote/pom.xml
- lock/pom.xml
- multimap/pom.xml
- persistence/remote/pom.xml
- persistence/rocksdb/pom.xml
- query-core/pom.xml
- query/pom.xml
- remote-query/remote-query-server/pom.xml
- server/core/pom.xml
- server/hotrod/pom.xml
- server/memcached/pom.xml
- server/resp/pom.xml
- server/rest/pom.xml
- spring/spring6/spring6-embedded/pom.xml
- spring/spring6/spring6-remote/pom.xml
- tasks/manager/pom.xml
- tasks/scripting/pom.xml
- tools/pom.xml
> [15.2.x][#14390] Avoid file clash in surefire-reports

- core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheWriterInterceptor.java
- core/src/test/java/org/infinispan/distribution/BaseDistStoreTest.java
- core/src/test/java/org/infinispan/invalidation/InvalidationPersistenceTest.java
> [#15192] Fix non-tx issue with Invalidation

- core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheWriterInterceptor.java
- core/src/test/java/org/infinispan/distribution/BaseDistStoreTest.java
- core/src/test/java/org/infinispan/invalidation/InvalidationPersistenceTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/15194
Fixes #15192
> [15.2.x] [#15192] Fix non-tx issue with Invalidation

- cli/src/main/java/org/infinispan/cli/impl/CliRuntimeRunner.java
**Backport:** https://github.com/infinispan/infinispan/pull/15228
Closes #15227
> [15.0.x] [#15227] CVE-2025-5731 Fix potential credential leakage in CLI

- server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/ClusteredRollingUpgradeIT.java
- server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/DefaultRollingUpgradeTest.java
- server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/PersistenceRollingUpgradeIT.java
- server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeAuthenticationIT.java
- server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradePersistenceTest.java
- server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeTaskTest.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfiguration.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java
- server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/AbstractServerExtension.java
- server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/RollingUpgradeHandlerExtension.java
* Throws an assertion error by default.
Closes #15185.
> [#15185] Update rolling upgrade exception handler

- documentation/src/main/asciidoc/topics/proc_query_querying_console_cli.adoc
> [#15224] Update query cache CLI doc

- server/rest/src/main/java/org/infinispan/rest/resources/ClusterResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/LocalClusterResourceTest.java
- server/runtime/src/main/java/org/infinispan/server/state/ServerStateManagerImpl.java
> [#15139] Fixes 500 REST endpoint with local server

- core/src/main/java/org/infinispan/manager/DefaultCacheManagerAdmin.java
- core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/15213
* The configuration is updated automatically by the listener.
* The entry is `org.infinispan.CONFIG` needs to be updated as well.
The issue happens because the entry in the cache wasn't updated. I am doing just the easiest thing of submitting another operation to update the previous cache. In theory, there is still a time window where both caches have the same alias and a new node will fail to join. To fix that, we would need to make `org.infinispan.CONFIG` transactional and submit both operations in a single TX.
Closes #15190.
> [15.2.x] [#15190] Remove old assigned alias

- commons/all/src/main/java/org/infinispan/commons/util/ReflectionUtil.java
- commons/all/src/test/java/org/infinispan/commons/util/ClassFinderTest.java
- commons/all/src/test/java/org/infinispan/commons/util/EnumUtilTest.java
- commons/all/src/test/java/org/infinispan/commons/util/ImmutableListCopyTest.java
- commons/all/src/test/java/org/infinispan/commons/util/ReflectionUtilTest.java
- commons/all/src/test/java/org/infinispan/commons/util/UtilTest.java
- hibernate/cache-v62/pom.xml
- pom.xml
Related to #14716. I am opening as draft to check if coverage is improving a little.
> [#14716] Increasing coverage

- commons-test/src/main/java/org/infinispan/commons/test/TestNGTestListener.java
> [#15321] No timeout for cdi test with expectedException

- core/src/main/java/org/infinispan/container/entries/AbstractInternalCacheEntry.java
- core/src/main/java/org/infinispan/container/entries/CacheEntry.java
- core/src/main/java/org/infinispan/container/entries/ClearCacheEntry.java
- core/src/main/java/org/infinispan/container/entries/ForwardingCacheEntry.java
- core/src/main/java/org/infinispan/container/entries/NullCacheEntry.java
- core/src/main/java/org/infinispan/container/entries/ReadCommittedEntry.java
- core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/InvalidationInterceptor.java
- core/src/main/java/org/infinispan/interceptors/locking/ClusteringDependentLogic.java
- core/src/main/java/org/infinispan/notifications/cachelistener/NotifyHelper.java
- core/src/main/java/org/infinispan/util/CoreImmutables.java
- core/src/test/java/org/infinispan/invalidation/InvalidationPersistenceTest.java
- core/src/test/java/org/infinispan/test/fwk/CacheEntryDelegator.java
**Backport:** https://github.com/infinispan/infinispan/pull/15286
Fixes #15193
> [15.2.x] [#15193] Invalidation mode anomalies in transactional cache

- core/src/main/java/org/infinispan/container/entries/AbstractInternalCacheEntry.java
- core/src/main/java/org/infinispan/container/entries/CacheEntry.java
- core/src/main/java/org/infinispan/container/entries/ClearCacheEntry.java
- core/src/main/java/org/infinispan/container/entries/ForwardingCacheEntry.java
- core/src/main/java/org/infinispan/container/entries/NullCacheEntry.java
- core/src/main/java/org/infinispan/container/entries/ReadCommittedEntry.java
- core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/InvalidationInterceptor.java
- core/src/main/java/org/infinispan/interceptors/locking/ClusteringDependentLogic.java
- core/src/main/java/org/infinispan/notifications/cachelistener/NotifyHelper.java
- core/src/main/java/org/infinispan/util/CoreImmutables.java
- core/src/test/java/org/infinispan/invalidation/InvalidationPersistenceTest.java
- core/src/test/java/org/infinispan/test/fwk/CacheEntryDelegator.java
**Backport:** https://github.com/infinispan/infinispan/pull/15286
Fixes #15193
> [15.0.x] [#15193] Invalidation mode anomalies in transactional cache

- server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/DefaultRollingUpgradeTestIT.java
- server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradePersistenceTestIT.java
- server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeTaskTestIT.java
- server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeXSiteIT.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java
- server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/RollingUpgradeHandlerXSiteExtension.java
> [#15348] Include IT suffix to test classes

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
This will allow calls to be shown nested when JGroups tracing is used.
Closes #15287
> [#15287] Make traces current while communication runs against JGroups

- query/src/main/java/org/infinispan/search/mapper/impl/InfinispanMappingInitiator.java
- query/src/test/java/org/infinispan/query/mapper/ProgrammaticSearchMappingProviderTest.java
> [#15394] Fixes ProgrammaticSearchMappingProvider use case

- commons/all/src/test/resources/log4j2-test.xml
- pom.xml
- query/src/test/java/org/infinispan/query/config/CacheModeTest.java
- query/src/test/java/org/infinispan/query/config/EngineConfigTest.java
> [#15415] Build clean up

- integrationtests/server-integration/third-party-server/pom.xml
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/DeploymentHelper.java
Supersedes https://github.com/infinispan/infinispan/pull/15402
Closes #15110
> [#15110] Use weld-servlet-core instead of weld-servlet-shaded

- core/src/main/java/org/infinispan/persistence/sifs/Index.java
- core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
- core/src/main/java/org/infinispan/persistence/sifs/configuration/SoftIndexFileStoreConfigurationBuilder.java
- core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFunctionalTest.java
- documentation/src/main/asciidoc/topics/changes.adoc
- documentation/src/main/asciidoc/topics/con_file_based_cache_stores.adoc
> [#15423] SIFS to support not being segmented

- commons/all/pom.xml
- commons/pom.xml
> [15.0] [#15489] Use correct activation range for JDK 21+

- .github/workflows/on_test_publish_surefire_report.yml
> [#15445] Rise required tests num

- pom.xml
> [#15317] Upgrade commons-lang3 to version 3.18.0

- server/runtime/src/main/server/bin/cli.bat
- server/runtime/src/main/server/bin/server.bat
> [infinispan#15175] remove DelayedExpansion from windows scripts

- build/configuration/pom.xml
- server/tests/src/test/java/org/infinispan/server/functional/resp/AbstractRespTest.java
- server/tests/src/test/java/org/infinispan/server/functional/resp/RespTransactionTest.java
> [#15531] Netty 4.1.124

- core/src/main/java/org/infinispan/marshall/protostream/impl/AbstractInternalProtoStreamMarshaller.java
- core/src/main/java/org/infinispan/marshall/protostream/impl/AbstractMarshallableCollection.java
- core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableCollection.java
- core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableDeque.java
- core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableList.java
- core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableObject.java
- core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableSet.java
> [#15262] Update MarshallableCollection, MarshallableArray etc to store WrappedMessage if !customMarshaller

- .gitignore
- pom.xml
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/tests/pom.xml
- server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
> [15.2] [#14878] Adjust FootprintIT limits to account for coverage and insights

- .gitignore
- pom.xml
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/tests/pom.xml
- server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
> [15.0] [#14878] Adjust FootprintIT limits to account for coverage and insights

- build/configuration/pom.xml
- server/tests/src/test/java/org/infinispan/server/functional/resp/AbstractRespTest.java
> [15.2] [#15531] Netty 4.1.124.Final

- build/configuration/pom.xml
- server/tests/src/test/java/org/infinispan/server/functional/resp/AbstractRespTest.java
> [15.0] [#15531] Netty 4.1.124.Final

- build/configuration/pom.xml
> [#15544] Upgrade to JGroups 5.3.21.Final

- build/configuration/pom.xml
Upgrade blockhound to support JDK 25
> [15.2] Blockhound 1.0.13

- commons/all/src/main/java/org/infinispan/query/remote/client/impl/GlobalContextInitializer.java
- server/core/src/main/java/org/infinispan/server/core/query/impl/GlobalContextInitializer.java
- server/core/src/main/java/org/infinispan/server/core/query/impl/persistence/PersistenceContextInitializer.java
- server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeTestUtil.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/tests/src/test/java/org/infinispan/server/test/core/Common.java
> [#15626] Fix query failures in rolling upgrades

- core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java
> [#15617] Cache stats check cache running

- build/configuration/pom.xml
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/aggregation/RemoteQueryAggregationCountTest.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryAnalyzer.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryMaker.java
- query/src/test/java/org/infinispan/query/aggregation/QueryAggregationBroadcastTest.java
- query/src/test/java/org/infinispan/query/aggregation/QueryAggregationCountTest.java
- query/src/test/java/org/infinispan/query/aggregation/QueryAggregationsSimpleTest.java
- query/src/test/java/org/infinispan/query/model/IndexedPlayer.java
- query/src/test/java/org/infinispan/query/model/Sale.java
- server/rest/src/test/java/org/infinispan/rest/search/aggregation/RestQueryAggregationCountTest.java
- server/tests/src/test/java/org/infinispan/server/functional/extensions/RemoteQueryAccessIT.java
- server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheContinuousQueries.java
- server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheEvents.java
- server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheQueries.java
- server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodFlagCacheOperations.java
- server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodListenerWithDslFilter.java
- server/tests/src/test/java/org/infinispan/server/test/core/Common.java
> [#15075] Use indexed queries for all aggregations

- core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
**Backport:** https://github.com/infinispan/infinispan/pull/15658
Close #15657.
> [15.0.x] [#15657] State transfer progress tracker 30s interval

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java
> [#15662] Client can hang on shutdown

- core/src/main/java/org/infinispan/configuration/cache/StateTransferConfiguration.java
- core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
> [#15649] Make await-initial-transfer mutable

- build/configuration/pom.xml
> [#15628] Updates to Quarkus 3.27

- server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
> [#15730] IsRebalancingEnabled blocking call

- core/pom.xml
- core/src/main/java/org/infinispan/metrics/impl/AbstractMetricsRegistry.java
- core/src/main/java/org/infinispan/metrics/impl/MetricsComponentFactory.java
- core/src/main/java/org/infinispan/metrics/impl/PrometheusRegistry.java
- core/src/main/java/org/infinispan/metrics/impl/PrometheusSimpleClientRegistry.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- javadoc/pom.xml
- pom.xml
> [#15699] Add support for micrometer-registry-prometheus-simpleclient

- server/tests/src/test/java/org/infinispan/server/persistence/JdbcPing2IT.java
* Fix eventually to actually invoke the operation again
Fixes #15771
> [#15771] JdbcPing2IT test hangs
