infinispan/infinispan

query/src/test/java/org/infinispan/query/distributed/ClusteredQueryMassIndexingTest.java
https://issues.jboss.org/browse/ISPN-4822
https://issues.jboss.org/browse/ISPN-4823
Clears the last unstable test in the ```infinispan-query``` suite.
With the work done on ISPN-4621, the MassIndexer now supports 'ClusteredQueries' style independent local indexes.
=> ISPN-4822 MassIndexer is not ClusteredQuery friendly

server/integration/testsuite/src/test/java/org/infinispan/server/test/jmx/management/JmxManagementIT.java
https://issues.jboss.org/browse/ISPN-5394
=> ISPN-5394  JmxManagementIT.testCacheManagerAttributes fails

documentation/src/main/asciidoc/user_guide/chapter-48-Using_Hot_Rod_Server.adoc, server/hotrod/src/main/scala/org/infinispan/server/hotrod/ClientListenerRegistry.scala, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/AbstractRemoteCacheIT.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/CustomEvent.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/CustomEventLogListener.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/CustomPojoEventConverterFactory.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/CustomPojoEventFilterFactory.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/CustomPojoFilterConverterFactory.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/HotRodRemoteCacheIT.java
* For custom classes to work fine with remote filter/converter classes, they need to be deployed in the same JAR along with the filter and/or converter classes.
=> ISPN-5444 Filter/converters can work with custom classes

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/RemoteAsyncAPIForceReturnPerCallTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/RemoteAsyncAPITest.java
* They were previously being ignored as a result of not sending from the
main thread to the thread executing the async operation.
=> ISPN-5677 RemoteCache async methods use flags [7.2.x]

integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/QueryDslConditionsTest.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java, query/src/test/java/org/infinispan/query/dsl/embedded/QueryDslConditionsTest.java
This was a leftover from an earlier version which did not take the params in the constructor.
Add test for hybrid query with parameter.
=> No need to set query parameters again after construction

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ClusterConfiguration.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ClusterConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/TopologyInfo.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/HotRodConstants.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/TransportFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/tcp/TcpTransportFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/HotRodClientTestingUtil.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/AbstractHotRodSiteFailoverTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/SiteDownFailoverTest.java, documentation/src/main/asciidoc/user_guide/chapter-48-Using_Hot_Rod_Server.adoc
https://issues.jboss.org/browse/ISPN-5520
* This initial implementation supports dealing with entire clusters
failing, and falling back on cluster information defined in Hot Rod
configuration.
* It's necessary for at least a single server's IP address to be
provided in the cluster definition, and from that the rest of the
topology can be deduced.
* Once a node has connected to a different site cluster, it remains
connected to that site until the cluster becomes unavailable, in which
case it failovers to next cluster.
* If all cluster sites become unavailable, as a last resort the initial
server configuration is tried.
=> ISPN-5520 Hot Rod client XSite failover support

javadoc/pom.xml
Fixed javadoc issue that was pointing to commons erroneously.
=> Fixed javadoc to point to correct common dependency

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/CacheTopologyInfo.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/CacheTopologyInfoImpl.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/TopologyInfo.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec10.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec20.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/HeaderParams.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/TransportFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/tcp/TcpTransportFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ConsistentHashV1IntegrationTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/RetryOnFailureUnitTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/SiteDownFailoverTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/SiteManualSwitchTest.java
Matej and I have been testing manually but I didn't have time to create a unit test for it. I'll create a JIRA for this.
* When switching clusters, update topology id of the cache involved. To
do so, enhance TopologyInfo to deal with multiple topology ids.
* Instead of relying on individual requests to check failover validity,
add a step in the failover cluster switch logic to check the servers
to which it is going to failover. If none of those are available
consider cluster switch not achieved. If any succeed, switch the
cluster and apply new topology.
* Cluster switches can happen while clients are hammering the server, in
which case there's a possibility that after a cluster switch old
topology updates are received. To avoid these being applied, the
concept of topology age has been …
=> ISPN-5879 Avoid concurrent cluster switches

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/TransportObjectFactoryTest.java, core/src/test/java/org/infinispan/partitionhandling/BasePartitionHandlingTest.java, server/hotrod/src/main/scala/org/infinispan/server/hotrod/CrashedMemberDetectorListener.scala, server/hotrod/src/main/scala/org/infinispan/server/hotrod/HotRodServer.scala, server/hotrod/src/test/scala/org/infinispan/server/hotrod/HotRodMergeTest.scala
https://issues.jboss.org/browse/ISPN-5889
Use a distributed task to check if any other member removed this node's
address, instead of relying on a CacheEntryInvalidatedEvent.
=> ISPN-5889 Re-add node to topology cache with overlapping partitions

core/src/main/java/org/infinispan/stream/impl/AbstractCacheStream.java, core/src/test/java/org/infinispan/stream/BaseStreamTest.java
deadlock issues
* Make sure processed segments are checked when completing
https://issues.jboss.org/browse/ISPN-6249
=> ISPN-6249 Streams filter key segments with using count can cause

parent/pom.xml
The tracking JIRA is: https://issues.jboss.org/browse/ISPN-6380
In the pom.xml you can see the big list of src folders which is added to sources of maven. This is done for jacoco, so that the generated report can also show the covered and uncovered lines directly on the class files. 
The build-helper-maven-plugin does not support the src folders inclusion via wildcards or include/exclude tags. If this is ok, I will file an issue in plugins repo, and as soon as it is implemented will change my code correspondingly.
=> ISPN-6380 - Fixed the coverage and jacocoReport profiles.

core/src/main/java/org/infinispan/notifications/cachelistener/cluster/ClusterEvent.java, core/src/test/java/org/infinispan/notifications/cachelistener/cluster/AbstractClusterListenerUtilTest.java
https://issues.jboss.org/browse/ISPN-6744
This needs to be cherry-picked to older versions as well.
=> Ispn 6744 ClusterEvent doesn't implement CacheEntryExpired

core/src/test/java/org/infinispan/notifications/cachelistener/cluster/AbstractClusterListenerUtilTest.java
* Changed test back to make it more reliable
https://issues.jboss.org/browse/ISPN-6744
This can go into 8.2.x as well.
=> ISPN-6744 ClusterEvent doesn't implement CacheEntryExpired

server/rest/src/main/scala/org/infinispan/rest/Server.scala, server/rest/src/test/scala/org/infinispan/rest/IntegrationTest.scala
https://issues.jboss.org/browse/ISPN-6626
Adding check for "\r" which will work in case the test is run on Windows machine.
=> ISPN-6626 - IntegrationTest.testGet* fails on Windows

core/src/main/java/org/infinispan/factories/components/JmxOperationMetadata.java
Added a null check and moved the check from the getter for operationName inside the constructor. Now operationName takes methodName in case when mo is null.
=> Potential null pointer dereference. Minor refactoring.

commons/src/main/java/org/infinispan/commons/util/OsgiClassLoader.java
Some weak references were used without checking for null.
=> Necessary null checks added because WeakReference.get() may return null.

core/src/main/java/org/infinispan/remoting/transport/jgroups/CommandAwareRpcDispatcher.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/RspListFuture.java, core/src/main/java/org/infinispan/statetransfer/InboundTransferTask.java
https://issues.jboss.org/browse/ISPN-7064
* Set the GroupRequest listener before the request is sent.
* Send the state transfer cancel commands asynchronously.
Not necessary with JGroups 4.0.
=> ISPN-7064 RPC to leaver times out instead of finishing immediately

core/src/main/java/org/infinispan/remoting/transport/jgroups/CommandAwareRpcDispatcher.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/RspListFuture.java, core/src/main/java/org/infinispan/statetransfer/InboundTransferTask.java
https://issues.jboss.org/browse/ISPN-7064
* Set the GroupRequest listener before the request is sent.
* Send the state transfer cancel commands asynchronously.
=> [8.2.x] ISPN-7064 RPC to leaver times out instead of finishing immediately

core/src/test/java/org/infinispan/marshall/SharedStreamMultiMarshallerTest.java, core/src/test/java/org/infinispan/marshall/VersionAwareMarshallerTest.java
https://issues.jboss.org/browse/ISPN-7111
=> ISPN-7111 Avoid using InetAddress.getLocalHost() in the tests

core/src/main/java/org/infinispan/container/entries/ClusteredRepeatableReadEntry.java, core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java, core/src/main/java/org/infinispan/transaction/impl/AbstractCacheTransaction.java, core/src/main/java/org/infinispan/transaction/xa/CacheTransaction.java
https://issues.jboss.org/browse/ISPN-7096
=> ISPN-7096 Remove CacheTransaction.lookedUpRemoteVersions

server/integration/testsuite/pom.xml, server/integration/testsuite/src/test/java/org/infinispan/server/test/jcache/JCacheStateAwarenessIT.java, server/integration/testsuite/src/test/resources/config/infinispan/cachecontainer.xml
Created new IT JCacheStateAwarenessIT to verify 
https://issues.jboss.org/browse/ISPN-6574
The new test has three additional tests commented out, these should be addressed in 
https://issues.jboss.org/browse/ISPN-7095
and uncommented later
Infinispan-remote dependency had to be removed from POM (no apparent impact on test results) due to clash with other dependencies (similar to ISPN-5193)
=> ISPN-6574 New IT JCacheStateAwarenessIT

integrationtests/compatibility-mode-it/src/test/java/org/infinispan/it/compatibility/EmbeddedRestHotRodTest.java, integrationtests/compatibility-mode-it/src/test/java/org/infinispan/it/compatibility/EmbeddedRestMemcachedHotRodTest.java, integrationtests/compatibility-mode-it/src/test/java/org/infinispan/it/compatibility/ReplEmbeddedRestHotRodTest.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/rest/AbstractRESTClientIT.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/rest/RESTAsyncIT.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/rest/RESTHelper.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/rest/RESTReplicationIT.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/configs/ExampleConfigsIT.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/expiration/ExpirationIT.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/rollingupgrades/RestRollingUpgradesDistIT.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/rollingupgrades/RestRollingUpgradesIT.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/security/rest/AbstractBasicSecurity.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/security/rest/RESTCertSecurityIT.java, server/rest/src/test/scala/org/infinispan/rest/TwoServerTest.java
commons-logging 1.1 was exposing HTTPServletResponse, but
commons-logging 1.2 made the servlet-api dependency optional.
=> [8.2.x] ISPN-6241 Fix compilation error in integration tests

query-dsl/src/main/java/org/infinispan/query/dsl/impl/BaseQuery.java
* we provide this method temporarily to avoid sudden compatibility issues with existing clients
* this is deprecated and will be removed in Infinispan 10.0
=> Continue to provide BaseQuery.getJPAQuery() method for backward compat

bom/pom.xml, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/marshall/ProtoStreamMarshaller.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/ModelFactoryPB.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/TransactionPB.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/marshallers/TransactionMarshaller.java, integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/testdomain/Transaction.java, integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/testdomain/hsearch/TransactionHS.java, object-filter/src/test/java/org/infinispan/objectfilter/impl/hql/ProtobufParsingTest.java, object-filter/src/test/java/org/infinispan/objectfilter/test/ProtobufMatcherTest.java, object-filter/src/test/java/org/infinispan/objectfilter/test/perf/ProtobufPerfTest.java, query/src/test/java/org/infinispan/query/dsl/embedded/testdomain/ModelFactory.java, query/src/test/java/org/infinispan/query/dsl/embedded/testdomain/Transaction.java, query/src/test/java/org/infinispan/query/dsl/embedded/testdomain/hsearch/ModelFactoryHS.java, query/src/test/java/org/infinispan/query/dsl/embedded/testdomain/hsearch/TransactionHS.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/DelegatingSerializationContext.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufFieldBridgeProvider.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufIndexedFieldProvider.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/filter/JPAFilterConverterUtils.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/FieldMapping.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadata.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadataCreator.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingTagHandler.java, server/integration/versions/pom.xml
* adapt to the protostream configuration API changes
* update protostream marshaller for the new Transaction.longDescription property in the test domain model
* add protostream annotations for analyzer
* rename protostream annotation ```@IndexedField``` to ```@Field``` and enhance it with more capabilities similar to Hibernate Search
https://issues.jboss.org/browse/ISPN-7183
=> ISPN-7183 Upgrade to protostream-4.0.0.Alpha2

core/src/main/java/org/infinispan/executors/LimitedExecutor.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/test/java/org/infinispan/executors/LimitedExecutorTest.java
https://issues.jboss.org/browse/ISPN-7172
* Fix WithinThreadExecutor handling in LimitedExecutor
* Remove LimitedExecutor permit before putting the LocalCacheStatus
in the runningCaches map.
=> ISPN-7172 Total order caches can hang during join

server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/BaseStoreConfigurationResource.java, server/integration/infinispan/src/main/resources/schema/jboss-infinispan-core_9_0.xsd
https://issues.jboss.org/browse/ISPN-7277
=> ISPN-7277:  Passivation disabled in embedded but enabled in server mode.

core/src/main/java/org/infinispan/marshall/core/ExternallyMarshallable.java
We have Selenium tests for quickstarts, which are started via maven-surefire-plugin, which enables assertions. Due to this, the assert fails on simple quickstart classes. In order not to complicate quickstarts with ExternalPojo or anything other configuration, I'm adding this package to whitelist.
=> Add quickstarts classes to whitelist of ExternallyMarshalable

core/src/main/java/org/infinispan/remoting/transport/jgroups/RspListFuture.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/SingleResponseFuture.java
https://issues.jboss.org/browse/ISPN-7238
=> ISPN-7238 Eliminate timeout task allocation for SingleResponseFuture

documentation/src/main/asciidoc/user_guide/cdi.adoc, documentation/src/main/asciidoc/user_guide/configuration.adoc, documentation/src/main/asciidoc/user_guide/eviction.adoc, documentation/src/main/asciidoc/user_guide/integrations.adoc
* Changed eviction section to have data container
* Added in caffeine and off heap
https://issues.jboss.org/browse/ISPN-7290
=> ISPN-7290 Document Data Container Changes

core/src/main/java/org/infinispan/marshall/jboss/ExternalizerTable.java, core/src/main/java/org/infinispan/util/logging/Log.java
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1403018
No upstream required
=> BZ-1403018 Backport ISPN-4706 To EAP 6.4.x

core/src/main/java/org/infinispan/commands/write/RemoveExpiredCommand.java, core/src/main/java/org/infinispan/commands/write/ValueMatcher.java, core/src/main/java/org/infinispan/context/SingleKeyNonTxInvocationContext.java, server/hotrod/src/test/scala/org/infinispan/server/hotrod/HotRodMarshallingTest.scala
* Wrap the key in HotRodMarshallingTest
* Never call key.equals(null) in SingleKeyNonTxInvocationContext,
because the JCache has some keys that don't implement it correctly.
* Remove Objects.equals() usage in value matchers
* Check the existing value instead of the new value in
MATCH_EXPECTED_OR_NULL
=> ISPN-6802 Fix tests broken by equivalence removal

commons/src/main/java/org/infinispan/commons/configuration/attributes/AttributeSet.java, commons/src/main/java/org/infinispan/commons/persistence/Store.java, core/src/main/java/org/infinispan/configuration/cache/AbstractStoreConfigurationBuilder.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/persistence/StoreConfigurationValidationTest.java, core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java, persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java, persistence/jpa/src/main/java/org/infinispan/persistence/jpa/JpaStore.java, persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java, persistence/rest/src/main/java/org/infinispan/persistence/rest/RestStore.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/SoftIndexFileStore.java
https://issues.jboss.org/browse/ISPN-7286
I have created a generic `@Store` annotation which currently only specifies whether a store can be shared or not (default=true), however in the future we can additional store characteristics here to help with config validation. If a store doesn't have a `@Store` annotation, e.g. third party stores, then the additional validation is simply ignored.
=> ISPN-7286: Cache stores should declare whether they can be shared.

commons/src/main/java/org/infinispan/commons/util/Util.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/Decoder2x.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodDecoder.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodPipeTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodTestingUtils.java
* Make sure hotrod tests use single frame decoder
* Fixed replay bugs that snuck in
https://issues.jboss.org/projects/ISPN/issues/ISPN-7358
=> ISPN-7364 SingleFrameDecoder is not applied to hot rod tests

plugins/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsExtractorMojo.java
https://issues.jboss.org/browse/ISPN-7371
When running `mvn install` we need to get classes from the jar, but when running `mvn test` the jar is not present, instead the classes are already on the classpath. Therefore, we log a missing jar instead of throwing an exception as we know the classes will be retrieved from the classpath.
=> ISPN-7371: infinispan-defaults - Rocksdb jar not found for leveldb.

server/integration/versions/pom.xml
Bump admin console to latest tagged and released version - 9.0.0.Beta2. Please integrate for the 9.0.0.Beta2 release
=> Bump console to 9.0.0.Beta2

core/src/main/java/org/infinispan/xsite/BackupReceiverRepositoryImpl.java
Do not attempt to use the default cache for xsite backups if one hasn't been configured
=> ISPN-7066 Fix for ExampleConfigsIT#testXsiteConfig failures

core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java, core/src/main/java/org/infinispan/remoting/transport/AbstractDelegatingTransport.java, core/src/main/java/org/infinispan/remoting/transport/Transport.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/xsite/XSiteAdminOperationsTest.java, server/integration/infinispan/src/main/java/org/infinispan/server/infinispan/SecurityActions.java, server/integration/infinispan/src/main/java/org/infinispan/server/infinispan/actions/GetSitesViewAction.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerMetricsHandler.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/MetricKeys.java, server/integration/jgroups/src/main/java/org/infinispan/server/jgroups/JChannelFactory.java, server/integration/jgroups/src/main/java/org/infinispan/server/jgroups/logging/JGroupsLogger.java
* Expose x-site view as INFO log message, JMX and DMR attribute.
* Two route status listeners have been created for handling embedded and
in-server set ups who track the x-site view members.
=> ISPN-7230 ISPN-7231 Expose XSite view

core/src/test/java/org/infinispan/manager/CacheManagerTest.java
=> ISPN-7066 Ensure CacheManagerTest.testMissingDefaultConfiguration uses a unique jmx domain

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
I removed the fix for the Java 6 bug (id 6427854, http://bugs.java.com/view_bug.do?bug_id=6427854).
It was fixed in 2011 (with Java7 b08).
Infinispan is baselined on Java 8.
=> removed fix for the java 6 bug (id 6427854) fixed in java 7

as-modules/embedded/src/main/resources/com/github/ben-manes/caffeine/main/module.xml
The as-modules dir was accidentally added again as part of the off-heap PR.
=> ISPN-7007: Remove as-modules dir that was accidentally reintroduced.

commons/src/main/resources/features.xml, wildfly-modules/src/main/resources/org/infinispan/client/hotrod/main/module.xml, wildfly-modules/src/main/resources/org/infinispan/commons/main/module.xml, wildfly-modules/src/main/resources/org/infinispan/core/main/module.xml
* Make caffeine optional dependency for maven
* Make caffeine internal dependency for as modules
https://issues.jboss.org/browse/ISPN-7464
=> ISPN-7464 Make caffeine optional dependency for infinispan core

core/src/main/java/org/infinispan/remoting/transport/jgroups/CommandAwareRpcDispatcher.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/Responses.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/RspListFuture.java, core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsTransportTest.java
… members
https://issues.jboss.org/browse/ISPN-7377
MessageDispatcher.cast() removes missing members from the destinations list
=> ISPN-7377 RPCs to non-members throw spurious TimeoutException

persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/table/management/PostgresTableManager.java, persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/table/management/SybaseTableManager.java
See: https://issues.jboss.org/browse/ISPN-7480
The logger was probably a copy&paste error, hence correcting it together.
=> [ISPN-7480] JDBC cache store doesn't work on Sybase

core/src/test/java/org/infinispan/container/versioning/AbstractClusteredWriteSkewTest.java
* Tries inserting different keys if first set fails
https://issues.jboss.org/browse/ISPN-7513
=> ISPN-7513 AbstractClusteredWriteSkewTest can fail randomly still

core/src/main/java/org/infinispan/persistence/util/PersistenceManagerCloseableSupplier.java, core/src/test/java/org/infinispan/persistence/LocalModePassivationTest.java
* Fixed bug where cache loader can miss entry with bulk op
https://issues.jboss.org/browse/ISPN-7522
The actual fix is trivial, but understanding what it is doing requires a little more knowledge.  Basically persistence thread is constantly feeding entries and then once it is complete it calls the close method.  However the user thread is constantly pulling from the queue being fed to it.
There was a small window where the queue could be empty for the user thread (so it checks to see if the supplier was closed).  If the persistence thread puts stuff into a queue and closes the supplier during this time the user thread won't see those last entries.
=> ISPN-7522 LocalMode[No]PassivationTest fails randomly

core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java, core/src/main/java/org/infinispan/interceptors/impl/BaseRpcInterceptor.java
https://issues.jboss.org/browse/ISPN-7523
Not sure if the `volatile` is really needed - we could probably live a moment before the update is propagated to the other threads. But volatile reads should be cheap.
=> ISPN-7523 Update cached RpcOptions when timeout changes

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SizeTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/SingleServerCompatibilityRemoteIteratorTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/HotRodNonIndexedQueryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/HotRodNonIndexedSingleFileStoreQueryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/HotRodQueryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDslConditionsTunedTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryJmxTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryWithProtostreamAnnotationsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/TwoCachesSharedIndexTest.java, core/src/test/java/org/infinispan/api/ByteArrayCacheTest.java, core/src/test/java/org/infinispan/api/MetadataAPIDistTest.java, core/src/test/java/org/infinispan/lock/KeyLockTest.java, core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodTestingUtils.java, server/hotrod/src/test/scala/org/infinispan/server/hotrod/test/HotRodTestingUtil.scala
* this is deprecated and a no-op anyway
https://issues.jboss.org/browse/ISPN-7539
=> ISPN-7539 Do not configure data container key/value equivalence in tests

core/src/main/java/org/infinispan/configuration/cache/AbstractStoreConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/ConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/EvictionConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/IndexingConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/PersistenceConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/SitesConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/StateTransferConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/TransactionConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/XSiteStateTransferConfigurationBuilder.java, core/src/main/java/org/infinispan/registry/impl/InternalCacheRegistryImpl.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/xsite/XSiteStateTransferFileParsingTest.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/BaseStoreConfigurationResource.java, server/integration/infinispan/src/main/resources/infinispan-defaults.xml
- Do not log configuration warnings for templates
- Also extract some configuration exceptions to log
- Do not disable expiration reaper in server
https://issues.jboss.org/browse/ISPN-7532
=> ISPN-7532 Do not log configuration warnings for templates

integrationtests/wildfly-modules/src/test/java/org/infinispan/test/integration/as/InfinispanStoreRocksDBIT.java, integrationtests/wildfly-modules/src/test/resources/arquillian.xml, server/integration/testsuite/src/test/java/org/infinispan/server/test/cs/rocksdb/RocksDBCacheStoreIT.java
https://issues.jboss.org/browse/ISPN-7530
=> ISPN-7530 InfinispanStoreRocksDBIT leaves files in the current directory

core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/test/java/org/infinispan/manager/CacheManagerTest.java
Configuration) applies the configurations in the wrong order
* Changed order so template applies first
https://issues.jboss.org/browse/ISPN-7587
=> ISPN-7587 DefaultCacheManager.defineConfiguration(String, String,

documentation/src/main/asciidoc/user_guide/integrations.adoc, integrationtests/as-lucene-directory/src/test/resources/user-provided-infinispan-persistence.xml, integrationtests/wildfly-modules/src/test/java/org/infinispan/test/integration/as/InfinispanModulesStoreJdbcIT.java, lucene/directory-provider/src/main/java/org/infinispan/hibernate/search/impl/DefaultCacheManagerService.java, lucene/directory-provider/src/main/java/org/infinispan/hibernate/search/impl/InfinispanConfigurationParser.java, lucene/lucene-directory/pom.xml, lucene/lucene-directory/src/main/java/org/infinispan/lucene/LifecycleCallbacks.java, wildfly-modules/build.xml, wildfly-modules/src/main/resources/org/infinispan/core/main/module.xml, wildfly-modules/src/main/resources/org/infinispan/for-hibernatesearch-wildfly/main/module.xml
This was a bit more complex than expected, as the Lucene Directory Provider component for Hibernate Search used to have its own copy of Infinispan-core.
Because of this copy, the CacheStore implementations would also depend on the wrong infinispan-core module instance, so I finally pulled off the full cleanup and we no longer need the Infinispan-core copies in the custom modules.
To achieve this removal, I had to fallback to an "explicit registration" of the custom Externalizers of the Lucene Directory module, as infinispan-core can no longer depend directly on Infinispan Query, or it would introduce the wrong Hibernate Search module on classpath.. 
Finally it feels much cleaner, I guess the mistake was trying hard to make service discovery work.
https://issues.jboss.org/browse/ISPN-7572
=> Fixing CacheStore / Lucene Directory integration

core/src/main/java/org/infinispan/container/offheap/BoundedOffHeapDataContainer.java, core/src/test/java/org/infinispan/container/offheap/OffHeapBoundedMemoryTest.java
than total size
* Make sure to handle eviction when entry is both head and tail
https://issues.jboss.org/browse/ISPN-7618
=> ISPN-7618 Bounded Off Heap can crash when a single entry size is larger

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/ProtocolVersion.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/Decoder2x.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/AbstractRemoteCacheIT.java
https://issues.jboss.org/browse/ISPN-7636
* Use HR 2.6 as default protocol version
* Fix HR decoder to read add listener command correctly
=> ISPN-7636 Update default HR version and fix HR decoder

core/src/test/java/org/infinispan/api/APINonTxTest.java, core/src/test/java/org/infinispan/distribution/DistSyncFuncTest.java
https://issues.jboss.org/browse/ISPN-7650
=> ISPN-7650 Refactoring two functional test assertions

integrationtests/as-lucene-directory/src/test/java/org/infinispan/test/integration/as/wildfly/InfinispanModuleMemberRegistrationIT.java, integrationtests/as-lucene-directory/src/test/resources/user-provided-infinispan-persistence.xml
A follow up on the already-merged ISPN-7572 to fix the regression spotted by the testsuite.
The important bit is setting the caches to `non-transactional` as otherwise the concurrent writes on H2 end up in transaction locks, caused e.g. by the Lucene merger thread and our async deletions of index data.
While at it, I also spotted two configuration inconsistencies.
=> ISPN-7572 Correct the testing configuration for index storage in H2

core/src/main/java/org/infinispan/configuration/cache/Configurations.java, core/src/main/java/org/infinispan/configuration/internal/PrivateGlobalConfiguration.java, core/src/main/java/org/infinispan/configuration/internal/PrivateGlobalConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/internal/PrivateGlobalConfigurationSerializer.java, core/src/main/java/org/infinispan/configuration/internal/package-info.java, core/src/main/java/org/infinispan/factories/InboundInvocationHandlerFactory.java, core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java, core/src/main/java/org/infinispan/factories/ResponseGeneratorFactory.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-7641
=> ISPN-7641 Do not use the Triangle when in server mode

server/integration/feature-pack/src/main/resources/modules/system/layers/base/org/infinispan/protostream/main/module.xml, server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/security/HotRodKrbAuthIT.java, server/integration/testsuite/src/test/resources/ibm_jaas_krb_login.conf, wildfly-modules/src/main/resources/org/infinispan/protostream/main/module.xml
ISPN-7675 Use a special JAAS login configuration file for Kerberos tests
ISPN-7676 Add sun.jdk dependency to Protostream server module
https://issues.jboss.org/browse/ISPN-7675
https://issues.jboss.org/browse/ISPN-7676
=> Some fixes for IBM JDK

core/src/test/java/org/infinispan/distribution/groups/BaseUtilGroupTest.java
Radim noticed a mistake introduced by my ISPN-7400 fix, which means the originator cache is sometimes a backup owner instead of a non-owner. The tests probably pass because the replication is about the same either way :)
=> ISPN-7400 Fix the the non-owner cache selection in BaseUtilGroupTest

bom/pom.xml, server/integration/versions/pom.xml
https://issues.jboss.org/browse/ISPN-7699
Infinispan 9.0.0.Final uses protostream-4.0.0.CR3 which is identical to 4.0.0.Final, so this upgrade is safe both for infinispan 9.1.x and 9.0.1.
=> ISPN-7699 Upgrade to protostream-4.0.0.Final

core/src/test/resources/stacks/tcp.xml
See https://issues.jboss.org/browse/JGRP-2167 (ping @belaban)
This issue is causing an often failure in `GetAllCommandStressTest`, where the `getAll()` fails with `TimeoutException` instead of being properly retried, because the originator node does not get the new view (without stopped member).
=> JGRP-2167 workaround

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ExpiryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientClusterExpirationEventsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientClusterFailoverEventsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/EmbeddedCompatContinuousQueryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/RemoteContinuousQueryTest.java, core/src/test/java/org/infinispan/api/ConditionalOperationPrimaryOwnerFailTest.java, core/src/test/java/org/infinispan/api/MetadataAPIDefaultExpiryTest.java, core/src/test/java/org/infinispan/container/SimpleDataContainerTest.java, core/src/test/java/org/infinispan/container/versioning/WriteSkewConsistencyTest.java, core/src/test/java/org/infinispan/distribution/rehash/OngoingTransactionsAndJoinTest.java, core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java, core/src/test/java/org/infinispan/expiry/AutoCommitExpiryTest.java, core/src/test/java/org/infinispan/expiry/ExpiryTest.java, core/src/test/java/org/infinispan/notifications/cachelistener/cluster/AbstractClusterListenerUtilTest.java, core/src/test/java/org/infinispan/partitionhandling/BaseTxPartitionAndMergeTest.java, core/src/test/java/org/infinispan/persistence/BaseStoreTest.java, core/src/test/java/org/infinispan/statetransfer/TxReplay3Test.java, core/src/test/java/org/infinispan/test/TestingUtil.java, core/src/test/java/org/infinispan/test/concurrent/InboundRpcSequencerAction.java, core/src/test/java/org/infinispan/util/ControlledTimeService.java, core/src/test/java/org/infinispan/xsite/offline/OfflineStatusTest.java, core/src/test/java/org/infinispan/xsite/statetransfer/failures/RetryMechanismTest.java, extended-statistics/src/test/java/org/infinispan/stats/BaseClusteredExtendedStatisticTest.java, jcache/commons/src/test/java/org/infinispan/jcache/AbstractTwoCachesExpirationTest.java, jcache/embedded/src/test/java/org/infinispan/jcache/JCacheLoaderTest.java, lucene/lucene-directory/src/test/java/org/infinispan/lucene/impl/DeltaReplicationTest.java, query/src/test/java/org/infinispan/query/continuous/ContinuousQueryTest.java
Offloading independent changes handy in other (future) PRs.
My motivation for using real time as start offset of the TimeService mock was that I wanted to place `assert timestamp != 0` at certain places.
=> [testsuite] Minor convenience changes

core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
https://issues.jboss.org/browse/ISPN-7696
=> ISPN-7696 RemoveExpired could be called with updated value

bom/pom.xml, integrationtests/elasticsearch-indexmanager-it/README-tests.txt, integrationtests/elasticsearch-indexmanager-it/pom.xml, integrationtests/elasticsearch-indexmanager-it/src/test/java/org/infinispan/query/it/ClusteredCacheWithElasticsearchIndexManagerIT.java, integrationtests/elasticsearch-indexmanager-it/src/test/java/org/infinispan/query/it/ElasticSearchMassIndexingIT.java, integrationtests/elasticsearch-indexmanager-it/src/test/java/org/infinispan/query/it/ElasticSearchNonIndexedValuesIT.java, integrationtests/elasticsearch-indexmanager-it/src/test/java/org/infinispan/query/it/ElasticsearchDSLConditionsIT.java, integrationtests/elasticsearch-indexmanager-it/src/test/java/org/infinispan/query/it/ElasticsearchTesting.java, integrationtests/elasticsearch-indexmanager-it/start-elastic.sh, integrationtests/wildfly-modules/pom.xml, integrationtests/wildfly-modules/src/test/resources/elasticsearch-indexing.xml, parent/pom.xml, query/src/main/java/org/infinispan/query/impl/LifecycleManager.java, query/src/test/java/org/infinispan/query/blackbox/TopologyAwareClusteredCacheTest.java, query/src/test/java/org/infinispan/query/blackbox/TopologyAwareClusteredQueryTest.java, query/src/test/java/org/infinispan/query/distributed/TopologyAwareDistMassIndexingTest.java, query/src/test/java/org/infinispan/query/dsl/embedded/impl/model/TheEntity.java, query/src/test/java/org/infinispan/query/dsl/embedded/testdomain/hsearch/AccountHS.java, query/src/test/java/org/infinispan/query/dsl/embedded/testdomain/hsearch/TransactionHS.java, query/src/test/java/org/infinispan/query/helper/TestQueryHelperFactory.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingTagHandler.java, wildfly-modules/build.xml
Upgrading Hibernate Search to the latest.
Headlines are here, essentially it now supports Elasticsearch 5 and the client is much improved:
- http://in.relation.to/2017/04/15/HibernateSearchNowSpeakingEs5/
Relevant for Infinispan: several internal bugfixes, some small performance improvements and most notably we flipped the default value for this configuration property:
- https://docs.jboss.org/hibernate/search/5.8/api/org/hibernate/search/cfg/Environment.html#INDEX_UNINVERTING_ALLOWED
This PR includes a "flip back" of the defaults for Infinispan, as I believe Infinispan Server is not ready to handle that yet.
- https://issues.jboss.org/browse/ISPN-7670
=> ISPN-7670 Upgrade to Hibernate Search 5.8.0.Beta1

Jenkinsfile
@Holmistr It turned out that when a compilation failure occurs, we *should* fail the pipeline.
=> Fail build on compilation error

core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/BaseRpcInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/BaseStateTransferInterceptor.java, core/src/test/java/org/infinispan/commands/GetAllCommandNodeCrashTest.java, core/src/test/java/org/infinispan/test/TestingUtil.java
https://issues.jboss.org/browse/ISPN-7717
I am actually not sure if throwing the IllegalStateException is entirely necessary, I vaguely recall Dan asking me to add it there, but I am fine with leaving it out. IIRC, upon suspect exception the retry should have been executed immediately, without waiting for the next topology.
=> ISPN-7717 ClusteredGetAllCommand should be invoked with SYNCHRONOUS_IGNORE_LEAVERS

query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java, query/src/test/java/org/infinispan/configuration/CreateCacheIndexTemplateTest.java
* Make sure QueryInterceptor abides by Inject rules
https://issues.jboss.org/browse/ISPN-7844
=> ISPN-7844 Cache templates with Type fail when they enable indexing

server/integration/feature-pack/pom.xml, server/integration/feature-pack/src/main/resources/modules/system/layers/base/org/jboss/marshalling/river/main/module.xml
https://issues.jboss.org/browse/ISPN-7838
I think we will need this for 9.0.x and probably 8.2.x.
@galderz @tristantarrant For ISPN-7652 it wasn't sufficient to simply ignore the river marshaller because wildfly-core depends on the river marshaller [upon domain startup](https://github.com/wildfly/wildfly-core/blob/master/server/src/main/java/org/jboss/as/server/DomainServerMain.java#L116), hence the NPE we encounter. So instead, we now explicitly depend on the version we need (2.0.0.Beta3), whilst excluding jboss-marshalling from this jar. This resolves the NPE and prevents `rg.infinispan.server.test.client.hotrod.HotRodRemoteCacheIT` from failing (as discussed [here](https://github.com/infinispan/infinispan/pull/4709))
=> ISPN-7838 Fix JBoss Modules NPE in Domain mode

core/src/main/java/org/infinispan/container/entries/AbstractInternalCacheEntry.java, core/src/main/java/org/infinispan/container/entries/CacheEntry.java, core/src/main/java/org/infinispan/container/entries/ClearCacheEntry.java, core/src/main/java/org/infinispan/container/entries/DeltaAwareCacheEntry.java, core/src/main/java/org/infinispan/container/entries/ForwardingCacheEntry.java, core/src/main/java/org/infinispan/container/entries/NullCacheEntry.java, core/src/main/java/org/infinispan/container/entries/ReadCommittedEntry.java, core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/VersionedEntryWrappingInterceptor.java, core/src/main/java/org/infinispan/interceptors/locking/ClusteringDependentLogic.java, core/src/main/java/org/infinispan/interceptors/totalorder/TotalOrderVersionedEntryWrappingInterceptor.java, core/src/main/java/org/infinispan/statetransfer/CommitManager.java, core/src/main/java/org/infinispan/util/CoreImmutables.java, core/src/test/java/org/infinispan/distribution/rehash/NonTxStateTransferOverwritingValue2Test.java, core/src/test/java/org/infinispan/notifications/cachelistener/OnlyPrimaryOwnerTest.java, core/src/test/java/org/infinispan/test/fwk/CacheEntryDelegator.java, core/src/test/java/org/infinispan/test/fwk/ClusteringDependentLogicDelegator.java
https://issues.jboss.org/browse/ISPN-7866
Metadata should be simply updated using `setMetadata()` on the `CacheEntry` in context, instead of passing the instance down.
=> ISPN-7866 Remove metadata param from CacheEntry.commit()

persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/table/management/PostgresTableManager.java, persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/table/management/SybaseTableManager.java
Backporting https://issues.jboss.org/browse/ISPN-7480 as part of backports https://issues.jboss.org/browse/ISPN-7327
=> [8.2] ISPN-7480 JDBC cache store doesn't work on Sybase

server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/EndpointLogger.java, server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/ProtocolServerService.java, server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RestService.java
https://issues.jboss.org/browse/ISPN-7913
The loggers output looks like this now:
```
14:57:43,579 INFO  [org.infinispan.server.endpoint] (MSC service thread 1-8) DGENDPT10000: HotRodServer starting
14:57:43,583 INFO  [org.infinispan.server.endpoint] (MSC service thread 1-8) DGENDPT10001: HotRodServer (TLS) listening on 127.0.0.1:11222
14:57:43,586 INFO  [org.infinispan.server.endpoint] (MSC service thread 1-5) DGENDPT10000: REST starting
14:57:43,717 INFO  [org.infinispan.server.endpoint] (MSC service thread 1-5) DGENDPT10002: REST (TLS) listening on 127.0.0.1:11222 (mapped to rest)
```
=> ISPN-7913 Unify logger outputs

all/embedded/pom.xml, bom/pom.xml, cloud/pom.xml, documentation/src/main/asciidoc/upgrading/upgrading.asciidoc, documentation/src/main/asciidoc/user_guide/cloud.adoc, parent/pom.xml, server/integration/feature-pack/pom.xml, server/integration/feature-pack/src/main/resources/modules/system/layers/base/org/jgroups/kubernetes/kubernetes/main/module.xml, wildfly-modules/build.xml, wildfly-modules/pom.xml, wildfly-modules/src/main/resources/org/jgroups/kubernetes/kubernetes/main/module.xml
https://issues.jboss.org/browse/ISPN-7924
https://issues.jboss.org/browse/ISPN-7928
This PR integrates the latest `KUBE_PING` into Infinispan. You may want to read [Bela's blog](http://belaban.blogspot.ch/2017/05/running-infinispan-cluster-with.html) to get the full spectrum of changes. The important from Infinispan perspective are:
* `KUBE_PING` has only 2 explicit dependencies now - JGroups and OAuth library.
* There is no need to use separate port for discovery (previously `KUBE_PING` used embedded HTTP for this).
* We don't need DMR (!!) dependency
* The new version of `KUBE_PING` uses only `KUBERNETES` prefixes for environmental variables. Previously it was possible to use either `KUBERNETES` or `OPENSHIFT`. This potentially impacts user apps deployed on *OpenShift* (apps deployed on …
=> Ispn 7924/upgrade kube ping

server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheDecodeContext.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodDecoder.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleClusteredNonLoopbackTest.java
https://issues.jboss.org/browse/ISPN-7814
* This check has proven to be not very effective.
* Instead, a more comprehensive default security configuration is needed
which is being worked on.
=> ISPN-7814 Remove protected cache security check

core/src/main/java/org/infinispan/eviction/impl/PassivationManagerImpl.java, core/src/main/java/org/infinispan/interceptors/impl/CacheWriterInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/DistCacheWriterInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/TransactionalStoreInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/TxBatchUpdater.java, core/src/main/java/org/infinispan/persistence/async/AsyncCacheWriter.java, core/src/main/java/org/infinispan/persistence/file/SingleFileStore.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManager.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerStub.java, core/src/main/java/org/infinispan/persistence/modifications/Modification.java, core/src/main/java/org/infinispan/persistence/spi/AdvancedCacheWriter.java, core/src/main/java/org/infinispan/persistence/spi/CacheWriter.java, core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java, core/src/test/java/org/infinispan/persistence/BaseStoreTest.java, persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/logging/Log.java, persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java, persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/table/management/PostgresTableManager.java, persistence/jpa/src/main/java/org/infinispan/persistence/jpa/JpaStore.java, persistence/jpa/src/main/java/org/infinispan/persistence/jpa/impl/Stats.java, persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
https://issues.jboss.org/browse/ISPN-5218
https://issues.jboss.org/browse/ISPN-7901
I have added the `writeBatch` and `deleteBatch` methods to the `CacheWriter` interface opposed to the `AdvancedCacheWriter` as the `DelegatingCacheWriter` implements the former. Both of these are implemented as default methods in the interface, which fall back to sequentially calling write/delete if a store is unable to perform batch write and/or delete operations.
=> ISPN-5218 Add batching to the CacheWriter Interface

bom/pom.xml, server/integration/feature-pack/pom.xml, server/integration/feature-pack/src/main/resources/modules/system/layers/base/org/jboss/marshalling/river/main/module.xml, server/integration/testsuite/pom.xml, server/integration/versions/pom.xml
* JBoss Marshalling's River jar version needs to be aligned with the
JBoss Marshalling API jar.
https://issues.jboss.org/browse/ISPN-7652
=> [8.2.x] ISPN-7652 Align River marshaller version

jcache/commons/pom.xml, jcache/embedded/pom.xml, jcache/remote/pom.xml, spring/spring4/spring4-common/pom.xml, spring/spring4/spring4-embedded/pom.xml, spring/spring4/spring4-remote/pom.xml
https://issues.jboss.org/browse/ISPN-7930
* Some of the provided dependencies were added to avoid issues with uber
jars, but these uber jars are not really designed for Maven-like envs.
* Having these provided dependencies forces users to define the provided
dependencies on top which is a usability issue.
* So this JIRA reverts these provided dependencies since users should
not be relying on uber jars as dependencies.
=> ISPN-7930 Avoid provided deps unless necessary

distribution/package.xml, distribution/pom.xml, distribution/src/main/resources/licenses/antlr-bsd.txt, distribution/src/main/resources/licenses/apache license, version 2.0.txt, distribution/src/main/resources/licenses/bsd-license.txt, distribution/src/main/resources/licenses/cc0-1.0.txt, distribution/src/main/resources/licenses/cddl-1.1-gpl-1-1.txt, distribution/src/main/resources/licenses/cddl-gplv2-classpath.txt, distribution/src/main/resources/licenses/cddl.txt, distribution/src/main/resources/licenses/epl-1.0.txt, distribution/src/main/resources/licenses/gpl-2.0-ce.txt, distribution/src/main/resources/licenses/indiana university extreme! lab software license, vesion 1.1.1 - license.txt, distribution/src/main/resources/licenses/lgpl-2.1.txt, distribution/src/main/resources/licenses/mit.txt, distribution/src/main/resources/licenses/mpl-1.1.txt, distribution/src/main/resources/licenses/xstream-bsd.txt, distribution/src/main/resources/template/licenses.css, distribution/src/main/resources/template/licenses.xsl
This is a blocker for release (required by legal).
The format of the generated license descriptor and table has also been set by legal.
This is what it looks like: http://www.dataforte.net/listing/infinispan/licenses/licenses.html
=> ISPN-7979 Add licenses to distributions

core/src/main/java/org/infinispan/commands/tx/AbstractTransactionBoundaryCommand.java, core/src/main/java/org/infinispan/commands/tx/PrepareCommand.java, core/src/main/java/org/infinispan/commands/tx/totalorder/TotalOrderCommitCommand.java, core/src/main/java/org/infinispan/commands/tx/totalorder/TotalOrderNonVersionedPrepareCommand.java, core/src/main/java/org/infinispan/commands/tx/totalorder/TotalOrderRollbackCommand.java, core/src/main/java/org/infinispan/commands/tx/totalorder/TotalOrderVersionedCommitCommand.java, core/src/main/java/org/infinispan/commands/tx/totalorder/TotalOrderVersionedPrepareCommand.java, core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/TxInterceptor.java, core/src/main/java/org/infinispan/interceptors/locking/PessimisticLockingInterceptor.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/statetransfer/OutdatedTopologyException.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/main/java/org/infinispan/transaction/impl/LocalTransaction.java, core/src/main/java/org/infinispan/transaction/impl/TransactionTable.java, core/src/test/java/org/infinispan/partitionhandling/BaseTxPartitionAndMergeTest.java, core/src/test/java/org/infinispan/statetransfer/ReplCommandForwardingTest.java, core/src/test/java/org/infinispan/tx/PrepareProcessedAfterOriginatorCrashTest.java, core/src/test/java/org/infinispan/tx/exception/TxAndTimeoutExceptionTest.java
https://issues.jboss.org/browse/ISPN-6997
https://issues.jboss.org/browse/ISPN-7960
* Handle lock failures with a regular rollback command.
* Don't send TxCompletionNotificationCommands from
PessimisticLockingInterceptor.
* Add lock recipients to the affected nodes even in case of failure.
* Send commit/rollback to all affected nodes, even if the cache
topology did not change.
* Do not change protocols when the cluster changes size 
* Do not create a remote transaction when the originator is not a
cluster member.
* Remove the originator check in TxInterceptor.
=> ISPN-6997 PessimisticTxPartitionAndMergeDuringRuntimeTest.testOriginatorIsolatedPartition random failures

server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodDecoder.java
https://issues.jboss.org/browse/ISPN-8006
* To avoid logging too long key/values
=> ISPN-8006 Key/value bodies should use printArray

core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java, core/src/test/java/org/infinispan/test/fwk/TestResourceTracker.java
https://issues.jboss.org/browse/ISPN-8036
May fix the random distexec failures in CI.
=> ISPN-8036 TestResourceTracker keeps cache managers alive

core/src/main/java/org/infinispan/distribution/LocalizedCacheTopology.java, core/src/main/java/org/infinispan/distribution/ch/ConsistentHash.java, core/src/main/java/org/infinispan/interceptors/distribution/NonTxDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/distribution/TriangleDistributionInterceptor.java
The distribution interceptors assume all segments have
CH.getNumOwners() owners, but in a union CH that's not true.
https://issues.jboss.org/browse/ISPN-7998
=> ISPN-7998 Multi-key write commands don't work with union CHs

core/src/main/java/org/infinispan/partitionhandling/package-info.java, core/src/main/java/org/infinispan/persistence/spi/CacheWriter.java, documentation/src/main/asciidoc/user_guide/clustering.adoc
https://issues.jboss.org/browse/ISPN-8064
=> Javadoc fixes

core/src/test/java/org/infinispan/xsite/statetransfer/failures/SiteConsumerTopologyChangeTest.java, core/src/test/java/org/infinispan/xsite/statetransfer/failures/SiteProviderTopologyChangeTest.java
* The tests are unstable and they are tracked by ISPN-6228
=> Disable SiteConsumer/ProviderTopologyChangeTests

query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java, query/src/main/java/org/infinispan/query/backend/QueryKnownClasses.java, query/src/main/java/org/infinispan/query/backend/SearchWorkCreator.java, query/src/main/java/org/infinispan/query/impl/DefaultSearchWorkCreator.java, query/src/test/java/org/infinispan/query/backend/QueryInterceptorTest.java
https://issues.jboss.org/browse/ISPN-7990
=> ISPN-7990 Provide a way to remove an entry from all indexes

core/src/main/java/org/infinispan/container/entries/AbstractInternalCacheEntry.java, core/src/main/java/org/infinispan/container/entries/CacheEntry.java, core/src/main/java/org/infinispan/container/entries/ClearCacheEntry.java, core/src/main/java/org/infinispan/container/entries/ForwardingCacheEntry.java, core/src/main/java/org/infinispan/container/entries/NullCacheEntry.java, core/src/main/java/org/infinispan/container/entries/ReadCommittedEntry.java, core/src/main/java/org/infinispan/util/CoreImmutables.java, core/src/test/java/org/infinispan/test/fwk/CacheEntryDelegator.java
https://issues.jboss.org/browse/ISPN-8085
* Add default implementations to isLoaded/setLoaded and removing
existing stubs, too.
=> ISPN-8085 Deprecate CacheEntry.isValid/setValid

core/src/main/java/org/infinispan/util/logging/Log.java, core/src/main/java/org/infinispan/xsite/BackupFailureException.java, core/src/main/java/org/infinispan/xsite/BaseBackupReceiver.java, core/src/test/java/org/infinispan/xsite/backupfailure/tx/BaseBackupTxFailureTest.java, core/src/test/java/org/infinispan/xsite/backupfailure/tx/CustomFailurePolicyTxTest.java
https://issues.jboss.org/browse/ISPN-4038
=> ISPN-4038 CustomFailurePolicyTxTest.testPrepareFailure random failures

core/src/test/java/org/infinispan/tx/TransactionXaAdapterTmIntegrationTest.java
The original Jira has already been closed although this test hadn't been fixed.
=> ISPN-1123 Fix and re-enable TransactionXaAdapterTmIntegrationTest

core/src/test/java/org/infinispan/distribution/rehash/NonTxPutIfAbsentDuringJoinStressTest.java
* JIRA ISPN-3918 (fails in both cache modes)
=> Disable NonTxPutIfAbsentDuringJoinStressTest

core/src/test/java/org/infinispan/partitionhandling/BaseTxPartitionAndMergeTest.java, core/src/test/java/org/infinispan/partitionhandling/OptimisticTxPartitionAndMergeDuringCommitTest.java
wrong assumption during when writing the test make it fail randomly.
the transaction is committed in the majority partition and checking and the locks are released. checking for locks during the split can fail depending if the locks are still acquired or not (locks are released asynchronously)
=> Fix OptimisticTxPartitionAndMergeDuringCommitTest

commons/src/main/java/org/infinispan/commons/util/ClassFinder.java
https://issues.jboss.org/browse/ISPN-8183
Change the rules for whether a classpath element belongs to Infinispan:
for files, the file name should contain "infinispan",
and for directories, they should have a subdirectory "org/infinispan".
=> ISPN-8183 ClassFinder logs lots of warnings in CI

core/src/main/java/org/infinispan/commands/read/SizeCommand.java, core/src/test/java/org/infinispan/eviction/impl/MarshalledValuesEvictionTest.java, core/src/test/java/org/infinispan/eviction/impl/MarshalledValuesManualEvictionTest.java
https://issues.jboss.org/browse/ISPN-8189
https://issues.jboss.org/browse/ISPN-4042
Also resurrects the MarshalledValuesEvictionTest to count marshalls/unmarshalls (to ensure we don't get spurious/unexpected ones).
=> ISPN-8189 Use IdentityEncoder in SizeCommand to avoid unmarshalling keys

server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedClusteredStatsTest.java
https://issues.jboss.org/browse/ISPN-5170
I've fixed the mbean name and re-enabled the test. I've run it in a loop locally for a couple of hourse and I haven't had it fail once...
=> ISPN-5170 Re-enable MemcachedClusteredStatsTest

core/src/main/java/org/infinispan/persistence/file/SingleFileStore.java, core/src/test/java/org/infinispan/persistence/file/SingleFileStoreStressTest.java
https://issues.jboss.org/browse/ISPN-8150
=> ISPN-8150 SingleFileStoreStressTest intermittent failure

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java, jcache/commons/src/test/java/org/infinispan/jcache/AbstractTwoCachesAnnotationsTest.java, jcache/commons/src/test/java/org/infinispan/jcache/AbstractTwoCachesBasicOpsTest.java, jcache/commons/src/test/java/org/infinispan/jcache/AbstractTwoCachesExpirationTest.java, jcache/commons/src/test/java/org/infinispan/jcache/JCacheAnnotatedClass.java, jcache/remote/src/test/java/org/infinispan/jcache/remote/JCacheTwoCachesBasicOpsTest.java, jcache/remote/src/test/java/org/infinispan/jcache/remote/JCacheTwoCachesExpirationTest.java
- Moved all remote tests into the "remote" package
- Use test-specific keys and values
- Remove listeners even in case of failures
- Fixed naming and added more debug information
=> ISPN-6952 Improve the JCacheTwoCachesBasicOpsTest

integrationtests/osgi/pom.xml, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/BasicInfinispanOSGiTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/features/OSGiKarafFeaturesTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/file/SingleFileStoreFunctionalTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/jdbc/configuration/XmlFileParsingTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/jdbc/stringbased/JdbcStringBasedStoreFunctionalTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/jdbc/stringbased/JdbcStringBasedStoreManagedFactoryFunctionalTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/jpa/JpaConfigurationTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/jpa/JpaStoreFunctionalTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/jpa/JpaStorePersonEntityTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/jpa/JpaStoreTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/jpa/JpaStoreUserEntityTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/jpa/JpaStoreVehicleEntityTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/remote/RemoteStoreFunctionalTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/persistence/rocksdb/RocksDBStoreFunctionalTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/tx/CustomObjectsReplicatedCacheTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/tx/TransactionsSpanningReplicatedCachesTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/util/SuiteCategory.java, parent/pom.xml, server/integration/versions/pom.xml
- Upgrade to Pax Exam 4.11
- Split testsuite into 3 minisuites to avoid the surefire container dying
NB. This doesn't fix the OSGi test issues completely but at least it makes it run completely
https://issues.jboss.org/browse/ISPN-8177
=> ISPN-8177 OSGi testsuite improvements

core/src/main/java/org/infinispan/stream/impl/AbstractCacheStream.java, core/src/main/java/org/infinispan/stream/impl/ClusterStreamManager.java, core/src/main/java/org/infinispan/stream/impl/ClusterStreamManagerImpl.java, core/src/main/java/org/infinispan/stream/impl/DistributedCacheStream.java, core/src/main/java/org/infinispan/stream/impl/PartitionAwareClusterStreamManager.java, core/src/main/java/org/infinispan/stream/impl/tx/TxClusterStreamManager.java
https://issues.jboss.org/browse/ISPN-8218
Reverts most of the stream related changes from ISPN-6645, fixing the
consistent hash instance used for both remote and local iteration. The
retry with newer topology is moved to xCacheStream instead.
Non-rehash-aware iteration through scattered cache may miss segments
that don't have owner during rehash.
=> ISPN-8218 ScatteredStreamIteratorTest.waitUntilProcessingResults random failure

counter/src/main/java/org/infinispan/counter/configuration/CounterConfigurationParser.java, counter/src/main/resources/schema/infinispan-counters-config-9.1.xsd, counter/src/test/resources/config/counters.xml, counter/src/test/resources/config/invalid.xml
The schema version of clustered counter remained at 9.0, so I updated it to 9.1.
https://github.com/infinispan/infinispan/blob/9.1.0.Final/counter/src/main/resources/schema/infinispan-counters-config-9.0.xsd
=> updated the schema version of clustered counter to 9.1

core/src/test/java/org/infinispan/distexec/BasicDistributedExecutorTest.java, core/src/test/java/org/infinispan/distexec/DistributedExecutorTest.java, core/src/test/java/org/infinispan/distexec/LocalDistributedExecutorTest.java, core/src/test/java/org/infinispan/test/fwk/TestClassLocal.java
https://issues.jboss.org/browse/ISPN-8248
Use a latch instead of Thread.sleep().
=> ISPN-8248 Missing timeout exceptions in distributed executor tests

core/src/main/java/org/infinispan/container/DefaultDataContainer.java, core/src/main/java/org/infinispan/stream/impl/TerminalFunctions.java, core/src/main/java/org/infinispan/stream/impl/local/EntryStreamSupplier.java, hibernate-cache/src/main/java/org/infinispan/hibernate/cache/access/InvalidationSynchronization.java, hibernate-cache/src/main/java/org/infinispan/hibernate/cache/access/PutFromLoadValidator.java, hibernate-cache/src/main/java/org/infinispan/hibernate/cache/access/TombstoneCallInterceptor.java, hibernate-cache/src/main/java/org/infinispan/hibernate/cache/access/VersionedCallInterceptor.java, hibernate-cache/src/main/java/org/infinispan/hibernate/cache/util/Tombstone.java, hibernate-cache/src/main/java/org/infinispan/hibernate/cache/util/VersionedEntry.java, hibernate-cache/src/test/java/org/infinispan/test/hibernate/cache/AbstractRegionAccessStrategyTest.java, hibernate-cache/src/test/java/org/infinispan/test/hibernate/cache/functional/BulkOperationsTest.java, hibernate-cache/src/test/java/org/infinispan/test/hibernate/cache/util/ExpectingInterceptor.java
A bunch of fixes to avoid the following problems:
* Async puts from tests that linger affecting other tests. This applies to both remove put from load calls, and remove end invalidation calls.
* Wait for end invalidation and putFromLoad calls before asserting cache size. Although cache gets might work fine, getting an accurate size count requires all remote ops to end well, so that streams can be correctly processed, filtered and counted.
=> ISPN-8026 Size related fixes in Hibernate Cache tests

core/src/test/java/org/infinispan/stream/LocalStreamIteratorWithPassivationTest.java
* Disabled test as we don't support concurrent activation with iteration
https://issues.jboss.org/browse/ISPN-8174
=> ISPN-8174 LocalStreamIteratorWithPassivationTest random failures

core/src/test/java/org/infinispan/manager/AllClusterExecutorTest.java, core/src/test/java/org/infinispan/test/TestingUtil.java
SingleClusterExecutorTest.testExecutorTriConsumerTimeoutException random
failures
* Invoke expiration manager event immediately to symbolize expiration
https://issues.jboss.org/browse/ISPN-8155
=> ISPN-8155 SingleClusterExecutorTest.testExecutorTriConsumerTimeoutException

core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java
randomly
* Added null check in case if expired entry is removed at same time
https://issues.jboss.org/browse/ISPN-8280
=> ISPN-8280 RemoteStoreRawValuesTest.testStopStartDoesNotNukeValues fails

bom/pom.xml, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/JBMARRemoteQueryDslConditionsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDslConditionsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDslConditionsTunedTest.java, integrationtests/as-lucene-directory/pom.xml, lucene/directory-provider/src/test/java/org/infinispan/hibernate/search/ClusterTestHelper.java, lucene/directory-provider/src/test/java/org/infinispan/hibernate/search/sharedIndex/SharedIndexTest.java, query/src/main/java/org/infinispan/query/impl/massindex/MassIndexStrategyFactory.java, query/src/test/java/org/infinispan/query/backend/MultipleEntitiesTest.java, query/src/test/java/org/infinispan/query/backend/QueryInterceptorIndexingOperationsTest.java, query/src/test/java/org/infinispan/query/config/DeclarativeConfigTest.java, query/src/test/java/org/infinispan/query/config/MultipleCachesTest.java, query/src/test/java/org/infinispan/query/dsl/embedded/ClusteredQueryDslConditionsTest.java, query/src/test/java/org/infinispan/query/dsl/embedded/QueryDslConditionsTest.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/RemoteQueryEngine.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/ProtobufValueWrapper.java, wildfly-modules/build.xml, wildfly-modules/pom.xml
https://issues.jboss.org/browse/ISPN-8302
N.B. The modules released by Hibernate Search are now aiming for WildFly 11 as primary targed. I see no reason for them not to work on WildFly 10 though.
Hibernate ORM also released modules compatible with WildFly 11; in that case those modules are not going to work on WildFly 10, so I'm intentionally not following up with an update of the Hibernate ORM component until Infinispan updates its target WildFly version as well.
=> Hibernate Search 5.8.0.Final

core/src/main/java/org/infinispan/container/offheap/BoundedOffHeapDataContainer.java, core/src/test/java/org/infinispan/container/offheap/OffHeapBoundedSingleNodeTest.java
long
* Replaced yield with lock acquisition and retry
https://issues.jboss.org/browse/ISPN-8110
This should help resolve timeout issues in test when TRACE is enabled.
=> ISPN-8110 OffHeapBoundedDataContainer.ensureSize() busy loop takes too

core/src/test/java/org/infinispan/container/offheap/OffHeapBoundedSingleNodeTest.java, core/src/test/java/org/infinispan/container/offheap/OffHeapMultiNodeTest.java, core/src/test/java/org/infinispan/container/offheap/OffHeapSingleNodeTest.java
trace logging enabled
* Disabled transactions which should let it run faster
https://issues.jboss.org/browse/ISPN-8111
=> ISPN-8111 OffHeapBoundedSingleNodeTest.testMultiThreaded fails with

core/src/test/java/org/infinispan/partitionhandling/OptimisticTxPartitionAndMergeDuringCommitTest.java, core/src/test/java/org/infinispan/partitionhandling/PessimisticTxPartitionAndMergeDuringPrepareTest.java
https://issues.jboss.org/browse/ISPN-8305
Also, disabled some tests that may hit https://issues.jboss.org/browse/ISPN-8232
=> ISPN-8305 PessimisticTxPartitionAndMergeDuringPrepareTest.testPrimaryOwnerIsolatedPartitionWithDiscard[DIST_SYNC] randomly failing

hibernate-cache/src/main/java/org/infinispan/hibernate/cache/util/Tombstone.java, hibernate-cache/src/test/java/org/infinispan/test/hibernate/cache/AbstractRegionAccessStrategyTest.java, hibernate-cache/src/test/java/org/infinispan/test/hibernate/cache/functional/AbstractFunctionalTest.java, hibernate-cache/src/test/java/org/infinispan/test/hibernate/cache/functional/BulkOperationsTest.java, hibernate-cache/src/test/java/org/infinispan/test/hibernate/cache/functional/cluster/NaturalIdInvalidationTest.java
https://issues.jboss.org/browse/ISPN-8263
Marking this as preview to get a few CI runs to verify this is working fine.
I've been running the full Hibernate Cache testsuite with TRACE for a day in one of the CI machines and has not failed again, but I want to leave it over the weekend to run and see whether anything else fails.
=> ISPN-8263 Taming Hibernate Cache size related random failures

Jenkinsfile, parent/pom.xml
Archive the dump/dumpstream files generated by Surefire
Log the correct thread name after we call Thread.setName()
=> Jenkins logs/artifacts improvements

core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java, core/src/test/java/org/infinispan/eviction/impl/EvictionFunctionalTest.java
* evict now takes into account configured Flags
https://issues.jboss.org/browse/ISPN-8322
=> ISPN-8322 Cache.evict(...) ignores Flag.SKIP_LISTENER_NOTIFICATION

core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java, core/src/test/java/org/infinispan/api/APINonTxTest.java, core/src/test/java/org/infinispan/eviction/impl/EvictionFunctionalTest.java, core/src/test/java/org/infinispan/notifications/CacheListenerCacheLoaderTest.java
an eviction listener is present
* Use regular for loop instead of Collectors
https://issues.jboss.org/browse/ISPN-8323
=> ISPN-8323 Cache.evict(...) throws NPE if entry was already evicted and

Jenkinsfile
The previous solution was missing "Error occurred in starting fork"
messages.
=> SUREFIRE-1426 Find all fork errors in the build output

core/src/main/java/org/infinispan/CacheStream.java, core/src/main/java/org/infinispan/filter/CacheFilters.java, core/src/main/java/org/infinispan/stream/impl/IntermediateCacheStream.java, core/src/main/java/org/infinispan/stream/impl/local/LocalCacheStream.java, core/src/main/java/org/infinispan/util/Casting.java, core/src/test/java/org/infinispan/stream/BaseSetupStreamIteratorTest.java, core/src/test/java/org/infinispan/stream/BaseStreamIteratorEvictionTest.java, core/src/test/java/org/infinispan/stream/BaseStreamIteratorTest.java, core/src/test/java/org/infinispan/stream/BaseStreamTest.java, core/src/test/java/org/infinispan/stream/DistributedStreamIteratorTxTest.java, core/src/test/java/org/infinispan/stream/stress/DistributedStreamRehashStressTest.java, documentation/src/main/asciidoc/user_guide/streams.adoc, server/integration/testsuite/src/test/java/org/infinispan/server/test/task/servertask/LocalMapReduceServerTask.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/BinaryOutputPrinter.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/JSONOutputPrinter.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/XMLOutputPrinter.java
https://issues.jboss.org/browse/ISPN-8281
Replaces #5421 and #5440.
* Use casting to deal with inner type generic casting issues.
* Add collect(Supplier) version that doesn't rely on standard
serialization requirements to marshall the function.
* Add CacheFilters.filterAndConvert method that takes and returns
CacheStream instead of Stream.
* Force more info into method references in test.
* Add javadocs.
I've rebased and fixed things reported in both #5421 and #5440 except for docu.
=> ISPN-8281 Overloaded collect() to take SerializableSupplier

Jenkinsfile, commons-test/pom.xml, commons-test/src/main/java/org/infinispan/commons/test/JUnitTestListener.java, commons-test/src/main/java/org/infinispan/commons/test/TestNGTestListener.java, commons-test/src/main/java/org/infinispan/commons/test/TestSuiteProgress.java, commons/pom.xml
https://issues.jboss.org/browse/ISPN-8414
=> ISPN-8414 Colored testsuite progress

commons/src/main/java/org/infinispan/commons/util/GlobUtils.java, core/src/main/java/org/infinispan/configuration/ConfigurationManager.java, core/src/main/java/org/infinispan/configuration/parsing/Parser.java, core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java, documentation/src/main/asciidoc/user_guide/configuration.adoc, jcache/embedded/src/main/java/org/infinispan/jcache/embedded/ConfigurationAdapter.java, jcache/embedded/src/main/java/org/infinispan/jcache/embedded/JCacheManager.java, jcache/embedded/src/test/java/org/infinispan/jcache/JCacheConfigurationTest.java, jcache/embedded/src/test/resources/infinispan_uri.xml
https://issues.jboss.org/browse/ISPN-8379
=> ISPN-8379 Support configuration wildcards

server/integration/feature-pack/feature-pack-build.xml, server/integration/feature-pack/src/main/resources/configuration/standalone/subsystems-services.xml, server/integration/infinispan/src/main/resources/subsystem-templates/infinispan-core.xml
https://issues.jboss.org/browse/ISPN-8430
@slaskawi I think this is all we need for now. This way we can just pass "services" as an argument to docker and we will only have to remove the "shared-memory-service" or "caching-service" template via the cli script depending on the mode we're operating.
=> ISPN-8430 Create Online Service Configuration Templates

persistence/jpa/pom.xml, pom.xml
https://issues.jboss.org/browse/ISPN-8444
This was caused by the fact that the features.xml file for JPA cache store was not generated properly as the maven plugins use filtering and they couldn't see the javax.persistence property.
=> ISPN-8444 JPA cache store failed to deploy in OSGi

commons/src/main/java/org/infinispan/commons/util/ClassFinder.java
Change the rules for whether a classpath element belongs to Infinispan:
for files, the file name should contain "infinispan",
and for directories, they should have a subdirectory "org/infinispan".
https://issues.jboss.org/browse/ISPN-8183
=> [9.0] ISPN-8183 ClassFinder logs lots of warnings in CI

commons/src/main/java/org/infinispan/commons/util/ClassFinder.java
Change the rules for whether a classpath element belongs to Infinispan:
for files, the file name should contain "infinispan",
and for directories, they should have a subdirectory "org/infinispan".
https://issues.jboss.org/browse/ISPN-8183
=> [8.1] ISPN-8183 ClassFinder logs lots of warnings in CI

integrationtests/pom.xml
The only downside to this fix is that we have to have the compiler settings explicit on the integration-tests pom.
=> ISPN-8408 integrationtests-parent no longer users pom inheritance

core/src/main/java/org/infinispan/partitionhandling/impl/PartitionHandlingInterceptor.java, core/src/test/java/org/infinispan/partitionhandling/BaseOptimisticTxPartitionAndMergeTest.java, core/src/test/java/org/infinispan/test/Exceptions.java
https://issues.jboss.org/browse/ISPN-8448
Updated to throw the AvailabilityException *before* sending the prepare command remotely.
After a CacheNotFoundResponse, the AvailabilityException is sent during the retry.
Opened ISPN-8453 to deal more directly with CacheNotFoundResponses.
Please cherry-pick to 9.1.x as well.
=> ISPN-8448 Retried prepare times out while partition is in degraded mode

core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
SuspectException
* Only register listeners with addresses that have this cache
* Cache could be stopped concurrently, so ignore SuspectException
https://issues.jboss.org/browse/ISPN-8504
=> ISPN-8504 View change during cluster listener registration can throw

Jenkinsfile, build.sh, etc/log4j2.xml, integrationtests/all-remote-it/src/test/resources/arquillian.xml, integrationtests/as-lucene-directory/src/test/resources/arquillian.xml, integrationtests/osgi/pom.xml, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/util/IspnKarafOptions.java, integrationtests/pom.xml, integrationtests/security-it/src/test/resources/arquillian.xml, integrationtests/wildfly-modules/pom.xml, integrationtests/wildfly-modules/src/test/resources/arquillian.xml, jcache/tck-runner/pom.xml, pom.xml, server/integration/testsuite/pom.xml, server/integration/versions/pom.xml
https://issues.jboss.org/browse/ISPN-8478
Since I first opened the PR, the ANSI escape codes in test suite output which were causing the OSGi tests OOME have been reverted.
So I've changed the target of the PR to get the build running on the new agents that only have 4GB of RAM.
=> ISPN-8478 Reduce build memory usage

core/src/main/java/org/infinispan/container/offheap/BoundedOffHeapDataContainer.java, core/src/main/java/org/infinispan/container/offheap/OffHeapLruNode.java, core/src/test/java/org/infinispan/container/offheap/OffHeapBoundedMemoryTest.java
memory block
* Memory count doesn't require separate amount for lru nodes anymore
https://issues.jboss.org/browse/ISPN-8409
=> ISPN-8409 Change off heap eviction to store everything in same allocated

core/src/main/java/org/infinispan/conflict/impl/DefaultConflictManager.java, core/src/main/java/org/infinispan/conflict/impl/StateReceiverImpl.java
Deadlock caused by StateReceiverImpl::stop synchronizing on
StateReceiverImpl.this, but then attempting to cancel a
StateRequestImpl.SegmentRequest whoms cancel() method synchs on itself.
However, a SegmentRequest can also be cancelled by another thread
when a CompletableFuture completes exceptionally. This results in
Thread-A acquiring StateReceiverImpl.this in StateReceiverImpl::stop and
calling SegmentRequest::cancel, however Thread-B has called SegmentRequest::cancel and
is now waiting to synchronize on StateReceiverImpl.this, hence deadlock.
Also, we shouldn't call StateReceiverImpl::stop in the
DefaultConflictManager.ReplicaSpliterator::tryAdvance when a
Cancellation/Execution Exception occurs as failed requests are already
cancelled on an exception in StateReceiverImpl. …
=> ISPN-8538 TwoWaySplitAndMerge[DIST_SYNC] deadlock in conflict resolution

core/src/main/java/org/infinispan/interceptors/locking/ClusteringDependentLogic.java
all entries locally
https://issues.jboss.org/browse/ISPN-8548
=> ISPN-8548 Clear post notifications can cause memory issues as it holds

core/src/main/java/org/infinispan/container/DefaultDataContainer.java, core/src/main/java/org/infinispan/container/offheap/OffHeapDataContainer.java, core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactory.java, core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactoryImpl.java, core/src/test/java/org/infinispan/eviction/impl/EvictionWithPassivationTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
* Reuse address pointer for compute remove
* Don't resurrect value if not needed
https://issues.jboss.org/browse/ISPN-8517
https://issues.jboss.org/browse/ISPN-8500
This issue now also includes objects that are expired are not read.
=> ISPN-8517 Lazily ressurect ice fromMemory

core/src/main/java/org/infinispan/configuration/cache/ConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/MemoryConfigurationBuilder.java, core/src/main/java/org/infinispan/container/offheap/BoundedOffHeapDataContainer.java, core/src/main/java/org/infinispan/container/offheap/MemoryAddressHash.java, core/src/main/java/org/infinispan/container/offheap/OffHeapDataContainer.java, core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactory.java, core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactoryImpl.java, core/src/main/java/org/infinispan/container/offheap/OffHeapMemoryAllocator.java, core/src/main/java/org/infinispan/container/offheap/UnpooledOffHeapMemoryAllocator.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/container/offheap/OffHeapBoundedMemoryTest.java, core/src/test/java/org/infinispan/eviction/impl/MemoryBasedEvictionFunctionalStoreAsBinaryTest.java, core/src/test/java/org/infinispan/eviction/impl/MemoryBasedEvictionFunctionalTest.java, server/rest/src/test/java/org/infinispan/rest/BaseRestOperationsTest.java, server/rest/src/test/java/org/infinispan/rest/RestOperationsOffHeapTest.java, server/rest/src/test/java/org/infinispan/rest/RestOperationsTest.java
* Add address count to memory based eviction count
* Align sizes of off heap to 8 bytes
* Also changed allocated count to LongAdder
* Fixed issue that MemoryConfiguration wasn't being validated
https://issues.jboss.org/browse/ISPN-8534
https://issues.jboss.org/browse/ISPN-8545
https://issues.jboss.org/browse/ISPN-8550
=> ISPN-8534 Make off heap memory based eviction a better estimation

server/rest/src/test/java/org/infinispan/rest/RestOperationsTest.java
Extracted the test from https://github.com/infinispan/infinispan/pull/5608 for master
https://github.com/infinispan/infinispan/pull/5608
=> ISPN-8557 Test that REST can delete entries created directly

core/src/test/java/org/infinispan/tx/totalorder/statetransfer/TotalOrderStateTransferFunctionalTest.java
Backport from master.
Do not close the issue.
=> [9.1.x] JGRP-2233 Mark TotalOrderStateTransferFunctionalTest unstable

integrationtests/osgi/src/test/java/org/infinispan/it/osgi/BasicInfinispanOSGiTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/features/OSGiKarafFeaturesTest.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/util/CustomPaxExamRunner.java, integrationtests/osgi/src/test/java/org/infinispan/it/osgi/util/IspnKarafOptions.java
https://issues.jboss.org/browse/ISPN-8516
Kill per-suite Karaf container in a shutdown hook.
Please cherry-pick to 9.1.x as well.
=> ISPN-8516 OSGI integration tests random failure listening to RMI port

server/memcached/src/main/java/org/infinispan/server/memcached/TextProtocolUtil.java, server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedFunctionalTest.java
https://issues.jboss.org/browse/ISPN-8594
=> ISPN-8594 Memcached not finding UTF-8 data 

core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
https://issues.jboss.org/browse/ISPN-8631
=> ISPN-8631 GetAllCacheNotFoundResponseTest.createBeforeClass fails

javadoc/javadoc-all/pom.xml, javadoc/javadoc-embedded/pom.xml, javadoc/javadoc-remote/pom.xml, pom.xml
https://issues.jboss.org/browse/ISPN-8629
* Configure maven-javadoc-plugin with detectOfflineLinks=false
* Add explicit dependency on the tools module in the javadoc modules
=> ISPN-8629 Javadoc modules' build invokes a new instance of Maven

core/src/main/java/org/infinispan/distribution/LocalizedCacheTopology.java, core/src/main/java/org/infinispan/partitionhandling/impl/PreferAvailabilityStrategy.java, core/src/main/java/org/infinispan/statetransfer/StateTransferManager.java, core/src/main/java/org/infinispan/stream/impl/LocalStreamManagerImpl.java, core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java, core/src/test/java/org/infinispan/distribution/TestAddress.java, core/src/test/java/org/infinispan/manager/CacheManagerTest.java, core/src/test/java/org/infinispan/remoting/transport/MockTransport.java, core/src/test/java/org/infinispan/topology/ClusterTopologyManagerImplTest.java, core/src/test/java/org/infinispan/topology/MockLocalTopologyManager.java
https://issues.jboss.org/browse/ISPN-8555
https://issues.jboss.org/browse/ISPN-8587
Backport of https://github.com/infinispan/infinispan/pull/5617
The main difference is that `IntSet` doesn't exist in 9.1, so I'm using `Collections.unmodifiableSet()` instead of backporting `ImmutableIntSet`.
=>  ISPN-8555 Fix deadlock in CacheManagerTest

lock/src/main/java/org/infinispan/lock/impl/lock/ClusteredLockImpl.java, lock/src/test/java/org/infinispan/lock/impl/lock/ClusteredLockImplTest.java
https://issues.jboss.org/browse/ISPN-8615
https://issues.jboss.org/browse/ISPN-8581
=> Fix test and trace log message

core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
https://issues.jboss.org/browse/ISPN-8710
`start()` accidentally overrode method in ExpirationManagerImpl and the expiration task was not scheduled.
=> ISPN-8710 JCacheTwoCachesExpirationTest.testExpiration failures

hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/PutFromLoadValidator.java
rearrange constructor to avoid race condition leading to NPE in beginInvalidatingWithPFER
=> ISPN-8721 rearrange constructor to avoid race condition

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdmin.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheManagerAdminImpl.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java, commons/src/main/java/org/infinispan/commons/api/CacheContainerAdmin.java, commons/src/main/java/org/infinispan/commons/configuration/BasicConfiguration.java, commons/src/main/java/org/infinispan/commons/configuration/XMLStringConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/Configuration.java, core/src/main/java/org/infinispan/configuration/parsing/ParserRegistry.java, core/src/main/java/org/infinispan/manager/CacheContainer.java, core/src/main/java/org/infinispan/manager/EmbeddedCacheManagerAdmin.java, jcache/remote/src/main/java/org/infinispan/jcache/remote/JCacheManager.java, server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/CacheCreateTask.java, server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/CacheGetOrCreateTask.java, server/core/src/main/java/org/infinispan/server/core/logging/Log.java
https://issues.jboss.org/browse/ISPN-8695
=> ISPN-8695 Create remote caches using the XML configuration

core/src/main/java/org/infinispan/configuration/cache/Configurations.java, core/src/main/java/org/infinispan/configuration/cache/MemoryConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/MemoryConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/parsing/Parser.java, core/src/main/java/org/infinispan/configuration/serializing/Serializer.java, core/src/main/java/org/infinispan/eviction/EvictionStrategy.java, core/src/main/java/org/infinispan/eviction/EvictionType.java, core/src/main/java/org/infinispan/factories/DataContainerFactory.java, core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java, core/src/main/java/org/infinispan/factories/SizeCalculatorFactory.java, core/src/main/java/org/infinispan/interceptors/impl/ContainerFullException.java, core/src/main/java/org/infinispan/interceptors/impl/TransactionalExceptionEvictionInterceptor.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/main/resources/schema/infinispan-config-9.2.xsd, core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java, core/src/test/java/org/infinispan/container/offheap/OffHeapSizeTest.java, core/src/test/java/org/infinispan/eviction/impl/ExceptionEvictionTest.java, core/src/test/resources/configs/named-cache-test.xml, documentation/src/main/asciidoc/user_guide/eviction.adoc, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/MemoryBinaryConfigurationResource.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/MemoryObjectConfigurationResource.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/MemoryOffHeapConfigurationResource.java, server/integration/infinispan/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
* Add strategy type configuration
* Add documentation describing strategies
https://issues.jboss.org/browse/ISPN-8396
=> ISPN-8396 Add interceptor preventing going out of memory

persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/Index.java
https://issues.jboss.org/browse/ISPN-8701
I started working on a reproducer but finding a sequence operations that would take the index to the desired state (see JIRA) seemed too complicated.
=> ISPN-8701 IndexOutOfBoundsException in SIFS during shutdown

core/src/test/java/org/infinispan/distribution/BaseDistSyncL1Test.java, core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java
https://issues.jboss.org/browse/ISPN-8742
getAsync() doesn't always run interceptor callbacks on a separate thread.
The remote get can finish before the calling thread calls thenAccept(),
especially when the test suite is limited to a single CPU.
The fix is trivial, figuring how the next test was affected took me much longer :)
=> DistSyncTxL1FuncTest.testGetBlockingAnotherGetCacheEntry random failures

core/src/main/java/org/infinispan/stream/impl/AbstractRehashPublisherDecorator.java, core/src/main/java/org/infinispan/stream/impl/CompletionRehashPublisherDecorator.java, core/src/main/java/org/infinispan/stream/impl/DistributedCacheStream.java, core/src/main/java/org/infinispan/stream/impl/IdentityPublisherDecorator.java, core/src/main/java/org/infinispan/stream/impl/KeyWatchingCompletionListener.java, core/src/main/java/org/infinispan/stream/impl/PublisherDecorator.java, core/src/main/java/org/infinispan/stream/impl/RehashPublisherDecorator.java, core/src/test/java/org/infinispan/stream/impl/CompletionRehashPublisherDecoratorTest.java, core/src/test/java/org/infinispan/stream/impl/TestRemoteIteratorPublisher.java
too early
* Use KeyWatchingListener for each publisher
https://issues.jboss.org/browse/ISPN-8708
=> ISPN-8708 Remote iteration with limited batch sends finished segments

core/src/main/java/org/infinispan/util/ByteString.java, core/src/test/java/org/infinispan/util/ByteStringTest.java
https://issues.jboss.org/browse/ISPN-8798
@tristantarrant Please backport to 9.1.x.  We'll need a prompt 9.1.6.Final release containing this fix, or else we'll need to revert back to 8.2.x for WF12. :(
=> ISPN-8798 Allow ByteString lengths up to 255.

all/embedded/pom.xml, all/remote/pom.xml, bom/pom.xml, client/hotrod-client/src/main/resources/features.xml, pom.xml, server/core/src/main/java/io/netty/handler/ssl/AlpnHackedSslSession.java, server/integration/feature-pack/pom.xml, server/integration/feature-pack/src/main/resources/modules/system/layers/base/io/netty/main/module.xml
https://issues.jboss.org/browse/ISPN-8657
=> ISPN-8657 Netty upgrade to 4.1.21

core/src/main/java/org/infinispan/LockedStream.java, core/src/main/java/org/infinispan/stream/impl/LockedStreamImpl.java
* Added methods to interface
https://issues.jboss.org/browse/ISPN-8829
=> ISPN-8829 LockedStream doesn't override BaseCacheStream methods

core/src/test/java/org/infinispan/dataconversion/DataConversionTest.java, core/src/test/java/org/infinispan/dataconversion/GzipEncoder.java, documentation/src/main/asciidoc/user_guide/cache_api.adoc, documentation/src/main/asciidoc/user_guide/compatibility_mode.adoc, documentation/src/main/asciidoc/user_guide/encoding.adoc, documentation/src/main/asciidoc/user_guide/marshalling.adoc
https://issues.jboss.org/browse/ISPN-8775
=> ISPN-8775 Encoder documentation

commons/src/main/java/org/infinispan/commons/util/Closeables.java, commons/src/main/java/org/infinispan/commons/util/SmallIntSet.java, core/src/main/java/org/infinispan/cache/impl/CacheImpl.java, core/src/main/java/org/infinispan/cache/impl/DecoratedCache.java, core/src/main/java/org/infinispan/cache/impl/EncoderCache.java, core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java, core/src/main/java/org/infinispan/commands/read/EntrySetCommand.java, core/src/main/java/org/infinispan/container/DataContainer.java, core/src/main/java/org/infinispan/container/DefaultDataContainer.java, core/src/main/java/org/infinispan/context/Flag.java, core/src/main/java/org/infinispan/context/impl/FlagBitSets.java, core/src/main/java/org/infinispan/encoding/DataConversion.java, core/src/main/java/org/infinispan/interceptors/impl/PrefetchInterceptor.java, core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java, core/src/main/java/org/infinispan/stream/impl/ClusterStreamManagerImpl.java, core/src/main/java/org/infinispan/stream/impl/CompletionRehashPublisherDecorator.java, core/src/main/java/org/infinispan/stream/impl/DistributedCacheStream.java, core/src/main/java/org/infinispan/stream/impl/IteratorResponse.java, core/src/main/java/org/infinispan/stream/impl/IteratorResponses.java, core/src/main/java/org/infinispan/stream/impl/LocalStreamManagerImpl.java, core/src/main/java/org/infinispan/stream/impl/PriorityMergingProcessor.java, core/src/main/java/org/infinispan/stream/impl/RehashPublisherDecorator.java, core/src/main/java/org/infinispan/stream/impl/interceptor/AbstractDelegatingEntryCacheSet.java, core/src/main/java/org/infinispan/stream/impl/local/EntryStreamSupplier.java, core/src/test/java/org/infinispan/stream/DistributedStreamIteratorExceptionTest.java, core/src/test/java/org/infinispan/stream/DistributedStreamIteratorTest.java, core/src/test/java/org/infinispan/stream/LocalStreamIteratorExceptionTest.java, core/src/test/java/org/infinispan/stream/impl/CompletionRehashPublisherDecoratorTest.java
https://issues.jboss.org/browse/ISPN-8790
https://issues.jboss.org/browse/ISPN-8806
Most of these changes are about trying to remove as many wrappers and needless invocations when using an iterator. Also a lot of places using a spliterator will give better performance than using an iterator.
The other big change is that subscriptions are now performed on the async executor. This way the user thread doesn't incur the cost of marshalling and sending a request and can go back to returning entries much faster.
There was also a bug found in requesting a new batch that could cause it to request 2x batch size on accident and is fixed in the ISPN-8806 commit.
=> Ispn 8790 distributed iterator performance tweaks

spring/spring4/spring4-common/src/main/java/org/infinispan/spring/provider/CacheDelegate.java, spring/spring4/spring4-embedded/src/test/java/org/infinispan/spring/provider/SpringCacheTest.java, spring/spring4/spring4-remote/src/test/java/org/infinispan/spring/provider/SpringRemoteCacheTest.java
https://issues.jboss.org/browse/ISPN-7224
Here's the missing part of [ISPN-7224](https://issues.jboss.org/browse/ISPN-7224) for synchronous GET methods. In the future we may reimplement `#get(Object, Callable<T>)` method to support different locking strategy but for now it would be an overkill. `StampedLock` seems cheap enough to do the trick.
=> ISPN-7224 Synchronous get

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/stress/IterationStressTest.java
https://issues.jboss.org/browse/ISPN-8822
Some numbers from my local environment:
| Method| 9.2.0.CR1 (ms) | 9.2.0.CR2 (ms)| 
| --- |---| ---|
| ingestion|6873|25323|
| iteration|377|2570|
The iteration method is a single client/single server iterating through all entries and closing the remote cache manager (like the Spark connector does). As explained in the JIRA, CR2 adds a 2s constant delay in closing the cache manager, so this should account for most of the discrepancy
With relation to data ingestion, was not expecting such a difference...
=> ISPN-8822 Performance degradation when running Spark jobs

server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/DefaultIterationManager.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationFilter.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/MarshallerBuilder.java
Some orElse didn't use constants but created objects. Didn't seem to cause any problems however so this is just a small optimization to not create objects unless they are actually needed.
=> Switched some orElse to orElseGet

server/integration/feature-pack/src/main/resources/content/bin/agent.conf, server/integration/feature-pack/src/main/resources/modules/system/layers/base/io/fabric8/agent-bond/main/jolokia-access.xml
The intention with this commit is allow only request from localhost
and using the post http method.
We can use also the following placeholders
$host or ${host} : Host name (if possible), otherwise address
$ip or ${ip} : IP Address
${prop:foo} : System property foo
${env:FOO} : Environment variable FOO
=> ISPN-8796 - Jolokia must be secured by default

server/integration/testsuite/src/test/java/org/infinispan/server/test/client/rest/RESTHelper.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/configs/ExampleConfigsIT.java, server/integration/testsuite/src/test/resources/arquillian.xml, server/integration/versions/pom.xml
https://issues.jboss.org/browse/ISPN-8720
=> ISPN-8720 Implement test for REST with SSL configuration template

core/src/main/java/org/infinispan/configuration/cache/EvictionConfigurationBuilder.java
ISPN000368: Memory approximation calculation for eviction is unsupported
for the 'OpenJDK 64-Bit Server VM' Java VM"
* Don't warn when OpenJDK VM is used
Wrong warn message for eviction "EvictionConfigurationBuilder ISPN000368: Memory approximation calculation for eviction is unsupported for the 'OpenJDK 64-Bit Server VM' Java VM"
=> ISPN-8888 Wrong warn message for eviction "EvictionConfigurationBuilder

core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/main/java/org/infinispan/security/impl/AuthorizationHelper.java
https://issues.jboss.org/browse/ISPN-8871
Avoids initializing Caffeine when we don't need it (unbounded and off-heap)
=> ISPN-8871 Do not create an ACL cache if one isn't needed

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/Util.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
* use non-busy-waiting get when expecting response
* avoid some thread-local lookups in Netty
https://issues.jboss.org/browse/ISPN-8822
@gustavonalle When checking, please make sure that you set the same GC for both runs (recently G1 was set as default in the testsuite and this has a huge impact).
=> ISPN-8822 Fix performance regression

core/src/main/java/org/infinispan/interceptors/impl/SimpleAsyncInvocationStage.java, core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java, core/src/main/java/org/infinispan/remoting/transport/Transport.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponse.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
In general, the code relays on getting the remote exception when it is getting the result of completable future which manages the invoked command, so it is not possible to change the return type of the exception throwing directly an ExecutionException.
This is a tentative solution using the suppressed exception featured to encapsulate the current thread stack trace in the exception thrown.
Jira issue: https://issues.jboss.org/browse/ISPN-8893
=> ISPN-8893 Do not ignore the asking thread stack trace when reporting a remoting exception.

core/src/main/java/org/infinispan/globalstate/ScopedPersistentState.java, core/src/main/java/org/infinispan/globalstate/impl/GlobalStateManagerImpl.java, core/src/main/java/org/infinispan/globalstate/impl/ScopedPersistentStateImpl.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
- perform validation of the global state file on startup
https://issues.jboss.org/browse/ISPN-8907
=> ISPN-8907 Prevent CacheManager start when global state is corrupt

core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactoryImpl.java, server/rest/src/test/java/org/infinispan/rest/BaseRestOperationsTest.java, server/rest/src/test/java/org/infinispan/rest/helper/RestServerHelper.java
RestOperationsTest#shouldPutImmortalEntryWithZeroTtlAndIdleTime random
failure
* Increased expiration times so they shouldn't expire with thread delay
https://issues.jboss.org/browse/ISPN-8930
=> ISPN-8930 RestOperationsTest random test failures

core/src/test/java/org/infinispan/topology/ClusterTopologyManagerImplTest.java
https://issues.jboss.org/browse/ISPN-8839
I missed the fact that `testCoordinatorLostDuringRebalance` needs 2 threads in the transport thread pool in the initial fix.
=> ISPN-8839 ClusterTopologyManagerImplTest failures

core/src/main/java/org/infinispan/stream/impl/ClusterStreamManagerImpl.java
* Added null check for response tracker due to cache shutdown
https://issues.jboss.org/browse/ISPN-8933
=> ISPN-8933 NullPointerException in StreamResponseCommand

documentation/src/main/asciidoc/contributing/basics.adoc, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/Compactor.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/FileProvider.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/Index.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/IndexNode.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/Log.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/LogAppender.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/LogRequest.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/SoftIndexFileStore.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/TemporaryTable.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/configuration/SoftIndexFileStoreConfiguration.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/configuration/SoftIndexFileStoreConfigurationBuilder.java
* validate the configuration
* use shorts where the value should be limited to short
* use i18d logging
* minor code cleanup based on IDE suggestions
https://issues.jboss.org/browse/ISPN-8912
=> ISPN-8912 SoftIndexFileStore does not fail gracefully if max node sizee exceeds 32767

cloud/src/main/resources/default-configs/default-jgroups-ec2.xml, cloud/src/main/resources/default-configs/default-jgroups-google.xml, cloud/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/main/resources/default-configs/default-jgroups-udp.xml, core/src/test/resources/configs/xsite/bridge.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/tcp_mping/tcp1.xml, core/src/test/resources/stacks/tcp_mping/tcp2.xml, core/src/test/resources/stacks/udp.xml, integrationtests/as-lucene-directory/src/test/resources/default-jgroups4-udp.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml, lucene/directory-provider/src/test/resources/testing-flush-loopback.xml, server/integration/jgroups/src/main/resources/jgroups-defaults.xml
Jira
https://issues.jboss.org/browse/ISPN-8978
GMS#install_view_locally_first was deprecated and is never used but does not issue a warning message (JGRP-2258).
This should be removed from the stack configuration.
Cross-check
https://github.com/belaban/JGroups/blob/master/src/org/jgroups/protocols/pbcast/GMS.java#L107
=> ISPN-8978 Remove usage of deprecated GMS#install_view_locally_first

core/src/main/java/org/infinispan/configuration/cache/PartitionHandlingConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/PartitionHandlingConfigurationBuilder.java, core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.jboss.org/browse/ISPN-9013
Added deprecation javadoc and fix log message.
=> ISPN-9013 Partition Handling enabled toggle should set merge-policy=NONE

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/ProtocolVersion.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/IterationNextOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/IterationStartOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec12.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec20.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec23.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec24.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec25.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec26.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/BulkOperationsTest.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java
versions before 9.2
* Added iterator methods to Codecs
* Put appropriate methods on each Codec version
https://issues.jboss.org/browse/ISPN-8719
=> ISPN-8719 KeySet.(iterator|spliterator|stream) not compatible with

core/src/test/java/org/infinispan/health/ClusterHealthImplTest.java
The cleanup is not properly done and if the order of the tests changez, we can have unhealthy caches and user created caches from other tests
=> ISPN-8994 fix cleanAfterMethod

demos/gui/pom.xml, distribution/src/main/release/all/README-Modules.txt, extended-statistics/pom.xml, persistence/remote/pom.xml, persistence/rest/pom.xml, pom.xml, tools/pom.xml
https://issues.jboss.org/browse/ISPN-8911
=> ISPN-8911 Copy dependencies for the distribution only for specific modules

LICENSE.md
Hello! 👋
(CCing @dankohn who has requested this work so that the license will appear correctly in https://landscape.cncf.io/selected=infinispan)
GitHub uses a library called Licensee to identify a project's license
type. It shows this information in the status bar and via the API if it
can unambiguously identify the license.
This commit adds a LICENSE.md file which contains the exact text of the
Apache 2.0 license. This allows Licensee to successfully identify the
license type of Infinispan's codebase as Apache 2.0.
=> edit Infinispan license info so that GitHub recognizes it

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/event/ContinuousQueryImpl.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/filter/Filters.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/BaseMatcher.java, query-dsl/src/main/java/org/infinispan/query/dsl/Query.java, query-dsl/src/main/java/org/infinispan/query/dsl/impl/BaseQuery.java, query-dsl/src/test/java/org/infinispan/query/dsl/impl/DummyQuery.java, query/src/main/java/org/infinispan/query/Search.java, query/src/main/java/org/infinispan/query/continuous/impl/ContinuousQueryImpl.java
* we no longer need to cast to BaseQuery in order to access it
https://issues.jboss.org/browse/ISPN-9081
=> ISPN-9081 Expose Query.getQueryString() as official API

core/src/main/java/org/infinispan/remoting/transport/jgroups/StaggeredRequest.java, core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsTransportTest.java
https://issues.jboss.org/browse/ISPN-9099
=> ISPN-9099 StaggeredRequest throws IllegalStateException

core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
https://issues.jboss.org/browse/ISPN-9104
After a merge NAKACK2 may replay topology updates from the minority
partition to the nodes of the majority partition. Fix the coordinator
check in doHandleTopologyUpdate so that we don't apply the updates.
=> ISPN-9104 Majority partition nodes can process minority topology updates

commons/src/main/java/org/infinispan/commons/util/ImmutableHopscotchHashSet.java, commons/src/main/java/org/infinispan/commons/util/Immutables.java, core/src/main/java/org/infinispan/distribution/LocalizedCacheTopology.java, core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java, core/src/main/java/org/infinispan/remoting/transport/Transport.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/ClusterView.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/test/java/org/infinispan/invalidation/BaseInvalidationTest.java, core/src/test/java/org/infinispan/jmx/RpcManagerMBeanTest.java, core/src/test/java/org/infinispan/remoting/rpc/RpcManagerTest.java, core/src/test/java/org/infinispan/remoting/transport/MockTransport.java, core/src/test/java/org/infinispan/replication/ForceSyncAsyncFlagsTest.java, core/src/test/java/org/infinispan/replication/SyncReplTest.java, core/src/test/java/org/infinispan/test/TestingUtil.java
https://issues.jboss.org/browse/ISPN-9008
I added an `ImmutableHopscotchHashSet` mainly because I didn't want to have both a `unmodifiableSet()` wrapper and `HashSet` wrapping `HashMap`. Considering addresses are random numbers I don't think hopscotch hashing per se can help with performance, but maybe we could do something to optimize `containsAll` @rvansa?
=> ISPN-9008 RpcManager.invokeCommandOnAll ignores cache member missing from cluster view

core/src/main/java/org/infinispan/persistence/util/PersistenceManagerCloseableSupplier.java
failures
* Fixed issue with retrieval during close
https://issues.jboss.org/browse/ISPN-9002
=> ISPN-9002 LocalModeNoPassivationTest.testValuesWithEvictedEntries random

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/stress/IterationStressTest.java, commons/src/main/java/org/infinispan/commons/util/ProcessorInfo.java, commons/src/test/java/org/infinispan/commons/util/ProcessorInfoTest.java, core/src/main/java/org/infinispan/container/offheap/OffHeapDataContainer.java, core/src/main/java/org/infinispan/container/offheap/StripedLock.java, core/src/main/java/org/infinispan/health/impl/HostInfoImpl.java, core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java, core/src/main/java/org/infinispan/util/concurrent/StripedCounters.java, core/src/test/java/org/infinispan/conflict/impl/MultipleCachesDuringConflictResolutionTest.java, core/src/test/java/org/infinispan/persistence/file/SingleFileStoreStressTest.java, documentation/src/main/asciidoc/performance_guide/performance_guide.asciidoc, persistence/cli/src/main/java/org/infinispan/persistence/cli/upgrade/CLInterfaceTargetMigrator.java, persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/HotRodTargetMigrator.java, persistence/rest/src/main/java/org/infinispan/persistence/rest/upgrade/RestTargetMigrator.java, query/src/test/java/org/infinispan/query/affinity/IndexManagerPerfTest.java, server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfigurationBuilder.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheResource.java
https://issues.jboss.org/browse/ISPN-9091
=> ISPN-9091 Determine available CPUs taking CGroup quotas into account

core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java, core/src/main/java/org/infinispan/registry/impl/InternalCacheRegistryImpl.java
https://issues.jboss.org/browse/ISPN-8969
* Await initial state transfer for internal global caches
* Disable rebalancing before removing a cache through the CacheManagerAdmin API
=> ISPN-8969 Make Global Configuration more robust

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponse.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/SingleSiteRequest.java, core/src/test/java/org/infinispan/xsite/backupfailure/tx/BaseLocalClusterTxFailureTest.java
https://issues.jboss.org/browse/ISPN-9113
* Implement only UpHandler in ChannelCallbacks
* Enable BaseLocalClusterTxFailureTest tests
=>  ISPN-9113 SITE_UNREACHABLE not handled by JGroupsTransport 

cloud/src/main/resources/default-configs/default-jgroups-ec2.xml, cloud/src/main/resources/default-configs/default-jgroups-google.xml, cloud/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/java/org/infinispan/configuration/cache/BackupConfiguration.java, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/main/resources/default-configs/default-jgroups-udp.xml, core/src/test/java/org/infinispan/xsite/XSiteFileParsing2Test.java, core/src/test/java/org/infinispan/xsite/XSiteFileParsingTest.java, core/src/test/resources/configs/xsite/bridge.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/tcp_mping/tcp1.xml, core/src/test/resources/stacks/tcp_mping/tcp2.xml, core/src/test/resources/stacks/udp.xml, demos/gui/src/main/release/etc/config/jgroups-relay1.xml, demos/gui/src/main/release/etc/config/jgroups-relay2.xml, demos/gui/src/main/release/etc/config/jgroups-tcp.xml, integrationtests/as-lucene-directory/src/test/resources/default-jgroups4-udp.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml, lucene/directory-provider/src/test/resources/testing-flush-loopback.xml, persistence/jdbc/src/test/resources/configs/as7/jdbc-standalone.xml, server/integration/jgroups/src/main/resources/jgroups-defaults.xml
https://issues.jboss.org/browse/ISPN-9087
* Replace FD_ALL with FD_ALL2 and change the timeout from 60s to 10s.
* Keep the default cache replication timeout at 15s
* Increase the default backup site timeout from 10s to 15s
=> ISPN-9087 Timeout during put operation when a node is blocked

hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/entity/EntityRegionAccessStrategyTest.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/EntityCollectionInvalidationTest.java
https://issues.jboss.org/browse/ISPN-9175
* Currently no grouping mechanism for JUnit tests, so just ignore them.
=> ISPN-9175 Ignore Hibernate 2LC unstable tests

commons-test/src/main/java/org/infinispan/commons/test/TestNGTestListener.java
https://issues.jboss.org/browse/ISPN-9189
=> ISPN-9189 ExceptionEvictionTest test failure causes testng to panic

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/test/java/org/infinispan/remoting/rpc/RpcManagerTest.java
collection leak memory
* Add check to only send command if not already complete
https://issues.jboss.org/browse/ISPN-9204
=> ISPN-9204 Single node JgroupsTransport invoke* methods that take a

hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/LocalInvalidationSynchronization.java
…tFromLoadValidator#endInvalidatingKey with arguments in incorrect order
=> [9.2] ISPN-9205 LocalInvalidationSynchronization#afterCompletion calls Pu

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/Util.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
* When catching InterruptedException, since we cannot send the
exception as is, also restore its interrupt status.
=> ISPN-9218 Wrap InterruptedException in HotRodClientException

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDisableLegacyIndexingTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDslConditionsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryTestUtils.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryWithProtostreamAnnotationsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/marshallers/AnalyzerTestEntityMarshaller.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/marshallers/NotIndexedMarshaller.java, commons/src/main/java/org/infinispan/commons/marshall/WrappedByteArray.java, core/src/main/java/org/infinispan/configuration/cache/CustomInterceptorsConfigurationBuilder.java, documentation/src/main/asciidoc/user_guide/query.adoc, integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/QueryDslConditionsTest.java, query-dsl/src/main/java/org/infinispan/query/dsl/impl/BaseCondition.java, query/src/main/java/org/infinispan/query/spi/ProgrammaticSearchMappingProvider.java, query/src/test/java/org/infinispan/query/dsl/embedded/QueryStringTest.java, remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/ContinuousQueryResult.java, remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/FilterResult.java, remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/QueryRequest.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProgrammaticSearchMappingProviderImpl.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadata.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerInterceptor.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/RemoteQueryEngine.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadata.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadataCreator.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingTagHandler.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/ProtobufValueWrapper.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/ProtobufValueWrapperFieldBridge.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/WrappedMessageTagHandler.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/logging/Log.java
https://issues.jboss.org/browse/ISPN-9021
This should improve performance for types that do not need indexing and thus are not annotated for indexing.
=> ISPN-9021 Remote query: add option to disable default/legacy indexing per schema file

client/hotrod-client/pom.xml
https://issues.jboss.org/browse/ISPN-9258
Not really a provided dependency based on how the code is laid out right now. 
Let's integrate this and @pruivo can take over to really make it provided?
=> ISPN-9258 javax.transaction dependency is not provided

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/TransportHelper.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/EpollAvailabilityTest.java
https://issues.jboss.org/browse/ISPN-9281
=> [9.2.x] ISPN-9281 Handle ClassNotFoundException for io.netty.channel.epoll.Epoll

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDisableLegacyIndexingTest.java, commons/src/main/java/org/infinispan/commons/dataconversion/WrapperIds.java, commons/src/main/java/org/infinispan/commons/marshall/WrappedByteArray.java, remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/BaseProtoStreamMarshaller.java, remote-query/remote-query-client/src/test/java/org/infinispan/query/remote/client/BaseProtoStreamMarshallerTest.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProgrammaticSearchMappingProviderImpl.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufRemoteQueryManager.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufValueWrapperIndexingInterceptor.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufWrapper.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/RemoteQueryEngine.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/filter/IckleFilterConverterUtils.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingWrappedMessageTagHandler.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/ProtobufValueWrapper.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/ProtobufValueWrapperFieldBridge.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/ProtobufValueWrapperInterceptor.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/WrappedMessageTagHandler.java, tasks/manager/src/test/java/org/infinispan/tasks/SecurityTaskManagerTest.java
…ng to handle conditional indexing for @Indexed(false)
https://issues.jboss.org/browse/ISPN-9020
* add ProtobufValueWrapperInterceptor to intercept writing of ProtobufValueWrapper objects in the cache and discover the inner message type
* add ProtobufValueWrapperIndexingInterceptor to provide conditional indexing
* rename ProtostreamWrapper to ProtobufWrapper because it's really the encoding format not the encoding library that's important
=> ISPN-9020 Remote query: disabling indexing for a type with @Indexed(false) still creates empty documents in index

hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/AbstractRegionAccessStrategyTest.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/entity/EntityRegionAccessStrategyTest.java
https://issues.jboss.org/browse/ISPN-9194
Please find details about the actual issue in the JIRA. The problem was that a `FutureUpdate` put was leaking from one test to other, resulting in the latches in the latter test passing when they shouldn't.
The fix contains:
* Wait for the `FutureUpdate` put at the end of testRemove.
* When checking for put latches, make sure the key is the expected one.
* Logging to make it easier to diagnose problems in the future.
=> ISPN-9194 EntityRegionAccessStrategyTest.testRemoveAll failing randomly

core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java
https://issues.jboss.org/browse/ISPN-9187
Keep joiners in the pending CH when updating members after a leave.
=> ISPN-9187 Lost segments logged when node leaves during rebalance

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/counter/AbstractCounterTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/counter/CounterManagerOperationTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/counter/StrongCounterAPITest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/counter/WeakCounterAPITest.java
https://issues.jboss.org/browse/ISPN-9219
https://issues.jboss.org/browse/ISPN-9266
at least locally, the failures are caused by retried functional commands. 
https://github.com/infinispan/infinispan/pull/5381 should fix those. In the meanwhile, lets make sure the counter's cache is started before start the testing.
=> ISPN-9219 ISPN-9266 (Weak|Strong)CounterAPITest.testAdd random failures

core/src/main/java/org/infinispan/persistence/PersistenceUtil.java
* Removed extra expiration check
* CacheLoader should handle check
https://issues.jboss.org/browse/ISPN-8988
=> ISPN-8988 Cache item can be expired after loading immediately

documentation/pom.xml, documentation/src/main/asciidoc/upgrading/upgrading.asciidoc, documentation/src/main/asciidoc/user_guide/integrations.adoc, feature-pack/build.xml, feature-pack/pom.xml
https://issues.jboss.org/browse/ISPN-9259
@Sanne @fax4ever FYI after becoming aware of the following [guidelines](https://developer.jboss.org/wiki%20/LayeredDistributionsAndModulePathOrganization) we're moving the wildfly-modules to `modules/system/add-ons/ispn`. Let me know if you know of any issues etc.
=> ISPN-9259 Feature-packs should utilise modules/system/add-ons dir

core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreListenerFunctionalTest.java, core/src/test/java/org/infinispan/persistence/file/SingleFileStoreFunctionalTest.java
https://issues.jboss.org/browse/ISPN-9016 removed the gitignore for *.dat files, and this exposed a problem in ExpirationSingleFileStoreListenerFunctionalTest
I initially thought the stale files were from SingleFileStoreFunctionalTest, so I changed it to skip the cache instantiation in the parse tests as well.
=> ISPN-9016 Delete temporary SingleFileStore .dat files after tests

integrationtests/wildfly-modules/pom.xml, server/integration/src/main/ant/infinispan-server.xml, server/integration/testsuite/pom.xml
https://issues.jboss.org/browse/ISPN-9287
* Only fail the build if all tools have a non-zero exit code
* Fix the infinispan-server.xml path in the rolling upgrades profile
=> ISPN-9287 Integration test suite fails when JAVA_HOME is not set

server/integration/versions/pom.xml
We had to release 9.3.1.Final as 9.3.0.Final had already been released by accident a few months ago.
=> Upgrade console to 9.3.1.Final

core/src/main/java/org/infinispan/interceptors/distribution/VersionedDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/locking/PessimisticLockingInterceptor.java, core/src/main/java/org/infinispan/remoting/inboundhandler/action/PendingTxAction.java, core/src/main/java/org/infinispan/statetransfer/StateProviderImpl.java, core/src/main/java/org/infinispan/transaction/impl/AbstractCacheTransaction.java, core/src/main/java/org/infinispan/transaction/impl/LocalTransaction.java, core/src/main/java/org/infinispan/transaction/xa/CacheTransaction.java, core/src/main/java/org/infinispan/util/concurrent/locks/impl/DefaultPendingLockManager.java, core/src/test/java/org/infinispan/tx/PessimisticDeadlockTest.java
https://issues.jboss.org/browse/ISPN-8533
=> ISPN-8533 Deadlock in pessimistic transaction

core/src/test/java/org/infinispan/atomic/OptimisticTxAtomicLockingTest.java, core/src/test/java/org/infinispan/atomic/PessimisticTxAtomicLockingTest.java
Forgot to check the CI results before merging #6064 and the build is now failing because the testName is incorrect.
=> ISPN-8431 Fix test name in @Test annotation

server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLWriter.java, server/integration/infinispan/src/test/java/org/jboss/as/clustering/infinispan/subsystem/SubsystemParsingTestCase.java, server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_3.xml
https://issues.jboss.org/browse/ISPN-9326
The model generated for this configuration is kind of weird
```
"modules" => {"MODULES" => {"module" => {
"module1" => {
"name" => "module1",
"slot" => undefined
},
"module2" => {
"name" => "module2",
"slot" => "slot2"
}
}}}
```
But I could not figure out how to improve it after 1h, so I just fixed the serialization bug
=> ISPN-9326 Marshall error when using <modules> config in the server

server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoder.java, server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedFunctionalTest.java
https://issues.jboss.org/browse/ISPN-9327
The test is failing because both the test and the server assume the platform encoding is UTF-8. E.g. the server uses UTF-8 when reading the key, and the platform encoding when writing it back.
On this machine the platform encoding is US-ASCII, and that breaks the test and the server.
@tristantarrant do you think it's useful for the server to use the platform encoding instead? (We'd have to change the way we read keys as well.)
Could you also explain a bit what kind of buffer overflow we are testing? If it's the buffer replay in the server, I think it would be better to include this in every test by using `SingleByteFrameDecoderChannelInitializer` to force a replay on every byte, without a separate test.
=> ISPN-9327 Always use UTF-8 in memcached server and tests

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
I added the following two properties to the ConfigurationBuilder Javadoc of Hot Rod Client.
* infinispan.client.hotrod.transaction.transaction_manager_lookup
* infinispan.client.hotrod.transaction.transaction_mode
It is a property added by Hot Rod Transaction, so I think that it was better to have a description in Javadoc.
=> add javadoc, Hot Rod Transaction properties

persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
* Make sure to properly use clearThreshold variable
https://issues.jboss.org/browse/ISPN-9359
=> ISPN-9359 RocksDB clear always reinitializes the database

server/integration/feature-pack/src/main/resources/content/bin/agent.conf, server/integration/feature-pack/src/main/resources/content/bin/jolokia.bat, server/integration/feature-pack/src/main/resources/content/bin/jolokia.sh
https://issues.jboss.org/browse/ISPN-9363
=> ISPN-9259 Fix agent-bond and jolokia module paths

commons/src/main/java/org/infinispan/commons/util/Util.java, core/src/main/java/org/infinispan/globalstate/impl/OverlayLocalConfigurationStorage.java, core/src/main/java/org/infinispan/util/logging/Log.java, counter/src/main/java/org/infinispan/counter/impl/manager/PersistedCounterConfigurationStorage.java, counter/src/main/java/org/infinispan/counter/logging/Log.java
On windows File.renameTo() fails if destination file exists. Quick fix provided.
https://issues.jboss.org/browse/ISPN-9333
=> ISPN-9333 Delete destination file before rename

core/src/main/java/org/infinispan/partitionhandling/impl/AvailabilityStrategy.java, core/src/main/java/org/infinispan/partitionhandling/impl/PreferAvailabilityStrategy.java, core/src/main/java/org/infinispan/partitionhandling/impl/PreferConsistencyStrategy.java, core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java, core/src/test/java/org/infinispan/remoting/transport/ControlledTransport.java, core/src/test/java/org/infinispan/scattered/statetransfer/CoordinatorStopTest.java, core/src/test/java/org/infinispan/test/TestingUtil.java, core/src/test/java/org/infinispan/test/TopologyChangeListener.java, core/src/test/java/org/infinispan/test/ViewChangeListener.java, core/src/test/java/org/infinispan/test/transport/DelayedViewJGroupsTransport.java, core/src/test/java/org/infinispan/topology/TestClusterCacheStatus.java, core/src/test/java/org/infinispan/tx/InfinispanNodeFailureTest.java, core/src/test/java/org/infinispan/util/BlockingLocalTopologyManager.java, core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
https://issues.jboss.org/browse/ISPN-9128
Includes https://issues.jboss.org/browse/ISPN-9095 as well. 
The fix is just one liner :)
=> ISPN-9128 RehashWithSharedStoreTest.testRehashes random failures

Jenkinsfile
https://issues.jboss.org/browse/ISPN-9403
Workaround only, do not close the issue.
=> ISPN-9403 Increase build timeout to work around slow CI

multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/StoreTypeMultimapCacheTest.java
Looking at the  multimap module, I've realised there is a test ignored attending this issue to be integrated: (functional maps + data conversion)
https://issues.jboss.org/browse/ISPN-7993
The issue is integrated now so the test should pass
=> StoreTypeMultimapCacheTest - was Ignored and should work now

hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/InvalidationSynchronization.java, hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/LocalInvalidationSynchronization.java, hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/NonTxInvalidationCacheAccessDelegate.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/LocalCacheTest.java, hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/impl/LocalInvalidationInvocation.java, hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/impl/NonTxInvalidationCacheAccessDelegate.java
https://hibernate.atlassian.net/browse/HHH-12457
Backport #5970 already integrated, but this has dependency to #5954 and #5964 
https://issues.jboss.org/browse/ISPN-9205 which was introduced in the backport is fixed here.
=> HHH-12457 Local Infinispan read-write caches become stale on rollback

documentation/src/main/asciidoc/user_guide/persistence.adoc
It is a description about the store described in the `Limitations` of the Persistence document, but is not it correct to write it in an unordered list?
For Infinispan's current User Guide, it seems to me that the table of contents and display are collapsed.
=> fix list notation for the description of Cache Passivation limitation

core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/test/java/org/infinispan/distribution/rehash/RehashAfterPartitionMergeTest.java, core/src/test/java/org/infinispan/notifications/MergeViewTest.java, core/src/test/java/org/infinispan/partitionhandling/PartitionStressTest.java, core/src/test/java/org/infinispan/partitionhandling/ScatteredCrashInSequenceTest.java, core/src/test/java/org/infinispan/scattered/statetransfer/CrashJoinTest.java, core/src/test/java/org/infinispan/statetransfer/ClusterTopologyManagerTest.java, core/src/test/java/org/infinispan/statetransfer/LeaveDuringStateTransferTest.java, core/src/test/java/org/infinispan/statetransfer/MergeDuringReplaceTest.java, core/src/test/java/org/infinispan/statetransfer/StateTransferRestart2Test.java, core/src/test/java/org/infinispan/statetransfer/StateTransferRestartTest.java, core/src/test/java/org/infinispan/stream/DistributedStreamIteratorTest.java, core/src/test/java/org/infinispan/test/TestingUtil.java, core/src/test/java/org/infinispan/topology/AsymmetricClusterTest.java, lucene/lucene-directory/src/test/java/org/infinispan/lucene/profiling/DynamicTopologyStressTest.java
https://issues.jboss.org/browse/ISPN-9465
When the last cache member leaves, the coordinator's ClusterCacheStatus
stays in state RUNNING, and the next join doesn't reinitialize the cache
topology.
=> ISPN-9465 Cannot join cache after killing the only member

commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitXMLReporter.java, core/src/test/java/org/infinispan/api/APINonTxOffHeapTest.java, core/src/test/java/org/infinispan/container/offheap/OffHeapSingleNodeExpirationEvictionTest.java, core/src/test/java/org/infinispan/manager/SingleClusterExecutorTest.java, core/src/test/java/org/infinispan/persistence/file/SingleFileStoreTest.java, core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java, core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java, query/src/test/java/org/infinispan/query/api/PutAllTest.java, query/src/test/java/org/infinispan/query/blackbox/ClusteredCacheTest.java, query/src/test/java/org/infinispan/query/blackbox/ClusteredQueryTest.java, query/src/test/java/org/infinispan/query/blackbox/LocalCacheStorageTypeTest.java, tasks/scripting/src/test/java/org/infinispan/scripting/ScriptingDataStoresTest.java
* the culprit is AbstractInfinispanTest
* after fixing this we find many tests were previously ignored by mistake and need params to be declared 
https://issues.jboss.org/browse/ISPN-9475
=> ISPN-9475 AbstractInfinispanTest mistakenly detects some test with params as duplicates

documentation/src/main/asciidoc/glossary/glossary.asciidoc, documentation/src/main/asciidoc/user_guide/transactions.adoc
I think the default isolation level after Infinispan 9.0 is REPEATABLE READ, but the document is READ COMMITTED.
[Enable write-skew for optimistic + repeatable-read transactions](https://issues.jboss.org/browse/ISPN-7613)
https://github.com/infinispan/infinispan/blob/9.4.0.CR1/core/src/main/java/org/infinispan/configuration/cache/LockingConfiguration.java#L19
=> fixed default value of isolation level of document

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheSupport.java, commons/src/main/java/org/infinispan/commons/api/AsyncCache.java, core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingCache.java, core/src/test/java/org/infinispan/api/AsyncAPITest.java, jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
AsyncAPITest has been refactored and adds compute/computeIfPresent/computeIfAbsent/merge and merge with lifespan/maxidle async testing
https://issues.jboss.org/browse/ISPN-9470
=> ISPN-9470 refactoring test and adds new tests for async

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/tcp/RoundRobinBalancingStrategy.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/RoundRobinBalancingStrategyTest.java
https://issues.jboss.org/browse/ISPN-9485
=> ISPN-9485 RoundRobinBalancingStrategy always starts from server 0

core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/test/java/org/infinispan/distribution/rehash/RehashAfterPartitionMergeTest.java, core/src/test/java/org/infinispan/notifications/MergeViewTest.java, core/src/test/java/org/infinispan/partitionhandling/PartitionStressTest.java, core/src/test/java/org/infinispan/partitionhandling/ScatteredCrashInSequenceTest.java, core/src/test/java/org/infinispan/scattered/statetransfer/CrashJoinTest.java, core/src/test/java/org/infinispan/statetransfer/ClusterTopologyManagerTest.java, core/src/test/java/org/infinispan/statetransfer/LeaveDuringStateTransferTest.java, core/src/test/java/org/infinispan/statetransfer/MergeDuringReplaceTest.java, core/src/test/java/org/infinispan/statetransfer/StateTransferRestart2Test.java, core/src/test/java/org/infinispan/statetransfer/StateTransferRestartTest.java, core/src/test/java/org/infinispan/stream/DistributedStreamIteratorTest.java, core/src/test/java/org/infinispan/test/TestingUtil.java, core/src/test/java/org/infinispan/topology/AsymmetricClusterTest.java, lucene/lucene-directory/src/test/java/org/infinispan/lucene/profiling/DynamicTopologyStressTest.java
https://issues.jboss.org/browse/ISPN-9465
When the last cache member leaves, the coordinator's ClusterCacheStatus
stays in state RUNNING, and the next join doesn't reinitialize the cache
topology.
=> ISPN-9465 Cannot join cache after killing the only member 9.3.x

commons-test/src/main/java/org/infinispan/commons/test/RunningTestsRegistry.java, core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
https://issues.jboss.org/browse/ISPN-9496
Enable FD only in xsite tests
=> ISPN-9496 Some xsite tests hang during teardown

core/src/test/java/org/infinispan/configuration/StringPropertyReplacementTest.java, core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java, core/src/test/java/org/infinispan/health/ClusterHealthImplTest.java, core/src/test/java/org/infinispan/statetransfer/ConcurrentStartTest.java, core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java, core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java, core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java, core/src/test/java/org/infinispan/test/fwk/TestResourceTracker.java, core/src/test/java/org/infinispan/util/PersistenceMockUtil.java, core/src/test/resources/configs/named-cache-test.xml, core/src/test/resources/configs/string-property-replaced.xml, tools/src/test/java/org/infinispan/tools/ConfigurationConverterTest.java
https://issues.jboss.org/browse/ISPN-9067
I had this lying around for a while...
* Only set the node name once
* Fail the test if a node doesn't have a proper name set
* Don't start the cache manager in the configuration parsing tests
=> ISPN-9067 Fix test node names

commons/src/main/java/org/infinispan/commons/util/ConcurrentSmallIntSet.java, commons/src/test/java/org/infinispan/commons/util/MutableIntSetTest.java
https://issues.jboss.org/browse/ISPN-9500
Fix the handling of negative values in clear() and several other
methods:
* toIntArray()
* forEach(IntConsumer)
* removeIf(IntPredicate)
=> ISPN-9500 ConcurrentSmallIntSet.clear() does not always set size to 0

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCacheService.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientCustomEventsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/AssertsNearCache.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/ClusterInvalidatedNearCacheTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/EvictInvalidatedNearCacheTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedFailoverNearCacheTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedNearCacheTest.java, commons/src/main/java/org/infinispan/commons/marshall/Ids.java, core/src/main/java/org/infinispan/marshall/core/InternalExternalizers.java, core/src/main/java/org/infinispan/notifications/cachelistener/filter/KeyValueFilterConverterAsCacheEventFilterConverter.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/ClientListenerRegistry.java
should not contain values
* All listeners without filter or converter don't use value
* Near cache ignores create remote events
https://issues.jboss.org/browse/ISPN-9484
=> ISPN-9484 Near cache invalidation should ignore created events and

core/src/main/java/org/infinispan/persistence/async/AdvancedAsyncCacheLoader.java, core/src/main/java/org/infinispan/persistence/async/State.java, core/src/main/java/org/infinispan/stream/impl/DistributedCacheStream.java, core/src/test/java/org/infinispan/persistence/support/ReplAsyncStoreTest.java
has write behind
* Also fixed async store segment filtering
* Also fixed clear losing later updates
https://issues.jboss.org/browse/ISPN-9332
=> ISPN-9332 REPL local iteration optimization cannot be used when store

core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
https://issues.jboss.org/browse/ISPN-9512
Restore the number of threads and queue in transport thread pool.
=> ISPN-9512 *TxPartitionAndMerge*Test tests hang during teardown

core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java, core/src/main/java/org/infinispan/container/offheap/OffHeapDataContainer.java
* Make sure stop occurs after clear on shutdown
https://issues.jboss.org/browse/ISPN-9509
=> ISPN-9509 OffHeapConcurentMap can throw exception during shutdown

documentation/src/main/asciidoc/user_guide/compatibility_mode.adoc, documentation/src/main/asciidoc/user_guide/endpoint_interop.adoc
It is currently hidden inside "Endpoint interoperability"
=> Fix security chapter disappearance

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheSupport.java, commons/src/main/java/org/infinispan/commons/api/AsyncCache.java, commons/src/main/java/org/infinispan/commons/api/BasicCache.java, core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingAdvancedCache.java, core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingCache.java, core/src/main/java/org/infinispan/cache/impl/CacheImpl.java, core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java, core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java, core/src/test/java/org/infinispan/api/AsyncAPITest.java, core/src/test/java/org/infinispan/functional/decorators/FunctionalAdvancedCache.java, jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
https://issues.jboss.org/browse/ISPN-9489
=> ISPN-9489 Adds missing compute family lifespan methods

build-configuration/pom.xml
JavaScript client can be upgraded to 0.5.0-SNAPSHOT
Spark connector can be upgraded to 0.9-SNAPSHOT
https://issues.jboss.org/browse/ISPN-9553
=> Upgrade JS client and Spark connector components

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/AssertsNearCache.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/ClusterInvalidatedNearCacheTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedFailoverNearCacheTest.java, core/src/main/java/org/infinispan/cache/impl/CacheImpl.java, core/src/main/java/org/infinispan/cache/impl/DecoratedCache.java, core/src/main/java/org/infinispan/commands/CommandsFactory.java, core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java, core/src/main/java/org/infinispan/commands/triangle/SingleKeyBackupWriteCommand.java, core/src/main/java/org/infinispan/commands/write/RemoveExpiredCommand.java, core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java, core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java, core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java, core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java, core/src/main/java/org/infinispan/expiration/impl/InternalExpirationManager.java, core/src/main/java/org/infinispan/expiration/impl/TxClusterExpirationManager.java, core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java, core/src/main/java/org/infinispan/util/concurrent/CompletableFutures.java, core/src/test/java/org/infinispan/container/SimpleDataContainerTest.java, core/src/test/java/org/infinispan/stress/DataContainerStressTest.java, core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
https://issues.jboss.org/browse/ISPN-9511
=> ISPN-9511 Expired event is not fired when modifying an expired entry

build-configuration/bom/pom.xml
Tried and tested locally to pull the 9.4.0.Final console. Also tested that the console actually loads and works as well. This one is gtg.
=> Bump console version to 9.4.0.Final

query/src/test/java/org/infinispan/query/affinity/BaseAffinityTest.java
https://issues.jboss.org/browse/ISPN-8799
=> ISPN-8799 Limit the default number of shards in the AffinityIndexManager

core/src/test/java/org/infinispan/distribution/DistAsyncFuncTest.java, core/src/test/java/org/infinispan/distribution/DistSyncFuncTest.java, core/src/test/java/org/infinispan/test/ReplListener.java
https://issues.jboss.org/browse/ISPN-8816
https://issues.jboss.org/browse/ISPN-8298
* Wait for replication in locked stream tests
* Delay command execution to trigger random failures more often
Should fix ISPN-8298 as well, although the `ReplListener` approach still has the risk of asynchronous commands leaking from one test method to the next. I hope to have more time to switch to `ControlledRpcManager` in the future.
=> ISPN-8616 DistAsyncFuncTest.testMergeFromNonOwner random failures

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/JsonKeyValueRawEventsTest.java, core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java, core/src/main/java/org/infinispan/notifications/cachelistener/filter/CacheEventConverter.java, server/core/src/main/java/org/infinispan/server/core/dataconversion/JBossMarshallingTranscoder.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/KeyValueVersionConverter.java
https://issues.jboss.org/browse/ISPN-9604
=> ISPN-9604 Support to run converters in the user requested format

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCacheService.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseDecoder.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/ClientListenerRegistry.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
https://issues.jboss.org/browse/ISPN-9589
https://issues.jboss.org/browse/ISPN-7087
=> ISPN-9589 Client Listener notifications can deadlock

jcache/tck-runner/src/test/resources/ExcludeList_remote
* Disable tck clear test for listener
https://issues.jboss.org/browse/ISPN-9665
NOTE this does not solve the issue, just disables the test from failing.
=> ISPN-9656 JCache remote notifies listener on clear

documentation/src/main/asciidoc/user_guide/persistence.adoc, documentation/src/main/asciidoc/user_guide/persistence_cli.adoc, documentation/src/main/asciidoc/user_guide/persistence_cluster.adoc, documentation/src/main/asciidoc/user_guide/persistence_custom.adoc, documentation/src/main/asciidoc/user_guide/persistence_jdbc.adoc, documentation/src/main/asciidoc/user_guide/persistence_jpa.adoc, documentation/src/main/asciidoc/user_guide/persistence_leveldb.adoc, documentation/src/main/asciidoc/user_guide/persistence_remote.adoc, documentation/src/main/asciidoc/user_guide/persistence_rocksdb.adoc, documentation/src/main/asciidoc/user_guide/persistence_sfs.adoc, documentation/src/main/asciidoc/user_guide/persistence_sifs.adoc, documentation/src/main/asciidoc/user_guide/persistence_storemigrator.adoc
https://issues.jboss.org/browse/ISPN-9681
Productized documentation should not include details on:
- Segment-aware shared cache stores
- Data Container Segment Striping
- Segmented Off Heap Data Container
=> ISPN-9681 Conditional statements to exclude unsupported features

query/src/test/java/org/infinispan/query/blackbox/ClusteredCacheFSDirectoryTest.java, query/src/test/java/org/infinispan/query/blackbox/LocalCacheAsyncCacheStoreTest.java, query/src/test/java/org/infinispan/query/blackbox/LocalCacheFSDirectoryTest.java, query/src/test/java/org/infinispan/query/blackbox/LocalCachePerfIspnDirConfTest.java, query/src/test/java/org/infinispan/query/blackbox/LocalCachePerfProgrammaticConfTest.java, query/src/test/java/org/infinispan/query/blackbox/LocalCachePerformantConfTest.java, query/src/test/java/org/infinispan/query/blackbox/LocalCacheTest.java, query/src/test/java/org/infinispan/query/dsl/embedded/QueryStringTest.java
https://issues.jboss.org/browse/ISPN-9725
=> [9.3.x] ISPN-9725 Blackbox query tests are failing due to improper teardown that does not take store and index into account

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, core/src/main/java/org/infinispan/executors/LazyInitializingBlockingTaskAwareExecutorService.java, core/src/main/java/org/infinispan/executors/LazyInitializingExecutorService.java, core/src/main/java/org/infinispan/executors/LazyInitializingScheduledExecutorService.java, core/src/main/java/org/infinispan/executors/ManageableExecutorService.java, core/src/main/java/org/infinispan/jmx/AbstractJmxRegistration.java, core/src/main/java/org/infinispan/jmx/ResourceDMBean.java, core/src/test/java/org/infinispan/jmx/CacheManagerMBeanTest.java, server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java, server/core/src/main/java/org/infinispan/server/core/transport/NettyChannelInitializer.java, server/core/src/main/java/org/infinispan/server/core/transport/NettyTransport.java, server/core/src/main/java/org/infinispan/server/core/transport/Transport.java, server/core/src/main/java/org/infinispan/server/core/utils/ManageableThreadPoolExecutorService.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseDecoder.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/jmx/management/JmxManagementIT.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedServer.java, server/rest/src/main/java/org/infinispan/rest/RestServer.java, server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
This adds MBeans for all global executors (notifications, timeout, async, etc) as well as for the worker executors associated with the protocol servers. Since only the Hot Rod server uses the worker executor, I am setting the maximum pool size for REST and Memcached to 1 (as 0 is not a valid argument).
=> ISPN-9708 Expose the executor services through JMX

client/marshaller/kryo/kryo-marshaller-compatibility-bundle/src/test/resources/README.txt, client/marshaller/protostuff/protostuff-marshaller-compatibility-bundle/src/test/resources/README.txt
https://issues.jboss.org/browse/ISPN-9745
Add dummy README.txt files to force the generation of test-source jars.
=> [9.4.x] ISPN-9745 Compatibility bundle modules don't have source jars

client/marshaller/kryo/kryo-marshaller-compatibility-bundle/src/test/resources/README.txt, client/marshaller/protostuff/protostuff-marshaller-compatibility-bundle/src/test/resources/README.txt
https://issues.jboss.org/browse/ISPN-9745
Add dummy README.txt files to force the generation of test-source jars.
=> ISPN-9745 Compatibility bundle modules don't have source jars

server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/BinaryOutputPrinter.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/JSONOutputPrinter.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/TextOutputPrinter.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/XMLOutputPrinter.java, server/rest/src/test/java/org/infinispan/rest/BaseRestOperationsTest.java, server/rest/src/test/java/org/infinispan/rest/RestOperationsOffHeapTest.java, server/rest/src/test/java/org/infinispan/rest/RestOperationsTest.java, server/rest/src/test/java/org/infinispan/rest/TestClass.java
https://issues.jboss.org/browse/ISPN-9707
This fixes the lambda serialization issues with the current implementation, that should eventually be replaced by https://issues.jboss.org/browse/ISPN-9738
=> ISPN-9707 Getting keys via REST fails with SerializationException

core/src/main/java/org/infinispan/persistence/spi/AdvancedCacheLoader.java, core/src/test/java/org/infinispan/persistence/AdvancedCacheLoaderFunctionalTest.java
than 2048 entries
* Use single thread pool temporarily
https://issues.jboss.org/browse/ISPN-9777
=> ISPN-9777 Default AdvancedCacheLoader#publishEntries can hang with more

core/src/main/java/org/infinispan/configuration/cache/L1ConfigurationBuilder.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/configuration/cache/L1ConfigurationBuilderTest.java
eviction
https://issues.jboss.org/browse/ISPN-9297
=> [9.4.x] ISPN-9605 Prevent cache configuration that has L1 and exception based

core/src/main/java/org/infinispan/persistence/spi/AdvancedCacheLoader.java, core/src/test/java/org/infinispan/persistence/AdvancedCacheLoaderFunctionalTest.java
than 2048 entries
* Use single thread pool temporarily
https://issues.jboss.org/browse/ISPN-9777
=> [9.4.x] ISPN-9777 Default AdvancedCacheLoader#publishEntries can hang with more

documentation/src/main/asciidoc/user_guide/compatibility_mode.adoc, documentation/src/main/asciidoc/user_guide/encoding.adoc, documentation/src/main/asciidoc/user_guide/endpoint_interop.adoc, documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc, documentation/src/main/asciidoc/user_guide/server_protocols_memcached.adoc
ISPN-9646 merged into master. Needs backport into 9.4.x. Documentation for protocol interoperability.
=> [9.4.x] Backporting ISPN-9646, Documentation for protocol interop

core/src/main/java/org/infinispan/marshall/exts/DoubleSummaryStatisticsExternalizer.java, core/src/main/java/org/infinispan/marshall/exts/IntSummaryStatisticsExternalizer.java, core/src/main/java/org/infinispan/marshall/exts/LongSummaryStatisticsExternalizer.java, core/src/main/java/org/infinispan/marshall/exts/SecurityActions.java, core/src/test/java/org/infinispan/marshall/exts/AbstractExternalizerTest.java, core/src/test/java/org/infinispan/marshall/exts/DoubleSummaryStatisticsExternalizerTest.java, core/src/test/java/org/infinispan/marshall/exts/IntSummaryStatisticsExternalizerTest.java, core/src/test/java/org/infinispan/marshall/exts/LongSummaryStatisticsExternalizerTest.java
https://issues.jboss.org/browse/ISPN-9720
https://issues.jboss.org/browse/WFLY-11355
Upstream PR: https://github.com/infinispan/infinispan/pull/6426
This is to avoid illegal access warnings on JDK 10+. Three classes were changed, which used reflection to access private fields in JDK types:
* IntSummaryStatisticsExternalizer
* LongSummaryStatisticsExternalizer
* DoubleSummaryStatisticsExternalizer (see bellow for details on this one)
Since JDK 10, relevant JDK types ([Int|Long|Double]SummaryStatistics) have gotten new parametrized constructors, so reflective access to set their inner state is no longer necessary.
The `DoubleSummaryStatistics` case is however somewhat problematic - except for `sum`, `count`, `min` and `max` fields (that are accessible by public API), the externalizer used …
=> ISPN-9720 JDK11: An illegal reflective access operation has occurred

core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
https://issues.jboss.org/browse/ISPN-9798
https://issues.jboss.org/browse/ISPN-9800
As `checkStoreAvailability()` always utilises the volatile `unavailableException` to determine whether the PersistenceManager is available, we don't need to use the writeLock as the `storeStatuses` map is never updated, only the `StoreStatus` itself. ~~However, we do need to introduce a lock to prevent scheduled calls to `pollStoreAvailability` overlapping.~~
=> ISPN-9798 Availability deadlock fixes

core/src/main/java/org/infinispan/stream/impl/LocalStreamManagerImpl.java, core/src/test/java/org/infinispan/stream/DistributedStreamRehashTest.java
caches with non iterator methods
* Fix typo so we add listener on non replicated caches
https://issues.jboss.org/browse/ISPN-9791
=> [9.4.x] ISPN-9791 Distributed Stream rehash can miss entries on non replicated

core/src/main/java/org/infinispan/stream/impl/LocalStreamManagerImpl.java, core/src/test/java/org/infinispan/stream/DistributedStreamRehashTest.java
caches with non iterator methods
* Fix typo so we add listener on non replicated caches
https://issues.jboss.org/browse/ISPN-9791
=> ISPN-9791 Distributed Stream rehash can miss entries on non replicated

core/src/test/java/org/infinispan/manager/AllClusterExecutorTest.java
https://issues.jboss.org/browse/ISPN-9807
I think this one doesn't need a separate PR for 9.4.x ;)
=> ISPN-9807 SingleClusterExecutorTest.testExecutorTriConsumerTimeoutException

build-configuration/bom/pom.xml, build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9809
=> ISPN-9809 Added version.component.console

core/src/main/java/org/infinispan/commands/FlagAffectedCommand.java, core/src/main/java/org/infinispan/container/entries/ReadCommittedEntry.java, core/src/main/java/org/infinispan/container/impl/AbstractDelegatingInternalDataContainer.java, core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java, core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java, core/src/main/java/org/infinispan/container/impl/InternalDataContainer.java, core/src/main/java/org/infinispan/container/impl/InternalDataContainerAdapter.java, core/src/main/java/org/infinispan/container/impl/InternalEntryFactoryImpl.java, core/src/main/java/org/infinispan/container/offheap/SegmentedBoundedOffHeapDataContainer.java, core/src/main/java/org/infinispan/interceptors/distribution/ScatteredDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/PrefetchInterceptor.java, core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/test/java/org/infinispan/statetransfer/StateTransferTimestampsTest.java, tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingInterceptor.java
https://issues.jboss.org/browse/ISPN-4075
The fix is a bit crude because I didn't want to add the timestamps in regular PutKeyValueCommands, but it does the job.
=> ISPN-4075 State transfer should preserve the timestamps of entries 

core/src/main/java/org/infinispan/commands/FlagAffectedCommand.java, core/src/main/java/org/infinispan/commands/write/PutKeyValueCommand.java, core/src/main/java/org/infinispan/container/entries/ReadCommittedEntry.java, core/src/main/java/org/infinispan/container/impl/AbstractDelegatingInternalDataContainer.java, core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java, core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java, core/src/main/java/org/infinispan/container/impl/InternalDataContainer.java, core/src/main/java/org/infinispan/container/impl/InternalDataContainerAdapter.java, core/src/main/java/org/infinispan/container/impl/InternalEntryFactoryImpl.java, core/src/main/java/org/infinispan/container/offheap/SegmentedBoundedOffHeapDataContainer.java, core/src/main/java/org/infinispan/interceptors/distribution/ScatteredDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/PrefetchInterceptor.java, core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/test/java/org/infinispan/statetransfer/StateTransferTimestampsTest.java, tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingInterceptor.java
Backport of https://github.com/infinispan/infinispan/pull/6525
https://issues.jboss.org/browse/ISPN-4075
* Use PutKeyValueCommand with InternalCacheEntry as value to pass the
created and last use timestamps
* Scattered caches also use PutMapCommand with InternalCacheValue values
* Always copy the timestamps when copying entries
* Ignore -1 timestamp values and use current time instead
=> [9.4.x] ISPN-4075 State transfer should preserve the timestamps of entries

pom.xml
https://issues.jboss.org/browse/ISPN-9395
Fix file:/// URL to have 3 slashes, otherwise C: is interpreted
as a host name
For testing see
https://ci.infinispan.org/job/InfinispanAlternateBuilds/job/InfinispanWindows/
=> ISPN-9395 Failures in karaf-maven-plugin on Windows

documentation/src/main/asciidoc/server_guide/configuration.adoc
https://issues.jboss.org/browse/ISPN-9888
=> ISPN-9888 Default JGroups Settings

core/src/main/java/org/infinispan/commands/write/PutKeyValueCommand.java, core/src/main/java/org/infinispan/commands/write/PutMapCommand.java, core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/PrefetchInterceptor.java, core/src/main/java/org/infinispan/metadata/impl/InternalMetadataImpl.java, core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingInterceptor.java
https://issues.jboss.org/browse/ISPN-4075
Use InternalMetadataImpl to store the timestamps instead of an
InternalCacheEntry in PutKeyValueCommand.
=> ISPN-4075 State transfer should preserve the timestamps of entries

core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/remoting/transport/MockTransport.java, core/src/test/java/org/infinispan/scattered/statetransfer/CoordinatorStopTest.java, core/src/test/java/org/infinispan/statetransfer/ConcurrentStartChanelLookupTest.java, core/src/test/java/org/infinispan/statetransfer/ConcurrentStartForkChannelTest.java, core/src/test/java/org/infinispan/statetransfer/CustomChannelLookup.java, core/src/test/java/org/infinispan/statetransfer/ForkChannelRestartTest.java, core/src/test/java/org/infinispan/test/transport/DelayedViewJGroupsTransport.java, core/src/test/java/org/infinispan/topology/ClusterCacheStatusTest.java, core/src/test/java/org/infinispan/topology/ClusterTopologyManagerImplTest.java
https://issues.jboss.org/browse/ISPN-9801
* ClusterTopologyManagerImpl should process new views while waiting
for member hearbeats for a previous view
* Member availability check should ignore nodes that didn't join
any cache
* Test doesn't reproduce the problem described in the issue,
but it's still good to have
* Small changes in other tests
=> ISPN-9801 ClusterTopologyManagerImpl hangs when restarting a FORK node

documentation/src/main/asciidoc/user_guide/configuration.adoc, documentation/src/main/asciidoc/user_guide/rolling_upgrades.adoc
Needs backport to 9.4.x. Rolling upgrades formatting fix. Plus correct level sequence for tuning JGroups.
=> ISPN-9851 Formatting for Rolling Upgrades

Jenkinsfile-release
This change should allow specify the next version in the jenkins release, if such is specified during the build with parameters
=> Should support the nextVersion feature in release

documentation/src/main/asciidoc/user_guide/transactions.adoc
clarify write-skew attribute deprecation
=> [9.4.x] ISPN-9885 Backport

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/StatisticsConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
Statistics options can't be configured with properties. For spring-boot infinispan integration with actuator, this should be possible.
https://issues.jboss.org/browse/ISPN-9969
backport https://github.com/infinispan/infinispan/pull/6684
=> ISPN-9969 Configure statistics with the hotrod-client.properties

core/src/test/java/org/infinispan/functional/AbstractFunctionalTest.java
https://github.com/infinispan/infinispan/pull/6365 broke FunctionalListenersTest because TestNG simplified the inheritance of groups: if a method and its declaring class are both missing the `@Test(groups)`, they don't automatically use the derived class' groups.
=> ISPN-9373 Fix FunctionalListenersTest

core/src/main/java/org/infinispan/health/impl/ClusterHealthImpl.java, core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/test/java/org/infinispan/health/ClusterHealthImplTest.java, server/core/src/main/java/org/infinispan/server/core/transport/NettyTransportConnectionStats.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/AbstractCacheConfigurationService.java
https://issues.jboss.org/browse/ISPN-9667
Previous fix was incomplete, because the getCache() returned null while stopping.
Cache the Transport so we can return the local address even while stopping.
=> ISPN-9667 DefaultCacheManager inconsistent status checks

core/src/main/java/org/infinispan/factories/KnownComponentNames.java
https://issues.jboss.org/browse/ISPN-10049
=> ISPN-10049 Persistence Executor threads should use ProcessorInfo

server/integration/jgroups/src/main/resources/subsystem-templates/cloud-jgroups.xml
This adds dns ping jgroups stack needed when running on okd.
https://issues.jboss.org/browse/ISPN-10005
=> ISPN-10005 stack for dns ping on okd

counter/src/main/java/org/infinispan/counter/impl/CounterModuleLifecycle.java, lock/src/main/java/org/infinispan/lock/EmbeddedClusteredLockManagerFactory.java, lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java, lock/src/main/java/org/infinispan/lock/logging/Log.java, lock/src/test/java/org/infinispan/lock/ClusteredLockWithoutClusterTest.java
Clustered locks work and are needed when we are in clustered mode. 
Log a message and avoid a transport error. More information in the issue
https://issues.jboss.org/browse/ISPN-10019
backport #6736
=> ISPN-10019 Avoid transport exception when using clustered locks

counter/src/main/java/org/infinispan/counter/impl/CounterModuleLifecycle.java, lock/src/main/java/org/infinispan/lock/EmbeddedClusteredLockManagerFactory.java, lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java, lock/src/main/java/org/infinispan/lock/logging/Log.java, lock/src/test/java/org/infinispan/lock/ClusteredLockWithoutClusterTest.java
https://issues.jboss.org/browse/ISPN-10019
Upstream #6735
=> [9.4] ISPN-10019 Avoid transport exception when using clustered locks

commons/src/main/java/org/infinispan/commons/executors/BlockingThreadPoolExecutorFactory.java, core/src/main/java/org/infinispan/factories/KnownComponentNames.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ThreadPoolResource.java
https://issues.jboss.org/browse/ISPN-10040
* Server thread pools now read from embedded
=> ISPN-10040 Embedded and server thread pool defaults should be the same

commons/src/main/java/org/infinispan/commons/executors/BlockingThreadPoolExecutorFactory.java, core/src/main/java/org/infinispan/factories/KnownComponentNames.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ThreadPoolResource.java
https://issues.jboss.org/browse/ISPN-10040
* Server thread pools now read from embedded
Backport of #6816
=> [9.4.x] ISPN-10040 Embedded and server thread pool defaults should be the same

commons-test/src/main/java/org/infinispan/commons/test/JUnitTestListener.java, commons-test/src/main/java/org/infinispan/commons/test/RunningTestsRegistry.java, commons-test/src/main/java/org/infinispan/commons/test/TestNGSuiteChecksTest.java, commons-test/src/main/java/org/infinispan/commons/test/TestNGTestListener.java, commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java, core/pom.xml, core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java, core/src/test/java/org/infinispan/test/fwk/TestResourceTrackingListener.java, documentation/src/main/asciidoc/contributing/tests.adoc, spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/InfinispanTestExecutionListener.java
https://issues.jboss.org/browse/ISPN-10090
* Don't check for leaks in AbstractInfinispanTest
* Change listeners to crash if they detect a leak
(and TestNGSuiteChecksTest didn't detect it first)
* Include TestNGSuiteChecksTest in default profile in core
* Log the file name when dumping threads programmatically (ISPN-10024)
=> ISPN-10090 Allow running TestNG tests without TestNGTestListener

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/AuthHandler.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/Authentication.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseDecoder.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java, server/hotrod/src/main/resources/hotrod.gr
https://issues.jboss.org/browse/ISPN-9841
=> ISPN-9841 Non-blocking Hot Rod authentication

documentation/src/main/asciidoc/user_guide/query.adoc
https://issues.jboss.org/browse/ISPN-10064
=> ISPN-10064, removing reference to JP-QL for Ickle Queries

pom.xml
https://issues.jboss.org/browse/ISPN-10099
Using the default execution allows modules to disable surefire
the same way for Java 8 and for Java 10+
=> ISPN-10099 Use execution default-test instead of java8-test

core/src/main/java/org/infinispan/commands/tx/PrepareCommand.java, core/src/main/java/org/infinispan/configuration/cache/PartitionHandlingConfigurationBuilder.java, core/src/main/java/org/infinispan/distribution/LocalizedCacheTopology.java, core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java, core/src/main/java/org/infinispan/interceptors/impl/InvalidationInterceptor.java, core/src/main/java/org/infinispan/interceptors/locking/AbstractLockingInterceptor.java, core/src/main/java/org/infinispan/interceptors/locking/NonTransactionalLockingInterceptor.java, core/src/main/java/org/infinispan/interceptors/locking/PessimisticLockingInterceptor.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/invalidation/InvalidationSharedStoreTest.java, core/src/test/java/org/infinispan/statetransfer/NonTxStateTransferInvalidationTest.java
https://issues.jboss.org/browse/ISPN-10029
* Lock tx keys on the primary owner
* Keep locking non-tx keys only on the originator
* InvalidationSharedStoreTest tests that global locks protect
the shared store with pessimistic and optimistic locking
* Require partition handling to be disabled in invalidation mode
=>  ISPN-10029 Invalidation locking is not clustered 

documentation/pom.xml, documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc, documentation/src/main/asciidoc/topics/configuration/wfly_extensions.adoc, documentation/src/main/asciidoc/user_guide/integrations.adoc
https://issues.jboss.org/browse/ISPN-10132 
"org.infinispan.server.endpoint:ispn-9.4" is community only.
=> ISPN-10132 removing endpoint extensions module from downstream

documentation/src/main/asciidoc/user_guide/query.adoc
Backport into 9.4.x: https://issues.jboss.org/browse/ISPN-10064
=> [9.4.x] ISPN-10064, removing reference to JP-QL for Ickle Queries

server/integration/src/main/ant/infinispan-server.xml, server/integration/testsuite/pom.xml, server/integration/testsuite/src/test/java/org/infinispan/server/test/rollingupgrades/HotRodRollingUpgradesDistIT.java, server/integration/testsuite/src/test/resources/arquillian.xml, server/integration/testsuite/src/test/resources/config/parts/rolling-upgrades-server-endpoint-9.4.xml
Fixed the configuration, as while the rolling upgrades tests running the servers were messed up.
=> ISPN-10165 - Fix rolling upgrades tests according to latest changes

persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/HotRodTargetMigrator.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/rollingupgrades/HotRodRollingUpgradesDistIT.java, server/integration/testsuite/src/test/java/org/infinispan/server/test/rollingupgrades/HotRodRollingUpgradesIT.java
https://issues.jboss.org/browse/ISPN-10165
=> [9.4] Use old rolling upgrade strategy when protocol < 2.5

core/src/main/java/org/infinispan/interceptors/impl/InvalidationInterceptor.java, core/src/test/java/org/infinispan/invalidation/BaseInvalidationTest.java, core/src/test/java/org/infinispan/invalidation/TxInvalidationLockingTest.java, core/src/test/java/org/infinispan/test/ReplListener.java, documentation/src/main/asciidoc/user_guide/clustering.adoc, hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/NonTxInvalidationInterceptor.java, hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/TxInvalidationInterceptor.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/NaturalIdInvalidationTest.java, hibernate/cache-v51/pom.xml, hibernate/cache-v53/pom.xml
https://issues.jboss.org/browse/ISPN-10029
The original fix didn't set the topology id in non-txt caches, only in tx caches.
=> ISPN-10029 Fix topology id for non-tx invalidation commands

build.bat, commons-test/src/main/java/org/infinispan/commons/test/RunningTestsRegistry.java
https://issues.jboss.org/browse/ISPN-10175
* Remove extra /pid argument from /taskkill
* Add /f argument to force kill
* Log more details when JVM kill fails
* Search for jstack with .exe extension on Windows
* Use mvn.cmd instead of mvn.bat
=> ISPN-10175 Long test killer doesn't kill the JVM on Windows

build.bat, commons-test/src/main/java/org/infinispan/commons/test/RunningTestsRegistry.java
https://issues.jboss.org/browse/ISPN-10175
* Remove extra /pid argument from /taskkill
* Add /f argument to force kill
* Log more details when JVM kill fails
* Search for jstack with .exe extension on Windows
* Use mvn.cmd instead of mvn.bat
Backport of #6903
=> [9.4] ISPN-10175 Long test killer doesn't kill the JVM on Windows

hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/AbstractPartialUpdateTest.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/PartialFutureUpdateTest.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/PartialTombstoneTest.java, hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/impl/Sync.java
https://issues.jboss.org/browse/ISPN-9919
* If tombstones are not applied everywhere, stale data could be left around.
Testing of such situations since it requires failures to be induced at a very particular situation. Not sure what alternatives we have though.
I'll send a PR for 9.4 when we're happy with this.
=> ISPN-9919 Tombstones after update have to be applied everywhere

core/src/main/java/org/infinispan/container/impl/DefaultDataContainer.java, core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationListenerFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreDistListenerFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreListenerFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreListenerFunctionalTest.java
https://issues.jboss.org/browse/ISPN-10074
In clustered caches, maxIdle expiration should be ignored by
executeTask() and iterator(), and expired entries should be returned
until the purge thread removes them from the container.
=> ISPN-10074 DefaultDataContainer executeTask() should ignore maxIdle

feature-pack/server/src/main/resources/modules/org/infinispan/extension/slot/module.xml, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/TransactionManagerProvider.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheConfigurationAdd.java, server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheConfigurationService.java
https://issues.jboss.org/browse/ISPN-10114
Needs backporting to 9.4.x.
=> ISPN-10114 Server managed transactional cache configuration cannot be persisted to global state

core/src/test/java/org/infinispan/functional/distribution/rehash/FunctionalTxTest.java, core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java, integrationtests/osgi/pom.xml, integrationtests/wildfly-modules/pom.xml, pom.xml, server/integration/testsuite/README.txt, server/integration/testsuite/pom.xml
https://issues.jboss.org/browse/ISPN-9748
ISPN-9748 Default transport for the test suite should be same
=> [9.4] ISPN-9748 Default transport for the test suite should be same

core/src/main/java/org/infinispan/container/impl/DefaultDataContainer.java, core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationListenerFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreDistListenerFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreListenerFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreListenerFunctionalTest.java
https://issues.jboss.org/browse/ISPN-10074
In clustered caches, maxIdle expiration should be ignored by
executeTask() and iterator(), and expired entries should be returned
until the purge thread removes them from the container.
Backport of #6799
=> [9.4.x] ISPN-10074 DefaultDataContainer executeTask() should ignore maxIdle

core/src/main/java/org/infinispan/commands/tx/PrepareCommand.java, core/src/main/java/org/infinispan/configuration/cache/PartitionHandlingConfigurationBuilder.java, core/src/main/java/org/infinispan/distribution/LocalizedCacheTopology.java, core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java, core/src/main/java/org/infinispan/interceptors/impl/InvalidationInterceptor.java, core/src/main/java/org/infinispan/interceptors/locking/AbstractLockingInterceptor.java, core/src/main/java/org/infinispan/interceptors/locking/NonTransactionalLockingInterceptor.java, core/src/main/java/org/infinispan/interceptors/locking/PessimisticLockingInterceptor.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/invalidation/BaseInvalidationTest.java, core/src/test/java/org/infinispan/invalidation/InvalidationSharedStoreTest.java, core/src/test/java/org/infinispan/invalidation/TxInvalidationLockingTest.java, core/src/test/java/org/infinispan/statetransfer/NonTxStateTransferInvalidationTest.java, core/src/test/java/org/infinispan/test/ReplListener.java, documentation/src/main/asciidoc/user_guide/clustering.adoc, hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/NonTxInvalidationInterceptor.java, hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/TxInvalidationInterceptor.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/NaturalIdInvalidationTest.java, hibernate/cache-v51/pom.xml, hibernate/cache-v53/pom.xml
https://issues.jboss.org/browse/ISPN-10029
The original fix didn't set the topology id in non-txt caches, only in tx caches.
Backport of https://github.com/infinispan/infinispan/pull/6886
=> [9.4.x] ISPN-10029 Invalidation locking is not clustered

commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitXMLReporter.java
This is a generic way to fix the following problems:
```
org.infinispan.configuration.parsing.UnifiedXmlFileParsingTest#testParseAndConstructUnifiedXmlFile([/home/jenkins/workspace/ispn-testsuite/647d21bf/infinispan/core/target/test-classes/configs/unified/9.4.xml])
org.infinispan.api.APINonTxTest#testLockedStreamActuallyLocks([org.infinispan.api.APINonTxTest$$Lambda$1688/0x0000000100b08440@79ef4571, false])
```
https://issues.jboss.org/browse/ISPN-10148
=> ISPN-10148 - Improve reported testName

commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitXMLReporter.java
Backport https://github.com/infinispan/infinispan/pull/6865
This is a generic way to fix the following problems:
```
org.infinispan.configuration.parsing.UnifiedXmlFileParsingTest#testParseAndConstructUnifiedXmlFile([/home/jenkins/workspace/ispn-testsuite/647d21bf/infinispan/core/target/test-classes/configs/unified/9.4.xml])
org.infinispan.api.APINonTxTest#testLockedStreamActuallyLocks([org.infinispan.api.APINonTxTest$$Lambda$1688/0x0000000100b08440@79ef4571, false])
```
https://issues.jboss.org/browse/ISPN-10148
=> [9.4] ISPN-10148 - Improve reported testName

core/src/test/java/org/infinispan/stats/ClusteredStatsFailureTest.java
https://issues.jboss.org/browse/ISPN-10066
=> [9.4] ISPN-10066 (addendum) ClusteredStatsFailureTest now uses awaitStrict

commons-test/src/main/java/org/infinispan/commons/lambda/NamedLambdas.java, commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitXMLReporter.java, core/src/test/java/org/infinispan/api/APINonTxTest.java, core/src/test/java/org/infinispan/manager/SingleClusterExecutorExecutionPolicyTest.java
https://issues.jboss.org/browse/ISPN-10220
Now the lambda tests will be stored in the XML like:
```xml
<testcase classname="org.infinispan.api.SimpleCacheTest" name="testLockedStreamActuallyLocks([functional-command, true])" time="0.001"/>
<testcase classname="org.infinispan.api.SimpleCacheTest" name="testLockedStreamActuallyLocks([put-async, true])" time="0.001"/>
<testcase classname="org.infinispan.api.SimpleCacheTest" name="testRetainAllMethodOfValuesCollection" time="0.001"/>
<testcase classname="org.infinispan.api.SimpleCacheTest" name="testLockedStreamActuallyLocks([functional-command, false])" time="0.001"/>
```
If the test was not implemented with the named lambda we will have:
```xml
<testcase classname="org.infinispan.api.SimpleCacheTest" …
```
=> ISPN-10220 Create named lambdas to identify which test is running

core/src/test/java/org/infinispan/tx/exception/ExceptionInCommandTest.java
The test returns a RuntimeException instead of throwing it.
=> ISPN-10230 Fix ExceptionInCommandTest

core/src/main/java/org/infinispan/configuration/cache/TransactionConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/TransactionConfigurationBuilder.java, core/src/main/java/org/infinispan/interceptors/totalorder/TotalOrderDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/totalorder/TotalOrderInterceptor.java, core/src/main/java/org/infinispan/interceptors/totalorder/TotalOrderStateTransferInterceptor.java, core/src/main/java/org/infinispan/interceptors/totalorder/TotalOrderVersionedDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/totalorder/TotalOrderVersionedEntryWrappingInterceptor.java, core/src/main/java/org/infinispan/remoting/inboundhandler/TotalOrderTxPerCacheInboundInvocationHandler.java, core/src/main/java/org/infinispan/transaction/TransactionProtocol.java, core/src/main/java/org/infinispan/transaction/impl/RemoteTransaction.java, core/src/main/java/org/infinispan/transaction/impl/TotalOrderRemoteTransactionState.java, core/src/main/java/org/infinispan/transaction/totalorder/TotalOrderLatch.java, core/src/main/java/org/infinispan/transaction/totalorder/TotalOrderManager.java, core/src/main/resources/schema/infinispan-config-10.0.xsd, documentation/src/main/asciidoc/upgrading/upgrading-content.adoc
https://issues.jboss.org/browse/ISPN-10259
Deprecated the configuration and interceptors. There are other classes around (commands) that aren't deprecated (should they be?)
=> ISPN-20259 Deprecate Total Order transactions

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCache.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/AssertsNearCache.java
https://issues.jboss.org/browse/ISPN-10248
Intended for backport to 9.4.x.
=> ISPN-10248 Allow users to customize NearCache behavior

core/src/test/java/org/infinispan/statetransfer/JoinInNewThreadTest.java, core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
https://issues.jboss.org/browse/ISPN-10080
Backport of #6794
=> [9.4.x] ISPN-10080 Test cache managers created in other threads cannot join the cluster with UDP

distribution/src/main/release/all/bin/config-converter.bat
Fix for : https://issues.jboss.org/browse/JDG-2953
Upstream: https://issues.jboss.org/browse/ISPN-10303
=> JDG-2953 ISPN-10303  config-converter.bat script contains wrong transaction library

server/integration/src/main/ant/infinispan-server.xml
https://issues.jboss.org/browse/ISPN-10247
* Save the log to a file and print it to the console after failure
* Check both the hotrod port and the management port when killing server
* Also kill pids reported by jps and ps
=> ISPN-10247 tck-runner module discards server console output

documentation/src/main/asciidoc/server_guide/management.adoc
https://issues.jboss.org/browse/ISPN-10271 
Reopening for correct port with JMX over TLS. Needs backport to 9.4.x.
=> ISPN-10271 Port 9993 for JMX over TLS

documentation/src/main/asciidoc/server_guide/management.adoc
https://issues.jboss.org/browse/ISPN-10271
Reopening for correct port with JMX over TLS.
=> [9.4.x] Backport for ISPN-10271 Port 9993 for JMX over TLS

core/src/main/java/org/infinispan/conflict/impl/DefaultConflictManager.java, core/src/test/java/org/infinispan/conflict/impl/CrashedNodeDuringConflictResolutionTest.java, core/src/test/java/org/infinispan/partitionhandling/BasePartitionHandlingTest.java
https://issues.jboss.org/browse/ISPN-9291
Backport of https://github.com/infinispan/infinispan/pull/6853
* Force STABLE gc before merge to reproduce the problem
* Compute the NAKACK2 digest for the merge view to fix it
=> [9.4] ISPN-9291 BasePartitionHandlingTest.Partition.installMergeView()

spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/provider/SpringCache.java, spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/session/AbstractInfinispanSessionRepository.java, spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanApplicationPublishedBridgeTCK.java, spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanSessionRepositoryTCK.java, spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepository.java, spring/spring5/spring5-embedded/src/test/java/org/infinispan/spring/embedded/session/EmbeddedApplicationPublishedBridgeTest.java, spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepository.java, spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/session/RemoteApplicationPublishedBridgeTest.java
https://issues.jboss.org/browse/ISPN-10224
=> ISPN-10224 Fix session protection

core/src/main/java/org/infinispan/AdvancedCache.java, core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingAdvancedCache.java, core/src/main/java/org/infinispan/cache/impl/CacheImpl.java, core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java, core/src/main/java/org/infinispan/configuration/cache/AbstractConfigurationChildBuilder.java, core/src/main/java/org/infinispan/configuration/cache/AbstractCustomInterceptorsConfigurationChildBuilder.java, core/src/main/java/org/infinispan/configuration/cache/Configuration.java, core/src/main/java/org/infinispan/configuration/cache/ConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/ConfigurationChildBuilder.java, core/src/main/java/org/infinispan/configuration/cache/CustomInterceptorsConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/CustomInterceptorsConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/InterceptorConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/parsing/Parser.java, core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/main/resources/schema/infinispan-config-10.0.xsd, core/src/test/java/org/infinispan/functional/decorators/FunctionalAdvancedCache.java, core/src/test/java/org/infinispan/test/TestingUtil.java, counter/src/main/java/org/infinispan/counter/impl/CounterModuleLifecycle.java, query/src/main/java/org/infinispan/query/impl/LifecycleManager.java, query/src/test/java/org/infinispan/query/blackbox/IndexedCacheRestartTest.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java, tasks/scripting/src/main/java/org/infinispan/scripting/impl/LifecycleCallbacks.java, tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingManagerImpl.java
https://issues.jboss.org/browse/ISPN-10262
ISPN-10262 Deprecate custom interceptors configuration
* Deprecate the custom interceptors configuration
* Warn at startup if custom interceptors are present
* Deprecate AdvancedCache.getAsyncInterceptorChain() 
* Replace interceptors configuration with direct AsyncInterceptorChain
manipulation in all the modules.
=> ISPN-10262 Deprecate custom interceptors configuration

core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java, core/src/main/java/org/infinispan/util/concurrent/BlockingTaskAwareExecutorServiceImpl.java
https://issues.jboss.org/browse/ISPN-10346
* BasicComponentRegistryImpl: Start factories before construct()
* BlockingTaskAwareExecutorServiceImpl: Release permit after rejection
=> ISPN-10346 InitialClusterSizeTest thread leak

core/src/main/java/org/infinispan/executors/LazyInitializingBlockingTaskAwareExecutorService.java, core/src/main/java/org/infinispan/executors/LazyInitializingExecutorService.java, core/src/main/java/org/infinispan/executors/LazyInitializingScheduledExecutorService.java, core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java, core/src/main/java/org/infinispan/util/concurrent/BlockingTaskAwareExecutorServiceImpl.java, core/src/test/java/org/infinispan/remoting/AsynchronousInvocationTest.java
https://issues.jboss.org/browse/ISPN-10363
* Remove cached executors from NamedExecutorFactory
* Move the @Stop methods to the executors themselves
* Don't allow lazy executors to start after stopping
=> ISPN-10363 LazyInitializingExecutorService is not thread-safe

server/rest/src/main/java/org/infinispan/rest/authentication/Authenticator.java, server/rest/src/main/java/org/infinispan/rest/authentication/impl/BasicAuthenticator.java, server/rest/src/main/java/org/infinispan/rest/authentication/impl/ClientCertAuthenticator.java, server/rest/src/main/java/org/infinispan/rest/authentication/impl/VoidAuthenticator.java
https://issues.jboss.org/browse/ISPN-8736
This causes issues with Netty since the the underlying buffer s refcounted.
=> ISPN-8736 REST endpoint authorization

build-configuration/bom/pom.xml, distribution/pom.xml, pom.xml
Removed:
org.infinispan.protostream:sample-domain-definition
org.infinispan.protostream:sample-domain-implementation
org.infinispan:infinispan-jcache-tck-runner
org.infinispan:infinispan-remote
org.infinispan:infinispan-javadoc-embedded
org.infinispan:infinispan-javadoc-remote
See JIRA description for more info.
https://issues.jboss.org/browse/ISPN-10395
=> ISPN-10395 Remove GAV from infinispan-bom and distribution pom

build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10425
=> ISPN-10425 Update Netty and RxJava2 to align with Quarkus dependencies

documentation/src/main/asciidoc/topics/upgrading.adoc, server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java, server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java, server/core/src/test/java/org/infinispan/server/core/AbstractProtocolServerTest.java, server/core/src/test/java/org/infinispan/server/core/configuration/MockServerConfiguration.java, server/core/src/test/java/org/infinispan/server/core/configuration/MockServerConfigurationBuilder.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/HotRodServerConfiguration.java, server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/EndpointSubsystemReader.java, server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/EndpointSubsystemWriter.java, server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/HotRodConnectorResource.java, server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/HotRodSubsystemAdd.java, server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/MemcachedConnectorResource.java, server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/ProtocolServerConnectorResource.java, server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/ProtocolServiceSubsystemAdd.java, server/integration/endpoint/src/main/resources/org/infinispan/server/endpoint/subsystem/LocalDescriptions.properties, server/integration/endpoint/src/test/java/org/infinispan/server/endpoint/EndpointSubsystemTestCase.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedServer.java, server/memcached/src/main/java/org/infinispan/server/memcached/configuration/MemcachedServerConfiguration.java, server/rest/src/main/java/org/infinispan/rest/RestServer.java, server/rest/src/main/java/org/infinispan/rest/configuration/RestServerConfiguration.java, server/router/src/main/java/org/infinispan/server/router/configuration/SinglePortRouterConfiguration.java, server/router/src/main/java/org/infinispan/server/router/configuration/builder/SinglePortRouterBuilder.java, server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
https://issues.jboss.org/browse/ISPN-9422
I've also made sure that different endpoints can actually have different defaults
=> ISPN-9422 Remove Worker Threads property

query/src/test/java/org/infinispan/query/queries/phrases/EmbeddedQueryTest.java, query/src/test/java/org/infinispan/query/queries/phrases/QueryPhrasesTest.java, query/src/test/java/org/infinispan/query/test/Author.java, query/src/test/java/org/infinispan/query/test/Book.java
https://issues.jboss.org/browse/ISPN-10403
This removes some small constructor hacks needed by jdg-functional-tests, which can be done in another way.
Not sure if we want this in 9.4.x also
=> ISPN-10403 Remove unwanted changes

core/src/main/resources/default-configs/default-jgroups-udp.xml, core/src/test/resources/stacks/udp.xml, tools/src/test/resources/udp.xml
https://issues.jboss.org/browse/ISPN-10469
Following the TCP custom `bind_addr` and `bind_port` configuration.
Yes, we have different config attributes when compared with JGroups
=> ISPN-10469 Allow custom bind_addr and bind_port UDP configuration

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java, core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingCache.java, core/src/main/java/org/infinispan/cache/impl/CacheImpl.java, core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java, core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/main/java/org/infinispan/manager/impl/AbstractDelegatingEmbeddedCacheManager.java, core/src/main/java/org/infinispan/notifications/Listenable.java, core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java, core/src/test/java/org/infinispan/functional/decorators/FunctionalAdvancedCache.java, jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
https://issues.jboss.org/browse/ISPN-10491
=> ISPN-10491 Deprecate Listenable.getListeners

pom.xml, tools/pom.xml
* this version is no longer used by any Infinispan module, but 3.23.1-GA is still used by hibernate-search so that one is kept
https://issues.jboss.org/browse/ISPN-10500
=> ISPN-10500 Remove javassist 3.24.1-GA dependency

documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
https://issues.jboss.org/browse/ISPN-10531 
Moving product doc URLs to upstream attributes file.
=> [9.4.x] ISPN-10531 product doc URL attributes

server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java, server/core/src/main/java/org/infinispan/server/core/SecurityActions.java, server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java, server/rest/src/main/java/org/infinispan/rest/cachemanager/SecurityActions.java
https://issues.jboss.org/browse/ISPN-9599
I forgot to backport these RestServer fixes to 9.4.x and RESTBasicSecurityIT is failing because of them.
=> [9.4.x] ISPN-9599 Fix RestServer startup with security enabled

integrationtests/wildfly-modules/pom.xml, integrationtests/wildfly-modules/src/test/resources/infinispan-custom.xml, jcache/tck-runner/pom.xml, server/integration/src/main/ant/infinispan-server.xml
Replaced Infinispan Wildfly Server with ServerNG in JCache remote tests and WildFly modules integration tests.
For Wildfly modules integration tests added custom infinispan configuration file for defining default cache as it is used by tests.
=> ISPN-10586 - Use ServerNG in the testsuite

documentation/src/main/asciidoc/topics/rest_api_v2.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_configuration.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_stats.adoc, server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java, server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java, server/rest/src/main/java/org/infinispan/rest/RestServer.java, server/rest/src/main/java/org/infinispan/rest/framework/ResourceManager.java, server/rest/src/main/java/org/infinispan/rest/framework/impl/InvocationImpl.java, server/rest/src/main/java/org/infinispan/rest/framework/impl/ResourceManagerImpl.java, server/rest/src/main/java/org/infinispan/rest/framework/impl/ResourceNode.java, server/rest/src/main/java/org/infinispan/rest/logging/Log.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/main/java/org/infinispan/rest/resources/StaticFileResource.java, server/rest/src/main/resources/index.html, server/rest/src/test/java/org/infinispan/rest/framework/RestDispatcherTest.java, server/rest/src/test/java/org/infinispan/rest/framework/impl/ResourceManagerImplTest.java, server/rest/src/test/java/org/infinispan/rest/resources/BaseCacheResourceTest.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java, server/rest/src/test/java/org/infinispan/rest/resources/StaticResourceTest.java
https://issues.jboss.org/browse/ISPN-10589
* Improved validation during registration of REST resources to detect ambiguous paths
* Fixed path errors: cache stats/config conflicting with operations involving keys and splash screen conflicting with rest v1 API
* Moved Splash screen and static resources from ```/rest``` to ```/```
=> ISPN-10589 REST Resources allow for ambiguous paths

documentation/src/main/asciidoc/topics/security.adoc
https://issues.jboss.org/browse/ISPN-10624
ISPN-10624 Documentation Global security authorization should be enabled if cache authorization enabled
=> ISPN-10624 Documentation Global security authorization should be enabled

server/runtime/pom.xml, server/runtime/src/test/java/org/infinispan/server/unit/configuration/ServerEventLoggerTest.java
https://issues.jboss.org/browse/ISPN-10611
* Enable the XML report in the surefire configuration
* Remove TestNG dependency in ServerEventLoggerTest
=> ISPN-10611 Enable server runtime surefire reports

build-configuration/pom.xml, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/marshallers/MarshallerRegistration.java, commons/src/main/java/org/infinispan/commons/marshall/ProtoStreamTypeIds.java, object-filter/src/test/java/org/infinispan/objectfilter/test/model/MarshallerRegistration.java, remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/impl/MarshallerRegistration.java
https://issues.jboss.org/browse/ISPN-10643
Aalso upgrades gson to 2.8.5 to use the latest, and align with newest protostream.
https://issues.jboss.org/browse/ISPN-10648
=> ISPN-10643 Upgrade protostream to 4.3.0.Alpha12

documentation/src/main/asciidoc/topics/con_server.adoc, documentation/src/main/asciidoc/topics/faq_content.adoc, documentation/src/main/asciidoc/topics/integrations.adoc, documentation/src/main/asciidoc/topics/security_server.adoc, documentation/src/main/asciidoc/topics/server_tasks.adoc
https://issues.jboss.org/browse/ISPN-10564
Removes references to WildFly from 10.x documentation. Keeps WildFly modules and integrations topics (Hibernate L2C). 
Sections on getting server health via CLI and REST will be updated as part of https://issues.jboss.org/browse/ISPN-10642
=> ISPN-10564 removing wildfly references

documentation/src/main/asciidoc/topics/rest_api_v2.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_keys.adoc, server/rest/src/main/java/org/infinispan/rest/CacheInputStream.java, server/rest/src/main/java/org/infinispan/rest/NettyRestResponse.java, server/rest/src/main/java/org/infinispan/rest/ResponseWriter.java, server/rest/src/main/java/org/infinispan/rest/logging/Log.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.jboss.org/browse/ISPN-10376
Uses HTTP chunked + KeepAlive + CacheStreams to stream the keys to the client efficiently
=> ISPN-10376 Optimize operation to get keys from a cache

build-configuration/bom/pom.xml, integrationtests/wildfly-modules/pom.xml, integrationtests/wildfly-modules/src/test/java/org/infinispan/test/integration/as/InfinispanStoreRocksDBIT.java
https://issues.jboss.org/browse/ISPN-10685
I've also added server/runtime as a dependency as running the test after `mvn clean install -am -pl integrationtests/widlfly-modules` fails otherwise.
=> InfinispanStoreRocksDBIT Fix

server/runtime/src/main/ant/infinispan-server.xml
https://issues.jboss.org/browse/ISPN-10774
Kill only the server process listening on the HotRod port,
not clients connected to it.
=> ISPN-10774 kill-server Ant task kills clients too

server/runtime/src/main/java/org/infinispan/server/Bootstrap.java, server/runtime/src/main/server/bin/common.bat, server/runtime/src/main/server/bin/common.sh
https://issues.jboss.org/browse/ISPN-10788
@ryanemerson @diegolovison 
This is what it looks like
```
18:22:20,066 INFO  [BOOT] (main) JVM OpenJDK 64-Bit Server VM Ubuntu 11.0.5-ea+10-post-Ubuntu-0ubuntu1
18:22:20,083 INFO  [BOOT] (main) JVM arguments = -Xms64m -Xmx512m -XX:MetaspaceSize=32M -XX:MaxMetaspaceSize=64m -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Dvisualvm.display.name=infinispan-server -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dinfinispan.server.home.path=/home/tst/Work/Infinispan/infinispan/server/runtime/target/infinispan-server-10.0.0-SNAPSHOT
18:22:20,129 INFO  [org.infinispan.SERVER] (main) ISPN080000: Infinispan Server starting
18:22:20,130 INFO  [org.infinispan.SERVER] (main) ISPN080017: Server configuration: …
```
=> ISPN-10788 Use logger to display JVM information on Server boot

build-configuration/pom.xml, persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/DatabaseType.java, persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/connectionfactory/PooledConnectionFactory.java, persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/TableManagerFactory.java, pom.xml, server/runtime/TESTING.md, server/runtime/pom.xml, server/runtime/src/main/java/org/infinispan/server/Extensions.java, server/runtime/src/test/java/org/infinispan/server/persistence/PersistenceIT.java, server/runtime/src/test/java/org/infinispan/server/persistence/PooledConnectionOperations.java, server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java, server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerTestConfiguration.java, server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerTestMethodRule.java, server/runtime/src/test/java/org/infinispan/server/test/category/Persistence.java, server/runtime/src/test/java/org/infinispan/server/test/persistence/ContainerDatabase.java, server/runtime/src/test/java/org/infinispan/server/test/persistence/Database.java, server/runtime/src/test/java/org/infinispan/server/test/persistence/DatabaseServerRule.java, server/runtime/src/test/java/org/infinispan/server/test/persistence/ExternalDatabase.java, server/runtime/src/test/resources/cli/pcache.xml, server/runtime/src/test/resources/database/db2.properties, server/runtime/src/test/resources/database/h2.properties, server/runtime/src/test/resources/database/mariadb.properties, server/runtime/src/test/resources/database/mysql.properties, server/runtime/src/test/resources/database/oracle.properties, server/runtime/src/test/resources/database/postgres.properties, server/runtime/src/test/resources/database/sqlserver.properties
https://issues.jboss.org/browse/ISPN-10558
This now runs server DB tests against containerized H2, MySQL and PostgreSQL.
=> ISPN-10558 ServerNG add database rules

javadoc/javadoc-all/pom.xml
https://issues.jboss.org/browse/ISPN-10815
This fixes the master build.
=> ISPN-10815 Javadoc missing jboss-marshalling dependency

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientListenerWithFilterAndProtobufTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/OldClientCustomEventsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/BaseMultiServerRemoteIteratorTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/ProtobufRemoteIteratorTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/SingleServerRemoteIteratorTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/marshallers/MarshallerRegistration.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/marshallers/TestDomainSCI.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/SingleHotRodServerTest.java, core/src/main/java/org/infinispan/configuration/global/SerializationConfigurationBuilder.java, documentation/src/main/asciidoc/topics/code_examples/ClientProtoStreamMarshaller.java, documentation/src/main/asciidoc/topics/code_examples/RemoteQuery.java, integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointsCacheFactory.java, integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/JsonIndexingProtobufStoreTest.java, integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/JsonPojoStoreTest.java, integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/ProtoRegistrationJsonTest.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java
https://issues.jboss.org/browse/ISPN-10831
https://issues.jboss.org/browse/ISPN-10832
https://issues.jboss.org/browse/ISPN-10833
https://issues.jboss.org/browse/ISPN-10834
This will be followed up by https://issues.jboss.org/browse/ISPN-10830 which will update all of the client tests to properly use the server-side SCI configuration, but this fixes the tests for now.
=> ISPN-10831 Hotrod-Client testsuite throws IllegalArgumentExceptions.

core/src/test/java/org/infinispan/security/BaseAuthorizationTest.java, core/src/test/java/org/infinispan/security/CacheAuthorizationTest.java, core/src/test/java/org/infinispan/security/CacheManagerAuthorizationTest.java
ISPN-9599 DefaultCacheManager.getGlobalComponentRegistry should require ADMIN permission
https://issues.jboss.org/browse/ISPN-9599
=> ISPN-9599 DefaultCacheManager.getGlobalComponentRegistry should require ADMIN permission

core/src/test/java/org/infinispan/security/BaseAuthorizationTest.java, core/src/test/java/org/infinispan/security/CacheAuthorizationTest.java, core/src/test/java/org/infinispan/security/CacheManagerAuthorizationTest.java
https://issues.jboss.org/browse/ISPN-9599
ISPN-9599 DefaultCacheManager.getGlobalComponentRegistry should require ADMIN permission
=> [9.4] ISPN-9599 DefaultCacheManager.getGlobalComponentRegistry should require ADMIN permission

wildfly/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-10866
This is necessary as the wildfly `InfinispanExtension` does not allow serialization to be configured via the DMR or XML. Therefore, we default to the old behaviour of using jboss-marshalling.
=> ISPN-10866 Force Infinispan Wildfly extension to use jboss marshalling

core/src/test/java/org/infinispan/distribution/DistStorePreloadTest.java, core/src/test/java/org/infinispan/invalidation/InvalidationPreloadTest.java
https://issues.jboss.org/browse/ISPN-9140
Already fixed, only adding a test.
=> Test for ISPN-9140 Topology id missing during preloading with JpaStore 

core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
https://issues.jboss.org/browse/ISPN-10855
My initial commit for ISPN-10855 simplified the handling of `@InCacheMode` and `@InTransactionMode` annotations so you can't add a new cache mode just for one method, but I made a mistake and I skipped running all the test methods when the class wasn't annotated with `@InCacheMode` or `@InTransactionMode`.
=> ISPN-10855 Run all test methods when the class isn't annotated @InCacheMode

server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
https://issues.jboss.org/browse/ISPN-10912
=> ISPN-10912 HotRod server retries CheckAddressTask indefinitely during shutdown

core/src/test/java/org/infinispan/distribution/RemoteGetFailureTest.java, core/src/test/java/org/infinispan/partitionhandling/BasePartitionHandlingTest.java, core/src/test/resources/configs/xsite/bridge.xml, core/src/test/resources/configs/xsite/xsite-inline-test.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/udp.xml, hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml, tools/src/test/resources/udp.xml
https://issues.jboss.org/browse/ISPN-10937
Reduce GMS.max_join_attempts to work around JGRP-2398
=> ISPN-10937 CleanupAfterMethod tests take a very long time

Jenkinsfile, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, server/runtime/pom.xml, server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java, server/runtime/src/test/java/org/infinispan/server/test/ContainerRemoteCacheManager.java, server/runtime/src/test/java/org/infinispan/server/test/ContainerUtil.java, server/runtime/src/test/java/org/infinispan/server/test/EmbeddedInfinispanServerDriver.java, server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerDriver.java, server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerRule.java
https://issues.jboss.org/browse/ISPN-10567
=> ISPN-10567 Allow container exposed ports when CONTAINER is the server driver

server/runtime/src/test/java/org/infinispan/server/cli/CliIT.java, server/runtime/src/test/java/org/infinispan/server/extensions/ExtensionsIT.java, server/runtime/src/test/java/org/infinispan/server/functional/ClusteredIT.java, server/runtime/src/test/java/org/infinispan/server/functional/ShutdownRestIT.java, server/runtime/src/test/java/org/infinispan/server/persistence/PersistenceIT.java, server/runtime/src/test/java/org/infinispan/server/resilience/GracefulShutdownRestartIT.java, server/runtime/src/test/java/org/infinispan/server/resilience/ResilienceIT.java, server/runtime/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java, server/runtime/src/test/java/org/infinispan/server/security/AuthenticationKeyCloakIT.java, server/runtime/src/test/java/org/infinispan/server/security/AuthenticationLDAPIT.java, server/runtime/src/test/java/org/infinispan/server/security/AuthenticationTLSIT.java, server/runtime/src/test/java/org/infinispan/server/security/AuthorizationLDAPIT.java, server/runtime/src/test/java/org/infinispan/server/security/authentication/AuthenticationIT.java, server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerRule.java, server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerRuleConfigurationBuilder.java, server/runtime/src/test/java/org/infinispan/server/test/LazyInfinispanServerDriver.java
https://issues.jboss.org/browse/ISPN-10879
`ClassRule` constructors should be trivial and complex objects be initialized in the `TestRule#apply` method.
=> ISPN-10879 Fix PersistenceIT random failures

commons/src/main/java/org/infinispan/commons/util/ReflectionUtil.java, commons/src/main/java/org/infinispan/commons/util/SecurityActions.java, core/src/main/java/org/infinispan/distribution/group/GroupManagerImpl.java, core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java, core/src/main/java/org/infinispan/factories/SecurityActions.java
Hi @tristantarrant  as discussed, here is a backport of [ISPN-9600](https://github.com/johnpoth/infinispan/pull/new/ISPN-9600) to the 8.2.x branch. cc @danberindei 
`maven clean install` passes sucessfully (except for some previously failing tests described in https://github.com/infinispan/infinispan/pull/6492). 
Thanks!
(cherry picked from commit 7bdc2822ccf79127a488130239c49a5e944e3ca2)
Conflicts:
commons/src/main/java/org/infinispan/commons/util/ReflectionUtil.java
commons/src/main/java/org/infinispan/commons/util/SecurityActions.java
core/src/main/java/org/infinispan/distribution/group/impl/GroupManagerImpl.java
core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java
core/src/test/java/org/infinispan/test/TestingUtil.java
=> [8.2] ISPN-9600 ReflectionUtil.invokeAccessibly should not be public

commons/src/main/java/org/infinispan/commons/util/concurrent/BlockingRejectedExecutionHandler.java, commons/src/main/java/org/infinispan/commons/util/concurrent/CacheBackpressureFullException.java, core/src/test/java/org/infinispan/reactive/RxJavaPublisherTest.java
* Use CacheBackpressureFullException instead of RejectedExecutionException
https://issues.jboss.org/browse/ISPN-10943
=> ISPN-10943 Handle thread pool queue rejection when invoking rxjava code

server/rest/src/main/java/org/infinispan/rest/ALPNHandler.java, server/rest/src/main/java/org/infinispan/rest/configuration/CorsConfigurationBuilder.java, server/rest/src/main/java/org/infinispan/rest/configuration/RestServerConfigurationBuilder.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java, server/rest/src/test/java/org/infinispan/rest/search/IndexedRestSearchTest.java
https://issues.jboss.org/browse/ISPN-10967
=> ISPN-10967 CORS rules for localhost don't take offset into account

documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc, server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
https://issues.jboss.org/browse/ISPN-11001
=> ISPN-11001 Get config templates

client/rest-client/src/main/java/org/infinispan/client/rest/RestResponse.java, server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java, server/rest/src/test/java/org/infinispan/rest/helper/RestResponses.java, server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
https://issues.jboss.org/browse/ISPN-11035
* Use push-state-status to wait for xsite state transfer end
* Add RestResponses with helper methods to close responses
* Reduce the number of entries in testCancelPushState
* Fix unchecked warnings
=> ISPN-11035 XSiteResourceTest.testPushAllCaches random failures

persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBExpirationConfiguration.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBExpirationConfigurationBuilder.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfiguration.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfigurationBuilder.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfigurationParser.java, persistence/rocksdb/src/main/resources/schema/infinispan-cachestore-rocksdb-config-10.1.xsd
https://issues.jboss.org/browse/ISPN-10963
When we have the following running on infinispan/master:
```java
cacheManager.defineConfiguration("weather", new ConfigurationBuilder()
.persistence()
.addStore(RocksDBStoreConfigurationBuilder.class)
.location("target/data")
.expiredLocation("target/expired")
.expiration().lifespan(5, TimeUnit.SECONDS)
.build());
cache = cacheManager.getCache("weather");
int max = 10001;
for (int i=0; i<max; i++) {
cache.put(UUID.randomUUID().toString(), UUID.randomUUID().toString());
}
```
The test took 60478ms. The max could be the following but not 10001
- 9999 = 1773 ms
- 10000 = 1797 ms
The ms values are from my local laptop not running in the perf lab. It just "show the problem".
The other changes are allowing we create a custom RocksDBStore that can use …
=> ISPN-10963 Remove blocking queue from RocksDBStore

cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java, client/rest-client/src/main/java/org/infinispan/client/rest/RestTaskClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestTaskClientOkHttp.java, documentation/src/main/asciidoc/topics/ref_rest_server_tasks.adoc, server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java, server/rest/src/main/java/org/infinispan/rest/framework/RestRequest.java, server/rest/src/main/java/org/infinispan/rest/framework/impl/SimpleRequest.java, server/rest/src/main/java/org/infinispan/rest/resources/TasksResource.java, server/runtime/src/test/java/org/infinispan/server/functional/RestOperations.java, tasks/manager/src/main/java/org/infinispan/tasks/TaskManager.java, tasks/manager/src/main/java/org/infinispan/tasks/impl/TaskManagerImpl.java
https://issues.redhat.com/browse/ISPN-11042
=> ISPN-11042 TaskResource should allow filtering admin tasks

core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
https://issues.redhat.com/browse/ISPN-10975
=> ISPN-10975 Transactional cache will slow down the expiration reaper

core/src/main/java/org/infinispan/scattered/ScatteredVersionManager.java, core/src/main/java/org/infinispan/scattered/impl/ScatteredVersionManagerImpl.java, core/src/test/java/org/infinispan/scattered/stream/ScatteredStreamIteratorTest.java, core/src/test/java/org/infinispan/stream/BaseSetupStreamIteratorTest.java, core/src/test/java/org/infinispan/stream/DistributedStreamIteratorTest.java, core/src/test/java/org/infinispan/test/Mocks.java
https://issues.redhat.com/browse/ISPN-10984
With awaitInitialTransfer disabled, publisher requests can arrive
during the initial state transfer, and in scattered caches
they would fail with StackOverflowError.
Publisher requests will still block for the initial transfer to end
because of ISPN-10864.
=> ISPN-10984 Scattered cache distributed streams stack overflow

core/src/main/java/org/infinispan/scattered/ScatteredVersionManager.java, core/src/main/java/org/infinispan/scattered/impl/ScatteredVersionManagerImpl.java, core/src/test/java/org/infinispan/scattered/stream/ScatteredStreamIteratorTest.java, core/src/test/java/org/infinispan/stream/BaseSetupStreamIteratorTest.java, core/src/test/java/org/infinispan/stream/DistributedStreamIteratorTest.java, core/src/test/java/org/infinispan/test/Mocks.java
https://issues.redhat.com/browse/ISPN-10984
With awaitInitialTransfer disabled, publisher requests can arrive
during the initial state transfer, and in scattered caches
they would fail with StackOverflowError.
Publisher requests will still block for the initial transfer to end
because of ISPN-10864.
=> [9.4.x] ISPN-10984 Scattered cache distributed streams stack overflow

Jenkinsfile
https://issues.redhat.com/browse/ISPN-11082
preferContainerExposedPorts is only required when running on MAC
=> ISPN-11082 Remove preferContainerExposedPorts from Jenkinsfile

server/rest/src/main/java/org/infinispan/rest/RestServer.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/EntrySetFormatter.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/OutputPrinter.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/BinaryOutputPrinter.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/Escaper.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/JSONOutputPrinter.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/TextOutputPrinter.java, server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/XMLOutputPrinter.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResource.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceQueryAction.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
https://issues.redhat.com/browse/ISPN-11006
This was erroneously merged in 10.x but the removal should be targeted for 11.0, since it was only deprecated in 10.0
This is a partial revert: it disables the bulk get operation which is broken anyway.
=> Partially revert "ISPN-11006 Remove REST v1 API"

core/src/main/java/org/infinispan/jmx/ResourceDMBean.java, core/src/main/java/org/infinispan/metrics/impl/ApplicationMetricsRegistry.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/main/resources/io/smallrye/metrics/base-metrics.properties, core/src/main/resources/io/smallrye/metrics/vendor-metrics.properties, server/runtime/src/test/java/org/infinispan/server/functional/RestMetricsResource.java
https://issues.redhat.com/browse/ISPN-11106
=> ISPN-11106 Export 'base' and 'vendor' microprofile metric registries

query-dsl/src/main/java/org/infinispan/query/dsl/Query.java
Please do not close the jira. This PR only deprecates the method in question.
https://issues.redhat.com/browse/ISPN-6162
=> ISPN-6162 Deprecate Query.getResultSize() method

commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitXMLReporter.java, commons-test/src/main/java/org/infinispan/commons/test/TestNGTestListener.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/AbstractGeneralDataRegionTest.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/TestDisabledIn53.java, hibernate/cache-v51/pom.xml, hibernate/cache-v53/pom.xml, hibernate/pom.xml
https://issues.redhat.com/browse/ISPN-10085
Replaces #7707, adds 2 commits:
* Properly exclude Hibernate 5.1-only tests in 5.3
* Shorten JUnit test names in TestNGTestListener
=> ISPN-10085 Hibernate51 and Hibernate53 should not report the same test name

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InvalidatedNearRemoteCache.java
https://issues.redhat.com/browse/ISPN-11140
=> ISPN-11140 RemoteCache w/near-cache throws InstanceAlreadyExistsException following restart

query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
* should use org.infinispan.query.logging.Log
https://issues.redhat.com/browse/ISPN-11159
=> [9.4.x] ISPN-11159 QueryInterceptor uses the wrong logger

documentation/src/main/asciidoc/topics/eviction.adoc
https://issues.redhat.com/browse/ISPN-11164
Needs backport to 9.4.x to hit downstream 7.3.5.
=> ISPN-11164 clustered max idle doc update

query/src/main/java/org/infinispan/query/SearchManager.java, query/src/main/java/org/infinispan/query/impl/SearchManagerImpl.java
https://issues.redhat.com/browse/ISPN-11155
From now on, there is no "Clustered Query" anymore. Let's erase this term from the collective mindset. If you are temped to say "Clustered Query", just say "Query". :smile:
=> ISPN-11555 Remove ClusteredQuery from the API

server/runtime/src/test/java/org/infinispan/server/test/Util.java, server/runtime/src/test/java/org/infinispan/server/unit/configuration/ServerEventLoggerTest.java
https://issues.redhat.com/browse/ISPN-7744
Events are inserted into the event log cache asynchronously,
the test should not assume they are immediately available.
=> ISPN-7744 ServerEventLoggerTest fails intermittently

core/src/test/java/org/infinispan/distribution/rehash/NonTxBackupOwnerBecomingPrimaryOwnerTest.java, core/src/test/java/org/infinispan/distribution/rehash/NonTxPrimaryOwnerBecomingNonOwnerTest.java, core/src/test/java/org/infinispan/eviction/impl/EvictionWithConcurrentOperationsTest.java, core/src/test/java/org/infinispan/eviction/impl/EvictionWithPassivationAndConcurrentOperationsTest.java, core/src/test/java/org/infinispan/test/fwk/CheckPoint.java
https://issues.redhat.com/browse/ISPN-11114
* Only block the topology updates the test needs to block.
* Remove CheckPoint.triggerAll()
Because it triggers all events that were already blocked,
the set of triggered events can change depending on what
other threads are doing, making it non-deterministic.
=> ISPN-11114 NonTxBackupOwnerBecomingPrimaryOwnerTest takes too long

commons/src/main/java/org/infinispan/commons/dataconversion/EncoderIds.java, commons/src/main/java/org/infinispan/commons/dataconversion/Transcoder.java, commons/src/main/java/org/infinispan/commons/dataconversion/WrapperIds.java, core/src/main/java/org/infinispan/encoding/DataConversion.java, core/src/main/java/org/infinispan/factories/EncoderRegistryFactory.java, core/src/main/java/org/infinispan/factories/InternalCacheFactory.java, core/src/main/java/org/infinispan/marshall/core/EncoderRegistry.java, core/src/main/java/org/infinispan/marshall/core/EncoderRegistryImpl.java
https://issues.redhat.com/browse/ISPN-11231
* Register transcoder adapter for global marshaller only once
* Cache transcoders in a map by source and target media type
* Look up encoders and wrappers directly by id
* Don't allow injection in the static encoders
=> ISPN-11231 Transcoder lookup is inefficient

core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java, core/src/main/java/org/infinispan/topology/CacheJoinInfo.java, core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/test/java/org/infinispan/partitionhandling/impl/PreferAvailabilityStrategyTest.java, core/src/test/java/org/infinispan/topology/ClusterCacheStatusTest.java, core/src/test/java/org/infinispan/topology/ClusterTopologyManagerImplTest.java, core/src/test/java/org/infinispan/topology/TestClusterCacheStatus.java
https://issues.jboss.org/browse/ISPN-11259
@danberindei As well as reducing the `CacheJoinInfo` payload size, this also benefits [ISPN-9622](https://issues.redhat.com/browse/ISPN-9622) as it's one less polymorphic variable to handle.
=> ISPN-11259 Remove Hash implementation from CacheJoinInfo

commons/src/main/java/org/infinispan/commons/dataconversion/EncoderIds.java, commons/src/main/java/org/infinispan/commons/dataconversion/Transcoder.java, commons/src/main/java/org/infinispan/commons/dataconversion/WrapperIds.java, core/src/main/java/org/infinispan/encoding/DataConversion.java, core/src/main/java/org/infinispan/factories/EncoderRegistryFactory.java, core/src/main/java/org/infinispan/factories/InternalCacheFactory.java, core/src/main/java/org/infinispan/marshall/core/EncoderRegistry.java, core/src/main/java/org/infinispan/marshall/core/EncoderRegistryImpl.java
https://issues.redhat.com/browse/ISPN-11231
* Register transcoder adapter for global marshaller only once
* Cache transcoders in a map by source and target media type
* Look up encoders and wrappers directly by id
* Don't allow injection in the static encoders
=> [10.1.x] ISPN-11231 Transcoder lookup is inefficient

commons/src/main/java/org/infinispan/commons/dataconversion/EncoderIds.java, commons/src/main/java/org/infinispan/commons/dataconversion/Transcoder.java, commons/src/main/java/org/infinispan/commons/dataconversion/WrapperIds.java, core/src/main/java/org/infinispan/encoding/DataConversion.java, core/src/main/java/org/infinispan/factories/EncoderRegistryFactory.java, core/src/main/java/org/infinispan/factories/InternalCacheFactory.java, core/src/main/java/org/infinispan/marshall/core/EncoderRegistry.java, core/src/main/java/org/infinispan/marshall/core/EncoderRegistryImpl.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodClient.java
https://issues.redhat.com/browse/ISPN-11231
* Register transcoder adapter for global marshaller only once
* Cache transcoders in a map by source and target media type
* Look up encoders and wrappers directly by id
* Don't allow injection in the static encoders
=> [9.4.x] ISPN-11231 Transcoder lookup is inefficient

jcache/tck-runner-embedded/pom.xml, jcache/tck-runner-embedded/src/test/resources/META-INF/beans.xml
https://issues.redhat.com/browse/ISPN-10804
Define system property `org.jboss.weld.se.archive.isolation`
to get the CDI 1.0 behaviour or applying the interceptors
fro any beans.xml to all the beans in the application.
=> ISPN-10804 JCache tck-runner does not run interception tests

cli/cli-client/src/main/java/org/infinispan/cli/commands/Site.java, cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java, cli/cli-client/src/main/resources/help/site.adoc
https://issues.redhat.com/browse/ISPN-11282
It was using `CliCommand.NAME` instead of `Site.NAME`. I changed `Site.NAME` => `Site.SITE_NAME` to avoid confusion.
Updated the help message.
=> ISPN-11282 CLI: site command isn't working properly

pom.xml, server/runtime/TESTING.md, server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java, server/runtime/src/test/java/org/infinispan/server/test/ServerRunMode.java, server/runtime/src/test/java/org/infinispan/server/test/TestSystemPropertyNames.java
https://issues.redhat.com/browse/ISPN-11290
To test this run a container test with the following properties
-Dorg.infinispan.test.server.container.usePrebuiltServer=true -Dorg.infinispan.test.server.container.baseImageName=infinispan/server:10.1.1.Final-3
Backport of #7843 also includes a fixed backport of ISPN-11071
=> [10.1] ISPN-11290 Optionally use a prebuilt server from the supplied container

server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
https://issues.redhat.com/browse/ISPN-11303
The local-non-blocking get was breaking the hit/miss statistics
when client requests didn't go to the primary owner,
e.g. with a load balancer between the clients and the servers.
=> [9.4.x] ISPN-11303 Local non-blocking get breaks hit/miss statistics

core/src/main/java/org/infinispan/util/concurrent/ConditionFuture.java, core/src/test/java/org/infinispan/test/concurrent/MatchCountMatcher.java, core/src/test/java/org/infinispan/util/concurrent/ConditionFutureTest.java
https://issues.redhat.com/browse/ISPN-11280
https://issues.redhat.com/browse/ISPN-11296
=>  ISPN-11280 ConcurrentModificationException in ConditionFuture

cloud/src/main/resources/default-configs/default-jgroups-ec2.xml, cloud/src/main/resources/default-configs/default-jgroups-google.xml, cloud/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/main/resources/default-configs/default-jgroups-udp.xml, core/src/test/resources/configs/xsite/bridge.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/tcp_mping/tcp1.xml, core/src/test/resources/stacks/tcp_mping/tcp2.xml, core/src/test/resources/stacks/udp.xml, demos/gui/src/main/release/etc/config/jgroups-relay1.xml, demos/gui/src/main/release/etc/config/jgroups-relay2.xml, demos/gui/src/main/release/etc/config/jgroups-tcp.xml, documentation/src/main/asciidoc/topics/jgroups/jgroups_default_stack.adoc, hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml, integrationtests/wildfly-modules/src/test/resources/as-config/standalone/configuration/standalone-test.xml, persistence/jdbc/src/test/resources/configs/as7/jdbc-standalone.xml, server/integration/jgroups/src/main/resources/jgroups-defaults.xml, server/integration/jgroups/src/main/resources/subsystem-templates/infinispan-jgroups.xml
https://issues.redhat.com/browse/ISPN-11377
* Increase max_credits to 4MB to compensate for the queue.
* Embedded already used UFC/MFC, only server needed to change
* Server was also missing UFC from the TCP stacks
=> [9.4.x] ISPN-11377 Change default flow control back to UFC/MFC

documentation/src/main/asciidoc/topics/con_expiration.adoc
doc update for https://issues.redhat.com/browse/ISPN-9082 
needs backport to 10.1.x
=> ISPN-9082 max idle with off-heap

core/src/main/java/org/infinispan/stream/impl/IteratorHandler.java, core/src/test/java/org/infinispan/jmx/JmxStatsFunctionalTest.java, core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java, counter/src/test/java/org/infinispan/counter/WeakCounterWithZeroCapacityNodesTest.java
https://issues.redhat.com/browse/ISPN-11467
https://issues.redhat.com/browse/ISPN-11435
=> [10.1.x] ISPN-11435 test fixes + ISPN-11467 IteratorHandler cannot start in a secure cache

core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java, core/src/test/java/org/infinispan/statetransfer/StatefulSetRollingUpgradeTest.java, server/runtime/src/main/java/org/infinispan/server/Server.java, server/runtime/src/main/server/server/conf/log4j2.xml
https://issues.redhat.com/browse/ISPN-11480
https://issues.redhat.com/browse/ISPN-11485
=> ISPN-11480 Call EmbeddedCacheManager#stop in shutdown hook

core/src/main/java/org/infinispan/cache/impl/CacheImpl.java, core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java, core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/main/java/org/infinispan/manager/impl/ReplicableRunnableCommand.java, core/src/main/java/org/infinispan/persistence/internal/PersistenceUtil.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManager.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerStub.java, core/src/main/java/org/infinispan/persistence/manager/SecurityActions.java, core/src/main/java/org/infinispan/persistence/manager/StartThreadAction.java, core/src/main/java/org/infinispan/persistence/support/DelegatingPersistenceManager.java, core/src/main/java/org/infinispan/transaction/impl/TransactionTable.java, core/src/main/java/org/infinispan/transaction/synchronization/SynchronizationAdapter.java, core/src/main/java/org/infinispan/transaction/xa/TransactionXaAdapter.java, core/src/main/java/org/infinispan/transaction/xa/XaTransactionTable.java, core/src/main/java/org/infinispan/util/concurrent/CompletionStages.java, core/src/test/java/org/infinispan/tx/TransactionXaAdapterTmIntegrationTest.java
https://issues.redhat.com/browse/ISPN-11489
https://issues.redhat.com/browse/ISPN-11443
This makes it so that when PersistenceManagerImpl is invoked by an Infinispan blocking thread that it runs the operation in the same thread, instead of spawning a new task. This prevents a blocking thread from waiting on another blocking thread, which can cause deadlocks. Also for bulk operations that are subscribed on a blocking thread we create a temporary thread to handle the load.
=> ISPN-11489 PersistenceManagerImpl thread checks need to be updated

query/src/test/resources/async-file-store-config.xml, query/src/test/resources/async-jdbc-store-config.xml
https://issues.redhat.com/browse/ISPN-11547
This is mere a workaround that prevents tests from hanging. 
The root cause is the Hibernate Search engine has an executor that deletes files from index asynchronously, and after the teardown the tx cannot complete for some reason, possibly a race with the cache shutdown
=> ISPN-11547 Query test suite hangs intermitently

query/src/main/java/org/infinispan/query/impl/massindex/DistributedExecutorMassIndexer.java, query/src/main/java/org/infinispan/query/impl/massindex/IndexUpdater.java, query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java, query/src/test/java/org/infinispan/query/distributed/AsyncMassIndexPerfTest.java
https://issues.redhat.com/browse/ISPN-11512
Performs the mass indexer grouping same indexes types (shared/non-shared)
=> ISPN-11512 The mass indexer should iterate over the cache only once

query/src/main/java/org/infinispan/query/impl/massindex/DistributedExecutorMassIndexer.java, query/src/main/java/org/infinispan/query/impl/massindex/IndexUpdater.java, query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java, query/src/test/java/org/infinispan/query/distributed/AsyncMassIndexPerfTest.java
https://issues.redhat.com/browse/ISPN-11512
=> [10.1.x] ISPN-11512 The mass indexer should iterate over the cache only once

server/testdriver/core/pom.xml
The org.infinispan:infinispan-core test-jar is required since its org.infinispan.test.TestingUtil is
used by org.infinispan.server.test.core.EmbeddedInfinispanServerDriver#start when running in
embedded run mode and optional maven dependency doesn't make it on the CP thus CNFE.
https://issues.redhat.com/browse/ISPN-11586
10.1 - https://github.com/infinispan/infinispan/pull/8159
=> ISPN-11586 CNFE when using testdriver in ServerRunMode.EMBEDDED mode

server/testdriver/core/pom.xml
The org.infinispan:infinispan-core test-jar is required since its org.infinispan.test.TestingUtil is
used by org.infinispan.server.test.core.EmbeddedInfinispanServerDriver#start when running in
embedded run mode and optional maven dependency doesn't make it on the CP thus CNFE.
Jira
https://issues.redhat.com/browse/ISPN-11586
=> [10.1] ISPN-11586 CNFE when using testdriver in ServerRunMode.EMBEDDED mode

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/StorageRoutingTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/MultiServerStoreQueryTest.java, core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java, core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactory.java, core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactoryImpl.java, core/src/test/java/org/infinispan/eviction/impl/ExceptionEvictionTest.java, core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationFunctionalTest.java, core/src/test/java/org/infinispan/functional/FunctionalStorageTypeTest.java, core/src/test/java/org/infinispan/statetransfer/StateTransferTimestampsTest.java, core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java, multimap/src/test/java/org/infinispan/multimap/impl/StoreTypeMultimapCacheTest.java, query/src/test/java/org/infinispan/query/blackbox/ClusteredCacheTest.java, query/src/test/java/org/infinispan/query/blackbox/ClusteredQueryTest.java
https://issues.redhat.com/browse/ISPN-11554
* Preserve the timestamps in OffHeapEntryFactoryImpl
* Delete deprecated OffHeapEntryFactory.create overload
* Pull up the storageType parameter in MultipleCacheManagersTest
* Use the inherited lockingMode in ExceptionEvictionTest
=> ISPN-11554 Off-heap state transfer resets timestamps

core/src/main/java/org/infinispan/context/Flag.java
https://issues.redhat.com/browse/ISPN-11589
`OPERATION_HOTROD` and `OPERATION_MEMCACHED` remain as they were only deprecated in 10.0.
=> ISPN-11589 Remove deprecated Flag enums and methods.

documentation/src/main/asciidoc/user_guide/persistence_sfs.adoc
https://issues.redhat.com/browse/ISPN-10428 
Return of the Jira, Episode II. Do not set path for single file stores with server.
=> [9.4.x] ISPN-10428 use default path with single file store

server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11627
=> ISPN-11627 InfinispanServerRule returning FileAlreadyExistsException if you use mavenArtifacts and restart the server

build-configuration/pom.xml, checkstyle/src/main/resources/checkstyle-hibernate-cache.xml, checkstyle/src/main/resources/checkstyle.xml, pom.xml
ISPN-11745 Netty 4.1.49
ISPN-11748 OkHTTP 3.14.8
ISPN-11747 Log4j 2.13.2
ISPN-11746 Jackson 2.11.0
ISPN-11752 Agroal 1.8 
ISPN-11751 Various Maven plugin upgrades, Checkstyle
* Maven Antrun 3.0.0
* Maven Checkstyle 3.1.1 Checkstyle 8.32
* Maven Bundle 4.2.1
* Maven Invoker 3.2.1
* Maven Jar 3.2.0
* Maven Release 3.0.0-M1
* Maven Shade 3.2.3
* Maven Source 3.2.0
* Maven Surefire 3.0.0-M4
* Karaf plugin 4.2.8
* Make BlockHound work with JDK 13
=> A bunch of component and maven plugin upgrades

cli/cli-client/src/main/java/org/infinispan/cli/CLI.java, commons/all/src/main/java/org/infinispan/commons/util/Version.java, commons/all/src/main/resources/META-INF/infinispan-version.properties, server/runtime/src/main/java/org/infinispan/server/Server.java, server/runtime/src/main/java/org/infinispan/server/security/UserTool.java, tools/src/main/java/org/infinispan/tools/store/migrator/StoreMigrator.java
https://issues.redhat.com/browse/ISPN-11511
To get consistent branding:
`-Dinfinispan.brand.name="My Brand" -Dinfinispan.brand.version="8.0.0.GA" -Dinfinispan.codename="Infinispan 11.0.0.Dev03"`
will result in the server (and other tools) printing the following banner:
`ISPN080001: My Brand 8.0.0.GA (Infinispan 11.0.0.Dev03)`
=> ISPN-11511 More consistent branding

server/rest/src/main/java/org/infinispan/rest/ALPNHandler.java, server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java, server/rest/src/test/java/org/infinispan/rest/assertion/ResponseAssertion.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
https://issues.redhat.com/browse/ISPN-11765
=> ISPN-11765 Add internal headers to CORS rules

documentation/src/main/asciidoc/index.asciidoc
https://issues.redhat.com/browse/ISPN-11808
This adds links to versioned docs for the Operator and SB Starter on 10.1.x. Depends on this change to the site: https://github.com/infinispan/infinispan.github.io/pull/109
=> [10.1.x] add versioned operator and spring boot docs

core/src/test/java/org/infinispan/statetransfer/StatefulSetRollingUpgradeTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMergeTest.java
https://issues.redhat.com/browse/ISPN-11566
In order to fix the test failure it's necessary for [ISPN-11634](https://issues.redhat.com/browse/ISPN-11634) to be implemented, in the interim the test is added to the "unstable" group.
=> ISPN-11566 Add StatefulSetRollingUpgradeTest to 'unstable' group

documentation/src/main/asciidoc/stories/assembly_xsite_replication.adoc, documentation/src/main/asciidoc/titles/xsite/xsite.asciidoc, documentation/src/main/asciidoc/topics/con_xsite_concurrent_writes.adoc, documentation/src/main/asciidoc/topics/con_xsite_replication.adoc, documentation/src/main/asciidoc/topics/con_xsite_site_masters.adoc
https://issues.redhat.com/browse/ISPN-11780
=> ISPN-11780 updating xsite docs for IRAC implementation

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
https://issues.redhat.com/browse/ISPN-11810
@wburns has already fixed this in master as part of ISPN-11674
=> [10.1.x] ISPN-11810 RemoteCacheManager ignores per-cache near cache configuration

server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11819
Master: https://github.com/infinispan/infinispan/pull/8312
=> [10.1.x] ISPN-11819 Prevent ContainerInfinispanServerDriver erroneous state with provided server directory

server/runtime/src/main/resources/schema/infinispan-server-11.0.xsd
* Fix server schema errors
caused by: https://issues.redhat.com/browse/ISPN-11205
error
```
[ERROR]      [java] org.xml.sax.SAXParseException; systemId: file:/mnt/data/pedro/work/infinispan/server/runtime/target/classes/schema/infinispan-server-11.0.xsd; lineNumber: 146; columnNumber: 94; The character sequence "]]>" must not appear in content unless used to mark the end of a CDATA section.
```
=> ISPN-11205 DataSource support in the Server

server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java
Resolves
https://issues.redhat.com/browse/ISPN-11895
INFINISPAN_SERVER_HOME is consumed from System properties instead of test configuration properties. See org.infinispan.server.test.core.ForkedInfinispanServerDriver#start. The user can make it to consume a system property if they choose to.
@tristantarrant @gustavolira please check if this isn't misguided.
=> ISPN-11895 INFINISPAN_SERVER_HOME is consumed from System properties instead of test configuration properties

pom.xml
https://issues.redhat.com/browse/ISPN-11921
Add the `lucene-misc` to `<dependencyManagement>` to replace its version downstream. It is shipped by the server.
=> ISPN-11921 Add org.apache.lucene:lucene-misc back

build-configuration/pom.xml, client/infinispan-key-value-store-hotrod/pom.xml, pom.xml
Set the same version as used by rxjava3. 
https://issues.redhat.com/browse/ISPN-11922
=> ISPN-11922 Upgrade org.reactivestreams:reactive-streams to 1.0.3

commons/all/src/main/java/org/infinispan/commons/util/Util.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java, server/rest/src/main/java/org/infinispan/rest/resources/JsonErrorResponseEntity.java, server/rest/src/main/java/org/infinispan/rest/resources/LoggingResource.java, server/rest/src/main/java/org/infinispan/rest/resources/LoginResource.java, server/rest/src/main/java/org/infinispan/rest/resources/ProtobufResource.java, server/rest/src/main/java/org/infinispan/rest/resources/ResourceUtil.java, server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java, server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java, server/rest/src/main/java/org/infinispan/rest/resources/TasksResource.java, server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
https://issues.redhat.com/browse/ISPN-11927
https://issues.redhat.com/browse/ISPN-11928
https://issues.redhat.com/browse/ISPN-11934
https://issues.redhat.com/browse/ISPN-11935
@gustavonalle Most of these changes are to benefit the quarkus native server. ISPN-11935 reduces repetition, but also it makes it so that JSON transformations are consistent. It's necessary to register all of the classes that Jackson needs to access for reflection with Quarkus, however in lots of the resources the returned 500 message did not contain the message of the exception thrown making it impossible to know why the server throw a 500. So I have centralised this logic and made it so that the exception message is returned in the response body as well output to the server log.
=> Rest resource changes

commons/all/src/main/java/org/infinispan/commons/util/ByRef.java, core/src/main/java/org/infinispan/eviction/impl/PassivationManagerImpl.java, core/src/main/java/org/infinispan/interceptors/impl/CacheWriterInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/DistCacheWriterInterceptor.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManager.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerStub.java, core/src/main/java/org/infinispan/persistence/support/DelegatingPersistenceManager.java, core/src/test/java/org/infinispan/distribution/BaseDistStoreTest.java, core/src/test/java/org/infinispan/distribution/DistSyncStoreSharedTest.java, core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java, core/src/test/java/org/infinispan/scattered/store/ScatteredSyncStoreSharedTest.java
https://issues.redhat.com/browse/ISPN-10373
https://issues.redhat.com/browse/ISPN-11902
* The putMap command now only iterates over the entries and calls into persistence manager once.
Fixes random test failure in ISPN-11902
* PassivationManagerImpl batch now does not utilize ConnectableFlowable as this can mess with if there is more than 1 store and they subscribe on different threads (ConnectableFlowable shares the same subscribing thread).
* The passivation insertion and putMap command now both call into the same shared batch code internally in PassivationManagerImpl.
* Fixed shared stores not updating the store count correctly (was counting non owned entries) - was broken before refactoring.
* Added additional tracing
=> ISPN-10373 Rework put map and simplify batch

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java, commons/all/src/main/java/org/infinispan/commons/dataconversion/EncoderIds.java, commons/all/src/main/java/org/infinispan/commons/dataconversion/GlobalMarshallerEncoder.java, commons/all/src/main/java/org/infinispan/commons/dataconversion/JavaSerializationEncoder.java, commons/all/src/main/java/org/infinispan/commons/dataconversion/MediaType.java, commons/all/src/main/java/org/infinispan/commons/util/KeyValueWithPrevious.java, core/src/main/java/org/infinispan/configuration/global/SerializationConfiguration.java, core/src/main/java/org/infinispan/encoding/impl/JavaSerializationTranscoder.java, core/src/main/java/org/infinispan/encoding/impl/TwoStepTranscoder.java, core/src/main/java/org/infinispan/factories/EncoderRegistryFactory.java, core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java, core/src/main/java/org/infinispan/marshall/persistence/impl/PersistenceMarshallerImpl.java, core/src/test/java/org/infinispan/dataconversion/DataConversionTest.java, core/src/test/java/org/infinispan/dataconversion/impl/JavaSerializationTranscoderTest.java, integrationtests/jboss-marshalling-it/src/test/java/org/infinispan/it/marshalling/jboss/JBMARRemoteQueryDslConditionsTest.java, jboss-marshalling/pom.xml, jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/JbossMarshallingModule.java, jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/dataconversion/GenericJbossMarshallerEncoder.java, jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/dataconversion/JBossMarshallingTranscoder.java, jcache/commons/src/main/java/org/infinispan/jcache/RICacheEntryEvent.java, jcache/commons/src/test/java/org/infinispan/jcache/AbstractTwoCachesBasicOpsTest.java, jcache/remote/src/main/java/org/infinispan/jcache/remote/JCacheManager.java, jcache/tck-runner-remote/src/test/resources/hotrod-client.properties, server/core/src/main/java/org/infinispan/server/core/LifecycleCallbacks.java
ISPN-11898 Missing transcoder for user marshaller's media type
https://issues.redhat.com/browse/ISPN-11898
ISPN-11899 application/x-java-serialized-object without custom marshaller
https://issues.redhat.com/browse/ISPN-11899
ISPN-11900 jboss-marshalling module missing application/x-jboss-marshalling transcoder
https://issues.redhat.com/browse/ISPN-11900
ISPN-11901 Deprecate unused encoders and media types
https://issues.redhat.com/browse/ISPN-11901
ISPN-11926 Remote JCacheManager creates two RemoteCacheManager instances
https://issues.redhat.com/browse/ISPN-11926
ISPN-11932 JCache remote events do not work with ProtostreamMarshaller
https://issues.redhat.com/browse/ISPN-11932
ISPN-11910 Server should see application/octet-stream as protostream
https://issues.redhat.com/browse/ISPN-11900
=> ISPN-11898 Missing transcoder for user marshaller's media type

commons/all/src/main/java/org/infinispan/commons/configuration/attributes/Attribute.java, commons/all/src/main/java/org/infinispan/commons/logging/Log.java, core/src/main/java/org/infinispan/configuration/cache/MemoryConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/MemoryConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/MemoryStorageConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/MemoryStorageConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/StorageType.java, core/src/main/java/org/infinispan/configuration/parsing/Parser.java, core/src/main/java/org/infinispan/encoding/impl/StorageConfigurationManager.java, core/src/main/java/org/infinispan/factories/DataContainerFactory.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/main/resources/schema/infinispan-config-11.0.xsd, core/src/test/java/org/infinispan/configuration/EvictionConfigurationTest.java, core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java, core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java, core/src/test/java/org/infinispan/encoding/impl/StorageConfigurationManagerTest.java, core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationFunctionalTest.java, core/src/test/java/org/infinispan/jmx/JmxStatsFunctionalTest.java, core/src/test/java/org/infinispan/manager/CacheManagerTest.java, core/src/test/java/org/infinispan/statetransfer/StateTransferTimestampsTest.java, core/src/test/java/org/infinispan/tx/ContextAffectsTransactionReadCommittedTest.java, core/src/test/java/org/infinispan/tx/ContextAffectsTransactionRepeatableReadTest.java, query/src/test/java/org/infinispan/query/blackbox/ClusteredQueryTest.java
https://issues.redhat.com/browse/ISPN-11998
* Change default storage to HEAP everywhere
* Document deprecated storage attribute values
in the XSD
* Synchronize new and old eviction attributes
both in the buider and in the runtime configuration
* Synchronize when copying configurations
* Synchronize when reading JSON
* Add new configuration and defaults tests
* Make attributes that cannot change at runtime immutable
* Eviction new and legacy attributes should stay in sync
* Fix tests that set the storage to null
* Update tests for new default storage type
=> ISPN-11998 Keep new and legacy memory attributes in sync

pom.xml
https://issues.redhat.com/browse/ISPN-12030
* Fix the activation condition for profile java13-test
* Don't add -XX:+AllowRedefinitionToAddDeleteMethods
if profile java8-test is active
=> ISPN-12030 BlockHound is not active on JDK 13/14

documentation/src/main/asciidoc/topics/ref_cache_store_rocksdb.adoc, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/CompressionType.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfiguration.java, persistence/rocksdb/src/main/resources/schema/infinispan-cachestore-rocksdb-config-11.0.xsd
https://issues.redhat.com/browse/ISPN-12038
Unfortunately writing a test to obtain the actual column family configuration is hard without some refactoring of the RocksDBStore, since the column family handle you obtain from the DB is not owned by it... (weird internal stuff)
=> ISPN-12038 Fix RocksDB compression options

hibernate/pom.xml, integrationtests/pom.xml, integrationtests/security-manager-it/pom.xml, integrationtests/wildfly-modules/pom.xml, jcache/tck-runner-embedded/pom.xml, jcache/tck-runner-remote/pom.xml, pom.xml, query/pom.xml, server/router/pom.xml, server/tests/pom.xml
https://issues.redhat.com/browse/ISPN-12030
* Extract a separate property for BlockHound on JDK13+
* Use the aggregate testjvm.jdkSpecificArgs property
everywhere
* Unset all JDK-specific properties in the java8-test
profile
=> ISPN-12030 Fix java8-test

wildfly/feature-pack/pom.xml
https://issues.redhat.com/browse/ISPN-12058
Move branding Ant script to phase process-resources,
after maven-resources-plugin has copied the files.
=> ISPN-12058 wildfly/feature-pack module doesn't build

integrationtests/wildfly-modules/src/test/resources/as-config/standalone/configuration/standalone-test.xml
https://issues.redhat.com/browse/ISPN-12060
Add missing org.wildfly.extension.microprofile.config-smallrye
extension to the test WildFly configuration.
=> ISPN-12060 WildFly modules integration tests do not on WildFly 19

anchored-keys/src/main/java/org/infinispan/anchored/AnchoredKeysModuleLifecycle.java, build-configuration/bom/pom.xml, server/runtime/pom.xml, server/tests/src/test/java/org/infinispan/server/functional/AnchoredKeysIT.java, server/tests/src/test/resources/configuration/AnchoredKeys.xml, server/tests/src/test/resources/configuration/cache-container/clustered-anchored.xml
https://issues.redhat.com/browse/ISPN-12065
@tristantarrant I had to set the run mode to CONTAINER ... for some reason with the default I get the following errors on the server:
```java
org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=10 returned server error (status=0x85): java.lang.ClassCastException: class org.infinispan.remoting.transport.jgroups.JGroupsAddress cannot be cast to class [B (org.infinispan.remoting.transport.jgroups.JGroupsAddress is in unnamed module of loader 'app'; [B is in module java.base of loader 'bootstrap')
```
=> ISPN-12065 Add the anchored-keys module to the server

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/statetransfer/OutboundTransferTask.java, core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.redhat.com/browse/ISPN-11923
Use `Future.cancel(false)` to avoid an `InterruptedIOException` closing `SingleFileStore`'s `FileChannel`.
=> [9.4.x] ISPN-11923 Another node leaving may break SingleFileStore

core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java, core/src/test/java/org/infinispan/util/CoreTestBlockHoundIntegration.java, pom.xml, server/testdriver/pom.xml
https://issues.redhat.com/browse/ISPN-12109
* Add BlockHound exceptions for JGroups w/ TCP transport
* Add BlockHound exception for Log4j2
* Remove property infinispan.cluster.stack from all profiles
=> ISPN-12109 TcpConnection.Receiver.run() blocking call

core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java, core/src/test/java/org/infinispan/util/CoreTestBlockHoundIntegration.java, pom.xml, server/testdriver/pom.xml
https://issues.redhat.com/browse/ISPN-12109
Backport of #8551
* Add BlockHound exceptions for JGroups w/ TCP transport
* Add BlockHound exception for Log4j2
* Remove property infinispan.cluster.stack from all profiles
=> [11.0.x] ISPN-12109 TcpConnection.Receiver.run() blocking call

commons-test/src/main/java/org/infinispan/commons/logging/log4j/ThreadNameFilter.java, commons-test/src/main/java/org/infinispan/commons/test/skip/StringLogAppender.java
* fix the sometimes meaningless exception message when StringLogAppender.getLog fails
* ThreadNameFilter does not really need a serialVersionUID field; also remove needless finals for parameters
=> Fix StringLogAppender.getLog error message once again

build-configuration/bom/pom.xml, documentation/src/main/asciidoc/topics/dependencies_maven/protostream-processor.xml, documentation/src/main/asciidoc/topics/proc_generating_serial_cxt_initializer.adoc
Continuing on ISPN-11924 Protostream Processor Dependency XML is incorrect 
see comment: https://github.com/infinispan/infinispan/pull/8402#issuecomment-635323863
https://issues.redhat.com/browse/ISPN-11924
=> ISPN-11924 Advise on using protostream-processor as a 'provided' dependency

core/src/main/java/org/infinispan/functional/impl/Params.java, core/src/main/java/org/infinispan/interceptors/impl/CacheMgmtInterceptor.java, hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/LockingInterceptor.java, hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/NonStrictAccessDelegate.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/AbstractNonInvalidationTest.java, hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/VersionedTest.java, hibernate/cache-v51/src/main/java/org/infinispan/hibernate/cache/v51/impl/BaseRegion.java, hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/impl/BaseRegionImpl.java
https://issues.redhat.com/browse/ISPN-12148
https://issues.redhat.com/browse/ISPN-12147
ISPN-12148 Hibernate-cache NullPointerException in CacheMgmtInterceptor
* Skip statistics update if the command failed
and it had flag FAIL_SILENTLY
* Throw exception on lock timeout for operations with flag
ZERO_LOCK_ACQUISITION_TIMEOUT, do not throw exception
with flag FAIL_SILENTLY
* Translate meta-param LockingMode.TRY_LOCK to flags
ZERO_LOCK_ACQUISITION_TIMEOUT + FAIL_SILENTLY
* Explicitly use flag FAIL_SILENTLY for
BaseRegion[Impl].beginInvalidation
ISPN-12147 NonStrictAccessDelegate ignores cache exceptions
=> ISPN-12148 Hibernate-cache NullPointerException in CacheMgmtInterceptor

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodNonOwnerStatisticsTest.java
https://issues.redhat.com/browse/ISPN-11303
The duplicate local-non-blocking get was removed in 10.0.0.Alpha2 with ISPN-9849, this just forward-ports the test.
=> ISPN-11303 Test hit/miss statistics after non-owner get

query/pom.xml, query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java, query/src/main/java/org/infinispan/query/backend/TxQueryInterceptor.java, query/src/main/java/org/infinispan/query/internal/QueryBlockHoundIntegration.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
https://issues.redhat.com/browse/ISPN-11731
=> ISPN-11731 Add blockhound to query module

server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractServerConfigBuilder.java, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerRuleBuilder.java, server/testdriver/junit5/pom.xml, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerExtensionBuilder.java, server/testdriver/junit5/src/test/java/org/infinispan/server/test/junit5/InfinispanServerExtensionContainerTest.java, server/testdriver/junit5/src/test/resources/infinispan.xml, server/testdriver/pom.xml
https://issues.redhat.com/browse/ISPN-12256
* Make InfinispanServerExtensionContainerTest use custom configuration
* Add test-tcp and test-udp stacks to custom configuration
* Remove surefire <argLine> element and use args from parent POM
* Define infinispan.cluster.stack=test-tcp in all testdriver modules
=> ISPN-12256 InfinispanServerExtensionContainerTest fails to start

server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerExtension.java, spring/spring-boot/remote/src/test/java/test/org/infinispan/spring/starter/remote/actuator/RemoteCacheMetricBinderTest.java, spring/spring-boot/remote/src/test/resources/infinispan.xml
https://issues.redhat.com/browse/ISPN-12263
* Make InfinispanServerExtension implement BeforeEachCallback
and AfterEachCallback
* Add custom server configuration to remove security
* Remove InfinispanCacheMetricBinderTest.cleanCache()
* Enable statistics in the RemoteCacheManager
* Create the mycache cache
Not ready for review, depends on #8651 and #8653
=> ISPN-12263 RemoteCacheMetricBinderTest fails

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/TopologyInfo.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec20.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HitsAwareCacheManagersTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ReplTopologyChangeTest.java
https://issues.redhat.com/browse/ISPN-12251
* Make RemoteCacheManager.getServers return the unresolved
hostname
* Make TopologyInfo use InetSocketAddress so we can extract
the host name and port number
* Keep SocketAddress in FailoverRequestBalancingStrategy
for source compatibility
=> ISPN-12251 HotRodClientJmxTest.testRemoteCacheManagerMBean fails on Java 14

core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java, core/src/main/java/org/infinispan/marshall/persistence/PersistenceMarshaller.java, core/src/test/java/org/infinispan/factories/impl/BasicComponentRegistryImplTest.java, core/src/test/java/org/infinispan/factories/impl/FactoryAutoInstantiationTest.java
https://issues.redhat.com/browse/ISPN-12273
Fix the race condition in factory auto-instantiation
by allowing all threads that see an EMPTY component wrapper
to create the instance (regardless of whether they registered
the component wrapper or not).
=> ISPN-12273 Potential race condition during wiring of EncoderCache

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ConsistentHashV2IntegrationTest.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
https://issues.redhat.com/browse/ISPN-6901
https://issues.redhat.com/browse/ISPN-12254
I was not able to reproduce the failure, so I'm re-enabling the test.
I did find a NPE in CheckAddressTask, but it's just a cosmetic issue.
=> ISPN-6901 ConsistentHashV2IntegrationTest.testCorrectBalancingOfKeysAfterNodeKill fails

core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java, core/src/main/java/org/infinispan/marshall/persistence/PersistenceMarshaller.java, core/src/test/java/org/infinispan/factories/impl/BasicComponentRegistryImplTest.java, core/src/test/java/org/infinispan/factories/impl/FactoryAutoInstantiationTest.java
https://issues.redhat.com/browse/ISPN-12273
Fix the race condition in factory auto-instantiation
by allowing all threads that see an EMPTY component wrapper
to create the instance (regardless of whether they registered
the component wrapper or not).
=> [11.0.x] ISPN-12273 Potential race condition during wiring of EncoderCache

build-configuration/bom/pom.xml, documentation/src/main/asciidoc/topics/dependencies_maven/protostream-processor.xml, documentation/src/main/asciidoc/topics/proc_generating_serial_cxt_initializer.adoc
Continuing on ISPN-11924 Protostream Processor Dependency XML is incorrect
see comment: #8402 (comment)
https://issues.redhat.com/browse/ISPN-11924
=> [11.0.x] ISPN-11924 Advise on using protostream-processor as a 'provided' dependenc

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/AbstractAuthenticationTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SslAuthenticationTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SslTest.java, commons/all/src/main/java/org/infinispan/commons/dataconversion/MediaType.java, commons/all/src/main/java/org/infinispan/commons/util/Immutables.java, commons/all/src/main/java/org/infinispan/commons/util/ObjectDuplicator.java, core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingAdvancedCache.java, core/src/main/java/org/infinispan/cache/impl/CacheImpl.java, core/src/main/java/org/infinispan/cache/impl/EncoderCache.java, core/src/main/java/org/infinispan/interceptors/locking/ClusteringDependentLogic.java, core/src/main/java/org/infinispan/marshall/core/Primitives.java, server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java, server/core/src/main/java/org/infinispan/server/core/transport/ExtendedByteBufJava.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodHeader.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/Intrinsics.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodSslWithCertPasswdTest.java, server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
https://issues.redhat.com/browse/ISPN-11005
* Avoid new byte[] instance when reading cache name
* Improve parsing and matching of media types
* Simplify copying of collections
* Avoid new array instance in withFlags(Flag)
* Avoid new lambda instance when stage is completed successfully
* Use HopscotchHashMap for GlobalMarshaller primitive ids
* Simplify ExtendedByteBufJava.readMaybeVInt() logic
* Call withFlags() only once in HotRodHeader.getOptimizedCache()
* Don't include key media type parameters in knownCaches key in
RestCacheManager.getCache()
=> ISPN-11005 HotRod decoder small performance improvements

commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
https://issues.redhat.com/browse/ISPN-12321
Ignore the thread.
We could stop it explicitly at the end of the test suite,
but it would add an explicit mysql dependency.
=> ISPN-12321 Leaked thread: mysql-cj-abandoned-connection-cleanup

server/runtime/src/main/ant/infinispan-server.xml
https://issues.redhat.com/browse/ISPN-12314
* Run lsof a single time, fail the build if it does not exist
* Remove the ps and jps checks
=> ISPN-12314 lsof check is too expensive

core/src/test/java/org/infinispan/commands/GetAllCommandNodeCrashTest.java
https://issues.redhat.com/browse/ISPN-12322
* Ignore StateTransferCancelCommand
* Remove the StateTransferLock mock, since it wasn't clear
what command was supposed to trigger it
* Explicitly assert that the command is retried only once
=> ISPN-12322 GetAllCommandNodeCrashTest.test random failures

commons/all/src/main/java/org/infinispan/commons/util/ImmutableListCopy.java, core/src/main/java/org/infinispan/distribution/ch/impl/ConsistentHashPersistenceConstants.java, core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHash.java, core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHashFactory.java, core/src/main/java/org/infinispan/distribution/ch/impl/ScatteredConsistentHash.java, core/src/main/java/org/infinispan/distribution/ch/impl/SyncConsistentHashFactory.java, core/src/main/java/org/infinispan/distribution/ch/impl/SyncReplicatedConsistentHashFactory.java, core/src/main/java/org/infinispan/distribution/impl/DistributionManagerImpl.java, core/src/main/java/org/infinispan/interceptors/impl/AsyncInterceptorChainImpl.java, core/src/test/java/org/infinispan/distribution/ZeroCapacityNodeTest.java, core/src/test/java/org/infinispan/distribution/ch/ReplicatedConsistentHashFactoryTest.java, core/src/test/java/org/infinispan/distribution/ch/ReplicatedConsistentHashPersistenceTest.java, core/src/test/java/org/infinispan/remoting/transport/MockTransport.java, core/src/test/java/org/infinispan/util/BaseControlledConsistentHashFactory.java
https://issues.redhat.com/browse/ISPN-12221
* Extend ZeroCapacityNodeTest to cover replicated
and scattered caches
* Add a list of members without state and a capacity
factors map to ReplicatedConsistentHash
* Ignore nodes with zero capacity when computing backups
* Change [Sync]ReplicatedConsistentHashFactory.
updateMembers() no not assign new members as backups
=> ISPN-12221 Add zero-capacity-node support for Replicated caches 

query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerProgressNotifier.java, search-mapper/src/main/java/org/infinispan/search/mapper/mapping/ProgrammaticSearchMappingProvider.java, search-mapper/src/main/java/org/infinispan/search/mapper/mapping/SearchIndexedEntity.java, search-mapper/src/main/java/org/infinispan/search/mapper/scope/impl/SearchWorkspaceImpl.java
https://issues.redhat.com/browse/ISPN-12371
The headers of The Hibernate 5 annotations package are related to old code, so probably we cannot remove the header from there...
=> ISPN-12371 Remove LGPL header from new code for Search 6 integration

commons/all/src/main/java/org/infinispan/commons/dataconversion/MediaType.java, commons/all/src/main/java/org/infinispan/commons/logging/Log.java, commons/all/src/test/java/org/infinispan/commons/dataconversion/MediaTypeTest.java, server/rest/src/test/java/org/infinispan/rest/profiling/MediaTypeParsingBenchmark.java
https://issues.redhat.com/browse/ISPN-12307
* Use regular expressions for parsing to reduce allocations
and to be closer to the spec
* Do not remove quotes or backlashes from quoted parameter values
* Add parsing benchmark
master Benchmark                                                |Mode  |Cnt  | Score   |Error  |Units
---------------------------------------------------------|------|-----|---------|-------|-----
MediaTypeParsingBenchmark.State.parseList                |avgt  | 30  |37.809 ± |0.225  |ns/op
MediaTypeParsingBenchmark.State.parseNoParameter         |avgt  | 30  | 2.787 ± |0.019  |ns/op
MediaTypeParsingBenchmark.State.parseOneParameter        |avgt  | 30  | 7.632 ± |0.105  |ns/op
MediaTypeParsingBenchmark.State.parseOneQuotedParameter  |avgt  | 30  | 7.720 ± |0.154  |ns/op …
=> ISPN-12307 Improve media type parsing

server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-12315
The test ```org.infinispan.rest.resources.CacheV2ResourceTest.testCRUDWithProtobufPrimitives``` started failing after https://github.com/infinispan/infinispan/pull/8747 was merged, it turned out the test was buggy and was not passing the correct headers
=> ISPN-12315 REST server can't handle entry changes with value encoded as java primitives

distribution/package.xml, pom.xml, wildfly/feature-pack/pom.xml
* Fix path: missing ${basedir}
* Remove hibernate-search-backend-jms
The licenses-plugin is configured to ignore test dependencies and it
was ignoring the dep. Remove it from our pom.xml fix the issues. It
isn't used explicitly anywhere.
https://issues.redhat.com/browse/ISPN-12375
=> [11.0.x] ISPN-12375 Add missing license information to wildfly modules

anchored-keys/src/main/java/org/infinispan/anchored/impl/AnchoredCacheNotifier.java, core/src/main/java/org/infinispan/configuration/global/CacheContainerConfiguration.java, core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java, core/src/test/java/org/infinispan/distribution/ZeroCapacityNodeTest.java, core/src/test/java/org/infinispan/notifications/cachelistener/BaseCacheNotifierImplInitialTransferTest.java
https://issues.redhat.com/browse/ISPN-12413
A replicated cache on a zero capacity node does not store any entries
locally, but it should still notify clustered listeners of changes.
=> ISPN-12413 Clustered listeners for replicated caches with zero capacity

cli/cli-client/src/test/resources/patch/v1/server/conf/infinispan.xml, cli/cli-client/src/test/resources/patch/v2/server/conf/infinispan.xml, cli/cli-client/src/test/resources/patch/v3/server/conf/infinispan.xml, documentation/src/main/asciidoc/topics/ref_default_cm_remote.adoc, integrationtests/server-integration/server-integration-commons/src/test/resources/infinispan-custom.xml, jcache/tck-runner-remote/src/test/resources/infinispan.xml, server/runtime/README.adoc, server/runtime/src/main/java/org/infinispan/server/Bootstrap.java, server/runtime/src/main/java/org/infinispan/server/Server.java, server/runtime/src/main/java/org/infinispan/server/logging/Messages.java, server/runtime/src/main/server/server/conf/infinispan-xsite.xml, server/runtime/src/main/server/server/conf/infinispan.xml, server/testdriver/junit5/src/test/resources/infinispan.xml, server/tests/src/test/resources/configuration/cache-container/clustered-anchored.xml, server/tests/src/test/resources/configuration/cache-container/clustered-authz.xml, server/tests/src/test/resources/configuration/cache-container/clustered.xml
Defaults for infinispan.cluster.name and infinispan.cluster.stack are set hardcoded, the defaults within the expression ${:XXX} are not working.
https://issues.redhat.com/browse/ISPN-12220
=> ISPN-12220: expression defaults not working correctly

core/src/main/java/org/infinispan/configuration/parsing/ParseUtils.java, core/src/main/java/org/infinispan/configuration/parsing/Parser.java, core/src/test/java/org/infinispan/persistence/BaseNonBlockingStoreTest.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfiguration.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfigurationBuilder.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfigurationParser.java, persistence/rocksdb/src/main/resources/schema/infinispan-cachestore-rocksdb-config-12.0.xsd, persistence/rocksdb/src/test/java/org/infinispan/persistence/rocksdb/RocksDBStoreTest.java, persistence/rocksdb/src/test/resources/config/rocksdb-config.xml
https://issues.redhat.com/browse/ISPN-8241
=> ISPN-8241 Refactor RocksDB clearThreshold

documentation/src/main/asciidoc/index.asciidoc
Need to sync index page with master to remove the links to Operator documentation. It's not reasonable to manually keep dev and stable versions tracked in the index page for docs.
=> Remove Operator links from doc index

CONTRIBUTING.md, README-Build.md, documentation/src/main/asciidoc/titles/cli/cli.asciidoc, documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc, documentation/src/main/asciidoc/topics/contributing/basics.adoc, documentation/src/main/asciidoc/topics/contributing/building.adoc
Some stale links in the Contributor's Guide to old Jira instances. Correcting link and stale details in README-Build.md.
=> Updating links to contributing and Jira

documentation/src/main/asciidoc/stories/assembly_hotrod_client_api.adoc, documentation/src/main/asciidoc/topics/counters.adoc, documentation/src/main/asciidoc/topics/ref_hotrod_countermanager.adoc
Backport for https://issues.redhat.com/browse/ISPN-12490
=> [11.0.x] ISPN-12490 CounterManager in HR docs

documentation/src/main/asciidoc/topics/config_examples/jgroups_asym_encrypt.xml, documentation/src/main/asciidoc/topics/proc_configuring_jgroups_asym_encrypt.adoc
For 11.0.x, the example asym_encrypt configuration cannot use INSERT_BEFORE. See https://github.com/infinispan/infinispan/blob/497c5279c49455717211fb6a9e3ab159111bce92/core/src/main/resources/schema/infinispan-config-11.0.xsd#L2598
=> [11.0.x] ISPN-10851 correct asym protocol example
