- core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java
- core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java
- core/src/main/java/org/infinispan/distribution/group/impl/GroupManagerImpl.java
- core/src/main/java/org/infinispan/factories/DataContainerFactory.java
- core/src/test/java/org/infinispan/configuration/DataContainerTest.java
* Don't wrap custom IDC
* Move circular dependency into GroupManagerImpl instead
https://issues.jboss.org/browse/ISPN-9329
> ISPN-9329 NPE during cache start due to circular component dependencies

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
- core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
https://issues.jboss.org/browse/ISPN-9335
> [9.3.x] ISPN-9335 Caches created via Hot Rod ignore media type configuration

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
- core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
https://issues.jboss.org/browse/ISPN-9335
> ISPN-9335 Caches created via Hot Rod ignore media type configuration

- bin/reversion.sh
Handle "all" test XMLs automatically in `reversion.sh`.
> Rewrite endpoint test configuration on schema version change

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
- persistence/jpa/src/main/java/org/infinispan/persistence/jpa/JpaStore.java
- persistence/rest/src/main/java/org/infinispan/persistence/rest/RestStore.java
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/SoftIndexFileStore.java
https://issues.jboss.org/browse/ISPN-9348
> ISPN-9348 Remove anonymous inner classes in lambdas for stores

- hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/util/CacheCommandInitializer.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/EntitiesAndCollectionsInSameRegionTest.java
- hibernate/cache-v51/pom.xml
- hibernate/cache-v51/src/main/java/org/infinispan/hibernate/cache/v51/impl/BaseTransactionalDataRegion.java
https://issues.jboss.org/browse/ISPN-8601
> ISPN-8601 Support entity and collection sharing same region name

- tools/src/main/resources/xsd/xsdoc.xslt
https://issues.jboss.org/browse/ISPN-9349
> ISPN-9349 Fix jquery script for xsd doc viewer

- commons/src/main/java/org/infinispan/commons/dataconversion/DefaultTranscoder.java
- server/core/src/main/java/org/infinispan/server/core/LifecycleCallbacks.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/XMLTranscoder.java
- server/integration/testsuite/build-testsuite.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/dataconversion/Currency.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/dataconversion/ObjectStorageIT.java
- server/integration/testsuite/src/test/resources/arquillian.xml
- server/integration/testsuite/src/test/resources/config/infinispan/pojo-storage.xml
https://issues.jboss.org/browse/ISPN-9336
https://issues.jboss.org/browse/ISPN-9357
> [9.3.x] ISPN-9336 & ISPN-9357 JSON/XML to Objects conversion fixes

- hibernate/cache-v53/pom.xml
- hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/InfinispanRegionFactory.java
- hibernate/cache-v53/src/test/java/org/infinispan/test/hibernate/cache/v53/util/TestInfinispanRegionFactory.java
- pom.xml
https://hibernate.atlassian.net//browse/HHH-12531
> [9.3.x] HHH-12531 Handle legacy names in configuration

- core/src/main/java/org/infinispan/interceptors/impl/SimpleAsyncInvocationStage.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
- core/src/main/java/org/infinispan/remoting/transport/Transport.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponse.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/util/logging/TraceException.java
https://issues.jboss.org/browse/ISPN-9362
Please cherry-pick to 9.3.x as well
> ISPN-9362 Break cycles in exception stack traces

- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/persistence/PersistenceUtil.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManager.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerStub.java
- core/src/test/java/org/infinispan/expiration/impl/CustomLoaderNonNullWithExpirationTest.java
- core/src/test/java/org/infinispan/persistence/UnnecessaryLoadingTest.java
* Add includeStores method to load method on PersistenceManager
https://issues.jboss.org/browse/ISPN-9370
> ISPN-9370 Always consult CacheLoader if entry is not in data container

- Jenkinsfile
https://issues.jboss.org/browse/ISPN-8997
> ISPN-8997 Deploy artifacts

- server/integration/versions/pom.xml
Master only. Bump console for 9.4.0.Alpha1 release.
> Bump console to 9.4.0.Alpha1

- core/src/main/java/org/infinispan/interceptors/impl/CacheMgmtInterceptor.java
- core/src/test/java/org/infinispan/interceptors/impl/CacheMgmtInterceptorTest.java
https://issues.jboss.org/browse/ISPN-9353
> ISPN-9353 CacheMgmtInterceptor GetAllCommand exceptions

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/query/RemoteQueryStringCreator.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/QueryDslConditionsTest.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/AndCondition.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/AttributeCondition.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/BaseQueryBuilder.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/BooleanCondition.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/IncompleteCondition.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/NotCondition.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/OperatorAndArgument.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/OrCondition.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/QueryStringCreator.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/logging/Log.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/package-info.java
- query-dsl/src/main/java/org/infinispan/query/dsl/package-info.java
- query/src/test/java/org/infinispan/query/dsl/embedded/QueryDslConditionsTest.java
https://issues.jboss.org/browse/ISPN-9378
> ISPN-9378 Avoid unneeded parentheses in Ickle query string generated by QueryBuilder

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InvalidatedNearRemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/BoundedConcurrentMapNearCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/ConcurrentMapNearCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/LinkedMapNearCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCacheService.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/AssertsNearCache.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedNearCacheTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/MockNearCacheService.java
- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWithOldValue.java
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
https://issues.jboss.org/browse/ISPN-9393
> ISPN-9393 Support async methods with the Hot Rod near cache

- core/src/main/java/org/infinispan/partitionhandling/impl/AvailabilityStrategy.java
- core/src/main/java/org/infinispan/partitionhandling/impl/PreferAvailabilityStrategy.java
- core/src/main/java/org/infinispan/partitionhandling/impl/PreferConsistencyStrategy.java
- core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
- core/src/test/java/org/infinispan/remoting/transport/ControlledTransport.java
- core/src/test/java/org/infinispan/scattered/statetransfer/CoordinatorStopTest.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- core/src/test/java/org/infinispan/test/TopologyChangeListener.java
- core/src/test/java/org/infinispan/test/ViewChangeListener.java
- core/src/test/java/org/infinispan/test/transport/DelayedViewJGroupsTransport.java
- core/src/test/java/org/infinispan/topology/TestClusterCacheStatus.java
- core/src/test/java/org/infinispan/tx/InfinispanNodeFailureTest.java
- core/src/test/java/org/infinispan/util/BlockingLocalTopologyManager.java
- core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
Reintroduce #5989 after reverted by #6159
> ISPN-9128 RehashWithSharedStoreTest.testRehashes random failures

- core/src/main/java/org/infinispan/interceptors/BaseAsyncInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/PrefetchInterceptor.java
- core/src/test/java/org/infinispan/scattered/statetransfer/PrefetchTest.java
https://issues.jboss.org/browse/ISPN-8431
> ISPN-8431 ScatteredSplitAndMergeTest random failures fix

- bom/pom.xml
- plugins/protocol-parser-generator-maven-plugin/pom.xml
- pom.xml
- remote-query/remote-query-client/src/test/java/org/infinispan/query/remote/client/BaseProtoStreamMarshallerTest.java
https://issues.jboss.org/browse/ISPN-9399
> ISPN-9399 Upgrade to protostream 4.2.1.Final

- core/src/main/java/org/infinispan/persistence/PersistenceUtil.java
- core/src/main/java/org/infinispan/persistence/internal/PersistenceUtil.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/persistence/support/ComposedSegmentedLoadWriteStore.java
- core/src/test/java/org/infinispan/persistence/BaseStoreTest.java
- documentation/src/main/asciidoc/user_guide/persistence_rocksdb.adoc
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfiguration.java
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/logging/Log.java
- persistence/rocksdb/src/test/java/org/infinispan/persistence/rocksdb/RocksDBStoreFunctionalTest.java
- persistence/rocksdb/src/test/java/org/infinispan/persistence/rocksdb/RocksDBStoreTest.java
- tools/src/test/java/org/infinispan/tools/store/migrator/rocksdb/RocksDBReaderTest.java
per instance
* Refactor to have column handler based on if segmented
https://issues.jboss.org/browse/ISPN-9375
> ISPN-9375 Change RocksDB segmentation to use column family instead of

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec12.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec20.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec23.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec27.java
- core/src/main/java/org/infinispan/persistence/InitializationContextImpl.java
- core/src/main/java/org/infinispan/persistence/PersistenceUtil.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/persistence/spi/InitializationContext.java
- core/src/main/java/org/infinispan/persistence/spi/SegmentedAdvancedLoadWriteStore.java
- core/src/main/java/org/infinispan/persistence/support/ComposedSegmentedLoadWriteStore.java
- core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/DummyInitializationContext.java
- core/src/test/java/org/infinispan/util/PersistenceMockUtil.java
- documentation/src/main/asciidoc/user_guide/persistence_remote.adoc
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
- persistence/jpa/src/test/java/org/infinispan/persistence/jpa/AbstractJpaStoreTest.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationBuilder.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/logging/Log.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreFunctionalTest.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreTest.java
* Added in segment based bulk operations
https://issues.jboss.org/browse/ISPN-9376
> ISPN-9376 Enhance RemoteStore to support segmentation

- bom/pom.xml
- hibernate/cache-v53/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-9406
> ISPN-9406 Update to Hibernate 5.3.4.Final

- distribution/pom.xml
- javadoc/javadoc-all/pom.xml
- javadoc/javadoc-embedded/pom.xml
Fixes build with `-Pdistribution`
> ISPN-9386 Remove remaining references to websocket module

- Jenkinsfile
- feature-pack/build.xml
- feature-pack/wf-modules/src/main/resources/modules/org/infinispan/hibernate-search/directory-provider/for-hibernatesearch-5.10/module.xml
- feature-pack/wf-modules/src/main/resources/modules/system/layers/base/org/apache/lucene/5.5/module.xml
- feature-pack/wf-modules/src/main/resources/modules/system/layers/base/org/apache/lucene/internal/5.5/module.xml
- pom.xml
- server/integration/feature-pack/build.xml
- server/integration/feature-pack/src/main/resources/modules/system/layers/base/org/apache/lucene/5.5/module.xml
- server/integration/feature-pack/src/main/resources/modules/system/layers/base/org/apache/lucene/internal/5.5/module.xml
https://issues.jboss.org/browse/ISPN-9410
> ISPN-9410 Intermittent Linkage erros when starting the server with indexed caches

- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RouterConnectorResource.java
https://issues.jboss.org/browse/ISPN-9387
Addresses @pruivo 's comment on https://github.com/infinispan/infinispan/pull/6157#discussion_r207272797
> ISPN-9387 Router connector default TCP keepalive should be false

- bom/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-9418
> ISPN-9418 Upgrade to Rxjava 2.2.0

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ExecTypedTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ExecTypedTestWithOlderClients.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/CustomEventLogListener.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/EventLogListener.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/OldClientCustomEventsTest.java
- commons/src/main/java/org/infinispan/commons/dataconversion/DefaultTranscoder.java
- commons/src/main/java/org/infinispan/commons/dataconversion/StandardConversions.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodHeader.java
- tasks/scripting/src/main/java/org/infinispan/scripting/utils/ScriptConversions.java
…lder clients
https://issues.jboss.org/browse/ISPN-9409
https://issues.jboss.org/browse/ISPN-9424
> ISPN-9409 ISPN-9424 CCE on scripts/filters/converters for older Hot Rod clients

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
https://issues.jboss.org/browse/ISPN-9436
> ISPN-9436 expose getServerList

- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
https://issues.jboss.org/browse/ISPN-9409
> ISPN-9409 Fix HotRodMergeTest

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/transcoding/DataFormatTest.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java
https://issues.jboss.org/browse/ISPN-9434
> ISPN-9434 Reading JSON content from untyped caches return escaped quotes

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/transcoding/DataFormatTest.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java
https://issues.jboss.org/browse/ISPN-9434
> [9.3.x] ISPN-9434 Reading JSON content from untyped caches return escaped quotes

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ClusterConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/NearCacheConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
https://issues.jboss.org/browse/ISPN-9427
> ISPN-9427 Expose xsite configuration via hotrod-client.properties

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
Completes 
https://issues.jboss.org/browse/ISPN-9398
https://issues.jboss.org/browse/ISPN-9427
> ISPN-9398 & ISPN-9427 Hotrod configuration via properties file

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/ForgetTransactionOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/RecoveryOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/recovery/RecoveryIterator.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/recovery/RecoveryManager.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tx/RecoveryTest.java
- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod_transaction.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod_wire.adoc
- server/hotrod/src/main/java/org/infinispan/server/hotrod/TransactionRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/BaseCompleteTransactionOperation.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/CommitTransactionOperation.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/RollbackTransactionOperation.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/Util.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/CacheNameCollector.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/GlobalTxTable.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/PerCacheTxTable.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/ConditionalMarkAsRollbackFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/CreateStateFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/PreparingDecisionFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetCompletedTransactionFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetDecisionFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetPreparedFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/TxFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/XidPredicate.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/counter/response/RecoveryTestResponse.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/tx/TopologyChangeFunctionalTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/tx/TxFunctionalTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/tx/TxReaperAndRecoveryTest.java
* Added JavaDoc for the missing classes
* Added Documentation about force-return-values effect
https://issues.jboss.org/browse/ISPN-9438
https://issues.jboss.org/browse/ISPN-9450
> ISPN-9438 & ISPN-9450 Hot Rod Transactions docs

- core/src/main/java/org/infinispan/interceptors/locking/ClusteringDependentLogic.java
https://issues.jboss.org/browse/ISPN-9464
> ISPN-9464 Notify listeners without holding the shared topology lock

- bom/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-9402
Let's see what CI has to say.
> ISPN-9402 Upgrade to JGroups 4.0.13.Final

- hibernate/cache-commons/pom.xml
- hibernate/cache-spi/pom.xml
- hibernate/cache-v51/pom.xml
- hibernate/cache-v51/src/main/resources/features.xml
- hibernate/cache-v53/pom.xml
- hibernate/cache-v53/src/main/resources/features.xml
- integrationtests/osgi/pom.xml
- integrationtests/osgi/src/test/java/org/infinispan/it/osgi/hibernate/cache/v53/HibernateCacheIntegrationTest.java
- integrationtests/osgi/src/test/resources/maven.properties
https://issues.jboss.org/browse/ISPN-8023
> ISPN-8023 Provide infinispan-hibernate-cache-v53 feature

- core/src/main/java/org/infinispan/cache/impl/EncoderCache.java
https://issues.jboss.org/browse/ISPN-9481
> ISPN-9481 implements toString in EncoderCache.EntryWrapper

- core/src/main/java/org/infinispan/partitionhandling/impl/AvailabilityStrategy.java
- core/src/main/java/org/infinispan/partitionhandling/impl/PreferAvailabilityStrategy.java
- core/src/main/java/org/infinispan/partitionhandling/impl/PreferConsistencyStrategy.java
- core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
- core/src/test/java/org/infinispan/remoting/transport/ControlledTransport.java
- core/src/test/java/org/infinispan/scattered/statetransfer/CoordinatorStopTest.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- core/src/test/java/org/infinispan/test/TopologyChangeListener.java
- core/src/test/java/org/infinispan/test/ViewChangeListener.java
- core/src/test/java/org/infinispan/test/transport/DelayedViewJGroupsTransport.java
- core/src/test/java/org/infinispan/topology/TestClusterCacheStatus.java
- core/src/test/java/org/infinispan/tx/InfinispanNodeFailureTest.java
- core/src/test/java/org/infinispan/util/BlockingLocalTopologyManager.java
- core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
https://issues.jboss.org/browse/ISPN-9128
https://issues.jboss.org/browse/ISPN-9095 
Requested by our dear friend @pferraro
> [9.3.x] ISPN-9128 RehashWithSharedStoreTest.testRehashes random failures

- Jenkinsfile
https://issues.jboss.org/browse/ISPN-9488
Please don't close the JIRA, this PR only allows us to see the cleanup script errors in the build log.
> ISPN-9488 Include the cleanup script output in the build log

- core/src/test/java/org/infinispan/test/fwk/TEST_PING.java
https://issues.jboss.org/browse/ISPN-9483
> ISPN-9483 TEST_PING doesn't trigger merge after JGroups 4.0.13 upgrade

- server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/Response.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMergeTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleClusteredNonLoopbackTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodTestingUtil.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/TestHashDistAware10Response.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/TestHashDistAware11Response.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/TestHashDistAware20Response.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/TestTopologyAwareResponse.java
https://issues.jboss.org/browse/ISPN-9415
* Send a complete topology to the client when degraded
* Enhance HotRodMergeTest to test with DENY_READ_WRITES
* Add lots of toString() methods for debugging
> ISPN-9415 HotRod Client takes 60 seconds for each operation after a split

- documentation/src/main/asciidoc/user_guide/clustering.adoc
- documentation/src/main/asciidoc/user_guide/transactions.adoc
Adding note to clarify about FORCE_WRITE_LOCK flag for non-tx caches
> ISPN-9453: Docs update for FORCE_WRITE_LOCK non-tx caches

- commons/src/main/java/org/infinispan/commons/marshall/WrappedBytes.java
- core/src/main/java/org/infinispan/configuration/cache/GroupsConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/cache/MemoryConfigurationBuilder.java
- core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java
- core/src/main/java/org/infinispan/container/impl/BoundedSegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/impl/L1SegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/offheap/BoundedOffHeapDataContainer.java
- core/src/main/java/org/infinispan/container/offheap/ContiguousOffsetCalculator.java
- core/src/main/java/org/infinispan/container/offheap/MemoryAddressHash.java
- core/src/main/java/org/infinispan/container/offheap/ModulusOffsetCalculator.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapDataContainer.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactory.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactoryImpl.java
- core/src/main/java/org/infinispan/container/offheap/OffsetCalculator.java
- core/src/main/java/org/infinispan/container/offheap/SegmentedBoundedOffHeapDataContainer.java
- core/src/main/java/org/infinispan/container/offheap/StripedLock.java
- core/src/main/java/org/infinispan/factories/DataContainerFactory.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/configuration/DataContainerTest.java
- core/src/test/java/org/infinispan/container/offheap/OffHeapMultiNodeTest.java
- core/src/test/java/org/infinispan/container/offheap/OffHeapSingleNodeExpirationEvictionTest.java
- core/src/test/java/org/infinispan/container/offheap/OffHeapSingleNodeTest.java
- core/src/test/java/org/infinispan/eviction/impl/ExceptionEvictionTest.java
- core/src/test/java/org/infinispan/stats/SingleStatsTest.java
- server/rest/src/test/java/org/infinispan/rest/BaseRestOperationsTest.java
- server/rest/src/test/java/org/infinispan/rest/assertion/ResponseAssertion.java
* Add off heap concurrent map to be used by segmented container
https://issues.jboss.org/browse/ISPN-9263
https://issues.jboss.org/browse/ISPN-8380
> ISPN-9263 Segmented Off Heap Data Container

- core/src/main/java/org/infinispan/stream/impl/AbstractCacheStream.java
https://issues.jboss.org/browse/ISPN-9501
> ISPN-9501 AbstractCacheStream.performOperationRehashAware() can hang

- core/src/main/java/org/infinispan/container/offheap/ContiguousOffsetCalculator.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
- core/src/main/java/org/infinispan/factories/DataContainerFactory.java
bucket
* Make sure buckets are address count not scaled to CPU
https://issues.jboss.org/browse/ISPN-9505
> ISPN-9505 Off-heap data container puts all the entries in a single

- server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java
- server/core/src/test/java/org/infinispan/server/core/dataconversion/JsonTranscoderTest.java
https://issues.jboss.org/browse/ISPN-9499
> ISPN-9499 Json to text conversion ignore charset

- server/hotrod/src/main/resources/hotrod.gr
https://issues.jboss.org/browse/ISPN-9530
> ISPN-9530 Error marshalling events with NearCache

- feature-pack/embedded/src/main/resources/modules/org/jgroups/slot/module.xml
- feature-pack/server/src/main/resources/modules/org/jgroups/extension/slot/module.xml
ISPN-9534 ClassNotFoundException: DnsContextFactory when using jgroups.stack=dnsping
> ISPN-9534 ClassNotFoundException: DnsContextFactory when using jgroups.stack=dnsping

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/JsonEventsTest.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java
- server/core/src/test/java/org/infinispan/server/core/dataconversion/JsonTranscoderTest.java
https://issues.jboss.org/browse/ISPN-9520
> ISPN-9520 JSON conversion causes NPE for events

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- commons/src/main/java/org/infinispan/commons/util/Features.java
- commons/src/test/java/org/infinispan/commons/util/FeaturesTest.java
- commons/src/test/resources/META-INF/infinispan-features.properties
- core/src/main/java/org/infinispan/configuration/global/GlobalConfiguration.java
- core/src/main/java/org/infinispan/configuration/global/GlobalConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-9535
> ISPN-9535 Feature toggles

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9546
https://issues.jboss.org/browse/ISPN-9517
> ISPN-9546 Upgrade to JGroups 4.0.15.Final

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9547
> ISPN-9547 JBoss Marshalling 2.0.6

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9549
> ISPN-9549 Netty 4.1.28

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9548
> ISPN-9548 JBoss Logging 3.3.2

- core/src/main/java/org/infinispan/stats/impl/CacheContainerStatsImpl.java
- core/src/main/java/org/infinispan/stats/impl/SecurityActions.java
https://issues.jboss.org/browse/ISPN-9543
> ISPN-9543 Unwrap caches before obtaining stats

- pom.xml
Branding info is already in build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9552
> ISPN-9552 Remove duplicated brand info

- core/src/main/java/org/infinispan/stream/impl/AbstractCacheStream.java
- core/src/main/java/org/infinispan/stream/impl/LocalStreamManagerImpl.java
- core/src/main/java/org/infinispan/stream/impl/TerminalFunctions.java
- core/src/test/java/org/infinispan/stream/stress/DistributedStreamRehashStressTest.java
* Use copy for listener
* Add optimization for REPL to not retry segments
https://issues.jboss.org/browse/ISPN-9542
> ISPN-9542 DistributedStreamRehashStressTest fails many of the tests

- documentation/pom.xml
https://issues.jboss.org/browse/ISPN-9551
> ISPN-9551 Explicitly depend on jruby-complete in the asciidoctor plugin

- core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
- core/src/main/java/org/infinispan/commands/triangle/SingleKeyBackupWriteCommand.java
- core/src/main/java/org/infinispan/commands/write/RemoveExpiredCommand.java
- core/src/main/java/org/infinispan/container/entries/MortalCacheEntry.java
- core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java
- core/src/main/java/org/infinispan/persistence/manager/OrderedUpdatesManagerImpl.java
- core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/cluster/AbstractClusterListenerTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/cluster/AbstractClusterListenerUtilTest.java
* Make removal more strict in checking if expired
* However provide 100 ms buffer
https://issues.jboss.org/browse/ISPN-9514
> ISPN-9514 Entry replaced with same expiration can expire immediately

- build-configuration/bom/pom.xml
- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9557
> ISPN-9557 Align 3rd party deps

- core/src/main/java/org/infinispan/configuration/ConfigurationManager.java
- core/src/main/java/org/infinispan/factories/DataContainerFactory.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/factories/DataContainerFactoryTest.java
https://issues.jboss.org/browse/ISPN-9538
> ISPN-9538 Allow for segmentation to be configurable via Features

- query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerConfigurationBuilder.java
See message on commit
https://issues.jboss.org/browse/ISPN-9559
> ISPN-9559 Server <modules> configuration with a single entry can break classloading

- commons/src/main/java/org/infinispan/commons/util/ServiceFinder.java
- core/src/main/java/org/infinispan/AdvancedCache.java
- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/main/java/org/infinispan/configuration/global/GlobalConfiguration.java
- core/src/main/java/org/infinispan/configuration/global/GlobalConfigurationBuilder.java
- core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java
- core/src/main/java/org/infinispan/factories/ComponentRegistry.java
- core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
- jcache/embedded/src/main/java/org/infinispan/jcache/embedded/JCachingProvider.java
- jcache/embedded/src/main/java/org/infinispan/jcache/embedded/WeakClassLoader.java
https://issues.jboss.org/browse/ISPN-9561
https://issues.jboss.org/browse/ISPN-9563
Fixes random server startup NPEs
> ISPN-9561 GlobalConfiguration should keep strong reference to classloader

- core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.jboss.org/browse/ISPN-9575
> ISPN-9575 Log a WARN when compat mode is used

- feature-pack/server/src/main/resources/modules/org/infinispan/server/hotrod/slot/module.xml
https://issues.jboss.org/browse/ISPN-9574
> ISPN-9574 Remove duplicated counter module from Hot Rod server

- query/src/main/java/org/infinispan/query/impl/CommandInitializer.java
- query/src/main/java/org/infinispan/query/impl/InfinispanQueryStatisticsInfo.java
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/ProtobufMetadataManager.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java
https://issues.jboss.org/browse/ISPN-9573
> ISPN-9573 Stopping a cache can lead to unintentional unregistering of another indexed cache query-related MBeans

- Jenkinsfile
https://issues.jboss.org/browse/ISPN-8997
> ISPN-8997 Revert deploying of artifacts until properly tested.

- core/src/main/resources/schema/infinispan-config-9.4.xsd
- documentation/src/main/asciidoc/user_guide/clustering.adoc
- documentation/src/main/asciidoc/user_guide/persistence.adoc
- documentation/src/main/asciidoc/user_guide/persistence_rocksdb.adoc
Jira: https://issues.jboss.org/browse/ISPN-9516
> ISPN-9516 docs for segmentation

- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/TaskRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/OldClientScriptExecIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/ScriptExecIT.java
https://issues.jboss.org/browse/ISPN-9562
> ISPN-9562 Remote Exec hangs with hotrod 2.[4567] ver and cache name is provided

- core/src/main/java/org/infinispan/container/impl/InternalEntryFactory.java
- core/src/main/java/org/infinispan/container/impl/InternalEntryFactoryImpl.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheWriterInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/TxBatchUpdater.java
- core/src/test/java/org/infinispan/commands/PutMapCommandStressTest.java
during rehash
* Don't attempt to insert non owned entries during batch
https://issues.jboss.org/browse/ISPN-9508
> ISPN-9508 NullPointerException from putAll on a cache with a store

- Jenkinsfile
- build-configuration/bom/pom.xml
- build-configuration/pom.xml
- checkstyle/pom.xml
- license/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-9577
> ISPN-9577 fix deploy urls

- Jenkinsfile-release
- all/pom.xml
- build-configuration/bom/pom.xml
- build-configuration/pom.xml
- checkstyle/pom.xml
- distribution/pom.xml
- integrationtests/as-lucene-directory/pom.xml
- integrationtests/wildfly-modules/pom.xml
- javadoc/doclets/pom.xml
- javadoc/javadoc-all/pom.xml
- javadoc/javadoc-embedded/pom.xml
- javadoc/javadoc-remote/pom.xml
- license/pom.xml
- lucene/directory-provider/pom.xml
- pom.xml
- tools/pom.xml
I think in upstream the `infinispan.brand.version` is always the same as `project.version`. If it is true, I can change the property
I'll squash the commits in the end and open a JIRA
https://issues.jboss.org/browse/ISPN-9581
> ISPN-9581 Backport downstream fixes to upstream

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec28.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/CodecUtils.java
- commons/src/main/java/org/infinispan/commons/dataconversion/MediaType.java
- commons/src/main/java/org/infinispan/commons/dataconversion/MediaTypeIds.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java
- server/hotrod/src/main/resources/hotrod.gr
https://issues.jboss.org/browse/ISPN-9580
> ISPN-9580 Avoid parsing MediaType if an id is provided

- README-i18n.md
- commons/src/main/java/org/infinispan/commons/logging/Log.java
- counter/src/main/java/org/infinispan/counter/logging/Log.java
- documentation/src/main/asciidoc/contributing/basics.adoc
https://issues.jboss.org/browse/ISPN-9606
> ISPN-9606 Fix logging ids for counters module

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9603
> ISPN-9603 Update version of RocksDB

- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.jboss.org/browse/ISPN-8813
> [9.3.x backport] ISPN-8813 Avoid NPE during BaseJPAFilterIndexingServiceProvider.stop()

- core/src/test/java/org/infinispan/distribution/DistSyncFuncTest.java
- core/src/test/java/org/infinispan/test/ReplListener.java
https://issues.jboss.org/browse/ISPN-8616
> ISPN-8616 Fix the replication wait in locked stream tests

- build-configuration/bom/pom.xml
- server/integration/feature-pack/pom.xml
- server/integration/feature-pack/src/main/resources/content/bin/prometheus.bat
- server/integration/feature-pack/src/main/resources/content/bin/prometheus.sh
- server/integration/feature-pack/src/main/resources/content/bin/prometheus_config.yaml
- server/integration/feature-pack/src/main/resources/content/bin/standalone.bat
- server/integration/feature-pack/src/main/resources/content/bin/standalone.conf
- server/integration/feature-pack/src/main/resources/content/bin/standalone.sh
- server/integration/feature-pack/src/main/resources/modules/system/add-ons/product-slot/io/prometheus/jmx/slot/module.xml
Preview of Prometheus integration. *Do not* integrate yet. Need a review from @slaskawi @ryanemerson and @tristantarrant
> ISPN-9558 Export Data Grid stats to Prometheus

- documentation/src/main/asciidoc/user_guide/integrations_spring.adoc
ISPN-9630 Spring Session contains {brandname} into the class name
> ISPN-9630 Spring Session contains {brandname} into the class name

- feature-pack/embedded/pom.xml
- feature-pack/embedded/src/main/resources/modules/org/infinispan/multimap/slot/module.xml
- feature-pack/server/src/main/resources/modules/org/infinispan/extension/slot/module.xml
- feature-pack/server/src/main/resources/modules/org/infinispan/server/hotrod/slot/module.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/HotRodCounterIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/HotRodMultimapIT.java
https://issues.jboss.org/browse/ISPN-9616
> ISPN-9616 server does not include multimap dependency

- documentation/src/main/asciidoc/user_guide/persistence_rocksdb.adoc
ISPN-9626 RocksDB documentation is not compiling because of properties
> ISPN-9626 RocksDB documentation is not compiling because of properties

- core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
- core/src/main/java/org/infinispan/statetransfer/InboundTransferTask.java
- core/src/main/java/org/infinispan/topology/RebalanceConfirmationCollector.java
https://issues.jboss.org/browse/ISPN-3791
The warnings are completely harmless, change them to trace logs.
> ISPN-3791 Silence "Received invalid rebalance confirmation from NodeX"

- pom.xml
https://issues.jboss.org/browse/ISPN-9628
> [9.3] ISPN-9628 Add Multi-Release entry to infinispan-commons jar

- pom.xml
https://issues.jboss.org/browse/ISPN-9628
> ISPN-9628 Add Multi-Release entry to infinispan-commons jar

- core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactoryImpl.java
- core/src/test/java/org/infinispan/container/offheap/OffHeapBoundedMemoryTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationListenerFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreDistListenerFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreListenerFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreListenerFunctionalTest.java
with expiration
* Make sure to include expiration when not using version or custom
https://issues.jboss.org/browse/ISPN-9641
> ISPN-9641 Using expiration with off heap doesn't subtract size properly

- core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactoryImpl.java
- core/src/test/java/org/infinispan/container/offheap/OffHeapBoundedMemoryTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationListenerFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreDistListenerFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreListenerFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreListenerFunctionalTest.java
with expiration
* Make sure to include expiration when not using version or custom
https://issues.jboss.org/browse/ISPN-9641
> [9.3.x] ISPN-9641 Using expiration with off heap doesn't subtract size properly

- core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/notifications/Listenable.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/AbstractDelegatingHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/BasePerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/PerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/TotalOrderTxPerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
- core/src/main/java/org/infinispan/statetransfer/StateTransferManager.java
- core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java
- core/src/test/java/org/infinispan/conflict/impl/ConflictManagerTest.java
- core/src/test/java/org/infinispan/conflict/impl/CrashedNodeDuringConflictResolutionTest.java
- core/src/test/java/org/infinispan/conflict/impl/OperationsDuringMergeConflictTest.java
- core/src/test/java/org/infinispan/container/versioning/WriteSkewConsistencyTest.java
- core/src/test/java/org/infinispan/distribution/rehash/OngoingTransactionsAndJoinTest.java
- core/src/test/java/org/infinispan/notifications/cachemanagerlistener/CacheManagerNotifierTest.java
- core/src/test/java/org/infinispan/partitionhandling/BaseTxPartitionAndMergeTest.java
- core/src/test/java/org/infinispan/scattered/BiasLeaseTest.java
- core/src/test/java/org/infinispan/scattered/statetransfer/PushTransferTest.java
- core/src/test/java/org/infinispan/test/concurrent/InboundRpcSequencerAction.java
- core/src/test/java/org/infinispan/tx/PessimisticDeadlockTest.java
- core/src/test/java/org/infinispan/tx/PrepareProcessedAfterOriginatorCrashTest.java
- extended-statistics/src/test/java/org/infinispan/stats/BaseClusteredExtendedStatisticTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/AbstractFunctionalTest.java
* Avoid IllegalLifecycleStateExceptions on shutdown
* Update registerComponent() javadoc
* Ignore IllegalLifecycleStateException when removing listener
https://issues.jboss.org/browse/ISPN-9627
> ISPN-9127 followup

- commons/src/main/java/org/infinispan/commons/logging/Log.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RouterService.java
* Prevent startup when single port is configured but not enabled
https://issues.jboss.org/browse/ISPN-9638
> ISPN-9638 Make Single port server a feature

- commons/src/main/java/org/infinispan/commons/util/AbstractDelegatingCollection.java
- commons/src/main/java/org/infinispan/commons/util/AbstractDelegatingConcurrentMap.java
- commons/src/main/java/org/infinispan/commons/util/AbstractDelegatingMap.java
- commons/src/main/java/org/infinispan/commons/util/AbstractDelegatingSet.java
- core/src/main/java/org/infinispan/distribution/util/ReadOnlySegmentAwareCollection.java
- core/src/main/java/org/infinispan/distribution/util/ReadOnlySegmentAwareMap.java
- core/src/main/java/org/infinispan/stream/impl/tx/TxClusterStreamManager.java
- core/src/main/java/org/infinispan/util/AbstractDelegatingCloseableIteratorCollection.java
- core/src/main/java/org/infinispan/util/AbstractDelegatingCloseableIteratorSet.java
- core/src/test/java/org/infinispan/functional/decorators/FunctionalAdvancedCache.java
https://issues.jboss.org/browse/ISPN-8844
> [9.3] ISPN-8844 Avoid package overlap between commons and core

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9639
> ISPN-9639 Upgrade Narayana to version 5.9.0.Final

- core/src/main/java/org/infinispan/configuration/cache/EvictionConfigurationBuilder.java
* Remove validation from eviction configuration
https://issues.jboss.org/browse/ISPN-9656
> ISPN-9656 Deprecated Eviction Builder reports inaccurate warning

- pom.xml
https://issues.jboss.org/browse/ISPN-9662
> ISPN-9662 commons-compress 1.18

- server/integration/feature-pack/src/main/resources/configuration/standalone/subsystems-cloud.xml
- server/integration/feature-pack/src/main/resources/configuration/standalone/subsystems-clustered.xml
- server/integration/feature-pack/src/main/resources/configuration/standalone/subsystems-services.xml
- server/integration/feature-pack/src/main/resources/configuration/standalone/subsystems.xml
- server/integration/infinispan/src/main/resources/subsystem-templates/infinispan-io.xml
https://issues.jboss.org/browse/ISPN-9663
> ISPN-9663 Reduce the XNIO threads to 2

- documentation/src/main/asciidoc/server_guide/management.adoc
- server/rest/src/main/java/org/infinispan/rest/logging/RestAccessLoggingHandler.java
- server/rest/src/test/java/org/infinispan/rest/logging/RestAccessLoggingTest.java
https://issues.jboss.org/browse/ISPN-9655
> ISPN-9655 REST Access Log headers

- documentation/src/main/asciidoc/server_guide/management.adoc
https://issues.jboss.org/browse/ISPN-9674
> ISPN-9674 Docs for Access Logs

- core/src/test/java/org/infinispan/expiration/impl/ExpirationListenerFunctionalTest.java
[https://issues.jboss.org/browse/ISPN-9511](https://issues.jboss.org/browse/ISPN-9511)
> ISPN-9511 Expired event is not raised when modifying an expired entry

- documentation/src/main/asciidoc/getting_started/embedded_cache.adoc
- documentation/src/main/asciidoc/getting_started/example_with_groovy.adoc
- documentation/src/main/asciidoc/server_guide/configuration.adoc
- documentation/src/main/asciidoc/server_guide/security.adoc
- documentation/src/main/asciidoc/user_guide/locked_streams.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
- documentation/src/main/asciidoc/user_guide/streams.adoc
https://issues.jboss.org/browse/ISPN-9652
> ISPN-9652 Fixing broken headings in docs

- core/src/main/java/org/infinispan/persistence/file/SingleFileStore.java
https://issues.jboss.org/browse/ISPN-7186
This will need backporting to 9.4.x as well.
> ISPN-7186 SFS Avoid Reading Index if Purge on startup is enabled

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9710
> ISPN-9710 Upgrade to Maven Surefire 3.0.0-M1

- documentation/src/main/asciidoc/user_guide/persistence_sfs.adoc
https://issues.jboss.org/browse/ISPN-9711
> ISPN-9711 fixing markup issues

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientCustomEventsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/CustomEventLogListener.java
- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
https://issues.jboss.org/browse/ISPN-9702
> ISPN-9702 ClassCastException when using converters in remote events

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientCustomEventsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/CustomEventLogListener.java
- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
https://issues.jboss.org/browse/ISPN-9702
> [9.3.x] ISPN-9702 ClassCastException when using converters in remote events

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientCustomEventsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/CustomEventLogListener.java
- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
https://issues.jboss.org/browse/ISPN-9702
> [9.4.x] ISPN-9702 ClassCastException when using converters in remote events

- commons/src/main/java/org/infinispan/commons/stat/DefaultSimpleStat.java
- commons/src/main/java/org/infinispan/commons/stat/SimpleStat.java
- commons/src/test/java/org/infinispan/commons/stat/DefaultSimpleStatTest.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/AbstractDelegatingHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/BasePerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/NonTotalOrderPerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/NonTotalOrderTxPerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/PerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/TrianglePerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManager.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
- core/src/main/java/org/infinispan/remoting/transport/AggregateBackupResponse.java
- core/src/main/java/org/infinispan/remoting/transport/BackupResponse.java
- core/src/main/java/org/infinispan/remoting/transport/RetryOnFailureXSiteCommand.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponse.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateProviderImpl.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferManagerImpl.java
- core/src/test/java/org/infinispan/jmx/PerCacheInboundHandlerMBeanTest.java
- core/src/test/java/org/infinispan/jmx/RpcManagerMBeanTest.java
- core/src/test/java/org/infinispan/util/AbstractDelegatingRpcManager.java
- core/src/test/java/org/infinispan/xsite/offline/DelegatingTransport.java
- extended-statistics/src/main/java/org/infinispan/stats/wrappers/ExtendedStatisticRpcManager.java
- query/src/test/java/org/infinispan/query/affinity/TrackingRpcManager.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheMetricsHandler.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanResourceDescriptionResolver.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/MetricKeys.java
- server/integration/infinispan/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
* Add average/max/min replication time (sync only)
* Add replication counts to xsite (both async and sync)
https://issues.jboss.org/browse/ISPN-8144
https://issues.jboss.org/browse/ISPN-9661
> ISPN-8144 & ISPN-9661 Cross-Site statistics

- commons/src/main/java/org/infinispan/commons/stat/DefaultSimpleStat.java
- commons/src/main/java/org/infinispan/commons/stat/SimpleStat.java
- commons/src/test/java/org/infinispan/commons/stat/DefaultSimpleStatTest.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/AbstractDelegatingHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/BasePerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/NonTotalOrderPerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/NonTotalOrderTxPerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/PerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/TrianglePerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManager.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
- core/src/main/java/org/infinispan/remoting/transport/AggregateBackupResponse.java
- core/src/main/java/org/infinispan/remoting/transport/BackupResponse.java
- core/src/main/java/org/infinispan/remoting/transport/RetryOnFailureXSiteCommand.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponse.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateProviderImpl.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferManagerImpl.java
- core/src/test/java/org/infinispan/jmx/PerCacheInboundHandlerMBeanTest.java
- core/src/test/java/org/infinispan/jmx/RpcManagerMBeanTest.java
- core/src/test/java/org/infinispan/util/AbstractDelegatingRpcManager.java
- core/src/test/java/org/infinispan/xsite/offline/DelegatingTransport.java
- extended-statistics/src/main/java/org/infinispan/stats/wrappers/ExtendedStatisticRpcManager.java
- query/src/test/java/org/infinispan/query/affinity/TrackingRpcManager.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheMetricsHandler.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanResourceDescriptionResolver.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/MetricKeys.java
- server/integration/infinispan/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
https://issues.jboss.org/browse/ISPN-8144
https://issues.jboss.org/browse/ISPN-9661
> [9.4.x] ISPN-8144 & ISPN-9661 Cross-Site statistics

- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/NonTxQueryTest.java
- hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/impl/QueryResultsRegionImpl.java
https://issues.jboss.org/browse/ISPN-9677
> ISPN-9677 Check tx running when updating query cache

- core/src/test/java/org/infinispan/notifications/cachelistener/cluster/RehashClusterListenerTest.java
* Make sure to reset CH each method
* Change assertion to match
https://issues.jboss.org/browse/ISPN-9713
> ISPN-9713 RehashClusterListenerTest can fail due to ordering of tests

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ExpiryTest.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/MetadataUtils.java
https://issues.jboss.org/browse/ISPN-9717
Source: https://github.com/infinispan/infinispan/pull/6402 with a test added. Thanks to @msfm
> ISPN-9717 Fix Integer overflow for lifespan and maxIdle

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ExpiryTest.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/MetadataUtils.java
https://issues.jboss.org/browse/ISPN-9717
> [9.4.x] ISPN-9717 Fix Integer overflow for lifespan and maxIdle

- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java
- server/integration/testsuite/build-testsuite.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryNearCacheIT.java
- server/integration/testsuite/src/test/resources/arquillian.xml
- server/integration/testsuite/src/test/resources/config/infinispan/indexing-minimal.xml
https://issues.jboss.org/browse/ISPN-9611
> ISPN-9611 Error executing command PutMapCommand

- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java
- server/integration/testsuite/build-testsuite.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryNearCacheIT.java
- server/integration/testsuite/src/test/resources/arquillian.xml
- server/integration/testsuite/src/test/resources/config/infinispan/indexing-minimal.xml
https://issues.jboss.org/browse/ISPN-9611
> [9.4.x] ISPN-9611 Error executing command PutMapCommand

- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- query/src/main/java/org/infinispan/query/impl/SecurityActions.java
- query/src/main/java/org/infinispan/query/impl/externalizers/LuceneBooleanQueryExternalizer.java
- query/src/main/java/org/infinispan/query/logging/Log.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteContinuousQueryIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteNonIndexedQueryIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryBaseIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryDescriptorIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryIspnDirIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryKeySetIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQuerySecurityIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryStringIT.java
- server/integration/testsuite/src/test/resources/arquillian.xml
https://issues.jboss.org/browse/ISPN-6728
> ISPN-6728 Add ability to override BooleanQuery.maxClauseCount

- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- query/src/main/java/org/infinispan/query/impl/SecurityActions.java
- query/src/main/java/org/infinispan/query/impl/externalizers/LuceneBooleanQueryExternalizer.java
- query/src/main/java/org/infinispan/query/logging/Log.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteContinuousQueryIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteNonIndexedQueryIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryBaseIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryDescriptorIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryIspnDirIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryKeySetIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQuerySecurityIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryStringIT.java
- server/integration/testsuite/src/test/resources/arquillian.xml
* added "infinispan.query.lucene.max-boolean-clauses" system property for setting BooleanQuery.setMaxClauseCount
https://issues.jboss.org/browse/ISPN-6728
> [9.4.x] ISPN-6728 Add ability to override BooleanQuery.maxClauseCount

- core/src/main/java/org/infinispan/Version.java
- core/src/main/resources/META-INF/infinispan-version.properties
https://issues.jboss.org/browse/ISPN-9724
> ISPN-9724 Use infinispan.base.version for Version.getModuleSlot()

- documentation/src/main/asciidoc/user_guide/integrations_spring.adoc
https://issues.jboss.org/browse/ISPN-9709
> ISPN-9709 doc edits for Spring integration

- core/src/main/java/org/infinispan/Version.java
- core/src/main/resources/META-INF/infinispan-version.properties
https://issues.jboss.org/browse/ISPN-9724
> [9.4.x] ISPN-9724 Use infinispan.base.version for Version.getModuleSlot()

- query/src/test/java/org/infinispan/query/blackbox/ClusteredCacheFSDirectoryTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCacheAsyncCacheStoreTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCacheFSDirectoryTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCachePerfIspnDirConfTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCachePerfProgrammaticConfTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCachePerformantConfTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCacheTest.java
https://issues.jboss.org/browse/ISPN-9725
> ISPN-9725 Blackbox query tests are failing due to improper teardown

- query/src/test/java/org/infinispan/query/blackbox/ClusteredCacheFSDirectoryTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCacheAsyncCacheStoreTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCacheFSDirectoryTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCachePerfIspnDirConfTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCachePerfProgrammaticConfTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCachePerformantConfTest.java
- query/src/test/java/org/infinispan/query/blackbox/LocalCacheTest.java
https://issues.jboss.org/browse/ISPN-9725
> [9.4.x] ISPN-9725 Blackbox query tests are failing due to improper teardown

- documentation/src/main/asciidoc/user_guide/integrations_spring.adoc
ISPN-9709 adding anchors
ISPN-9709 review edits
ISPN-9709 updating mvn dependencies
> Backporting docs: ISPN-9709 doc edits for Spring integration

- spring/spring4/spring4-remote/src/main/java/org/infinispan/spring/provider/SpringRemoteCacheManager.java
- spring/spring4/spring4-remote/src/test/java/org/infinispan/spring/provider/SpringRemoteCacheManagerFactoryBeanContextTest.java
https://issues.jboss.org/browse/ISPN-9731
> [9.4.x] ISPN-9731 Fix SpringRemoteCacheManager.getWriteTimeout

- spring/spring4/spring4-remote/src/main/java/org/infinispan/spring/provider/SpringRemoteCacheManager.java
- spring/spring4/spring4-remote/src/test/java/org/infinispan/spring/provider/SpringRemoteCacheManagerFactoryBeanContextTest.java
https://issues.jboss.org/browse/ISPN-9731
> ISPN-9731 Fix SpringRemoteCacheManager.getWriteTimeout

- core/src/main/java/org/infinispan/stream/impl/DistributedCacheStream.java
non shared stores
* Only prevent local optimization for shared stores with write behind
https://issues.jboss.org/browse/ISPN-9732
> ISPN-9732 Local iteration optimization with write behind is valid for

- core/src/main/java/org/infinispan/stream/impl/DistributedCacheStream.java
non shared stores
* Only prevent local optimization for shared stores with write behind
https://issues.jboss.org/browse/ISPN-9732
> [9.4.x] ISPN-9732 Local iteration optimization with write behind is valid for

- documentation/src/main/asciidoc/user_guide/query.adoc
https://issues.jboss.org/browse/ISPN-9647
@gustavonalle and @anistor review, please. ISPN docs don't really cover analysis and I'm not sure what level of detail we need to go into here. maybe it will be sufficient to mention the default analyzers for now and wait to add more detail on using them when we address the larger issues with querying and indexing in docs. thanks!
> ISPN-9647 adding default analyzers

- build-configuration/pom.xml
- integrationtests/all-embedded-it/pom.xml
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/ProtocolServerConnectorResource.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/configs/ExampleConfigsIT.java
https://issues.jboss.org/browse/ISPN-9719
> [9.4.x] ISPN-9719 Upgrade WildFly Core to 6.0.2

- build-configuration/pom.xml
- integrationtests/all-embedded-it/pom.xml
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/ProtocolServerConnectorResource.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/configs/ExampleConfigsIT.java
https://issues.jboss.org/browse/ISPN-9719
> ISPN-9719 Upgrade WildFly Core to 6.0.2

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- core/src/main/java/org/infinispan/executors/LazyInitializingBlockingTaskAwareExecutorService.java
- core/src/main/java/org/infinispan/executors/LazyInitializingExecutorService.java
- core/src/main/java/org/infinispan/executors/LazyInitializingScheduledExecutorService.java
- core/src/main/java/org/infinispan/executors/ManageableExecutorService.java
- core/src/main/java/org/infinispan/jmx/AbstractJmxRegistration.java
- core/src/main/java/org/infinispan/jmx/ResourceDMBean.java
- core/src/test/java/org/infinispan/jmx/CacheManagerMBeanTest.java
- server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
- server/core/src/main/java/org/infinispan/server/core/transport/NettyChannelInitializer.java
- server/core/src/main/java/org/infinispan/server/core/transport/NettyTransport.java
- server/core/src/main/java/org/infinispan/server/core/transport/Transport.java
- server/core/src/main/java/org/infinispan/server/core/utils/ManageableThreadPoolExecutorService.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseDecoder.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/jmx/management/JmxManagementIT.java
- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedServer.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
> [9.4.x] ISPN-9708 Expose the executor services through JMX

- spring/spring4/spring4-common/src/main/java/org/infinispan/spring/provider/SpringCache.java
- spring/spring4/spring4-embedded/src/test/java/org/infinispan/spring/provider/SpringCacheTest.java
https://issues.jboss.org/browse/ISPN-9705
https://issues.jboss.org/browse/ISPN-9706
both have to be backported
> ISPN-9705 and ISPN-9706 Null values bugs

- core/src/main/java/org/infinispan/executors/LazyInitializingBlockingTaskAwareExecutorService.java
- core/src/main/java/org/infinispan/executors/ManageableExecutorService.java
- core/src/test/java/org/infinispan/jmx/CacheManagerMBeanTest.java
- core/src/test/java/org/infinispan/jmx/ClusteredCacheManagerMBeanTest.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
Fix remote command executor attributes
> [9.4.x] ISPN-9708 Fix remote threadpool attributes in JMX

- core/src/main/java/org/infinispan/executors/LazyInitializingBlockingTaskAwareExecutorService.java
- core/src/main/java/org/infinispan/executors/ManageableExecutorService.java
- core/src/test/java/org/infinispan/jmx/CacheManagerMBeanTest.java
- core/src/test/java/org/infinispan/jmx/ClusteredCacheManagerMBeanTest.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
Fix remote command executor attributes
> ISPN-9708 Fix remote threadpool attributes in JMX

- build-configuration/pom.xml
- jcache/tck-runner/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-9753
> ISPN-9753 Fix maven parallel builds

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
methods
https://issues.jboss.org/browse/ISPN-9752
> ISPN-9752 JDBCStringBasedStore should disable auto commit for publish

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
methods
https://issues.jboss.org/browse/ISPN-9752
> [9.4.x] ISPN-9752 JDBCStringBasedStore should disable auto commit for publish

- core/src/test/java/org/infinispan/jmx/ClusteredCacheManagerMBeanTest.java
Test only constant attributes
Random failures were introduced by https://github.com/infinispan/infinispan/pull/6431
> ISPN-9708 Fix ClusteredCacheManagerMBeanTest random failures

- server/hotrod/src/main/resources/hotrod.gr
https://issues.jboss.org/browse/ISPN-9746
> ISPN-9746 HotRod decoder should release allocated buffers

- core/src/main/java/org/infinispan/transaction/impl/TransactionTable.java
https://issues.jboss.org/browse/ISPN-9701
@danberindei Please review.
Needs backporting to 9.4.x, 9.3.x, and 8.2.x.
> ISPN-9701 TransactionTable does not shutdown gracefully

- pom.xml
https://issues.jboss.org/browse/ISPN-9767
> ISPN-9767 Don't exclude *.txt files from jars

- pom.xml
https://issues.jboss.org/browse/ISPN-9767
> [9.4] ISPN-9767 Don't exclude *.txt files from jars

- core/src/test/java/org/infinispan/persistence/PassivatePersistentTest.java
- core/src/test/java/org/infinispan/persistence/PassivationFunctionalTest.java
> ISPN-8381 Offheap passivation

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/BuiltInAnalyzersTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/TestEntity.java
- client/hotrod-client/src/test/resources/analyzers.proto
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/ProtobufValueWrapperAnalyzerDiscriminator.java
https://issues.jboss.org/browse/ISPN-9742
> [9.4.x] ISPN-9742 Analyzers not working for inner objects

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/BuiltInAnalyzersTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/TestEntity.java
- client/hotrod-client/src/test/resources/analyzers.proto
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/ProtobufValueWrapperAnalyzerDiscriminator.java
https://issues.jboss.org/browse/ISPN-9742
Reproducer only
> ISPN-9742 Analyzers not working for inner objects

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResource.java
- server/rest/src/test/java/org/infinispan/rest/RestOperationsTest.java
- server/rest/src/test/java/org/infinispan/rest/helper/RestServerHelper.java
https://issues.jboss.org/browse/ISPN-9749
> ISPN-9749 Rest PUT fails to replace value when storing pojos without equality

- server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/BinaryOutputPrinter.java
- server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/JSONOutputPrinter.java
- server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/TextOutputPrinter.java
- server/rest/src/main/java/org/infinispan/rest/operations/mediatypes/impl/XMLOutputPrinter.java
- server/rest/src/test/java/org/infinispan/rest/BaseRestOperationsTest.java
- server/rest/src/test/java/org/infinispan/rest/RestOperationsOffHeapTest.java
- server/rest/src/test/java/org/infinispan/rest/RestOperationsTest.java
- server/rest/src/test/java/org/infinispan/rest/TestClass.java
https://issues.jboss.org/browse/ISPN-9707
> [9.4.x] ISPN-9707 Getting keys via REST fails with SerializationException

- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointInteroperabilityTest.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/SecurityActions.java
https://issues.jboss.org/browse/ISPN-9739
> ISPN-9739 REST call fails when deleting and re-creating a cache

- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointInteroperabilityTest.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/SecurityActions.java
https://issues.jboss.org/browse/ISPN-9739
> [9.4.x] ISPN-9739 REST call fails when deleting and re-creating a cache

- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/NonTxQueryTest.java
- hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/impl/QueryResultsRegionImpl.java
https://issues.jboss.org/browse/ISPN-9677
> [9.4.x] ISPN-9677 Check tx running when updating query cache

- core/src/main/java/org/infinispan/context/Flag.java
- core/src/main/java/org/infinispan/context/impl/FlagBitSets.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/TxInterceptor.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManager.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerStub.java
- core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/ClassLoaderManagerDisablingTest.java
- core/src/test/java/org/infinispan/persistence/SharedStoreTest.java
- core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stores/TxStoreTest.java
async
* Directly ask loader for size when a shared store
https://issues.jboss.org/browse/ISPN-9754
> ISPN-9754 Cache size method should consult Shared cache stores when not

- core/src/main/java/org/infinispan/context/Flag.java
- core/src/main/java/org/infinispan/context/impl/FlagBitSets.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/TxInterceptor.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManager.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerStub.java
- core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/ClassLoaderManagerDisablingTest.java
- core/src/test/java/org/infinispan/persistence/SharedStoreTest.java
- core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stores/TxStoreTest.java
async
* Directly ask loader for size when a shared store
https://issues.jboss.org/browse/ISPN-9754
> [9.4.x] ISPN-9754 Cache size method should consult Shared cache stores when not

- documentation/src/main/asciidoc/user_guide/compatibility_mode.adoc
- documentation/src/main/asciidoc/user_guide/encoding.adoc
- documentation/src/main/asciidoc/user_guide/endpoint_interop.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_memcached.adoc
https://issues.jboss.org/browse/ISPN-9646
> ISPN-9646 Docs for Protocol Interoperability

- server/rest/src/main/java/org/infinispan/rest/RestServer.java
https://issues.jboss.org/browse/ISPN-9782
> ISPN-9782 RestServer.stop() should call super.stop()

- server/rest/src/main/java/org/infinispan/rest/RestServer.java
https://issues.jboss.org/browse/ISPN-9782
> [9.4] ISPN-9782 RestServer.stop() should call super.stop()

- core/src/main/java/org/infinispan/transaction/impl/TransactionTable.java
- core/src/test/java/org/infinispan/lock/singlelock/AbstractInitiatorCrashTest.java
- core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
https://issues.jboss.org/browse/ISPN-9701
> [9.3.x] ISPN-9701 TransactionTable does not shutdown gracefully

- core/src/main/java/org/infinispan/configuration/cache/L1ConfigurationBuilder.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/configuration/cache/L1ConfigurationBuilderTest.java
eviction
https://issues.jboss.org/browse/ISPN-9297
> ISPN-9605 Prevent cache configuration that has L1 and exception based

- documentation/src/main/asciidoc/server_guide/configuration.adoc
- documentation/src/main/asciidoc/server_guide/security.adoc
> [9.4.x] Backport of ISPN-9741 Formatting Fixes

- server/integration/feature-pack/src/main/resources/content/bin/prometheus_config.yaml
An updated JMX Prometheus agent configuration. This configuration is better suitable for Grafana dashboards. All credit goes to Madou Coulibaly
> ISPN-9786 Update Prometheus JMX agent configuration pattern

- build-configuration/pom.xml
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- documentation/src/main/asciidoc/upgrading/upgrading-content.adoc
- documentation/src/main/asciidoc/user_guide/integrations_spring.adoc
- integrationtests/spring-boot-it/pom.xml
- integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/AbstractSpringSessionTCK.java
- integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/configuration/WebConfig.java
- integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/remote/RemoteSpringSessionTest.java
- pom.xml
- spring/spring5/pom.xml
- spring/spring5/spring5-common/pom.xml
- spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/session/AbstractApplicationPublisherBridge.java
- spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/session/AbstractInfinispanSessionRepository.java
- spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanApplicationPublishedBridgeTCK.java
- spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanSessionRepositoryTCK.java
- spring/spring5/spring5-embedded/pom.xml
- spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/session/EmbeddedApplicationPublishedBridge.java
- spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/session/configuration/InfinispanEmbeddedHttpSessionConfiguration.java
- spring/spring5/spring5-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepositoryTest.java
- spring/spring5/spring5-remote/pom.xml
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepository.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/session/RemoteApplicationPublishedBridge.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/session/configuration/EnableInfinispanRemoteHttpSession.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/session/configuration/InfinispanRemoteHttpSessionConfiguration.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/support/InfinispanNamedRemoteCacheFactoryBean.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepositoryTest.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/session/RemoteApplicationPublishedBridgeTest.java
Spring Session was not using the good version
Some API changes are included
https://issues.jboss.org/browse/ISPN-7035
> ISPN-7035 Spring Session 2.1 support

- feature-pack/embedded-query/pom.xml
- feature-pack/embedded-query/src/main/resources/feature-pack-build.xml
- feature-pack/embedded-query/src/main/resources/modules/org/infinispan/query/slot/module.xml
https://issues.jboss.org/browse/ISPN-9795
> ISPN-9795 Make the elastic search module optional

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/BulkOperationsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/ReplicationRetryTest.java
- documentation/src/main/asciidoc/upgrading/upgrading-content.adoc
- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EmbeddedHotRodBulkTest.java
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/AbstractRemoteCacheIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/security/HotRodAuthzOperationTests.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/security/HotRodOperationsAuthzIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/configs/ExampleConfigsIT.java
https://issues.jboss.org/browse/ISPN-9683
https://issues.jboss.org/browse/ISPN-9785
> ISPN-9863 Remove getBulk methods from RemoteCache

- core/src/main/java/org/infinispan/marshall/exts/DoubleSummaryStatisticsExternalizer.java
- core/src/main/java/org/infinispan/marshall/exts/IntSummaryStatisticsExternalizer.java
- core/src/main/java/org/infinispan/marshall/exts/LongSummaryStatisticsExternalizer.java
- core/src/main/java/org/infinispan/marshall/exts/SecurityActions.java
- core/src/test/java/org/infinispan/marshall/exts/AbstractExternalizerTest.java
- core/src/test/java/org/infinispan/marshall/exts/DoubleSummaryStatisticsExternalizerTest.java
- core/src/test/java/org/infinispan/marshall/exts/IntSummaryStatisticsExternalizerTest.java
- core/src/test/java/org/infinispan/marshall/exts/LongSummaryStatisticsExternalizerTest.java
https://issues.jboss.org/browse/ISPN-9720
Upstream for https://github.com/infinispan/infinispan/pull/6411
> ISPN-9720 JDK11: An illegal reflective access operation has occurred

- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_bom.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_embedded.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_remote.adoc
- documentation/src/main/asciidoc/user_guide/integrations_spring.adoc
https://issues.jboss.org/browse/ISPN-9799
Dependencies are externalized to separate asciidoc files.
> ISPN_9799 integrating productized spring boot

- core/src/test/java/org/infinispan/lock/singlelock/AbstractInitiatorCrashTest.java
- core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
Forward port of the test fix in https://github.com/infinispan/infinispan/pull/6477
> [9.4.x] ISPN-9701 Fix InitiatorCrashPessimisticTest

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
Backport of #6510 
https://issues.jboss.org/browse/ISPN-9798
https://issues.jboss.org/browse/ISPN-9800
> [9.4.x] ISPN-9798 Availability deadlock fixes

- core/src/test/java/org/infinispan/lock/singlelock/AbstractInitiatorCrashTest.java
- core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
Forward port of the test fix in #6477
> ISPN-9701 Fix InitiatorCrashPessimisticTest

- server/integration/feature-pack/src/main/resources/content/bin/prometheus_config.yaml
Update Prometheus metrics format for 9.4.x branch
> [9.4.x] ISPN-9786 Update Prometheus JMX agent configuration pattern

- Jenkinsfile
https://issues.jboss.org/browse/ISPN-9787
> ISPN-9787 Integration tests fail on the 8.2.x branch

- build-configuration/bom/pom.xml
- build-configuration/pom.xml
* To avoid patch conflicts with downstream every time console gets updated!
https://issues.jboss.org/browse/ISPN-9809
> [9.4.x] ISPN-9809 Added version.component.console

- core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java
- core/src/main/java/org/infinispan/topology/LocalTopologyManager.java
- core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
- core/src/main/java/org/infinispan/util/AbstractControlledLocalTopologyManager.java
- core/src/test/java/org/infinispan/topology/MockLocalTopologyManager.java
https://issues.jboss.org/browse/ISPN-9805
> ISPN-9805 Use remote-timeout for leave requests

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
Backport of #6510
https://issues.jboss.org/browse/ISPN-9798
https://issues.jboss.org/browse/ISPN-9800
> [9.3.x] ISPN-9798 Availability deadlock fixes 

- build-configuration/pom.xml
- integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/web/TestRESTController.java
- pom.xml
https://issues.jboss.org/browse/ISPN-9818
> ISPN-9818 upgrade tomcat version

- query/src/test/java/org/infinispan/query/affinity/AffinityTest.java
https://issues.jboss.org/browse/ISPN-9825
Disabling the test for now until further investigation is done
> ISPN-9825 Disable test

- core/src/main/java/org/infinispan/globalstate/ConfigurationStorage.java
- core/src/main/java/org/infinispan/globalstate/ScopeFilter.java
- core/src/main/java/org/infinispan/globalstate/package-info.java
https://issues.jboss.org/browse/ISPN-9823
> ISPN-9823 Include JavaDocs for org.infinispan.globalstate

- distribution/package.xml
- distribution/pom.xml
https://issues.jboss.org/browse/ISPN-9826
> [9.4] ISPN-9826 Include the Spring5 modules in the distributions

- core/src/main/java/org/infinispan/globalstate/ConfigurationStorage.java
- core/src/main/java/org/infinispan/globalstate/ScopeFilter.java
- documentation/src/main/asciidoc/user_guide/cache_manager.adoc
https://issues.jboss.org/browse/ISPN-9788
> ISPN-9788 edits to obtaining cache docs

- core/src/main/java/org/infinispan/globalstate/ConfigurationStorage.java
- core/src/main/java/org/infinispan/globalstate/ScopeFilter.java
- documentation/src/main/asciidoc/user_guide/cache_manager.adoc
Note: Conflicts with https://github.com/infinispan/infinispan/pull/6544
> [9.4.x] ISPN-9788 edits to obtaining cache docs

- commons/src/main/java/org/infinispan/commons/configuration/ClassWhiteList.java
https://issues.jboss.org/browse/ISPN-9830
> ISPN-9830 ClassWhiteList loads jboss marshalling despite being optional

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/IdleStateHandlerProvider.java
https://issues.jboss.org/browse/ISPN-9831
> ISPN-9831 IdleStateHandlerProvider's log should be static

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
https://issues.jboss.org/browse/ISPN-9833
> ISPN-9833 Reorganize to not load jmx classes in client

- core/src/main/java/org/infinispan/commands/RemoteCommandsFactory.java
- core/src/main/java/org/infinispan/manager/impl/AllClusterExecutor.java
- core/src/main/java/org/infinispan/manager/impl/ReplicableManagerFunctionCommand.java
- core/src/main/java/org/infinispan/manager/impl/ReplicableRunnableCommand.java
- core/src/main/java/org/infinispan/manager/impl/SingleClusterExecutor.java
- core/src/main/java/org/infinispan/marshall/exts/ReplicableCommandExternalizer.java
https://issues.jboss.org/browse/ISPN-9808
> ISPN-9808 Cluster executor commands don't end in Command

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/MixedExpiryTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientClusterExpirationEventsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientClusterFailoverEventsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tx/RecoveryTest.java
- core/src/test/java/org/infinispan/container/offheap/OffHeapSingleNodeTest.java
- core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/CustomLoaderNonNullWithExpirationTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationWithClusteredWriteSkewTest.java
- core/src/test/java/org/infinispan/interceptors/impl/CacheMgmtInterceptorTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/cluster/AbstractClusterListenerUtilTest.java
- core/src/test/java/org/infinispan/util/ControlledTimeService.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/tx/TxReaperAndRecoveryTest.java
https://issues.jboss.org/browse/ISPN-9834
> ISPN-9834 Use a constant start time in ControlledTimeService

- server/integration/jgroups/src/main/resources/jgroups-defaults.xml
https://issues.jboss.org/browse/ISPN-9828
> ISPN-9828 Server defaults missing for UFC_NB and MFC_NB

- documentation/src/main/asciidoc/topics/productized/spring_boot_starter.adoc
- documentation/src/main/asciidoc/user_guide/integrations_spring.adoc
https://issues.jboss.org/browse/ISPN-9799
> ISPN-9799 Spring dependency changes

- documentation/src/main/asciidoc/topics/dependencies/sb2_embedded.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb2_remote.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_actuator.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_bom.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_embedded.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_remote.adoc
- documentation/src/main/asciidoc/topics/productized/spring_boot_starter.adoc
- documentation/src/main/asciidoc/user_guide/integrations_spring.adoc
Relates to https://github.com/infinispan/infinispan/pull/6565
> [9.4.x] ISPN-9799 changes for spring dependencies in 9.4.x

- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb2_bom.adoc
- documentation/src/main/asciidoc/topics/productized/spring_boot_starter.adoc
@karesti sorry for this but I need to update the BOM as well
> ISPN-9799 9.4.x Spring Boot dependencies

- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_actuator.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_bom.adoc
- documentation/src/main/asciidoc/topics/productized/spring_boot_starter.adoc
@karesti docs for Spring Boot actuator with 10
> ISPN-9799 spring boot actuator

- core/src/main/java/org/infinispan/globalstate/ConfigurationStorage.java
- core/src/main/java/org/infinispan/globalstate/package-info.java
https://issues.jboss.org/browse/ISPN-9823
> [9.4] ISPN-9823 Include JavaDocs for org.infinispan.globalstate

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/marshall/BytesOnlyJBossLikeMarshaller.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/marshall/BytesOnlyMarshaller.java
- commons/src/main/java/org/infinispan/commons/util/Util.java
marshalling
https://issues.jboss.org/browse/ISPN-9832
> ISPN-9832 Allow default client marshaller to not require jboss

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
https://issues.jboss.org/browse/ISPN-9840
> ISPN-9840 RemoteCacheManager shouldn't attempt to start a second time

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/TransactionConfigurationBuilder.java
ConsistentHash classes when not needed.
https://issues.jboss.org/browse/ISPN-9842
> ISPN-9842 Hotrod ConfigurationBuilder#withProperties loads

- cdi/common/src/main/java/org/infinispan/cdi/common/util/Reflections.java
- cdi/common/src/main/java/org/infinispan/cdi/common/util/SetAccessiblePrivilegedAction.java
- core/src/main/java/org/infinispan/factories/components/ComponentMetadataRepo.java
- core/src/main/java/org/infinispan/factories/components/SecurityActions.java
Jira
https://issues.jboss.org/browse/ISPN-9822
Also should be merged to master.
> [9.4]  ISPN-9822 BasicComponentRegistryImpl fails with security manager

- integrationtests/spring-boot2-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/AbstractSpringSessionTCK.java
- integrationtests/spring-boot2-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/configuration/InfinispanSessionListener.java
- integrationtests/spring-boot2-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/configuration/WebConfig.java
- integrationtests/spring-boot2-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/remote/RemoteConfiguration.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ClientListenerRegistry.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/KeyValueVersionConverter.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/KeyValueVersionConverterFactory.java
- spring/spring4/spring4-embedded/src/main/java/org/infinispan/spring/session/EmbeddedApplicationPublishedBridge.java
- spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanApplicationPublishedBridgeTCK.java
- spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/util/EventsWaiter.java
- spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/session/EmbeddedApplicationPublishedBridge.java
- spring/spring5/spring5-remote/pom.xml
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepository.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/session/RemoteApplicationPublishedBridge.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/session/configuration/EnableInfinispanRemoteHttpSession.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/session/configuration/InfinispanRemoteHttpSessionConfiguration.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepositoryTest.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/session/RemoteApplicationPublishedBridgeTest.java
https://issues.jboss.org/browse/ISPN-9819
> [9.4.x] ISPN-9819 Listeners correction in spring session

- documentation/README.md
- documentation/src/main/asciidoc/contributing/docs.adoc
https://issues.jboss.org/browse/ISPN-9829
> ISPN-9829 doc guidelines

- integrationtests/security-it/pom.xml
- integrationtests/security-it/server-provisioning.xml
- integrationtests/security-it/src/test/resources/arquillian.xml
- integrationtests/wildfly-modules/pom.xml
- integrationtests/wildfly-modules/server-provisioning.xml
- integrationtests/wildfly-modules/src/test/resources/arquillian.xml
- jcache/tck-runner/pom.xml
- pom.xml
- server/integration/src/main/ant/infinispan-server.xml
https://issues.jboss.org/browse/ISPN-9854
> ISPN-9854 Fix various app-server integration tests

- integrationtests/security-it/pom.xml
- integrationtests/security-it/server-provisioning.xml
- integrationtests/security-it/src/test/resources/arquillian.xml
- integrationtests/wildfly-modules/pom.xml
- integrationtests/wildfly-modules/server-provisioning.xml
- integrationtests/wildfly-modules/src/test/resources/arquillian.xml
- jcache/tck-runner/pom.xml
- pom.xml
- server/integration/src/main/ant/infinispan-server.xml
https://issues.jboss.org/browse/ISPN-9854
> [9.4] ISPN-9854 Fix various app-server integration tests

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/RemoteContinuousQueryLeavingRemoteCacheManagerTest.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ClientListenerRegistry.java
* Remove client listener when channel disconnects on different thread
https://issues.jboss.org/browse/ISPN-9867
> ISPN-9867 Client listeners are removed when a notification occurs

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9870
> [9.4] ISPN-9870 Upgrade RxJava2 to 2.2.4

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9870
> ISPN-9870 Upgrade RxJava2 to 2.2.4

- core/src/main/java/org/infinispan/transaction/impl/AbstractEnlistmentAdapter.java
- core/src/test/java/org/infinispan/lock/singlelock/AbstractInitiatorCrashTest.java
- core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
https://issues.jboss.org/browse/ISPN-9701
> [8.2.x] ISPN-9701 TransactionTable does not shutdown gracefully

- lock/src/main/java/org/infinispan/lock/impl/lock/ClusteredLockImpl.java
- lock/src/main/java/org/infinispan/lock/impl/lock/RequestExpirationScheduler.java
- lock/src/main/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManager.java
- lock/src/test/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManagerTest.java
This is causing a memory leak! 
https://issues.jboss.org/browse/ISPN-9873
> ISPN-9873 Remove listeners when lock is removed

- lock/src/main/java/org/infinispan/lock/impl/lock/ClusteredLockImpl.java
- lock/src/main/java/org/infinispan/lock/impl/lock/RequestExpirationScheduler.java
- lock/src/main/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManager.java
- lock/src/test/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManagerTest.java
Backport https://issues.jboss.org/browse/ISPN-9873
> [9.4.x] ISPN-9873 Remove listeners when lock is removed

- Jenkinsfile
https://issues.jboss.org/browse/ISPN-9703
> ISPN-9703 CI should test that distribution builds work on non PRs

- documentation/src/main/asciidoc/user_guide/rolling_upgrades.adoc
Backport into 9.4.x https://issues.jboss.org/browse/ISPN-9851
> [9.4.x] ISPN-9851 Rolling Upgrade Procedures

- documentation/src/main/asciidoc/user_guide/persistence_storemigrator.adoc
https://issues.jboss.org/browse/ISPN-9892
> ISPN-9892 edits to store migrator docs

- persistence/jpa/src/test/java/org/infinispan/persistence/jpa/AbstractJpaStoreTest.java
https://issues.jboss.org/browse/ISPN-9881
> ISPN-9881 Jpa store tests fail with hibernate 5.1

- persistence/jpa/src/test/java/org/infinispan/persistence/jpa/AbstractJpaStoreTest.java
https://issues.jboss.org/browse/ISPN-9881
> [9.4.x] ISPN-9881 Jpa store tests fail with hibernate 5.1

- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/SecurityActions.java
https://issues.jboss.org/browse/ISPN-7333
> ISPN-7333 Unwrap protobuf cache security for internal uses

- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/SecurityActions.java
https://issues.jboss.org/browse/ISPN-7333
> [9.4] ISPN-7333 Unwrap protobuf cache security for internal uses

- documentation/src/main/asciidoc/server_guide/configuration.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod_transaction.adoc
https://issues.jboss.org/browse/ISPN-9880
> ISPN-9880 HR TX Docs

- documentation/src/main/asciidoc/topics/configuration/clustered_lock_manager.adoc
- documentation/src/main/asciidoc/user_guide/clustered_lock.adoc
Needs backport to 9.4.x
https://issues.jboss.org/browse/ISPN-9903
> ISPN-9903 clustered lock mgr doc edits

- documentation/src/main/asciidoc/server_guide/configuration.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod_transaction.adoc
note about custom tx mgr
Backport for https://issues.jboss.org/browse/ISPN-9880
> [9.4.x] ISPN-9880 hr tx docs

- core/src/test/java/org/infinispan/test/SingleCacheManagerTest.java
https://issues.jboss.org/browse/ISPN-9896
> [9.4.x] ISPN-9896 TypeNotPresentExceptionProxy when using reflection

- core/src/test/java/org/infinispan/test/SingleCacheManagerTest.java
https://issues.jboss.org/browse/ISPN-9896
> ISPN-9896 TypeNotPresentExceptionProxy when using reflection

- documentation/src/main/asciidoc/server_guide/configuration.adoc
Update documentation/src/main/asciidoc/server_guide/configuration.adoc
Co-Authored-By: oraNod <dnaro@redhat.com>
> [9.4.x] ISPN-9888 Default JGroups Settings

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9911
> [9.4] ISPN-9911 Fix JMX javadoc generation

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9911
> ISPN-9911 Fix JMX javadoc generation

- counter/pom.xml
- lock/pom.xml
- multimap/pom.xml
https://issues.jboss.org/browse/ISPN-9657
Backport https://github.com/infinispan/infinispan/pull/6638
> ISPN-9657 multimap, lock and counter OSGI manifest

- counter/pom.xml
- lock/pom.xml
- multimap/pom.xml
https://issues.jboss.org/browse/ISPN-9657
upstream https://github.com/infinispan/infinispan/pull/6637
> [9.4.x] ISPN-9657 multimap, lock and counter OSGI manifest

- core/src/main/java/org/infinispan/configuration/global/GlobalConfiguration.java
- core/src/main/java/org/infinispan/configuration/global/GlobalConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/Attribute.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java
- core/src/main/resources/schema/infinispan-config-10.0.xsd
- core/src/test/java/org/infinispan/distribution/ZeroCapacityNodeTest.java
- core/src/test/java/org/infinispan/functional/FunctionalTestUtils.java
- core/src/test/resources/configs/unified/10.0.xml
- core/src/test/resources/infinispan-features.properties
- counter/src/test/java/org/infinispan/counter/StrongCounterWithZeroCapacityNodesTest.java
- counter/src/test/java/org/infinispan/counter/WeakCounterWithZeroCapacityNodesTest.java
- documentation/src/main/asciidoc/user_guide/clustering.adoc
- lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java
- lock/src/main/java/org/infinispan/lock/logging/Log.java
- lock/src/test/java/org/infinispan/lock/ClusteredLockTest.java
- lock/src/test/java/org/infinispan/lock/ClusteredLockWithZeroCapacityIncorrectConfigTest.java
- lock/src/test/java/org/infinispan/lock/ClusteredLockWithZeroCapacityNodesTest.java
- server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java
https://issues.jboss.org/browse/ISPN-9699
depends on https://github.com/infinispan/infinispan/pull/6546
Backport to 9.4.x: https://github.com/infinispan/infinispan/pull/6633
> ISPN-9699 0.0.f Global Capacity Factor

- core/src/main/java/org/infinispan/configuration/global/GlobalConfiguration.java
- core/src/main/java/org/infinispan/configuration/global/GlobalConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/Attribute.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java
- core/src/main/resources/schema/infinispan-config-9.4.xsd
- core/src/test/java/org/infinispan/distribution/ZeroCapacityNodeTest.java
- core/src/test/java/org/infinispan/functional/FunctionalTestUtils.java
- core/src/test/resources/configs/unified/9.4.xml
- core/src/test/resources/infinispan-features.properties
- counter/src/test/java/org/infinispan/counter/StrongCounterWithZeroCapacityNodesTest.java
- counter/src/test/java/org/infinispan/counter/WeakCounterWithZeroCapacityNodesTest.java
- documentation/src/main/asciidoc/user_guide/clustering.adoc
- lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java
- lock/src/main/java/org/infinispan/lock/logging/Log.java
- lock/src/test/java/org/infinispan/lock/ClusteredLockTest.java
- lock/src/test/java/org/infinispan/lock/ClusteredLockWithZeroCapacityIncorrectConfigTest.java
- lock/src/test/java/org/infinispan/lock/ClusteredLockWithZeroCapacityNodesTest.java
- server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java
https://issues.jboss.org/browse/ISPN-9699
Upstream PR : https://github.com/infinispan/infinispan/pull/6440
> [9.4.x] ISPN-9699 0.0.f Global Capacity Factor

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
https://issues.jboss.org/browse/ISPN-9915
https://issues.jboss.org/browse/ISPN-9916
> JDBC Flowable fixes

- documentation/src/main/asciidoc/user_guide/transactions.adoc
https://issues.jboss.org/browse/ISPN-9885
> ISPN-9885 Write Skew Minor Doc Fix

- core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
The return slipped to the wrong line.
> ISPN-9801 Fix spurious startup warning

- documentation/src/main/asciidoc/user_guide/integrations_spring.adoc
@karesti could you please review?
> ISPN-9937 removing broken javadoc links

- build-configuration/pom.xml
- server/integration/feature-pack/build.xml
https://issues.jboss.org/browse/ISPN-9930
> ISPN-9930 Allow the CLI shell script to be branded

- Jenkinsfile-release
Should allow to specify a new version and this should be changed and commit to the branch
> [9.4] Should support the nextVersion feature in release

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
https://issues.jboss.org/browse/ISPN-9915
https://issues.jboss.org/browse/ISPN-9916
> [9.4.x] JDBC Flowable fixes

- pom.xml
https://issues.jboss.org/browse/ISPN-9953
> ISPN-9953 Fix jaxb-runtime version property

- documentation/src/main/asciidoc/user_guide/integrations_spring.adoc
@karesti here's the backport for 9.4. thank you.
> [9.4.x] ISPN-9937 removing broken javadoc links

- build-configuration/pom.xml
- server/integration/feature-pack/build.xml
https://issues.jboss.org/browse/ISPN-9930
> [9.4] ISPN-9930 Allow the CLI shell script to be branded

- server/integration/testsuite/pom.xml
https://issues.jboss.org/browse/ISPN-9954
> ISPN-9954 Missing dependency on server/integration/testsuite

- server/integration/testsuite/pom.xml
https://issues.jboss.org/browse/JDG-2555
> JDG-2555 Missing dependency on server/integration/testsuite

- documentation/src/main/asciidoc/user_guide/cli.adoc
- documentation/src/main/asciidoc/user_guide/integrations.adoc
- documentation/src/main/asciidoc/user_guide/integrations_hibernate_cache.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_rest.adoc
- documentation/src/main/asciidoc/user_guide/streams.adoc
https://issues.jboss.org/browse/ISPN-9939
> ISPN-9939 brandname variable is not replaced in code blocks

- documentation/src/main/asciidoc/user_guide/cli.adoc
- documentation/src/main/asciidoc/user_guide/distributed_executor.adoc
- documentation/src/main/asciidoc/user_guide/integrations.adoc
- documentation/src/main/asciidoc/user_guide/integrations_hibernate_cache.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_rest.adoc
- documentation/src/main/asciidoc/user_guide/streams.adoc
Backport for https://issues.jboss.org/browse/ISPN-9939
> [9.4.x] ISPN-9939 brandname variable is not replaced in code blocks

- all/remote/pom.xml
- server/integration/testsuite/pom.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/osgi/RemoteCacheOsgiIT.java
https://issues.jboss.org/browse/ISPN-9968
https://issues.jboss.org/browse/ISPN-9954
> JCacheStateAwarenessIT Fix

- all/remote/pom.xml
- server/integration/testsuite/pom.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/osgi/RemoteCacheOsgiIT.java
https://issues.jboss.org/browse/ISPN-9968
https://issues.jboss.org/browse/ISPN-9954
> [9.4.x] JCacheStateAwarenessIT Fix

- Jenkinsfile
- checkstyle/pom.xml
https://issues.jboss.org/browse/ISPN-9835
* Use `mvn deploy` instead of `mvn deploy:deploy`
* Perform cleanup only after deploy
* Use the new `fixed` post condition to send emails
(`unsuccessful` is not yet available)
> ISPN-9835 Jenkinsfile snapshot deployment fails

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9887
> ISPN-9887 Upgrade to JGroups 4.0.17.Final

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9887
Backport of https://github.com/infinispan/infinispan/pull/6682
> [9.4] ISPN-9887 Upgrade to JGroups 4.0.17.Final

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/StatisticsConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
https://issues.jboss.org/browse/ISPN-9969
upstream https://github.com/infinispan/infinispan/pull/6683
> [9.4] ISPN-9969 Configure statistics with the hotrod-client.properties

- javadoc/javadoc-all/pom.xml
- javadoc/javadoc-embedded/pom.xml
- pom.xml
it is only for 9.4.x
https://issues.jboss.org/browse/ISPN-9972
> [9.4.x] ISPN-9972 Fail to compile with distribution profile

- pom.xml
https://issues.jboss.org/browse/ISPN-9974
> Upgrade maven-assembly-plugin to 3.1.1 to reduce memory usage

- server/core/src/main/java/org/infinispan/server/core/utils/SecurityActions.java
- server/core/src/main/java/org/infinispan/server/core/utils/SslUtils.java
https://issues.jboss.org/browse/ISPN-9971
> ISPN-9971 Use the JDK ALPN support when Java > 9

- documentation/pom.xml
https://issues.jboss.org/browse/ISPN-9975
> ISPN-9975 Upgrade to asciidoctorj 1.6.2

- documentation/pom.xml
https://issues.jboss.org/browse/ISPN-9975
> [9.4] ISPN-9975 Upgrade to asciidoctorj 1.6.2

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9980
Backport https://github.com/infinispan/infinispan/pull/6698
> ISPN-9980 Upgrades spring dependencies

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9985
> ISPN-9985 JGroups 4.0.18

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9985
> [9.4] ISPN-9985 JGroups 4.0.18

- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_bom.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_embedded.adoc
- documentation/src/main/asciidoc/topics/dependencies/sb_remote.adoc
- documentation/src/main/asciidoc/topics/productized/spring_boot_starter.adoc
https://issues.jboss.org/browse/ISPN-9989
> ISPN-9989 improve user experience with Spring Boot docs

- lock/src/main/resources/schema/infinispan-clustered-locks-config-10.0.xsd
- lock/src/main/resources/schema/infinispan-clustered-locks-config-9.4.xsd
https://issues.jboss.org/browse/ISPN-10003
backport #6720
> ISPN-10003 Default value is CONSISTENT

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/CustomMarshallerEventIT.java
- core/src/test/java/org/infinispan/configuration/JsonSerializationTest.java
- core/src/test/java/org/infinispan/functional/AbstractFunctionalTest.java
- core/src/test/java/org/infinispan/functional/FunctionalMapTest.java
- core/src/test/java/org/infinispan/scattered/statetransfer/CoordinatorStopTest.java
- core/src/test/java/org/infinispan/statetransfer/StateTransferTimestampsTest.java
- core/src/test/java/org/infinispan/test/fwk/NamedTestMethod.java
- jcache/embedded/src/test/java/org/infinispan/jcache/LimitExpiryFactoryTest.java
- pom.xml
- server/core/src/test/java/org/infinispan/server/core/dataconversion/XMLTranscoderTest.java
- server/rest/src/test/java/org/infinispan/rest/framework/impl/ResourceManagerImplTest.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManagerFactoryBeanContextTest.java
https://issues.jboss.org/browse/ISPN-9373 Bump testng
> ISPN-9373 Upgrade testng to 6.14.3

- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
- server/integration/infinispan/src/test/java/org/jboss/as/clustering/infinispan/subsystem/CacheConfigurationTestCase.java
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/cache-configuration-test.xml
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_0.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_1.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_2.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_3.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_4.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_5.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_0.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_1.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_2.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_3.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_4.properties
https://issues.jboss.org/browse/ISPN-9957
> [9.4] Server Configuration Fix

- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
- server/integration/infinispan/src/test/java/org/jboss/as/clustering/infinispan/subsystem/CacheConfigurationTestCase.java
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/cache-configuration-test.xml
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_10_0.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_0.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_1.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_2.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_3.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_4.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_8_5.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_0.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_1.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_2.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_3.properties
- server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_4.properties
https://issues.jboss.org/browse/ISPN-9957
> Server configuration fix

- server/integration/build/trim-delete.txt
- server/integration/feature-pack/src/main/resources/content/bin/ispn-cli-logging.properties
- server/integration/feature-pack/src/main/resources/content/bin/ispn-cli.bat
- server/integration/feature-pack/src/main/resources/content/bin/ispn-cli.sh
https://issues.jboss.org/browse/ISPN-9998
> ISPN-9998 Fix server CLI with Java 11

- server/integration/build/trim-delete.txt
- server/integration/feature-pack/src/main/resources/content/bin/ispn-cli-logging.properties
- server/integration/feature-pack/src/main/resources/content/bin/ispn-cli.bat
- server/integration/feature-pack/src/main/resources/content/bin/ispn-cli.sh
https://issues.jboss.org/browse/ISPN-9998
> [9.4] ISPN-9998 Fix server CLI with Java 11

- tasks/scripting/src/test/java/org/infinispan/scripting/ScriptingTest.java
https://issues.jboss.org/browse/ISPN-10008
> ISPN-10008 ScriptingTest.testNonSupportedScript fix

- integrationtests/all-remote-it/src/test/java/org/infinispan/all/remote/RemoteAllTestIT.java
- integrationtests/pom.xml
https://issues.jboss.org/browse/ISPN-9990
https://issues.jboss.org/browse/ISPN-9991
> Integration tests fixes

- documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
Needs backport to 9.4.x
https://issues.jboss.org/browse/ISPN-10017
> ISPN-10017 edits to bringing sites back online and state transfer

- core/src/test/java/org/infinispan/eviction/impl/DeadlockClusteredCachesTest.java
To test you should run ` mvn verify -Dtest=DeadlockClusteredCachesTest -Ptest-stress`
> ISPN-9982 - Possible deadlock for clustered caches with Expiration

- feature-pack/embedded-query/src/main/resources/modules/org/infinispan/lucene-directory/slot/module.xml
https://issues.jboss.org/browse/ISPN-10007
> [9.4] ISPN-10007 Lucene directory module missing reactive-stream dependencies

- documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
Backport for https://issues.jboss.org/browse/ISPN-10017
> [9.4.x] ISPN-10017 edits to bringing sites back online and state transfer

- feature-pack/embedded-query/src/main/resources/modules/org/infinispan/lucene-directory/slot/module.xml
https://issues.jboss.org/browse/ISPN-10007
> ISPN-10007 Lucene directory module missing reactive-stream dependencies

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/CustomMarshallerEventIT.java
- core/src/test/java/org/infinispan/functional/AbstractFunctionalTest.java
- core/src/test/java/org/infinispan/functional/FunctionalMapTest.java
- core/src/test/java/org/infinispan/persistence/PassivatePersistentTest.java
- core/src/test/java/org/infinispan/scattered/statetransfer/CoordinatorStopTest.java
- core/src/test/java/org/infinispan/statetransfer/StateTransferTimestampsTest.java
- core/src/test/java/org/infinispan/test/fwk/NamedTestMethod.java
- pom.xml
- server/core/src/test/java/org/infinispan/server/core/dataconversion/XMLTranscoderTest.java
- spring/spring4/spring4-remote/src/test/java/org/infinispan/spring/provider/SpringRemoteCacheManagerFactoryBeanContextTest.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManagerFactoryBeanContextTest.java
https://issues.jboss.org/browse/ISPN-9373
> [9.4] ISPN-9373 Upgrade testng to 6.14.3

- core/src/main/java/org/infinispan/interceptors/impl/TxBatchUpdater.java
- core/src/test/java/org/infinispan/interceptors/impl/CacheWriterTxModificationsTest.java
https://issues.jboss.org/browse/ISPN-10022
> ISPN-10022 Tx compute command updates are not written to stores

- query/src/main/java/org/infinispan/query/impl/DefaultSearchMappingProvider.java
* add a new analyzer called "filename" in DefaultSearchMappingProvider
https://issues.jboss.org/browse/ISPN-10016
> ISPN-10016 Provide a default Lucene analyzer for file names

- query/src/main/java/org/infinispan/query/impl/DefaultSearchMappingProvider.java
* add a new analyzer called "filename" in DefaultSearchMappingProvider
https://issues.jboss.org/browse/ISPN-10016
> [9.4.x] ISPN-10016 Provide a default Lucene analyzer for file names

- documentation/src/main/asciidoc/user_guide/streams.adoc
https://issues.jboss.org/browse/ISPN-9712
> ISPN-9712 note about REPL optimization for write-behind

- documentation/src/main/asciidoc/user_guide/streams.adoc
> [9.4.x] ISPN-9712 note about REPL optimization for write-behind

- documentation/src/main/asciidoc/user_guide/transactions.adoc
Backporting ISPN-9560
https://issues.jboss.org/browse/ISPN-9560
> [9.4.x] ISPN-9560 removing deadlock detection from docs because it is deprecated

- core/src/main/java/org/infinispan/interceptors/impl/TxBatchUpdater.java
- core/src/test/java/org/infinispan/interceptors/impl/CacheWriterTxModificationsTest.java
https://issues.jboss.org/browse/ISPN-10022
Backport of https://github.com/infinispan/infinispan/pull/6746
> [9.4.x] ISPN-10022 Tx compute command updates are not written to stores

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/RemoteContinuousQueryLeavingRemoteCacheManagerTest.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ClientListenerRegistry.java
* Remove client listener when channel disconnects on different thread
https://issues.jboss.org/browse/ISPN-9867
> [9.4.x] ISPN-9867 Client listeners are removed when a notification occurs

- core/pom.xml
https://issues.jboss.org/browse/ISPN-10043
Backport of #6758
> ISPN-10043 Add explicit dependency on surefire-testng

- integrationtests/all-remote-it/src/test/java/org/infinispan/all/remote/RemoteAllTestIT.java
- integrationtests/pom.xml
https://issues.jboss.org/browse/ISPN-9990
> [9.4] Integration Test fixes

- server/integration/feature-pack/src/main/resources/content/bin/prometheus.sh
https://issues.jboss.org/browse/ISPN-10046-9.4
> [9.4] ISPN-10046 Server standalone.sh --jmx fails with Java 11

- commons-test/src/main/java/org/infinispan/commons/test/RunningTestsRegistry.java
- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
https://issues.jboss.org/browse/ISPN-10024
* Add alternative location for jstack
* Add custom thread dump for JDKs without jstack
> ISPN-10024 Long test killer doesn't work on Java 11

- pom.xml
https://issues.jboss.org/browse/ISPN-10035
> ISPN-10035 Upgrade to Javassist 3.24.1-GA

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/AbstractTransactionTable.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/SyncModeTransactionTable.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/TransactionContext.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/TransactionOperationFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/TransactionTable.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/TransactionalRemoteCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/XaModeTransactionTable.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/operations/CompleteTransactionOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/operations/ForgetTransactionOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/operations/PrepareTransactionOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/operations/RecoveryOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tx/RecoveryTest.java
https://issues.jboss.org/browse/ISPN-9463
> ISPN-9463 Provide API to enlist the resource with TransactionManager

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-9980
Upstream https://github.com/infinispan/infinispan/pull/6697
> [9.4] ISPN-9980 Upgrade Spring 5 dependencies

- core/src/test/java/org/infinispan/eviction/impl/ExceptionEvictionTest.java
* Change assertion to eventually to catch issue of async tx notification
https://issues.jboss.org/browse/ISPN-9191
> ISPN-9191 ExceptionEvictionTest random failure during clearContent

- cdi/remote/src/test/java/org/infinispan/cdi/embedded/test/cachemanager/remote/DefaultCacheManagerOverrideTest.java
- cdi/remote/src/test/java/org/infinispan/cdi/embedded/test/cachemanager/remote/DefaultCacheManagerTest.java
- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
- core/src/test/java/org/infinispan/test/fwk/TestResourceTrackingListener.java
- jcache/embedded/src/test/java/org/infinispan/jcache/JCacheConfigurationTest.java
- lucene/directory-provider/src/test/java/org/infinispan/hibernate/search/AsyncMetadataConfigurationTest.java
- query/src/test/java/org/infinispan/query/distributed/MassIndexerAsyncBackendTest.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/jcache/JCacheStateAwarenessIT.java
Discovered some more issues while rebasing the 9.4.x backport (#6734)
> ISPN-9863 more jcache fixes

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/StatisticsConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-10056
> ISPN-10056 Client statistics javadoc

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/StatisticsConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-10056
> [9.4] ISPN-10056 Client statistics javadoc

- server/integration/jgroups/src/main/resources/subsystem-templates/cloud-jgroups.xml
same as https://github.com/infinispan/infinispan/pull/6749
but for 10.x
> ISPN-10005 stack for dns ping on okd (10.x)

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
- server/core/src/main/java/org/infinispan/server/core/logging/Log.java
https://issues.jboss.org/browse/ISPN-10060
> ISPN-10060 Log netty transport epoll/nio messages as INFO

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
- server/core/src/main/java/org/infinispan/server/core/logging/Log.java
https://issues.jboss.org/browse/ISPN-10060
> [9.4] ISPN-10060 Log netty transport epoll/nio messages as INFO

- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
- core/src/test/java/org/infinispan/reactive/publisher/impl/RehashClusterPublisherManagerTest.java
https://issues.jboss.org/browse/ISPN-10058
https://issues.jboss.org/browse/ISPN-10061
> ISPN-10058 RehashClusterPublisherManagerTest OOME on IBM JDK

- pom.xml
https://issues.jboss.org/browse/ISPN-10055
> ISPN-10055 Checkstyle 8.18

- pom.xml
https://issues.jboss.org/browse/ISPN-10055
> [9.4] ISPN-10055 Checkstyle 8.18

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/DB2TableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/GenericTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/H2TableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/MySQLTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/OracleTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/PostgresTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/SQLServerTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/SQLiteTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/SybaseTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/TableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/TableManagerFactory.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/TableManagerTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/TableNameUniquenessTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stores/TxStoreTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStoreTest.java
- tools/src/main/java/org/infinispan/tools/store/migrator/jdbc/JdbcStoreReader.java
@ryanemerson I have a few questions:
1) Should `JdbcStringBasedStore` have final fields?
2) WDYT about the change in the method `testTableQuoting`?
3) There are two unused fields `selectMultipleRowSql` and `deleteAllRows`
> ISPN-9306 - Unguarded lazy initialization of SQL statements in JDBCacheStore

- core/src/test/java/org/infinispan/functional/distribution/rehash/FunctionalTxTest.java
- core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
- integrationtests/osgi/pom.xml
- integrationtests/wildfly-modules/pom.xml
- pom.xml
- server/integration/testsuite/README.txt
- server/integration/testsuite/pom.xml
Default transport for the test suite should be the same except if it was activated by another profile
> ISPN-9748 Default transport for the test suite should be same

- commons-test/src/main/java/org/infinispan/commons/test/RunningTestsRegistry.java
- commons-test/src/main/java/org/infinispan/commons/test/TestNGTestListener.java
- core/src/main/java/org/infinispan/container/impl/DefaultDataContainer.java
- core/src/main/java/org/infinispan/container/impl/InternalDataContainerAdapter.java
- core/src/main/java/org/infinispan/container/offheap/BoundedOffHeapDataContainer.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapDataContainer.java
- core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
- core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
- core/src/test/java/org/infinispan/container/impl/DefaultSegmentedDataContainerTest.java
- core/src/test/java/org/infinispan/container/offheap/OffHeapMultiNodeTest.java
- core/src/test/java/org/infinispan/distribution/BaseDistStoreTest.java
- core/src/test/java/org/infinispan/factories/DataContainerFactoryTest.java
- core/src/test/java/org/infinispan/persistence/CacheLoaderFunctionalTest.java
https://issues.jboss.org/browse/ISPN-10059
Backport of #6779
> [9.4.x] ISPN-10059 Off-heap clustered cache cannot start with segmentation disabled

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ClientSocketReadTimeoutTest.java
https://issues.jboss.org/browse/ISPN-10077
> ISPN-10077 Fix ClientSocketReadTimeoutTest.testPutTimeout

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ClientSocketReadTimeoutTest.java
https://issues.jboss.org/browse/ISPN-10077
> [9.4] ISPN-10077 Fix ClientSocketReadTimeoutTest.testPutTimeout

- feature-pack/commons/src/main/resources/modules/com/github/ben-manes/caffeine/slot/module.xml
https://issues.jboss.org/browse/ISPN-10082
> ISPN-10082 Caffeine module missing unsafe dependency

- feature-pack/commons/src/main/resources/modules/com/github/ben-manes/caffeine/slot/module.xml
https://issues.jboss.org/browse/ISPN-10082
> [9.4] ISPN-10082 Caffeine module missing unsafe dependency

- commons-test/src/main/java/org/infinispan/commons/test/JUnitTestListener.java
- commons-test/src/main/java/org/infinispan/commons/test/RunningTestsRegistry.java
- commons-test/src/main/java/org/infinispan/commons/test/TestNGSuiteChecksTest.java
- commons-test/src/main/java/org/infinispan/commons/test/TestNGTestListener.java
- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
- core/pom.xml
- core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java
- core/src/test/java/org/infinispan/test/fwk/TestResourceTrackingListener.java
- documentation/src/main/asciidoc/contributing/tests.adoc
- spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/InfinispanTestExecutionListener.java
Backport of https://github.com/infinispan/infinispan/pull/6812
> [9.4.x]  ISPN-10090 Allow running TestNG tests without TestNGTestListener

- pom.xml
https://issues.jboss.org/browse/ISPN-10079
> ISPN-10079 Upgrade to jboss-modules 1.8.7.Final

- pom.xml
https://issues.jboss.org/browse/ISPN-10079
Backport of #6792
> [9.4.x] ISPN-10079 Upgrade to jboss-modules 1.8.7.Final

- build-configuration/pom.xml
- feature-pack/build.xml
- feature-pack/wf-modules/pom.xml
- feature-pack/wf-modules/src/main/resources/modules/org/hibernate/commons-annotations/slot/module.xml
- feature-pack/wf-modules/src/main/resources/modules/org/hibernate/search/engine/hibernate-search-slot/module.xml
- feature-pack/wf-modules/src/main/resources/modules/system/layers/base/org/hibernate/search/engine/hibernate-slot/module.xml
- server/integration/feature-pack/build.xml
https://issues.jboss.org/browse/ISPN-10101
https://issues.jboss.org/browse/ISPN-10105
> [9.4]  Module fixes

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/AuthHandler.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/Authentication.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseDecoder.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
https://issues.jboss.org/browse/ISPN-9841
> [9.4] ISPN-9841 Non-blocking Hot Rod authentication

- documentation/src/main/asciidoc/user_guide/integrations_spring.adoc
https://issues.jboss.org/browse/ISPN-10111
Needs backport into 9.4.x.
> ISPN-10111 duplicate mbean registration

- core/src/test/java/org/infinispan/scattered/statetransfer/CoordinatorStopTest.java
https://issues.jboss.org/browse/ISPN-9940
> ISPN-9440 CoordinatorStopTest move to unstable group

- documentation/src/main/asciidoc/user_guide/query.adoc
https://issues.jboss.org/browse/ISPN-10083
> ISPN-10083 filename tokenizer

- maven-settings.xml
https://issues.jboss.org/browse/ISPN-10109
> ISPN-10109 Use https urls in maven settings

- maven-settings.xml
https://issues.jboss.org/browse/ISPN-10109
> [9.4] ISPN-10109 Use https urls in maven settings

- core/src/test/java/org/infinispan/statetransfer/JoinInNewThreadTest.java
- core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
https://issues.jboss.org/browse/ISPN-10080
> ISPN-10080 Test cache managers created in other threads cannot join the cluster with UDP

- core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/test/java/org/infinispan/commands/module/TestGlobalConfiguration.java
- core/src/test/java/org/infinispan/commands/module/TestGlobalConfigurationBuilder.java
- core/src/test/java/org/infinispan/commands/module/TestGlobalConfigurationSerializer.java
- core/src/test/java/org/infinispan/commands/module/TestModuleCommandExtensions.java
- core/src/test/java/org/infinispan/commands/module/TestModuleLifecycle.java
- core/src/test/java/org/infinispan/configuration/serializer/ConfigurationSerializerTest.java
- core/src/test/java/org/infinispan/manager/CacheManagerTest.java
- core/src/test/resources/META-INF/services/org.infinispan.commands.module.ModuleCommandExtensions
https://issues.jboss.org/browse/ISPN-10070
> ISPN-10070 DefaultCacheManager should stop components after start failure

- core/src/main/java/org/infinispan/container/offheap/OffHeapMemory.java
https://issues.jboss.org/browse/ISPN-10102
> ISPN-10102 Bound checks with byte should be 1

- documentation/src/main/asciidoc/user_guide/query.adoc
https://issues.jboss.org/browse/ISPN-10083
Also backporting changes from ISPN-9647. These were not backported.
> [9.4.x] Default analyzer docs

- core/src/main/java/org/infinispan/configuration/cache/AbstractStoreConfigurationBuilder.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/persistence/LocalConditionalCommandTest.java
- core/src/test/java/org/infinispan/persistence/StoreConfigurationValidationTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/configuration/XmlFileParsingTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stores/TxStoreTest.java
https://issues.jboss.org/browse/ISPN-10095
> ISPN-10095 Shared stores should throw exception when cache is local

- documentation/src/main/asciidoc/user_guide/integrations_spring.adoc
https://issues.jboss.org/browse/ISPN-10111
> ISPN-10111: removing SB issue about duplicate MBean registration

- documentation/src/main/asciidoc/server_guide/management.adoc
- documentation/src/main/asciidoc/server_guide/topics.adoc
- documentation/src/main/asciidoc/user_guide/cloud.adoc
https://issues.jboss.org/browse/ISPN-10112
Needs backport into 9.4.x
> ISPN-10112 ispn-cli.sh for community only

- Jenkinsfile
- query/pom.xml
Query Project - Store the test results using TestNG
We will have:
- query / target / surefire-reports / testng-junit-results / TEST-org.infinispan.query.dsl.embedded.impl.xml
- query / target / surefire-reports / testng-native-results / TEST-infinispan-query.xml
> ISPN-10108 - Query Project - Store the test results using TestNG

- documentation/src/main/asciidoc/server_guide/management.adoc
- documentation/src/main/asciidoc/server_guide/topics.adoc
- documentation/src/main/asciidoc/user_guide/cloud.adoc
https://issues.jboss.org/browse/ISPN-10112
> [9.4.x] Backporting ISPN-10112 ispn-cli.sh for community only

- documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
https://issues.jboss.org/browse/ISPN-10131
> ISPN-10131 taking sites offline with SYNC only

- documentation/src/main/asciidoc/user_guide/cli.adoc
https://issues.jboss.org/browse/ISPN-10112 
Missed one reference to the script. Needs backport to 9.4.x.
> ISPN-10112 lurking reference to ispn-cli script

- documentation/src/main/asciidoc/user_guide/cli.adoc
https://issues.jboss.org/browse/ISPN-10112
> [9.4.x] ISPN-10112 lurking reference to ispn-cli script

- server/integration/feature-pack/src/main/resources/content/bin/standalone.bat
- server/integration/feature-pack/src/main/resources/content/bin/standalone.conf.bat
- server/integration/feature-pack/src/main/resources/content/bin/standalone.conf.ps1
- server/integration/feature-pack/src/main/resources/content/bin/standalone.ps1
https://issues.jboss.org/browse/ISPN-10133
> ISPN-10133 Update Windows scripts

- server/integration/feature-pack/src/main/resources/content/bin/standalone.bat
- server/integration/feature-pack/src/main/resources/content/bin/standalone.conf.bat
- server/integration/feature-pack/src/main/resources/content/bin/standalone.conf.ps1
- server/integration/feature-pack/src/main/resources/content/bin/standalone.ps1
https://issues.jboss.org/browse/ISPN-10133
> [9.4] ISPN-10133 Update Windows scripts

- core/src/main/java/org/infinispan/interceptors/impl/InvocationContextInterceptor.java
- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.jboss.org/browse/ISPN-10145
> ISPN-10145 Command execution error should log cache name

- core/src/main/java/org/infinispan/interceptors/impl/InvocationContextInterceptor.java
- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.jboss.org/browse/ISPN-10145
> [9.4.x] ISPN-10145 Command execution error should log cache name

- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
- integrationtests/pom.xml
- integrationtests/security-it/src/test/java/org/infinispan/test/integration/security/embedded/LdapAuthenticationIT.java
- integrationtests/wildfly-modules/pom.xml
- integrationtests/wildfly-modules/src/test/resources/as-config/standalone/configuration/standalone-test.xml
- jcache/tck-runner/pom.xml
- pom.xml
- server/integration/testsuite/pom.xml
https://issues.jboss.org/browse/ISPN-10142
https://issues.jboss.org/browse/ISPN-10144
https://issues.jboss.org/browse/ISPN-10106 (partial fix, do not close)
>  ISPN-10142 Wildfly modules integrationtests ignore branding

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/BaseCounter.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/CounterOperationFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/NotificationManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/RemoteCounterManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/StrongCounterImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/WeakCounterImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/AddListenerOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/AddOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/BaseCounterOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/CompareAndSwapOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/DefineCounterOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/GetConfigurationOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/GetCounterNamesOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/GetValueOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/IsDefinedOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/RemoveListenerOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/RemoveOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/ResetOperation.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/counter/StrongCounterHitsAwareTest.java
https://issues.jboss.org/browse/ISPN-10157
> ISPN-10157 Counter client does not use CH to locate a counter

- core/src/main/java/org/infinispan/Cache.java
- core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingCache.java
- core/src/test/java/org/infinispan/marshall/core/StoreAsBinaryTest.java
- core/src/test/java/org/infinispan/security/SecureCacheTestDriver.java
https://issues.jboss.org/browse/ISPN-10143
Backport https://github.com/infinispan/infinispan/pull/6860
> ISPN-10143 Fix StackOverflow exception with computeIfAbsent

- cli/cli-interpreter/src/main/java/org/infinispan/cli/interpreter/statement/StatsStatement.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/remoting/transport/AbstractDelegatingTransport.java
- core/src/main/java/org/infinispan/remoting/transport/Transport.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/test/java/org/infinispan/jmx/ClusteredCacheManagerMBeanTest.java
- core/src/test/java/org/infinispan/remoting/transport/MockTransport.java
https://issues.jboss.org/browse/ISPN-10081
> ISPN-10081 Get physical addresses of all members

- cli/cli-interpreter/src/main/antlr3/org/infinispan/cli/interpreter/IspnCliQL.g
- cli/cli-interpreter/src/test/java/org/infinispan/cli/interpreter/SiteStatementTest.java
https://issues.jboss.org/browse/ISPN-10127
> ISPN-10127 Unquote quoted site names in the CLI

- server/integration/testsuite/src/test/java/org/infinispan/server/test/security/rest/RESTCertSecurityIT.java
https://issues.jboss.org/browse/ISPN-10154
> ISPN-10154 Fix RESTCertSecurityIT.testInvalidCertificateAccess

- server/integration/testsuite/src/test/java/org/infinispan/server/test/security/rest/RESTCertSecurityIT.java
https://issues.jboss.org/browse/ISPN-10154
> [9.4] ISPN-10154 Fix RESTCertSecurityIT.testInvalidCertificateAccess

- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/AbstractQueryTest.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/IndexedEntityAutodetectTest.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/LocalCacheTest.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/QueryDslConditionsTest.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/QueryPhrasesTest.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/SimpleFacetingTest.java
- integrationtests/as-lucene-directory/src/test/java/org/infinispan/test/integration/as/testframework/H2DatabaseLifecycleManager.java
- integrationtests/security-it/src/test/java/org/infinispan/test/integration/security/embedded/KrbLdapAuthenticationIT.java
- integrationtests/security-it/src/test/java/org/infinispan/test/integration/security/embedded/LdapAuthenticationIT.java
- integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/embedded/EmbeddedSpringSessionTest.java
- integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/remote/RemoteSpringSessionTest.java
- jcache/tck-runner/pom.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/AbstractRemoteCacheManagerIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/HotRodCounterIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/HotRodMultimapIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/HotRodTransactionalCacheIT.java
https://issues.jboss.org/browse/ISPN-10106
> ISPN-10106 Fix/ignore JUnit modules thread leaks

- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/AbstractQueryTest.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/IndexedEntityAutodetectTest.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/LocalCacheTest.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/QueryDslConditionsTest.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/QueryPhrasesTest.java
- integrationtests/all-embedded-query-it/src/test/java/org/infinispan/all/embeddedquery/SimpleFacetingTest.java
- integrationtests/as-lucene-directory/src/test/java/org/infinispan/test/integration/as/testframework/H2DatabaseLifecycleManager.java
- integrationtests/security-it/src/test/java/org/infinispan/test/integration/security/embedded/KrbLdapAuthenticationIT.java
- integrationtests/security-it/src/test/java/org/infinispan/test/integration/security/embedded/LdapAuthenticationIT.java
- integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/embedded/EmbeddedSpringSessionTest.java
- integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/remote/RemoteSpringSessionTest.java
- jcache/tck-runner/pom.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/AbstractRemoteCacheManagerIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/HotRodCounterIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/HotRodMultimapIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/HotRodTransactionalCacheIT.java
https://issues.jboss.org/browse/ISPN-10106
> [9.4.x] ISPN-10106 Fix/ignore JUnit modules thread leaks

- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/productized/spring_boot_starter.adoc
https://issues.jboss.org/browse/ISPN-10134
> [9.4.x] ISPN-10134 SB dependencies

- server/integration/src/main/ant/infinispan-server.xml
- server/integration/testsuite/pom.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/rollingupgrades/HotRodRollingUpgradesDistIT.java
- server/integration/testsuite/src/test/resources/arquillian.xml
- server/integration/testsuite/src/test/resources/config/parts/rolling-upgrades-server-endpoint-9.4.xml
https://issues.jboss.org/browse/ISPN-10165-9.4.x
@andyuk1986 @karesti
> [9.4] ISPN-10165 - Fix rolling upgrades tests according to latest changes

- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/HotRodTargetMigrator.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/rollingupgrades/HotRodRollingUpgradesDistIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/rollingupgrades/HotRodRollingUpgradesIT.java
https://issues.jboss.org/browse/ISPN-10165
> Use old rolling upgrade strategy when protocol < 2.5

- distribution/src/main/assemblies/server.xml
https://issues.jboss.org/browse/ISPN-10163
> ISPN-10163 Fix more references to fat/thin servers

- distribution/src/main/assemblies/server.xml
- jcache/tck-runner/pom.xml
https://issues.jboss.org/browse/ISPN-10163
> [9.4] ISPN-10163 Fix more references to fat/thin servers

- documentation/pom.xml
- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/configuration/wfly_extensions.adoc
- documentation/src/main/asciidoc/user_guide/integrations.adoc
Backport for ISPN-10132 
https://issues.jboss.org/browse/ISPN-10132
> [9.4.x] ISPN-10132 removing endpoint extensions module from downstream

- core/src/main/java/org/infinispan/conflict/impl/DefaultConflictManager.java
- core/src/test/java/org/infinispan/conflict/impl/CrashedNodeDuringConflictResolutionTest.java
- core/src/test/java/org/infinispan/partitionhandling/BasePartitionHandlingTest.java
https://issues.jboss.org/browse/ISPN-9291
* Force STABLE gc before merge to reproduce the problem
* Compute the NAKACK2 digest for the merge view to fix it
> ISPN-9291 BasePartitionHandlingTest.Partition.installMergeView()

- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/security/HotRodKrbAuthIT.java
https://issues.jboss.org/browse/ISPN-10188
> ISPN-10188 Fix absolute path to the kerberos files on Windows

- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/security/HotRodKrbAuthIT.java
https://issues.jboss.org/browse/ISPN-10188
> [9.4] ISPN-10188 Fix absolute path to the kerberos files on Windows

- commons/src/main/java/org/infinispan/commons/time/TimeServiceTicker.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/DefaultIterationManager.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationReaper.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodIteratorReapTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodClient.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/TestIteratorNextResponse.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/TestIteratorStartResponse.java
https://issues.jboss.org/browse/ISPN-9195
The timeout reaper is set at 1 minute. This is probably too short for some uses. I don't really want to add an extra config parameter for this. We can consider using some other timeout (remote timeout?)
> ISPN-9195 Reap Server Iterators

- build-configuration/pom.xml
- core/src/test/java/org/infinispan/test/TestingUtil.java
https://issues.jboss.org/browse/ISPN-10190
> ISPN-10190 JDK 12+ fixes

- documentation/src/main/asciidoc/server_guide/configuration.adoc
- documentation/src/main/asciidoc/topics/jgroups/jgroups_subsystem.adoc
Relates to QE feedback in https://issues.jboss.org/browse/JDG-2671
> ISPN-10091 feedback on dns ping

- persistence/soft-index/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreStressTest.java
https://issues.jboss.org/browse/ISPN-10197
> ISPN-10197 SoftIndexFileStoreStressTest is broken

- integrationtests/pom.xml
- integrationtests/wildfly-modules/pom.xml
- integrationtests/wildfly-modules/src/test/resources/as-config/standalone/configuration/standalone-test.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-10142
https://issues.jboss.org/browse/ISPN-10144
https://issues.jboss.org/browse/ISPN-10106 (partial fix, do not close)
> [9.4] ISPN-10142 Wildfly modules integrationtests ignore branding

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/AbstractHotRodSiteFailoverTest.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
- core/src/main/java/org/infinispan/remoting/transport/AggregateBackupResponse.java
- core/src/main/java/org/infinispan/remoting/transport/BackupResponse.java
- core/src/main/java/org/infinispan/remoting/transport/XSiteAsyncAckListener.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponse.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/main/java/org/infinispan/xsite/OfflineStatus.java
- core/src/test/java/org/infinispan/jmx/RpcManagerMBeanTest.java
- core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponseUnitTest.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/DelegatingTransport.java
- documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheMetricsHandler.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/MetricKeys.java
- server/integration/infinispan/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
* async replication time
* automatically take a site offline
> ISPN-9457 ISPN-10180 Async Cross-Site Features

- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/productized/spring_boot_starter.adoc
Relates to Anna's comments in https://issues.jboss.org/browse/JDG-2838
> QE review for SB Starter docs

- core/src/test/java/org/infinispan/scattered/statetransfer/CoordinatorStopTest.java
https://issues.jboss.org/browse/ISPN-9940
> [9.4] ISPN-9440 CoordinatorStopTest move to unstable group

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheContainer.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/exceptions/CacheNotTransactionalException.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ClientStatistics.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/Util.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/TransactionalRemoteCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tx/InvalidServerConfigTxTest.java
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
https://issues.jboss.org/browse/ISPN-9397
> ISPN-9397 Check TX support for remote caches

- persistence/jpa/src/test/java/org/infinispan/persistence/jpa/BaseJpaStoreTest.java
https://issues.jboss.org/browse/ISPN-10196
>  ISPN-10196 Fixing java.lang.IllegalStateException: EntityManager is closed

- integrationtests/wildfly-modules/pom.xml
- jcache/tck-runner/pom.xml
- server/integration/testsuite/pom.xml
https://issues.jboss.org/browse/ISPN-10164
> ISPN-10164 Ensure that all tests are running with the correct JVM version

- distribution/package.xml
- distribution/pom.xml
- distribution/src/main/assemblies/wildfly-server.xml
- integrationtests/all-remote-it/src/test/resources/arquillian.xml
- integrationtests/wildfly-modules/pom.xml
- jcache/tck-runner/pom.xml
- server/integration/testsuite/pom.xml
- server/integration/versions/pom.xml
https://issues.jboss.org/browse/ISPN-10200
> ISPN-10200 Server Distribution changes

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10203
> ISPN-10203 Upgrade ElasticSearch Maven Plugin to 6.13

- persistence/jpa/src/test/java/org/infinispan/persistence/jpa/BaseJpaStoreTest.java
https://issues.jboss.org/browse/ISPN-10196
Entitymanager is already being closed on finally method
> [9.4] ISPN-10196 Fixing java.lang.IllegalStateException: EntityManager is closed

- distribution/wildfly-provisioning.xml
- feature-pack/build.xml
- feature-pack/wf-modules/pom.xml
- feature-pack/wf-modules/src/main/resources/modules/org/hibernate/commons-annotations/slot/module.xml
- feature-pack/wf-modules/src/main/resources/modules/org/hibernate/search/engine/hibernate-search-slot/module.xml
- feature-pack/wf-modules/src/main/resources/modules/system/layers/base/org/hibernate/search/engine/hibernate-slot/module.xml
- server/integration/feature-pack/build.xml
https://issues.jboss.org/browse/ISPN-10105
> Override org.hibernate.search.engine module

- commons/src/main/java/org/infinispan/commons/util/Util.java
- documentation/src/main/asciidoc/user_guide/server_protocols_rest.adoc
- feature-pack/server/src/main/resources/modules/org/infinispan/server/rest/slot/module.xml
- server/rest/pom.xml
- server/rest/src/main/java/org/infinispan/rest/RestResponseException.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/authentication/AuthenticationException.java
- server/rest/src/main/java/org/infinispan/rest/logging/Log.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java
- server/rest/src/test/java/org/infinispan/rest/BaseRestOperationsTest.java
- server/rest/src/test/java/org/infinispan/rest/RestOperationsTest.java
https://issues.jboss.org/browse/ISPN-10151
> ISPN-10151 Implement REST counter operations

- core/src/main/java/org/infinispan/Cache.java
- core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingCache.java
- core/src/test/java/org/infinispan/marshall/core/StoreAsBinaryTest.java
- core/src/test/java/org/infinispan/security/SecureCacheTestDriver.java
https://issues.jboss.org/browse/JDG-2817
backport of https://github.com/infinispan/infinispan/pull/6859
> [9.4.x] ISPN-10143 fix Stackoverflow exception

- Jenkinsfile
- query/pom.xml
Backport https://github.com/infinispan/infinispan/pull/6826
> [9.4] ISPN-10108 - Query Project - Store the test results using TestNG

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/BaseCounter.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/CounterOperationFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/NotificationManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/RemoteCounterManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/StrongCounterImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/WeakCounterImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/AddListenerOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/AddOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/BaseCounterOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/CompareAndSwapOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/DefineCounterOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/GetConfigurationOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/GetCounterNamesOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/GetValueOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/IsDefinedOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/RemoveListenerOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/RemoveOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/ResetOperation.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/counter/StrongCounterHitsAwareTest.java
https://issues.jboss.org/browse/ISPN-10157
> [9.4.x] ISPN-10157 Counter client does not use CH to locate a counter

- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/DefaultIterationManager.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationManager.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationReaper.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationState.java
https://issues.jboss.org/browse/ISPN-9195
Aligned with the improvements in https://github.com/infinispan/infinispan/pull/6912
> ISPN-9195 Reap Hot Rod Server iteration states (amended)

- commons/src/main/java/org/infinispan/commons/time/TimeServiceTicker.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/DefaultIterationManager.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationManager.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationReaper.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationState.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodIteratorReapTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodClient.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/TestIteratorNextResponse.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/TestIteratorStartResponse.java
https://issues.jboss.org/browse/ISPN-9195
> [9.4] ISPN-9195 Reap Server Iterators

- integrationtests/wildfly-modules/pom.xml
- jcache/tck-runner/pom.xml
- server/integration/testsuite/pom.xml
https://issues.jboss.org/browse/ISPN-10164
Backport: https://github.com/infinispan/infinispan/pull/6924
> [9.4] ISPN-10164 Ensure that all tests are running with the correct JVM version

- spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/provider/SpringEmbeddedCacheManager.java
- spring/spring5/spring5-embedded/src/test/java/org/infinispan/spring/embedded/provider/SpringEmbeddedCacheManagerTest.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManager.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManagerTest.java
Backport https://issues.jboss.org/browse/ISPN-10171
> ISPN-10171 Reuse SpringCache instances

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/AbstractHotRodSiteFailoverTest.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
- core/src/main/java/org/infinispan/remoting/transport/AggregateBackupResponse.java
- core/src/main/java/org/infinispan/remoting/transport/BackupResponse.java
- core/src/main/java/org/infinispan/remoting/transport/XSiteAsyncAckListener.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponse.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/main/java/org/infinispan/xsite/OfflineStatus.java
- core/src/test/java/org/infinispan/jmx/RpcManagerMBeanTest.java
- core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponseUnitTest.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/DelegatingTransport.java
- documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheMetricsHandler.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/MetricKeys.java
- server/integration/infinispan/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
* async replication time
* automatically take a site offline
> [9.4.x] ISPN-9457 ISPN-10180 Async Cross-Site Features

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10203
> [9.4] ISPN-10203 Upgrade ElasticSearch Maven Plugin to 6.13

- feature-pack/build.xml
https://issues.jboss.org/browse/ISPN-10177
> [9.4] ISPN-10177 Fix hibernate-slot rename under Windows

- documentation/src/main/asciidoc/user_guide/clustered_lock.adoc
- lock/src/main/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManager.java
https://issues.jboss.org/browse/ISPN-10205
> [9.4] ISPN-10205 Clustered Locks documentation should use EmbeddedClusteredLockManagerFactory

- documentation/src/main/asciidoc/user_guide/clustered_lock.adoc
- lock/src/main/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManager.java
ISPN-9625 Clustered Locks reliability and consistency XML config
I am reusing the same issue because there are only a few changes. Let me know if you prefer a new one.
> ISPN-10205 Clustered Locks documentation should use EmbeddedClusteredLockManagerFactory

- persistence/jpa/src/main/java/org/infinispan/persistence/jpa/JpaStore.java
https://issues.jboss.org/browse/ISPN-10103
> [9.4] ISPN-10103 Allow JpaStore batch deletes with EAP 6

- documentation/src/main/asciidoc/user_guide/security.adoc
https://issues.jboss.org/browse/ISPN-10219
> ISPN-10219 security session doc with wrong declarative configuration

- documentation/src/main/asciidoc/user_guide/security.adoc
https://issues.jboss.org/browse/ISPN-10219
> [9.4] ISPN-10219 security session doc with wrong declarative configuration

- server/integration/src/main/ant/infinispan-server.xml
https://issues.jboss.org/browse/ISPN-10221
> ISPN-10221 On Windows don't run the standalone.conf.bat script

- server/integration/src/main/ant/infinispan-server.xml
https://issues.jboss.org/browse/ISPN-10221
> [9.4] ISPN-10221 On Windows don't run the standalone.conf.bat script

- core/src/main/java/org/infinispan/configuration/cache/AbstractStoreConfigurationBuilder.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/persistence/LocalConditionalCommandTest.java
- core/src/test/java/org/infinispan/persistence/StoreConfigurationValidationTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/configuration/XmlFileParsingTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stores/TxStoreTest.java
https://issues.jboss.org/browse/ISPN-10095
> [9.4] ISPN-10095 Shared stores should throw exception when cache is local

- cli/cli-interpreter/src/main/antlr3/org/infinispan/cli/interpreter/IspnCliQL.g
- cli/cli-interpreter/src/test/java/org/infinispan/cli/interpreter/SiteStatementTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/AbstractHotRodSiteFailoverTest.java
- core/src/test/java/org/infinispan/xsite/AbstractMultipleSitesTest.java
- core/src/test/java/org/infinispan/xsite/AbstractTwoSitesTest.java
- core/src/test/java/org/infinispan/xsite/AtomicMapBackupTest.java
- core/src/test/java/org/infinispan/xsite/BackupCacheStoppedTest.java
- core/src/test/java/org/infinispan/xsite/BackupForNotSpecifiedTest.java
- core/src/test/java/org/infinispan/xsite/BaseSiteUnreachableTest.java
- core/src/test/java/org/infinispan/xsite/CacheOperationsTest.java
- core/src/test/java/org/infinispan/xsite/NoFailureAsyncReplWarnFailurePolicyTest.java
- core/src/test/java/org/infinispan/xsite/NonTxAsyncBackupTest.java
- core/src/test/java/org/infinispan/xsite/RollbackNoPrepareOptimisticTest.java
- core/src/test/java/org/infinispan/xsite/XSiteAdminOperationsTest.java
- core/src/test/java/org/infinispan/xsite/XSiteCacheConfigurationTest.java
- core/src/test/java/org/infinispan/xsite/backupfailure/BaseBackupFailureTest.java
- core/src/test/java/org/infinispan/xsite/backupfailure/NonTxBackupFailureTest.java
- core/src/test/java/org/infinispan/xsite/backupfailure/tx/BaseBackupTxFailureTest.java
- core/src/test/java/org/infinispan/xsite/backupfailure/tx/BaseLocalClusterTxFailureTest.java
- core/src/test/java/org/infinispan/xsite/backupfailure/tx/SinglePhaseCommitFailureTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/DelegatingTransport.java
- core/src/test/java/org/infinispan/xsite/offline/NonTxOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/ResetOfflineStatusTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/LocalCacheStateTransferTest.java
- core/src/test/resources/configs/xsite/relay-config.xml
https://issues.jboss.org/browse/ISPN-10127
> [9.4] ISPN-10127 Unquote quoted site names in the CLI

- spring/spring4/pom.xml
https://issues.jboss.org/browse/ISPN-10214
> [9.4] ISPN-10214 Remove non-existing properties in spring4 module

- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/cs/factory/DeployedCacheStoreMetadata.java
- server/integration/infinispan/src/test/java/org/jboss/as/clustering/infinispan/cs/factory/DeployedCacheStoreMetadataTest.java
https://issues.jboss.org/browse/ISPN-10226
> ISPN-10226 DeployedCacheStoreMetadataTest fixes

- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/cs/factory/DeployedCacheStoreMetadata.java
- server/integration/infinispan/src/test/java/org/jboss/as/clustering/infinispan/cs/factory/DeployedCacheStoreMetadataTest.java
https://issues.jboss.org/browse/ISPN-10226
> [9.4] ISPN-10226 DeployedCacheStoreMetadataTest fixes

- distribution/package.xml
https://issues.jboss.org/browse/ISPN-10228
> ISPN-10229 Name of server licenses file should be licenses.xml

- distribution/package.xml
https://issues.jboss.org/browse/ISPN-10228
> [9.4] ISPN-10229 Name of server licenses file should be licenses.xml

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client/src/test/resources/hotrod-client.properties
- server/integration/testsuite/src/test/resources/hotrod-client.properties
- spring/spring5/spring5-remote/src/test/resources/org/infinispan/spring/remote/support/InfinispanRemoteCacheManagerFactoryBeanContextTest.xml
https://issues.jboss.org/browse/ISPN-6164
> ISPN-6164 Remove deprecated ping on startup configuration

- core/src/main/java/org/infinispan/context/Flag.java
- core/src/main/java/org/infinispan/context/impl/FlagBitSets.java
https://issues.jboss.org/browse/ISPN-8205
> ISPN-8070 Remove deprecate flags, deprecate unused flags

- core/src/test/java/org/infinispan/notifications/cachelistener/ListenerExceptionTest.java
https://issues.jboss.org/browse/ISPN-10241
> ISPN-10241 ListenerExceptionTest random failures in async test methods

- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/AbstractPartialUpdateTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/PartialFutureUpdateTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/PartialTombstoneTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/util/ExpectingInterceptor.java
- hibernate/cache-v51/pom.xml
- hibernate/cache-v53/pom.xml
Generate Hibernate cache test results - https://issues.jboss.org/browse/ISPN-10208
PartialUpdateTest / PartialTombstoneTest fixes - https://issues.jboss.org/browse/ISPN-10207
> ISPN-10208 & ISPN-10207 Hibernate cache fixes

- core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java
- core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java
https://issues.jboss.org/browse/ISPN-10136
https://issues.jboss.org/browse/ISPN-9979
>  ISPN-10136 Spurious dependency cycle detected error 

- persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/AbstractRemoteStoreConfigurationChildBuilder.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfiguration.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationBuilder.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationChildBuilder.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/HotRodMigratorHelper.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/HotRodTargetMigrator.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeSynchronizerTest.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/TestCluster.java
- tools/src/main/java/org/infinispan/tools/config/v6/remote/RemoteStoreConfigurationParser60.java
- tools/src/test/java/org/infinispan/tools/ConfigurationConverterTest.java
https://issues.jboss.org/browse/ISPN-8089
> ISPN-8089 Remove RemoteStore deprecated config

- core/src/main/java/org/infinispan/atomic/impl/AtomicKeySetImpl.java
- core/src/main/java/org/infinispan/atomic/impl/FineGrainedAtomicMapProxyImpl.java
https://issues.jboss.org/browse/ISPN-10239
Fixes NullPointerException in
DistFineGrainedAtomicMapAPITest.testReplicationPutAndClearCommit
> ISPN-10239 FineGrainedAtomicMap.clear() concurrency issues

- hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/UnorderedDistributionInterceptor.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/AbstractFunctionalTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/BulkOperationsTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/ConcurrentWriteTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/EntitiesAndCollectionsInSameRegionTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/EqualityTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/LocalCacheTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/NonTxQueryTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/ReadOnlyTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/ReadWriteTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/VersionedTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/EntityCollectionInvalidationTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/NaturalIdInvalidationTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/SessionRefreshTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/util/TestConfigurationHook.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/util/TestRegionFactory.java
https://issues.jboss.org/browse/ISPN-10229
> ISPN-10229 Ignore returns from other nodes and return stats

- hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/UnorderedDistributionInterceptor.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/AbstractFunctionalTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/BulkOperationsTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/ConcurrentWriteTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/EntitiesAndCollectionsInSameRegionTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/EqualityTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/LocalCacheTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/NonTxQueryTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/ReadOnlyTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/ReadWriteTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/VersionedTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/EntityCollectionInvalidationTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/NaturalIdInvalidationTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/SessionRefreshTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/util/TestConfigurationHook.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/util/TestRegionFactory.java
https://issues.jboss.org/browse/ISPN-10229
> [9.4] ISPN-10229 Ignore returns from other nodes and return stats

- build-configuration/pom.xml
- checkstyle/pom.xml
- jcache/tck-runner/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-9564
> [9.4.x] ISPN-9564 Align Versions

- extended-statistics/pom.xml
https://issues.jboss.org/browse/ISPN-10258
> ISPN-10258 Remove hard-coded version of com.clearspring.analytics:stream

- extended-statistics/pom.xml
https://issues.jboss.org/browse/ISPN-10258
> [9.4.x] ISPN-10258 Remove hard-coded version of com.clearspring.analytics:stream

- core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
- core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationStateListener.java
- core/src/main/java/org/infinispan/statetransfer/StateProviderImpl.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferManagerImpl.java
- query/src/main/java/org/infinispan/query/affinity/AffinityIndexManager.java
- query/src/main/java/org/infinispan/query/backend/SearchFactoryHandler.java
- query/src/main/java/org/infinispan/query/indexmanager/ClusteredSwitchingBackend.java
https://issues.jboss.org/browse/ISPN-9715
> ISPN-9715 Update internal embedded listeners to be non blocking

- hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/UnorderedDistributionInterceptor.java
https://issues.jboss.org/browse/ISPN-10267
Fixes 2 CI failures
> ISPN-10267 Rethrow remote exceptions

- commons-test/src/main/java/org/infinispan/commons/lambda/NamedLambdas.java
- commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitXMLReporter.java
- core/src/test/java/org/infinispan/api/APINonTxTest.java
- core/src/test/java/org/infinispan/manager/SingleClusterExecutorExecutionPolicyTest.java
Backport https://github.com/infinispan/infinispan/pull/6950
> [9.4] ISPN-10220 Create named lambdas to identify which test is running

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10263
> ISPN-10263 upgrade spring dependencies

- core/src/main/java/org/infinispan/configuration/parsing/Element.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/InfinispanMessages.java
- server/integration/infinispan/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
A few things I missed in https://github.com/infinispan/infinispan/pull/7003
> ISPN-10234 Remove SingletonCacheWriter extras

- hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/UnorderedDistributionInterceptor.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/AbstractPartialUpdateTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/PartialFutureUpdateTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/PartialTombstoneTest.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/util/ExpectingInterceptor.java
- hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/impl/Sync.java
https://issues.jboss.org/browse/ISPN-9919
https://issues.jboss.org/browse/ISPN-10207
https://issues.jboss.org/browse/ISPN-10267
> [9.4] Hibernate Cache backports

- commons/src/main/java/org/infinispan/commons/time/DefaultTimeService.java
- commons/src/main/java/org/infinispan/commons/time/TimeService.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
- core/src/main/java/org/infinispan/remoting/transport/XSiteAsyncAckListener.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponseUnitTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
- extended-statistics/src/test/java/org/infinispan/stats/BaseTxClusterExtendedStatisticLogicTest.java
- extended-statistics/src/test/java/org/infinispan/stats/logic/LocalTxClusterExtendedStatisticLogicTest.java
- extended-statistics/src/test/java/org/infinispan/stats/logic/OptimisticLockingTxClusterExtendedStatisticLogicTest.java
- extended-statistics/src/test/java/org/infinispan/stats/logic/PessimisticLockingTxClusterExtendedStatisticLogicTest.java
https://issues.jboss.org/browse/ISPN-10264
> ISPN-10264 Wrong time conversion for async xsite take-offline

- core/src/main/java/org/infinispan/atomic/impl/AtomicKeySetImpl.java
- core/src/main/java/org/infinispan/atomic/impl/FineGrainedAtomicMapProxyImpl.java
https://issues.jboss.org/browse/ISPN-10239
Fixes NullPointerException in
DistFineGrainedAtomicMapAPITest.testReplicationPutAndClearCommit
> [9.4.x] ISPN-10239 FineGrainedAtomicMap.clear() concurrency issues

- commons/src/main/java/org/infinispan/commons/time/DefaultTimeService.java
- commons/src/main/java/org/infinispan/commons/time/TimeService.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
- core/src/main/java/org/infinispan/remoting/transport/XSiteAsyncAckListener.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponseUnitTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
- extended-statistics/src/test/java/org/infinispan/stats/BaseTxClusterExtendedStatisticLogicTest.java
- extended-statistics/src/test/java/org/infinispan/stats/logic/LocalTxClusterExtendedStatisticLogicTest.java
- extended-statistics/src/test/java/org/infinispan/stats/logic/OptimisticLockingTxClusterExtendedStatisticLogicTest.java
- extended-statistics/src/test/java/org/infinispan/stats/logic/PessimisticLockingTxClusterExtendedStatisticLogicTest.java
https://issues.jboss.org/browse/ISPN-10264
master: https://github.com/infinispan/infinispan/pull/7008
> [9.4.x] ISPN-10264 Wrong time conversion for async xsite take-offline

- spring/spring4/spring4-common/src/main/resources/META-INF/spring.schemas
- spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/config/CacheLoaderNotFoundTest-context.xml
- spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/config/InfinispanContainerCacheManagerDefinitionTest-context.xml
- spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/config/InfinispanEmbeddedCacheManagerDefinitionTest-context.xml
- spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/provider/sample/SampleEmbeddedCacheTestConfig.xml
- spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/provider/sample/SampleTransactionIntegrationTestConfig.xml
- spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/provider/sample/SampleXmlConfigurationTestConfig.xml
- spring/spring4/spring4-remote/src/test/resources/org/infinispan/spring/config/InfinispanRemoteCacheManagerDefinitionTest-context.xml
- spring/spring4/spring4-remote/src/test/resources/org/infinispan/spring/provider/sample/SampleRemoteCacheTestConfig.xml
- spring/spring5/spring5-common/src/main/resources/META-INF/spring.schemas
- spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/config/CacheLoaderNotFoundTest-context.xml
- spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/config/InfinispanContainerCacheManagerDefinitionTest-context.xml
- spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/config/InfinispanEmbeddedCacheManagerDefinitionTest-context.xml
- spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleEmbeddedCacheTestConfig.xml
- spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleTransactionIntegrationTestConfig.xml
- spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleXmlConfigurationTestConfig.xml
- spring/spring5/spring5-remote/src/test/resources/org/infinispan/spring/remote/config/InfinispanRemoteCacheManagerDefinitionTest-context.xml
- spring/spring5/spring5-remote/src/test/resources/org/infinispan/spring/remote/provider/sample/SampleRemoteCacheTestConfig.xml
https://issues.jboss.org/browse/ISPN-10277
> [9.4] ISPN-10277 Fix Spring Schema location to account for both http and https

- build-configuration/pom.xml
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelInitializer.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/DroppedConnectionsTest.java
- commons/src/main/java/org/infinispan/commons/util/SaslUtils.java
- pom.xml
- server/core/src/main/java/org/infinispan/server/core/admin/AdminOperationsHandler.java
- server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/EmbeddedServerAdminOperationHandler.java
- server/core/src/main/java/org/infinispan/server/core/security/AuthorizingCallbackHandler.java
- server/core/src/main/java/org/infinispan/server/core/security/ServerAuthenticationProvider.java
- server/core/src/main/java/org/infinispan/server/core/security/SubjectSaslServer.java
- server/core/src/main/java/org/infinispan/server/core/security/external/ExternalSaslServer.java
- server/core/src/main/java/org/infinispan/server/core/security/external/ExternalSaslServerFactory.java
- server/core/src/main/java/org/infinispan/server/core/security/simple/SimpleGroupPrincipal.java
- server/core/src/main/java/org/infinispan/server/core/security/simple/SimpleServerAuthenticationProvider.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/Authentication.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/AuthenticationConfiguration.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/AuthenticationConfigurationBuilder.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/EndpointServerAuthenticationProvider.java
https://issues.jboss.org/browse/ISPN-10202
ISPN-10202 Rework SASL integration to ease Elytron integration 
Depends on https://github.com/infinispan/infinispan/pull/6952
>  ISPN-10202 Rework SASL integration to ease Elytron integration 

- core/src/main/java/org/infinispan/configuration/ConfigurationManager.java
- core/src/main/java/org/infinispan/configuration/cache/CacheMode.java
- core/src/main/java/org/infinispan/configuration/cache/ClusteringConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/cache/ConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/ParseUtils.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/resources/schema/infinispan-config-10.0.xsd
- core/src/test/java/org/infinispan/configuration/JsonSerializationTest.java
- core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java
- hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/PutFromLoadValidator.java
- hibernate/cache-v51/src/main/java/org/infinispan/hibernate/cache/v51/InfinispanRegionFactory.java
- hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/InfinispanRegionFactory.java
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfigurationParser.java
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/configuration/Attribute.java
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/configuration/SoftIndexFileStoreConfigurationParser.java
https://issues.jboss.org/browse/ISPN-10281
https://issues.jboss.org/browse/ISPN-10282
> ISPN-10281 & ISPN-10282 Misc XML parser fixes

- core/src/main/java/org/infinispan/persistence/support/ComposedSegmentedLoadWriteStore.java
* Make sure to set parallelism level properly
* Fix issue where store bulkUpdate could happen in parallel
https://issues.jboss.org/browse/ISPN-10286
> ISPN-10286 Segmented Store can get stuck with bulk write

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/Flag.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SkipNotificationsFlagTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientEventsWithIgnoreNotificationsFlagTest.java
- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
- documentation/src/main/asciidoc/upgrading/upgrading-content.adoc
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodHeader.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ProtocolFlag.java
https://issues.jboss.org/browse/ISPN-10296
Backport of #7031
> [9.4.x] ISPN-10296 SKIP_LISTENER_NOTIFICATION flag in hotrod

- documentation/src/main/asciidoc/server_guide/management.adoc
https://issues.jboss.org/browse/ISPN-10271 
> ISPN-10271 JMX URL changes

- build-configuration/pom.xml
- core/src/main/java/org/infinispan/configuration/parsing/XmlConfigHelper.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- server/integration/jgroups/src/main/java/org/infinispan/server/jgroups/JChannelFactory.java
- server/integration/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/ProtocolDefaultsBuilder.java
https://issues.jboss.org/browse/ISPN-10291
* Use only constructor JChannel(InputStream)
* Copy Protocol.setProperties()
* Sprinkle Util.getIpStackType() where needed
> ISPN-10291 Upgrade to JGroups 4.1.1.Final

- distribution/src/main/release/all/bin/config-converter.bat
Script with wrong transaction library name
https://issues.jboss.org/browse/ISPN-10303
> ISPN-10303 config-converter.bat contains wrong transaction library

- core/src/main/java/org/infinispan/remoting/transport/impl/SingleTargetRequest.java
https://issues.jboss.org/browse/ISPN-10289
> ISPN-10289 SingleTargetRequest may invoke the response collector twice

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.jboss.org/browse/ISPN-10290
> ISPN-10290 JGroupsTransport.invokeCommandStaggered allocates too much

- spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/provider/SpringCache.java
- spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/session/AbstractInfinispanSessionRepository.java
- spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanApplicationPublishedBridgeTCK.java
- spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanSessionRepositoryTCK.java
- spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepository.java
- spring/spring5/spring5-embedded/src/test/java/org/infinispan/spring/embedded/session/EmbeddedApplicationPublishedBridgeTest.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepository.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/session/RemoteApplicationPublishedBridgeTest.java
https://issues.jboss.org/browse/ISPN-10224
> [9.4.x] ISPN 10224 Fix session fixation protection

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10307
> ISPN-10307 Upgrade to Jackson Databind 2.9.8

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10307
> [9.4] ISPN-10307 Upgrade to Jackson Databind 2.9.8

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/stress/ClientEventStressTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/stress/ClusterClientEventStressTest.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ClientListenerRegistry.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
https://issues.jboss.org/browse/ISPN-9716
> ISPN-9716 Update internal remote listener code to support non blocking

- commons-test/src/main/java/org/infinispan/commons/test/junit/TmpDir.java
- integrationtests/all-embedded-it/src/test/java/org/infinispan/all/embedded/EmbeddedAllTest.java
https://issues.jboss.org/browse/ISPN-10305
> ISPN-10305 EmbeddedAllTest doesn't clean up its files

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.jboss.org/browse/ISPN-10308
> ISPN-10308 - Allow overwrite startJGroupsChannelIfNeeded

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/Flag.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SkipNotificationsFlagTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientEventsWithIgnoreNotificationsFlagTest.java
- documentation/src/main/asciidoc/hotrod_protocol/hotrod_protocol.asciidoc
- documentation/src/main/asciidoc/upgrading/upgrading-content.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodHeader.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ProtocolFlag.java
https://issues.jboss.org/browse/ISPN-10296
Backport https://github.com/infinispan/infinispan/pull/7032
> ISPN-10296 SKIP_LISTENER_NOTIFICATION flag in hotrod

- core/src/main/java/org/infinispan/health/impl/HealthImpl.java
- documentation/src/main/asciidoc/user_guide/server_protocols_rest.adoc
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/resources/ClusterResource.java
- server/rest/src/test/java/org/infinispan/rest/RestOperationsTest.java
https://issues.jboss.org/browse/ISPN-10268
This should provide enough info to support the [two](https://github.com/jboss-dockerfiles/infinispan/blob/master/server/is_healthy.sh) [healthchecks](https://github.com/jboss-dockerfiles/infinispan/blob/master/server/is_running.sh) in the docker image.
> ISPN-10268 Cluster Resource

- bin/process_trace_logs.sh
https://issues.jboss.org/browse/ISPN-10314
> ISPN-10314 process_trace_logs.sh improvements

- Jenkinsfile
- Jenkinsfile-release
https://issues.jboss.org/browse/ISPN-10321
Define a buildDiscarder option in Jenkinsfile
> ISPN-10321 Jenkins ignores orphaned item strategy in UI

- cloud/src/main/resources/default-configs/default-jgroups-ec2.xml
- cloud/src/main/resources/default-configs/default-jgroups-google.xml
- cloud/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/test/resources/configs/xsite/bridge.xml
- core/src/test/resources/stacks/tcp.xml
- core/src/test/resources/stacks/tcp_mping/tcp1.xml
- core/src/test/resources/stacks/tcp_mping/tcp2.xml
- demos/gui/src/main/release/etc/config/jgroups-tcp.xml
- documentation/src/main/asciidoc/topics/jgroups/tcp_ping.adoc
- hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
- persistence/jdbc/src/test/resources/configs/as7/jdbc-standalone.xml
- server/integration/jgroups/src/main/resources/subsystem-templates/cloud-jgroups.xml
https://issues.jboss.org/browse/JDG-2940
> [9.4.x] ISPN-9886 JGRP-2301 Add UFC protocol even in TCP stacks

- cloud/src/main/resources/default-configs/default-jgroups-ec2.xml
- cloud/src/main/resources/default-configs/default-jgroups-google.xml
- cloud/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/test/resources/configs/xsite/bridge.xml
- core/src/test/resources/stacks/tcp.xml
- core/src/test/resources/stacks/tcp_mping/tcp1.xml
- core/src/test/resources/stacks/tcp_mping/tcp2.xml
- demos/gui/src/main/release/etc/config/jgroups-tcp.xml
- documentation/src/main/asciidoc/topics/jgroups/tcp_ping.adoc
- hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
- persistence/jdbc/src/test/resources/configs/as7/jdbc-standalone.xml
- server/integration/jgroups/src/main/resources/subsystem-templates/cloud-jgroups.xml
Reverts infinispan/infinispan#7022
> Revert "[9.4.x] ISPN-9886 JGRP-2301 Add UFC protocol even in TCP stacks"

- core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
- documentation/src/main/asciidoc/user_guide/interceptors.adoc
I think this is the last one 😅
> Minor spelling mistake (again)

- bin/process_trace_logs.sh
https://issues.jboss.org/browse/ISPN-10314
> ISPN-10314 Fixup: Remove debug logging

- distribution/pom.xml
- pom.xml
- server/integration/licenses/pom.xml
https://issues.jboss.org/browse/ISPN-10328
> ISPN-10328 Upgrade licenses-plugin to 2.0.0.Final

- distribution/pom.xml
- pom.xml
- server/integration/licenses/pom.xml
https://issues.jboss.org/browse/ISPN-10328
> [9.4.x] ISPN-10328 Upgrade licenses-plugin to 2.0.0.Final

- core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java
https://issues.jboss.org/browse/ISPN-10330
> ISPN-10330 BasicComponentRegistryImpl.findFactory() concurrency issue

- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
- core/src/main/java/org/infinispan/notifications/cachemanagerlistener/CacheManagerNotifierImpl.java
- core/src/main/java/org/infinispan/notifications/impl/AbstractListenerImpl.java
- core/src/main/java/org/infinispan/util/concurrent/CompletionStages.java
- core/src/test/java/org/infinispan/notifications/cachelistener/BaseCacheNotifierImplInitialTransferTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/CacheNotifierImplTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/KeyFilterTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/OnlyPrimaryOwnerTest.java
https://issues.jboss.org/browse/ISPN-10332
>  ISPN-10332 Make sure listeners resume on the cpu thread

- core/src/main/java/org/infinispan/configuration/cache/PersistenceConfiguration.java
- core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java
- core/src/main/java/org/infinispan/factories/PublisherManagerFactory.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/persistence/support/ComposedSegmentedLoadWriteStore.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/LocalPublisherManagerImpl.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/NonSegmentedLocalPublisherManagerImpl.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherRequestCommand.java
- core/src/test/java/org/infinispan/persistence/PersistenceManagerTest.java
- core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
https://issues.jboss.org/browse/ISPN-9816
> ISPN-9816 Publisher Performance

- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManager.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerStub.java
https://issues.jboss.org/browse/ISPN-10335
> ISPN-10335 Use stub for PersistenceManager when no stores are configured

- Jenkinsfile
- Jenkinsfile-release
https://issues.jboss.org/browse/ISPN-10321
Backport of https://github.com/infinispan/infinispan/pull/7054
> [9.4.x] ISPN-10321 Jenkins ignores orphaned item strategy in UI

- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ClientListenerRegistry.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/Events.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
* Change to add Future in Event
* Complete event in CPU thread pool instead of netty
* Remove check for sync listener
https://issues.jboss.org/browse/ISPN-10329
> ISPN-10329 Remote listener comments

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
https://issues.jboss.org/browse/ISPN-10337
> ISPN-10337 JDBC Purge improvements

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/PutAllProtoRegistrationTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerInterceptor.java
https://issues.jboss.org/browse/ISPN-10269
> ISPN-10269 ProtobufMetadataManagerImpl.registerProtofiles always times out

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
https://issues.jboss.org/browse/ISPN-10337
> [9.4] ISPN-10337 JDBC Purge improvements

- commons/src/main/java/org/infinispan/commons/executors/BlockingThreadPoolExecutorFactory.java
- commons/src/main/java/org/infinispan/commons/util/concurrent/CallerRunsRejectOnShutdownPolicy.java
* Change rejected policy to throw exception when shutdown
https://issues.jboss.org/browse/ISPN-10349
> ISPN-10349 PersistenceManager.addSegments may never complete

- core/src/test/java/org/infinispan/statetransfer/ClusterTopologyManagerTest.java
https://issues.jboss.org/browse/ISPN-9257
https://issues.jboss.org/browse/ISPN-8329
[SCATTERED_SYNC, tx=false] random failures
Use TestingUtil.installNewView to make the test more deterministic
and faster.
> ISPN-9257 ClustertopologyManagerTest.testAbruptLeaveAfterGetStatus2

- core/src/test/java/org/infinispan/statetransfer/ClusterTopologyManagerTest.java
https://issues.jboss.org/browse/ISPN-9257
https://issues.jboss.org/browse/ISPN-8329
[SCATTERED_SYNC, tx=false] random failures
Use TestingUtil.installNewView to make the test more deterministic
and faster.
Backport of https://github.com/infinispan/infinispan/pull/7094
> [9.4.x] ISPN-9257 ClustertopologyManagerTest.testAbruptLeaveAfterGetStatus2

- core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
* Make sure test controls persistence thread configuration
https://issues.jboss.org/browse/ISPN-10364
> ISPN-10364 Persistence (Blocking) thread pool should have a queue

- documentation/src/main/asciidoc/topics/server_protocols_rest.adoc
- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/rest/src/main/java/org/infinispan/rest/Http20RequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/configuration/RestServerConfigurationBuilder.java
- server/rest/src/main/java/org/infinispan/rest/framework/Invocation.java
- server/rest/src/main/java/org/infinispan/rest/framework/RestDispatcher.java
- server/rest/src/main/java/org/infinispan/rest/framework/RestRequest.java
- server/rest/src/main/java/org/infinispan/rest/framework/impl/InvocationImpl.java
- server/rest/src/main/java/org/infinispan/rest/framework/impl/RestDispatcherImpl.java
- server/rest/src/main/java/org/infinispan/rest/framework/impl/SimpleRequest.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceQueryAction.java
- server/rest/src/main/java/org/infinispan/rest/resources/ClusterResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/ConfigResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/SplashResource.java
- server/rest/src/test/java/org/infinispan/rest/framework/RestDispatcherTest.java
https://issues.jboss.org/browse/ISPN-10210
> ISPN-10210 The REST endpoint should be non-blocking

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
* Make sure to observe on the CPU thread
https://issues.jboss.org/browse/ISPN-10378
> ISPN-10378 Preload write is performed on persistence thread

- documentation/src/main/asciidoc/user_guide/security.adoc
- documentation/src/main/asciidoc/user_guide/server_protocols_rest.adoc
Backport for https://issues.jboss.org/browse/ISPN-10381
> [9.4.x] ISPN-10381 anchors to resolve issue with generated docs

- documentation/src/main/asciidoc/topics/security.adoc
- documentation/src/main/asciidoc/topics/server_protocols_rest.adoc
https://issues.jboss.org/browse/ISPN-10381
> ISPN-10381 anchors to resolve issue with generated docs

- feature-pack/server/src/main/resources/modules/org/infinispan/server/endpoint/slot/module.xml
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RestService.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/security/BasicRestSecurityDomain.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/security/HttpServerRequestAdapter.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/security/HttpServerResponseAdapter.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/security/SecurityRealmRestAuthenticator.java
- server/integration/testsuite/build-testsuite.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/rest/RESTHelper.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/security/rest/AbstractBasicSecurity.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/security/rest/RESTBasicSecurityIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/security/rest/RESTCertSecurityIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/security/rest/RESTDigestSecurityIT.java
- server/integration/testsuite/src/test/resources/config/infinispan/rest-security.xml
- server/integration/testsuite/src/test/resources/config/xslt/rest-sec-config-modifier.xsl
- server/rest/src/main/java/org/infinispan/rest/Http20RequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/InfinispanCacheAPIRequest.java
- server/rest/src/main/java/org/infinispan/rest/InfinispanErrorResponse.java
- server/rest/src/main/java/org/infinispan/rest/InfinispanRequest.java
- server/rest/src/main/java/org/infinispan/rest/InfinispanResponse.java
- server/rest/src/main/java/org/infinispan/rest/authentication/SecurityDomain.java
- server/rest/src/main/java/org/infinispan/rest/authentication/impl/BasicAuthenticator.java
- server/rest/src/main/java/org/infinispan/rest/authentication/impl/ClientCertAuthenticator.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/SecurityActions.java
- server/rest/src/main/java/org/infinispan/rest/operations/AbstractOperations.java
- server/rest/src/main/java/org/infinispan/rest/operations/CacheOperations.java
- server/rest/src/main/java/org/infinispan/rest/operations/SearchOperations.java
- server/rest/src/main/java/org/infinispan/rest/operations/SecurityActions.java
- server/rest/src/test/java/org/infinispan/rest/AuthenticationTest.java
- server/rest/src/test/java/org/infinispan/rest/cachemanager/RestCacheManagerTest.java
ISPN-8546 DIGEST authentication
ISPN-10374 CLIENT_CERT authentication
ISPN-8736 REST authorization
https://issues.jboss.org/browse/ISPN-8546
https://issues.jboss.org/browse/ISPN-10374
https://issues.jboss.org/browse/ISPN-8736
> [9.4] ISPN-8736 REST Authz

- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/PooledConnectionFactoryTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/AbstractStringBasedCacheStore.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithManagedConnectionFunctionalTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithPooledConnectionFunctionalTest.java
https://issues.jboss.org/browse/ISPN-10348
> ISPN-10348 Migrate JDBC String based Cache Store from jdg-functional-tests to upstream

- documentation/pom.xml
- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/server_health.adoc
https://issues.jboss.org/browse/ISPN-10382
> ISPN-10382 health query for clusters

- documentation/pom.xml
- documentation/src/main/asciidoc/server_guide/topics.adoc
- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
https://issues.jboss.org/browse/ISPN-10382
> [9.4.x] ISPN-10382 health query for clusters

- query/pom.xml
- query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
- query/src/main/java/org/infinispan/query/backend/QueryKnownClasses.java
- query/src/main/java/org/infinispan/query/backend/SearchFactoryHandler.java
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- query/src/main/java/org/infinispan/query/impl/PersistenceContextInitializer.java
https://issues.jboss.org/browse/ISPN-10380
> ISPN-10380 QueryKnownClasses throws NotSerializableException

- pom.xml
https://issues.jboss.org/browse/ISPN-10383
> ISPN-10383 Align org.jboss.weld to 2.3.4.Final

- documentation/src/main/asciidoc/topics/server_health.adoc
https://issues.jboss.org/browse/ISPN-10382
> ISPN-10382 changing clustered mode to domain mode for clarity

- documentation/src/main/asciidoc/server_guide/topics.adoc
https://issues.jboss.org/browse/ISPN-10382
> ISPN-10382 changing clustered to domain mode for clarity

- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- server/rest/src/main/java/org/infinispan/rest/Http20RequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/BaseRestOperationsTest.java
- server/rest/src/test/java/org/infinispan/rest/RestOperationsTest.java
https://issues.jboss.org/browse/ISPN-10392
> ISPN-10392 Support cache creation with template via REST

- documentation/src/main/asciidoc/topics/clustering.adoc
- documentation/src/main/asciidoc/topics/configuration.adoc
- documentation/src/main/asciidoc/topics/persistence_jdbc.adoc
https://issues.jboss.org/browse/ISPN-10260
> ISPN-10260 Invalid Javadoc Links

- documentation/src/main/asciidoc/user_guide/clustering.adoc
- documentation/src/main/asciidoc/user_guide/configuration.adoc
- documentation/src/main/asciidoc/user_guide/persistence_jdbc.adoc
https://issues.jboss.org/browse/ISPN-10260
> [9.4.x] ISPN-10260 Invalid Javadoc Links

- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/EndpointUtils.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/HotRodSubsystemAdd.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/MemcachedSubsystemAdd.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RestService.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RestSubsystemAdd.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RouterSubsystemAdd.java
- server/integration/feature-pack/src/main/resources/configuration/domain/template.xml
- server/integration/feature-pack/src/main/resources/configuration/standalone/template.xml
https://issues.jboss.org/browse/ISPN-10393
> ISPN-10393 Don't "require" socket-bindings when they are really optional

- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/EndpointUtils.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/HotRodSubsystemAdd.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/MemcachedSubsystemAdd.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RestService.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RestSubsystemAdd.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RouterSubsystemAdd.java
- server/integration/feature-pack/src/main/resources/configuration/domain/template.xml
- server/integration/feature-pack/src/main/resources/configuration/standalone/template.xml
https://issues.jboss.org/browse/ISPN-10393
> [9.4] ISPN-10393 Don't "require" socket-bindings when they are really optional

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10333
> ISPN-10333 Bump RocksDB to 5.18.3

- client/hotrod-client/pom.xml
- persistence/remote/pom.xml
- server/hotrod/pom.xml
- server/integration/testsuite/build-testsuite.xml
- server/integration/testsuite/pom.xml
- server/rest/pom.xml
- server/router/pom.xml
https://issues.jboss.org/browse/ISPN-10233
This is missing the keystore creation using the test JDK
> ISPN-10233 Use test JDK to determine vendor for JAAS config file and keytool/vault execution 

- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/BaseCacheResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceOffHeapTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/ClusterResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/ConfigResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CounterResourceTest.java
https://issues.jboss.org/browse/ISPN-10396
Also took the chance to split the REST tests since they were all in the same place
> ISPN-10396 Obtain cache size via REST

- core/src/main/java/org/infinispan/persistence/factory/CacheStoreFactoryRegistry.java
https://issues.jboss.org/browse/ISPN-10397
Use CopyOnWriteArrayList
> ISPN-10397 CacheStoreFactoryRegistry incorrect synchronization

- core/src/main/java/org/infinispan/persistence/factory/CacheStoreFactoryRegistry.java
https://issues.jboss.org/browse/ISPN-10397
Use CopyOnWriteArrayList
> [9.4.x] ISPN-10397 CacheStoreFactoryRegistry incorrect synchronization

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCache.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/AssertsNearCache.java
https://issues.jboss.org/browse/ISPN-10248
Backport of https://github.com/infinispan/infinispan/pull/6999
> [9.4.x] ISPN-10248 Allow users to customize NearCache behavior

- core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/test/java/org/infinispan/commands/module/TestGlobalConfiguration.java
- core/src/test/java/org/infinispan/commands/module/TestGlobalConfigurationBuilder.java
- core/src/test/java/org/infinispan/commands/module/TestGlobalConfigurationSerializer.java
- core/src/test/java/org/infinispan/commands/module/TestModuleCommandExtensions.java
- core/src/test/java/org/infinispan/commands/module/TestModuleLifecycle.java
- core/src/test/java/org/infinispan/configuration/serializer/ConfigurationSerializerTest.java
- core/src/test/java/org/infinispan/manager/CacheManagerTest.java
- core/src/test/resources/META-INF/services/org.infinispan.commands.module.ModuleCommandExtensions
https://issues.jboss.org/browse/ISPN-10070
Backport of #6806
> [9.4.x] ISPN-10070 DefaultCacheManager should stop components after start failure

- core/src/main/java/org/infinispan/executors/LazyInitializingBlockingTaskAwareExecutorService.java
- core/src/main/java/org/infinispan/executors/LazyInitializingExecutorService.java
- core/src/main/java/org/infinispan/executors/LazyInitializingScheduledExecutorService.java
- core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java
- core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/util/concurrent/BlockingTaskAwareExecutorServiceImpl.java
- core/src/test/java/org/infinispan/commands/module/TestGlobalConfiguration.java
- core/src/test/java/org/infinispan/commands/module/TestGlobalConfigurationBuilder.java
- core/src/test/java/org/infinispan/commands/module/TestGlobalConfigurationSerializer.java
- core/src/test/java/org/infinispan/commands/module/TestModuleCommandExtensions.java
- core/src/test/java/org/infinispan/commands/module/TestModuleLifecycle.java
- core/src/test/java/org/infinispan/configuration/serializer/ConfigurationSerializerTest.java
- core/src/test/java/org/infinispan/manager/CacheManagerTest.java
- core/src/test/java/org/infinispan/remoting/AsynchronousInvocationTest.java
- core/src/test/resources/META-INF/services/org.infinispan.commands.module.ModuleCommandExtensions
https://issues.jboss.org/browse/ISPN-10363
Depends on #6807
> [9.4.x] ISPN-10363 LazyInitializingExecutorService is not thread-safe

- build-configuration/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-10257
> [9.4] ISPN-10257 Remove unused and declared dependencies

- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/management_server.adoc
- documentation/src/main/asciidoc/topics/rolling_upgrades.adoc
- documentation/src/main/asciidoc/topics/server_health.adoc
https://issues.jboss.org/browse/ISPN-10398
> ISPN-10398 updating CLI attribute references

- core/src/main/java/org/infinispan/commands/tx/PrepareCommand.java
- core/src/main/java/org/infinispan/configuration/cache/PartitionHandlingConfigurationBuilder.java
- core/src/main/java/org/infinispan/distribution/LocalizedCacheTopology.java
- core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
- core/src/main/java/org/infinispan/interceptors/impl/InvalidationInterceptor.java
- core/src/main/java/org/infinispan/interceptors/locking/AbstractLockingInterceptor.java
- core/src/main/java/org/infinispan/interceptors/locking/NonTransactionalLockingInterceptor.java
- core/src/main/java/org/infinispan/interceptors/locking/PessimisticLockingInterceptor.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/invalidation/BaseInvalidationTest.java
- core/src/test/java/org/infinispan/invalidation/InvalidationSharedStoreTest.java
- core/src/test/java/org/infinispan/invalidation/TxInvalidationLockingTest.java
- core/src/test/java/org/infinispan/statetransfer/NonTxStateTransferInvalidationTest.java
- core/src/test/java/org/infinispan/test/ReplListener.java
- documentation/src/main/asciidoc/user_guide/clustering.adoc
- hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/NonTxInvalidationInterceptor.java
- hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/TxInvalidationInterceptor.java
> [9.3.x] ISPN-10029 Invalidation locking is not clustered 

- client/hotrod-client/pom.xml
- persistence/remote/pom.xml
- server/hotrod/pom.xml
- server/integration/testsuite/build-testsuite.xml
- server/integration/testsuite/pom.xml
- server/rest/pom.xml
- server/router/pom.xml
https://issues.jboss.org/browse/ISPN-10233
Preview: I still need to add using the test JDK to generate keystores/vaults
> [9.4] ISPN-10233 Use test JDK to determine vendor for JAAS config file and keytool/vault execution 

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/RemoteCounterManager.java
- commons/src/main/java/org/infinispan/counter/api/CounterManager.java
- counter/src/main/java/org/infinispan/counter/configuration/AbstractCounterConfiguration.java
- counter/src/main/java/org/infinispan/counter/configuration/CounterConfigurationBuilder.java
- counter/src/main/java/org/infinispan/counter/configuration/StrongCounterConfiguration.java
- counter/src/main/java/org/infinispan/counter/configuration/StrongCounterConfigurationBuilder.java
- counter/src/main/java/org/infinispan/counter/configuration/WeakCounterConfiguration.java
- counter/src/main/java/org/infinispan/counter/configuration/WeakCounterConfigurationBuilder.java
- counter/src/main/java/org/infinispan/counter/impl/manager/CounterConfigurationManager.java
- counter/src/main/java/org/infinispan/counter/impl/manager/CounterConfigurationStorage.java
- counter/src/main/java/org/infinispan/counter/impl/manager/EmbeddedCounterManager.java
- counter/src/main/java/org/infinispan/counter/impl/manager/PersistedCounterConfigurationStorage.java
- counter/src/main/java/org/infinispan/counter/impl/manager/VolatileCounterConfigurationStorage.java
- counter/src/test/java/org/infinispan/counter/ConfigurationSerializerTest.java
- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- documentation/src/main/asciidoc/topics/server_protocols_rest.adoc
- server/hotrod/src/test/java/org/infinispan/server/hotrod/counter/impl/TestCounterManager.java
- server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceQueryAction.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/CounterResourceTest.java
https://issues.jboss.org/browse/ISPN-10152
> ISPN-10152 Rest counter admin

- pom.xml
https://issues.jboss.org/browse/ISPN-10395
Fixes compile error in Distribution profile.
> ISPN-10395 Fix missing version for ispn-cli

- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/productized/spring_boot_starter.adoc
https://issues.jboss.org/browse/JDG-3004
> SB Starter dependency fix

- pom.xml
https://issues.jboss.org/browse/ISPN-10404
> ISPN-10404 XStream 1.4.11.1

- documentation/src/main/asciidoc/topics/integrations_hibernate_cache.adoc
https://issues.jboss.org/browse/ISPN-10415
> ISPN-10415 Remove standalone-ha.xml references

- documentation/src/main/asciidoc/user_guide/integrations_hibernate_cache.adoc
https://issues.jboss.org/browse/ISPN-10415
> [9.4] ISPN-10415 Remove standalone-ha.xml references

- commons/src/main/java/org/infinispan/commons/dataconversion/BinaryTranscoder.java
- commons/src/main/java/org/infinispan/commons/dataconversion/DefaultTranscoder.java
- core/src/main/java/org/infinispan/factories/EncoderRegistryFactory.java
- core/src/main/java/org/infinispan/marshall/core/EncoderRegistry.java
- core/src/main/java/org/infinispan/marshall/core/EncoderRegistryImpl.java
- core/src/test/java/org/infinispan/dataconversion/DataConversionTest.java
- core/src/test/java/org/infinispan/dataconversion/TranscoderRegistrationTest.java
- server/core/src/main/java/org/infinispan/server/core/LifecycleCallbacks.java
- server/rest/src/test/java/org/infinispan/rest/dataconversion/TextBinaryTranscoderTest.java
- server/rest/src/test/java/org/infinispan/rest/dataconversion/TextObjectTranscoderTest.java
https://issues.jboss.org/browse/ISPN-10433
> ISPN-10433 Decouple JBossMarshallers from Transcoders

- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/AbstractStringBasedCacheStore.java
Fix the thread leak error
Changes are the `AfterMethod` and removing the try finally clause on the tests
https://issues.jboss.org/browse/ISPN-10430
> ISPN-10430 Fix test suite thread leak error

- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManager.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManagerTest.java
Clear SpringCache ok
Clear when removed and recreated with a new config no
backport  #7146 
https://issues.jboss.org/browse/ISPN-10266
> ISPN-10266 SpringCache clear when cache is removed

- persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
https://issues.jboss.org/browse/ISPN-10454
> ISPN-10454 RemoteStore loaded entry has incorrect key

- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManager.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManagerTest.java
backport of #7145 
https://issues.jboss.org/browse/ISPN-10266
> [9.4.x] ISPN-10266 SpringCache clear when cache is removed

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java
- documentation/src/main/asciidoc/topics/hotrod_protocol.adoc
- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodConstants.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/TimeUnitValue.java
- server/hotrod/src/main/resources/hotrod.gr
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodFunctionalTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleNodeTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSslFunctionalTest.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodClient.java
https://issues.jboss.org/browse/ISPN-10032
> ISPN-10032 No longer treat Hot Rod expiration as Unix time in HR 3.0

- core/src/test/java/org/infinispan/persistence/support/AsyncStoreFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/support/AsyncStoreWithoutEvictionFunctionalTest.java
- query/src/test/java/org/infinispan/query/queries/phrases/EmbeddedQueryTest.java
- query/src/test/java/org/infinispan/query/queries/phrases/QueryPhrasesTest.java
- query/src/test/java/org/infinispan/query/test/Author.java
- query/src/test/java/org/infinispan/query/test/Book.java
https://issues.jboss.org/browse/ISPN-10403
> ISPN-10403 Add queries and async-cache functional tests

- core/src/test/java/org/infinispan/persistence/support/AsyncStoreFunctionalTest.java
- query/src/test/java/org/infinispan/query/queries/phrases/EmbeddedQueryTest.java
- query/src/test/java/org/infinispan/query/queries/phrases/QueryPhrasesTest.java
- query/src/test/java/org/infinispan/query/test/Author.java
- query/src/test/java/org/infinispan/query/test/Book.java
https://issues.jboss.org/browse/ISPN-10403
> [9.4] ISPN-10403 Add queries and async-cache functional tests

- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/PooledConnectionFactoryTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/AbstractStringBasedCacheStore.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStoreTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithManagedConnectionFunctionalTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithManagedConnectionTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithPooledConnectionFunctionalTest.java
https://issues.jboss.org/browse/ISPN-10348
> [9.4] ISPN-10348 Migrate JDBC String based Cache Store from jdg-functional tests to upstream

- build-configuration/bom/pom.xml
- build-configuration/pom.xml
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/ProtoStreamMarshallerWithAnnotationsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryWithProtostreamAnnotationsTest.java
- commons/src/main/java/org/infinispan/commons/dataconversion/MediaType.java
- core/src/main/java/org/infinispan/container/versioning/NumericVersion.java
- core/src/main/java/org/infinispan/functional/impl/MetaParamsInternalMetadata.java
- core/src/main/java/org/infinispan/marshall/persistence/impl/MarshalledValueImpl.java
- core/src/main/java/org/infinispan/metadata/EmbeddedMetadata.java
- counter/src/main/java/org/infinispan/counter/impl/strong/StrongCounterKey.java
- counter/src/main/java/org/infinispan/counter/impl/weak/WeakCounterKey.java
- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/CryptoCurrency.java
- lucene/lucene-directory/src/main/java/org/infinispan/lucene/ChunkCacheKey.java
- lucene/lucene-directory/src/main/java/org/infinispan/lucene/FileCacheKey.java
- lucene/lucene-directory/src/main/java/org/infinispan/lucene/impl/FileListCacheValue.java
- lucene/lucene-directory/src/test/java/org/infinispan/lucene/Key2StringMapperTest.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/predicateindex/ProtobufMatcherEvalContext.java
- pom.xml
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadata.java
- server/integration/event-logger/src/main/java/org/infinispan/server/eventlogger/ServerEventImpl.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryWithProtostreamAnnotationsIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/query/Transaction.java
- server/runtime/src/test/java/org/infinispan/server/functional/HotRodCacheQueries.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptMetadata.java
https://issues.jboss.org/browse/ISPN-10432
> ISPN-10432 Upgrade Protostream to 4.3.0.Alpha9

- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
https://issues.jboss.org/browse/ISPN-10423
> ISPN-10423 Fix RocksDB ReadOptions memory leak

- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
https://issues.jboss.org/browse/ISPN-10423
> [9.4] ISPN-10423 Fix RocksDB ReadOptions memory leak

- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.jboss.org/browse/ISPN-10465
> ISPN-10465 Improve jgroups stack-file configuration exceptions

- query/src/test/java/org/infinispan/query/queries/phrases/EmbeddedQueryTest.java
- query/src/test/java/org/infinispan/query/queries/phrases/QueryPhrasesTest.java
- query/src/test/java/org/infinispan/query/test/Author.java
- query/src/test/java/org/infinispan/query/test/Book.java
https://issues.jboss.org/browse/ISPN-10403
> [94x] ISPN-10403 Fix generics in query results, fix asserts in query tests

- core/src/main/java/org/infinispan/executors/LazyInitializingBlockingTaskAwareExecutorService.java
- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
- core/src/main/java/org/infinispan/factories/RecoveryManagerFactory.java
- core/src/main/java/org/infinispan/marshall/exts/CollectionExternalizer.java
- core/src/main/java/org/infinispan/marshall/exts/MapExternalizer.java
https://issues.jboss.org/browse/ISPN-10471
> ISPN-10471 Infinispan changes to support Quarkus using LOCAL cache

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10474
> ISPN-10474 Align logging versions with Quarkus

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10475
> ISPN-10475 Update jgroups to a version that supports Quarkus

- commons/src/main/java/org/infinispan/commons/util/Features.java
https://issues.jboss.org/browse/ISPN-10463
Use the infinispan-commons classloader to look up the features
properties file.
> ISPN-10463 Server uses disabled features

- commons/src/main/java/org/infinispan/commons/util/Features.java
https://issues.jboss.org/browse/ISPN-10463
Use the infinispan-commons classloader to look up the features
properties file.
> [9.4.x] ISPN-10463 Server uses disabled features

- documentation/src/main/asciidoc/topics/server_protocols_hotrod.adoc
https://issues.jboss.org/browse/ISPN-10255 
Backport to 9.4.x
> ISPN-10255 incorrect detail about LRU eviction with near cache

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10484
https://issues.jboss.org/browse/ISPN-10483
> ISPN-10484 Upgrade Protostream to 4.3.0.Alpha10

- Jenkinsfile
- distribution/pom.xml
https://issues.jboss.org/browse/ISPN-10489
> ISPN-10489 Deploy ServerNG zip with SNAPSHOT deployments

- core/src/test/java/org/infinispan/remoting/jgroups/NonExistingJGroupsConfigTest.java
https://issues.jboss.org/browse/ISPN-10465
> ISPN-10465 NonExistingJGroupsConfigTest NPE fix

- server/integration/testsuite/build-testsuite.xml
https://issues.jboss.org/browse/ISPN-10479
I know that I should first open a PR against master but I would like to know if the fix is right.
Thanks,
> ISPN-10479 server.jvm.args is not set to jvm

- server/rest/src/main/java/org/infinispan/rest/ByteBufContentSource.java
https://issues.jboss.org/browse/ISPN-10498
> ISPN-10498 Rest Body Content contains junk with HeapByteBuf

- commons/src/main/java/org/infinispan/commons/dataconversion/StandardConversions.java
- server/core/src/main/java/org/infinispan/server/core/admin/AdminServerTask.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/HotRodServerConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-10501
> ISPN-10501 Various fixes for Quarkus compatibility in Server

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- server/core/src/main/java/org/infinispan/server/core/LifecycleCallbacks.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/JBossMarshallingTranscoder.java
https://issues.jboss.org/browse/ISPN-10499
> ISPN-10499 Remove additional JBossMarshalling references

- core/src/main/java/org/infinispan/context/Flag.java
- core/src/main/java/org/infinispan/context/impl/FlagBitSets.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/StaggeredRequest.java
- core/src/test/java/org/infinispan/configuration/JsonSerializationTest.java
- core/src/test/resources/configs/config-with-jgroups-stack.xml
- core/src/test/resources/configs/unified/10.0.xml
- core/src/test/resources/configs/xsite/bridge.xml
- core/src/test/resources/configs/xsite/xsite-inline-test.xml
- core/src/test/resources/stacks/tcp.xml
- core/src/test/resources/stacks/tcp_mping/tcp1.xml
- core/src/test/resources/stacks/tcp_mping/tcp2.xml
- core/src/test/resources/stacks/udp.xml
- documentation/src/main/asciidoc/topics/config_examples/config_inline_jgroups.xml
- documentation/src/main/asciidoc/topics/upgrading.adoc
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
- lucene/directory-provider/src/test/resources/testing-flush-loopback.xml
- persistence/jdbc/src/test/resources/configs/as7/jdbc-standalone.xml
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/integration/jgroups/src/main/java/org/infinispan/server/jgroups/JChannelFactory.java
- server/integration/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_0.properties
- server/integration/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_0.xml
- server/runtime/src/test/resources/configuration/test-jgroups-tcp.xml
- tools/src/test/resources/udp.xml
https://issues.jboss.org/browse/ISPN-10464
* Remove the GUARANTEED_DELIVERY flag
* Remove the RSVP protocol
>  ISPN-10464 Remove Flag.GUARANTEED_DELIVERY 

- documentation/src/main/asciidoc/topics/cdi.adoc
- documentation/src/main/asciidoc/topics/cloud.adoc
- documentation/src/main/asciidoc/topics/contributing/building.adoc
- documentation/src/main/asciidoc/topics/embedded_datagrid.adoc
- documentation/src/main/asciidoc/topics/integrations_spring.adoc
- documentation/src/main/asciidoc/topics/marshalling.adoc
- documentation/src/main/asciidoc/topics/persistence_jdbc.adoc
- documentation/src/main/asciidoc/topics/persistence_jpa.adoc
https://issues.jboss.org/browse/ISPN-10517
> ISPN-10517 fixing asciidoc errors with broken include statements

- server/integration/feature-pack/src/main/resources/modules/system/add-ons/product-slot/org/jboss/as/cli/main/module.xml
https://issues.jboss.org/browse/ISPN-10524
> ISPN-10524 Align CLI module.xml

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10529
> ISPN-10529 Upgrade to Netty 4.1.39 and tcnative 2.0.25

- server/integration/feature-pack/src/main/resources/modules/system/add-ons/product-slot/org/jboss/as/cli/main/module.xml
https://issues.jboss.org/browse/ISPN-10524
> [9.4] ISPN-10524 Align CLI module.xml

- all/remote/pom.xml
- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10529
> [9.4] ISPN-10529 Upgrade to Netty 4.1.39 and tcnative 2.0.25

- core/src/main/java/org/infinispan/configuration/parsing/ParseUtils.java
- server/runtime/src/main/java/org/infinispan/server/SecurityActions.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/configuration/hotrod/HotRodServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/RealmConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/TrustStoreRealmConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/TrustStoreRealmConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/security/RolePrincipal.java
- server/runtime/src/main/java/org/infinispan/server/security/ServerSecurityRealm.java
- server/runtime/src/main/resources/schema/infinispan-server-10.0.xsd
- server/runtime/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
- server/runtime/src/test/java/org/infinispan/server/security/AuthenticationTLSIT.java
- server/runtime/src/test/java/org/infinispan/server/security/AuthorizationLDAPIT.java
- server/runtime/src/test/java/org/infinispan/server/test/EmbeddedInfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerTestMethodRule.java
- server/runtime/src/test/resources/configuration/AuthorizationLDAPTest.xml
- server/runtime/src/test/resources/configuration/ServerConfigurationParserTest.xml
- server/runtime/src/test/resources/configuration/cache-container/clustered-authz.xml
- server/runtime/src/test/resources/configuration/endpoints/default-auth-tls-external.xml
- server/runtime/src/test/resources/configuration/endpoints/default-auth-tls.xml
- server/runtime/src/test/resources/configuration/endpoints/default-auth.xml
- server/runtime/src/test/resources/configuration/endpoints/default-oauth.xml
- server/runtime/src/test/resources/configuration/security/truststore.xml
- server/runtime/src/test/resources/ldif/infinispan-kerberos.ldif
- server/runtime/src/test/resources/ldif/infinispan.ldif
ISPN-10523 ServerNG TrustStore realm
ISPN-10523 ServerNG parse XML elements in schema order
ISPN-10528 ServerNG enable authorization
https://issues.jboss.org/browse/ISPN-10523
https://issues.jboss.org/browse/ISPN-10528
> ISPN-10523 + ISPN-10528 ServerNG TrustStore and Authorization

- build-configuration/pom.xml
- server/core/pom.xml
https://issues.jboss.org/browse/ISPN-10536
> ISPN-10536 Remove unused tcnative properties from pom.xml

- documentation/src/main/asciidoc/topics/rest_api_v1.adoc
- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
https://issues.jboss.org/browse/ISPN-10486
> ISPN-10486 REST endpoint docs missing the /rest context

- core/src/main/java/org/infinispan/configuration/parsing/XmlConfigHelper.java
- integrationtests/pom.xml
- object-filter/src/main/java/org/infinispan/objectfilter/impl/ReflectionMatcher.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ReflectionPropertyHelper.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/util/ReflectionHelper.java
- object-filter/src/test/java/org/infinispan/objectfilter/impl/util/ReflectionHelperTest.java
- pom.xml
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelper.java
no more java.beans or java.desktop module
https://issues.jboss.org/browse/ISPN-10544
> ISPN-10544 Remove dependencies on java.beans module

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10551
> ISPN-10551 Bump Arquillian to 1.4.1.Final

- commons/src/main/java/org/infinispan/commons/tx/TransactionImpl.java
- core/src/test/java/org/infinispan/tx/EmbeddedTransactionTest.java
https://issues.jboss.org/browse/ISPN-9425
> ISPN-9425 Do not ignore NO_TX XA return code

- commons/src/main/java/org/infinispan/commons/tx/TransactionImpl.java
- core/src/test/java/org/infinispan/tx/EmbeddedTransactionTest.java
https://issues.jboss.org/browse/ISPN-9425
> [9.4.x] ISPN-9425 Do not ignore NO_TX XA return code

- documentation/src/main/asciidoc/server_guide/configuration.adoc
https://issues.jboss.org/browse/JDG-3159 
Server Guide mentions the old eviction configuration. Docs should point to the eviction section in the User Guide.
> [9.4.x] JDG-3159 old eviction configuration

- core/src/main/java/org/infinispan/marshall/core/GlobalMarshaller.java
- core/src/main/java/org/infinispan/marshall/persistence/impl/PersistenceMarshallerImpl.java
https://issues.jboss.org/browse/ISPN-10541
> ISPN-10541 Disable Jboss-marshalling warning in server mode

- client/hotrod-client/src/main/resources/features.xml
- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- feature-pack/embedded-query/src/main/resources/modules/org/infinispan/objectfilter/slot/module.xml
- object-filter/pom.xml
- object-filter/src/main/java/org/infinispan/objectfilter/impl/logging/Log.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelper.java
- query/src/main/java/org/infinispan/query/logging/Log.java
- query/src/test/java/org/infinispan/query/blackbox/ClusteredQueryTest.java
https://issues.jboss.org/browse/ISPN-10532
https://issues.jboss.org/browse/ISPN-10533
>  ISPN-10532 org.antlr.runtime.RecognitionException class leaks from logger interface of object-filter

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodServerStartStopTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ReplTopologyChangeTest.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelper.java
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- query/src/test/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelperTest.java
- query/src/test/java/org/infinispan/query/dsl/embedded/impl/LuceneTransformationTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ObjectReflectionMatcher.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ObjectRemoteQueryManager.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufObjectReflectionMatcher.java
- remote-query/remote-query-server/src/test/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadataTest.java
- server/core/src/test/java/org/infinispan/server/core/dataconversion/ProtostreamJsonTranscoderTest.java
- server/core/src/test/java/org/infinispan/server/core/dataconversion/ProtostreamTextTranscoderTest.java
https://issues.jboss.org/browse/ISPN-9976
> Reimplement ISPN-9976 test for Elastic Search availability 

- javadoc/javadoc-all/pom.xml
https://issues.jboss.org/browse/ISPN-10556
> ISPN-10556 Add antlr-runtime to the javadoc dependencies to fix build

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10569
> ISPN-10569 Bump JGroups to 4.1.4.Final

- core/src/main/java/org/infinispan/interceptors/impl/TransactionalExceptionEvictionInterceptor.java
https://issues.jboss.org/browse/ISPN-10579
> ISPN-10579 TransactionalExceptionEvictionInterceptor 1PC PrepareCommand

- build-configuration/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-10561
> ISPN-10561 Upgrade to Jackson Databind 2.9.9.3

- build-configuration/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-10561
> [9.4] ISPN-10561 Upgrade to Jackson Databind 2.9.9.3

- .gitignore
- build-configuration/pom.xml
- pom.xml
Cretaceous dependency
https://issues.jboss.org/browse/ISPN-10582
> ISPN-10582 Remove ANTLR 2.x

- server/integration/testsuite/pom.xml
https://issues.jboss.org/browse/ISPN-10585
> [9.4.x] ISPN-10585 Wrong property for jackson-databind in server-testsuite

- server/integration/testsuite/pom.xml
https://issues.jboss.org/browse/ISPN-10585
> ISPN-10585 Wrong property for jackson-databind in server-testsuite

- build-configuration/pom.xml
- client/hotrod-client/pom.xml
- javadoc/javadoc-all/pom.xml
- javadoc/javadoc-embedded/pom.xml
- javadoc/javadoc-remote/pom.xml
https://issues.jboss.org/browse/ISPN-10576
> [9.4.x] ISPN-10576 Upgrade Protostream to 4.2.4.Final

- build-configuration/pom.xml
- client/hotrod-client/pom.xml
- core/src/main/java/org/infinispan/marshall/persistence/impl/PersistenceMarshallerImpl.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java
https://issues.jboss.org/browse/ISPN-10519
> ISPN-10519 Upgrade to protostream-4.3.0.Alpha11

- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestClientOkHttp.java
- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/integration/testsuite/src/test/resources/config/parts/cachecontainer-endpoints-multitenancy.xml
- server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/router/src/test/java/org/infinispan/server/router/integration/RestEndpointRouterTest.java
- server/router/src/test/java/org/infinispan/server/router/integration/SinglePortTest.java
- server/router/src/test/java/org/infinispan/server/router/utils/RestTestingUtil.java
- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointsConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
- server/runtime/src/main/resources/schema/infinispan-server-10.0.xsd
- server/runtime/src/test/java/org/infinispan/server/configuration/JsonSerializationTest.java
- server/runtime/src/test/java/org/infinispan/server/functional/ClusteredIT.java
- server/runtime/src/test/java/org/infinispan/server/functional/RestRouter.java
- server/runtime/src/test/java/org/infinispan/server/unit/configuration/ServerConfigurationParserTest.java
- server/runtime/src/test/resources/configuration/ServerConfigurationParserTest.xml
https://issues.jboss.org/browse/ISPN-10476
> ISPN-10476 SinglePort routing is broken for REST

- commons/src/main/java/org/infinispan/commons/configuration/attributes/Attribute.java
- server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RestService.java
- server/rest/src/main/java/org/infinispan/rest/configuration/CorsConfigurationBuilder.java
- server/rest/src/main/java/org/infinispan/rest/configuration/CorsRuleConfigurationBuilder.java
- server/rest/src/main/java/org/infinispan/rest/configuration/RestServerConfiguration.java
- server/rest/src/main/java/org/infinispan/rest/configuration/RestServerConfigurationBuilder.java
- server/rest/src/test/java/org/infinispan/rest/helper/RestServerHelper.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
- server/runtime/src/test/java/org/infinispan/server/configuration/JsonSerializationTest.java
https://issues.jboss.org/browse/ISPN-10571
> ISPN-10571 CORS usability issues

- documentation/pom.xml
- documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
https://issues.jboss.org/browse/ISPN-10531
> ISPN-10531 standardizing attributes

- core/src/main/java/org/infinispan/util/concurrent/locks/impl/DefaultLockManager.java
addListener creates a lambda instance and a CompletableFuture,
we just need a field to cancel the timeout task.
The JIRA is already marked as fixed, but I didn't create a new one because I had meant to include the change in the original PR. Let me know if you think it's worth a separate issue ;)
> ISPN-10317 CompositeLockPromise cancel timeout task optimization

- core/src/main/java/org/infinispan/interceptors/impl/TransactionalExceptionEvictionInterceptor.java
- core/src/main/java/org/infinispan/statetransfer/StateConsumer.java
- core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
- core/src/main/java/org/infinispan/statetransfer/StateResponseCommand.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/functional/distribution/rehash/FunctionalTxTest.java
- core/src/test/java/org/infinispan/statetransfer/DelegatingStateConsumer.java
https://issues.jboss.org/browse/ISPN-10310
Please do not change the status in JIRA, this is just the first step...
> ISPN-10310 Apply state without blocking

- server/runtime/pom.xml
https://issues.jboss.org/browse/ISPN-10611
Some new test failures should appear, the thread leaks should be fixed by #7107
> ISPN-10611 Jenkins ignores server/runtime test failures

- core/src/main/java/org/infinispan/util/concurrent/locks/impl/DefaultLockManager.java
https://issues.jboss.org/browse/ISPN-10621
> ISPN-10621 NullPointerException in CompositeLockPromise

- core/src/main/java/org/infinispan/configuration/global/GlobalStorageConfigurationBuilder.java
- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- server/rest/pom.xml
- server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/framework/RestRequest.java
- server/rest/src/main/java/org/infinispan/rest/framework/impl/SimpleRequest.java
- server/rest/src/main/java/org/infinispan/rest/operations/exceptions/InvalidFlagException.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceQueryAction.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/cachemanager/RestCacheManagerTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.jboss.org/browse/ISPN-4915
> ISPN-4915 Support flags for REST endpoint

- core/src/main/java/org/infinispan/configuration/global/GlobalRoleConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-10612
> ISPN-10612 Support multiple permissions for GlobalRoleConfigurationBuilder

- wildfly/feature-pack/pom.xml
https://issues.jboss.org/browse/ISPN-10631
> ISPN-10631 infinispan-feature-pack is using wrong parent path

- core/src/main/java/org/infinispan/configuration/cache/AuthorizationConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-10613
> ISPN-10613 Support multiple roles for AuthorizationConfigurationBuilder

- cli/cli-interpreter/pom.xml
- component-annotations/src/main/java/org/infinispan/jmx/annotations/Parameter.java
- component-processor/src/main/java/org/infinispan/component/processor/ComponentAnnotationProcessor.java
- core/pom.xml
- core/src/main/java/org/infinispan/jmx/ResourceDMBean.java
- core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
- counter/pom.xml
- extended-statistics/pom.xml
- hibernate/cache-commons/pom.xml
- hibernate/cache-spi/pom.xml
- hibernate/cache-v51/pom.xml
- hibernate/cache-v53/pom.xml
- jcache/embedded/pom.xml
- lock/pom.xml
- multimap/pom.xml
- pom.xml
- query/pom.xml
- remote-query/remote-query-server/pom.xml
- server/core/pom.xml
- server/hotrod/pom.xml
- server/router/pom.xml
- tasks/manager/pom.xml
- tasks/scripting/pom.xml
https://issues.jboss.org/browse/ISPN-10628
https://issues.jboss.org/browse/ISPN-10629
> ISPN-10628 Signature of DynamicMBean operations and attributes must not use generics

- distribution/wildfly-provisioning.xml
https://issues.jboss.org/browse/ISPN-10632
> ISPN-10632 remove infinispan-feature-pack-server from WF modules

- commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitXMLWriter.java
https://issues.jboss.org/browse/ISPN-10161
Fix the random FileNotFoundException
> ISPN-10161 Create reports directory if missing

- documentation/src/main/asciidoc/topics/code_examples/RequestBalancing.java
- documentation/src/main/asciidoc/topics/server_protocols_hotrod.adoc
https://issues.jboss.org/browse/ISPN-10566
> ISPN-10566 balancing strategy

- documentation/src/main/asciidoc/topics/code_examples/RequestBalancing.java
- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
https://issues.jboss.org/browse/ISPN-10566
> [9.4.x] Backporting ISPN-10566 balancing strategy

- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
Made some mistakes when I backported the changes from 10.x. Thanks.
> [9.4.x] ISPN-10566 9.4.x fix formatting

- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferManagerImpl.java
- core/src/test/java/org/infinispan/xsite/statetransfer/LocalCacheStateTransferTest.java
https://issues.jboss.org/browse/ISPN-10343
> ISPN-10343 LocalCacheStateTransferTest random failures

- core/src/main/java/org/infinispan/configuration/global/GlobalAuthorizationConfiguration.java
- core/src/main/java/org/infinispan/configuration/global/WhiteListConfiguration.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/SaslConfiguration.java
https://issues.jboss.org/browse/ISPN-10644
> ISPN-10644 Random failures in JsonSerializationTest

- server/runtime/pom.xml
https://issues.jboss.org/browse/ISPN-10652
Replaces https://github.com/infinispan/infinispan/pull/7353
> ISPN-10652 Add Agroal Pool to the server

- core/src/main/resources/schema/infinispan-config-10.0.xsd
https://issues.jboss.org/browse/ISPN-10654
> ISPN-10654 Allow multiple sites in jgroups relay schema

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10653
> ISPN-10653 Upgrade to Elytron 1.10.1.Final

- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/test/java/org/infinispan/xsite/NonTxAsyncBackupTest.java
https://issues.jboss.org/browse/ISPN-10650
> ISPN-10650 Expiration should not be replicated cross site

- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- documentation/src/main/asciidoc/topics/rest_examples/get_v2_counter_list.adoc
- documentation/src/main/asciidoc/topics/rest_examples/get_v2_list_caches.adoc
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CounterResourceTest.java
https://issues.jboss.org/browse/ISPN-10655
> ISPN-10655 Add REST operations to return cache and counter names

- server/runtime/src/main/resources/infinispan-defaults.xml
- server/runtime/src/main/server/server/conf/infinispan-local.xml
- server/runtime/src/main/server/server/conf/infinispan.xml
https://issues.jboss.org/browse/ISPN-10672
> ISPN-10672 Adjust default server configs

- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/main/java/org/infinispan/xsite/NoOpBackupSender.java
- core/src/main/java/org/infinispan/xsite/statetransfer/NoOpXSiteStateProvider.java
- core/src/main/java/org/infinispan/xsite/statetransfer/NoOpXSiteStateTransferManager.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferManagerImpl.java
I changed my mind. See comment in https://issues.jboss.org/browse/ISPN-10600?focusedCommentId=13785267&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13785267
https://issues.jboss.org/browse/ISPN-10600
> ISPN-10600 Create empty XSiteStateTransferManager and related classes

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10689
> ISPN-10689 RocksDB 6.2.2

- build-configuration/pom.xml
- server/core/src/main/java/org/infinispan/server/core/dataconversion/json/SecureTypeResolverBuilder.java
https://issues.jboss.org/browse/ISPN-10691
> ISPN-10691 Jackson 2.10.0

- server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/main/java/org/infinispan/rest/resources/MediaTypeUtils.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.jboss.org/browse/ISPN-10688
> ISPN-10688 Error negotiating MediaType when obtaining cache and cache manager config

- core/src/main/java/org/infinispan/remoting/transport/jgroups/FileJGroupsChannelConfigurator.java
https://issues.jboss.org/browse/ISPN-10686
> ISPN-10686 Lazy property replacement for built-in JGroups stacks

- build-configuration/pom.xml
- maven-settings.xml
- pom.xml
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingTagHandler.java
https://issues.jboss.org/browse/ISPN-10692
> ISPN-10692 WildFly 18.0.0.Beta1

- documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
https://issues.jboss.org/browse/ISPN-10679
> [9.4.x] ISPN-10679 expiration with xsite replication

- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoder.java
- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedOperation.java
- server/memcached/src/main/java/org/infinispan/server/memcached/TextProtocolUtil.java
- server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedFunctionalTest.java
https://issues.jboss.org/browse/ISPN-10275
This PR will add support for the Memcached TOUCH operation.
> ISPN-10275 add memcached TOUCH operation

- cli/cli-interpreter/src/main/java/org/infinispan/cli/interpreter/LifecycleCallbacks.java
- core/src/main/java/org/infinispan/factories/ComponentRegistry.java
- core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/registry/impl/InternalCacheRegistryImpl.java
- core/src/main/java/org/infinispan/stats/impl/CacheContainerStatsImpl.java
- core/src/main/java/org/infinispan/util/logging/events/EventLogManager.java
- core/src/main/java/org/infinispan/util/logging/events/impl/EventLogManagerImpl.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- core/src/test/java/org/infinispan/util/PersistenceMockUtil.java
- counter/src/main/java/org/infinispan/counter/EmbeddedCounterManagerFactory.java
- counter/src/main/java/org/infinispan/counter/impl/listener/CounterManagerNotificationManager.java
- counter/src/test/java/org/infinispan/counter/ConfigurationTest.java
- persistence/jpa/src/test/java/org/infinispan/persistence/jpa/JpaStoreTest.java
- server/runtime/src/main/java/org/infinispan/server/logging/events/LifecycleCallbacks.java
- server/runtime/src/test/java/org/infinispan/server/unit/configuration/ServerEventLoggerTest.java
https://issues.jboss.org/browse/ISPN-9541
https://issues.jboss.org/browse/ISPN-10186
>  ISPN-9541 Module initialization is not thread-safe

- core/src/main/java/org/infinispan/util/logging/Log.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/JBossMarshallingTranscoder.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/ProtostreamBinaryTranscoder.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/ProtostreamJsonTranscoder.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/ProtostreamObjectTranscoder.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/ProtostreamTextTranscoder.java
https://issues.jboss.org/browse/ISPN-10699
> ISPN-10699 Add Transcoder name to log statements to aid debugging

- documentation/src/main/asciidoc/topics/cross_site_replication.adoc
https://issues.jboss.org/browse/ISPN-10676
> ISPN-10676 expiration with cross site replication

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/MultiServerStoreQueryTest.java
- commons/src/main/java/org/infinispan/commons/hash/MurmurHash3.java
https://issues.jboss.org/browse/ISPN-10669
> ISPN-10669 MurmurHash3 should have a special case for WrappedBytes

- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
https://issues.jboss.org/browse/ISPN-8198
> ISPN-8198 The RocksDB store should call System.gc() only on Windows

- core/src/main/resources/default-configs/default-jgroups-azure.xml
- core/src/main/resources/default-configs/default-jgroups-ec2.xml
- core/src/main/resources/default-configs/default-jgroups-google.xml
- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/main/resources/default-configs/default-jgroups-udp.xml
https://issues.jboss.org/browse/ISPN-10711
> ISPN-10711 Common jgroups.bind.[address|port] properties

- server/runtime/src/main/server/bin/cli.bat
- server/runtime/src/main/server/bin/common.bat
- server/runtime/src/main/server/bin/server.bat
- server/runtime/src/main/server/bin/user-tool.bat
https://issues.jboss.org/browse/ISPN-10427
> ISPN-10427 Server Windows batch files

- build-configuration/pom.xml
- documentation/pom.xml
- documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/management_server.adoc
- documentation/src/main/asciidoc/topics/proc_accessing_health_cli.adoc
- documentation/src/main/asciidoc/topics/proc_syncing_data_source_clusters.adoc
https://issues.jboss.org/browse/ISPN-10715
> ISPN-10715 removing unnecessary brandcli attribute

- documentation/src/main/asciidoc/titles/hotrod_java/stories.adoc
- documentation/src/main/asciidoc/topics/code_examples/HotRodClientInstance.java
- documentation/src/main/asciidoc/topics/code_examples/HotRodClientProperties.java
- documentation/src/main/asciidoc/topics/config_examples/hotrod-client.properties
- documentation/src/main/asciidoc/topics/proc_configuring_hotrod_java_client_properties.adoc
- documentation/src/main/asciidoc/topics/proc_creating_hotrod_java_client_instances.adoc
- documentation/src/main/asciidoc/topics/server_protocols_hotrod.adoc
https://issues.jboss.org/browse/ISPN-10597
> ISPN-10597 Docs: Configuring Hot Rod Java clients

- client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/RestRawClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestRawClientOkHttp.java
- core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteCacheResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
https://issues.jboss.org/browse/ISPN-10442
> ISPN-10442 Expose XSite information via REST

- api/API_MANIFESTO.md
This file will move to the ```infinispan-api``` module
This is a starting point.
Comments, suggestions, additions, deletions, flowers 🌹  and candy 🍬 , welcome!
https://issues.jboss.org/browse/ISPN-9966
> ISPN-9966 API manifesto

- cli/cli-client/src/main/java/org/infinispan/cli/CLI.java
- cli/cli-client/src/main/java/org/infinispan/cli/activators/ConnectionActivator.java
- cli/cli-client/src/main/java/org/infinispan/cli/impl/CliRuntimeRunner.java
- cli/cli-client/src/main/java/org/infinispan/cli/logging/Messages.java
- commons/src/main/java/org/infinispan/commons/util/StringPropertyReplacer.java
- server/runtime/src/test/java/org/infinispan/server/cli/CliIT.java
- server/runtime/src/test/java/org/infinispan/server/test/AeshTestShell.java
- server/runtime/src/test/resources/cli/batch-preconnect.cli
- server/runtime/src/test/resources/cli/batch.cli
https://issues.jboss.org/browse/ISPN-10714
> ISPN-10174 CLI Batch mode

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/BaseCounterOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/AddClientListenerOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/FaultTolerantPingOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/PingOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/jmx/RemoteCacheManagerMXBean.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HitsAwareCacheManagersTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SocketTimeoutErrorTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/EventLogListener.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/EventSocketTimeoutTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/AbstractRetryTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/SocketTimeoutFailureRetryTest.java
- core/src/test/java/org/infinispan/test/Exceptions.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- core/src/test/java/org/infinispan/test/ThrowableSupplier.java
https://issues.jboss.org/browse/ISPN-10429
> ISPN-10429 Retry Hot Rod operations on socket timeout

- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
https://issues.jboss.org/browse/ISPN-10704
> ISPN-10704 updating HR client properties for 9.4.x

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10720
> ISPN-10720 Update Caffeine to 2.8.x

- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/test/java/org/infinispan/xsite/NonTxAsyncBackupTest.java
https://issues.jboss.org/browse/ISPN-10650
> [9.4.x] ISPN-10650 Expiration should not be replicated cross site

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
https://issues.jboss.org/browse/ISPN-10488
> ISPN-10488 Infinispan Version is not printed in Quarkus native mode

- core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
- core/src/main/java/org/infinispan/container/offheap/SegmentedBoundedOffHeapDataContainer.java
https://issues.jboss.org/browse/ISPN-10754
> ISPN-10754 OffHeap code cleanup

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10759
> ISPN-10759 WildFly 18

- core/src/main/java/org/infinispan/xsite/GlobalXSiteAdminOperations.java
https://issues.jboss.org/browse/ISPN-10722
> [9.4.x] ISPN-10722 Mgmt console: home page load fails with secured container

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10750
> ISPN-10750 Bump maven-compiler-plugin to 3.8.1

- core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
- core/src/main/java/org/infinispan/container/offheap/SegmentedBoundedOffHeapDataContainer.java
- core/src/main/java/org/infinispan/container/offheap/StripedLock.java
https://issues.jboss.org/browse/ISPN-10681
> ISPN-10681 Investigate and possibly convert to StampedLock for OffHeap

- commons/src/main/java/org/infinispan/commons/util/ReflectionUtil.java
- core/src/main/java/org/infinispan/distribution/group/impl/GroupManagerImpl.java
- core/src/main/java/org/infinispan/factories/impl/SecurityActions.java
https://issues.jboss.org/browse/ISPN-9600
> ISPN-9600 ReflectionUtil.invokeAccessibly should not be public

- server/rest/src/main/java/org/infinispan/rest/framework/impl/ResourceNode.java
- server/rest/src/test/java/org/infinispan/rest/framework/impl/ResourceManagerImplTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
https://issues.jboss.org/browse/ISPN-10748
> ISPN-10748 Rest endpoint is not able to reach a preconfigured cache

- client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheManagerClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheManagerClientOkHttp.java
- core/src/main/java/org/infinispan/xsite/GlobalXSiteAdminOperations.java
- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/framework/impl/ResourceNode.java
- server/rest/src/main/java/org/infinispan/rest/logging/Log.java
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
- server/rest/src/test/java/org/infinispan/rest/framework/impl/ResourceManagerImplTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
https://issues.jboss.org/browse/ISPN-10728
> ISPN-10728 Expose cache container level cross-site operations via REST

- client/rest-client/src/main/java/org/infinispan/client/rest/configuration/AbstractConfigurationChildBuilder.java
- client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfiguration.java
- client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationBuilder.java
- client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationChildBuilder.java
- client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationProperties.java
https://issues.jboss.org/browse/ISPN-10773
> ISPN-10773 RestClientConfigurationBuilder timeout configuration must be a long value

- cli/cli-client/src/test/java/org/infinispan/cli/connection/rest/RestConnectorTest.java
https://issues.jboss.org/browse/ISPN-10779
> ISPN-10779 Fix RestConnectorTest.testUrlWithSSL failure

- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
https://issues.jboss.org/browse/ISPN-10782
> ISPN-10782 Log if the serverNG failed to start

- server/runtime/src/main/server/bin/common.bat
- server/runtime/src/main/server/bin/common.sh
https://issues.jboss.org/browse/ISPN-10788
> ISPN-10788 Display serverNG environment always

- documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
https://issues.jboss.org/browse/ISPN-10785
> [9.4.x] ISPN-10785 remove xsite expiration note

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10775
> [9.4] ISPN-10775 Netty 4.1.42

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10775
> ISPN-10775 Update Netty to 4.1.42

- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- documentation/src/main/asciidoc/topics/rest_examples/get_v2_caches.adoc
- documentation/src/main/asciidoc/topics/rest_examples/rest_caches_info_response.json
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
Super simple endpoint, stating point for caches info page
https://issues.jboss.org/browse/ISPN-10690
> ISPN-10690 Caches endpoint starting point

- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
https://issues.jboss.org/browse/ISPN-10792
> ISPN-10792 Log serverNG PID

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10783
> ISPN-10783 Upgrade to latest Spring versions

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/ConnectionFactoryConfigurationBuilder.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/JdbcStringBasedStoreConfigurationBuilder.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/ManagedConnectionFactoryConfigurationBuilder.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/SegmentColumnConfigurationBuilder.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/TableManipulationConfigurationBuilder.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/configuration/ConfigurationTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStoreTest.java
- persistence/jdbc/src/test/resources/configs/string-based-jndi.xml
- tools/src/test/java/org/infinispan/tools/store/migrator/MigratorConfigurationTest.java
https://issues.jboss.org/browse/ISPN-10790
> ISPN-10790 JDBCTableManipulation config is not validated

- server/runtime/src/main/server/server/conf/logging.properties
* json logging off by default
https://issues.jboss.org/browse/ISPN-10011
> ISPN-10011 Add JSON logging in server

- server/core/src/main/java/org/infinispan/server/core/dataconversion/XMLTranscoder.java
https://issues.jboss.org/browse/ISPN-10787
> ISPN-10787 Xstream WARNING printed when starting the server

- core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
- core/src/test/java/org/infinispan/test/fwk/SuiteResourcesAndLogTest.java
- documentation/src/main/asciidoc/topics/contributing/tests.adoc
- integrationtests/security-manager-it/pom.xml
- integrationtests/wildfly-modules/pom.xml
- jcache/tck-runner/pom.xml
- pom.xml
- server/runtime/pom.xml
- wildfly/infinispan/pom.xml
https://issues.jboss.org/browse/ISPN-10695
> ISPN-10695 Standardize the transport stack for the test suite

- documentation/src/main/asciidoc/stories/assembly_monitoring.adoc
- documentation/src/main/asciidoc/stories/assembly_server_logging.adoc
- documentation/src/main/asciidoc/titles/server/stories.adoc
- documentation/src/main/asciidoc/topics/con_access_logs.adoc
- documentation/src/main/asciidoc/topics/faq_content.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_log_properties.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_access_logs.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_json_logging.adoc
- documentation/src/main/asciidoc/topics/ref_access_log_properties.adoc
- documentation/src/main/asciidoc/topics/ref_logging_framework.adoc
- documentation/src/main/asciidoc/topics/ref_logs_categories.adoc
- documentation/src/main/asciidoc/topics/ref_logs_formatters.adoc
- documentation/src/main/asciidoc/topics/ref_logs_handlers.adoc
- documentation/src/main/asciidoc/topics/ref_logs_levels.adoc
- documentation/src/main/asciidoc/topics/ref_logs_root.adoc
- documentation/src/main/asciidoc/topics/ref_logs_server.adoc
- server/runtime/src/main/server/server/conf/logging.properties
https://issues.jboss.org/browse/ISPN-10543
> ISPN-10543 server logging docs
