infinispan/infinispan

- core/src/main/resources/schema/infinispan-config-10.0.xsd
- core/src/test/java/org/infinispan/configuration/ConfigurationUnitTest.java
https://issues.jboss.org/browse/ISPN-10808
> ISPN-10808 infinispan-config-10.xsd is invalid

- core/src/main/java/org/infinispan/transaction/lookup/GenericTransactionManagerLookup.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- server/runtime/pom.xml
https://issues.jboss.org/browse/ISPN-10807
> ISPN-10807 Don't include Narayana in the server

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- commons/src/main/java/org/infinispan/commons/api/AsyncCache.java
- core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingCache.java
- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/main/java/org/infinispan/cache/impl/DecoratedCache.java
- core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
- core/src/main/java/org/infinispan/container/offheap/BoundedOffHeapDataContainer.java
- core/src/main/java/org/infinispan/factories/PublisherManagerFactory.java
- core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManager.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/LocalClusterPublisherManagerImpl.java
- core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java
- core/src/test/java/org/infinispan/functional/decorators/FunctionalAdvancedCache.java
- core/src/test/java/org/infinispan/security/SecureCacheTestDriver.java
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
https://issues.jboss.org/browse/ISPN-10802
> ISPN-10802 Add sizeAsync method

- build-configuration/pom.xml
- integrationtests/spring-boot2-it/pom.xml
- integrationtests/spring-boot2-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/web/TestRESTController.java
https://issues.jboss.org/browse/JDG-3308
> [9.4] ISPN-10783 Upgrade to latest Spring versions

- core/src/main/java/org/infinispan/AdvancedCache.java
- core/src/main/java/org/infinispan/Cache.java
- core/src/test/java/org/infinispan/security/SecureCacheTestDriver.java
https://issues.jboss.org/browse/ISPN-10810
> ISPN-10810 Add Serializable override methods for the Async methods

- core/src/main/java/org/infinispan/configuration/cache/SingleFileStoreConfigurationBuilder.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- documentation/src/main/asciidoc/topics/upgrading.adoc
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/configuration/SoftIndexFileStoreConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-10813
> ISPN-10813 File Stores should notify user of being segmented can use many file descriptors

- core/src/main/java/org/infinispan/remoting/LocalInvocation.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
- core/src/main/java/org/infinispan/util/concurrent/ActionSequencer.java
- core/src/main/java/org/infinispan/util/concurrent/CompletableFutures.java
- core/src/main/java/org/infinispan/xsite/BackupReceiver.java
- core/src/main/java/org/infinispan/xsite/BaseBackupReceiver.java
- core/src/main/java/org/infinispan/xsite/ClusteredCacheBackupReceiver.java
- core/src/main/java/org/infinispan/xsite/LocalCacheBackupReceiver.java
- core/src/main/java/org/infinispan/xsite/SingleXSiteRpcCommand.java
- core/src/main/java/org/infinispan/xsite/XSiteReplicateCommand.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStatePushCommand.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferControlCommand.java
- core/src/test/java/org/infinispan/jmx/PerCacheInboundHandlerMBeanTest.java
- core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java
- core/src/test/java/org/infinispan/util/ActionSequencerUnitTest.java
- core/src/test/java/org/infinispan/xsite/BackupReceiverDelegator.java
- core/src/test/java/org/infinispan/xsite/RollbackNoPrepareOptimisticTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/failures/RetryMechanismTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/failures/SiteConsumerTopologyChangeTest.java
* distinct keys can be applied in parallel
https://issues.jboss.org/browse/ISPN-10657
ps. don't close the JIRA. It needs to be backported to 9.4.x
> ISPN-10657 Handle async-xsite in parallel

- commons-test/src/main/java/org/infinispan/commons/test/RunningTestsRegistry.java
https://issues.jboss.org/browse/ISPN-10824
> ISPN-10824 Hanged tests are ignored by Jenkins

- documentation/src/main/asciidoc/topics/server_protocols_rest.adoc
https://issues.jboss.org/browse/ISPN-10584
> ISPN-10584 Create a new java rest client example with the new HttpClient API

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10852
> [10.0.x] ISPN-10852 Upgrade to protostream-4.3.0.Final

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10852
> ISPN-10852 Upgrade to protostream-4.3.0.Final

- Jenkinsfile-release
- commons/proto.lock
- core/proto.lock
- counter/proto.lock
- jcache/embedded/proto.lock
- lucene/lucene-directory/proto.lock
- multimap/proto.lock
- persistence/rocksdb/proto.lock
- query/pom.xml
- query/proto.lock
- remote-query/remote-query-server/proto.lock
- server/core/proto.lock
- server/memcached/proto.lock
- server/runtime/proto.lock
- tasks/scripting/proto.lock
https://issues.jboss.org/browse/ISPN-10856
> Manually commit proto.lock files

- Jenkinsfile-release
- commons/proto.lock
- core/proto.lock
- counter/proto.lock
- jcache/embedded/proto.lock
- lucene/lucene-directory/proto.lock
- multimap/proto.lock
- persistence/rocksdb/proto.lock
- query/pom.xml
- query/proto.lock
- remote-query/remote-query-server/proto.lock
- server/core/proto.lock
- server/memcached/proto.lock
- server/runtime/proto.lock
- tasks/scripting/proto.lock
https://issues.jboss.org/browse/ISPN-10856
> [10.0.x] Manually commit proto.lock files

- core/src/main/java/org/infinispan/configuration/format/PropertyFormatter.java
* should not attempt to access static or non-public methods and should
mark them accessible to prevent eventual cross-module accessibility
checks from failing
https://issues.jboss.org/browse/ISPN-10863
> ISPN-10863 java.lang.IllegalAccessException logged by PropertyFormatter

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10872
> ISPN-10872 Update rxjava2 to 2.2.12

- pom.xml
https://issues.jboss.org/browse/ISPN-10871
> ISPN-10871 Add org.aesh:readline to dependency management

- core/src/main/java/org/infinispan/configuration/global/TransportConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-10878
> ISPN-10878 TransportConfigurationBuilder.read(...) does not propagate properties

- wildfly/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-10866-10.0.x
> [10.0.x] ISPN-10866 Force Infinispan Wildfly extension to use jboss marshalling

- component-annotations/src/main/java/org/infinispan/jmx/annotations/DataType.java
- component-processor/src/main/java/org/infinispan/component/processor/Generator.java
- core/src/main/java/org/infinispan/eviction/impl/ActivationManagerImpl.java
- core/src/main/java/org/infinispan/jmx/ResourceDMBean.java
- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/metrics/impl/ApplicationMetricsRegistry.java
https://issues.jboss.org/browse/ISPN-10860
> ISPN-10860 Attributes with DataType.TRAIT are not metrics

- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
https://issues.jboss.org/browse/ISPN-10877
> ISPN-10877 REST API consistency fixes

- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
https://issues.jboss.org/browse/ISPN-10877
> [10.0.x] ISPN-10877 REST API consistency fixes

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/EagerKeyValueConverterTest.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/KeyValueVersionConverter.java
https://issues.jboss.org/browse/ISPN-10876
> ISPN-10876 NPE when using PutMap with listener

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/EagerKeyValueConverterTest.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/KeyValueVersionConverter.java
https://issues.jboss.org/browse/ISPN-10876
> [10.0.x] ISPN-10876 NPE when using PutMap with listener

- component-annotations/src/main/java/org/infinispan/jmx/annotations/DataType.java
- component-processor/src/main/java/org/infinispan/component/processor/Generator.java
- core/src/main/java/org/infinispan/eviction/impl/ActivationManagerImpl.java
- core/src/main/java/org/infinispan/jmx/ResourceDMBean.java
- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/metrics/impl/ApplicationMetricsRegistry.java
https://issues.jboss.org/browse/ISPN-10860
> [10.0.x] ISPN-10860 Attributes with DataType.TRAIT are not metrics

- core/src/main/java/org/infinispan/configuration/format/PropertyFormatter.java
* should not attempt to access static or non-public methods and should
mark them accessible to prevent eventual cross-module accessibility
checks from failing
https://issues.jboss.org/browse/ISPN-10863
> [10.0.x] ISPN-10863 java.lang.IllegalAccessException logged by PropertyFormatter

- core/src/main/java/org/infinispan/xsite/GlobalXSiteAdminOperations.java
https://issues.jboss.org/browse/ISPN-10826
> [9.4.x] ISPN-10826 Fix GlobalXSiteAdminOpsTest failures

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10890
> ISPN-10890 Upgrade to Netty 4.1.43.Final

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-10890
> [10.0.x] ISPN-10890 Upgrade to Netty 4.1.43.Final

- pom.xml
to remove the dependency from server/lib/
https://issues.jboss.org/browse/ISPN-10913
> ISPN-10913 Exclude checker-qual from caffeine dependency

- server/runtime/src/test/java/org/infinispan/server/functional/HotRodMultiMapOperations.java
https://issues.jboss.org/browse/ISPN-10911
> ISPN-10911 HotRodMultiMapOperations random failures

- commons-test/src/main/java/org/infinispan/commons/test/RunningTestsRegistry.java
- jcache/embedded/src/test/java/org/infinispan/jcache/JCacheConfigurationTest.java
https://issues.jboss.org/browse/ISPN-10880
https://issues.jboss.org/browse/ISPN-10824
Also corrects the test timeout failure names
>  ISPN-10880 JCacheConfigurationTest leaks cache manager 

- core/src/main/java/org/infinispan/configuration/cache/Configurations.java
- core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java
- core/src/main/java/org/infinispan/distribution/ch/impl/KeyPartitionerFactory.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/LocalClusterPublisherManagerImpl.java
https://issues.jboss.org/browse/ISPN-10749
> ISPN-10749 Invalidation mode needs a proper key partitioner

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/test/java/org/infinispan/persistence/PersistenceManagerTest.java
https://issues.jboss.org/browse/ISPN-10822
> ISPN-10822 java.lang.Error: Maximum permit count exceeded

- core/src/test/java/org/infinispan/api/ConditionalOperationsConcurrentOptimisticTest.java
- core/src/test/java/org/infinispan/api/ConditionalOperationsConcurrentPessimisticTest.java
- core/src/test/java/org/infinispan/distribution/DistSyncTx1PCL1FuncTest.java
- core/src/test/java/org/infinispan/distribution/rehash/PessimisticStateTransferLocksTest.java
- core/src/test/java/org/infinispan/distribution/topologyaware/TopologyAwareDistAsyncFuncTest.java
- core/src/test/java/org/infinispan/distribution/topologyaware/TopologyAwareDistSyncUnsafeFuncTest.java
- core/src/test/java/org/infinispan/functional/FunctionalMapTest.java
- core/src/test/java/org/infinispan/functional/FunctionalWriteSkewInMemoryTest.java
- core/src/test/java/org/infinispan/health/impl/ClusterHealthImplTest.java
- core/src/test/java/org/infinispan/persistence/ClusteredTxConditionalCommandPassivationTest.java
- core/src/test/java/org/infinispan/persistence/ClusteredTxConditionalCommandTest.java
- core/src/test/java/org/infinispan/scattered/ScatteredSkipRemoteLookupTest.java
- core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java
- core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
- core/src/test/java/org/infinispan/test/fwk/ChainMethodInterceptor.java
- core/src/test/java/org/infinispan/test/fwk/FakeTestClass.java
- core/src/test/java/org/infinispan/test/fwk/TestFrameworkFailure.java
https://issues.jboss.org/browse/ISPN-10855
> ISPN-10855 MultipleCacheManagersTest factory issues are ignored

- core/src/main/java/org/infinispan/reactive/RxJavaInterop.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
https://issues.jboss.org/browse/ISPN-10896
> ISPN-10309 Convert usages of size to use sizeAsync

- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- core/src/test/java/org/infinispan/xsite/BaseSiteUnreachableTest.java
https://issues.jboss.org/browse/ISPN-10919
> ISPN-10919 Offline Xsite test failures

- core/src/main/java/org/infinispan/remoting/transport/RetryOnFailureXSiteCommand.java
- core/src/test/java/org/infinispan/xsite/AbstractTwoSitesTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/failures/StateTransferLinkFailuresTest.java
https://issues.jboss.org/browse/ISPN-10922
> ISPN-10922 StateTransferLinkFailuresTest random failures

- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
https://issues.jboss.org/browse/ISPN-10920
> [9.4.x] ISPN-10920 SB starter dependencies

- commons/src/main/java/org/infinispan/commons/executors/BlockingThreadPoolExecutorFactory.java
- commons/src/main/java/org/infinispan/commons/executors/ThreadPoolExecutorFactory.java
- core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
* Add check to ensure configured pool factory is non blocking
https://issues.jboss.org/browse/ISPN-10903
https://issues.jboss.org/browse/ISPN-10927
> ISPN-10903 Handle thread pool queue rejection better

- documentation/src/main/asciidoc/user_guide/execute_grid.adoc
- documentation/src/main/asciidoc/user_guide/locked_streams.adoc
- documentation/src/main/asciidoc/user_guide/multimapcache.adoc
- documentation/src/main/asciidoc/user_guide/query.adoc
https://issues.jboss.org/browse/ISPN-10917 Removing TODOs from doc.
> [9.4.x] ISPN-10917 removing TODOs from doc

- documentation/src/main/asciidoc/user_guide/cli.adoc
https://issues.jboss.org/browse/ISPN-10918
> [9.4.x] ISPN-10918 adding CLI session expiration info

- core/src/test/java/org/infinispan/api/ConditionalOperationsConcurrentOptimisticTest.java
- core/src/test/java/org/infinispan/api/ConditionalOperationsConcurrentPessimisticTest.java
- core/src/test/java/org/infinispan/distribution/DistSyncTx1PCL1FuncTest.java
- core/src/test/java/org/infinispan/distribution/topologyaware/TopologyAwareDistAsyncFuncTest.java
- core/src/test/java/org/infinispan/distribution/topologyaware/TopologyAwareDistSyncUnsafeFuncTest.java
- core/src/test/java/org/infinispan/functional/FunctionalWriteSkewInMemoryTest.java
- core/src/test/java/org/infinispan/scattered/ScatteredSkipRemoteLookupTest.java
- core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
https://issues.jboss.org/browse/ISPN-10855
> ISPN-10855 Remove the need for factory() implementations when the base class has it

- core/src/main/java/org/infinispan/reactive/RxJavaInterop.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
* Only request 1 cache size at a time
* Added CompletionStageToSingle interop method
https://issues.jboss.org/browse/ISPN-10896
> ISPN-10896 Convert usages of size to use sizeAsync

- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.jboss.org/browse/ISPN-10934
> ISPN-10934 RESTv2 HEAD on cache name

- server/rest/src/main/java/org/infinispan/rest/configuration/RestServerConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-10949
> ISPN-10949 CORS is not enabled for localhost on port 11222 by default

- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/search/IndexedRestSearchTest.java
https://issues.jboss.org/browse/ISPN-10949
> ISPN-10949 Fix test failures

- core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
https://issues.jboss.org/browse/ISPN-9394
> ISPN-9394 Getting CCE after calling XSiteAdmin.status

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/BaseCounterOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/AddClientListenerOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/FaultTolerantPingOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/PingOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/jmx/RemoteCacheManagerMXBean.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HitsAwareCacheManagersTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SocketTimeoutErrorTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/EventLogListener.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/EventSocketTimeoutTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/AbstractRetryTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/SocketTimeoutFailureRetryTest.java
- core/src/test/java/org/infinispan/test/Exceptions.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- core/src/test/java/org/infinispan/test/ThrowableSupplier.java
https://issues.jboss.org/browse/ISPN-10429
> [9.4] ISPN-10429 Retry Hot Rod operations on socket timeout

- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/test/java/org/infinispan/server/functional/ConcurrentShutdownRestIT.java
- server/runtime/src/test/java/org/infinispan/server/functional/ShutdownRestIT.java
- server/runtime/src/test/java/org/infinispan/server/test/EmbeddedInfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerRule.java
- server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerTestMethodRule.java
https://issues.jboss.org/browse/ISPN-10883
> ISPN-10883 Concurrent server stop

- core/src/main/java/org/infinispan/configuration/global/GlobalConfigurationBuilder.java
https://issues.jboss.org/browse/ISPN-10956
> ISPN-10956 GlobalConfigurationBuilder.addModule() should be idempotent

- core/src/main/java/org/infinispan/reactive/publisher/impl/LocalPublisherManagerImpl.java
https://issues.jboss.org/browse/ISPN-9721
> ISPN-9721 LocalPublisherManagerImpl performs blocking Cache operations

- javadoc/javadoc-all/pom.xml
https://issues.jboss.org/browse/javadoc_scripting_fix
> ISPN-10854 Fix building javadocs

- wildfly/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ThreadPoolBuilder.java
- wildfly/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ThreadPoolBuilderFactory.java
* Just assume async is non blocking for now
https://issues.jboss.org/browse/ISPN-10952
> ISPN-10952 InfinispanExtenionIT fails

- build-configuration/pom.xml
- server/runtime/pom.xml
https://issues.jboss.org/browse/ISPN-10954
> ISPN-10954 Add console dependency to server

- core/src/main/java/org/infinispan/configuration/cache/TakeOfflineConfigurationBuilder.java
- core/src/main/java/org/infinispan/xsite/OfflineStatus.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateProviderImpl.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/OfflineStatusTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/failures/StateTransferLinkFailuresTest.java
- documentation/src/main/asciidoc/topics/cross_site_replication.adoc
https://issues.jboss.org/browse/ISPN-10848
> ISPN-10848 Change site status only after failures

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/ReindexCacheTest.java
- core/src/main/java/org/infinispan/configuration/cache/IndexingConfigurationBuilder.java
- documentation/src/main/asciidoc/topics/rest_api_v2.adoc
- integrationtests/elasticsearch-indexmanager-it/src/test/java/org/infinispan/query/it/ElasticSearchMassIndexingIT.java
- query/pom.xml
- query/src/main/java/org/infinispan/query/MassIndexer.java
- query/src/main/java/org/infinispan/query/impl/ComponentRegistryUtils.java
- query/src/main/java/org/infinispan/query/impl/InfinispanQueryStatisticsInfo.java
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- query/src/main/java/org/infinispan/query/impl/SearchManagerImpl.java
- query/src/main/java/org/infinispan/query/impl/massindex/DistributedExecutorMassIndexer.java
- query/src/main/java/org/infinispan/query/impl/massindex/DistributedMassIndexerLock.java
- query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
- query/src/main/java/org/infinispan/query/impl/massindex/LocalMassIndexerLock.java
- query/src/main/java/org/infinispan/query/impl/massindex/MassIndexLock.java
- query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerAlreadyStartedException.java
- query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerLockFactory.java
- query/src/main/java/org/infinispan/query/logging/Log.java
- query/src/test/java/org/infinispan/query/distributed/DistProgrammaticMassIndexTest.java
- query/src/test/java/org/infinispan/query/distributed/DistributedMassIndexingTest.java
- query/src/test/java/org/infinispan/query/distributed/MassIndexingTest.java
- query/src/test/java/org/infinispan/query/distributed/ReplRamMassIndexingTest.java
- query/src/test/java/org/infinispan/query/distributed/TopologyAwareDistMassIndexingTest.java
- query/src/test/java/org/infinispan/query/jmx/DistributedMassIndexingViaJmxTest.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/logging/Log.java
- server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java
- server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
- wildfly/feature-pack/embedded-query/src/main/resources/modules/org/infinispan/query/slot/module.xml
https://issues.jboss.org/browse/ISPN-10884
:beetle:  plus a required bug fix:
* https://issues.jboss.org/browse/ISPN-10930
:hammer: and the also required MassIndexer changes:
* https://issues.jboss.org/browse/ISPN-10932
* https://issues.jboss.org/browse/ISPN-10933
:bulb:  Suggestion for review: per JIRA
> ISPN-10884 Expose indexing/querying operations and stats for a cache

- commons/src/main/java/org/infinispan/commons/executors/BlockingThreadPoolExecutorFactory.java
- commons/src/main/java/org/infinispan/commons/executors/NonBlockingThread.java
- commons/src/main/java/org/infinispan/commons/executors/NonBlockingThreadFactory.java
- commons/src/main/java/org/infinispan/commons/util/concurrent/BlockingRejectedExecutionHandler.java
- commons/src/main/java/org/infinispan/commons/util/concurrent/NonBlockingRejectedExecutionHandler.java
- core/src/main/java/org/infinispan/configuration/global/BoundedThreadPoolConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/global/CachedThreadPoolConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/global/ScheduledThreadPoolConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/global/ThreadFactoryConfiguration.java
- core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java
- core/src/main/java/org/infinispan/factories/threads/DefaultNonBlockingThreadFactory.java
- core/src/main/java/org/infinispan/factories/threads/DefaultThreadFactory.java
https://issues.jboss.org/browse/ISPN-10950
> ISPN-10950 Add interface to designate a thread is non blocking

- server/rest/src/main/java/org/infinispan/rest/resources/StaticContentResource.java
https://issues.jboss.org/browse/ISPN-10965
> ISPN-10965 StaticFileResource fails to serve symlinked resources

- documentation/src/main/asciidoc/topics/rest_examples/rest_full_cache_detail.json
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
Eviction instead of expiration: https://issues.jboss.org/browse/ISPN-10897
Detail cache: https://issues.jboss.org/browse/ISPN-10971
Display indexing in progress: https://issues.jboss.org/browse/ISPN-10884
Caches are retrieved in order: https://issues.jboss.org/browse/ISPN-10972
> REST corrections

- Jenkinsfile-release
- build-configuration/bom/pom.xml
- build-configuration/pom.xml
- documentation/pom.xml
- pom.xml
- server/runtime/pom.xml
https://issues.jboss.org/browse/ISPN-10978
Also, removed some unused properties (no longer used downstream).
> ISPN-10978 Fix infinispan-console-ng dependency

- server/runtime/src/test/java/org/infinispan/server/configuration/JsonSerializationTest.java
https://issues.jboss.org/browse/ISPN-10967
> ISPN-10967 CORS rules for localhost don't take offset into account

- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
- server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
https://issues.jboss.org/browse/ISPN-11009
> ISPN-11009 Server parameter to specify custom logging configuration

- client/rest-client/src/main/java/org/infinispan/client/rest/RestRawClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestRawClientOkHttp.java
- server/rest/src/main/java/org/infinispan/rest/NettyRestResponse.java
- server/rest/src/main/java/org/infinispan/rest/framework/impl/RestResponseBuilder.java
- server/rest/src/main/java/org/infinispan/rest/framework/impl/SimpleRestResponse.java
- server/rest/src/main/java/org/infinispan/rest/resources/SplashResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/StaticContentResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/StaticResourceTest.java
- server/rest/src/test/resources/static-test/console/index.html
- server/runtime/src/test/java/org/infinispan/server/security/authentication/RestAuthentication.java
https://issues.jboss.org/browse/ISPN-10988
https://issues.jboss.org/browse/ISPN-10986
> Console redirection and disabling auth for static resources

- pom.xml
https://issues.jboss.org/browse/ISPN-10982
> ISPN-10982 Update commons-compress to 1.19

- documentation/src/main/asciidoc/topics/ref_rest_cors.adoc
https://issues.jboss.org/browse/ISPN-10993
> ISPN-10993 Rest CORS documentation table missing allowed-headers

- documentation/pom.xml
- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/config_examples/clustered_counters_config.xml
- documentation/src/main/asciidoc/topics/config_examples/clustered_lock_manager.xml
- documentation/src/main/asciidoc/topics/config_examples/ispn_datasource.xml
- documentation/src/main/asciidoc/topics/config_examples/ispn_subsystem.xml
- documentation/src/main/asciidoc/topics/config_examples/ispn_subsystem_endpoint.xml
- documentation/src/main/asciidoc/topics/config_examples/jgroups_subsystem.xml
- documentation/src/main/asciidoc/topics/config_examples/persistence_example_ds_jndi.xml
- documentation/src/main/asciidoc/topics/config_examples/persistence_example_jdbc.xml
- documentation/src/main/asciidoc/topics/config_examples/persistence_jpa_store.xml
- documentation/src/main/asciidoc/topics/config_examples/persistence_remote_store.xml
- documentation/src/main/asciidoc/topics/config_examples/persistence_rocksdb_example.xml
- documentation/src/main/asciidoc/topics/config_examples/persistence_soft_index_file_store.xml
- documentation/src/main/asciidoc/topics/config_examples/wfly_endpoints.xml
- documentation/src/main/asciidoc/topics/config_examples/wfly_jgroups.xml
- documentation/src/main/asciidoc/topics/config_examples/wfly_subsystem.xml
https://issues.jboss.org/browse/ISPN-11002
https://issues.jboss.org/browse/ISPN-11003
> XML Example fixes

- cli/cli-client/src/main/resources/help/quit.adoc
- cli/cli-client/src/main/resources/help/remove.adoc
- cli/cli-client/src/main/resources/help/task.adoc
- cli/cli-client/src/main/resources/help/version.adoc
- documentation/src/main/asciidoc/stories/assembly_cli_command_reference.adoc
https://issues.jboss.org/browse/ISPN-11016
> ISPN-11016 cli help ref fixes

- documentation/src/main/asciidoc/stories/assembly_server_monitoring.adoc
- documentation/src/main/asciidoc/topics/jmx_prometheus.adoc
https://issues.jboss.org/browse/ISPN-10999
> ISPN-10999 remove out of date jmx prometheus doc

- documentation/src/main/asciidoc/titles/rest/stories.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- documentation/src/main/asciidoc/topics/ref_rest_client_http.adoc
- documentation/src/main/asciidoc/topics/ref_rest_client_java.adoc
- documentation/src/main/asciidoc/topics/ref_rest_data_formats.adoc
- documentation/src/main/asciidoc/topics/ref_rest_security.adoc
https://issues.jboss.org/browse/ISPN-10997
> ISPN-10997 minor fixes for rest doc productization

- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
https://issues.jboss.org/browse/ISPN-10990
> ISPN-10990 Log certain server-side Hot Rod warnings only once

- pom.xml
- server/runtime/src/test/java/org/infinispan/server/test/KeyCloakServerRule.java
https://issues.jboss.org/browse/ISPN-11019
> ISPN-11019 Test against KeyCloak 8.0.1

- build-configuration/bom/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-11028
> ISPN-11028 Add org.infinispan:infinispan-spring5-common to infinispan-bom

- build-configuration/bom/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-11028
> [9.4.x] ISPN-11028 Add org.infinispan:infinispan-spring5-common to infinispan-bom

- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ObjectRemoteQueryManager.java
- server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
https://issues.jboss.org/browse/ISPN-11023
> ISPN-11023 Indexless query fails with missing component in the registry

- server/rest/src/main/java/org/infinispan/rest/ALPNHandler.java
- server/rest/src/main/java/org/infinispan/rest/configuration/CorsConfiguration.java
https://issues.jboss.org/browse/ISPN-11030
> ISPN-11030 ConcurrentModificationException in CorsHandler

- documentation/src/main/asciidoc/topics/config_examples/deserialization_whitelist.xml
- documentation/src/main/asciidoc/topics/marshalling.adoc
https://issues.redhat.com/browse/ISPN-9381
> ISPN-9381 Document server whitelist configuration

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java
https://issues.redhat.com/browse/ISPN-11044
> ISPN-11044 Log the connection address in case of SocketTimeoutException

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java
https://issues.redhat.com/browse/ISPN-11044
> [9.4] ISPN-11044 Log the connection address in case of SocketTimeoutException

- documentation/src/main/asciidoc/server_guide/management.adoc
https://issues.jboss.org/browse/ISPN-10999
> [9.4.x] Backport for ISPN-10999 removing reference to Jolokia from product docs

- api/src/main/java/org/infinispan/api/Experimental.java
- build-configuration/pom.xml
- commons/src/main/java/org/infinispan/commons/jmx/MBeanServerLookup.java
- commons/src/main/java/org/infinispan/commons/jmx/package-info.java
- commons/src/main/java/org/infinispan/commons/util/Experimental.java
- component-annotations/src/main/java/org/infinispan/jmx/annotations/MBean.java
- component-annotations/src/main/java/org/infinispan/jmx/annotations/ManagedAttribute.java
- component-annotations/src/main/java/org/infinispan/jmx/annotations/ManagedOperation.java
- component-annotations/src/main/java/org/infinispan/jmx/annotations/Parameter.java
- component-processor/src/main/java/org/infinispan/component/processor/Generator.java
- core/src/main/java/org/infinispan/CoreModule.java
- core/src/main/java/org/infinispan/jmx/MBeanServerLookup.java
- core/src/main/java/org/infinispan/security/mappers/CommonNameRoleMapper.java
- core/src/main/java/org/infinispan/security/mappers/IdentityRoleMapper.java
- javadoc/javadoc-all/pom.xml
https://issues.redhat.com/browse/ISPN-11043
> Exclude non-API elements from javadoc

- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/memcached/pom.xml
- server/memcached/src/main/java/org/infinispan/server/memcached/LifecycleCallbacks.java
- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoder.java
- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoderState.java
- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedMetadata.java
- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedOperation.java
- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedServer.java
- server/memcached/src/main/java/org/infinispan/server/memcached/PersistenceContextInitializer.java
- server/memcached/src/main/java/org/infinispan/server/memcached/TextProtocolUtil.java
- server/memcached/src/main/java/org/infinispan/server/memcached/configuration/MemcachedServerConfiguration.java
- server/memcached/src/main/java/org/infinispan/server/memcached/configuration/MemcachedServerConfigurationBuilder.java
- server/memcached/src/main/java/org/infinispan/server/memcached/configuration/package-info.java
- server/memcached/src/main/java/org/infinispan/server/memcached/logging/Log.java
- server/runtime/src/main/server/server/conf/infinispan.xml
https://issues.redhat.com/browse/ISPN-11047
> ISPN-11047 Deprecate the memcached protocol server

- server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
- server/runtime/src/main/java/org/infinispan/server/security/UserTool.java
https://issues.redhat.com/browse/ISPN-11037
> ISPN-11037 UserTool: Ask for password confirmation

- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
https://issues.jboss.org/browse/ISPN-10990
> [9.4] ISPN-10990 Log certain server-side Hot Rod warnings only once

- build-configuration/pom.xml
- documentation/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-10977
Also fixes the base.version (ISPN-10870)
> ISPN-10977 AsciiDoctor/J 2.1.0

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
SitesView attribute is empty or shows an incomplete view of members
https://issues.jboss.org/browse/ISPN-10980
> [9.4.x] ISPN-10980 Incorrect cross-site view

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-11051
> ISPN-11051 Upgrade to protostream-4.3.1.Final

- component-annotations/src/main/java/org/infinispan/jmx/annotations/DataType.java
- component-annotations/src/main/java/org/infinispan/jmx/annotations/ManagedAttribute.java
- component-annotations/src/main/java/org/infinispan/jmx/annotations/Units.java
- component-processor/src/main/java/org/infinispan/component/processor/ComponentAnnotationProcessor.java
- component-processor/src/main/java/org/infinispan/component/processor/Generator.java
- component-processor/src/main/java/org/infinispan/component/processor/Model.java
- core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingAdvancedCache.java
- core/src/main/java/org/infinispan/eviction/impl/ActivationManagerImpl.java
- core/src/main/java/org/infinispan/factories/impl/MBeanMetadata.java
- core/src/main/java/org/infinispan/health/impl/jmx/HealthJMXExposerImpl.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheMgmtInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheWriterInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/JmxStatsCommandInterceptor.java
- core/src/main/java/org/infinispan/jmx/ResourceDMBean.java
- core/src/main/java/org/infinispan/metrics/impl/ApplicationMetricsRegistry.java
- core/src/main/java/org/infinispan/metrics/impl/ObjectNameMapper.java
- core/src/main/java/org/infinispan/stats/impl/StatsCollector.java
- core/src/test/java/org/infinispan/stress/MemoryCleanupTest.java
- query/src/main/java/org/infinispan/query/impl/InfinispanQueryStatisticsInfo.java
- query/src/test/java/org/infinispan/query/backend/MultipleEntitiesTest.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/main/java/org/infinispan/rest/resources/MetricsResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java
- server/runtime/src/test/java/org/infinispan/server/functional/RestMetricsResource.java
* Histogram and Timer microprofile stats
https://issues.jboss.org/browse/ISPN-9660
Support for ```@ManagedAttribute``` on fields is gone. A getter will continue to do the magic.
> ISPN-9660 Histogram stats

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.jboss.org/browse/ISPN-10906
> ISPN-10906 JGroupsTransport instance reuse

- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
https://issues.jboss.org/browse/ISPN-11023
Also include the node name in the server name (and in the thread names)
> ISPN-11023 Remove random in BaseRestServerTest

- core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
https://issues.redhat.com/browse/ISPN-10975
> ISPN-10975 Transactional cache will slow down the expiration reaper

- core/src/test/java/org/infinispan/tx/TransactionsSpanningReplicatedCachesTest.java
https://issues.redhat.com/browse/ISPN-11077
> ISPN-11077 TransactionsSpanningReplicatedCachesTest.testReadOnlyTransaction random failures

- build-configuration/pom.xml
- core/src/test/resources/configs/xsite/bridge.xml
- core/src/test/resources/configs/xsite/xsite-inline-test.xml
- core/src/test/resources/stacks/tcp.xml
- core/src/test/resources/stacks/udp.xml
- hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
- tools/src/test/resources/udp.xml
https://issues.redhat.com/browse/ISPN-11058
> ISPN-11058 Upgrade to JGroups 4.1.8.Final

- server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/test/EmbeddedInfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11091
> ISPN-11091 Add feature to read server logs from ContainerInfinispanServerDriver

- documentation/src/main/asciidoc/topics/json_examples/rest_caches_info_response.json
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
https://issues.redhat.com/browse/ISPN-11080
> ISPN-11080 Remove size and add Health

- commons/src/main/java/org/infinispan/commons/util/Util.java
https://issues.redhat.com/browse/ISPN-11054
> ISPN-11054 Fail if we cannot recursively delete a directory during tests

- documentation/src/main/asciidoc/topics/query.adoc
- query-dsl/src/main/java/org/infinispan/query/dsl/Expression.java
- query-dsl/src/main/java/org/infinispan/query/dsl/FilterConditionBeginContext.java
- query-dsl/src/main/java/org/infinispan/query/dsl/FilterConditionContext.java
- query-dsl/src/main/java/org/infinispan/query/dsl/FilterConditionContextQueryBuilder.java
- query-dsl/src/main/java/org/infinispan/query/dsl/FilterConditionEndContext.java
- query-dsl/src/main/java/org/infinispan/query/dsl/IndexedQueryMode.java
- query-dsl/src/main/java/org/infinispan/query/dsl/PaginationContext.java
- query-dsl/src/main/java/org/infinispan/query/dsl/ParameterContext.java
- query-dsl/src/main/java/org/infinispan/query/dsl/Query.java
- query-dsl/src/main/java/org/infinispan/query/dsl/QueryBuilder.java
- query-dsl/src/main/java/org/infinispan/query/dsl/QueryFactory.java
- query-dsl/src/main/java/org/infinispan/query/dsl/RangeConditionContext.java
- query-dsl/src/main/java/org/infinispan/query/dsl/RangeConditionContextQueryBuilder.java
- query-dsl/src/main/java/org/infinispan/query/dsl/SortOrder.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/BaseQuery.java
- query-dsl/src/main/java/org/infinispan/query/dsl/impl/package-info.java
- query-dsl/src/main/java/org/infinispan/query/dsl/package-info.java
- query-dsl/src/test/java/org/infinispan/query/dsl/impl/DummyQuery.java
https://issues.redhat.com/browse/ISPN-11066
> ISPN-11066 Deprecate QueryBuilder DSL

- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManagerAdmin.java
- core/src/main/java/org/infinispan/manager/EmbeddedCacheManagerAdmin.java
- core/src/main/java/org/infinispan/security/impl/AuthorizationHelper.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/runtime/src/test/java/org/infinispan/server/security/AuthorizationLDAPIT.java
https://issues.redhat.com/browse/ISPN-11070
> ISPN-11070 Use REST Subject to perform cache admin ops

- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/resources/StaticContentResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/StaticResourceTest.java
https://issues.redhat.com/browse/ISPN-11049
> ISPN-11049 the console is able to resolve console urls

- core/src/main/java/org/infinispan/configuration/global/SerializationConfiguration.java
- core/src/main/java/org/infinispan/configuration/global/SerializationConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.jboss.org/browse/ISPN-11055
> ISPN-11055 Deprecate SerializatinConfiguration Version

- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
https://issues.redhat.com/browse/ISPN-11104
> [9.4.x] ISPN-11104 SB Starter doc

- documentation/src/main/asciidoc/user_guide/clustering.adoc
https://issues.redhat.com/browse/ISPN-11105
> [9.4.x] ISPN-11105 scattered cache community only

- core/src/main/java/org/infinispan/commands/CommandsFactory.java
- core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
- core/src/main/java/org/infinispan/commands/RemoteCommandsFactory.java
- core/src/main/java/org/infinispan/commands/remote/CheckTransactionRpcCommand.java
- core/src/main/java/org/infinispan/marshall/exts/CacheRpcCommandExternalizer.java
- core/src/main/java/org/infinispan/transaction/impl/TransactionTable.java
- core/src/test/java/org/infinispan/tx/NoLockLostOnLongTxTest.java
- core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
- extended-statistics/src/main/java/org/infinispan/extendedstats/wrappers/ExtendedStatisticRpcManager.java
https://issues.jboss.org/browse/ISPN-10367
> ISPN-10367 Possible lock lost if a transaction reaches timeout

- build-configuration/pom.xml
I've just released 0.1.Beta2
Unless something blocking is found, this is the release version for now
> Release Console 0.1.Beta2

- server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/test/CountdownLatchLoggingConsumer.java
https://issues.redhat.com/browse/ISPN-11094
> ISPN-11094 Allow custom container server startup timeout

- server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/test/KeyCloakServerRule.java
https://issues.redhat.com/browse/ISPN-11083
> ISPN-11083 Replace TestContainers::withFileSystemBind with withCopyFileToContainer

- javadoc/javadoc-all/pom.xml
* Fix javadoc build
https://issues.redhat.com/browse/ISPN-10803
> ISPN-10803 Use WildFly OpenSSL - Fix Javadoc

- documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
- documentation/src/main/asciidoc/user_guide/user_guide.asciidoc
https://issues.redhat.com/browse/ISPN-10784
> [9.4.x] ISPN-10784 xsite updates for 9.4.x concurrent writes

- core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
https://issues.jboss.org/browse/ISPN-11101
> ISPN-11101 Purge on JDBC shared stores can cause deadlocks

- build-configuration/pom.xml
> Infinispan Console 0.1.Final

- build-configuration/pom.xml
> 10.1 codename "Turia"

- core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
https://issues.jboss.org/browse/ISPN-11101
> [9.4.x] ISPN-11101 Purge on JDBC shared stores can cause deadlocks

- server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11078
> ISPN-11078 - Accept external server file configuration on InfinispanServerRuleBuilder

- core/src/main/java/org/infinispan/commands/write/InvalidateCommand.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/test/java/org/infinispan/invalidation/WriteStoreInvalidationTest.java
https://issues.redhat.com/browse/ISPN-11116
> ISPN-11116 Invalidation commands should not load the previous value

- core/src/main/java/org/infinispan/commands/write/InvalidateCommand.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/test/java/org/infinispan/invalidation/WriteStoreInvalidationTest.java
https://issues.redhat.com/browse/ISPN-11116
> [9.3.x] ISPN-11116 Invalidation commands should not load the previous value

- core/src/main/java/org/infinispan/commands/write/InvalidateCommand.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/test/java/org/infinispan/invalidation/WriteStoreInvalidationTest.java
https://issues.redhat.com/browse/ISPN-11116
> [9.4.x] ISPN-11116 Invalidation commands should not load the previous value

- core/src/main/java/org/infinispan/util/logging/Log.java
Indexing work was moved to ISPN 11
> ISPN000403 use outdated release for deprecation warning

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11134
> [9.4.x] ISPN-11134 Upgrade Jackson to version 2.9.10

- core/src/main/java/org/infinispan/AdvancedCache.java
- core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingAdvancedCache.java
- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/main/java/org/infinispan/cache/impl/DecoratedCache.java
- core/src/main/java/org/infinispan/cache/impl/EncoderCache.java
- core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
- core/src/main/java/org/infinispan/container/DataContainer.java
- core/src/main/java/org/infinispan/container/impl/EntryFactory.java
- core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java
- core/src/main/java/org/infinispan/container/impl/InternalDataContainer.java
- core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
- core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java
- core/src/main/java/org/infinispan/expiration/impl/InternalExpirationManager.java
- core/src/main/java/org/infinispan/expiration/impl/TxClusterExpirationManager.java
- core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
- core/src/main/java/org/infinispan/interceptors/distribution/L1NonTxInterceptor.java
- core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/BiasedEntryWrappingInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/RetryingEntryWrappingInterceptor.java
- core/src/main/java/org/infinispan/interceptors/locking/ClusteringDependentLogic.java
- core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java
- core/src/test/java/org/infinispan/api/ConditionalOperationPrimaryOwnerFailTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreDistListenerFunctionalTest.java
- core/src/test/java/org/infinispan/functional/decorators/FunctionalAdvancedCache.java
- core/src/test/java/org/infinispan/stress/DataContainerStressTest.java
https://issues.redhat.com/browse/ISPN-11112
> ISPN-11112 Make expiration non blocking

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/server/server/conf/infinispan.xml
https://issues.redhat.com/browse/ISPN-11133
> ISPN-11133 Pass server -n and -b arguments to the transport

- core/src/test/java/org/infinispan/partitionhandling/BasePartitionHandlingTest.java
https://issues.redhat.com/browse/ISPN-11113
Reset cluster name in LOCAL_PING before stopping
> ISPN-11113 ScatteredDelayedAvailabilityUpdateTest takes too long

- jcache/embedded/src/main/java/org/infinispan/jcache/embedded/JCache.java
https://issues.redhat.com/browse/ISPN-10981
> ISPN-10981 Fix JCache.removeAll regression

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedNearCacheTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/MockNearCacheService.java
- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
https://issues.redhat.com/browse/ISPN-10369
> ISPN-10369 InvalidatedNearCacheTest random failures

- cli/cli-client/src/main/java/org/infinispan/cli/impl/ContextImpl.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestClientOkHttp.java
- commons/src/main/java/org/infinispan/commons/util/Util.java
- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
- server/runtime/src/main/server/bin/cli.bat
- server/runtime/src/main/server/bin/cli.log4j2.xml
- server/runtime/src/main/server/bin/cli.sh
https://issues.redhat.com/browse/ISPN-11148 CLI: close all connections to the server to prevent hang
https://issues.redhat.com/browse/ISPN-11149 CLI logging file
https://issues.redhat.com/browse/ISPN-11150 Show server URL on boot
> ISPN-11148 + ISPN-11149 + ISPN-11150 CLI hang fix / CLI logging

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/SocketTimeoutFailureRetryTest.java
https://issues.redhat.com/browse/ISPN-11166
Avoid repl get optimization to hit the DelayInterceptor
> ISPN 11166 SocketTimeoutFailureRetryTest random failures

- core/src/main/java/org/infinispan/configuration/parsing/ParserRegistry.java
- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.redhat.com/browse/ISPN-11175
> ISPN-11175 Improve Log::unsupportedConfiguration method adding that a missing dependency can cause the issue

- core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
- core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java
- core/src/main/java/org/infinispan/expiration/impl/InternalExpirationManager.java
- core/src/main/java/org/infinispan/expiration/impl/TouchCommand.java
https://issues.redhat.com/browse/ISPN-11163
> ISPN-11163 Max Idle 2 addditional review comments

- documentation/src/main/asciidoc/user_guide/persistence_jdbc.adoc
https://issues.redhat.com/browse/ISPN-11169
> [9.4.x] jdbc string based config examples

- core/src/main/java/org/infinispan/commands/tx/PrepareCommand.java
- core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
- core/src/main/java/org/infinispan/interceptors/locking/OptimisticLockingInterceptor.java
https://issues.redhat.com/browse/ISPN-11020
https://issues.redhat.com/browse/ISPN-11157
> ISPN-11020 Max Idle Test Fix

- core/src/main/java/org/infinispan/eviction/impl/PassivationManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.redhat.com/browse/ISPN-5904
> ISPN-5904 Downgrade passivation messages to DEBUG 

- wildfly/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerConfigurationBuilder.java
https://issues.redhat.com/browse/ISPN-10310
Fixes failure in InfinispanExtensionIT
> [10.1] ISPN-10310 Drop state transfer pool from the infinispan WF subsystem

- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/resources/StaticContentResource.java
https://issues.redhat.com/browse/ISPN-11203
> ISPN-11203 StaticContentResource should not contain console logic

- documentation/src/main/asciidoc/user_guide/eviction.adoc
https://issues.redhat.com/browse/ISPN-11164
> [9.4.x] Backport ISPN-1164 clustered max idle

- documentation/src/main/asciidoc/user_guide/clustering.adoc
https://issues.redhat.com/browse/ISPN-11196
> [9.4.x] ISPN-11196 capacity factor doc update

- documentation/src/main/asciidoc/topics/security_server.adoc
- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
- server/runtime/src/main/java/org/infinispan/server/security/UserTool.java
- server/runtime/src/main/server/server/conf/infinispan-local.xml
- server/runtime/src/main/server/server/conf/infinispan-xsite.xml
- server/runtime/src/main/server/server/conf/infinispan.xml
- server/runtime/src/test/java/org/infinispan/server/usertool/UserToolTest.java
https://issues.redhat.com/browse/ISPN-11224
Also adds support for both plain and pre-digested passwords to the user tool and update the upgrading and server security guides.
> ISPN-11224 Add plain-text="true" to the default property realms

- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-11220
> ISPN-11220 Server can leak protocol servers

- documentation/src/main/asciidoc/topics/ref_endpoints_comparison.adoc
matrix show that HotRod not support transactions, this is wrong
> HotRod client support transactions, changing the Protocol Comparison table

- server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodClient.java
https://issues.redhat.com/browse/ISPN-11242
> ISPN-11242 HotRod server test client sends invalid iteration start request

- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/DefaultIterationManager.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodIteratorReapTest.java
https://issues.redhat.com/browse/ISPN-11244
> ISPN-11244 HotRodIteratorReapTest random failures

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11213 Jackson 2.10.2
https://issues.redhat.com/browse/ISPN-11214 Agroal 1.7
https://issues.redhat.com/browse/ISPN-11215 OkHttp 3.14.6
https://issues.redhat.com/browse/ISPN-11216 JUnit 4.13
https://issues.redhat.com/browse/ISPN-11217 Elytron 1.11.0.Final
> ISPN-11213 ISPN-11214 ISPN-11215 ISPN-11216 ISPN-11217 Upgrades

- integrationtests/wildfly-modules/src/test/java/org/infinispan/test/integration/as/cdi/DuplicatedDomainsCdiIT.java
https://issues.redhat.com/browse/ISPN-11168
> ISPN-11168 Use manifest dependencies in DuplicatedDomainsCdiIT

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11190
> [9.4.x] ISPN-11190 Upgrade to JGroups 4.0.21.Final

- core/src/main/java/org/infinispan/remoting/LocalInvocation.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
- core/src/main/java/org/infinispan/util/concurrent/ActionSequencer.java
- core/src/main/java/org/infinispan/util/concurrent/CompletableFutures.java
- core/src/main/java/org/infinispan/xsite/BackupReceiver.java
- core/src/main/java/org/infinispan/xsite/BaseBackupReceiver.java
- core/src/main/java/org/infinispan/xsite/ClusteredCacheBackupReceiver.java
- core/src/main/java/org/infinispan/xsite/LocalCacheBackupReceiver.java
- core/src/main/java/org/infinispan/xsite/SingleXSiteRpcCommand.java
- core/src/main/java/org/infinispan/xsite/XSiteReplicateCommand.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStatePushCommand.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferControlCommand.java
- core/src/test/java/org/infinispan/jmx/PerCacheInboundHandlerMBeanTest.java
- core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java
- core/src/test/java/org/infinispan/util/ActionSequencerUnitTest.java
- core/src/test/java/org/infinispan/xsite/BackupReceiverDelegator.java
- core/src/test/java/org/infinispan/xsite/RollbackNoPrepareOptimisticTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/failures/RetryMechanismTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/failures/SiteConsumerTopologyChangeTest.java
* distinct keys can be applied in parallel
https://issues.redhat.com/browse/ISPN-10657
> [9.4.x] ISPN-10657 Handle async-xsite in parallel

- server/hotrod/src/main/resources/hotrod.gr
https://issues.redhat.com/browse/ISPN-11253
> ISPN-11253 Add task name to hotrod server log

- server/hotrod/src/main/resources/hotrod.gr
https://issues.redhat.com/browse/ISPN-11253
> ISPN-11253 Add task name to hotrod access log

- documentation/src/main/asciidoc/topics/marshalling.adoc
https://issues.redhat.com/browse/ISPN-10836
> ISPN-10836 deserialization whitelist per cache manager

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-11258
@pruivo would backporting this to 10.1.x cause any issues for you?
> ISPN-11258 Proto Compatibility check should not fail on unknown OS

- build-configuration/pom.xml
https://issues.jboss.org/browse/ISPN-11258
> [10.1.x] ISPN-11258 Proto Compatibility check should not fail on unknown OS

- core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java
- core/src/main/java/org/infinispan/container/impl/TouchableMap.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactory.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactoryImpl.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapMemory.java
- core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
- core/src/main/java/org/infinispan/expiration/impl/TouchCommand.java
- core/src/main/java/org/infinispan/remoting/transport/ResponseCollector.java
- core/src/main/java/org/infinispan/remoting/transport/impl/MultiTargetRequest.java
- core/src/test/java/org/infinispan/eviction/impl/ExceptionEvictionTest.java
- core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
https://issues.redhat.com/browse/ISPN-9082
https://issues.redhat.com/browse/ISPN-11204
> ISPN-9082 Off Heap max idle

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/AbstractHotRodSiteFailoverTest.java
- core/src/main/java/org/infinispan/configuration/global/SiteConfiguration.java
- core/src/main/java/org/infinispan/configuration/global/SiteConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/remoting/transport/AbstractDelegatingTransport.java
- core/src/main/java/org/infinispan/remoting/transport/Transport.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java
- core/src/test/java/org/infinispan/remoting/transport/MockTransport.java
- core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
- core/src/test/java/org/infinispan/test/fwk/TransportFlags.java
- core/src/test/java/org/infinispan/xsite/AbstractMultipleSitesTest.java
- core/src/test/java/org/infinispan/xsite/AbstractTwoSitesTest.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- core/src/test/java/org/infinispan/xsite/BackupForConfigTest.java
- core/src/test/java/org/infinispan/xsite/BackupForNotSpecifiedTest.java
- core/src/test/java/org/infinispan/xsite/BaseSiteUnreachableTest.java
- core/src/test/java/org/infinispan/xsite/XSiteFileParsing2Test.java
- core/src/test/java/org/infinispan/xsite/XSiteFileParsing3Test.java
- core/src/test/java/org/infinispan/xsite/XSiteFileParsingTest.java
- core/src/test/java/org/infinispan/xsite/XSiteInlineConfigFileParsingTest.java
- core/src/test/java/org/infinispan/xsite/XSiteStateTransferFileParsingTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/LocalCacheStateTransferTest.java
- wildfly/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerConfigurationBuilder.java
https://issues.redhat.com/browse/ISPN-11278
> ISPN-11278 Deprecate SiteConfiguration

- cli/cli-client/src/main/java/org/infinispan/cli/commands/Create.java
- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
https://issues.redhat.com/browse/ISPN-11247
> ISPN-11247 Fix permanent cache creation via CLI and make default

- cli/cli-client/src/main/java/org/infinispan/cli/commands/Create.java
- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
https://issues.redhat.com/browse/ISPN-11247
> [10.1] ISPN-11247 Fix permanent cache creation via CLI and make default

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/AbstractHotRodSiteFailoverTest.java
- core/src/main/java/org/infinispan/configuration/global/SiteConfiguration.java
- core/src/main/java/org/infinispan/configuration/global/SiteConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/remoting/transport/AbstractDelegatingTransport.java
- core/src/main/java/org/infinispan/remoting/transport/Transport.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java
- core/src/test/java/org/infinispan/remoting/transport/MockTransport.java
- core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
- core/src/test/java/org/infinispan/test/fwk/TransportFlags.java
- core/src/test/java/org/infinispan/xsite/AbstractMultipleSitesTest.java
- core/src/test/java/org/infinispan/xsite/AbstractTwoSitesTest.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- core/src/test/java/org/infinispan/xsite/BackupForConfigTest.java
- core/src/test/java/org/infinispan/xsite/BackupForNotSpecifiedTest.java
- core/src/test/java/org/infinispan/xsite/BaseSiteUnreachableTest.java
- core/src/test/java/org/infinispan/xsite/XSiteFileParsing2Test.java
- core/src/test/java/org/infinispan/xsite/XSiteFileParsing3Test.java
- core/src/test/java/org/infinispan/xsite/XSiteFileParsingTest.java
- core/src/test/java/org/infinispan/xsite/XSiteInlineConfigFileParsingTest.java
- core/src/test/java/org/infinispan/xsite/XSiteStateTransferFileParsingTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/LocalCacheStateTransferTest.java
- wildfly/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerConfigurationBuilder.java
https://issues.redhat.com/browse/ISPN-11278
> [10.1.x] ISPN-11278 Deprecate SiteConfiguration

- server/hotrod/src/main/resources/hotrod.gr
https://issues.redhat.com/browse/ISPN-11253
> [10.1] ISPN-11253 Add task name to hotrod access log

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/EpollAvailabilityTest.java
- commons-test/src/main/java/org/infinispan/commons/test/skip/OS.java
- commons-test/src/main/java/org/infinispan/commons/test/skip/SkipJunit.java
- commons-test/src/main/java/org/infinispan/commons/test/skip/SkipTestNG.java
https://issues.redhat.com/browse/ISPN-11283
> ISPN-11283 Only run the epoll availability test on Linux

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/EpollAvailabilityTest.java
- commons-test/src/main/java/org/infinispan/commons/test/skip/OS.java
- commons-test/src/main/java/org/infinispan/commons/test/skip/SkipJunit.java
- commons-test/src/main/java/org/infinispan/commons/test/skip/SkipTestNG.java
https://issues.redhat.com/browse/ISPN-11283
> [10.1] ISPN-11283 Only run the epoll availability test on Linux

- client/marshaller/kryo/kryo-marshaller-compatibility-bundle/pom.xml
- client/marshaller/protostuff/protostuff-marshaller-compatibility-bundle/pom.xml
- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
- integrationtests/osgi/src/test/java/org/infinispan/it/osgi/util/IspnKarafOptions.java
- integrationtests/spring-boot-it/pom.xml
- jcache/embedded/pom.xml
- jcache/tck-runner-embedded/pom.xml
- jcache/tck-runner-remote/pom.xml
- pom.xml
- server/rest/src/test/java/org/infinispan/rest/helper/RestResponses.java
- server/runtime/pom.xml
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/test/java/org/infinispan/server/functional/IgnoreCaches.java
- server/runtime/src/test/java/org/infinispan/server/functional/RestRouter.java
- server/runtime/src/test/java/org/infinispan/server/functional/ShutdownRestIT.java
- server/runtime/src/test/java/org/infinispan/server/security/AuthorizationLDAPIT.java
- server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerTestMethodRule.java
- server/runtime/src/test/java/org/infinispan/server/test/TestThreadTrackerRule.java
- server/runtime/src/test/java/org/infinispan/server/unit/configuration/ServerConfigurationParserTest.java
- server/runtime/src/test/java/org/infinispan/server/unit/configuration/ServerEventLoggerTest.java
- wildfly/infinispan/pom.xml
https://issues.redhat.com/browse/ISPN-11179
> ISPN-11179 Ignore OkHttp thread leaks and close our responses

- distribution/src/main/release/common/configs/log4j/log4j2.xml
- server/runtime/src/main/server/server/conf/log4j2.xml
https://issues.redhat.com/browse/ISPN-11245
> ISPN-11245 Show full category (class) names for logging

- server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11284
> ISPN-11284 Make the containerized server timeout configurable

- server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11284
Backport of #7835
> [10.1] ISPN-11284 Make the containerized server timeout configurable

- cli/cli-client/src/main/java/org/infinispan/cli/commands/Site.java
- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
- cli/cli-client/src/main/resources/help/site.adoc
https://issues.redhat.com/browse/ISPN-11282
master: https://github.com/infinispan/infinispan/pull/7837
> [10.1.x] ISPN-11282 CLI: site command isn't working properly

- integrationtests/wildfly-modules/src/test/java/org/infinispan/test/integration/as/cdi/DuplicatedDomainsCdiIT.java
https://issues.redhat.com/browse/ISPN-11168
Backport of #7744
> [10.1] ISPN-11168 Use manifest dependencies in DuplicatedDomainsCdiIT

- server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11071
> ISPN-11071 Support container server driver image troubleshooting

- documentation/src/main/asciidoc/topics/con_caches_distribution.adoc
https://issues.redhat.com/browse/ISPN-11219
> ISPN-11219 update capacity factors doc

- documentation/src/main/asciidoc/topics/con_caches_distribution.adoc
https://issues.redhat.com/browse/ISPN-11219
> [10.1.x] ISPN-11219 update capacity factors doc

- distribution/src/main/release/common/configs/log4j/log4j2.xml
- server/runtime/src/main/server/server/conf/log4j2.xml
https://issues.redhat.com/browse/ISPN-11245
> [10.1.x] ISPN-11245 Show full category (class) names for logging

- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
https://issues.redhat.com/browse/ISPN-11294
> ISPN-11294 Prevent 'cd' under a cache

- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
https://issues.redhat.com/browse/ISPN-11294
Backport of #7851
> [10.1] ISPN-11294 Prevent 'cd' under a cache

- pom.xml
- server/runtime/TESTING.md
- server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/test/ServerRunMode.java
- server/runtime/src/test/java/org/infinispan/server/test/TestSystemPropertyNames.java
https://issues.redhat.com/browse/ISPN-11290
To test this run a container test with the following properties
-Dorg.infinispan.test.server.container.usePrebuiltServer=true -Dorg.infinispan.test.server.container.baseImageName=infinispan/server:10.1.1.Final-3
> ISPN-11290 Optionally use a prebuilt server from the supplied container

- core/src/main/java/org/infinispan/conflict/impl/DefaultConflictManager.java
https://issues.redhat.com/browse/ISPN-11291
> ISPN-11291 MultipleCachesDuringConflictResolutionTest.testPartitionMergePolicy

- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
https://issues.redhat.com/browse/ISPN-11275
backport #7864
> ISPN-11275 expose local site name

- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
Backport of https://issues.redhat.com/browse/ISPN-11275
#7822
> [10.1.x] IISPN-11275 expose local site name

- core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
- core/src/test/java/org/infinispan/test/SingleCacheManagerTest.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- persistence/soft-index/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFunctionalTest.java
- persistence/soft-index/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreStressTest.java
- persistence/soft-index/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreTest.java
https://issues.redhat.com/browse/ISPN-11301
> ISPN-11301 SIFS tests should clear /tmp files per method call

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11318
> ISPN-11318 Netty 4.1.45.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11318
> [10.1] ISPN-11318 Netty 4.1.45.Final

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.redhat.com/browse/ISPN-11323
> ISPN-11323 solate JGroupsTransport MBean references to private methods

- core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
- core/src/main/java/org/infinispan/factories/DataContainerFactory.java
- core/src/test/java/org/infinispan/configuration/DataContainerTest.java
- core/src/test/java/org/infinispan/container/offheap/OffHeapMultiNodeTest.java
* Updated missing reference
https://issues.redhat.com/browse/ISPN-11209
> [9.4.x] ISPN-11209 Max Idle changes caused a REPL read performance regression

- all/remote/pom.xml
- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11318
> [9.4] ISPN-11318 Netty 4.1.45.Final

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.redhat.com/browse/ISPN-11209
> [10.1.x] ISPN-11323 Isolate JGroupsTransport MBean references to private methods

- build-configuration/pom.xml
> Upgrade Console to 0.2.Final

- build-configuration/pom.xml
Upgrade to the latest release of the console
> [10.1.x] Upgrade Console to 0.2.Final

- build-configuration/pom.xml
- core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
- wildfly/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/AbstractProtocolConfigurationBuilder.java
- wildfly/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/ProtocolResourceRegistrationHandler.java
https://issues.redhat.com/browse/ISPN-11322
> ISPN-11322 Upgrade JGroups to 4.1.9.Final

- build-configuration/pom.xml
- core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
- wildfly/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/AbstractProtocolConfigurationBuilder.java
- wildfly/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/ProtocolResourceRegistrationHandler.java
https://issues.redhat.com/browse/ISPN-11322
> [10.1.x] ISPN-11322 Upgrade JGroups to 4.1.9.Final

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
https://issues.redhat.com/browse/ISPN-11302
> [10.1.x] ISPN-11302 Add infinispan.client.hotrod.context-initializers property

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/SQLServerTableManager.java
https://issues.redhat.com/browse/ISPN-11004
I'll backport to 10.1.x and 9.4.x once approved.
> ISPN-11004 SQL server exception purging data

- pom.xml
https://issues.redhat.com/browse/ISPN-11340
> ISPN-11340 Upgrade JNA to 5.5.0

- pom.xml
https://issues.redhat.com/browse/ISPN-11340
> [10.1.x] ISPN-11340 Upgrade JNA to 5.5.0

- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
- server/runtime/src/main/java/org/infinispan/server/security/UserTool.java
- server/runtime/src/main/server/server/conf/infinispan-local.xml
- server/runtime/src/main/server/server/conf/infinispan-xsite.xml
- server/runtime/src/main/server/server/conf/infinispan.xml
- server/runtime/src/test/java/org/infinispan/server/usertool/UserToolTest.java
https://issues.redhat.com/browse/ISPN-11224
> [10.1] ISPN-11224 Add plain-text="true" to the default property realms

- server/runtime/src/main/java/org/infinispan/server/tool/Main.java
- server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/usertool/UserToolTest.java
https://issues.redhat.com/browse/ISPN-11342
> ISPN-11342 Use UserTool to genrate test users/groups property files

- server/runtime/src/main/java/org/infinispan/server/tool/Main.java
- server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/usertool/UserToolTest.java
https://issues.redhat.com/browse/ISPN-11342
> [10.1] ISPN-11342 Use UserTool to genrate test users/groups property files

- core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java
- core/src/main/java/org/infinispan/container/impl/BoundedSegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/impl/DefaultDataContainer.java
- core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/impl/L1SegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/impl/PeekableTouchableContainerMap.java
- core/src/main/java/org/infinispan/container/impl/PeekableTouchableMap.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapDataContainer.java
- core/src/main/java/org/infinispan/container/offheap/SegmentedBoundedOffHeapDataContainer.java
- core/src/main/java/org/infinispan/factories/DataContainerFactory.java
- core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
* Make sure to not calculate segment if segmentation is disabled
* Add in interface to prevent additional if/else blocks
https://issues.redhat.com/browse/ISPN-11209
> [10.1.x] ISPN-11209 Max Idle changes caused a REPL read performance regression

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11346
Backport #7900
> ISPN-11346 upgrade console to 0.3.Final

- build-configuration/pom.xml
> [10.1.x] ISPN-11346 upgrade console to 0.3.Final

- client/marshaller/kryo/kryo-marshaller-compatibility-bundle/pom.xml
- client/marshaller/protostuff/protostuff-marshaller-compatibility-bundle/pom.xml
- commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
- integrationtests/osgi/src/test/java/org/infinispan/it/osgi/util/IspnKarafOptions.java
- integrationtests/spring-boot-it/pom.xml
- jcache/embedded/pom.xml
- jcache/tck-runner-embedded/pom.xml
- jcache/tck-runner-remote/pom.xml
- pom.xml
- server/rest/src/test/java/org/infinispan/rest/helper/RestResponses.java
- server/runtime/pom.xml
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/test/java/org/infinispan/server/functional/IgnoreCaches.java
- server/runtime/src/test/java/org/infinispan/server/functional/RestRouter.java
- server/runtime/src/test/java/org/infinispan/server/functional/ShutdownRestIT.java
- server/runtime/src/test/java/org/infinispan/server/security/AuthorizationLDAPIT.java
- server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
- server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerTestMethodRule.java
- server/runtime/src/test/java/org/infinispan/server/test/TestThreadTrackerRule.java
- server/runtime/src/test/java/org/infinispan/server/test/Util.java
- server/runtime/src/test/java/org/infinispan/server/unit/configuration/ServerConfigurationParserTest.java
- server/runtime/src/test/java/org/infinispan/server/unit/configuration/ServerEventLoggerTest.java
- wildfly/infinispan/pom.xml
https://issues.redhat.com/browse/ISPN-11179
Backport of #7784
> [10.1.x] ISPN-11179 Ignore OkHttp thread leaks and close our responses

- documentation/src/main/asciidoc/topics/ref_rest_data_formats.adoc
- persistence/rest/src/main/java/org/infinispan/persistence/rest/RestStore.java
- server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/framework/impl/ResourceManagerImpl.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-11232
> [10.1.x] ISPN-11232 Creating resources via REST should allow names with special chars

- integrationtests/wildfly-modules/src/test/resources/infinispan-custom.xml
https://issues.redhat.com/browse/ISPN-11343
> ISPN-11343 Use LOCAL_PING in server used in WildFly modules IT

- integrationtests/wildfly-modules/src/test/resources/infinispan-custom.xml
https://issues.redhat.com/browse/ISPN-11343
> [10.1] ISPN-11343 Use LOCAL_PING in server used in WildFly modules IT

- documentation/src/main/asciidoc/topics/ref_rest_data_formats.adoc
- persistence/rest/src/main/java/org/infinispan/persistence/rest/RestStore.java
- server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/framework/impl/ResourceManagerImpl.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-11232
> ISPN-11232 Creating resources via REST should allow names with special chars

- core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
- core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
https://issues.redhat.com/browse/ISPN-11297
> ISPN-11297 Prevent creating clustered caches incompatible with global state

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/SQLServerTableManager.java
https://issues.redhat.com/browse/ISPN-11004
> [9.4.x] ISPN-1004 backport fixed to use correct method overriding

- core/src/main/resources/default-configs/default-jgroups-udp.xml
- core/src/test/resources/stacks/udp.xml
- tools/src/test/resources/udp.xml
- wildfly/jgroups/src/main/resources/jgroups-defaults.xml
https://issues.redhat.com/browse/ISPN-11347
> ISPN-11347 Change default TOS for UDP

- core/src/main/resources/default-configs/default-jgroups-udp.xml
- core/src/test/resources/stacks/udp.xml
- tools/src/test/resources/udp.xml
- wildfly/jgroups/src/main/resources/jgroups-defaults.xml
https://issues.redhat.com/browse/ISPN-11347
> [10.1.x] ISPN-11347 Change default TOS for UDP

- core/src/main/resources/default-configs/default-jgroups-udp.xml
- core/src/test/resources/stacks/udp.xml
- demos/gui/src/main/release/etc/config/jgroups-relay1.xml
- demos/gui/src/main/release/etc/config/jgroups-relay2.xml
- server/integration/jgroups/src/main/resources/jgroups-defaults.xml
https://issues.redhat.com/browse/ISPN-11347
> [9.4.x] ISPN-11347 Change default TOS for UDP

- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/FileProvider.java
https://issues.redhat.com/browse/ISPN-11349
> [10.1.x] ISPN-11349 lock leak in SIFS FileProvider

- pom.xml
- server/runtime/pom.xml
- server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11172
> ISPN-11172 Fork 'id' to get uid/gid

- pom.xml
- server/runtime/pom.xml
- server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11172
> [10.1] ISPN-11172 Fork 'id' to get uid/gid

- core/src/main/java/org/infinispan/util/concurrent/ConditionFuture.java
- core/src/test/java/org/infinispan/test/Exceptions.java
- core/src/test/java/org/infinispan/util/concurrent/ConditionFutureTest.java
https://issues.redhat.com/browse/ISPN-11280
Apply #7853 feedback
> ISPN-11280 More ConditionFuture updates

- server/integration/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/JGroupsSubsystemXMLWriter.java
- server/integration/jgroups/src/main/resources/schema/jboss-infinispan-jgroups_9_4.xsd
- server/integration/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-9_4.xml
https://issues.redhat.com/browse/ISPN-11352
> [9.4] ISPN-11352 JGroups Subssytem: persist properties in the relay element

- wildfly/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/JGroupsSubsystemXMLWriter.java
- wildfly/jgroups/src/main/resources/schema/jboss-infinispan-jgroups_10_1.xsd
- wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_0.xml
- wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_1.xml
- wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-9_4.xml
https://issues.redhat.com/browse/ISPN-11352
> [10.1] ISPN-11352 JGroups Subssytem: persist properties in the relay element

- wildfly/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/JGroupsSubsystemXMLWriter.java
- wildfly/jgroups/src/main/resources/schema/jboss-infinispan-jgroups_11_0.xsd
- wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_0.xml
- wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_1.xml
- wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-11_0.xml
- wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-9_4.xml
https://issues.redhat.com/browse/ISPN-11352
> ISPN-11352 JGroups Subssytem: persist properties in the relay element

- core/src/main/java/org/infinispan/xsite/commands/XSiteStateTransferFinishSendCommand.java
- core/src/test/java/org/infinispan/xsite/statetransfer/failures/RetryMechanismTest.java
https://issues.redhat.com/browse/ISPN-11369
> ISPN-11369 RetryMechanismTest.testRetryLocally fails randomly

- feature-pack/client/src/main/resources/modules/io/netty/slot/module.xml
- server/integration/build/trim-delete.txt
https://issues.redhat.com/browse/ISPN-11318
> [9.4] ISPN-11318 Silence spurious log4j2 classloader warning from Netty

- commons/src/main/java/org/infinispan/commons/util/PeekableMap.java
- core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java
- core/src/main/java/org/infinispan/container/impl/BoundedSegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/impl/DefaultDataContainer.java
- core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/impl/L1SegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/impl/PeekableTouchableContainerMap.java
- core/src/main/java/org/infinispan/container/impl/PeekableTouchableMap.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapDataContainer.java
- core/src/main/java/org/infinispan/container/offheap/SegmentedBoundedOffHeapDataContainer.java
- core/src/main/java/org/infinispan/factories/DataContainerFactory.java
- core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
* Make sure to not calculate segment if segmentation is disabled
* Add in interface to prevent additional if/else blocks
https://issues.redhat.com/browse/ISPN-11209
> ISPN-11209 Max Idle changes caused a REPL read performance regression

- core/src/test/java/org/infinispan/lock/LockManagerTest.java
* Fix test failure
https://issues.redhat.com/browse/ISPN-11292
> ISPN-11292 Add in (non)blocking thread pools

- server/runtime/src/main/resources/schema/infinispan-server-11.0.xsd
https://issues.redhat.com/browse/ISPN-11334 
> ISPN-11334 do not change REST context path

- server/runtime/src/main/resources/schema/infinispan-server-10.1.xsd
> [10.1.x] ISPN-11334 do not change REST context path

- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
https://issues.redhat.com/browse/ISPN-11372
> ISPN-11372 AsyncTimeBasedOfflineTest.testSFOOffline() random failures

- server/runtime/src/test/java/org/infinispan/server/functional/RestMetricsResource.java
https://issues.redhat.com/browse/ISPN-11174
> ISPN-11174 Fix RestMetricsResource test failure

- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/main/java/org/infinispan/cache/impl/ContextBuilder.java
- core/src/main/java/org/infinispan/cache/impl/DecoratedCache.java
- core/src/main/java/org/infinispan/cache/impl/InvocationHelper.java
- core/src/main/java/org/infinispan/configuration/cache/Configurations.java
- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
* Extract code from CacheImpl to be used by IRAC updates.
https://issues.redhat.com/browse/ISPN-11368
> ISPN-11368 Refactor CacheImpl code

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
https://issues.redhat.com/browse/ISPN-11386
> ISPN-11386 Use blocking thread pool in Persistent preload

- core/src/test/java/org/infinispan/remoting/AsynchronousInvocationTest.java
https://issues.redhat.com/browse/ISPN-11391
* Re-add the blocking ReplicableCommand test
* Use mocks instead of actual commands
> ISPN-11391 Check GlobalRpcCommands in AsynchronousInvocationTest

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsChannelLookup.java
https://issues.redhat.com/browse/ISPN-11376
> ISPN-11376 Deprecate JGroupsChannelLookup

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11383
> ISPN-11383 upgrade spring versions

- core/src/main/java/org/infinispan/util/concurrent/ConditionFuture.java
- core/src/test/java/org/infinispan/test/Exceptions.java
- core/src/test/java/org/infinispan/util/concurrent/ConditionFutureTest.java
https://issues.redhat.com/browse/ISPN-11280
> [10.1.x] ISPN-11280 ConcurrentModificationException in ConditionFuture

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11383
> [9.4.x] ISPN-11383 upgrade spring versions

- core/src/main/java/org/infinispan/factories/ComponentRegistry.java
- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/marshall/exts/EnumExternalizer.java
- core/src/main/java/org/infinispan/xsite/BackupSender.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/main/java/org/infinispan/xsite/NoOpBackupSender.java
- core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteAmendOfflineStatusCommand.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteBringOnlineCommand.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteOfflineStatusCommand.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteStatusCommand.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteTakeOfflineCommand.java
- core/src/main/java/org/infinispan/xsite/status/BringSiteOnlineResponse.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
- core/src/main/java/org/infinispan/xsite/status/NoOpTakeOfflineManager.java
- core/src/main/java/org/infinispan/xsite/status/SiteState.java
- core/src/main/java/org/infinispan/xsite/status/TakeOfflineManager.java
- core/src/main/java/org/infinispan/xsite/status/TakeSiteOfflineResponse.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- core/src/test/java/org/infinispan/xsite/XSiteAdminOperationsTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/NonTxOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/ResetOfflineStatusTest.java
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
https://issues.redhat.com/browse/ISPN-11298
Moves the code that takes sites offline from BackupSender to TakeOfflineManager.
> ISPN-11298 Create TakeOfflineManager

- core/src/main/java/org/infinispan/configuration/global/GlobalJmxConfiguration.java
- core/src/main/java/org/infinispan/configuration/global/GlobalJmxConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/global/GlobalJmxStatisticsConfiguration.java
- core/src/main/java/org/infinispan/configuration/global/GlobalJmxStatisticsConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/Attribute.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
- core/src/main/java/org/infinispan/jmx/AbstractJmxRegistration.java
- core/src/main/java/org/infinispan/jmx/CacheJmxRegistration.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/resources/schema/infinispan-config-11.0.xsd
- core/src/test/java/org/infinispan/configuration/JsonSerializationTest.java
- core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java
- core/src/test/java/org/infinispan/jmx/CacheMBeanTest.java
- core/src/test/java/org/infinispan/jmx/CacheManagerMBeanTest.java
- core/src/test/java/org/infinispan/jmx/JmxStatsFunctionalTest.java
- core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
- core/src/test/resources/configs/named-cache-test.xml
- core/src/test/resources/configs/unified/11.0.xml
https://issues.redhat.com/browse/ISPN-10900
> ISPN-10900 allowDuplicateDomains, no more!

- cli/cli-client/src/main/java/org/infinispan/cli/commands/Stats.java
- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
- cli/cli-client/src/main/java/org/infinispan/cli/logging/Messages.java
- cli/cli-client/src/main/resources/help/stats.adoc
- documentation/src/main/asciidoc/stories/assembly_cli_starting.adoc
- documentation/src/main/asciidoc/topics/proc_cli_statistics.adoc
https://issues.redhat.com/browse/ISPN-11382
> ISPN-11382 Implement the CLI stats command

- cli/cli-client/src/main/java/org/infinispan/cli/commands/Stats.java
- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
- cli/cli-client/src/main/java/org/infinispan/cli/logging/Messages.java
- cli/cli-client/src/main/resources/help/stats.adoc
- documentation/src/main/asciidoc/stories/assembly_cli_starting.adoc
- documentation/src/main/asciidoc/topics/proc_cli_statistics.adoc
https://issues.redhat.com/browse/ISPN-11382
> [10.1] ISPN-11382 Implement the CLI stats command

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/SegmentKeyTracker.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/StorageRoutingTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/ReplicationIndexTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/FixedServerBalancing.java
- core/src/main/java/org/infinispan/encoding/DataConversion.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeEncodings.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/TestCluster.java
https://issues.redhat.com/browse/ISPN-11341
> ISPN-11341 Client requests go to wrong server with binary storage

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/SegmentKeyTracker.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/StorageRoutingTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/ReplicationIndexTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/FixedServerBalancing.java
- core/src/main/java/org/infinispan/encoding/DataConversion.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeEncodings.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/TestCluster.java
https://issues.redhat.com/browse/ISPN-11341
> [10.1.x] ISPN-11341 Client requests go to wrong server with binary storage

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/SegmentKeyTracker.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/StorageRoutingTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/ReplicationIndexTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/FixedServerBalancing.java
- core/src/main/java/org/infinispan/encoding/DataConversion.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeEncodings.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/TestCluster.java
https://issues.redhat.com/browse/ISPN-11341
> [9.4.x] ISPN-11341 Client requests go to wrong server with binary storage

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.redhat.com/browse/ISPN-11373
> [9.4.x] [PREVIEW] ISPN-11373 XSite backup commands should be sent from a blocking thread

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11410
Backport #7981
> ISPN-11410 upgrade to console 0.4.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11410
> [10.1.x] ISPN-11410 upgrade to console 0.4.Final

- server/runtime/src/main/server/server/conf/infinispan-local.xml
- server/runtime/src/main/server/server/conf/infinispan-xsite.xml
- server/runtime/src/main/server/server/conf/infinispan.xml
https://issues.redhat.com/browse/ISPN-11400
> ISPN-11400 Let's disable histograms in the server by default

- server/runtime/src/main/server/server/conf/infinispan-local.xml
- server/runtime/src/main/server/server/conf/infinispan-xsite.xml
- server/runtime/src/main/server/server/conf/infinispan.xml
https://issues.redhat.com/browse/ISPN-11400
> [10.1.x] ISPN-11400 Let's disable histograms in the server by default

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/util/concurrent/ActionSequencer.java
- core/src/main/java/org/infinispan/xsite/BaseBackupReceiver.java
- core/src/test/java/org/infinispan/util/ActionSequencerUnitTest.java
https://issues.redhat.com/browse/ISPN-11404
> [9.4.x] ISPN-11404 Add metrics to ActionSequencer

- core/src/main/java/org/infinispan/remoting/inboundhandler/BasePerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/PerCacheInboundInvocationHandler.java
- core/src/main/java/org/infinispan/xsite/BaseBackupReceiver.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheMetricsHandler.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanResourceDescriptionResolver.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/MetricKeys.java
- server/integration/infinispan/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
https://issues.redhat.com/browse/ISPN-11404
> [9.4.x] ISPN-11405 Always use thread pool to handle async xsite requests

- core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
- core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
- core/src/main/java/org/infinispan/util/concurrent/ActionSequencer.java
- core/src/main/java/org/infinispan/xsite/BaseBackupReceiver.java
- core/src/test/java/org/infinispan/util/ActionSequencerUnitTest.java
https://issues.redhat.com/browse/ISPN-11404
> ISPN-11404 Add metrics to ActionSequencer

- core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
- core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
- core/src/main/java/org/infinispan/util/concurrent/ActionSequencer.java
- core/src/main/java/org/infinispan/xsite/BaseBackupReceiver.java
- core/src/test/java/org/infinispan/util/ActionSequencerUnitTest.java
https://issues.redhat.com/browse/ISPN-11404
> [10.1.x] ISPN-11404 Add metrics to ActionSequencer

- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
- server/runtime/src/test/java/org/infinispan/server/unit/configuration/ServerEventLoggerTest.java
https://issues.redhat.com/browse/ISPN-11411
> ISPN-11411 Fix ServerEventLoggerTest failures

- core/src/main/java/org/infinispan/configuration/cache/MemoryStorageConfiguration.java
- core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java
- core/src/test/resources/configs/unified/11.0.xml
https://issues.redhat.com/browse/ISPN-11384
> ISPN-11384 Cannot create OFF_HEAP caches dynamically

- wildfly/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerConfigurationBuilder.java
* Remove reference from now removed transport executor
https://issues.redhat.com/browse/ISPN-11415
> ISPN-11415 InfinispanExtensionIT always fails

- cli/cli-client/src/main/java/org/infinispan/cli/CLI.java
https://issues.redhat.com/browse/ISPN-11418
> ISPN-11418 Disconnect CLI after running batch

- cli/cli-client/src/main/java/org/infinispan/cli/CLI.java
https://issues.redhat.com/browse/ISPN-11418
> [10.1] ISPN-11418 Disconnect CLI after running batch

- server/runtime/build.xml
https://issues.redhat.com/browse/ISPN-11417
> ISPN-11417 Include XSDs in the server's docs/schema directory

- server/runtime/build.xml
https://issues.redhat.com/browse/ISPN-11417
> [10.1] ISPN-11417 Include XSDs in the server's docs/schema directory

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11401
> ISPN-11401 Log4j 2.13.1

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11401
> [10.1] ISPN-11401 Log4j 2.13.1

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java
https://issues.redhat.com/browse/ISPN-7819
> ISPN-7819 update putAll docs

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/DB2TableManager.java
https://issues.redhat.com/browse/ISPN-11433
> ISPN-11433 DB2TableManager is missing segmentColumnName parameter

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/DB2TableManager.java
https://issues.redhat.com/browse/ISPN-11433
> [10.1.x] ISPN-11433 DB2TableManager is missing segmentColumnName parameter

- build-configuration/bom/pom.xml
https://issues.redhat.com/browse/ISPN-11437
> ISPN-11437 Protostream Processor missing from infinispan-bom

- build-configuration/bom/pom.xml
https://issues.redhat.com/browse/ISPN-11437
> [10.1.x] ISPN-11437 Protostream Processor missing from infinispan-bom

- build-configuration/pom.xml
- cdi/embedded/pom.xml
- cdi/remote/pom.xml
- hibernate/cache-commons/pom.xml
- hibernate/cache-v51/pom.xml
- hibernate/cache-v53/pom.xml
- integrationtests/cdi-jcache-it/pom.xml
- integrationtests/cdi-weld-se-it/pom.xml
- jcache/embedded/pom.xml
- jcache/tck-runner-embedded/pom.xml
- jcache/tck-runner-remote/pom.xml
- pom.xml
* Added property for Hibernate 5.1.x and 5.3.x
* Removed hardcoded version
https://issues.redhat.com/browse/ISPN-11397
> ISPN-11397 Align common dependencies with EAP

- build-configuration/pom.xml
- cdi/embedded/pom.xml
- cdi/remote/pom.xml
- hibernate/cache-commons/pom.xml
- hibernate/cache-v51/pom.xml
- hibernate/cache-v53/pom.xml
- integrationtests/cdi-jcache-it/pom.xml
- integrationtests/cdi-weld-se-it/pom.xml
- jcache/embedded/pom.xml
- jcache/tck-runner-embedded/pom.xml
- jcache/tck-runner-remote/pom.xml
- pom.xml
* Added property for Hibernate 5.1.x and 5.3.x
* Removed hardcoded version
https://issues.redhat.com/browse/ISPN-11397
> [10.1.x] ISPN-11397 Align common dependencies with EAP

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/TableManagerFactory.java
https://issues.redhat.com/browse/ISPN-11451
> ISPN-11451 Add postgresqlplus to TableManagerFactory#guessDialect

- core/src/main/java/org/infinispan/configuration/cache/MemoryStorageConfiguration.java
- core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java
- core/src/test/resources/configs/unified/10.1.xml
- query/src/test/java/org/infinispan/query/distributed/MassIndexingTest.java
https://issues.redhat.com/browse/ISPN-11384
> [10.1.x] ISPN-11384 Cannot create OFF_HEAP caches dynamically

- core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactory.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactoryImpl.java
- core/src/main/java/org/infinispan/container/offheap/OffHeapMemory.java
- core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
- core/src/main/java/org/infinispan/expiration/impl/TouchCommand.java
- core/src/test/java/org/infinispan/eviction/impl/ExceptionEvictionTest.java
- core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
https://issues.redhat.com/browse/ISPN-9082
> [10.1.x] ISPN-9082 Off Heap maxIdle expiration works like lifespan

- core/src/main/java/org/infinispan/globalstate/impl/GlobalStateManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
- server/runtime/src/main/server/README.md
ISPN-11460 Separate arguments for endpoint and cluster address binding
https://issues.redhat.com/browse/ISPN-11460 
ISPN-11461 Do not persist global state when startup fails 
https://issues.redhat.com/browse/ISPN-11461
> ISPN-11461 Do not persist global state when startup fails

- core/src/main/java/org/infinispan/globalstate/impl/GlobalStateManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
- server/runtime/src/main/server/README.md
ISPN-11460 Separate arguments for endpoint and cluster address binding
https://issues.redhat.com/browse/ISPN-11460
ISPN-11461 Do not persist global state when startup fails
https://issues.redhat.com/browse/ISPN-11461
> [10.1] ISPN-11461 Do not persist global state when startup fails

- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-11468
> ISPN-11468 TransactionTable#calculateMinTopologyId should allow blocking

- core/src/main/java/org/infinispan/health/impl/HealthImpl.java
- core/src/main/java/org/infinispan/health/impl/SecurityActions.java
- core/src/main/java/org/infinispan/security/Security.java
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/test/java/org/infinispan/rest/AuthenticationTest.java
- server/tests/src/test/java/org/infinispan/server/security/AuthorizationLDAPIT.java
- server/tests/src/test/resources/configuration/cache-container/clustered-authz.xml
- server/tests/src/test/resources/configuration/cache-container/clustered.xml
- server/tests/src/test/resources/configuration/cache-container/default.xml
https://issues.redhat.com/browse/ISPN-11126
depends on https://github.com/infinispan/infinispan/pull/8016
> ISPN-11126 Perform some cache manager ops in privileged blocks

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
- core/src/main/java/org/infinispan/util/concurrent/locks/impl/InfinispanLock.java
- core/src/main/java/org/infinispan/util/concurrent/locks/impl/PerKeyLockContainer.java
- core/src/main/java/org/infinispan/util/concurrent/locks/impl/StripedLockContainer.java
- core/src/test/java/org/infinispan/lock/InfinispanLockTest.java
- core/src/test/java/org/infinispan/lock/LockContainerTest.java
- core/src/test/java/org/infinispan/lock/LockManagerTest.java
- core/src/test/java/org/infinispan/lock/SimpleLockContainerTest.java
https://issues.redhat.com/browse/ISPN-11443
https://issues.redhat.com/browse/ISPN-11450
https://issues.redhat.com/browse/ISPN-11295
> ISPN-11443 PersistenceManagerImpl thread checks need to be updated

- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
- server/hotrod/pom.xml
- server/hotrod/src/main/java/org/infinispan/server/hotrod/LifecycleCallbacks.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ServerHotRodBlockHoundIntegration.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/ServerHotRodTestBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-11441
> ISPN-11441 Add blockhound support to hotrod server

- commons/src/main/java/org/infinispan/commons/api/BasicCacheContainer.java
- core/src/main/java/org/infinispan/manager/CacheContainer.java
- core/src/main/java/org/infinispan/manager/EmbeddedCacheManager.java
https://issues.redhat.com/browse/ISPN-11367
Quick follow-up to update the javadoc.
I have also updated the javadoc of the deprecated methods, but we might decide to remove those before 11.0
> ISPN-11367 Update cache manager javadoc for default caches

- core/src/test/java/org/infinispan/invalidation/BaseInvalidationTest.java
- core/src/test/java/org/infinispan/util/AbstractDelegatingRpcManager.java
https://issues.redhat.com/browse/ISPN-6721
Issue was fixed in 9.0 with ISPN-6599, but I didn't add a test at the time.
> ISPN-6721 Test that invalidations ignore leavers

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelRecord.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/DroppedConnectionsTest.java
https://issues.redhat.com/browse/ISPN-10270
> [10.1] ISPN-10270 Fix DropppedConnectionsTest random failures

- pom.xml
https://issues.redhat.com/browse/ISPN-11486
> ISPN-11486 Upgrade to javassist 3.26.0-GA

- documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
https://issues.redhat.com/browse/ISPN-11447
backport to 10.1.x please
> get cache templates via REST

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/DefaultTemplate.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdmin.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheManagerAdminImpl.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
https://issues.redhat.com/browse/ISPN-11239
> ISPN-11239 Create caches with default template name

- documentation/src/main/asciidoc/topics/proc_getting_store_migrator.adoc
https://issues.redhat.com/browse/ISPN-11484
> ISPN-11484 storemigrator from maven

- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/AbstractStringBasedCacheStore.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithManagedConnectionFunctionalTest.java
https://issues.redhat.com/browse/ISPN-11464
> ISPN-11464 Make possible to override table manipulation configuration from AbstractStringBasedCacheStore

- core/src/main/java/org/infinispan/security/Security.java
- core/src/main/java/org/infinispan/security/impl/AuthorizationHelper.java
https://issues.redhat.com/browse/ISPN-11515
> ISPN-11515 Drop use of java.security.acl.Group

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelRecord.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/DroppedConnectionsTest.java
https://issues.redhat.com/browse/ISPN-10270
> ISPN-10270 Fix DropppedConnectionsTest random failures

- documentation/src/main/asciidoc/topics/proc_getting_store_migrator.adoc
https://issues.redhat.com/browse/ISPN-11484
> [10.1.x] ISPN-11484 storemigrator from maven

- query/src/test/java/org/infinispan/query/blackbox/IndexingDuringStateTransferTest.java
https://issues.redhat.com/browse/ISPN-11518
> ISPN-11518 IndexingDuringStateTransferTest random failures

- documentation/src/main/asciidoc/topics/con_write_behind.adoc
- documentation/src/main/asciidoc/topics/con_write_through.adoc
https://issues.redhat.com/browse/ISPN-11536
> ISPN-11536 updates to write behind and write through docs

- documentation/src/main/asciidoc/topics/con_write_behind.adoc
- documentation/src/main/asciidoc/topics/con_write_through.adoc
https://issues.redhat.com/browse/ISPN-11536
> [10.1.x] ISPN-11536 updates to write behind and write through docs

- documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
backport for https://issues.redhat.com/browse/ISPN-11447
> [10.1.x] get cache templates via REST

- documentation/src/main/asciidoc/topics/proc_xsite_configuring_backups.adoc
- documentation/src/main/asciidoc/topics/ref_rest_xsite.adoc
https://issues.redhat.com/browse/ISPN-11544
> [10.1.x] ISPN-11544 xsite doc fixes

- core/src/main/java/org/infinispan/functional/impl/AbstractFunctionalMap.java
- multimap/pom.xml
https://issues.redhat.com/browse/ISPN-11542
> ISPN-11542 Make Multimap transactions non blocking

- core/pom.xml
- counter/pom.xml
- lock/pom.xml
- persistence/jdbc/pom.xml
- persistence/jpa/pom.xml
- persistence/remote/pom.xml
- persistence/rest/pom.xml
- persistence/rocksdb/pom.xml
- persistence/rocksdb/src/main/resources/schema/infinispan-cachestore-rocksdb-config-11.0.xsd
- persistence/soft-index/pom.xml
- persistence/soft-index/src/main/resources/schema/infinispan-persistence-soft-index-config-11.0.xsd
- plugins/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsExtractorMojo.java
- server/core/src/main/java/org/infinispan/server/core/configuration/EncryptionConfiguration.java
- server/runtime/pom.xml
- server/runtime/src/main/resources/schema/infinispan-server-11.0.xsd
https://issues.redhat.com/browse/ISPN-11522
> ISPN-11522 Store filtered XSDs in the jars

- documentation/src/main/asciidoc/stories/assembly_cache_stores.adoc
- documentation/src/main/asciidoc/topics/code_examples/ConfigRocksDbProperties.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigSingleFileStore.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigSoftIndexFileStore.java
- documentation/src/main/asciidoc/topics/config_examples/persistence_file_store.xml
- documentation/src/main/asciidoc/topics/config_examples/persistence_rocksdb_example.xml
- documentation/src/main/asciidoc/topics/config_examples/persistence_soft_index_file_store.xml
- documentation/src/main/asciidoc/topics/proc_setting_persistent_location.adoc
- documentation/src/main/asciidoc/topics/ref_cache_store_rocksdb.adoc
https://issues.redhat.com/browse/ISPN-11517
> ISPN-11517 set global persistent location for file-based cache stores

- documentation/src/main/asciidoc/stories/assembly_cache_stores.adoc
- documentation/src/main/asciidoc/topics/code_examples/ConfigRocksDbProperties.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigSingleFileStore.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigSoftIndexFileStore.java
- documentation/src/main/asciidoc/topics/config_examples/persistence_file_store.xml
- documentation/src/main/asciidoc/topics/config_examples/persistence_rocksdb_example.xml
- documentation/src/main/asciidoc/topics/config_examples/persistence_soft_index_file_store.xml
- documentation/src/main/asciidoc/topics/proc_setting_persistent_location.adoc
- documentation/src/main/asciidoc/topics/ref_cache_store_rocksdb.adoc
https://issues.redhat.com/browse/ISPN-11517
> [10.1.x] ISPN-11517 set global persistent location for file-based cache stores

- client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
- commons/all/src/main/java/org/infinispan/commons/configuration/JsonReader.java
- core/src/main/java/org/infinispan/configuration/cache/PersistenceConfigurationBuilder.java
- documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
- documentation/src/main/asciidoc/topics/ref_rest_rolling.adoc
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfiguration.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationBuilder.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/MigrationTask.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/configuration/ConfigurationSerializerTest.java
- persistence/remote/src/test/resources/remote-cl-config-security.xml
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeIT.java
https://issues.redhat.com/browse/ISPN-11503
> ISPN-11503 Export Rolling Upgrade operations via REST

- documentation/src/main/asciidoc/stories/assembly_hotrod_client_api.adoc
- documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
- documentation/src/main/asciidoc/stories/assembly_server_endpoints.adoc
- documentation/src/main/asciidoc/topics/code_examples/ConfigCacheStores.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigClustering.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigStats.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigTransactionsLocking.java
- documentation/src/main/asciidoc/topics/code_examples/EmbeddedConflictManager.java
- documentation/src/main/asciidoc/topics/code_examples/InitialClusterSize.java
- documentation/src/main/asciidoc/topics/code_examples/PartitionHandling.java
- documentation/src/main/asciidoc/topics/code_examples/RestClient.java
- documentation/src/main/asciidoc/topics/code_examples/rest_client.py
- documentation/src/main/asciidoc/topics/code_examples/rest_client.rb
- documentation/src/main/asciidoc/topics/con_caches_simple.adoc
- documentation/src/main/asciidoc/topics/con_endpoints_memcached.adoc
- documentation/src/main/asciidoc/topics/con_store_migrator.adoc
- documentation/src/main/asciidoc/topics/dependencies_maven/persistence_storemigrator.xml
- documentation/src/main/asciidoc/topics/proc_cli_shutdown.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_statistics.adoc
- documentation/src/main/asciidoc/topics/proc_getting_store_migrator.adoc
- documentation/src/main/asciidoc/topics/proc_running_embedded.adoc
- documentation/src/main/asciidoc/topics/proc_starting_server.adoc
- documentation/src/main/asciidoc/topics/ref_cache_store_jpa.adoc
- documentation/src/main/asciidoc/topics/ref_cache_store_jpa_example.adoc
- documentation/src/main/asciidoc/topics/ref_endpoints_comparison.adoc
- documentation/src/main/asciidoc/topics/ref_hotrod_client_transactions.adoc
- documentation/src/main/asciidoc/topics/ref_hotrod_listeners.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- documentation/src/main/asciidoc/topics/ref_rest_security.adoc
https://issues.redhat.com/browse/ISPN-11539
> ISPN-11539 Documentation edits and corrections

- documentation/src/main/asciidoc/stories/assembly_hotrod_client_api.adoc
- documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
- documentation/src/main/asciidoc/stories/assembly_server_endpoints.adoc
- documentation/src/main/asciidoc/topics/code_examples/ConfigCacheStores.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigClustering.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigStats.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigTransactionsLocking.java
- documentation/src/main/asciidoc/topics/code_examples/EmbeddedConflictManager.java
- documentation/src/main/asciidoc/topics/code_examples/InitialClusterSize.java
- documentation/src/main/asciidoc/topics/code_examples/PartitionHandling.java
- documentation/src/main/asciidoc/topics/code_examples/RestClient.java
- documentation/src/main/asciidoc/topics/code_examples/rest_client.py
- documentation/src/main/asciidoc/topics/code_examples/rest_client.rb
- documentation/src/main/asciidoc/topics/con_caches_simple.adoc
- documentation/src/main/asciidoc/topics/con_endpoints_memcached.adoc
- documentation/src/main/asciidoc/topics/con_store_migrator.adoc
- documentation/src/main/asciidoc/topics/dependencies_maven/persistence_storemigrator.xml
- documentation/src/main/asciidoc/topics/proc_cli_shutdown.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_statistics.adoc
- documentation/src/main/asciidoc/topics/proc_getting_store_migrator.adoc
- documentation/src/main/asciidoc/topics/proc_running_embedded.adoc
- documentation/src/main/asciidoc/topics/proc_starting_server.adoc
- documentation/src/main/asciidoc/topics/ref_cache_store_jpa.adoc
- documentation/src/main/asciidoc/topics/ref_cache_store_jpa_example.adoc
- documentation/src/main/asciidoc/topics/ref_endpoints_comparison.adoc
- documentation/src/main/asciidoc/topics/ref_hotrod_client_transactions.adoc
- documentation/src/main/asciidoc/topics/ref_hotrod_listeners.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- documentation/src/main/asciidoc/topics/ref_rest_security.adoc
https://issues.redhat.com/browse/ISPN-11539
> [10.1.x] ISPN-11539 Documentation edits and corrections

- core/src/main/java/org/infinispan/transaction/impl/TransactionCoordinator.java
- core/src/test/java/org/infinispan/statetransfer/StaleLocksWithCommitDuringStateTransferTest.java
https://issues.redhat.com/browse/ISPN-11489
> ISPN-11489 TransactionCoordinator updated for non blocking

- commons/all/src/main/java/org/infinispan/commons/api/CacheContainerAdmin.java
https://issues.redhat.com/browse/ISPN-11573
> ISPN-11573 Remove CacheContainerAdmin.AdminFlag.PERMANENT

- commons/all/src/main/java/org/infinispan/commons/api/CacheContainerAdmin.java
https://issues.redhat.com/browse/ISPN-11573
@karesti It seems it was too soon :laughing:
> Revert "ISPN-11573 Remove CacheContainerAdmin.AdminFlag.PERMANENT"

- core/src/main/java/org/infinispan/commands/CommandsFactory.java
- core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/commands/batch/CancelPublisherCommand.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/commands/batch/InitialPublisherCommand.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/commands/batch/NextPublisherCommand.java
- core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
https://issues.redhat.com/browse/ISPN-11578
> ISPN-11578 Publisher commands can store RequestID as String

- commons/src/main/java/org/infinispan/commons/util/ReflectionUtil.java
- commons/src/main/java/org/infinispan/commons/util/SecurityActions.java
- core/src/main/java/org/infinispan/distribution/group/impl/GroupManagerImpl.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
https://issues.redhat.com/browse/ISPN-9600
Backport of ISPN-9600 to 9.3.x.
> [9.3.x] ISPN-9600 ReflectionUtil.invokeAccessibly should not be public

- core/src/main/java/org/infinispan/configuration/cache/ClusteringConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/cache/PartitionHandlingConfigurationBuilder.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java
https://issues.redhat.com/browse/ISPN-11529
https://issues.redhat.com/browse/ISPN-11530
Lets see if this breaks any tests :slightly_smiling_face:
> ISPN-11530 Only allow numOwners=1 and ALLOW_READ_WRITES strategy

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11548
> ISPN-11548 Update BlockHound to 1.0.3

- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/health/impl/HealthImpl.java
- core/src/main/java/org/infinispan/health/impl/SecurityActions.java
- core/src/main/java/org/infinispan/security/Security.java
- core/src/main/resources/schema/infinispan-config-fragment-10.1.xsd
- core/src/test/resources/configs/includes/include-1.xml
- documentation/src/main/asciidoc/topics/config_examples/config_xincluded.xml
- documentation/src/main/asciidoc/topics/config_examples/config_xincluded_with_schema.xml
- documentation/src/main/asciidoc/topics/ref_config_xinclude.adoc
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/test/java/org/infinispan/rest/AuthenticationTest.java
- server/tests/src/test/java/org/infinispan/server/security/AuthorizationLDAPIT.java
- server/tests/src/test/resources/configuration/cache-container/clustered-authz.xml
- server/tests/src/test/resources/configuration/cache-container/clustered.xml
- server/tests/src/test/resources/configuration/cache-container/default.xml
https://issues.redhat.com/browse/ISPN-11126
> [10.1] ISPN-11126 Perform some cache manager ops in privileged blocks

- core/pom.xml
- counter/pom.xml
- lock/pom.xml
- persistence/jdbc/pom.xml
- persistence/jpa/pom.xml
- persistence/remote/pom.xml
- persistence/rest/pom.xml
- persistence/rocksdb/pom.xml
- persistence/rocksdb/src/main/resources/schema/infinispan-cachestore-rocksdb-config-10.1.xsd
- persistence/soft-index/pom.xml
- persistence/soft-index/src/main/resources/schema/infinispan-persistence-soft-index-config-10.1.xsd
- plugins/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsExtractorMojo.java
- server/core/src/main/java/org/infinispan/server/core/configuration/EncryptionConfiguration.java
- server/runtime/pom.xml
- server/runtime/src/main/resources/schema/infinispan-server-10.1.xsd
https://issues.redhat.com/browse/ISPN-11522
> [10.1] ISPN-11522 Store filtered XSDs in the jars

- core/src/main/java/org/infinispan/security/Security.java
- core/src/main/java/org/infinispan/security/impl/AuthorizationHelper.java
https://issues.redhat.com/browse/ISPN-11515
> [10.1] ISPN-11515 Drop use of java.security.acl.Group

- core/src/main/java/org/infinispan/configuration/cache/ClusteringConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/cache/PartitionHandlingConfigurationBuilder.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java
https://issues.redhat.com/browse/ISPN-11529
https://issues.redhat.com/browse/ISPN-11530
> [10.1.x] ISPN-11530 Only allow numOwners=1 and ALLOW_READ_WRITES strategy

- core/src/main/java/org/infinispan/notifications/FilteringListenable.java
- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
- core/src/main/java/org/infinispan/notifications/cachelistener/cluster/ClusterListenerReplicateCallable.java
- core/src/test/java/org/infinispan/notifications/cachelistener/cluster/AbstractClusterListenerTest.java
- query/src/test/java/org/infinispan/query/continuous/AbstractCQMultipleCachesTest.java
- query/src/test/java/org/infinispan/query/continuous/CallCountingCQResultListener.java
https://issues.redhat.com/browse/ISPN-11459
https://issues.redhat.com/browse/JDG-3578
> [10.1.x] ISPN-11459 NullPointerException installing continuous query listener on joiner

- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
https://issues.redhat.com/browse/ISPN-11580
> ISPN-11580 Change Stopping cache manager log message to info

- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/AbstractStringBasedCacheStore.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithManagedConnectionFunctionalTest.java
https://issues.redhat.com/browse/ISPN-11464
> [10.1] ISPN-11464 Make possible to override table manipulation configuration from AbstractStringBasedCacheStore

- commons/src/main/java/org/infinispan/commons/util/BlueprintGenerator.java
- commons/src/main/java/org/infinispan/commons/util/OsgiClassLoader.java
- commons/src/main/java/org/infinispan/commons/util/Util.java
- documentation/src/main/asciidoc/topics/upgrading.adoc
- osgi/src/main/java/org/infinispan/osgi/InfinispanEmbeddedServiceFactory.java
https://issues.redhat.com/browse/ISPN-11419
> [10.1] ISPN-11419 Deprecate OSGi

- lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java
- lock/src/main/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManager.java
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/runtime/src/main/server/bin/server.sh
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanServerTestConfiguration.java
- server/testdriver/core/src/main/resources/overlay/bin/kill.sh
- server/testdriver/core/src/main/resources/overlay/bin/pause.sh
- server/testdriver/core/src/main/resources/overlay/bin/resume.sh
- server/testdriver/core/src/main/resources/overlay/bin/term.sh
- server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerRuleBuilder.java
- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeIT.java
- server/tests/src/test/java/org/infinispan/server/resilience/StatefulSetRollingUpgradeIT.java
https://issues.redhat.com/browse/ISPN-11527
https://issues.redhat.com/browse/ISPN-11537
https://issues.redhat.com/browse/ISPN-11538
https://issues.redhat.com/browse/ISPN-11582
I'll create a backport PR once this has been merged.
The clustered locks changed was required as previously it was not cleaning up it's resource and was blocking shutdown via sigterm.
ISPN-11538 should probably be 11.x only.
> StatefulSet Integration Test

- pom.xml
- server/runtime/build.xml
- server/runtime/pom.xml
https://issues.redhat.com/browse/ISPN-11436
> ISPN-11436 Fix licenses for server

- pom.xml
- server/runtime/build.xml
- server/runtime/pom.xml
https://issues.redhat.com/browse/ISPN-11436
> [10.1] ISPN-11436 Fix licenses for server

- server/runtime/src/main/server/bin/server.conf
https://issues.redhat.com/browse/ISPN-11590
> ISPN-11590 Remove MaxMetaspaceSize from server script

- server/runtime/src/main/server/bin/server.conf
https://issues.redhat.com/browse/ISPN-11590
> [10.1] ISPN-11590 Remove MaxMetaspaceSize from server script

- core/src/main/java/org/infinispan/transaction/xa/recovery/InDoubtTxInfoImpl.java
- core/src/main/java/org/infinispan/transaction/xa/recovery/RecoveryAdminOperations.java
- core/src/main/java/org/infinispan/transaction/xa/recovery/RecoveryManager.java
https://issues.redhat.com/browse/ISPN-11591
> ISPN-11591 InDoubtTxInfoImpl can store status as an Integer

- core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
- lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java
- lock/src/main/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManager.java
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/server/server/conf/log4j2.xml
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanServerTestConfiguration.java
- server/testdriver/core/src/main/resources/overlay/bin/kill.sh
- server/testdriver/core/src/main/resources/overlay/bin/pause.sh
- server/testdriver/core/src/main/resources/overlay/bin/resume.sh
- server/testdriver/core/src/main/resources/overlay/bin/term.sh
- server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerRuleBuilder.java
- server/tests/src/test/java/org/infinispan/server/resilience/StatefulSetRollingUpgradeIT.java
https://issues.redhat.com/browse/ISPN-11480
https://issues.redhat.com/browse/ISPN-11485
https://issues.redhat.com/browse/ISPN-11527
https://issues.redhat.com/browse/ISPN-11537
https://issues.redhat.com/browse/ISPN-11582
I have omitted `StatefulSetRollingUpgradeTest` for now as it's frequently failing on master. I'll backport once the test is fixed.
> [10.1.x] Various server fixes

- server/runtime/build.xml
- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/loader/Loader.java
https://issues.redhat.com/browse/ISPN-11594
https://issues.redhat.com/browse/ISPN-11593
> ISPN-11594 Prevent duplicate jars

- core/src/test/java/org/infinispan/eviction/impl/EvictionWithPassivationAndConcurrentOperationsTest.java
- core/src/test/java/org/infinispan/test/Mocks.java
testEvictionDuringWriteWithConcurrentRead random failures
https://issues.redhat.com/browse/ISPN-11598
> ISPN-11598 EvictionWithPassivationAndConcurrentOperationsTest

- client/infinispan-key-value-store-hotrod/src/test/java/org/infinispan/api/client/impl/SearchKeyValueStoreTest.java
- commons/all/src/main/java/org/infinispan/commons/marshall/Ids.java
- core/src/main/java/org/infinispan/filter/CacheFilters.java
- core/src/main/java/org/infinispan/marshall/core/InternalExternalizers.java
- core/src/main/java/org/infinispan/notifications/cachelistener/BaseQueueingSegmentListener.java
- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
- core/src/main/java/org/infinispan/notifications/cachelistener/DistributedQueueingSegmentListener.java
- core/src/main/java/org/infinispan/notifications/cachelistener/QueueingSegmentListener.java
- core/src/main/java/org/infinispan/reactive/publisher/PublisherTransformers.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/LocalClusterPublisherManagerImpl.java
- core/src/main/java/org/infinispan/stream/impl/CacheIntermediatePublisher.java
- core/src/main/java/org/infinispan/stream/impl/DistributedCacheStream.java
- core/src/test/java/org/infinispan/notifications/cachelistener/BaseCacheNotifierImplInitialTransferTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/CacheNotifierImplInitialTransferDistTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/cluster/NonBlockingClusterListener.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ClientListenerRegistry.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ServerHotRodBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-10457
> ISPN-10457 Convert bulk blocking stream operations to publisher

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11610
> ISPN-11610 Use getHostAddress() to obtain the docker bridge IP

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11610
> [10.1] ISPN-11610 Use getHostAddress() to obtain the docker bridge IP

- Jenkinsfile-release
- documentation/src/main/asciidoc/stories/assembly_configuring_maven_repository.adoc
- documentation/src/main/asciidoc/stories/assembly_developing.adoc
- documentation/src/main/asciidoc/stories/assembly_embedding.adoc
- documentation/src/main/asciidoc/stories/assembly_hotrod_clients.adoc
- documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/dependencies_maven/cdi_embedded.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/cdi_remote.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/clustered_counters.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/clustered_locks.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/eap_dependencies.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/hibernate_directory_provider.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/hibernate_v5.1.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/hotrod_java_client.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/ispn_bom.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/ispn_embedded.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/jcache.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/kyro_marshaller.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/lucene_directory.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/multimap.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/persistence_storemigrator.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/spring5_session_dependencies.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/spring_integration.xml
- documentation/src/main/asciidoc/topics/proc_adding_maven_repository.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_pom_xml.adoc
- documentation/src/main/asciidoc/topics/proc_download_hotrod_java_client.adoc
- documentation/src/main/asciidoc/topics/proc_downloading_maven_repository.adoc
- documentation/src/main/asciidoc/topics/proc_installing_embedded.adoc
https://issues.redhat.com/browse/ISPN-11612
> ISPN-11612 adding maven repository details

- Jenkinsfile-release
- documentation/src/main/asciidoc/stories/assembly_configuring_maven_repository.adoc
- documentation/src/main/asciidoc/stories/assembly_developing.adoc
- documentation/src/main/asciidoc/stories/assembly_embedding.adoc
- documentation/src/main/asciidoc/stories/assembly_hotrod_clients.adoc
- documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
- documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
- documentation/src/main/asciidoc/topics/dependencies_maven/cdi_embedded.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/cdi_remote.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/clustered_counters.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/clustered_locks.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/eap_dependencies.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/hibernate_directory_provider.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/hibernate_v5.1.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/hotrod_java_client.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/ispn_bom.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/ispn_embedded.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/jcache.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/kyro_marshaller.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/lucene_directory.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/multimap.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/persistence_storemigrator.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/spring5_session_dependencies.xml
- documentation/src/main/asciidoc/topics/dependencies_maven/spring_integration.xml
- documentation/src/main/asciidoc/topics/proc_adding_maven_repository.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_pom_xml.adoc
- documentation/src/main/asciidoc/topics/proc_download_hotrod_java_client.adoc
- documentation/src/main/asciidoc/topics/proc_downloading_maven_repository.adoc
- documentation/src/main/asciidoc/topics/proc_installing_embedded.adoc
https://issues.redhat.com/browse/ISPN-11612
> [10.1.x] ISPN-11612 adding maven repository details

- core/src/main/java/org/infinispan/configuration/global/CacheContainerConfigurationBuilder.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceOffHeapTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CounterResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/StaticResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/TasksResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/security/AuthClient.java
- server/rest/src/test/java/org/infinispan/rest/resources/security/SimpleSecurityDomain.java
https://issues.redhat.com/browse/ISPN-11622
> ISPN-11622 Modify REST resource tests to include security

- core/src/test/java/org/infinispan/distribution/rehash/StateTransferOverwritingValueTest.java
In testBackupOwnerJoiningDuringPut[SCATTERED_SYNC]
https://issues.redhat.com/browse/ISPN-11609
> ISPN-11609 StateTransferOverwritingValueTest random failures

- documentation/src/main/asciidoc/server_guide/configuration.adoc
- documentation/src/main/asciidoc/user_guide/integrations.adoc
- documentation/src/main/asciidoc/user_guide/persistence_rocksdb.adoc
https://issues.redhat.com/browse/ISPN-11637
> [9.4.x] ISPN-11637 minor doc tweaks

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/SecureRemoteCacheAdminTest.java
https://issues.redhat.com/browse/ISPN-11635
> ISPN-11635 HotRod client testsuite leaves index folders behind

- documentation/src/main/asciidoc/user_guide/persistence_sfs.adoc
https://issues.redhat.com/browse/ISPN-10428
> [9.4.x] clarifying paths for single file cache stores

- core/src/main/java/org/infinispan/marshall/core/InternalExternalizers.java
- core/src/main/java/org/infinispan/stream/impl/AbstractCacheStream.java
https://issues.redhat.com/browse/ISPN-11640
> ISPN-11640 Remove Unused AbstractCacheStream inner classes

- documentation/src/main/asciidoc/server_guide/configuration.adoc
- documentation/src/main/asciidoc/topics/proc_starting_stopping_endpoints.adoc
- documentation/src/main/asciidoc/user_guide/cli.adoc
https://issues.redhat.com/browse/ISPN-11639
> [9.4.x] ISPN-11639 start stop endpoint connectors via cli

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheSupport.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/APITest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tx/APITxTest.java
https://issues.redhat.com/browse/ISPN-11650
> ISPN-11650 Session externalization tests are hanging with ATTRIBUTE granularity + EAP7.3+hotrod-session-management

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdmin.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheManagerAdminImpl.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
https://issues.redhat.com/browse/ISPN-11645
Backport #8201
> ISPN-11645 getOrCreate with DefaultTemplate

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdmin.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheManagerAdminImpl.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
https://issues.redhat.com/browse/ISPN-11645
backport of #8200
> [10.1.x] ISPN-11645 getOrCreate with DefaultTemplate

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/HotRodNonIndexedSingleFileStoreQueryTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/HotRodQueryTest.java
- core/src/main/java/org/infinispan/persistence/file/SingleFileStore.java
- core/src/test/java/org/infinispan/configuration/SampleConfigFilesCorrectnessTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreDistListenerFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreListenerFunctionalTest.java
- core/src/test/java/org/infinispan/expiry/ExpiryTest.java
- core/src/test/java/org/infinispan/persistence/file/SingleFileStoreStressTest.java
- core/src/test/java/org/infinispan/persistence/support/AsyncStoreWithoutEvictionFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/support/BatchAsyncStoreTest.java
- core/src/test/java/org/infinispan/statetransfer/ReplStateTransferCacheLoaderTest.java
- core/src/test/java/org/infinispan/util/ThreadLocalLeakTest.java
- distribution/src/main/release/common/configs/config-samples/sample.xml
- query/src/test/java/org/infinispan/query/backend/QueryInterceptorTest.java
- query/src/test/java/org/infinispan/query/dsl/embedded/NonIndexedSingleFileStoreQueryDslConditionsTest.java
- query/src/test/java/org/infinispan/query/persistence/InconsistentIndexesAfterRestartTest.java
- query/src/test/resources/async-file-store-config.xml
https://issues.redhat.com/browse/ISPN-11556
Preview to see how many tests fail
> ISPN-11556 SFS file location not relative to global persistent-location

- server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-11643
> ISPN-11643 REST connector misinterprets % in query path elements

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- documentation/src/main/asciidoc/topics/jcache.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_hotrod_createonaccess.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_hotrod_nearcaching.adoc
Companion to https://github.com/infinispan/infinispan/pull/8214 
Doc suggestions for https://issues.redhat.com/browse/ISPN-11676
> ISPN-11642 hot rod client cache configuration

- .gitattributes
https://issues.redhat.com/browse/ISPN-11686
> [10.1] ISPN-11686 Ensure that Windows batch files use CR LF line endings

- .gitattributes
https://issues.redhat.com/browse/ISPN-11686
> ISPN-11686 Ensure that Windows batch files use CR LF line endings

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/HotRodNonIndexedSingleFileStoreQueryTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/HotRodQueryTest.java
- core/src/main/java/org/infinispan/persistence/PersistenceUtil.java
- core/src/main/java/org/infinispan/persistence/file/SingleFileStore.java
- core/src/test/java/org/infinispan/configuration/SampleConfigFilesCorrectnessTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreDistListenerFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreListenerFunctionalTest.java
- core/src/test/java/org/infinispan/expiry/ExpiryTest.java
- core/src/test/java/org/infinispan/persistence/file/SingleFileStoreStressTest.java
- core/src/test/java/org/infinispan/persistence/support/AsyncStoreWithoutEvictionFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/support/BatchAsyncStoreTest.java
- core/src/test/java/org/infinispan/statetransfer/ReplStateTransferCacheLoaderTest.java
- core/src/test/java/org/infinispan/util/ThreadLocalLeakTest.java
- distribution/src/main/release/common/configs/config-samples/sample.xml
- query/src/test/java/org/infinispan/query/backend/QueryInterceptorTest.java
- query/src/test/java/org/infinispan/query/dsl/embedded/NonIndexedSingleFileStoreQueryDslConditionsTest.java
- query/src/test/java/org/infinispan/query/persistence/InconsistentIndexesAfterRestartTest.java
- query/src/test/resources/async-file-store-config.xml
https://issues.redhat.com/browse/ISPN-11556
> [10.1.x] ISPN-11556 SFS file location not relative to global persistent-location

- core/src/main/resources/schema/infinispan-config-11.0.xsd
- documentation/src/main/asciidoc/topics/code_examples/ConfigSingleFileStore.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigSingleFileStoreRemote.java
- documentation/src/main/asciidoc/topics/config_examples/persistence_file_store.xml
- documentation/src/main/asciidoc/topics/proc_setting_persistent_location.adoc
- documentation/src/main/asciidoc/topics/ref_cache_store_sfs.adoc
https://issues.redhat.com/browse/ISPN-10428
> ISPN-10428 clarify path usage for single file stores

- core/src/main/resources/schema/infinispan-config-10.1.xsd
- documentation/src/main/asciidoc/topics/code_examples/ConfigSingleFileStore.java
- documentation/src/main/asciidoc/topics/code_examples/ConfigSingleFileStoreRemote.java
- documentation/src/main/asciidoc/topics/config_examples/persistence_file_store.xml
- documentation/src/main/asciidoc/topics/proc_setting_persistent_location.adoc
- documentation/src/main/asciidoc/topics/ref_cache_store_sfs.adoc
https://issues.redhat.com/browse/ISPN-10428
> [10.1.x] ISPN-10428 clarify path usage for single file stores

- build-configuration/pom.xml
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
- server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
- server/runtime/src/main/java/org/infinispan/server/security/SecurityActions.java
- server/runtime/src/main/java/org/infinispan/server/security/UserTool.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/EncryptedPropertiesSecurityRealm.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/PropertiesSecurityRealm.java
- server/runtime/src/test/java/org/infinispan/server/usertool/UserToolTest.java
https://issues.redhat.com/browse/ISPN-11575
> ISPN-11575 EncryptedPropertiesSecurityRealm

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/TransactionContext.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/entry/Modification.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/operations/PrepareTransactionOperation.java
* try to prepare the transaction in the primary owner
https://issues.redhat.com/browse/ISPN-10135
> ISPN-10135 Performance Regression for HotRod-TX

- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/resources/schema/infinispan-config-11.0.xsd
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/resources/configs/unified/11.0.xml
https://issues.redhat.com/browse/ISPN-11690
> ISPN-11690 Remove File-store relative-to attribute

- documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/ISPN-11690
> ISPN-11690 Upgrading docs updated

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11711
> ISPN-11711 upgrade console

- core/src/main/java/org/infinispan/encoding/DataConversion.java
- core/src/main/java/org/infinispan/marshall/core/EncoderRegistry.java
- core/src/main/java/org/infinispan/marshall/core/EncoderRegistryImpl.java
- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
- core/src/test/java/org/infinispan/dataconversion/DataConversionTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/CacheNotifierImplTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/FakeEncoderRegistry.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/BaseRemoteQueryManager.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ClientListenerRegistry.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/DefaultIterationManager.java
- server/rest/src/main/java/org/infinispan/rest/resources/MediaTypeUtils.java
- server/rest/src/main/java/org/infinispan/rest/resources/SecurityActions.java
- tasks/scripting/src/main/java/org/infinispan/scripting/utils/ScriptConversions.java
https://issues.redhat.com/browse/ISPN-11620
> ISPN-11620 Remove EncoderRegistry from DataConversion

- client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
- commons/src/main/java/org/infinispan/commons/configuration/JsonReader.java
- core/src/main/java/org/infinispan/configuration/cache/PersistenceConfigurationBuilder.java
- documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
- documentation/src/main/asciidoc/topics/ref_rest_rolling.adoc
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfiguration.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationBuilder.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/MigrationTask.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/configuration/ConfigurationSerializerTest.java
- persistence/remote/src/test/resources/remote-cl-config-security.xml
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeIT.java
https://issues.redhat.com/browse/ISPN-11503
> [10.1] ISPN-11503 Export Rolling Upgrade operations via REST

- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeIT.java
Fixes compile error from https://github.com/infinispan/infinispan/pull/8099
> [10.1] ISPN-11503 - Fix compile error

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ExecTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ExecTypedTest.java
- core/src/main/java/org/infinispan/health/Health.java
- core/src/main/java/org/infinispan/health/impl/HealthImpl.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/manager/EmbeddedCacheManager.java
- core/src/main/java/org/infinispan/manager/impl/AbstractDelegatingEmbeddedCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/main/java/org/infinispan/rest/resources/SecurityActions.java
- server/rest/src/main/java/org/infinispan/rest/resources/TasksResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/TasksResourceTest.java
- server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestMethodRule.java
https://issues.redhat.com/browse/ISPN-11525
Backport https://github.com/infinispan/infinispan/pull/8239
> ISPN-11525 Fix Authz with REST admin ops

- all/pom.xml
- build-configuration/pom.xml
- javadoc/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-11732
This also updates javadoc plugin to 3.2.0.
This is the latest and greatest. And it's good for you too.
> ISPN-11732  Upgrade infinispan doclets to 1.3.0

- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_nix.adoc
- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_win.adoc
https://issues.redhat.com/browse/ISPN-11697
> [10.1.x] ISPN-11697 user tool invalid flag

- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_authz_nix.adoc
- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_authz_win.adoc
- documentation/src/main/asciidoc/topics/proc_starting_server.adoc
https://issues.redhat.com/browse/ISPN-11697
> ISPN-11697 usertool doc update

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ExecTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ExecTypedTest.java
- core/src/main/java/org/infinispan/configuration/global/CacheContainerConfigurationBuilder.java
- core/src/main/java/org/infinispan/health/Health.java
- core/src/main/java/org/infinispan/health/impl/HealthImpl.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/manager/EmbeddedCacheManager.java
- core/src/main/java/org/infinispan/manager/impl/AbstractDelegatingEmbeddedCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/main/java/org/infinispan/rest/resources/SecurityActions.java
- server/rest/src/main/java/org/infinispan/rest/resources/TasksResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceOffHeapTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CounterResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/StaticResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/TasksResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/security/AuthClient.java
- server/rest/src/test/java/org/infinispan/rest/resources/security/SimpleSecurityDomain.java
- server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestMethodRule.java
https://issues.redhat.com/browse/ISPN-11525
> [10.1] ISPN-11525 Authz handled in REST endpoints

- lock/pom.xml
- lock/src/main/java/org/infinispan/lock/impl/lock/ClusteredLockImpl.java
- lock/src/main/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManager.java
https://issues.redhat.com/browse/ISPN-11740
https://issues.redhat.com/browse/ISPN-11553
> ISPN-11740 Add blockhound to lock module

- tasks/manager/pom.xml
- tasks/scripting/pom.xml
https://issues.redhat.com/browse/ISPN-11738
> ISPN-11738 Add blockhound to task modules

- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
- counter/pom.xml
https://issues.redhat.com/browse/ISPN-11736
> ISPN-11736 Add blockhound to counter module

- build-configuration/bom/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-11202
> ISPN-11202 Put jcache-commons in bom

- cli/cli-client/src/main/java/org/infinispan/cli/commands/Batch.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/CliCommand.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/Create.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/Patch.java
- cli/cli-client/src/main/java/org/infinispan/cli/impl/ContextAwareCommandInvocation.java
- cli/cli-client/src/main/java/org/infinispan/cli/impl/ContextImpl.java
- cli/cli-client/src/main/java/org/infinispan/cli/impl/ShellOutputStreamAdapter.java
- cli/cli-client/src/main/java/org/infinispan/cli/logging/Messages.java
- cli/cli-client/src/main/java/org/infinispan/cli/patching/PatchInfo.java
- cli/cli-client/src/main/java/org/infinispan/cli/patching/PatchOperation.java
- cli/cli-client/src/main/java/org/infinispan/cli/patching/PatchTool.java
- cli/cli-client/src/main/java/org/infinispan/cli/patching/ServerFile.java
- cli/cli-client/src/main/resources/help/patch.adoc
- cli/cli-client/src/test/java/org/infinispan/cli/patching/PatchToolTest.java
- cli/cli-client/src/test/resources/patch/v1/bin/different.sh
- cli/cli-client/src/test/resources/patch/v1/bin/same.sh
- cli/cli-client/src/test/resources/patch/v1/server/conf/infinispan.xml
- cli/cli-client/src/test/resources/patch/v2/bin/different.sh
- cli/cli-client/src/test/resources/patch/v2/bin/same.sh
- cli/cli-client/src/test/resources/patch/v2/server/conf/infinispan.xml
- cli/cli-client/src/test/resources/patch/v3/.patches/patches.json
- cli/cli-client/src/test/resources/patch/v3/bin/different.sh
- cli/cli-client/src/test/resources/patch/v3/bin/same.sh
- cli/cli-client/src/test/resources/patch/v3/server/conf/infinispan.xml
- cli/cli-client/src/test/resources/patch/v3/server/data/IGNOREME.txt
- cli/cli-client/src/test/resources/patch/v3/server/lib/IGNOREME.txt
- cli/cli-client/src/test/resources/patch/v3/server/log/IGNOREME.txt
- commons/all/src/main/java/org/infinispan/commons/util/Version.java
https://issues.redhat.com/browse/ISPN-11624
> ISPN-11624 Server Patch Tool

- server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-11643
> [10.1] ISPN-11643 REST connector misinterprets % in query path elements

- core/src/main/java/org/infinispan/manager/impl/AbstractClusterExecutor.java
- core/src/main/java/org/infinispan/manager/impl/LocalClusterExecutor.java
- query/src/main/java/org/infinispan/query/impl/massindex/DistributedExecutorMassIndexer.java
- query/src/test/java/org/infinispan/query/distributed/AsyncMassIndexPerfTest.java
https://issues.redhat.com/browse/ISPN-11710
> ISPN-11710 MassIndexer timeouts after 4 minutes

- core/src/main/java/org/infinispan/manager/impl/AbstractClusterExecutor.java
- core/src/main/java/org/infinispan/manager/impl/LocalClusterExecutor.java
- query/src/main/java/org/infinispan/query/impl/massindex/DistributedExecutorMassIndexer.java
- query/src/test/java/org/infinispan/query/distributed/AsyncMassIndexPerfTest.java
https://issues.redhat.com/browse/ISPN-11710
> [10.1] ISPN-11710 MassIndexer timeouts after 4 minutes

- server/runtime/src/main/java/org/infinispan/server/loader/Loader.java
https://issues.redhat.com/browse/ISPN-11737
> ISPN-11737 Correctly add the server root lib classpath from the loader

- query/src/main/java/org/infinispan/query/impl/massindex/LocalMassIndexerLock.java
- query/src/test/java/org/infinispan/query/distributed/LocalCacheMassIndexerTest.java
https://issues.redhat.com/browse/ISPN-11709
> ISPN-11709 The MassIndexer reports wrong status for local caches

- query/src/main/java/org/infinispan/query/impl/massindex/LocalMassIndexerLock.java
- query/src/test/java/org/infinispan/query/distributed/LocalCacheMassIndexerTest.java
https://issues.redhat.com/browse/ISPN-11709
> [10.1] ISPN-11709 The MassIndexer reports wrong status for local caches

- cli/cli-client/src/main/java/org/infinispan/cli/commands/Batch.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/CliCommand.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/Create.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/Patch.java
- cli/cli-client/src/main/java/org/infinispan/cli/impl/ContextAwareCommandInvocation.java
- cli/cli-client/src/main/java/org/infinispan/cli/impl/ContextImpl.java
- cli/cli-client/src/main/java/org/infinispan/cli/impl/ShellOutputStreamAdapter.java
- cli/cli-client/src/main/java/org/infinispan/cli/logging/Messages.java
- cli/cli-client/src/main/java/org/infinispan/cli/patching/PatchInfo.java
- cli/cli-client/src/main/java/org/infinispan/cli/patching/PatchOperation.java
- cli/cli-client/src/main/java/org/infinispan/cli/patching/PatchTool.java
- cli/cli-client/src/main/java/org/infinispan/cli/patching/ServerFile.java
- cli/cli-client/src/main/resources/help/patch.adoc
- cli/cli-client/src/test/java/org/infinispan/cli/patching/PatchToolTest.java
- cli/cli-client/src/test/resources/patch/v1/bin/different.sh
- cli/cli-client/src/test/resources/patch/v1/bin/same.sh
- cli/cli-client/src/test/resources/patch/v1/server/conf/infinispan.xml
- cli/cli-client/src/test/resources/patch/v2/bin/different.sh
- cli/cli-client/src/test/resources/patch/v2/bin/same.sh
- cli/cli-client/src/test/resources/patch/v2/server/conf/infinispan.xml
- cli/cli-client/src/test/resources/patch/v3/.patches/patches.json
- cli/cli-client/src/test/resources/patch/v3/bin/different.sh
- cli/cli-client/src/test/resources/patch/v3/bin/same.sh
- cli/cli-client/src/test/resources/patch/v3/server/conf/infinispan.xml
- cli/cli-client/src/test/resources/patch/v3/server/data/IGNOREME.txt
- cli/cli-client/src/test/resources/patch/v3/server/lib/IGNOREME.txt
- cli/cli-client/src/test/resources/patch/v3/server/log/IGNOREME.txt
- commons/src/main/java/org/infinispan/commons/util/Version.java
https://issues.redhat.com/browse/ISPN-11624
> [10.1] ISPN-11624 Server Patch Tool

- lucene/directory-provider/src/test/java/org/infinispan/hibernate/search/StoredIndexTest.java
- lucene/directory-provider/src/test/resources/filesystem-loading-infinispan.xml
Fix test failure caused by https://issues.redhat.com/browse/ISPN-11556
> [10.1] ISPN-11556 - Fix StoredIndexTest

- server/runtime/src/main/java/org/infinispan/server/loader/Loader.java
https://issues.redhat.com/browse/ISPN-11737
> [10.1] ISPN-11737 Correctly add the server root lib classpath from the loader

- server/tests/src/test/java/org/infinispan/server/functional/ClusteredIT.java
https://issues.redhat.com/browse/ISPN-11750
> ISPN-11750 ClusteredIT must have RestLoggingResource

- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-11607
> ISPN-11607 Fix blocking LimitedExecutor#addPermit test failures

- component-processor/src/main/java/org/infinispan/component/processor/ComponentAnnotationProcessor.java
https://issues.redhat.com/browse/ISPN-11675
> ISPN-11675 ComponentAnnotationProcessor exception hides compilation error

- cdi/embedded/src/main/java/org/infinispan/cdi/embedded/InfinispanExtensionEmbedded.java
- cdi/embedded/src/test/java/org/infinispan/cdi/embedded/test/cache/specific/Config.java
- core/src/main/java/org/infinispan/configuration/parsing/ConfigurationBuilderHolder.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/test/java/org/infinispan/manager/CacheManagerTest.java
- core/src/test/java/org/infinispan/persistence/support/AsyncStoreWithoutEvictionFunctionalTest.java
- core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
- core/src/test/java/org/infinispan/util/ThreadLocalLeakTest.java
- integrationtests/cdi-weld-se-it/src/test/java/org/infinispan/integrationtests/cdi/weld/Config.java
- spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/AbstractEmbeddedCacheManagerFactory.java
- tools/src/main/java/org/infinispan/tools/store/migrator/TargetStoreFactory.java
- tools/src/main/java/org/infinispan/tools/store/migrator/marshaller/SerializationConfigUtil.java
https://issues.redhat.com/browse/ISPN-11534
> ISPN-11534 Deprecate DefaultCacheManager constructors with default cache

- build-configuration/pom.xml
- pom.xml
~for testing purposes...~
https://issues.redhat.com/browse/ISPN-11535
> ISPN-11535 Remove Transitive Dependencies

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/TransactionContext.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/entry/Modification.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/operations/PrepareTransactionOperation.java
* try to prepare the transaction in the primary owner
https://issues.redhat.com/browse/ISPN-10135
> [10.1.x] ISPN-10135 Performance Regression for HotRod-TX

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11761
> ISPN-11761 Upgrade to 0.5.Final

- core/src/main/java/org/infinispan/transaction/xa/TransactionXaAdapter.java
- core/src/main/java/org/infinispan/transaction/xa/XaTransactionTable.java
- core/src/main/java/org/infinispan/util/concurrent/CompletionStages.java
https://issues.redhat.com/browse/ISPN-11595
> ISPN-11595 Non Blocking Transaction Performance Regression

- core/src/main/java/org/infinispan/configuration/global/TransportConfiguration.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.redhat.com/browse/ISPN-11781
> ISPN-11781 Log the JGroups stack name if one was provided

- jcache/tck-runner-embedded/pom.xml
- jcache/tck-runner-remote/pom.xml
https://issues.redhat.com/browse/ISPN-11771
> ISPN-11771 Change TCK Runner project name

- documentation/src/main/asciidoc/index.asciidoc
- documentation/src/main/asciidoc/stories/assembly_integrating.adoc
- documentation/src/main/asciidoc/titles/getting_started/getting_started.asciidoc
- documentation/src/main/asciidoc/titles/integrating/integrating.asciidoc
- documentation/src/main/asciidoc/titles/overview/overview.asciidoc
- documentation/src/main/asciidoc/topics/integrations_apache_lucene.adoc
- documentation/src/main/asciidoc/topics/integrations_hibernate_cache.adoc
- documentation/src/main/asciidoc/topics/integrations_hibernate_ogm.adoc
- documentation/src/main/asciidoc/topics/integrations_hibernate_search.adoc
- documentation/src/main/asciidoc/topics/integrations_spring.adoc
https://issues.redhat.com/browse/ISPN-11742
> ISPN-11742 updating index page and integrations doc

- cli/cli-client/src/main/java/org/infinispan/cli/CLI.java
- commons/src/main/java/org/infinispan/commons/util/Version.java
- commons/src/main/resources/META-INF/infinispan-version.properties
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/security/UserTool.java
- tools/src/main/java/org/infinispan/tools/store/migrator/StoreMigrator.java
https://issues.redhat.com/browse/ISPN-11511
> [10.1] ISPN-11511 More consistent branding

- anchored-keys/src/test/java/org/infinispan/anchored/ScaleUpWithoutStateTransferTest.java
- anchored-keys/src/test/resources/config/anchored.xml
https://issues.redhat.com/browse/ISPN-11805
> ISPN-11805 Fix tests in Infinispan Anchored Keys

- core/src/test/java/org/infinispan/persistence/support/AsyncStoreWithoutEvictionFunctionalTest.java
https://issues.redhat.com/browse/ISPN-11806
> ISPN-11806 AsyncStoreWithoutEvictionFunctionalTest remove data from core

- server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
- server/core/src/main/java/org/infinispan/server/core/utils/ManageableThreadPoolExecutorService.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ServerHotRodBlockHoundIntegration.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/ServerHotRodTestBlockHoundIntegration.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/logging/HotRodAccessLoggingTest.java
https://issues.redhat.com/browse/ISPN-11532
https://issues.redhat.com/browse/ISPN-11531
https://issues.redhat.com/browse/ISPN-11755
> ISPN-11532 HotRod Worker Thread Pool

- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
https://issues.redhat.com/browse/ISPN-11667
Backport #8302
> ISPN-11667 Deal with ignore caches. Status Ignored

- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
https://issues.redhat.com/browse/ISPN-11667
Backport of #8301
> [10.1.x] ISPN-11667 Deal with ignore caches. Status Ignored

- core/src/main/java/org/infinispan/configuration/cache/AuthorizationConfigurationBuilder.java
- core/src/main/java/org/infinispan/security/impl/AuthorizationHelper.java
- core/src/test/java/org/infinispan/security/BaseAuthorizationTest.java
- core/src/test/java/org/infinispan/security/CacheImplicitRolesAuthorizationTest.java
- documentation/src/main/asciidoc/topics/config_examples/cache_authorization_explicit_roles.xml
- documentation/src/main/asciidoc/topics/security.adoc
- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
https://issues.redhat.com/browse/ISPN-11763
> ISPN-11763 Implicit cache authorization

- build-configuration/pom.xml
- client/hotrod-client/pom.xml
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
https://issues.redhat.com/browse/ISPN-11815
> ISPN-11815 Elytron 1.11.4

- documentation/src/main/asciidoc/stories/assembly_cli_cache_operations.adoc
- documentation/src/main/asciidoc/topics/proc_cli_adding_entries.adoc
- documentation/src/main/asciidoc/topics/proc_cli_creating_caches_files.adoc
- documentation/src/main/asciidoc/topics/proc_cli_creating_caches_templates.adoc
- documentation/src/main/asciidoc/topics/proc_cli_deleting_entries.adoc
- documentation/src/main/asciidoc/topics/proc_cli_dropping_caches.adoc
- documentation/src/main/asciidoc/topics/proc_cli_resetting_dropping_counters.adoc
https://issues.redhat.com/browse/ISPN-11826
> ISPN-11826 topic for deleting caches via CLI

- core/src/main/java/org/infinispan/configuration/cache/ConfigurationBuilder.java
- hibernate/cache-commons/src/main/resources/org/infinispan/hibernate/cache/commons/builder/infinispan-configs-local.xml
- hibernate/cache-commons/src/main/resources/org/infinispan/hibernate/cache/commons/builder/infinispan-configs.xml
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/InfinispanRegionFactoryTestCase.java
- hibernate/cache-v51/src/main/java/org/infinispan/hibernate/cache/v51/InfinispanRegionFactory.java
- hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/InfinispanRegionFactory.java
- jcache/embedded/src/main/java/org/infinispan/jcache/embedded/ConfigurationAdapter.java
- query-core/src/main/java/org/infinispan/query/core/impl/QueryCache.java
- server/runtime/src/main/java/org/infinispan/server/logging/events/LifecycleCallbacks.java
- server/runtime/src/main/resources/infinispan-defaults.xml
https://issues.redhat.com/browse/ISPN-11424
> ISPN-11424 Remove deprecated memory configurations from internal caches

- server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseDecoder.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
https://issues.redhat.com/browse/ISPN-11841
> [9.4.x] ISPN-11841 Listener leaking and produce OOM error

- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMergeTest.java
https://issues.redhat.com/browse/ISPN-11840
> ISPN-11840 HotRodMergeTest updated to use numOwners=2

- commons/all/src/main/java/org/infinispan/commons/dataconversion/MediaTypeResolver.java
- commons/all/src/main/java/org/infinispan/commons/internal/CommonsBlockHoundIntegration.java
- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
- lock/src/main/java/org/infinispan/lock/impl/ClusteredLockBlockHoundIntegration.java
- query/src/main/java/org/infinispan/query/MassIndexer.java
- query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
- query/src/main/java/org/infinispan/query/backend/SegmentListener.java
- query/src/main/java/org/infinispan/query/impl/massindex/DistributedExecutorMassIndexer.java
- query/src/main/java/org/infinispan/query/impl/massindex/DistributedMassIndexerLock.java
- query/src/main/java/org/infinispan/query/impl/massindex/LocalMassIndexerLock.java
- query/src/main/java/org/infinispan/query/impl/massindex/MassIndexLock.java
- query/src/test/java/org/infinispan/query/distributed/AsyncMassIndexPerfTest.java
- query/src/test/java/org/infinispan/query/distributed/AsyncMassIndexTest.java
- query/src/test/java/org/infinispan/query/distributed/DistributedMassIndexingTest.java
- query/src/test/java/org/infinispan/query/distributed/LocalCacheMassIndexerTest.java
- query/src/test/java/org/infinispan/query/distributed/MassIndexingTest.java
- server/core/pom.xml
- server/core/src/main/java/org/infinispan/server/core/ServerCoreBlockHoundIntegration.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ServerHotRodBlockHoundIntegration.java
- server/rest/pom.xml
- server/rest/src/main/java/org/infinispan/rest/ServerRestBlockHoundIntegration.java
- server/rest/src/main/java/org/infinispan/rest/resources/BaseCacheResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java
- server/rest/src/test/java/org/infinispan/rest/ServerRestTestBlockHoundIntegration.java
- server/rest/src/test/java/org/infinispan/rest/client/NettyHttpClient.java
https://issues.redhat.com/browse/ISPN-11831
https://issues.redhat.com/browse/ISPN-11836
// Do not close the following ones
https://issues.redhat.com/browse/ISPN-11731
https://issues.redhat.com/browse/ISPN-11834
https://issues.redhat.com/browse/ISPN-11835
> ISPN-11831 Rest Server BlockHound

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/HotRodURI.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/security/BasicCallbackHandler.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/AuthenticationTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
https://issues.redhat.com/browse/ISPN-11820
> ISPN-11820 Hot Rod URI

- documentation/src/main/asciidoc/stories/assembly_cli_cache_operations.adoc
- documentation/src/main/asciidoc/topics/proc_cli_adding_entries.adoc
- documentation/src/main/asciidoc/topics/proc_cli_creating_caches_files.adoc
- documentation/src/main/asciidoc/topics/proc_cli_creating_caches_templates.adoc
- documentation/src/main/asciidoc/topics/proc_cli_deleting_entries.adoc
- documentation/src/main/asciidoc/topics/proc_cli_dropping_caches.adoc
- documentation/src/main/asciidoc/topics/proc_cli_resetting_dropping_counters.adoc
https://issues.redhat.com/browse/ISPN-11826
> [10.1.x] ISPN-11826 topic for deleting caches via CLI

- documentation/src/main/asciidoc/topics/dependencies_maven/jcache-remote.xml
- documentation/src/main/asciidoc/topics/jcache.adoc
https://issues.redhat.com/browse/ISPN-11848 
> ISPN-11848 remote jcache dependency

- documentation/src/main/asciidoc/topics/dependencies_maven/jcache-remote.xml
- documentation/src/main/asciidoc/topics/jcache.adoc
https://issues.redhat.com/browse/ISPN-11848 
Here's the backport. Thanks @pruivo !
> [10.1.x] ISPN-11848 remote jcache dependency

- core/src/main/java/org/infinispan/configuration/cache/StateTransferConfiguration.java
Fix wrong javadoc
https://issues.redhat.com/browse/ISPN-11860
> ISPN-11860 correction for wrong Javadoc classheader

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-11842
Backport #8330
> ISPN-11842 Upgrade Spring Boot 2.3 dependencies

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
- server/tests/src/test/resources/configuration/log4j2-trace.xml
https://issues.redhat.com/browse/ISPN-11817
> ISPN-11817 Support trace log messages for ContainerInfinispanServerDriver

- documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
- documentation/src/main/asciidoc/topics/json_examples/rest_protobuf_create_update_schema_response.json
- documentation/src/main/asciidoc/topics/json_examples/rest_protobuf_schemas_response.json
- documentation/src/main/asciidoc/topics/ref_rest_protobuf.adoc
- server/rest/src/main/java/org/infinispan/rest/RestServer.java
- server/rest/src/main/java/org/infinispan/rest/operations/exceptions/NoDataFoundException.java
- server/rest/src/main/java/org/infinispan/rest/operations/exceptions/NoKeyException.java
- server/rest/src/main/java/org/infinispan/rest/resources/ProtobufResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/ProtobufResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
- server/rest/src/test/resources/error.proto
https://issues.redhat.com/browse/ISPN-10446
> ISPN-10446 Protobuf resource

- server/hotrod/src/test/java/org/infinispan/server/hotrod/logging/HotRodAccessLoggingTest.java
* Revert test change as the netty event loop is no longer replaced
https://issues.redhat.com/browse/ISPN-11532
> ISPN-11532 Replace HotRod worker thread pool

- documentation/src/main/asciidoc/index.asciidoc
https://issues.redhat.com/browse/ISPN-11808
This adds links to versioned docs for the Operator on master. Depends on this change to the site: infinispan/infinispan.github.io#109
> add versioned operator docs

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11819
> ISPN-11819 Prevent ContainerInfinispanServerDriver erroneous state with provided server directory

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheContainer.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfiguration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheCreateOnAccessTest.java
https://issues.redhat.com/browse/ISPN-11852
> ISPN-11852 Create new RemoteCacheConfigurations in a Configuration

- cli/cli-client/src/main/resources/help/patch.adoc
Fixes:
```
[disconnected]> help patch
java.io.IOException: File did not include the correct header.
```
> Fix patch help file

- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMergeTest.java
https://issues.redhat.com/browse/ISPN-11840
> [10.1.x] ISPN-11840 HotRodMergeTest updated to use numOwners=2

- core/src/main/java/org/infinispan/AdvancedCache.java
- core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingAdvancedCache.java
- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/main/java/org/infinispan/cache/impl/DecoratedCache.java
- core/src/main/java/org/infinispan/cache/impl/EncoderCache.java
- core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
- core/src/main/java/org/infinispan/cache/impl/StatsCollectingCache.java
- core/src/main/java/org/infinispan/commands/functional/Mutations.java
- core/src/main/java/org/infinispan/encoding/DataConversion.java
- core/src/main/java/org/infinispan/encoding/impl/StorageConfigurationManager.java
- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
- core/src/main/java/org/infinispan/functional/impl/EntryViews.java
- core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java
- core/src/main/java/org/infinispan/interceptors/xsite/NonTransactionalBackupInterceptor.java
- core/src/main/java/org/infinispan/marshall/core/EncoderRegistry.java
- core/src/main/java/org/infinispan/marshall/core/EncoderRegistryImpl.java
- core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java
- core/src/main/java/org/infinispan/util/EntryWrapper.java
- core/src/test/java/org/infinispan/api/flags/FlagsEnabledTest.java
- core/src/test/java/org/infinispan/functional/decorators/FunctionalAdvancedCache.java
- core/src/test/java/org/infinispan/notifications/cachelistener/BaseCacheNotifierImplInitialTransferTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/CacheNotifierImplTest.java
- core/src/test/java/org/infinispan/notifications/cachelistener/OnlyPrimaryOwnerTest.java
- core/src/test/java/org/infinispan/security/SecureCacheTestDriver.java
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/util/ClassLoaderAwareCache.java
- query/src/test/java/org/infinispan/query/impl/EagerIteratorTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufRemoteQueryManager.java
https://issues.redhat.com/browse/ISPN-11629
> ISPN-11629 Initialize DataConversion storage media type only once

- server/core/src/main/java/org/infinispan/server/core/ServerCoreBlockHoundIntegration.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/ServerHotRodBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-11872
> ISPN-11872 CertificateTest test blocking

- commons/all/src/main/java/org/infinispan/commons/persistence/Store.java
https://issues.redhat.com/browse/ISPN-11865
Depends on https://github.com/infinispan/infinispan/pull/8316
> ISPN-11865 Deprecate the @Store annotation

- core/src/main/java/org/infinispan/configuration/cache/PartitionHandlingConfiguration.java
- core/src/main/java/org/infinispan/configuration/cache/PartitionHandlingConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
https://issues.redhat.com/browse/ISPN-11877
> ISPN-11877 Remove PartitionHandling.ENABLED

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/persistence/spi/AdvancedCacheExpirationWriter.java
- core/src/main/java/org/infinispan/persistence/spi/AdvancedCacheLoader.java
- core/src/main/java/org/infinispan/persistence/spi/AdvancedCacheWriter.java
- core/src/main/java/org/infinispan/persistence/spi/AdvancedLoadWriteStore.java
- core/src/main/java/org/infinispan/persistence/spi/CacheLoader.java
- core/src/main/java/org/infinispan/persistence/spi/CacheWriter.java
- core/src/main/java/org/infinispan/persistence/spi/ExternalStore.java
- core/src/main/java/org/infinispan/persistence/spi/InitializationContext.java
- core/src/main/java/org/infinispan/persistence/spi/NonBlockingStore.java
- core/src/main/java/org/infinispan/persistence/spi/SegmentedAdvancedLoadWriteStore.java
- core/src/main/java/org/infinispan/persistence/spi/TransactionalCacheWriter.java
- core/src/main/java/org/infinispan/util/concurrent/BlockingManager.java
- core/src/main/java/org/infinispan/util/concurrent/NonBlockingManager.java
https://issues.redhat.com/browse/ISPN-10373
Contains mostly Javadoc, but there are a few changes regarding characteristics and segmentation that were caught while writing docs.
> ISPN-10373 Store/Loader Non blocking SPI Documentation

- core/src/test/java/org/infinispan/distribution/DistSyncL1FuncTest.java
- core/src/test/java/org/infinispan/partitionhandling/BaseTxPartitionAndMergeTest.java
- core/src/test/java/org/infinispan/test/AbstractCacheTest.java
- core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java
https://issues.redhat.com/browse/ISPN-11857
> ISPN-11857 eventually() default poll interval is too long

- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_authz_nix.adoc
- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_authz_win.adoc
- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_nix.adoc
- documentation/src/main/asciidoc/topics/cmd_examples/user_tool_win.adoc
- documentation/src/main/asciidoc/topics/proc_adding_server_users.adoc
- documentation/src/main/asciidoc/topics/proc_server_user_tool.adoc
- documentation/src/main/asciidoc/topics/proc_starting_server.adoc
- documentation/src/main/asciidoc/topics/ref_rest_security.adoc
- server/runtime/src/main/server/README.md
https://issues.redhat.com/browse/ISPN-11871
> ISPN-11871 cli user command instead of user-tool

- server/runtime/src/main/java/org/infinispan/server/Extensions.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-11837
https://issues.redhat.com/browse/ISPN-11849
> ISPN-11849 ParamKeyValueFilterConverterFactory missing from Server Extensions

- build-configuration/pom.xml
> Console 0.6.Final

- cli/cli-client/src/main/java/org/infinispan/cli/patching/PatchTool.java
- commons/all/src/main/java/org/infinispan/commons/util/Version.java
https://issues.redhat.com/browse/ISPN-11919
> ISPN-11919 Patch tool should use the brand version

- build-configuration/pom.xml
- wildfly/feature-pack/pom.xml
https://issues.redhat.com/browse/ISPN-11908
> ISPN-11908 Fix Wildfly version.

- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
~~https://issues.redhat.com/browse/ISPN-11889~~
> ISPN-11889 Remove deprecated parser attributes

- documentation/src/main/asciidoc/topics/dependencies_maven/protostream-processor.xml
https://issues.redhat.com/browse/ISPN-11924
> ISPN-11924 Protostream Processor Dependency XML is incorrect

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/persistence/spi/InitializationContext.java
- core/src/main/java/org/infinispan/persistence/spi/NonBlockingStore.java
- core/src/main/java/org/infinispan/util/concurrent/BlockingManager.java
- core/src/main/java/org/infinispan/util/concurrent/NonBlockingManager.java
https://issues.redhat.com/browse/ISPN-11896
> ISPN-11896 non blocking cache store SPI docs

- query/src/main/java/org/infinispan/query/impl/massindex/DistributedExecutorMassIndexer.java
- query/src/test/java/org/infinispan/query/distributed/MassIndexingTest.java
https://issues.redhat.com/browse/ISPN-11891
> ISPN-11891 MassIndexingTest#testOverlappingMassIndexers random failures

- core/src/main/java/org/infinispan/container/entries/MVCCEntry.java
- core/src/main/java/org/infinispan/container/entries/ReadCommittedEntry.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheWriterInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/DistCacheWriterInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/TransactionalStoreInterceptor.java
- core/src/main/java/org/infinispan/persistence/async/AsyncNonBlockingStore.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManager.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerStub.java
- core/src/main/java/org/infinispan/persistence/spi/ExternalNonBlockingStore.java
- core/src/main/java/org/infinispan/persistence/spi/NonBlockingStore.java
- core/src/main/java/org/infinispan/persistence/support/DelegatingNonBlockingStore.java
- core/src/main/java/org/infinispan/persistence/support/DelegatingPersistenceManager.java
- core/src/main/java/org/infinispan/persistence/support/NonBlockingStoreAdapter.java
- core/src/main/java/org/infinispan/persistence/support/SegmentPublisherWrapper.java
- core/src/main/java/org/infinispan/persistence/support/SingleSegmentPublisher.java
- core/src/test/java/org/infinispan/commands/PutMapCommandTest.java
- core/src/test/java/org/infinispan/persistence/BaseNonBlockingStoreTest.java
- core/src/test/java/org/infinispan/persistence/WriteBehindFaultToleranceTest.java
- core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
- core/src/test/java/org/infinispan/persistence/support/EnsureNonBlockingStore.java
- core/src/test/java/org/infinispan/persistence/support/WaitNonBlockingStore.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stores/TxStoreTest.java
* Rework batch to allow for atomic write and remove
https://issues.redhat.com/browse/ISPN-10373
The RocksDBStore implementation can be found here https://github.com/infinispan/infinispan/pull/8405/files#diff-f32efbe49859e690ae6743ec1daf7608R210
> ISPN-10373 Store/Loader Non blocking SPI batch method

- query/src/test/java/org/infinispan/query/distributed/MassIndexingTest.java
https://issues.redhat.com/browse/ISPN-11891
> ISPN-11891 MassIndexingTest#testOverlappingMassIndexers failures

- server/runtime/src/test/java/org/infinispan/server/license/LicenseTest.java
https://issues.redhat.com/browse/ISPN-11839
> ISPN-11839 Create a test to check licenses in distributions

- server/rest/src/main/java/org/infinispan/rest/ALPNHandler.java
- server/rest/src/main/java/org/infinispan/rest/NettyRestResponse.java
- server/rest/src/main/java/org/infinispan/rest/ResponseHeader.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
https://issues.redhat.com/browse/ISPN-11941
> ISPN-11941 Add custom response headers permissions in CORS for localhost

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-11929
> ISPN-11929 Add query boolean property

- documentation/src/main/asciidoc/topics/proc_cli_registering_protobuf_schema.adoc
- documentation/src/main/asciidoc/topics/query.adoc
https://issues.redhat.com/browse/ISPN-11825 - for 10.1.x only. Will address changes for 11 separately.
> [10.1.x] ISPN-11825 update procedure to register schemas with CLI

- server/runtime/src/main/resources/infinispan-defaults.xml
https://issues.redhat.com/browse/ISPN-11938
> ISPN-11398 Add template for a Protobuf cache

- build-configuration/pom.xml
- core/src/main/java/org/infinispan/container/impl/BoundedSegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/impl/DefaultDataContainer.java
- core/src/main/java/org/infinispan/container/impl/PeekableTouchableCaffeineMap.java
* Update peek to use caffeine getIfPresentQuietly
https://issues.redhat.com/browse/ISPN-11944
> ISPN-11944 Update caffeine to 2.8.4

- core/src/main/java/org/infinispan/interceptors/impl/TransactionalStoreInterceptor.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStoreFunctionalTest.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStoreTxFunctionalTest.java
https://issues.redhat.com/browse/ISPN-11937
Added tests and fixed a few various bugs with transactional, where it was just invoking the bulk method instead.
> ISPN-11937 JDBCStringBasedStore needs test around a rollback occurring

- core/src/main/java/org/infinispan/configuration/cache/AbstractStoreConfigurationBuilder.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- documentation/src/main/asciidoc/topics/proc_creating_custom_cache_stores.adoc
- documentation/src/main/asciidoc/topics/proc_deploying_custom_cache_stores.adoc
- server/tests/src/test/java/org/infinispan/server/persistence/CustomNonBlockingStore.java
- server/tests/src/test/java/org/infinispan/server/persistence/CustomStoreOperationsIT.java
- server/tests/src/test/resources/configuration/CustomStoreTest.xml
https://issues.redhat.com/browse/ISPN-11959
> ISPN-11959 Add custom NonBlockingStore server test

- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java
- server/tests/src/test/java/org/infinispan/server/functional/XSiteRestCacheOperations.java
https://issues.redhat.com/browse/ISPN-11961
> ISPN-11961 DefaultIracManager should handle ImmutableSet

- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
https://issues.redhat.com/browse/ISPN-11945
> ISPN-11945 JGroups Kubernetes stack should set 'port_range="0"'

- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/AbstractJBossMarshaller.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/CheckedClassResolver.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/DefaultContextClassResolver.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/ExtendedRiverMarshaller.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/ExtendedRiverUnmarshaller.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/JBossExternalizerAdapter.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/JBossMarshallerFactory.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/RiverCloseListener.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/SerializeWithExtFactory.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/core/JBossMarshaller.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/core/JBossUserMarshaller.java
https://issues.redhat.com/browse/ISPN-11946
> ISPN-11946 Deprecate JBossUserMarshaller and associated classes

- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/TokenRealmConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/TokenRealmConfigurationBuilder.java
- server/runtime/src/main/resources/schema/infinispan-server-11.0.xsd
- server/runtime/src/test/resources/configuration/ServerConfigurationParserTest.xml
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationKeyCloakIT.java
- server/tests/src/test/java/org/infinispan/server/test/core/KeyCloakServerRule.java
- server/tests/src/test/resources/configuration/security/keycloak-oauth2.xml
- server/tests/src/test/resources/keycloak/infinispan-keycloak-realm.json
https://issues.redhat.com/browse/ISPN-11879
> ISPN-11879 KeyCloak console login

- documentation/src/main/asciidoc/topics/ref_rest_cors.adoc
- server/rest/src/main/java/org/infinispan/rest/ALPNHandler.java
- server/rest/src/main/java/org/infinispan/rest/CorsUtil.java
- server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java
- server/rest/src/main/java/org/infinispan/rest/RequestHeader.java
- server/rest/src/main/java/org/infinispan/rest/ResponseHeader.java
- server/rest/src/main/java/org/infinispan/rest/logging/Log.java
- server/rest/src/main/java/org/infinispan/rest/resources/BaseCacheResource.java
- server/rest/src/test/java/org/infinispan/rest/assertion/ResponseAssertion.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
https://issues.redhat.com/browse/ISPN-11971
> ISPN-11971 Add a JVM property to enable all CORS permissions

- build-configuration/pom.xml
I got carried away with the labels
> 11.0 Codename: Corona Extra

- commons/all/src/main/java/org/infinispan/commons/util/Util.java
- etc/log4j2.xml
- server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractServerConfigBuilder.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanServerTestConfiguration.java
- server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
- server/tests/src/test/java/org/infinispan/server/extensions/ScriptingTasks.java
- server/tests/src/test/java/org/infinispan/server/extensions/ServerTasks.java
- server/tests/src/test/java/org/infinispan/server/functional/ClusteredIT.java
- server/tests/src/test/java/org/infinispan/server/functional/ConcurrentShutdownRestIT.java
- server/tests/src/test/java/org/infinispan/server/functional/RestLoggingResource.java
- server/tests/src/test/java/org/infinispan/server/functional/RestRouter.java
- server/tests/src/test/java/org/infinispan/server/functional/RestServerResource.java
- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeIT.java
- server/tests/src/test/java/org/infinispan/server/functional/ShutdownRestIT.java
- server/tests/src/test/resources/cli/batch.cli
https://issues.redhat.com/browse/ISPN-11850
https://issues.redhat.com/browse/ISPN-11936
https://issues.redhat.com/browse/ISPN-11948
ISPN-11850 should remain open as there are still tests that won't work with the CONTAINER driver. These will be fixed at a later date.
> Server Testsuite changes for Native Image

- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/manager/EmbeddedCacheManager.java
- core/src/main/java/org/infinispan/manager/impl/AbstractDelegatingEmbeddedCacheManager.java
- core/src/main/java/org/infinispan/manager/impl/UnwrappingEmbeddedCacheManager.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/manager/CacheManagerTest.java
https://issues.redhat.com/browse/ISPN-11894
> ISPN-11894 Remove EmbeddedCacheManager getCache explicit configuration name

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
- server/tests/pom.xml
- server/tests/src/test/resources/configuration/cache-container/clustered-authz.xml
https://issues.redhat.com/browse/ISPN-11861
> ISPN-11861 ContainerInfinispanServerDriver is not setting the JGroups stack to the server

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/HotRodNonIndexedSingleFileStoreQueryTest.java
- core/src/main/java/org/infinispan/configuration/cache/SingleFileStoreConfigurationBuilder.java
- core/src/main/java/org/infinispan/persistence/PersistenceUtil.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/eviction/impl/EvictionWithConcurrentOperationsTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreDistListenerFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/MultiStoresFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/file/SingleFileStoreStressTest.java
- core/src/test/java/org/infinispan/persistence/support/AsyncStoreWithoutEvictionFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/support/BatchAsyncStoreTest.java
- core/src/test/java/org/infinispan/statetransfer/ReplStateTransferCacheLoaderTest.java
- core/src/test/resources/configs/named-cache-test.xml
- documentation/src/main/asciidoc/topics/proc_setting_persistent_location.adoc
- persistence/rocksdb/output.txt
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfigurationBuilder.java
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/configuration/SoftIndexFileStoreConfigurationBuilder.java
- persistence/soft-index/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreTest.java
- query/src/test/java/org/infinispan/query/backend/QueryInterceptorTest.java
- query/src/test/java/org/infinispan/query/dsl/embedded/NonIndexedSingleFileStoreQueryDslConditionsTest.java
- query/src/test/java/org/infinispan/query/persistence/InconsistentIndexesAfterRestartTest.java
https://issues.redhat.com/browse/ISPN-11845
>     ISPN-11845 SingleFileStore location validation should be skipped when global state is disabled

- documentation/src/main/asciidoc/topics/proc_upgrading_sync_data.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- documentation/src/main/asciidoc/topics/ref_rest_clusters.adoc
- documentation/src/main/asciidoc/topics/ref_rest_counters.adoc
- documentation/src/main/asciidoc/topics/ref_rest_rolling.adoc
- documentation/src/main/asciidoc/topics/ref_rest_servers.adoc
- documentation/src/main/asciidoc/topics/ref_rest_xsite.adoc
- documentation/src/main/asciidoc/topics/ref_rest_xsite_cache_managers.adoc
- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/main/java/org/infinispan/rest/resources/ClusterResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/LoginResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/TasksResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
https://issues.redhat.com/browse/ISPN-11967
> ISPN-11967 Support POST for actions with side effects in the REST API

- commons-test/src/main/java/org/infinispan/commons/test/BlockHoundHelper.java
- commons-test/src/main/java/org/infinispan/commons/test/CommonsTestBlockHoundIntegration.java
- core/src/main/java/org/infinispan/persistence/spi/NonBlockingStore.java
- core/src/main/java/org/infinispan/util/concurrent/BlockingManager.java
- core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
- core/src/test/java/org/infinispan/persistence/BaseNonBlockingStoreTest.java
- core/src/test/java/org/infinispan/persistence/support/WaitNonBlockingStore.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- core/src/test/java/org/infinispan/util/PersistenceMockUtil.java
- core/src/test/java/org/infinispan/xsite/irac/persistence/BaseIracPersistenceTest.java
- persistence/rocksdb/pom.xml
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/internal/RocksDBBlockHoundIntegration.java
- persistence/rocksdb/src/test/java/org/infinispan/persistence/rocksdb/RocksDBStoreTest.java
https://issues.redhat.com/browse/ISPN-11930
This relies upon https://github.com/infinispan/infinispan/pull/8400
> ISPN-11930 Rocks db converted to new SPI

- server/rest/src/main/java/org/infinispan/rest/RequestHeader.java
https://issues.redhat.com/browse/ISPN-11987
> ISPN-11987 Authorization header blocked by CORS

- core/src/test/java/org/infinispan/statetransfer/PrepareTimeoutTest.java
I haven't created a separate JIRA, as the test failure was caused directly by my https://github.com/infinispan/infinispan/pull/8374 changes.
> ISPN-11893 Fix PrepareTimeoutTest

- core/src/test/java/org/infinispan/util/ThreadLocalLeakTest.java
https://issues.redhat.com/browse/ISPN-11989
> ISPN-11989 Fix ThreadLocalLeakTest

- documentation/src/main/asciidoc/stories/assembly_persistence.adoc
https://issues.redhat.com/browse/ISPN-11988
> ISPN-11988 fix invalid include directive

- commons/jdk11/pom.xml
https://issues.redhat.com/browse/ISPN-11990
> ISPN-11990 JDK 11 modules do not compile in IntelliJ

- documentation/src/main/asciidoc/topics/ref_cache_store_remote.adoc
- documentation/src/main/asciidoc/topics/ref_rolling_upgrade_remote_store.adoc
https://issues.redhat.com/browse/ISPN-11991
> ISPN-11911 remote store segmentation note

- core/src/main/java/org/infinispan/encoding/impl/StorageConfigurationManager.java
https://issues.redhat.com/browse/ISPN-11980
> ISPN-11980 Storage type HEAP should default to application/x-java-object

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteNonIndexedQueryStringTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDslConditionsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryStringTest.java
- documentation/src/main/asciidoc/topics/upgrading.adoc
- query/src/main/java/org/infinispan/query/backend/SearchableCacheConfiguration.java
- server/rest/src/test/resources/person.proto
https://issues.redhat.com/browse/ISPN-11795
> ISPN-11795 Entity mapping deprecations

- build-configuration/pom.xml
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteNonIndexedQueryStringTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDslConditionsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryStringTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingTagHandler.java
* upgrade to protostream 4.3.3.Final
> IPROTO-142 Make some fields in bank.proto @SortableField

- build-configuration/pom.xml
- javadoc/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-12001
> ISPN-12001 Add jboss-parent

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
https://issues.redhat.com/browse/ISPN-11996
> ISPN-11996 Allow customize memory and memory swap for Testcontainers images

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12007
> ISPN-12007 Elytron 1.12.1.Final

- server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
https://issues.redhat.com/browse/ISPN-12006
> ISPN-12006 Test upload schema with CLI

- documentation/src/main/asciidoc/index.asciidoc
- documentation/src/main/asciidoc/js/js.js
https://issues.redhat.com/browse/ISPN-11913
> ISPN-11913 search and improved index

- persistence/rest/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-12010
> ISPN-12010 Remove Apache Commons Codec

- pom.xml
https://issues.redhat.com/browse/ISPN-12012
> ISPN-12012 Force the same Guava version in all transitive dependencies

- documentation/pom.xml
- pom.xml
* Upgrade its transitive dependencies:
Maven-Core to 3.5.4
Plexus-utils to 3.1.0
https://issues.redhat.com/browse/ISPN-12014
> ISPN-12014 Upgrade mojo-executor

- build-configuration/pom.xml
- pom.xml
* Overwrite the following transitive dependencies version:
* Apache Avro to 1.9.1
* Dom4j to 2.1.3
https://issues.redhat.com/browse/ISPN-12009
> ISPN-12009 Upgrade Hibernate to latest micro

- core/src/test/java/org/infinispan/persistence/PersistenceCompatibilityTest.java
- persistence/jpa/src/test/resources/META-INF/persistence.xml
https://issues.redhat.com/browse/ISPN-12018
> ISPN-12018 Fix JpaStoreCompatibilityTest failure

- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/EntitiesAndCollectionsInSameRegionTest.java
- pom.xml
https://issues.redhat.com/browse/ISPN-12013
> ISPN-12013 Upgrade H2 database engine to 1.4.200

- client/hotrod-client/pom.xml
- commons/all/src/main/java/org/infinispan/commons/util/SslContextFactory.java
- pom.xml
- server/hotrod/pom.xml
- server/rest/pom.xml
- server/router/pom.xml
https://issues.redhat.com/browse/ISPN-12019
> ISPN-12019 OpenSSL init

- pom.xml
https://issues.redhat.com/browse/ISPN-12017
> ISPN-12017 Set java8.home property to java8-test profile

- archetypes/README.md
- archetypes/client/pom.xml
- archetypes/client/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetypes/client/src/main/resources/archetype-resources/pom.xml
- archetypes/client/src/main/resources/archetype-resources/src/main/java/Application.java
- archetypes/client/src/main/resources/archetype-resources/src/main/resources/hotrod-client.properties
- archetypes/client/src/test/resources/projects/test/archetype.properties
- archetypes/client/src/test/resources/projects/test/goal.txt
- archetypes/embedded/pom.xml
- archetypes/embedded/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetypes/embedded/src/main/resources/archetype-resources/pom.xml
- archetypes/embedded/src/main/resources/archetype-resources/src/main/java/Application.java
- archetypes/embedded/src/main/resources/archetype-resources/src/main/resources/infinispan-clustered-kubernetes.xml
- archetypes/embedded/src/main/resources/archetype-resources/src/main/resources/infinispan-clustered-tcp.xml
- archetypes/embedded/src/main/resources/archetype-resources/src/main/resources/infinispan-clustered-udp.xml
- archetypes/embedded/src/main/resources/archetype-resources/src/main/resources/infinispan-local.xml
- archetypes/embedded/src/test/resources/projects/test/archetype.properties
- archetypes/embedded/src/test/resources/projects/test/goal.txt
- archetypes/pom.xml
- archetypes/store/pom.xml
- archetypes/store/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetypes/store/src/main/resources/archetype-resources/pom.xml
- archetypes/store/src/main/resources/archetype-resources/src/main/java/CustomStore.java
- archetypes/store/src/main/resources/archetype-resources/src/main/java/CustomStoreConfiguration.java
- archetypes/store/src/main/resources/archetype-resources/src/main/java/CustomStoreConfigurationBuilder.java
- archetypes/store/src/main/resources/archetype-resources/src/main/java/CustomStoreConfigurationParser.java
- archetypes/store/src/test/resources/projects/test/archetype.properties
- archetypes/store/src/test/resources/projects/test/goal.txt
- pom.xml
https://issues.redhat.com/browse/ISPN-11952
https://issues.redhat.com/browse/ISPN-11953
https://issues.redhat.com/browse/ISPN-11956
https://issues.redhat.com/browse/ISPN-11957
~~Client ~~and Store~~ archetype to be added.~~
> ISPN-11952 Revive Infinispan Archetypes

- pom.xml
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/ContainerDatabase.java
- server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerRule.java
- server/tests/pom.xml
- server/tests/src/test/java/org/infinispan/server/functional/MemcachedOperations.java
- server/tests/src/test/java/org/infinispan/server/functional/RestOperations.java
- server/tests/src/test/java/org/infinispan/server/persistence/AsyncJdbcStringBasedCacheStore.java
- server/tests/src/test/java/org/infinispan/server/persistence/JdbcConfigurationUtil.java
- server/tests/src/test/java/org/infinispan/server/persistence/JdbcStringBasedCacheStorePassivation.java
- server/tests/src/test/java/org/infinispan/server/persistence/PersistenceIT.java
- server/tests/src/test/java/org/infinispan/server/persistence/TableManipulation.java
- server/tests/src/test/resources/database/h2.properties
- server/tests/src/test/resources/database/mysql.properties
https://issues.redhat.com/browse/ISPN-11151
> ISPN-11151 - Migrating some remote tests from jdg-functional-tests to upstream

- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.redhat.com/browse/ISPN-12045
> ISPN-12045 Clarify jboss-marshalling deprecation message

- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- documentation/src/main/asciidoc/stories/assembly_server_statistics.adoc
- documentation/src/main/asciidoc/stories/assembly_statistics.adoc
- documentation/src/main/asciidoc/stories/assembly_xsite_cli.adoc
- documentation/src/main/asciidoc/stories/assembly_xsite_jmx.adoc
- documentation/src/main/asciidoc/stories/assembly_xsite_monitoring.adoc
- documentation/src/main/asciidoc/stories/assembly_xsite_operations.adoc
- documentation/src/main/asciidoc/stories/assembly_xsite_rest.adoc
- documentation/src/main/asciidoc/titles/xsite/stories.adoc
- documentation/src/main/asciidoc/topics/con_xsite_concurrent_writes.adoc
- documentation/src/main/asciidoc/topics/config_examples/config_dist_xsite_lon.xml
- documentation/src/main/asciidoc/topics/proc_enabling_jmx.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_metrics.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_statistics.adoc
- documentation/src/main/asciidoc/topics/proc_troubleshooting_xsite.adoc
- documentation/src/main/asciidoc/topics/proc_xsite_performing_jmx_operations.adoc
- documentation/src/main/asciidoc/topics/ref_jmx_xsite_components.adoc
- documentation/src/main/asciidoc/topics/ref_logs_xsite.adoc
- documentation/src/main/asciidoc/topics/ref_metrics.adoc
https://issues.redhat.com/browse/ISPN-11782
> ISPN-11782 xsite monitoring and troubleshooting

- jcache/commons/src/test/java/org/infinispan/jcache/util/InMemoryJCacheLoader.java
- jcache/embedded/src/main/java/org/infinispan/jcache/embedded/JCacheLoaderAdapter.java
- jcache/embedded/src/test/java/org/infinispan/jcache/JCacheLoaderTest.java
https://issues.redhat.com/browse/ISPN-12032
Use a custom MarshallableEntry without marshalling
for JCache loaders
> ISPN-12032 JCache cache loader should not require marshalling

- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/HotRodAccessLogging.java
- server/hotrod/src/main/resources/hotrod.gr
https://issues.redhat.com/browse/ISPN-12030
> ISPN-12030 Use Instant.now() to avoid blocking

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheContainer.java
https://issues.redhat.com/browse/ISPN-12027
> ISPN-12027 RemoteCacheContainer missing getCache overrides

- server/tests/src/test/java/org/infinispan/server/persistence/CustomStoreOperationsIT.java
* Update test to not use jboss marshalling media type
https://issues.redhat.com/browse/ISPN-11974
> ISPN-11974 Remove GenericJbossMarshaller automatic configuration

- server/rest/src/main/java/org/infinispan/rest/BaseHttpRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/rest/src/test/java/org/infinispan/rest/Http2Test.java
https://issues.redhat.com/browse/ISPN-12067
> ISPN-12067 HTTP/2 framing error for invalid requests

- server/rest/src/main/java/org/infinispan/rest/ALPNHandler.java
- server/rest/src/main/java/org/infinispan/rest/CorsHandler.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
https://issues.redhat.com/browse/ISPN-12064
> ISPN-12064 REST server returns 403 (forbidden) for same origin request

- server/rest/src/main/java/org/infinispan/rest/ALPNHandler.java
- server/rest/src/main/java/org/infinispan/rest/ResponseWriter.java
https://issues.redhat.com/browse/ISPN-12068
Not sure if we need the CORS handler too. @gustavonalle can you check please ?
> ISPN-12068 Add Chunked File handler to the HTTP/2 pipeline

- server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
https://issues.redhat.com/browse/ISPN-12059
These changes are required so that we can utilise the test in the https://github.com/infinispan/infinispan-quarkus repo.
> ISPN-12059 CliIT allow external module use

- server/tests/src/test/java/org/infinispan/server/resilience/StatefulSetRollingUpgradeIT.java
https://issues.redhat.com/browse/ISPN-11566
> ISPN-11566 Add StatefulSetRollingUpgradeIT to unstable category

- server/tests/src/test/java/org/infinispan/server/resilience/StatefulSetRollingUpgradeIT.java
Reverts infinispan/infinispan#8511
> Revert "ISPN-11566 Add StatefulSetRollingUpgradeIT to unstable category"

- commons/all/src/main/java/org/infinispan/commons/util/Util.java
- core/src/main/java/org/infinispan/persistence/file/SingleFileStore.java
https://issues.redhat.com/browse/ISPN-12056
> ISPN-12056 Some tests are failing on windows when they try to delete the SingleFileStore

- commons-test/src/main/java/org/infinispan/commons/test/TestSuiteProgress.java
https://issues.redhat.com/browse/ISPN-12074
Workaround for https://issues.apache.org/jira/browse/SUREFIRE-1814
> ISPN-12074 Test progress messages are split over multiple lines

- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheManagerClientOkHttp.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestClientOkHttp.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestClusterClientOkHttp.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCounterClientOkHttp.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestServerClientOkHttp.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestTaskClientOkHttp.java
- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/framework/Invocation.java
- server/rest/src/main/java/org/infinispan/rest/framework/impl/InvocationImpl.java
- server/rest/src/main/java/org/infinispan/rest/logging/Log.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/main/java/org/infinispan/rest/resources/ClusterResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/LoginResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/TasksResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
- server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeIT.java
https://issues.redhat.com/browse/ISPN-12054
~~Depends on #8502~~
> ISPN-12054 Remove deprecated GET methods

- core/src/main/java/org/infinispan/configuration/global/TemporaryGlobalStatePathConfiguration.java
- core/src/main/java/org/infinispan/persistence/file/SingleFileStore.java
https://issues.redhat.com/browse/ISPN-12087
> ISPN-12087 Some tests are failing on windows

- core/src/main/java/org/infinispan/configuration/cache/ClusteringConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/Attribute.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
- core/src/main/resources/schema/infinispan-config-12.0.xsd
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/resources/configs/unified/12.0.xml
https://issues.redhat.com/browse/ISPN-12077
> ISPN-12077 Serializer unable to serialize scattered caches

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/SybaseTableManager.java
https://issues.redhat.com/browse/ISPN-12098
> ISPN-12098 JDBC String Base Cache Store (sybase160) trying to create an index when already exist

- core/src/main/java/org/infinispan/configuration/cache/TransactionConfigurationBuilder.java
- core/src/test/java/org/infinispan/configuration/ConfigurationUnitTest.java
https://issues.redhat.com/browse/ISPN-12104
This removes the pesky empty tx config
> ISPN-12104 Do not touch tx mode if unnecessary

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12112
> [9.4.x] ISPN-12112 Upgrade Jackson-Databind to 2.9.10.4

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12119
> [9.4.x] ISPN-12119 Upgrade Jetty to 9.4.11.v20180605

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12118
> [9.4.x] ISPN-12118 Upgrade Netty to 4.1.46.Final

- pom.xml
https://issues.redhat.com/browse/ISPN-12116
> [9.4.x] ISPN-12116 Upgrade undertow to 2.0.30

- pom.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/Node0OnlyBalancingStrategy.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/Node1OnlyBalancingStrategy.java
https://issues.redhat.com/browse/ISPN-12110
> [9.4.x] ISPN-12110 Upgrade httpcomponents to 4.4.5

- build-configuration/pom.xml
- pom.xml
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingTagHandler.java
https://issues.redhat.com/browse/ISPN-12111
> [9.4.x] ISPN-12111 Upgrade Hibernate Core/Search to 5.3.17.Final/5.10.7.Final

- build-configuration/bom/pom.xml
https://issues.redhat.com/browse/ISPN-11336
> ISPN-11336 Infinispan BOM should only have dependency management

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/TopologyInfo.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/IterationStartOperation.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/IterationRoutingTest.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/DataPartitioner.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/HotRodTargetMigrator.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/impl/LocalityAwareDataPartitioner.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeStressTest.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/LocationAwareDataPartitionTest.java
https://issues.redhat.com/browse/ISPN-12002
> ISPN-12002  Rolling Upgrades location aware data retrieving

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodNonOwnerStatisticsTest.java
https://issues.redhat.com/browse/ISPN-11303
> [9.4.x] ISPN-11303 Test hit/miss statistics after non-owner get

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12135
> ISPN-12135 Upgrade Netty to 4.1.51.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12135
> [9.4.x] ISPN-12135 Upgrade Netty to 4.1.51.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12135
> [11.0.x] ISPN-12135 Upgrade Netty to 4.1.51.Final

- documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
https://issues.redhat.com/browse/ISPN-12136
> ISPN-12136 update deployment structure xml

- commons/all/src/main/resources/META-INF/infinispan-version.properties
https://issues.redhat.com/browse/ISPN-12125
Potential workaround, does not always fix the problem.
> ISPN-12125 IntelliJ copies infinispan-version.properties without filtering

- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
- server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
- server/tests/src/test/resources/cli/qcache.xml
https://issues.redhat.com/browse/ISPN-12146
> ISPN-12146 Fix CLI Stats NPE

- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
- server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
- server/tests/src/test/resources/cli/qcache.xml
https://issues.redhat.com/browse/ISPN-12146
> [11.0] ISPN-12146 Fix CLI Stats NPE

- core/src/test/java/org/infinispan/eviction/impl/MarshalledValuesManualEvictionTest.java
- core/src/test/java/org/infinispan/marshall/InvalidatedMarshalledValueTest.java
- core/src/test/java/org/infinispan/marshall/core/StoreAsBinaryTest.java
- core/src/test/java/org/infinispan/test/data/CountMarshallingPojo.java
https://issues.redhat.com/browse/ISPN-11604
> ISPN-11604 CountMarshallingPojo Breaks with parallel tests

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractServerConfigBuilder.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeIT.java
https://issues.redhat.com/browse/ISPN-12130
> ISPN-12130 RollingUpgradeIT ignoring system properties

- commons/all/src/main/java/org/infinispan/commons/util/concurrent/BlockingRejectedExecutionHandler.java
- core/pom.xml
- core/src/main/java/org/infinispan/configuration/global/BoundedThreadPoolConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
- core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java
- core/src/main/java/org/infinispan/factories/threads/AbstractThreadPoolExecutorFactory.java
- core/src/main/java/org/infinispan/factories/threads/CoreExecutorFactory.java
- core/src/main/java/org/infinispan/factories/threads/EnhancedQueueExecutorFactory.java
- core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadPoolExecutorFactory.java
- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
- core/src/main/resources/features.xml
- core/src/test/java/org/infinispan/configuration/StringPropertyReplacementTest.java
- core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
- integrationtests/security-it/src/test/java/org/infinispan/test/integration/security/utils/Deployments.java
- remote-query/remote-query-server/src/test/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerInterceptorTest.java
- server/runtime/pom.xml
- wildfly/feature-pack/src/main/resources/modules/org/infinispan/slot/module.xml
https://issues.redhat.com/browse/ISPN-12029
> ISPN-12029 Replace Blocking Executor with an EnhancedQueueExecutor

- client/marshaller/kryo/kryo-marshaller/src/main/java/org/infinispan/marshaller/kryo/KryoMarshaller.java
- client/marshaller/kryo/kryo-marshaller/src/main/java/org/infinispan/marshaller/kryo/KryoTranscoder.java
- client/marshaller/kryo/kryo-marshaller/src/main/java/org/infinispan/marshaller/kryo/SerializerRegistryService.java
- client/marshaller/protostuff/protostuff-marshaller/src/main/java/org/infinispan/marshaller/protostuff/ProtostuffMarshaller.java
- client/marshaller/protostuff/protostuff-marshaller/src/main/java/org/infinispan/marshaller/protostuff/ProtostuffTranscoder.java
- client/marshaller/protostuff/protostuff-marshaller/src/main/java/org/infinispan/marshaller/protostuff/SchemaRegistryService.java
- documentation/src/main/asciidoc/topics/proc_using_kyro_marshaller.adoc
- documentation/src/main/asciidoc/topics/proc_using_protostuff_marshaller.adoc
- documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/ISPN-12159
> ISPN-12159 Deprecate the Kryo and Protostuff marshallers

- documentation/src/main/asciidoc/topics/proc_using_kyro_marshaller.adoc
- documentation/src/main/asciidoc/topics/proc_using_protostuff_marshaller.adoc
https://issues.redhat.com/browse/ISPN-12159
> ISPN-12159 Address the Don's comments

- README-i18n.md
- anchored-keys/src/main/java/org/infinispan/anchored/AnchoredKeysModule.java
- anchored-keys/src/main/java/org/infinispan/anchored/configuration/AnchoredKeysConfiguration.java
- anchored-keys/src/main/java/org/infinispan/anchored/configuration/AnchoredKeysConfigurationBuilder.java
- anchored-keys/src/main/java/org/infinispan/anchored/configuration/AnchoredKeysConfigurationParser.java
- anchored-keys/src/main/java/org/infinispan/anchored/impl/Log.java
- anchored-keys/src/test/resources/config/anchored.xml
- documentation/src/main/asciidoc/stories/assembly_developing.adoc
- documentation/src/main/asciidoc/topics/anchored_keys.adoc
- documentation/src/main/asciidoc/topics/con_cache_interface.adoc
- documentation/src/main/asciidoc/topics/faq_content.adoc
- documentation/src/main/asciidoc/topics/functional_api.adoc
https://issues.redhat.com/browse/ISPN-11304
> ISPN-11304 Add anchored keys documentation in developer guide

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12154
> ISPN-12154 upgrade console

- core/src/test/java/org/infinispan/container/versioning/WriteSkewConsistencyTest.java
https://issues.redhat.com/browse/ISPN-7166
> ISPN-7166 WriteSkewConsistencyTest random failures

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedServer.java
https://issues.redhat.com/browse/ISPN-12041
> ISPN-12041 ServerRunMode.FORKED mode doesn't work on Windows

- core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/resources/schema/infinispan-config-12.0.xsd
- core/src/test/resources/configs/unified/11.0.xml
https://issues.redhat.com/browse/ISPN-12004
This should only land after we branch for 12.
> ISPN-12004 JGroups INSERT_BEFORE

- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/PropertiesRealmConfigurationBuilder.java
https://issues.redhat.com/browse/ISPN-12181
> ISPN-12181 Add a 'ready' boolean flag to the login config resource

- query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
- query/src/main/java/org/infinispan/query/clustered/ClusteredCacheQueryImpl.java
- query/src/main/java/org/infinispan/query/clustered/ClusteredQueryInvoker.java
- query/src/main/java/org/infinispan/query/clustered/ClusteredQueryOperation.java
- query/src/main/java/org/infinispan/query/clustered/QueryResponse.java
- query/src/main/java/org/infinispan/query/clustered/SegmentsClusteredQueryCommand.java
- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQCommandType.java
- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQCreateEagerQuery.java
- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQGetResultSize.java
- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQWorker.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java
- query/src/main/java/org/infinispan/query/impl/SearchManagerImpl.java
https://issues.redhat.com/browse/ISPN-12178
> ISPN-12178 Query broadcast blocks on the non-blocking executor

- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-12185
> ISPN-12185 Don't NPE when authn is not configured on the REST endpoint

- core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java
- core/src/test/java/org/infinispan/partitionhandling/DegradedJoinTest.java
https://issues.redhat.com/browse/ISPN-12179
> ISPN-12179 Allow cache to start in degraded mode

- build-configuration/pom.xml
- client/hotrod-client/pom.xml
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/QuerySerializer.java
- client/hotrod-client/src/main/resources/features.xml
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/HotRodQueryIspnDirectoryTest.java
- pom.xml
- remote-query/remote-query-client/pom.xml
- remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/impl/JsonClientQueryResponse.java
- remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/impl/QueryRequest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/JsonQuerySerializer.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java
https://issues.redhat.com/browse/ISPN-12191
> ISPN-12191 Remove GSON

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.redhat.com/browse/ISPN-12194
> ISPN-12194 Transport::getSitesView() should be ordered

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodNonOwnerStatisticsTest.java
https://issues.redhat.com/browse/ISPN-12197
> ISPN-12197 HotRodNonOwnerStatisticsTest failures

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.redhat.com/browse/ISPN-12194
> [11.x] ISPN-12194 Transport::getSitesView() should be ordered

- build-configuration/pom.xml
- integrationtests/wildfly-modules/src/test/java/org/infinispan/test/integration/as/client/HotRodQueryIT.java
- integrationtests/wildfly-modules/src/test/java/org/infinispan/test/integration/as/remote/InfinispanRemoteWithQueryIT.java
- pom.xml
- wildfly/feature-pack/pom.xml
- wildfly/feature-pack/src/main/resources/modules/org/infinispan/slot/module.xml
https://issues.redhat.com/browse/ISPN-12190
~~Depends on #8605~~
> ISPN-12190 Re-add hibernate search for wildfly modules 

- commons/all/src/main/java/org/infinispan/commons/util/OS.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/server/bin/report-osx.sh
https://issues.redhat.com/browse/ISPN-12150
> ISPN-12150 Improve CLI server report to work with MacOs

- documentation/src/main/asciidoc/index.asciidoc
https://issues.redhat.com/browse/ISPN-12175
> ISPN-12175 update index links

- core/src/main/java/org/infinispan/partitionhandling/impl/PreferAvailabilityStrategy.java
- core/src/test/java/org/infinispan/partitionhandling/impl/PreferAvailabilityStrategyTest.java
https://issues.redhat.com/browse/ISPN-10365
> ISPN-10365 PreferAvailabilityStrategy assertion failure

- documentation/src/main/asciidoc/topics/proc_download_hotrod_java_client.adoc
- documentation/src/main/asciidoc/topics/ref_server_requirements.adoc
https://issues.redhat.com/browse/ISPN-12233
Needs backport to 11 and 10.1
> ISPN-12233 Server requires Java 11

- documentation/src/main/asciidoc/topics/contributing/docs.adoc
https://issues.redhat.com/browse/ISPN-10092
> ISPN-10092 link doc readme

- documentation/src/main/asciidoc/topics/con_eviction.adoc
https://issues.redhat.com/browse/ISPN-12173 
Needs backport to 11
> ISPN-12173 update eviction description

- documentation/src/main/asciidoc/topics/proc_download_hotrod_java_client.adoc
- documentation/src/main/asciidoc/topics/ref_server_requirements.adoc
https://issues.redhat.com/browse/ISPN-12233 
Backport to 11.0.x
> [11.0.x] ISPN-12233 Server requires Java 11

- documentation/src/main/asciidoc/topics/proc_enabling_spring_session.adoc
https://issues.redhat.com/browse/ISPN-11868
> ISPN-11868: add hint about no default cache for spring session

- documentation/src/main/asciidoc/stories/assembly_configuring_clustering.adoc
- documentation/src/main/asciidoc/stories/assembly_ports_protocols.adoc
related to https://issues.redhat.com/browse/ISPN-12217
> update anchor to fix doc build

- documentation/src/main/asciidoc/stories/assembly_configuring_clustering.adoc
- documentation/src/main/asciidoc/stories/assembly_ports_protocols.adoc
related to https://issues.redhat.com/browse/ISPN-12217
> [11.x] update anchor to fix doc build

- commons-test/src/main/java/org/infinispan/commons/test/BlockHoundHelper.java
- commons-test/src/main/java/org/infinispan/commons/test/CommonsTestBlockHoundIntegration.java
- core/src/main/java/org/infinispan/util/concurrent/BlockingManager.java
- core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
- core/src/test/java/org/infinispan/test/Mocks.java
- core/src/test/java/org/infinispan/util/concurrent/BlockingManagerTest.java
https://issues.redhat.com/browse/ISPN-12242
> ISPN-12242 BlockingManager add reentrant blocking scheduler

- pom.xml
https://issues.redhat.com/browse/ISPN-12276
> ISPN-12276 Bump Testcontainers 1.14.3

- documentation/src/main/asciidoc/topics/con_xsite_auto_offline.adoc
- documentation/src/main/asciidoc/topics/config_examples/jgroups-relay.xml
- documentation/src/main/asciidoc/topics/ref_xsite_jgroups_relay_custom.adoc
https://issues.redhat.com/browse/ISPN-12272 
Needs backport to 11.
> ISPN-12272 clarify xsite docs

- documentation/src/main/asciidoc/topics/con_xsite_auto_offline.adoc
- documentation/src/main/asciidoc/topics/config_examples/jgroups-relay.xml
- documentation/src/main/asciidoc/topics/ref_xsite_jgroups_relay_custom.adoc
https://issues.redhat.com/browse/ISPN-12272
> [11.0.x] ISPN-12272 clarify xsite docs

- core/src/main/java/org/infinispan/util/logging/Log.java
- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/json/SecureTypeIdResolver.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/json/SecureTypeResolverBuilder.java
https://issues.redhat.com/browse/ISPN-12121
> ISPN-12121 Deprecate custom objects to JSON automatic conversion

- component-processor/src/main/java/org/infinispan/component/processor/Generator.java
https://issues.redhat.com/browse/ISPN-12274
Put each injection method argument on a separate line.
> ISPN-12274 Component annotation processor injection method single line

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/DataFormat.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/multimap/RemoteMultimapCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/marshall/MarshallerUtil.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/AbstractRemoteStoreConfigurationChildBuilder.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/Attribute.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfiguration.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationBuilder.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationChildBuilder.java
- persistence/remote/src/main/resources/schema/infinispan-cachestore-remote-config-12.0.xsd
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/AbstractRemoteCacheManagerFactory.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/ConfigurationPropertiesOverrides.java
https://issues.redhat.com/browse/ISPN-12230
> ISPN-11230 Deprecate client attributes key/valueSizeEstimate

- hibernate/cache-commons/src/main/resources/org/infinispan/hibernate/cache/commons/builder/infinispan-configs-local.xml
- hibernate/cache-commons/src/main/resources/org/infinispan/hibernate/cache/commons/builder/infinispan-configs.xml
https://issues.redhat.com/browse/ISPN-12252
Please cherry-pick into 11.0.x.
> ISPN-12252 Default hibernate cache configurations use unspecified media type

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
- server/testdriver/junit4/pom.xml
- server/testdriver/junit5/pom.xml
- server/testdriver/pom.xml
https://issues.redhat.com/browse/ISPN-12284
* Try to stop the servers even if they failed to start
* Use the `tcp` stack in server/testdriver/junit4
> ISPN-12284 InfinispanRuleBasicTest thread leak

- core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- core/src/test/java/org/infinispan/xsite/offline/InvalidConfigurationOfflineTest.java
* If the cache isn't properly configured in the remote site,
the site is taken offline
https://issues.redhat.com/browse/ISPN-12249
> ISPN-12249 Better exception handling for cross-site requests

- documentation/src/main/asciidoc/topics/config_examples/server_groups.properties
- server/runtime/src/main/server/server/conf/groups.properties
https://issues.redhat.com/browse/ISPN-12088
> ISPN-12088 Correctly document group properties

- server/runtime/src/test/java/org/infinispan/server/license/LicenseTest.java
https://issues.redhat.com/browse/ISPN-12285
> ISPN-12285 LicenseTest should check the licenses links

- server/runtime/src/main/ant/infinispan-server.xml
https://issues.redhat.com/browse/ISPN-12280
> ISPN-12280 Failfast if lsof is not present in unix

- build-configuration/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-12243
Configure Surefire to communicate with the fork JVM using TCP
> ISPN-12243 Upgrade to Surefire 3.0.0-M5

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12287
> ISPN-12287 Console 0.9.Final

- spring/spring-boot/remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteAutoConfiguration.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/AbstractRemoteCacheManagerFactory.java
https://issues.redhat.com/browse/ISPN-12257
Use both the "allowlist" and the "whitelist" properties in
AbstractRemoteCacheManagerFactory.initializeMarshallingProperties()
> ISPN-12257 RemoteSpringSessionTest.testCreatingSessionWhenUsingREST

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/AbstractHotRodSiteFailoverTest.java
- server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
- server/core/src/main/java/org/infinispan/server/core/ProtocolServer.java
- server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfigurationChildBuilder.java
- server/core/src/main/java/org/infinispan/server/core/transport/NettyTransportConnectionStats.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodStatsTest.java
- server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedStatsTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
https://issues.redhat.com/browse/ISPN-12260
> ISPN-12260 Don't use JMX to compute global server connection stats

- build-configuration/bom/pom.xml
- distribution/pom.xml
- documentation/pom.xml
- javadoc/pom.xml
- tools/pom.xml
https://issues.redhat.com/browse/ISPN-12234
> ISPN-12234 remove infinispan-cachestore-rest final bits

- build-configuration/pom.xml
- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQCreateEagerQuery.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelper.java
- query/src/main/java/org/infinispan/query/impl/EntityLoader.java
- search-mapper/src/main/java/org/hibernate/search/annotations/IndexedEmbedded.java
https://issues.redhat.com/browse/ISPN-12288
> ISPN-12288 Upgrade to Hibernate Search 6.0.0.Beta10

- cli/cli-client/src/main/java/org/infinispan/cli/commands/Add.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/Connect.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/Create.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/Drop.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/Query.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/Schema.java
Add some more descriptions for cli command help where arguments and options are not explained and values unclear
> additional description for CLI help

- documentation/src/main/asciidoc/user_guide/cache_api.adoc
- documentation/src/main/asciidoc/user_guide/functional_api.adoc
https://issues.redhat.com/browse/ISPN-12305
> ISPN-12305 functional map conditionals

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManagerFactoryBeanTest.java
- spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/support/InfinispanRemoteCacheManagerFactoryBeanTest.java
https://issues.redhat.com/browse/ISPN-12162
> [11.0.x] ISPN-12162 Fix the Marshaller configuration

- commons/all/src/main/java/org/infinispan/commons/util/concurrent/BlockingRejectedExecutionHandler.java
- core/pom.xml
- core/src/main/java/org/infinispan/configuration/global/BoundedThreadPoolConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
- core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java
- core/src/main/java/org/infinispan/factories/threads/AbstractThreadPoolExecutorFactory.java
- core/src/main/java/org/infinispan/factories/threads/CoreExecutorFactory.java
- core/src/main/java/org/infinispan/factories/threads/EnhancedQueueExecutorFactory.java
- core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadPoolExecutorFactory.java
- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
- core/src/main/resources/features.xml
- core/src/test/java/org/infinispan/configuration/StringPropertyReplacementTest.java
- core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
- integrationtests/security-it/src/test/java/org/infinispan/test/integration/security/utils/Deployments.java
- remote-query/remote-query-server/src/test/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerInterceptorTest.java
- server/runtime/pom.xml
- wildfly/feature-pack/src/main/resources/modules/org/infinispan/slot/module.xml
https://issues.redhat.com/browse/ISPN-12029
> [11.0.x] ISPN-12029 Replace Blocking Executor with an EnhancedQueueExecutor

- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/commons/client/AbstractHotRodClientIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/HotRodClientIT.java
- integrationtests/server-integration/wildfly-modules/src/test/java/org/infinispan/test/integration/as/client/HotRodClientIT.java
- pom.xml
https://issues.redhat.com/browse/ISPN-12317
> ISPN-12317 WildFly modules integration tests do not start

- core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- core/src/test/java/org/infinispan/xsite/offline/InvalidConfigurationOfflineTest.java
* If the cache isn't properly configured in the remote site,
the site is taken offline
https://issues.redhat.com/browse/ISPN-12249
> [11.0.x] ISPN-12249 Better exception handling for cross-site requests

- core/src/main/java/org/infinispan/commands/irac/IracUpdateKeyCommand.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/inboundhandler/InboundInvocationHandler.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManager.java
- core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
- core/src/main/java/org/infinispan/remoting/transport/AbstractDelegatingTransport.java
- core/src/main/java/org/infinispan/remoting/transport/RetryOnFailureXSiteCommand.java
- core/src/main/java/org/infinispan/remoting/transport/Transport.java
- core/src/main/java/org/infinispan/remoting/transport/XSiteResponse.java
- core/src/main/java/org/infinispan/remoting/transport/impl/XSiteResponseImpl.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/xsite/BackupReceiver.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/main/java/org/infinispan/xsite/ClusteredCacheBackupReceiver.java
- core/src/main/java/org/infinispan/xsite/SingleXSiteRpcCommand.java
- core/src/main/java/org/infinispan/xsite/XSiteReplicateCommand.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteStateTransferFinishReceiveCommand.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteStateTransferStartReceiveCommand.java
- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStatePushCommand.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
- core/src/main/java/org/infinispan/xsite/status/TakeOfflineManager.java
- core/src/test/java/org/infinispan/jmx/PerCacheInboundHandlerMBeanTest.java
- core/src/test/java/org/infinispan/jmx/RpcManagerMBeanTest.java
- core/src/test/java/org/infinispan/util/AbstractDelegatingRpcManager.java
- core/src/test/java/org/infinispan/xsite/BackupReceiverDelegator.java
- core/src/test/java/org/infinispan/xsite/RollbackNoPrepareOptimisticTest.java
- core/src/test/java/org/infinispan/xsite/offline/DelegatingTransport.java
- core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
- extended-statistics/src/main/java/org/infinispan/extendedstats/wrappers/ExtendedStatisticRpcManager.java
https://issues.redhat.com/browse/ISPN-12319
> ISPN-12319 XSite Response should allow a value

- query/src/main/java/org/infinispan/query/clustered/commandworkers/CQCreateEagerQuery.java
https://issues.redhat.com/browse/ISPN-12318
> ISPN-12318 Query.maxResult() ignored during entity loading

- pom.xml
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-12297
The new version fixes the tc-okhttp-stream thread leak.
It also fixes the startup of the mysql container on my machine.
> ISPN-12297 Upgrade to Testcontainers 1.15.0-rc1

- distribution/pom.xml
- persistence/jpa/src/main/resources/schema/infinispan-cachestore-jpa-config-12.0.xsd
* Added missing lock & counter modules
* Fixed default value for batch size (JPA schema)
https://issues.redhat.com/browse/ISPN-12334
> ISPN-12334 Fix configdocs

- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.redhat.com/browse/ISPN-12345
> ISPN-12345 Dump JGroups stack on startup

- core/src/main/resources/schema/infinispan-config-12.0.xsd
- documentation/src/main/asciidoc/topics/ref_cache_store_remote.adoc
https://issues.redhat.com/browse/ISPN-12344
> ISPN-12344 cannot preload shared remote stores

- core/src/main/resources/schema/infinispan-config-11.0.xsd
- documentation/src/main/asciidoc/topics/ref_cache_store_remote.adoc
https://issues.redhat.com/browse/ISPN-12344 
Forgot to mention it needs a backport to 11.x. Thanks!
> [11.x] ISPN-12344 cannot preload shared remote stores

- spring/spring5/spring5-common/pom.xml
- spring/spring5/spring5-embedded/pom.xml
- spring/spring5/spring5-remote/pom.xml
https://issues.redhat.com/browse/ISPN-12342
> ISPN-12342 Add Dependencies Manifest header to Spring artifacts

- server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestClientXSiteDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractServerConfigBuilder.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestServer.java
- server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanXSiteServerRule.java
- server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanXSiteServerRuleBuilder.java
- server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanXSiteServerTestMethodRule.java
- server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanXSiteServerExtension.java
- server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanXSiteServerExtensionBuilder.java
- server/testdriver/junit5/src/test/java/org/infinispan/server/test/junit5/InfinispanXSiteServerTest.java
- server/testdriver/junit5/src/test/resources/XSiteServerTest.xml
- server/testdriver/junit5/src/test/resources/cache-container/clustered.xml
- server/testdriver/junit5/src/test/resources/endpoints/default.xml
- server/testdriver/junit5/src/test/resources/interfaces/default.xml
- server/testdriver/junit5/src/test/resources/jgroups/xsite-stacks.xml
- server/testdriver/junit5/src/test/resources/security/none.xml
- server/testdriver/junit5/src/test/resources/socket-bindings/default.xml
- server/tests/src/test/java/org/infinispan/server/functional/XSiteHotRodCacheOperations.java
- server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java
- server/tests/src/test/java/org/infinispan/server/functional/XSiteRestCacheOperations.java
https://issues.redhat.com/browse/ISPN-12206
> ISPN-12206 Create an InfinispanXSiteServerRule and increase the tests coverage

- documentation/src/main/asciidoc/topics/con_caches_distribution.adoc
https://issues.redhat.com/browse/ISPN-12221
> ISPN-12221 Update zero-capacity-node docs

- documentation/src/main/asciidoc/user_guide/architecture.adoc
- documentation/src/main/asciidoc/user_guide/introduction.adoc
https://issues.redhat.com/browse/ISPN-12355
> ISPN-12355 fix broken links in User Guide

- core/src/main/java/org/infinispan/util/ExponentialBackOff.java
- core/src/main/java/org/infinispan/util/ExponentialBackOffImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
- core/src/test/java/org/infinispan/util/ExponentialBackOffImplUnitTest.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracExponentialBackOffTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
https://issues.redhat.com/browse/ISPN-12250
> ISPN-12250 Add exponential back-off for cross-site network failures

- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
https://issues.redhat.com/browse/ISPN-12356
> ISPN-12356 ScatteredStreamIteratorTest random failure

- integrationtests/server-integration/third-party-server/pom.xml
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/DeploymentHelper.java
- integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
https://issues.redhat.com/browse/ISPN-12339
```
mvn verify -Dinfinispan.server.integration.launch=eap -s maven-settings.xml -pl integrationtests/server-integration/third-party-server -Deap.zip=/path/to/eap.zip
```
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.infinispan.test.integration.thirdparty.HotRodClientIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.947 s - in org.infinispan.test.integration.thirdparty.HotRodClientIT
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```
> ISPN-12339 Add eap profile for third-party-server project

- integrationtests/server-integration/third-party-server/pom.xml
https://issues.redhat.com/browse/ISPN-12338
> ISPN-12338 Unzip tomcat only during the test phase

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12360
> ISPN-12360 Upgrade Server Console to 0.10.Final

- commons/all/pom.xml
- commons/all/src/main/java/org/infinispan/commons/jdkspecific/ProcessInfo.java
- commons/jdk11/src/main/java/org/infinispan/commons/jdkspecific/ProcessInfo.java
Resolves
https://issues.redhat.com/browse/ISPN-12366
> ISPN-12366 infinispan-commons is not a valid Multi-Release jar

- core/src/main/java/org/infinispan/globalstate/impl/VolatileLocalConfigurationStorage.java
- core/src/main/java/org/infinispan/health/CacheHealth.java
- core/src/main/java/org/infinispan/health/HealthStatus.java
- core/src/main/java/org/infinispan/health/impl/CacheHealthImpl.java
- core/src/main/java/org/infinispan/health/impl/ClusterHealthImpl.java
- core/src/main/java/org/infinispan/health/impl/HealthImpl.java
- core/src/main/java/org/infinispan/health/impl/InvalidCacheHealth.java
- core/src/main/java/org/infinispan/stats/impl/CacheContainerStatsImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/rest/src/main/java/org/infinispan/rest/BaseHttpRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/helper/RestServerHelper.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-12309
> ISPN-12309 Creating cache with invalid configuration leaves inconsistent state

- core/src/main/java/org/infinispan/globalstate/impl/VolatileLocalConfigurationStorage.java
- core/src/main/java/org/infinispan/health/HealthStatus.java
- core/src/main/java/org/infinispan/health/impl/ClusterHealthImpl.java
- core/src/main/java/org/infinispan/health/impl/HealthImpl.java
- core/src/main/java/org/infinispan/health/impl/InvalidCacheHealth.java
- core/src/main/java/org/infinispan/stats/impl/CacheContainerStatsImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
- server/rest/src/main/java/org/infinispan/rest/BaseHttpRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/helper/RestServerHelper.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-12309
> [11.0.x] ISPN-12309 Creating cache with invalid configuration leaves inconsistent state 

- distribution/package.xml
- wildfly/feature-pack/pom.xml
https://issues.redhat.com/browse/ISPN-12375
> ISPN-12375 Add missing license information to wildfly modules

- distribution/package.xml
- wildfly/feature-pack/pom.xml
- wildfly/feature-pack/src/main/resources/modules/org/infinispan/slot/module.xml
https://issues.redhat.com/browse/ISPN-12375
> [11.0.x] ISPN-12375 Add missing license information to wildfly modules

- build-configuration/pom.xml
- core/proto.lock
- documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/ISPN-12362
> ISPN-12362 Upgrade to protostream 4.3.4.Final

- build-configuration/pom.xml
- core/proto.lock
- documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/ISPN-12362
> [11.0.x] ISPN-12362 Upgrade to protostream 4.3.4.Final

- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/security/ElytronHTTPAuthenticator.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-12374
> ISPN-12374 Shutdown the Digest nonce manager "manually"

- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/security/ElytronHTTPAuthenticator.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-12374
> [11.0] ISPN-12374 Shutdown the Digest nonce manager "manually"

- query/src/main/java/org/infinispan/query/clustered/ClusteredQueryInvoker.java
https://issues.redhat.com/browse/ISPN-12378
> ISPN-12378 Distributed queries don't respect RPC timeout

- query/src/main/java/org/infinispan/query/clustered/ClusteredQueryInvoker.java
https://issues.redhat.com/browse/ISPN-12378
> [11.0.x] ISPN-12378 Distributed queries don't respect RPC timeout

- core/src/main/java/org/infinispan/util/ExponentialBackOff.java
- core/src/main/java/org/infinispan/util/ExponentialBackOffImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
- core/src/test/java/org/infinispan/util/ExponentialBackOffImplUnitTest.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracExponentialBackOffTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
https://issues.redhat.com/browse/ISPN-12250
master PR: https://github.com/infinispan/infinispan/pull/8672
> [11.0.x] ISPN-12250 Add exponential back-off for cross-site network failures

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12382
> [11.x] Console upgrade 0.7.1

- core/src/main/java/org/infinispan/encoding/ProtostreamTranscoder.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/DefaultQuerySerializer.java
- server/rest/src/main/java/org/infinispan/rest/ResponseWriter.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-12315
> ISPN-12315 REST server can't handle entry changes with value encoded as java primitives

- commons/all/src/main/java/org/infinispan/commons/dataconversion/MediaType.java
- commons/all/src/test/java/org/infinispan/commons/dataconversion/MediaTypeTest.java
- core/src/main/java/org/infinispan/AdvancedCache.java
- core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingAdvancedCache.java
- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/main/java/org/infinispan/cache/impl/EncoderCache.java
- core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
- core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java
- core/src/test/java/org/infinispan/dataconversion/DataConversionTest.java
- core/src/test/java/org/infinispan/functional/decorators/FunctionalAdvancedCache.java
- core/src/test/java/org/infinispan/security/SecureCacheTestDriver.java
- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointInteroperabilityTest.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreTest.java
- server/core/src/main/java/org/infinispan/server/core/CacheInfo.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/TransactionRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/DefaultIterationManager.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/BaseCompleteTransactionOperation.java
- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoder.java
- server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
- server/rest/src/test/java/org/infinispan/rest/cachemanager/RestCacheManagerTest.java
- server/runtime/src/main/java/org/infinispan/server/tasks/DistributedServerTask.java
- server/runtime/src/main/java/org/infinispan/server/tasks/ServerTaskEngine.java
- server/tests/src/test/java/org/infinispan/server/persistence/CustomNonBlockingStore.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/DataTypedCacheManager.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/DistributedScript.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingManagerImpl.java
https://issues.redhat.com/browse/ISPN-12392
> ISPN-12392  EndpointInteroperabilityTest.testStringKeysAndByteArrayValue failing

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12412
> ISPN-12412 Upgrade Hibernate Core to 5.3.18.Final

- pom.xml
https://issues.redhat.com/browse/ISPN-12415
> ISPN-12415 Force JSoup version to 1.9.2

- pom.xml
https://issues.redhat.com/browse/ISPN-12415
> [11.0.x] ISPN-12415 Force JSoup version to 1.9.2

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12412
> [11.0.x] ISPN-12412 Upgrade Hibernate Core to 5.3.18.Final

- build-configuration/bom/pom.xml
* Added: infinispan-component-processor
* Added: infinispan-hibernate-commons
* Removed: infinispan-defaults-maven-plugin
https://issues.redhat.com/browse/ISPN-12409
> [11.0.x] ISPN-12409 Add missing GAV to infinispan-bom

- build-configuration/bom/pom.xml
* Added: infinispan-component-processor
* Added: infinispan-hibernate-commons
* Removed: infinispan-defaults-maven-plugin
https://issues.redhat.com/browse/ISPN-12409
> ISPN-12409 Add missing GAV to infinispan-bom

- build-configuration/pom.xml
- cli/cli-client/pom.xml
- cli/cli-client/src/main/java/org/infinispan/cli/benchmark/BenchmarkOutputFormat.java
- cli/cli-client/src/main/java/org/infinispan/cli/benchmark/HotRodBenchmark.java
- cli/cli-client/src/main/java/org/infinispan/cli/benchmark/HttpBenchmark.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/Benchmark.java
- cli/cli-client/src/main/java/org/infinispan/cli/commands/CLI.java
- cli/cli-client/src/main/java/org/infinispan/cli/completers/BenchmarkModeCompleter.java
- cli/cli-client/src/main/java/org/infinispan/cli/completers/BenchmarkVerbosityModeCompleter.java
- cli/cli-client/src/main/java/org/infinispan/cli/completers/TimeUnitCompleter.java
- cli/cli-client/src/main/java/org/infinispan/cli/connection/Connection.java
- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
- cli/cli-client/src/main/resources/help/benchmark.adoc
- client/rest-client/src/main/java/org/infinispan/client/rest/RestURI.java
- client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfiguration.java
- client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationBuilder.java
- client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationProperties.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/auth/DigestAuthenticator.java
- server/runtime/pom.xml
- server/runtime/src/main/server/bin/cli.log4j2.xml
https://issues.redhat.com/browse/ISPN-12044
> ISPN-12044 CLI performance tool

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12426
> ISPN-12426 Upgrade the web console to 0.11.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12428
> ISPN-12428 Upgrade JUnit to 4.13.1

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12428
> [11.0.x] ISPN-12428 Upgrade JUnit to 4.13.1

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12432
> ISPN-12432 Fix maven warning

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12432
> [11.0.x] ISPN-12432 Fix maven warning

- pom.xml
https://issues.redhat.com/browse/ISPN-12431
ps. only affect 11.0.x
> ISPN-12431 Upgrade HTTPClient to 4.5.13

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12436
> ISPN-12436 Upgrade JGroups to 4.2.7.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12436
> [11.0.x] ISPN-12436 Upgrade JGroups to 4.2.7.Final

- core/src/main/resources/default-configs/default-jgroups-azure.xml
- core/src/main/resources/default-configs/default-jgroups-ec2.xml
- core/src/main/resources/default-configs/default-jgroups-google.xml
- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/main/resources/default-configs/default-jgroups-udp.xml
- core/src/test/resources/stacks/broken-tcp.xml
- core/src/test/resources/stacks/tcp.xml
- core/src/test/resources/stacks/tcp_mping/tcp1.xml
- core/src/test/resources/stacks/tcp_mping/tcp2.xml
- core/src/test/resources/stacks/udp.xml
https://issues.redhat.com/browse/ISPN-12436
> ISPN-12436 Prevent JGroups version warning

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheManagerAdminImpl.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
- commons/all/src/main/java/org/infinispan/commons/api/CacheContainerAdmin.java
- core/src/main/java/org/infinispan/globalstate/GlobalConfigurationManager.java
- core/src/main/java/org/infinispan/globalstate/LocalConfigurationStorage.java
- core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
- core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationStateListener.java
- core/src/main/java/org/infinispan/globalstate/impl/ImmutableLocalConfigurationStorage.java
- core/src/main/java/org/infinispan/globalstate/impl/OverlayLocalConfigurationStorage.java
- core/src/main/java/org/infinispan/globalstate/impl/VolatileLocalConfigurationStorage.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManagerAdmin.java
- core/src/main/java/org/infinispan/manager/EmbeddedCacheManagerAdmin.java
- core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java
- core/src/test/java/org/infinispan/configuration/JsonSerializationTest.java
- core/src/test/java/org/infinispan/distribution/ZeroCapacityAdministrationTest.java
- core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
- core/src/test/java/org/infinispan/globalstate/NoOpGlobalConfigurationManager.java
- server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/EmbeddedServerAdminOperationHandler.java
- server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/TemplateCreateTask.java
- server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/TemplateRemoveTask.java
https://issues.redhat.com/browse/ISPN-12394
https://issues.redhat.com/browse/ISPN-12411
> ISPN-12394 Allow templates to be defined clusterwide and persisted

- core/src/main/resources/default-configs/default-jgroups-azure.xml
- core/src/main/resources/default-configs/default-jgroups-ec2.xml
- core/src/main/resources/default-configs/default-jgroups-google.xml
- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/main/resources/default-configs/default-jgroups-udp.xml
- core/src/test/resources/configs/xsite/bridge.xml
- core/src/test/resources/stacks/broken-tcp.xml
- core/src/test/resources/stacks/tcp.xml
- core/src/test/resources/stacks/tcp_mping/tcp1.xml
- core/src/test/resources/stacks/tcp_mping/tcp2.xml
- core/src/test/resources/stacks/udp.xml
- documentation/src/main/asciidoc/topics/config_examples/jgroups-relay.xml
- hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
- tools/src/test/resources/udp.xml
https://issues.redhat.com/browse/ISPN-12436
> [11.0.x] ISPN-12436 Prevent JGroups version warning

- server/runtime/src/main/server/bin/service/infinispan.service
https://issues.redhat.com/browse/ISPN-12160
> ISPN-12160 systemd example to start Infinispan server with systemctl
