infinispan/infinispan

- server/rest/src/main/java/org/infinispan/rest/RestServer.java
https://issues.redhat.com/browse/ISPN-12440
> ISPN-12440 LoggingResource endpoint does not work with Quarkus

- server/rest/src/main/java/org/infinispan/rest/RestServer.java
https://issues.redhat.com/browse/ISPN-12440
> [11.0.x] ISPN-12440 LoggingResource endpoint does not work with Quarkus

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/ContainerDatabase.java
https://issues.redhat.com/browse/ISPN-12103
> ISPN-12103 Improve ContainerDatabase to add custom wait strategy

- server/runtime/src/main/server/bin/server.conf
https://issues.redhat.com/browse/ISPN-12417
Supersedes https://github.com/infinispan/infinispan/pull/8769
> ISPN-12417 Enable server GC logs by default unless overridden

- server/runtime/src/main/server/bin/server.conf
https://issues.redhat.com/browse/ISPN-12417
> [11.0] ISPN-12417 Enable server GC logs by default unless overridden

- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
https://issues.redhat.com/browse/ISPN-12390
> ISPN-12390 Allow overriding the infinispan.server.conf.dir using system properties

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12397
> ISPN-12397 Upgrade to WildFly OpenSSL 1.0.11.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12397
> [11.0] ISPN-12397 Upgrade to WildFly OpenSSL 1.0.11.Final

- integrationtests/server-integration/server-integration-commons/pom.xml
- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/commons/client/AbstractMemcacheClientIT.java
- integrationtests/server-integration/server-integration-commons/src/test/resources/infinispan-custom.xml
- integrationtests/server-integration/third-party-server/pom.xml
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/DeploymentHelper.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/MemcachedClientIT.java
https://issues.redhat.com/browse/ISPN-12341
> ISPN-12341 Add Memcached client test for third-party-server

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12397
> ISPN-12397 WildFly OpenSSL 1.0.12.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12397
> [11.0] ISPN-12397 WildFly OpenSSL 1.0.12.Final

- server/rest/src/main/java/org/infinispan/rest/ResponseHeader.java
- server/rest/src/main/java/org/infinispan/rest/ResponseWriter.java
https://issues.redhat.com/browse/ISPN-12347
> ISPN-12347 Serving static resources from REST can hang

- server/rest/src/main/java/org/infinispan/rest/ResponseHeader.java
- server/rest/src/main/java/org/infinispan/rest/ResponseWriter.java
https://issues.redhat.com/browse/ISPN-12347
> [11.0.x] ISPN-12347 Serving static resources from REST can hang

- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
https://issues.redhat.com/browse/ISPN-12127
> ISPN-12127 Refresh CLI state before performing `ls`

- cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
https://issues.redhat.com/browse/ISPN-12127
> [11.0.x] ISPN-12127 Refresh CLI state before performing `ls`

- client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
- documentation/src/main/asciidoc/topics/json_examples/rest_caches_all_entries.json
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- server/rest/src/main/java/org/infinispan/rest/CacheEntryInputStream.java
- server/rest/src/main/java/org/infinispan/rest/CacheKeyInputStream.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
* Limit parameter
* Metadata parameter
* Limit parameter included for key streaming
https://issues.redhat.com/browse/ISPN-12444
> ISPN-12444 Stream K/V endpoint

- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheAdd.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerBuilder.java
- server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheService.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/partitionhandling/CustomEntryMergePolicyIT.java
https://issues.redhat.com/browse/ISPN-12420
Move the DeployedMergePolicyFactoryService dependency from the cache 
to the cache container
> [9.4.x] ISPN-12420 ConcurrentModificationException for EntryMergePolicyFactoryRegistry

- Jenkinsfile
- build-configuration/pom.xml
- cdi/embedded/pom.xml
- cdi/remote/pom.xml
- feature-pack/server/src/main/resources/modules/org/jgroups/extension/slot/module.xml
- integrationtests/cdi-jcache-it/pom.xml
- integrationtests/cdi-weld-se-it/pom.xml
- integrationtests/wildfly-modules/pom.xml
- jcache/embedded/pom.xml
- pom.xml
- server/core/src/main/java/org/infinispan/server/core/dataconversion/json/SecureTypeResolverBuilder.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/Authentication.java
- server/integration/jgroups/src/main/java/org/infinispan/server/jgroups/security/SaslClientCallbackHandler.java
- server/integration/testsuite/pom.xml
- server/integration/testsuite/src/test/resources/config/infinispan/hotrod-auth-qop.xml
Use and align dependencies with WF18. 
https://issues.redhat.com/browse/ISPN-12457
> [9.4.x] ISPN-12457 Use WF18 as base server

- pom.xml
https://issues.redhat.com/browse/ISPN-12471
> [9.4.x] ISPN-12471 Fix CI OOM

- pom.xml
https://issues.redhat.com/browse/ISPN-12471
> ISPN-12471 Fix CI OOM

- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java
- server/tests/src/test/java/org/infinispan/server/functional/BackupManagerIT.java
https://issues.redhat.com/browse/ISPN-12467
> ISPN-12467 Backup of cache content stores the key as the value

- Jenkinsfile
https://issues.redhat.com/browse/ISPN-12471
> ISPN-12471 Increase Maven heap size

- Jenkinsfile
- build-configuration/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-12471
> ISPN-12471 Upgrade PMD to version 6.29.0 + Increase Maven heap size 

- documentation/src/main/asciidoc/js/js.js
This updates the location of the version chooser drop down for community docs.
> [10.1.x] version chooser directory

- documentation/src/main/asciidoc/stories/assembly_contributing.adoc
- documentation/src/main/asciidoc/topics/contributing/docs.adoc
- documentation/src/main/asciidoc/topics/contributing/terminology.adoc
- documentation/src/main/asciidoc/topics/contributing/ui.adoc
- documentation/src/main/asciidoc/topics/proc_using_mvn_archetypes.adoc
https://issues.redhat.com/browse/ISPN-12384
> UI and terminology guidelines in contributor's guide

- core/src/main/java/org/infinispan/configuration/cache/TransactionConfigurationBuilder.java
- core/src/test/java/org/infinispan/configuration/ConfigurationUnitTest.java
https://issues.redhat.com/browse/ISPN-12104
> [11.0] ISPN-12104 Do not touch tx mode if unnecessary

- server/rest/src/main/java/org/infinispan/rest/ResponseWriter.java
https://issues.redhat.com/browse/ISPN-12494
> ISPN-12494 Incomplete chunked static resources from REST

- server/rest/src/main/java/org/infinispan/rest/ResponseWriter.java
https://issues.redhat.com/browse/ISPN-12494
> [11.0.x] ISPN-12494 Incomplete chunked static resources from REST

- pom.xml
https://issues.redhat.com/browse/ISPN-12507
> ISPN-12507 Upgrade to XStream 1.4.14

- pom.xml
https://issues.redhat.com/browse/ISPN-12507
> [11.0] ISPN-12507 Upgrade to XStream 1.4.14

- pom.xml
https://issues.redhat.com/browse/ISPN-12507
> [9.4] ISPN-12507 Upgrade to XStream 1.4.14

- documentation/src/main/asciidoc/stories/assembly_hotrod_client_api.adoc
- documentation/src/main/asciidoc/topics/con_off_heap_memory.adoc
- documentation/src/main/asciidoc/topics/counters.adoc
- documentation/src/main/asciidoc/topics/ref_hotrod_countermanager.adoc
https://issues.redhat.com/browse/ISPN-12490
This creates a reference for CounterManager in the Hot Rod docs. There is a plan to revamp the counter docs and improve structure and separation of embedded vs remote. Until then these changes should help HR users.
> ISPN-12490 CounterManager in HR docs

- documentation/src/main/asciidoc/stories/assembly_server_logging.adoc
- documentation/src/main/asciidoc/topics/con_access_logs.adoc
- documentation/src/main/asciidoc/topics/config_examples/enable_access_logs.xml
- documentation/src/main/asciidoc/topics/proc_configuring_log_properties.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_access_logs.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_json_logging.adoc
- documentation/src/main/asciidoc/topics/ref_access_log_properties.adoc
- documentation/src/main/asciidoc/topics/ref_logs_categories.adoc
- documentation/src/main/asciidoc/topics/ref_logs_formatters.adoc
- documentation/src/main/asciidoc/topics/ref_logs_handlers.adoc
- documentation/src/main/asciidoc/topics/ref_logs_levels.adoc
- documentation/src/main/asciidoc/topics/ref_logs_server.adoc
https://issues.redhat.com/browse/ISPN-12491
Needs backport to 11.0.x
> ISPN-12491 doc updates to server logging

- documentation/src/main/asciidoc/stories/assembly_server_logging.adoc
- documentation/src/main/asciidoc/topics/con_access_logs.adoc
- documentation/src/main/asciidoc/topics/config_examples/enable_access_logs.xml
- documentation/src/main/asciidoc/topics/proc_configuring_log_properties.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_access_logs.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_json_logging.adoc
- documentation/src/main/asciidoc/topics/ref_access_log_properties.adoc
- documentation/src/main/asciidoc/topics/ref_logs_categories.adoc
- documentation/src/main/asciidoc/topics/ref_logs_formatters.adoc
- documentation/src/main/asciidoc/topics/ref_logs_handlers.adoc
- documentation/src/main/asciidoc/topics/ref_logs_levels.adoc
- documentation/src/main/asciidoc/topics/ref_logs_server.adoc
https://issues.redhat.com/browse/ISPN-12491
> [11.0.x] ISPN-12491 doc updates to server logging

- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
https://issues.redhat.com/browse/ISPN-12492
> ISPN-12492 Server option to load property file

- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
https://issues.redhat.com/browse/ISPN-12492
> [11.0] ISPN-12492 Server option to load property file

- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-12496
> ISPN-12496 Support port offset for JGroups ports in the server

- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-12496
> [11.0] ISPN-12496 Support port offset for JGroups ports in the server

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/ProtocolVersion.java
https://issues.redhat.com/browse/ISPN-12514
> ISPN-12514 ProtocolVersion in HotRod must be 3.1

- build-configuration/pom.xml
- core/src/main/resources/default-configs/default-jgroups-azure.xml
- core/src/main/resources/default-configs/default-jgroups-ec2.xml
- core/src/main/resources/default-configs/default-jgroups-google.xml
- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/main/resources/default-configs/default-jgroups-udp.xml
- core/src/test/java/org/infinispan/configuration/JsonSerializationTest.java
- core/src/test/resources/configs/config-with-jgroups-stack.xml
- core/src/test/resources/configs/unified/12.0.xml
- core/src/test/resources/configs/xsite/bridge.xml
- core/src/test/resources/configs/xsite/xsite-inline-test.xml
- core/src/test/resources/stacks/broken-tcp.xml
- core/src/test/resources/stacks/tcp.xml
- core/src/test/resources/stacks/tcp_mping/tcp1.xml
- core/src/test/resources/stacks/tcp_mping/tcp2.xml
- core/src/test/resources/stacks/udp.xml
- hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
- server/testdriver/junit5/src/test/resources/jgroups/xsite-stacks.xml
- server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml
- tools/src/test/resources/udp.xml
https://issues.redhat.com/browse/ISPN-12510
> ISPN-12510 Upgrade JGroups to 4.2.9.Final

- build-configuration/pom.xml
- core/src/main/resources/default-configs/default-jgroups-azure.xml
- core/src/main/resources/default-configs/default-jgroups-ec2.xml
- core/src/main/resources/default-configs/default-jgroups-google.xml
- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/main/resources/default-configs/default-jgroups-udp.xml
- core/src/test/java/org/infinispan/configuration/JsonSerializationTest.java
- core/src/test/resources/configs/config-with-jgroups-stack.xml
- core/src/test/resources/configs/unified/11.0.xml
- core/src/test/resources/configs/xsite/bridge.xml
- core/src/test/resources/configs/xsite/xsite-inline-test.xml
- core/src/test/resources/stacks/broken-tcp.xml
- core/src/test/resources/stacks/tcp.xml
- core/src/test/resources/stacks/tcp_mping/tcp1.xml
- core/src/test/resources/stacks/tcp_mping/tcp2.xml
- core/src/test/resources/stacks/udp.xml
- documentation/src/main/asciidoc/topics/config_examples/jgroups-relay.xml
- hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
- server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
- server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml
- tools/src/test/resources/udp.xml
https://issues.redhat.com/browse/ISPN-12510
> [11.0.x] ISPN-12510 Upgrade JGroups to 4.2.9.Final

- server/runtime/src/main/server/bin/common.sh
https://issues.redhat.com/browse/ISPN-12502
I've copied the Java 9+ GC settings from the wildfly-core project.
> ISPN-12502 GC logging provided by default with GC_LOG is valid for Java 8 only

- server/runtime/src/main/server/bin/common.sh
https://issues.redhat.com/browse/ISPN-12502
https://issues.redhat.com/browse/JDG-4177
> [11.0.x] ISPN-12502 GC logging provided by default with GC_LOG is valid for Java 8 only

- component-processor/src/main/java/org/infinispan/component/processor/ComponentAnnotationProcessor.java
- component-processor/src/main/java/org/infinispan/component/processor/Generator.java
- component-processor/src/main/java/org/infinispan/component/processor/Model.java
https://issues.redhat.com/browse/ISPN-12521
> ISPN-12521 Component annotation processors fails incremental compilation

- core/src/main/java/org/infinispan/configuration/cache/TransactionConfigurationBuilder.java
* fix test
https://issues.redhat.com/browse/ISPN-12104
> [11.0.x] ISPN-12104 Do not touch tx mode if unnecessary

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AuthenticationConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/Authentication.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
https://issues.redhat.com/browse/ISPN-12515
> ISPN-12515 Improve HR authentication errors

- build-configuration/pom.xml
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDslConditionsTunedTest.java
- query-dsl/src/main/java/org/infinispan/query/dsl/Query.java
- query/src/main/java/org/infinispan/query/clustered/ClusteredQueryInvoker.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelper.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryBuilder.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryMaker.java
- query/src/main/java/org/infinispan/query/impl/EntityLoader.java
- query/src/main/java/org/infinispan/query/impl/IndexedQueryImpl.java
- query/src/main/java/org/infinispan/search/mapper/mapping/impl/IndexProperties.java
- query/src/main/java/org/infinispan/search/mapper/session/impl/InfinispanSearchSession.java
- query/src/test/java/org/infinispan/query/dsl/embedded/impl/LuceneTransformationTest.java
- query/src/test/java/org/infinispan/query/helper/IndexAccessor.java
- query/src/test/java/org/infinispan/query/helper/SearchConfig.java
- query/src/test/java/org/infinispan/query/helper/StaticTestingErrorHandler.java
- query/src/test/java/org/infinispan/query/timeout/DistributedIndexedTimeoutTest.java
- query/src/test/java/org/infinispan/query/timeout/LocalIndexedTimeoutTest.java
- query/src/test/java/org/infinispan/query/timeout/TestHelper.java
- query/src/test/resources/nrt-performance-writer-infinispandirectory.xml
- query/src/test/resources/nrt-performance-writer.xml
- query/src/test/resources/testconfig-LocalCachePerformantConfTest.xml
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/model/ProtobufRawTypeModel.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/typebridge/ProtobufMessageBinder.java
https://issues.redhat.com/browse/ISPN-12464
> ISPN-12464 Update to Hibernate Search 6.0.0.CR1

- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
https://issues.redhat.com/browse/ISPN-12547
You only will see this issue if you download the file `persistence/rocksdb/target/infinispan-infinispan-cachestore-rocksdb.log`
> ISPN-12547 NPE when closing RocksDB store

- core/src/test/java/org/infinispan/api/NonDuplicateModificationTest.java
- core/src/test/java/org/infinispan/util/ControlledRpcManager.java
https://issues.redhat.com/browse/ISPN-12541
https://issues.redhat.com/browse/ISPN-12542
> ISPN-12541 Remove ControlledRpcManager allRequests

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12553
> ISPN-12553 Upgrade to console 0.7.2.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12552
> ISPN-12552 Bump RocksDB 6.13.3

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/resources/testcontainers.properties
https://issues.redhat.com/browse/ISPN-12524
> [11.0.x] No more docker hub

- cli/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
- server/tests/src/test/java/org/infinispan/server/functional/CliBackupManagerIT.java
https://issues.redhat.com/browse/ISPN-12528
> ISPN-12528 CLI backup create doesn't reflect directory provided

- commons/all/src/main/java/org/infinispan/commons/util/SegmentAwareKey.java
- core/src/main/java/org/infinispan/commands/CommandsFactory.java
- core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
- core/src/main/java/org/infinispan/commands/SegmentSpecificCommand.java
- core/src/main/java/org/infinispan/commands/irac/IracCleanupKeyCommand.java
- core/src/main/java/org/infinispan/commands/irac/IracStateResponseCommand.java
- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/interceptors/xsite/BaseBackupInterceptor.java
- core/src/main/java/org/infinispan/interceptors/xsite/NonTransactionalBackupInterceptor.java
- core/src/main/java/org/infinispan/interceptors/xsite/OptimisticBackupInterceptor.java
- core/src/main/java/org/infinispan/interceptors/xsite/PessimisticBackupInterceptor.java
- core/src/main/java/org/infinispan/util/ExponentialBackOff.java
- core/src/main/java/org/infinispan/util/ExponentialBackOffImpl.java
- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/main/java/org/infinispan/xsite/irac/IracExecutor.java
- core/src/main/java/org/infinispan/xsite/irac/IracManager.java
- core/src/main/java/org/infinispan/xsite/irac/IracResponseCollector.java
- core/src/main/java/org/infinispan/xsite/irac/NoOpIracManager.java
- core/src/test/java/org/infinispan/util/ExponentialBackOffImplUnitTest.java
- core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
- core/src/test/java/org/infinispan/xsite/irac/ControlledIracManager.java
- core/src/test/java/org/infinispan/xsite/irac/IracExponentialBackOffTest.java
- core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java
- core/src/test/java/org/infinispan/xsite/irac/persistence/IracMetadataStoreTest.java
https://issues.redhat.com/browse/ISPN-12477
> ISPN-12477 Remove IRAC sender thread

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationKeyCloakIT.java
- server/tests/src/test/java/org/infinispan/server/test/core/KeyCloakServerRule.java
- server/tests/src/test/resources/keycloak/infinispan-rhsso-realm.json
https://issues.redhat.com/browse/ISPN-12551
> ISPN-12551 Override existing parameters for Keycloak test integration

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationKeyCloakIT.java
- server/tests/src/test/java/org/infinispan/server/test/core/KeyCloakServerRule.java
- server/tests/src/test/resources/keycloak/infinispan-rhsso-realm.json
https://issues.redhat.com/browse/ISPN-12551
> [11.x] ISPN-12551 Override existing parameters for Keycloak test integration

- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-12498
> ISPN-12498 Single-server shutdown authz permissions

- cli/src/main/java/org/infinispan/cli/commands/Backup.java
- cli/src/main/resources/help/backup.adoc
- documentation/src/main/asciidoc/topics/backup_resources.adoc
- documentation/src/main/asciidoc/topics/proc_cli_backup_creating.adoc
- documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
- documentation/src/main/asciidoc/topics/ref_rest_clusters.adoc
- server/core/src/main/java/org/infinispan/server/core/BackupManager.java
- server/core/src/main/java/org/infinispan/server/core/backup/BackupManagerResources.java
- server/core/src/main/java/org/infinispan/server/core/backup/Constants.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheConfigResource.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/ContainerResourceFactory.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/InternalCacheResource.java
- server/core/src/test/java/org/infinispan/server/core/backup/BackupManagerImplTest.java
- server/tests/src/test/java/org/infinispan/server/functional/BackupManagerIT.java
- server/tests/src/test/java/org/infinispan/server/functional/CliBackupManagerIT.java
https://issues.redhat.com/browse/ISPN-12398
> ISPN-12398 Update Backup manager resource names and directories

- documentation/src/main/asciidoc/stories/assembly_cache_clustered.adoc
- documentation/src/main/asciidoc/topics/con_expiration_maxidle.adoc
- documentation/src/main/asciidoc/topics/ref_cache_modes.adoc
- documentation/src/main/asciidoc/topics/ref_cache_modes_comparison.adoc
https://issues.redhat.com/browse/ISPN-12567
> ISPN-12567 remove scattered cache conditionals

- documentation/src/main/asciidoc/stories/assembly_cache_clustered.adoc
- documentation/src/main/asciidoc/topics/con_expiration_maxidle.adoc
- documentation/src/main/asciidoc/topics/ref_cache_modes.adoc
- documentation/src/main/asciidoc/topics/ref_cache_modes_comparison.adoc
https://issues.redhat.com/browse/ISPN-12567
> [11.0.x] ISPN-12567 remove scattered cache conditionals

- cli/src/main/resources/help/alias.adoc
- cli/src/main/resources/help/config.adoc
- cli/src/main/resources/help/unalias.adoc
- documentation/src/main/asciidoc/stories/assembly_cli_command_reference.adoc
- documentation/src/main/asciidoc/stories/assembly_cli_config.adoc
- documentation/src/main/asciidoc/topics/proc_cli_creating_command_aliases.adoc
- documentation/src/main/asciidoc/topics/ref_cache_modes_comparison.adoc
- documentation/src/main/asciidoc/topics/ref_cli_storage_directory.adoc
https://issues.redhat.com/browse/ISPN-12568 
Needs backport to 11.0.x
> ISPN-12568 CLI alias command help

- cli/cli-client/src/main/resources/help/config.adoc
- cli/src/main/resources/help/alias.adoc
- cli/src/main/resources/help/unalias.adoc
- documentation/src/main/asciidoc/stories/assembly_cli_command_reference.adoc
- documentation/src/main/asciidoc/stories/assembly_cli_config.adoc
- documentation/src/main/asciidoc/topics/proc_cli_creating_command_aliases.adoc
- documentation/src/main/asciidoc/topics/ref_cache_modes_comparison.adoc
- documentation/src/main/asciidoc/topics/ref_cli_storage_directory.adoc
https://issues.redhat.com/browse/ISPN-12568
> [11.0.x] ISPN-12568 CLI alias command help

- documentation/src/main/asciidoc/topics/json_examples/rest_caches_all_entries.json
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- server/rest/src/main/java/org/infinispan/rest/CacheEntryInputStream.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-12565
> ISPN-12565 Converts lifespan and maxidle to seconds

- documentation/src/main/asciidoc/topics/ref_rest_logging.adoc
https://issues.redhat.com/browse/ISPN-12573
correction of wrong request example
> ISPN-12573 small correction of REST API request in documentation

- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-12498
> [11.0] ISPN-12498 Single-server shutdown authz permissions

- server/hotrod/src/main/java/org/infinispan/server/hotrod/Authentication.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/SaslConfigurationBuilder.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/configuration/AuthenticationConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/hotrod/HotRodServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/configuration/rest/RestServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
- server/runtime/src/main/java/org/infinispan/server/security/ElytronHTTPAuthenticator.java
- server/runtime/src/main/java/org/infinispan/server/security/ElytronSASLAuthenticationProvider.java
- server/runtime/src/main/java/org/infinispan/server/security/ServerSecurityRealm.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/api/RestTestClientDriver.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationImplicitIT.java
https://issues.redhat.com/browse/ISPN-12576
> ISPN-12576 Filter authentication mechanism on the Elytron authenticator

- server/hotrod/src/main/java/org/infinispan/server/hotrod/Authentication.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/SaslConfigurationBuilder.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
- server/rest/src/main/java/org/infinispan/rest/BaseHttpRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/configuration/AuthenticationConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/hotrod/HotRodServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/configuration/rest/RestServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
- server/runtime/src/main/java/org/infinispan/server/security/ElytronHTTPAuthenticator.java
- server/runtime/src/main/java/org/infinispan/server/security/ElytronSASLAuthenticationProvider.java
- server/runtime/src/main/java/org/infinispan/server/security/ServerSecurityRealm.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/api/RestTestClientDriver.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationImplicitIT.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationKerberosIT.java
- server/tests/src/test/java/org/infinispan/server/security/authentication/RestAuthentication.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
https://issues.redhat.com/browse/ISPN-12576
> [11.0] ISPN-12576 Filter authentication mechanism on the Elytron authenticator

- persistence/soft-index/pom.xml
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/SyncProcessingQueue.java
- persistence/soft-index/src/test/java/org/infinispan/persistence/sifs/SyncProcessingQueueBenchmark.java
https://issues.redhat.com/browse/ISPN-12481
> ISPN-12481 lock-free SyncProcessingQueue

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestServer.java
- server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerRule.java
https://issues.redhat.com/browse/ISPN-12583
> ISPN-12583 InfinispanServerRule cannot be reused

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12590
> ISPN-12590 Upgrade console to 0.12.Final

- build-configuration/pom.xml
- core/pom.xml
- core/src/main/java/org/infinispan/marshall/persistence/impl/PersistenceContextInitializer.java
- core/src/main/java/org/infinispan/marshall/protostream/impl/UUIDAdapter.java
https://issues.redhat.com/browse/ISPN-12463
> ISPN-12463 Upgrade to protostream 4.4.0.Alpha4

- cli/src/main/java/org/infinispan/cli/commands/CLI.java
- server/runtime/src/main/server/bin/cli.sh
- server/runtime/src/main/server/bin/common.sh
https://issues.redhat.com/browse/ISPN-12588
> ISPN-12588 Fix server's common.sh to handle custom paths correctly

- core/src/main/java/org/infinispan/commands/CommandsFactory.java
- core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/marshall/exts/EnumExternalizer.java
- core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteStateTransferCancelSendCommand.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteStateTransferClearStatusCommand.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteStateTransferFinishReceiveCommand.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteStateTransferRestartSendingCommand.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteStateTransferStartReceiveCommand.java
- core/src/main/java/org/infinispan/xsite/commands/XSiteStateTransferStartSendCommand.java
- core/src/main/java/org/infinispan/xsite/statetransfer/NoOpXSiteStateTransferManager.java
- core/src/main/java/org/infinispan/xsite/statetransfer/RemoteSiteStatus.java
- core/src/main/java/org/infinispan/xsite/statetransfer/StateTransferStatus.java
- core/src/main/java/org/infinispan/xsite/statetransfer/StatusResponseCollector.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateProviderImpl.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferManager.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferManagerImpl.java
- core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java
- core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
- core/src/test/java/org/infinispan/xsite/statetransfer/failures/StateTransferLinkFailuresTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
* Changes for ISPN-12476 (IRAC state transfer)
https://issues.redhat.com/browse/ISPN-12575
> ISPN-12575 Refactor XSiteStateTransferManager

- build-configuration/pom.xml
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/FileSystemRealmConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/LdapRealmConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/PropertiesRealmConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/RealmConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/RealmConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/TokenRealmConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/TrustStoreRealmConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/CachingModifiableSecurityRealm.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/CachingSecurityRealm.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/EncryptedPropertiesSecurityRealm.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/PropertiesSecurityRealm.java
- server/runtime/src/main/resources/schema/infinispan-server-12.0.xsd
https://issues.redhat.com/browse/ISPN-12156
> ISPN-12156 Security Realm identity caching

- core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
- core/src/main/java/org/infinispan/configuration/parsing/ParseUtils.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfigurationParser.java
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfigurationParser.java
https://issues.redhat.com/browse/ISPN-12592
> ISPN-12592 Improve error message when XML element is removed

- cli/cli-client/src/main/java/org/infinispan/cli/commands/CLI.java
- server/runtime/src/main/server/bin/cli.sh
- server/runtime/src/main/server/bin/common.sh
https://issues.redhat.com/browse/ISPN-12588
> [11.0] ISPN-12588 Fix server's common.sh to handle custom paths correctly

- documentation/src/main/asciidoc/topics/con_server_directory_structure.adoc
- server/runtime/src/main/server/README.adoc
https://issues.redhat.com/browse/ISPN-12599
> ISPN-12599 server home and root properties

- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/logging/Log.java
https://issues.redhat.com/browse/ISPN-12534
> ISPN-12534 Report missing index annotations

- core/src/main/java/org/infinispan/stats/impl/CacheContainerStatsImpl.java
- core/src/test/java/org/infinispan/jmx/CacheContainerStatsMBeanTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
https://issues.redhat.com/browse/ISPN-12607
> ISPN-12607 Cache container stat collection

- core/src/main/java/org/infinispan/stats/impl/CacheContainerStatsImpl.java
- core/src/test/java/org/infinispan/jmx/CacheContainerStatsMBeanTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
https://issues.redhat.com/browse/ISPN-12607
> [11.x] ISPN-12607 Cache container stat collection

- persistence/remote/pom.xml
- persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/MigrationTask.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/CustomObject.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeEncodingsTest.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradePojoTest.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/SerializationCtx.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/TestCluster.java
- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeIT.java
https://issues.redhat.com/browse/ISPN-12616
> [11.0.x] ISPN-12616 Rolling Upgrade fails for caches storing POJOs

- server/rest/src/main/java/org/infinispan/rest/ALPNHandler.java
- server/rest/src/test/java/org/infinispan/rest/PipelineInitializationTest.java
https://issues.redhat.com/browse/ISPN-12602
> ISPN-12602 WARN during server start: java.lang.IllegalArgumentException: configList.size

- server/rest/src/main/java/org/infinispan/rest/ALPNHandler.java
- server/rest/src/test/java/org/infinispan/rest/PipelineInitializationTest.java
https://issues.redhat.com/browse/ISPN-12602
> [11.0.x] ISPN-12602 WARN during server start: java.lang.IllegalArgumentException: configList.size

- documentation/src/main/asciidoc/stories/assembly_configuring_maven_repository.adoc
- documentation/src/main/asciidoc/topics/proc_adding_maven_repository.adoc
https://issues.redhat.com/browse/ISPN-12608
Needs backport to 11.0.x
> ISPN-12608 maven repos update

- documentation/src/main/asciidoc/stories/assembly_configuring_maven_repository.adoc
- documentation/src/main/asciidoc/topics/proc_adding_maven_repository.adoc
https://issues.redhat.com/browse/ISPN-12608
> [11.0.x] ISPN-12608 maven repos update

- core/src/main/resources/schema/infinispan-config-12.0.xsd
https://issues.redhat.com/browse/ISPN-12629
> ISPN-12629 XSD "segmented" description is incorrect

- core/src/main/resources/schema/infinispan-config-11.0.xsd
https://issues.redhat.com/browse/ISPN-12629
> [11.x] ISPN-12629 XSD "segmented" description is incorrect

- documentation/src/main/asciidoc/topics/proc_adding_maven_repository.adoc
https://issues.redhat.com/browse/ISPN-12608
> ISPN-12608 maven config docs

- documentation/src/main/asciidoc/topics/proc_adding_maven_repository.adoc
https://issues.redhat.com/browse/ISPN-12608
> [11.0.x] ISPN-12608 maven config docs

- core/src/main/java/org/infinispan/configuration/cache/IndexingConfigurationBuilder.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/resources/schema/infinispan-config-12.0.xsd
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- query/src/main/java/org/infinispan/query/impl/config/SearchPropertyExtractor.java
- query/src/test/java/org/infinispan/query/config/EngineConfigTest.java
https://issues.redhat.com/browse/ISPN-12536
> ISPN-12536 Use the global storage to store indexes in the server

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/multimap/RemoteMultimapCacheAPITest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/multimap/RemoteMultimapStateTransferTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java
- multimap/src/main/java/org/infinispan/multimap/impl/Bucket.java
- multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapCache.java
- multimap/src/main/java/org/infinispan/multimap/impl/function/ContainsFunction.java
- multimap/src/main/java/org/infinispan/multimap/impl/function/PutFunction.java
- multimap/src/main/java/org/infinispan/multimap/impl/function/RemoveFunction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/MultimapRequestProcessor.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/VersionedEncoder.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestClientXSiteDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestClient.java
- server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanXSiteServerTestMethodRule.java
- server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanXSiteServerExtension.java
- server/tests/src/test/java/org/infinispan/server/functional/HotRodMultiMapOperations.java
- server/tests/src/test/java/org/infinispan/server/functional/XSiteHotRodCacheOperations.java
https://issues.redhat.com/browse/ISPN-12635
> ISPN-12635 Multimap Bucket can't get replicated in server mode

- documentation/src/main/asciidoc/topics/proc_implementing_protostream_sci.adoc
https://issues.redhat.com/browse/ISPN-12626
> [11.0.x] ISPN-12626 note message marshaller deprecation

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/EvictionProtobufTest.java
- core/src/main/java/org/infinispan/marshall/core/WrappedByteArraySizeCalculator.java
https://issues.redhat.com/browse/ISPN-12641
> ISPN-12641 IllegalArgumentException when using eviction by size with protobuf indexed caches

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12645
> ISPN-12645 Upgrade console to 0.13.Final

- documentation/src/main/asciidoc/topics/code_examples/JBossUserMarshaller.java
- documentation/src/main/asciidoc/topics/config_examples/jboss_user_marshaller.xml
- documentation/src/main/asciidoc/topics/proc_using_jboss_marshaller.adoc
https://issues.redhat.com/browse/ISPN-12626
Needs backport to 11.0.x
> Update to jboss marshalling

- documentation/src/main/asciidoc/topics/code_examples/JBossUserMarshaller.java
- documentation/src/main/asciidoc/topics/config_examples/jboss_user_marshaller.xml
- documentation/src/main/asciidoc/topics/proc_using_jboss_marshaller.adoc
https://issues.redhat.com/browse/ISPN-12626
> [11.0.x] update to jboss marshalling

- cli/src/main/resources/operator/operator-install.yaml
- cli/src/main/resources/operator/operator-subscription.yaml
- cli/src/main/resources/operator/operator-uninstall.yaml
https://issues.redhat.com/browse/ISPN-12648
> ISPN-12648 Update CLI operator files for 12.x

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfiguration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/TransactionConfiguration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/TransactionConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/APITest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tx/APITxTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tx/LCROTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tx/MultipleCacheTxFunctionalTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tx/RecoveryTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tx/TxFunctionalTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tx/util/TransactionSetup.java
- client/hotrod-client/src/test/resources/hotrod-client-percache.properties
- documentation/src/main/asciidoc/topics/attributes/transaction-attributes.adoc
- documentation/src/main/asciidoc/topics/ref_hotrod_client_transactions.adoc
- server/tests/src/test/java/org/infinispan/server/functional/HotRodTransactionalCacheOperations.java
https://issues.redhat.com/browse/ISPN-12627
> ISPN-12627 Per-cache Hot Rod configuration ignores transaction mode

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/stress/RemoteClientPutGetTest.java
- pom.xml
- server/core/pom.xml
- server/core/src/main/java/org/infinispan/server/core/RequestTracer.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/Containers.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedServer.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/ContainerDatabase.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/DatabaseServerListener.java
- server/tests/pom.xml
- server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java
- server/tests/src/test/java/org/infinispan/server/persistence/PersistenceIT.java
https://issues.redhat.com/browse/ISPN-10013
Please do not close the issue, this PR is only a partial fix.
Only track Hot Rod cache write requests (i.e. no counters, multimap etc.)
to simplify the implementation.
The implementation is selected with system properties
infinispan.opentracing.factory.class and
infinispan.opentracing.factory.method.
An OpenTracing implementation is not included, instead it must be added
to the server/lib directory.
> ISPN-10013 Observability: Distributed tracing

- build-configuration/pom.xml
- commons/all/src/main/java/org/infinispan/commons/util/SslContextFactory.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/RealmConfigurationBuilder.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
https://issues.redhat.com/browse/ISPN-12639
> ISPN-12639 Use OpenSSL provider explicitly

- core/src/test/java/org/infinispan/xsite/irac/IracWriteSkewTest.java
https://issues.redhat.com/browse/ISPN-12658
> ISPN-12658 Fix IracWriteSkewTest test

- query/src/test/java/org/infinispan/query/blackbox/LocalIndexSyncStateTransferTest.java
https://issues.redhat.com/browse/ISPN-12663
> ISPN-12663 LocalIndexSyncStateTransferTest random failures

- query/src/test/java/org/infinispan/query/distributed/StatsTest.java
https://issues.redhat.com/browse/ISPN-12659
> ISPN-12659 StatsTest random failures

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/ReplicationIndexTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java
https://issues.redhat.com/browse/ISPN-12666
> ISPN-12666 ReplicationIndexTest random failures

- core/src/main/java/org/infinispan/persistence/file/SingleFileStore.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/SoftIndexFileStore.java
https://issues.redhat.com/browse/ISPN-12665
https://issues.redhat.com/browse/ISPN-12671
> ISPN-12665 Add cache name to peristence migration logs

- server/testdriver/junit5/pom.xml
- spring/spring-boot/pom.xml
- spring/spring-boot/remote/pom.xml
https://issues.redhat.com/browse/ISPN-12669
> [12.0.x] ISPN-12669 Tests failing due to relying on published images

- server/testdriver/junit5/pom.xml
- spring/spring-boot/pom.xml
- spring/spring-boot/remote/pom.xml
https://issues.redhat.com/browse/ISPN-12669
> ISPN-12669 Tests failing due to relying on published images

- persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeEncodingsTest.java
https://issues.redhat.com/browse/ISPN-12692
> ISPN-12692 HotRodUpgradeEncodingsTest random failures

- server/rest/src/main/java/org/infinispan/rest/resources/LoginResource.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-12664
> ISPN-12664 Deprecate login and add supported mechs on config

- integrationtests/server-integration/third-party-server/pom.xml
https://issues.redhat.com/browse/ISPN-12695
> ISPN-12695 Remove unzip tomcat logic from third-party-server module

- integrationtests/server-integration/third-party-server/pom.xml
- integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
https://issues.redhat.com/browse/ISPN-12695
I am sorry that I didn't catch this while working on https://github.com/infinispan/infinispan/pull/9037
> ISPN-12697 Remove unzip eap logic from third-party-server module

- core/src/main/java/org/infinispan/remoting/transport/impl/MapResponseCollector.java
- core/src/main/java/org/infinispan/remoting/transport/impl/VoidResponseCollector.java
- core/src/test/java/org/infinispan/functional/FunctionalTestUtils.java
- lock/src/test/java/org/infinispan/lock/ConsistentReliabilitySplitBrainTest.java
https://issues.redhat.com/browse/ISPN-12710
Do not add a suppressed exception unless the existing exception
is a RemoteException.
> ISPN-12710 IllegalArgumentException in VoidResponseCollector

- cli/src/main/java/org/infinispan/cli/commands/Batch.java
- cli/src/main/java/org/infinispan/cli/commands/CLI.java
- cli/src/main/java/org/infinispan/cli/commands/Quit.java
- cli/src/main/java/org/infinispan/cli/commands/Run.java
- cli/src/main/java/org/infinispan/cli/impl/CliRuntimeRunner.java
- cli/src/main/java/org/infinispan/cli/impl/ExitCodeResultHandler.java
- cli/src/main/resources/help/quit.adoc
https://issues.redhat.com/browse/ISPN-12700
> ISPN-12700 Return non-zero exit code from CLI on error

- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/Index.java
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/IndexNode.java
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/SoftIndexFileStore.java
- persistence/soft-index/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java
https://issues.redhat.com/browse/ISPN-12630
> ISPN-12630 SIFS does not set the seqId when loading index from disk

- core/src/main/java/org/infinispan/security/actions/GetEmbeddedCacheManagerAction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/DefaultIterationManager.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationManager.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/SecurityActions.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
https://issues.redhat.com/browse/ISPN-12716
> ISPN-12716 Hot Rod iteration shouldn't require ADMIN permission

- core/src/main/java/org/infinispan/security/actions/GetEmbeddedCacheManagerAction.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/DefaultIterationManager.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationManager.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/SecurityActions.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
https://issues.redhat.com/browse/ISPN-12716
> [12.0.x] ISPN-12716 Hot Rod iteration shouldn't require ADMIN permission

- cli/src/main/java/org/infinispan/cli/commands/Batch.java
- cli/src/main/java/org/infinispan/cli/commands/CLI.java
- cli/src/main/java/org/infinispan/cli/commands/Quit.java
- cli/src/main/java/org/infinispan/cli/commands/Run.java
- cli/src/main/java/org/infinispan/cli/impl/CliRuntimeRunner.java
- cli/src/main/java/org/infinispan/cli/impl/ExitCodeResultHandler.java
- cli/src/main/resources/help/quit.adoc
https://issues.redhat.com/browse/ISPN-12700
> [12.0] ISPN-12700 Return non-zero exit code from CLI on error

- commons/all/src/main/java/org/infinispan/commons/marshall/ProtoStreamTypeIds.java
- spring/spring5/spring5-common/pom.xml
- spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/PersistenceContextInitializer.java
- spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/provider/NullValue.java
- spring/spring5/spring5-embedded/pom.xml
- spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/SpringEmbeddedModule.java
- spring/spring5/spring5-embedded/src/test/java/org/infinispan/spring/embedded/provider/SpringCacheTest.java
- spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/provider/named-async-cache.xml
https://issues.redhat.com/browse/ISPN-12268
Add a ModuleLifecycle implementation in the spring2-embedded module
to enrich embedded caches.
* Register protostream serialization context initializer for NullValue.
* Add NullValue to allow list.
> ISPN-12268 Support Protobuf Marshaller in Embedded Spring Caches

- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheConfigResource.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/CounterResource.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/InternalCacheResource.java
https://issues.redhat.com/browse/ISPN-12718
> ISPN-12718 Add addtional DEBUG logs to Backup/Restore operations

- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheConfigResource.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/CounterResource.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/InternalCacheResource.java
https://issues.redhat.com/browse/ISPN-12718
> [12.0] ISPN-12718 Add addtional DEBUG logs to Backup/Restore operations

- client/hotrod-client/pom.xml
https://issues.redhat.com/browse/ISPN-12724
> ISPN-12724 Trim Elytron dependencies from the Hot Rod client

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12729
> [12.0] ISPN-12729 Upgrade console 0.13.1.Final

- client/hotrod-client/pom.xml
https://issues.redhat.com/browse/ISPN-12724
> [12.0] ISPN-12724 Trim Elytron dependencies from the Hot Rod client

- pom.xml
https://issues.redhat.com/browse/ISPN-12277
> ISPN-12277 Testcontainers ResourceReaper::start blocks test startup

- integrationtests/server-integration/third-party-server/pom.xml
https://issues.redhat.com/browse/ISPN-12732
> ISPN-12732 Replace org.wildfly with ${appserver.groupId} in pom.xml

- build-configuration/pom.xml
[ISPN-12740](https://issues.redhat.com/browse/ISPN-12740) Netty 4.1.59
[ISPN-12741](https://issues.redhat.com/browse/ISPN-12741) Log4j 2.14.0
[ISPN-12742](https://issues.redhat.com/browse/ISPN-12742) JGroups 4.2.11
[ISPN-12743](https://issues.redhat.com/browse/ISPN-12743) Jackson 2.12.1
[ISPN-12745](https://issues.redhat.com/browse/ISPN-12745) Elytron 1.14.2
> Various upgrades

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/IndexedCacheNonIndexedEntityTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/logging/Log.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/SerializationContextSearchMapping.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/search/IndexedCacheNonIndexedEntityTest.java
https://issues.redhat.com/browse/ISPN-12684
> ISPN-12684 Lazy start SearchMapping for protobuf caches

- documentation/src/main/asciidoc/topics/config_examples/server_ssl_identity_truststore.xml
- documentation/src/main/asciidoc/topics/proc_server_identity_ssl.adoc
- documentation/src/main/asciidoc/topics/ref_server_realm_trust.adoc
- documentation/src/main/asciidoc/topics/upgrading.adoc
- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/SSLConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/SSLConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/ServerIdentitiesConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/ServerIdentitiesConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/TrustStoreConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/TrustStoreConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/TrustStoreRealmConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/TrustStoreRealmConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
- server/runtime/src/main/resources/schema/infinispan-server-12.1.xsd
- server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationParserTest.java
- server/runtime/src/test/resources/configuration/ServerConfigurationParserTest.xml
- server/tests/src/test/java/org/infinispan/server/security/CertWithoutAuthenticationIT.java
- server/tests/src/test/resources/configuration/CertWithoutAuthenticationTest.xml
- server/tests/src/test/resources/configuration/endpoints/cert-implicit.xml
- server/tests/src/test/resources/configuration/security/tls-truststore.xml
- server/tests/src/test/resources/configuration/security/trustrealm.xml
https://issues.redhat.com/browse/ISPN-12726
> ISPN-12726 Trust Store

- documentation/src/main/asciidoc/topics/ref_cache_modes_comparison.adoc
https://issues.redhat.com/browse/ISPN-12769
> [11.0.x] ISPN-12769 no indexing with invalidation caches

- documentation/src/main/asciidoc/topics/ref_cache_modes_comparison.adoc
https://issues.redhat.com/browse/ISPN-12769
> [12.0.x] ISPN-12769 no indexing with invalidation caches

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryRepeatedMappingTest.java
- client/hotrod-client/src/test/resources/indexed-repeated.proto
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/MessageReferenceProvider.java
https://issues.redhat.com/browse/ISPN-12730
> ISPN-12730 NPE when mapping a repeated non-indexed field in a schema

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryRepeatedMappingTest.java
- client/hotrod-client/src/test/resources/indexed-repeated.proto
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/MessageReferenceProvider.java
https://issues.redhat.com/browse/ISPN-12730
> [12.0.x] ISPN-12730 NPE when mapping a repeated non-indexed field in a schema

- cli/src/main/resources/help/credentials.adoc
- documentation/src/main/asciidoc/topics/config_examples/server_credentials.xml
- documentation/src/main/asciidoc/topics/config_examples/server_credentials_datasource.xml
- documentation/src/main/asciidoc/topics/config_examples/server_credentials_ldap.xml
https://issues.redhat.com/browse/ISPN-12774
> ISPN-12774 Credential store support example for datasource is incomplete

- client/hotrod-client/pom.xml
https://issues.redhat.com/browse/ISPN-12724
> ISPN-12724 Add elytron-password-impl dependency

- client/hotrod-client/pom.xml
https://issues.redhat.com/browse/ISPN-12724
> [12.0] ISPN-12724 Add elytron-password-impl dependency

- build-configuration/pom.xml
- query/src/main/java/org/infinispan/search/mapper/model/impl/InfinispanPropertyModel.java
- query/src/main/java/org/infinispan/search/mapper/model/impl/InfinispanRawTypeModel.java
https://issues.redhat.com/browse/ISPN-12776
This may also fix https://issues.redhat.com/browse/ISPN-12694
CC @gustavonalle
> ISPN-12776 Upgrade to Hibernate Search 6.0.2.Final

- documentation/src/main/asciidoc/topics/ref_query_embedded.adoc
- documentation/src/main/asciidoc/topics/ref_query_remote.adoc
https://issues.redhat.com/browse/ISPN-12773
> ISPN-12773 query doc fixes

- wildfly/feature-pack/src/main/resources/modules/com/amazonws/aws-java-sdk/slot/module.xml
- wildfly/feature-pack/src/main/resources/modules/org/infinispan/slot/module.xml
https://issues.redhat.com/browse/ISPN-12805
> ISPN-12805 WildFly Modules: separate the AWS dependencies into a module

- distribution/package.xml
* fixed path to licenses-overwrite.xml
https://issues.redhat.com/browse/ISPN-12817
> ISPN-12817 Fix path when packaging licenses

- distribution/src/main/resources/template/licenses.xsl
https://issues.redhat.com/browse/ISPN-12816
> ISPN-12816 Create alias for GPL v2 + CE license

- query/src/main/java/org/infinispan/query/Indexer.java
- query/src/main/java/org/infinispan/query/Search.java
- query/src/main/java/org/infinispan/query/Transformable.java
- query/src/main/java/org/infinispan/query/Transformer.java
- query/src/main/java/org/infinispan/query/package-info.java
https://issues.redhat.com/browse/ISPN-12050
Some minor suggestions to comments in the Query API.
> ISPN-12050 consistency edits for Query docs

- cli/src/main/java/org/infinispan/cli/commands/CLI.java
https://issues.redhat.com/browse/ISPN-12819
> ISPN-12819 CLI invalid connection string results in zero exit code

- documentation/src/main/asciidoc/topics/proc_creating_caches_hotrod_onaccess.adoc
https://issues.redhat.com/browse/ISPN-12771 
Needs backport
> ISPN-12771 Clarify HR onaccess

- documentation/src/main/asciidoc/stories/assembly_server_getting_started.adoc
https://issues.redhat.com/browse/ISPN-12603 
Needs backport to 12.0.x and 11.0.x
> ISPN-12603 link to image getting started

- core/src/main/java/org/infinispan/globalstate/impl/OverlayLocalConfigurationStorage.java
https://issues.redhat.com/browse/ISPN-12572
https://issues.redhat.com/browse/ISPN-12571
https://issues.redhat.com/browse/ISPN-11687
https://issues.redhat.com/browse/ISPN-9146
Add synchronization in OverlayLocalConfigurationStorage.persistConfigurations
so that a single thread tries to rename the caches.xml file at a time.
> ISPN-12572 OverlappingFileLockException in OverlayLocalConfigurationStorage

- server/runtime/src/main/server/server/conf/log4j2.xml
https://issues.redhat.com/browse/ISPN-12677
> ISPN-12677 Show date and time in the STDOUT Console Appender

- jcache/embedded/src/main/java/org/infinispan/jcache/embedded/JCacheManager.java
- jcache/embedded/src/test/java/org/infinispan/jcache/JCacheConfigurationTest.java
https://issues.redhat.com/browse/ISPN-12811
> ISPN-12811 Programmatic JCache configuration

- jcache/embedded/src/main/java/org/infinispan/jcache/embedded/JCacheManager.java
- jcache/embedded/src/test/java/org/infinispan/jcache/JCacheConfigurationTest.java
- jcache/embedded/src/test/resources/infinispan_uri.xml
https://issues.redhat.com/browse/ISPN-12797
> ISPN-12797 JCache embedded property replacement

- jcache/embedded/src/main/java/org/infinispan/jcache/embedded/JCacheManager.java
- jcache/embedded/src/test/java/org/infinispan/jcache/JCacheConfigurationTest.java
- jcache/embedded/src/test/resources/infinispan_uri.xml
https://issues.redhat.com/browse/ISPN-12797
> [12.0] ISPN-12797 JCache embedded property replacement

- server/rest/src/main/resources/io/smallrye/metrics/base-metrics.properties
https://issues.redhat.com/browse/ISPN-12800
> ISPN-12800 Add some missing JVM metrics

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12827
> ISPN-12827 upgrade to console 0.13.2.Final

- archetypes/store/src/main/resources/archetype-resources/src/main/java/CustomStoreConfigurationParser.java
https://issues.redhat.com/browse/ISPN-12618
> ISPN-12618 Fix archetype after parser changes

- commons/all/src/main/java/org/infinispan/commons/configuration/ClassAllowList.java
- commons/all/src/main/java/org/infinispan/commons/configuration/ClassWhiteList.java
- commons/all/src/main/java/org/infinispan/commons/marshall/CheckedInputStream.java
- core/src/main/java/org/infinispan/configuration/global/AllowListConfiguration.java
- core/src/main/java/org/infinispan/configuration/global/AllowListConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/global/SerializationConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/ConfigurationBuilderHolder.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/tests/src/test/java/org/infinispan/server/extensions/ExtensionsIT.java
- server/tests/src/test/java/org/infinispan/server/extensions/Person.java
- server/tests/src/test/java/org/infinispan/server/extensions/PojoMarshalling.java
- server/tests/src/test/resources/configuration/cache-container/clustered.xml
https://issues.redhat.com/browse/ISPN-12812
> ISPN-12812 Set the server cache manager class loader

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/DataFormat.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfiguration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/DelegatingRemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InternalRemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemotePublisher.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/MarshallerPerCacheTest.java
- client/hotrod-client/src/test/resources/hotrod-client-percache.properties
https://issues.redhat.com/browse/ISPN-12808
> [12.0.x] ISPN-12808 Per-cache Hot Rod client marshaller

- documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
- documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- documentation/src/main/asciidoc/topics/ref_rest_clusters.adoc
- documentation/src/main/asciidoc/topics/ref_rest_counters.adoc
- documentation/src/main/asciidoc/topics/ref_rest_logging.adoc
- documentation/src/main/asciidoc/topics/ref_rest_protobuf.adoc
- documentation/src/main/asciidoc/topics/ref_rest_rolling.adoc
- documentation/src/main/asciidoc/topics/ref_rest_server_tasks.adoc
- documentation/src/main/asciidoc/topics/ref_rest_servers.adoc
- documentation/src/main/asciidoc/topics/ref_rest_xsite.adoc
- documentation/src/main/asciidoc/topics/rest_examples/get_v2_tasks_exec.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/BackupManagerResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/BaseCacheResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/main/java/org/infinispan/rest/resources/ProtobufResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
All REST calls are reviews and documentation updated.
Also some redundant HTTP codes were changed in REST API description
@oraNod could you please review docs changes or/and add someone for review (I don't have an reviewer rights in this repo)
> ISPN-12628 All REST response descriptions should contain possible HTTP response codes

- build-configuration/pom.xml
- core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableUserObject.java
- core/src/test/java/org/infinispan/marshall/ProtostreamUserMarshallerTest.java
- object-filter/src/main/java/org/infinispan/objectfilter/impl/predicateindex/ProtobufMatcherEvalContext.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMessageContext.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingTagHandler.java
- spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/session/MapSessionProtoAdapter.java
https://issues.redhat.com/browse/ISPN-12830
> ISPN-12830 Upgrade to protostream 4.4.0.Alpha7

- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/GenericJBossMarshaller.java
https://issues.redhat.com/browse/ISPN-12824
> ISPN-12824 JBoss Marshalling classloader fixes

- commons/all/src/main/java/org/infinispan/commons/tx/TransactionManagerImpl.java
- core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
- core/src/main/java/org/infinispan/interceptors/impl/TxInterceptor.java
- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateConsumerImpl.java
- core/src/test/java/org/infinispan/tx/StateTransferTransactionTest.java
https://issues.redhat.com/browse/ISPN-12798
> ISPN-12798 Do not enlist state transfer transaction

- core/src/main/java/org/infinispan/partitionhandling/impl/PartitionHandlingManagerImpl.java
- core/src/test/java/org/infinispan/lock/ExplicitUnlockTest.java
- core/src/test/java/org/infinispan/partitionhandling/PessimisticTxPartitionHandlingReleaseLockTest.java
https://issues.redhat.com/browse/ISPN-12757
> ISPN-12757 PartitionHandlingManagerImpl is unable to release locks

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
https://issues.redhat.com/browse/ISPN-12747
Depends on #9101
> ISPN-12747 Detail cache fix acl access

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12841
> ISPN-12841 Spring Boot 2.4.3 / Spring 5.3.4 / Spring Session 2.4.2

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12845
> ISPN-12845 Netty 4.1.60

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12842
> ISPN-12842 Elytron 1.15.1

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12848
> ISPN-12848 Upgrade jboss-marshalling to 2.0.11.Final

- pom.xml
https://issues.redhat.com/browse/ISPN-12849
https://issues.redhat.com/browse/ISPN-12851
> ISPN-12849 & ISPN-12851 Upgrade xstream & snakeyaml

- server/testdriver/core/pom.xml
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-12844
> ISPN-12844 Remove infinispan-core test-jar from server-testdrive

- pom.xml
https://issues.redhat.com/browse/ISPN-12852
> ISPN-12852 Remove duplicated opentracing dependencies

- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/Compactor.java
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/FileProvider.java
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/Index.java
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/IndexRequest.java
- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
- persistence/soft-index/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreTest.java
* Added in NonBlockingManager to not leak out Index thread
* Also removed some redundant code
https://issues.redhat.com/browse/ISPN-12850
> ISPN-12850 New SIFS isn't deleting old files from compactor

- query/src/main/java/org/infinispan/query/impl/massindex/DistributedExecutorMassIndexer.java
- server/rest/src/test/java/org/infinispan/rest/search/IndexedCacheNonIndexedEntityTest.java
https://issues.redhat.com/browse/ISPN-12861
> ISPN-12861 Indexer stuck in status 'running'

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12862
> ISPN-12862 Upgrade server to console 0.14.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12863
> ISPN-12863 Upgrade to protostream 4.4.0.Beta1

- spring/spring-boot/remote/pom.xml
https://issues.redhat.com/browse/ISPN-12864
> ISPN-12864 test driver should be test scope

- counter/src/test/resources/config/counters-9.4.xml
* Make sure 9.4 and master directories don't mix
https://issues.redhat.com/browse/ISPN-12877
> ISPN-12877 ConfigurationSerializerTest.testParser fails randomly

- server/runtime/src/test/java/org/infinispan/server/license/LicenseTest.java
* Patternfly puts the artifact in with the group and has empty artifact
https://issues.redhat.com/browse/ISPN-12878
> ISPN-12878 LicenseTest.testLicense fails regex No match found

- server/core/src/main/java/org/infinispan/server/core/utils/SslUtils.java
- server/router/src/main/java/org/infinispan/server/router/router/impl/hotrod/handlers/util/SslUtils.java
- server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
- server/tests/src/test/resources/configuration/security/tls.xml
https://issues.redhat.com/browse/ISPN-12882
> ISPN-12882 Correctly set the enabled ciphers on the SSL Engine passed to Netty

- commons/all/src/main/java/org/infinispan/commons/util/TypedProperties.java
- commons/all/src/test/java/org/infinispan/commons/util/TypedPropertiesTest.java
https://issues.redhat.com/browse/ISPN-12802
> ISPN-12802 TypedProperties::getXProperty should return the value if match the type

- core/src/main/java/org/infinispan/reactive/RxJavaInterop.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/PartitionAwareClusterPublisherManager.java
* Properly cancel upstream from partition change
* Ignore publisher error if already cancelled
https://issues.redhat.com/browse/ISPN-12886
> ISPN-12886 Fix Stream iteration Undelievered test failures

- commons/all/src/main/java/org/infinispan/commons/configuration/io/xml/XmlConfigurationReader.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/resources/configs/unified/11.0.xml
- core/src/test/resources/configs/unified/12.0.xml
- core/src/test/resources/configs/unified/12.1.xml
https://issues.redhat.com/browse/ISPN-12887
> ISPN-12887 Trim element text in XML parser

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12815
> ISPN-12815 RocksDB 6.15.5

- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/main/java/org/infinispan/configuration/cache/MemoryConfiguration.java
https://issues.redhat.com/browse/ISPN-12803
> ISPN-12803 Don't warn on evict() when eviction strategy is MANUAL

- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/main/java/org/infinispan/configuration/cache/MemoryConfiguration.java
https://issues.redhat.com/browse/ISPN-12803
> [11.0] ISPN-12803 Don't warn on evict() when eviction strategy is MANUAL

- core/src/main/java/org/infinispan/security/actions/GetClassInstanceAction.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/connectionfactory/ConnectionFactory.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/connectionfactory/SecurityActions.java
https://issues.redhat.com/browse/ISPN-12788
> [11.0] ISPN-12788 Use a PrivilegedAction to obtain the connection factory

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/MultiServerDistRemoteIteratorTest.java
https://issues.redhat.com/browse/ISPN-11680
https://issues.redhat.com/browse/ISPN-11682
https://issues.redhat.com/browse/ISPN-11683
> ISPN-11680 Remove Hot Rod deprecations

- core/src/test/java/org/infinispan/util/CoreTestBlockHoundIntegration.java
- lock/src/test/java/org/infinispan/lock/ClusteredLockTest.java
* Make sure to wait on unlocks to complete
https://issues.redhat.com/browse/ISPN-12889
> ISPN-12889 ClusteredLockTest.destroyLock random failures

- server/core/pom.xml
https://issues.redhat.com/browse/ISPN-12892
:crossed_fingers:
> ISPN-12892 Exclude MXParser dependency

- server/tests/src/test/java/org/infinispan/server/security/CertWithoutAuthenticationIT.java
https://issues.redhat.com/browse/ISPN-12891
> ISPN-12891 CertWithoutAuthenticationTest using the wrong configuration

- server/tests/pom.xml
https://issues.redhat.com/browse/ISPN-12894
> ISPN-12894 Show by default logs when running tests for the module server/tests

- cli/src/main/java/org/infinispan/cli/commands/CLI.java
https://issues.redhat.com/browse/ISPN-12888
> ISPN-12888 CLI batch failuires result in zero exit code

- server/core/src/main/java/org/infinispan/server/core/transport/NettyTransport.java
* An exception in start() prevents stop() to shutdown the event loop
threads
https://issues.redhat.com/browse/ISPN-12893
> ISPN-12893 Fix SiteDownFailoverTest.ThreadLeakChecker

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/HotRodURI.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
https://issues.redhat.com/browse/ISPN-12883
> ISPN-12883 ConfigurationBuilder::uri doesn't return what was configured

- core/src/main/resources/default-configs/default-jgroups-azure.xml
- core/src/main/resources/default-configs/default-jgroups-ec2.xml
- core/src/main/resources/default-configs/default-jgroups-google.xml
- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/main/resources/default-configs/default-jgroups-udp.xml
- core/src/test/resources/configs/config-with-jgroups-stack.xml
- core/src/test/resources/configs/unified/10.0.xml
- core/src/test/resources/configs/unified/10.1.xml
- core/src/test/resources/configs/unified/11.0.xml
- core/src/test/resources/configs/unified/12.0.xml
- core/src/test/resources/configs/unified/12.1.xml
- core/src/test/resources/configs/xsite/bridge.xml
- core/src/test/resources/configs/xsite/xsite-inline-test.xml
- core/src/test/resources/stacks/tcp.xml
- core/src/test/resources/stacks/tcp_mping/tcp1.xml
- core/src/test/resources/stacks/tcp_mping/tcp2.xml
- core/src/test/resources/stacks/udp.xml
- documentation/src/main/asciidoc/topics/config_examples/jgroups_inline_stack.xml
- documentation/src/main/asciidoc/topics/upgrading.adoc
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
- integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
- tools/src/test/resources/udp.xml
https://issues.redhat.com/browse/ISPN-12823
Increase xmit_interval and reduce max_xmit_request_size
> ISPN-12823 JGroups retransmission requests are too frequent and overlap

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/DataFormat.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfiguration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/MarshallerRegistry.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/MarshallerPerCacheTest.java
https://issues.redhat.com/browse/ISPN-12872
> ISPN-12872 Per remote cache marshaller should reuse instances

- core/src/main/java/org/infinispan/factories/PartitionHandlingManagerFactory.java
- core/src/main/java/org/infinispan/partitionhandling/impl/PartitionHandlingManagerImpl.java
- core/src/main/java/org/infinispan/scattered/impl/ScatteredPartitionHandlingManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.redhat.com/browse/ISPN-12756
> ISPN-12756 Improve PartitionHandlingManagerImpl logging

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/AbstractJdbcStoreConfiguration.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/AbstractJdbcStoreConfigurationBuilder.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/Attribute.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/JdbcStoreConfigurationParser.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
- persistence/jdbc/src/main/resources/schema/infinispan-cachestore-jdbc-config-12.1.xsd
https://issues.redhat.com/browse/ISPN-12825
> ISPN-12825 Add query timeouts to the JDBC store

- cli/src/main/java/org/infinispan/cli/benchmark/BenchmarkOutputFormat.java
- cli/src/main/java/org/infinispan/cli/benchmark/HttpBenchmark.java
- cli/src/main/java/org/infinispan/cli/commands/Benchmark.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
- server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
https://issues.redhat.com/browse/ISPN-12869
> ISPN-12869 Correctly handle HTTP failures in CLI benchmark

- server/tests/src/test/java/org/infinispan/server/functional/RestLoggingResource.java
https://issues.redhat.com/browse/ISPN-12904
> ISPN-12904 Fix RestLoggingResource.testListAppenders failure

- core/src/main/java/org/infinispan/container/entries/ReadCommittedEntry.java
- core/src/main/java/org/infinispan/container/entries/RepeatableReadEntry.java
- core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java
- core/src/test/java/org/infinispan/api/CacheAPITest.java
- query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
- query/src/main/java/org/infinispan/query/impl/LifecycleManager.java
- query/src/test/java/org/infinispan/query/blackbox/ClusteredCacheTest.java
- query/src/test/java/org/infinispan/query/blackbox/IndexingDuringStateTransferTest.java
https://issues.redhat.com/browse/ISPN-11299
> ISPN-11299 Stale values can be indexed during State Transfer

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
https://issues.redhat.com/browse/ISPN-12873
> ISPN-12873 Fix empty XML from the REST cache config endpoint

- documentation/src/main/asciidoc/stories/assembly_create_spring_boot_project.adoc
- documentation/src/main/asciidoc/stories/assembly_spring_application_properties.adoc
- documentation/src/main/asciidoc/stories/assembly_spring_boot_embedded.adoc
- documentation/src/main/asciidoc/stories/assembly_spring_boot_remote.adoc
- documentation/src/main/asciidoc/stories/assembly_using_spring_session.adoc
- documentation/src/main/asciidoc/topics/config_examples/application.properties
- documentation/src/main/asciidoc/topics/proc_adding_embeddedcm_bean.adoc
- documentation/src/main/asciidoc/topics/proc_adding_sb_dependencies.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_remotecm_bean.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_spring_cache.adoc
- documentation/src/main/asciidoc/topics/proc_enabling_spring_session.adoc
- documentation/src/main/asciidoc/topics/proc_enforcing_sb_versions.adoc
- documentation/src/main/asciidoc/topics/proc_exposing_statistics_actuator.adoc
- documentation/src/main/asciidoc/topics/proc_spring_boot_serialization.adoc
- documentation/src/main/asciidoc/topics/ref_embedded_custom_beans.adoc
- documentation/src/main/asciidoc/topics/ref_remote_custom_beans.adoc
https://issues.redhat.com/browse/ISPN-12899
> ISPN-12899 add protostream to spring starter docs

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12912
> ISPN-12912 Upgrade console to 0.14.1.Final

- integrationtests/security-it/src/test/java/org/infinispan/test/integration/security/utils/Deployments.java
- persistence/jdbc/pom.xml
- wildfly/feature-pack/src/main/resources/modules/org/infinispan/slot/module.xml
https://issues.redhat.com/browse/ISPN-12913
https://issues.redhat.com/browse/ISPN-12914
* Add protostream-types artifact to Wildfly module
* Add explicit dependency to protostream-types in persistence/jdbc so that it's in the classpath before protobuf-java
> ISPN-12913 and ISPN-12914 protostream-types classpath problems

- cli/src/main/java/org/infinispan/cli/benchmark/HttpBenchmark.java
https://issues.redhat.com/browse/ISPN-12915
> ISPN-12915 Thread leaks in CLI benchmarks tests

- core/src/main/java/org/infinispan/eviction/impl/ActivationManagerImpl.java
https://issues.redhat.com/browse/ISPN-12917
> ISPN-12917 A cache with off heap exposes cluster and local stats

- build-configuration/bom/pom.xml
- cloudevents-integration/src/main/java/org/infinispan/cloudevents/CloudEventsModule.java
- cloudevents-integration/src/main/java/org/infinispan/cloudevents/impl/EntryEventListener.java
- cloudevents-integration/src/main/java/org/infinispan/cloudevents/impl/KafkaEventSenderFactory.java
- cloudevents-integration/src/main/java/org/infinispan/cloudevents/impl/KafkaEventSenderImpl.java
- cloudevents-integration/src/main/java/org/infinispan/cloudevents/impl/Log.java
- cloudevents-integration/src/test/java/org/infinispan/cloudevents/CloudEventsConfigurationSerializerTest.java
- cloudevents-integration/src/test/resources/config/cloudevents-missing-bootstrap-servers.xml
- core/src/test/java/org/infinispan/commands/module/TestModuleLifecycle.java
- integrationtests/server-integration/pom.xml
- server/runtime/pom.xml
- server/tests/pom.xml
- server/tests/src/test/java/org/infinispan/server/functional/CloudEventsIntegrationIT.java
- server/tests/src/test/resources/configuration/CloudEventsIntegration.xml
- server/tests/src/test/resources/configuration/cache-container/clustered-cloudevents.xml
https://issues.redhat.com/browse/ISPN-12909
* Fix cloud events invalid configuration test
* Add cloudevents-integration dependency to server
* Add scope annotation to KafkaEventSenderFactory
* Do not send cloud events for internal caches
* Add integration test for cloud events
> ISPN-12909 CloudEvents integration not working in server

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12907
> ISPN-12907 Upgrade to JGroups 4.2.12.Final

- build-configuration/pom.xml
- persistence/jdbc/pom.xml
https://issues.redhat.com/browse/ISPN-12929
> ISPN-12929 Upgrade to protostream 4.4.0.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12939
> ISPN-12939 Upgrade Netty to 4.1.63.Final

- pom.xml
https://issues.redhat.com/browse/ISPN-12934
> ISPN-12934 Upgrade to Guava 30.1.1-jre

- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/HotRodTargetMigrator.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/SecurityActions.java
- server/tests/src/test/java/org/infinispan/server/functional/AbstractMultiClusterIT.java
- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeIT.java
- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeSecureIT.java
https://issues.redhat.com/browse/ISPN-12927
> ISPN-12927 Intermittent error ISPN000287 when triggering rolling upgrades

- server/runtime/build.xml
https://issues.redhat.com/browse/ISPN-12945
> ISPN-12945 Include copy of bsd-2-clause.txt license in server zip

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
- documentation/src/main/asciidoc/stories/assembly_xsite_jmx.adoc
- documentation/src/main/asciidoc/stories/assembly_xsite_replication.adoc
- documentation/src/main/asciidoc/topics/code_examples/XSiteEntryMergePolicy.java
- documentation/src/main/asciidoc/topics/con_xsite_concurrent_writes.adoc
- documentation/src/main/asciidoc/topics/config_examples/server_datasources.xml
- documentation/src/main/asciidoc/topics/config_examples/xsite_state_transfer.xml
- documentation/src/main/asciidoc/topics/counters.adoc
- documentation/src/main/asciidoc/topics/execute_grid.adoc
- documentation/src/main/asciidoc/topics/faq_content.adoc
- documentation/src/main/asciidoc/topics/hotrod_protocol.adoc
- documentation/src/main/asciidoc/topics/interceptors.adoc
- documentation/src/main/asciidoc/topics/proc_adding_deserialization_allowlist.adoc
- documentation/src/main/asciidoc/topics/proc_cli_xsite_push.adoc
- documentation/src/main/asciidoc/topics/proc_cli_xsite_state_transfer_mode.adoc
- documentation/src/main/asciidoc/topics/proc_using_custom_filters.adoc
- documentation/src/main/asciidoc/topics/proc_xsite_configuring_conflict_resolver.adoc
- documentation/src/main/asciidoc/topics/proc_xsite_configuring_state_transfer.adoc
- documentation/src/main/asciidoc/topics/proc_xsite_customizing_conflict_resolution.adoc
- documentation/src/main/asciidoc/topics/ref_hotrod_remote_cache.adoc
- documentation/src/main/asciidoc/topics/ref_logs_levels.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- documentation/src/main/asciidoc/topics/ref_rest_counters.adoc
- documentation/src/main/asciidoc/topics/ref_rest_server_security.adoc
- documentation/src/main/asciidoc/topics/ref_rest_xsite_cache_managers.adoc
- documentation/src/main/asciidoc/topics/ref_rolling_upgrades_k8s.adoc
- documentation/src/main/asciidoc/topics/ref_script_metadata.adoc
- documentation/src/main/asciidoc/topics/ref_user_roles_permissions.adoc
- documentation/src/main/asciidoc/topics/streams.adoc
- documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/ISPN-12925
> ISPN-12925 doc updates and edits

- persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
https://issues.redhat.com/browse/ISPN-12940
> ISPN-12940 SoftIndexFileStore availability check checks wrong file

- documentation/src/main/asciidoc/stories/assembly_developing.adoc
- documentation/src/main/asciidoc/stories/assembly_wildfly_modules.adoc
- documentation/src/main/asciidoc/titles/developing/stories.adoc
- documentation/src/main/asciidoc/topics/proc_adding_dependencies_wildfly_modules.adoc
https://issues.redhat.com/browse/ISPN-12947
> ISPN-12947 Docs: add aws modules

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/DB2TableManager.java
...in DB2TableManager
Currently the DB2 manager looks into all schemas to determine if caching
table exists when the schema is not specified.
https://issues.redhat.com/browse/ISPN-12930
https://issues.redhat.com/browse/JBEAP-21362
Upstream PR: https://github.com/infinispan/infinispan/pull/9227
Work in progress - I would like to have the idea reviewed by someone from Infinispan team. I will add a unit test if this looks OK.
> [11.0] ISPN-12930 Try to determine current schema during table existence check

- core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferManagerImpl.java
https://issues.redhat.com/browse/ISPN-12919
> [11.0.x] ISPN-12919 NullPointerException when retrying cross-site state transfer

- server/tests/src/test/java/org/infinispan/server/functional/CloudEventsIntegrationIT.java
- server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationImplicitIT.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationKerberosIT.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationLDAPIT.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationMultiEndpointIT.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationKerberosIT.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationLDAPIT.java
- server/tests/src/test/java/org/infinispan/server/test/core/LdapServerListener.java
https://issues.redhat.com/browse/ISPN-12948
* Stop the LDAP server after stopping the server
* Ignore LdapCtx thread
> ISPN-12948 AuthenticationLDAPIT and AuthenticationKerberosIT thread leaks

- documentation/src/main/asciidoc/stories/assembly_spring_boot_embedded.adoc
- documentation/src/main/asciidoc/stories/assembly_spring_boot_remote.adoc
- documentation/src/main/asciidoc/topics/config_examples/application.properties
- documentation/src/main/asciidoc/topics/proc_adding_embeddedcm_bean.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_remotecm_bean.adoc
- documentation/src/main/asciidoc/topics/proc_spring_boot_serialization.adoc
- documentation/src/main/asciidoc/topics/ref_spring_boot_properties.adoc
https://issues.redhat.com/browse/ISPN-12899
> ISPN-12899 sb starter feedback

- tools/src/main/java/org/infinispan/tools/store/migrator/marshaller/SerializationConfigUtil.java
- tools/src/test/java/org/infinispan/tools/store/migrator/MigratorConfigurationTest.java
https://issues.redhat.com/browse/ISPN-12960
> ISPN-12960 StoreMigrator tests failing with Infinispan 13.0.0-SNAPSHOT

- commons/all/pom.xml
- server/testdriver/junit5/pom.xml
- server/testdriver/junit5/src/test/resources/XSiteServerTest.xml
https://issues.redhat.com/browse/ISPN-12967
> ISPN-12967 Fix InfinispanXSiteServerTest

- documentation/src/main/asciidoc/topics/proc_adding_server_tasks.adoc
- documentation/src/main/asciidoc/topics/rest_examples/get_v2_tasks_exec.adoc
@oraNod could you please review when possible
> ISPN-12969 Сhange the sequence of actions when packaging a server task

- documentation/src/main/asciidoc/topics/proc_adding_server_tasks.adoc
- documentation/src/main/asciidoc/topics/rest_examples/get_v2_tasks_exec.adoc
> [12.1.x] ISPN-12969 Change the sequence of actions when packaging a server task

- core/src/main/java/org/infinispan/interceptors/impl/NonTxIracRemoteSiteInterceptor.java
- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/main/java/org/infinispan/xsite/irac/IracManager.java
- core/src/main/java/org/infinispan/xsite/irac/NoOpIracManager.java
- core/src/test/java/org/infinispan/xsite/irac/ControlledIracManager.java
- core/src/test/java/org/infinispan/xsite/irac/IracXsiteStatsTest.java
https://issues.redhat.com/browse/ISPN-12478
Change are pushed for ISPN-12478 
Changes are in the following files:
~~~
NonTxIracRemoteSiteInterceptor.java
DefaultIracManager.java
IracManager.java 
NoOpIracManager.java
ControlledIracManager.java 
IracXsiteStatsTest.java 
~~~
> ISPN-12478:IRAC metrics

- core/src/main/java/org/infinispan/globalstate/impl/CacheState.java
- core/src/main/java/org/infinispan/partitionhandling/impl/PreferConsistencyStrategy.java
- core/src/main/java/org/infinispan/statetransfer/StateTransferLockImpl.java
- core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java
- core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
- core/src/main/java/org/infinispan/util/concurrent/ConditionFuture.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/distribution/ZeroCapacityNodeTest.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/SecurityActions.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/SecurityActions.java
- server/core/src/main/java/org/infinispan/server/core/transport/SecurityActions.java
- server/runtime/src/main/java/org/infinispan/server/tasks/SecurityActions.java
https://issues.redhat.com/browse/ISPN-12962
https://issues.redhat.com/browse/ISPN-4996
https://issues.redhat.com/browse/ISPN-12953
> Zero capacity backports

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12988
> ISPN-12988 Upgrade to JGroups 4.2.14.Final

- server/tests/src/test/java/org/infinispan/server/functional/CloudEventsIntegrationIT.java
https://issues.redhat.com/browse/ISPN-12946
Use Kafka image from quay.io
> ISPN-12946 CloudEventsIntegrationIT fails because of rate limit

- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
https://issues.redhat.com/browse/ISPN-12955
> ISPN-12955 Clearer Hot Rod error when user is not authenticated

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/DB2TableManager.java
...in DB2TableManager
We need to port this to 12.1.x branch, since this was merged in 11.0.x and is going to be included in EAP 7.4.1
Upstream PR: https://github.com/infinispan/infinispan/pull/9227
11.0.x PR: https://github.com/infinispan/infinispan/pull/9224
> ISPN-12930 Try to determine current schema during table existence check

- server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
https://issues.redhat.com/browse/ISPN-12955
> [12.1] ISPN-12955 Clearer Hot Rod error when user is not authenticated

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedServer.java
Resolves
https://issues.redhat.com/browse/ISPN-12385
https://issues.redhat.com/browse/ISPN-12442
> ISPN-12385 ServerRunMode.FORKED mode test driver doesn't work with a secured server + ISPN-12442 Windows support + process handling fixes

- anchored-keys/src/test/java/org/infinispan/anchored/AnchoredConfigurationSerializerTest.java
- anchored-keys/src/test/java/org/infinispan/anchored/AnchoredKeysOperationsTest.java
- anchored-keys/src/test/java/org/infinispan/anchored/AnchoredKeysScalingTest.java
- core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java
- core/src/test/java/org/infinispan/test/FeaturesListener.java
- core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- core/src/test/java/org/infinispan/util/FeaturesListenerTest.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractServerConfigBuilder.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanServerTestConfiguration.java
- server/tests/src/test/java/org/infinispan/server/functional/AbstractMultiClusterIT.java
- server/tests/src/test/java/org/infinispan/server/functional/AnchoredKeysIT.java
https://issues.redhat.com/browse/ISPN-9926
> ISPN-9926 Don't run tests for disabled features

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/OracleTableManager.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/impl/table/OracleTableManagerTest.java
https://issues.redhat.com/browse/ISPN-12323
> ISPN-12323 JDBC store: use different index prefix on Oracle before 12.1

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13003
> ISPN-13003 Console 0.14.2.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13006
> ISPN-13006 Bump RocksDB 6.19.3

- documentation/src/main/asciidoc/topics/con_expiration_overview.adoc
https://issues.redhat.com/browse/ISPN-13010
missmatch of >  <
> ISPN-13010 fix wrong calculation of expiration check

- core/src/main/java/org/infinispan/remoting/transport/SiteAddress.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/SingleSiteRequest.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
https://issues.redhat.com/browse/ISPN-12938
> ISPN-12938 Improve some error messages for cross-site replication

- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
- documentation/src/main/asciidoc/topics/upgrading.adoc
- query/src/main/java/org/infinispan/query/impl/massindex/DistributedExecutorMassIndexer.java
- query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
- query/src/main/java/org/infinispan/search/mapper/mapping/SearchMapping.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java
- server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java
- server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
- server/rest/src/test/resources/person-changed.proto
https://issues.redhat.com/browse/ISPN-12986
> ISPN-12986 Protobuf schema changes not being considered after reindexing

- pom.xml
https://issues.redhat.com/browse/ISPN-13039
> ISPN-13039 Upgrade commons-io to 2.8.0

- core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java
- core/src/test/java/org/infinispan/stats/ClusteredStatsTest.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/AbstractContainerResource.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/CounterResource.java
- server/core/src/test/java/org/infinispan/server/core/backup/BackupManagerImplTest.java
https://issues.redhat.com/browse/ISPN-13022
https://issues.redhat.com/browse/ISPN-13025
https://issues.redhat.com/browse/ISPN-13026
https://issues.redhat.com/browse/ISPN-13031
> [12.1.x] Backup/Restore issues

- core/src/main/java/org/infinispan/persistence/file/SecurityActions.java
- core/src/main/java/org/infinispan/persistence/file/SingleFileStore.java
https://issues.redhat.com/browse/ISPN-11121
https://issues.redhat.com/browse/JDG-4550
> [9.4.x] JDG-4550 ISPN-11121 Single file store fails to start with security manager

- documentation/src/main/asciidoc/topics/code_examples/JBossUserMarshaller.java
- documentation/src/main/asciidoc/topics/config_examples/jboss_user_marshaller.xml
- documentation/src/main/asciidoc/topics/proc_adding_deserialization_whitelist.adoc
- documentation/src/main/asciidoc/topics/proc_using_custom_marshallers.adoc
- documentation/src/main/asciidoc/topics/proc_using_java_serialization.adoc
- documentation/src/main/asciidoc/topics/proc_using_jboss_marshaller.adoc
- documentation/src/main/asciidoc/topics/proc_using_kyro_marshaller.adoc
- documentation/src/main/asciidoc/topics/proc_using_protostuff_marshaller.adoc
https://issues.redhat.com/browse/ISPN-13028
> [11.0.x] ISPN-13028 docs mention allowlist

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13047
> ISPN-13047 Agroal 1.11

- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/HotRodTargetMigrator.java
https://issues.redhat.com/browse/ISPN-13049
> ISPN-13049 RollingUpgrade should not timeout

- documentation/src/main/asciidoc/topics/con_cache_encoding.adoc
- documentation/src/main/asciidoc/topics/con_protobuf_encoding.adoc
- documentation/src/main/asciidoc/topics/con_text_encoding.adoc
https://issues.redhat.com/browse/ISPN-13050
> ISPN-13050 Gustavo's encoding doc review

- documentation/src/main/asciidoc/stories/assembly_encrypting_cluster_traffic.adoc
- documentation/src/main/asciidoc/stories/assembly_setting_up_clusters.adoc
Relates to https://issues.redhat.com/browse/ISPN-13033
> ISPN-13033 fix broken doc ref

- documentation/src/main/asciidoc/stories/assembly_encrypting_cluster_traffic.adoc
- documentation/src/main/asciidoc/stories/assembly_setting_up_clusters.adoc
Relates to https://issues.redhat.com/browse/ISPN-13033
> [12.1.x] ISPN-13033 fix broken doc ref

- pom.xml
https://issues.redhat.com/browse/ISPN-13039
backport of https://github.com/infinispan/infinispan/pull/9315
> [12.1] ISPN-13039 Upgrade commons-io to 2.8.0

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/HotRodQueryIspnDirectoryTest.java
- remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/impl/QueryRequest.java
https://issues.redhat.com/browse/ISPN-13036
> [12.1.x] ISPN-13036  UnsupportedOperationException when querying Cache with json data type

- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/HotRodTargetMigrator.java
https://issues.redhat.com/browse/ISPN-13049
> [12.1.x] ISPN-13049 RollingUpgrade should not timeout

- pom.xml
https://issues.redhat.com/browse/ISPN-13073
> [12.1] ISPN-13073 Bump xstream from 1.4.16 to 1.4.17

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13064
> ISPN-13064 WildFly OpenSSL 2.1.4

- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/tests/src/test/java/org/infinispan/server/security/authentication/RestAuthentication.java
https://issues.redhat.com/browse/ISPN-13072
> ISPN-13072 Treat all HTTP authentication failures as such

- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/tests/src/test/java/org/infinispan/server/security/authentication/RestAuthentication.java
https://issues.redhat.com/browse/ISPN-13072
> [12.1] ISPN-13072 Treat all HTTP authentication failures as such

- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
- server/tests/src/test/java/org/infinispan/server/security/authentication/RestAuthentication.java
https://issues.redhat.com/browse/ISPN-13072
> [11.0] ISPN-13072 Treat all HTTP authentication failures as such

- build-configuration/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13064
> [12.1] ISPN-13064 WildFly OpenSSL 2.1.4

- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
https://issues.redhat.com/browse/ISPN-13079
> ISPN-13079 Lock contention in DefaultCacheManager.getCache()

- core/src/main/java/org/infinispan/encoding/DataConversion.java
- query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
- query/src/test/java/org/infinispan/query/distributed/ClusteredQueryMassIndexingTest.java
- query/src/test/java/org/infinispan/query/distributed/DistProgrammaticMassIndexTest.java
- query/src/test/java/org/infinispan/query/distributed/DistributedMassIndexingTest.java
- query/src/test/java/org/infinispan/query/distributed/UnsharedDistMassIndexTest.java
- query/src/test/resources/mass-index-with-store.xml
https://issues.redhat.com/browse/ISPN-12976
> ISPN-12976 Reindexing OFF_HEAP cache leads to ClassCastException when querying

- core/src/main/java/org/infinispan/encoding/DataConversion.java
- query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
- query/src/test/java/org/infinispan/query/distributed/ClusteredQueryMassIndexingTest.java
- query/src/test/java/org/infinispan/query/distributed/DistProgrammaticMassIndexTest.java
- query/src/test/java/org/infinispan/query/distributed/DistributedMassIndexingTest.java
- query/src/test/java/org/infinispan/query/distributed/UnsharedDistMassIndexTest.java
- query/src/test/resources/mass-index-with-store.xml
https://issues.redhat.com/browse/ISPN-12976
> [12.1] ISPN-12976  Reindexing OFF_HEAP cache leads to ClassCastException when querying

- cli/src/main/java/org/infinispan/cli/commands/CliCommand.java
- cli/src/main/java/org/infinispan/cli/commands/Run.java
- cli/src/main/java/org/infinispan/cli/logging/Messages.java
- server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
- server/tests/src/test/resources/cli/batch-error.cli
https://issues.redhat.com/browse/ISPN-12752
> ISPN-12752 Handle CLI batch errors to be more informative

- cli/src/main/java/org/infinispan/cli/commands/CliCommand.java
- cli/src/main/java/org/infinispan/cli/commands/Run.java
- cli/src/main/java/org/infinispan/cli/logging/Messages.java
- server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
- server/tests/src/test/resources/cli/batch-error.cli
https://issues.redhat.com/browse/ISPN-12752
> [12.1] ISPN-12752 Handle CLI batch errors to be more informative

- documentation/src/main/asciidoc/topics/config_examples/rolling_upgrade_remote_store.xml
- persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/wrapper/HotRodEntryMarshaller.java
- persistence/remote/src/main/resources/schema/infinispan-cachestore-remote-config-13.0.xsd
https://issues.redhat.com/browse/ISPN-13084
> ISPN-13084 Make hotrod-wrapping config redundant in the Remote Store

- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
https://issues.redhat.com/browse/ISPN-13079
> [12.1] ISPN-13079 Lock contention in DefaultCacheManager.getCache()

- documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
- documentation/src/main/asciidoc/topics/contributing/basics.adoc
- documentation/src/main/asciidoc/topics/contributing/docs.adoc
- documentation/src/main/asciidoc/topics/contributing/source_control.adoc
- documentation/src/main/asciidoc/topics/extending.adoc
- documentation/src/main/asciidoc/topics/faq_content.adoc
- documentation/src/main/asciidoc/topics/hotrod_protocol.adoc
- documentation/src/main/asciidoc/topics/integrations_hibernate_cache.adoc
- documentation/src/main/asciidoc/topics/proc_memcached_multi_clustered_server_tutorial.adoc
- documentation/src/main/asciidoc/topics/ref_cache_store_jpa.adoc
- documentation/src/main/asciidoc/topics/ref_cache_store_rocksdb.adoc
- documentation/src/main/asciidoc/topics/ref_logging_framework.adoc
updating links and attributes in documentation for the branch renaming from master to main
> branch renaming to main

- server/testdriver/core/src/main/resources/testcontainers.properties
https://issues.redhat.com/browse/ISPN-13098
> ISPN-13098 Upgrade testsuite containers to ubi-minimal:8.4

- server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
- server/tests/src/test/resources/configuration/security/tls.xml
https://issues.redhat.com/browse/ISPN-12951
> [12.1] ISPN-12951 Test TLSv1.3

- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- core/src/main/java/org/infinispan/remoting/transport/AbstractDelegatingTransport.java
- core/src/main/java/org/infinispan/remoting/transport/Transport.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/test/java/org/infinispan/remoting/transport/MockTransport.java
- documentation/src/main/asciidoc/topics/json_examples/rest_cache_manager_response.json
- documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
- server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
* Fetch the sites name from RELAY2 protocol directly. Only the site
masters will have access and log the xsite view
* Added site_coordinator boolean to REST & Transport
* Added site masters address list to REST & Transport
https://issues.redhat.com/browse/ISPN-12871
> ISPN-12871 Improve Cross-Site view logging

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/MixedExpiryTest.java
- client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/BinaryTranscoder.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/DefaultTranscoder.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/StandardConversions.java
- commons/all/src/test/java/org/infinispan/commons/dataconversion/StandardConversionsTest.java
- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointInteroperabilityTest.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/dataconversion/JBossMarshallingTranscoder.java
- server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/BaseCacheResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-13082
> ISPN-13082 Improper marshalling in caches without encoding

- wildfly/feature-pack/pom.xml
store
* Removed lines from pom referencing no longer existant module
https://issues.redhat.com/browse/ISPN-12990
> ISPN-12990 Change SoftIndexFileStore to be the Infinispan default file

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryRepeatedMappingTest.java
- client/hotrod-client/src/test/resources/indexed-repeated.proto
- query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
- query/src/main/java/org/infinispan/query/logging/Log.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/MessageReferenceProvider.java
https://issues.redhat.com/browse/ISPN-13101
> ISPN-13101 NPE when mapping nested entity that is not @Indexed but has @Field

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryRepeatedMappingTest.java
- client/hotrod-client/src/test/resources/indexed-repeated.proto
- query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
- query/src/main/java/org/infinispan/query/logging/Log.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/MessageReferenceProvider.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-12994
https://issues.redhat.com/browse/ISPN-13101
> [12.1] ISPN-13101 NPE when mapping nested entity that is not @Indexed &&  ISPN-12994 Cache and indexes can become out of sync 

- query/src/main/java/org/infinispan/query/impl/massindex/DistributedExecutorMassIndexer.java
- query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
- query/src/main/java/org/infinispan/search/mapper/mapping/SearchMapping.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java
- server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
- server/rest/src/test/resources/person-changed.proto
https://issues.redhat.com/browse/ISPN-12986
> [12.1] ISPN-12986 Protobuf schema changes not being considered after reindexing

- integrationtests/security-it/pom.xml
- integrationtests/server-integration/third-party-server/pom.xml
- integrationtests/server-integration/wildfly-modules/pom.xml
https://issues.redhat.com/browse/ISPN-13119
> ISPN-13119 Skip Wildfly startup during build time

- commons/all/src/main/java/org/infinispan/commons/tx/TransactionManagerImpl.java
- core/src/main/java/org/infinispan/interceptors/impl/TxInterceptor.java
- core/src/main/java/org/infinispan/transaction/impl/AbstractCacheTransaction.java
- core/src/main/java/org/infinispan/transaction/impl/LocalTransaction.java
- core/src/main/java/org/infinispan/transaction/impl/RemoteTransaction.java
- core/src/main/java/org/infinispan/transaction/impl/TransactionTable.java
- core/src/main/java/org/infinispan/util/concurrent/locks/LockReleasedException.java
- core/src/main/java/org/infinispan/util/concurrent/locks/impl/DefaultLockManager.java
- core/src/main/java/org/infinispan/util/concurrent/locks/impl/InfinispanLock.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/tx/locking/LocalPessimisticTxTest.java
- core/src/test/java/org/infinispan/tx/locking/RollbackDuringLockAcquisitionTest.java
Fix concurrency issue between the TM's reaper and lock acquisition which
can lead to unreleased lock
https://issues.redhat.com/browse/ISPN-13024
> ISPN-13024 Implicit Cache Lock Release Failure

- cli/src/main/java/org/infinispan/cli/commands/rest/DataSource.java
- cli/src/main/java/org/infinispan/cli/commands/rest/Server.java
- cli/src/main/java/org/infinispan/cli/completers/DataSourceCompleter.java
- cli/src/main/java/org/infinispan/cli/connection/Connection.java
- cli/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
- cli/src/main/resources/help/server.adoc
- client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestServerClientOkHttp.java
- documentation/src/main/asciidoc/stories/assembly_server_datasources.adoc
- documentation/src/main/asciidoc/topics/proc_server_testing_datasources.adoc
- server/core/src/main/java/org/infinispan/server/core/ServerManagement.java
- server/rest/src/main/java/org/infinispan/rest/logging/Messages.java
- server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/tests/src/test/java/org/infinispan/server/persistence/ManagedConnectionOperations.java
https://issues.redhat.com/browse/ISPN-13020
> ISPN-13020 Datasource  CLI test

- server/runtime/src/main/java/org/infinispan/server/datasource/DataSourceFactory.java
https://issues.redhat.com/browse/ISPN-13067
> ISPN-13067 DataSource exception sorter

- server/runtime/src/main/java/org/infinispan/server/datasource/DataSourceFactory.java
https://issues.redhat.com/browse/ISPN-13067
> [12.1] ISPN-13067 DataSource exception sorter

- cli/src/main/java/org/infinispan/cli/commands/rest/DataSource.java
- cli/src/main/java/org/infinispan/cli/commands/rest/Server.java
- cli/src/main/java/org/infinispan/cli/completers/DataSourceCompleter.java
- cli/src/main/java/org/infinispan/cli/connection/Connection.java
- cli/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
- cli/src/main/resources/help/server.adoc
- client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestServerClientOkHttp.java
- documentation/src/main/asciidoc/stories/assembly_server_datasources.adoc
- documentation/src/main/asciidoc/topics/proc_server_testing_datasources.adoc
- server/core/src/main/java/org/infinispan/server/core/ServerManagement.java
- server/rest/src/main/java/org/infinispan/rest/logging/Messages.java
- server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/tests/src/test/java/org/infinispan/server/persistence/ManagedConnectionOperations.java
https://issues.redhat.com/browse/ISPN-13020
> [12.1] ISPN-13020 Datasource  CLI test

- build-configuration/pom.xml
- core/src/main/java/org/infinispan/interceptors/impl/CacheMgmtInterceptor.java
- core/src/main/java/org/infinispan/metrics/impl/TimerTrackerImpl.java
https://issues.redhat.com/browse/ISPN-13120
> ISPN-13120 CacheMetricsRegistration compatibility with Wildfly 23

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13125
> ISPN-13125 Upgrade Console to 0.15.0.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13125
> ISPN-13125 Upgrade Console to 0.14.3.Final

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestClient.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingManagerImpl.java
https://issues.redhat.com/browse/ISPN-12998
> ISPN-12998 pass subject from task context

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestClient.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
- tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingManagerImpl.java
https://issues.redhat.com/browse/ISPN-12998
> [12.1.x] ISPN-12998 pass subject from task context

- core/src/main/java/org/infinispan/globalstate/GlobalStateManager.java
- core/src/main/java/org/infinispan/globalstate/impl/GlobalStateManagerImpl.java
- core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
- core/src/test/java/org/infinispan/globalstate/AbstractGlobalStateRestartTest.java
- core/src/test/java/org/infinispan/globalstate/ThreeNodeDistGlobalStateRestartTest.java
- core/src/test/java/org/infinispan/globalstate/ThreeNodeReplGlobalStateRestartTest.java
- core/src/test/java/org/infinispan/globalstate/ThreeNodeScatteredGlobalStateRestartTest.java
https://issues.redhat.com/browse/ISPN-13121
Backport of #9399
> [12.1.x] ISPN-13121 Cache persistent state is not deleted after restart

- documentation/src/main/asciidoc/topics/ref_server_realm_ldap.adoc
- server/runtime/src/main/resources/schema/infinispan-server-13.0.xsd
Forward port of doc changes extracted from @oraNod 's commits on https://github.com/infinispan/infinispan/pull/9378
https://issues.redhat.com/browse/ISPN-13014
> ISPN-13014 Doc fixes

- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestResponseOkHttp.java
- server/rest/src/main/java/org/infinispan/rest/ServerRestBlockHoundIntegration.java
- server/rest/src/test/java/org/infinispan/rest/assertion/ResponseAssertion.java
- server/rest/src/test/java/org/infinispan/rest/helper/RestServerHelper.java
- server/runtime/src/main/java/org/infinispan/server/state/ServerStateManagerImpl.java
https://issues.redhat.com/browse/ISPN-13131
https://issues.redhat.com/browse/ISPN-13132
> ISPN-13131 REST keys operation blocks in a non-blocking thread

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13150
> ISPN-13150 WildFly Galleon Maven plugin 5.2.1

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13153
> ISPN-13153 Upgrade to Hibernate Search 6.0.5.Final

- server/core/src/main/java/org/infinispan/server/core/ServerCoreBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-13148
> ISPN-13148 XMLTranscoder can block during reflection

- server/core/src/main/java/org/infinispan/server/core/dataconversion/XMLTranscoder.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/xml/XStreamEngine.java
https://issues.redhat.com/browse/ISPN-13156
> ISPN-13156 Multiple instances of XMLTranscoder reuse the same internal object

- commons/all/src/main/java/org/infinispan/commons/dataconversion/AbstractTranscoder.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/Base16Codec.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/BinaryTranscoder.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/DefaultTranscoder.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/JavaMediaTypeCodec.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/JavaStringCodec.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/MediaType.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/MediaTypeCodec.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/OneToManyTranscoder.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/RFC4648Codec.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/StandardConversions.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/TranscoderMarshallerAdapter.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/UrlFormCodec.java
- commons/all/src/main/java/org/infinispan/commons/logging/Log.java
- commons/all/src/test/java/org/infinispan/commons/dataconversion/BinaryTranscoderTest.java
- commons/all/src/test/java/org/infinispan/commons/dataconversion/DefaultTranscoderTest.java
- core/src/main/java/org/infinispan/encoding/ProtostreamTranscoder.java
- core/src/main/java/org/infinispan/encoding/impl/TwoStepTranscoder.java
- core/src/test/java/org/infinispan/dataconversion/ProtostreamTranscoderTest.java
- core/src/test/java/org/infinispan/test/data/Address.java
- core/src/test/java/org/infinispan/test/data/Person.java
- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointInteroperabilityTest.java
- jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/dataconversion/JBossMarshallingTranscoder.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/XMLTranscoder.java
- server/rest/src/main/java/org/infinispan/rest/NettyRestRequest.java
- server/rest/src/main/java/org/infinispan/rest/resources/BaseCacheResource.java
- server/rest/src/test/java/org/infinispan/rest/TestClass.java
- server/rest/src/test/java/org/infinispan/rest/resources/BaseCacheResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java
https://issues.redhat.com/browse/ISPN-13078
https://issues.redhat.com/browse/ISPN-13129
> ISPN-13078 ISPN-13129 MediaType encoding param && REST binary only keys

- commons/all/src/main/java/org/infinispan/commons/marshall/WrappedByteArray.java
https://issues.redhat.com/browse/ISPN-13143
> ISPN-13143 WrappedByteArray compute the hash code during toString

- core/src/test/java/org/infinispan/distribution/rehash/ConcurrentJoinTest.java
- core/src/test/java/org/infinispan/remoting/transport/InitialClusterSizeTest.java
- core/src/test/java/org/infinispan/statetransfer/ConcurrentStartChanelLookupTest.java
- core/src/test/java/org/infinispan/statetransfer/ConcurrentStartForkChannelTest.java
- core/src/test/java/org/infinispan/statetransfer/ConcurrentStartTest.java
- core/src/test/java/org/infinispan/statetransfer/ForkChannelRestartTest.java
- core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
- core/src/test/java/org/infinispan/test/fwk/TransportFlags.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- core/src/test/java/org/infinispan/xsite/statetransfer/ControlledXSiteStateTransferManager.java
https://issues.redhat.com/browse/ISPN-13192
Use separate mcast addresses and ports for each site.
> ISPN-13192 Warning messages in xsite test logs

- build-configuration/pom.xml
- cdi/common/pom.xml
- cdi/embedded/pom.xml
- cdi/remote/pom.xml
- client/hotrod-client/pom.xml
- client/marshaller/kryo/kryo-marshaller-compatibility-bundle/pom.xml
- client/marshaller/protostuff/protostuff-marshaller-compatibility-bundle/pom.xml
- commons/all/pom.xml
- core/pom.xml
- distribution/pom.xml
- integrationtests/cdi-jcache-it/pom.xml
- integrationtests/cdi-weld-se-it/pom.xml
- integrationtests/server-integration/server-integration-commons/pom.xml
- integrationtests/server-integration/wildfly-modules/pom.xml
- javadoc/pom.xml
- jcache/commons/pom.xml
- jcache/embedded/pom.xml
- persistence/jpa/pom.xml
- plugins/infinispan-defaults-maven-plugin/pom.xml
- pom.xml
- wildfly/feature-pack/pom.xml
https://issues.redhat.com/browse/ISPN-13180
> ISPN-13180 Transition to using JakartaEE APIs

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13211
> ISPN-13211 Upgrade Hibernate Core to 5.3.21.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13213
> ISPN-13213 Upgrade Jackson to 2.12.4

- core/src/main/java/org/infinispan/distribution/ch/ConsistentHash.java
- core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHash.java
- core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHash.java
- core/src/main/java/org/infinispan/distribution/ch/impl/ScatteredConsistentHash.java
- core/src/main/java/org/infinispan/scattered/impl/BiasManagerImpl.java
- core/src/main/java/org/infinispan/scattered/impl/ScatteredStateProviderImpl.java
- core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
https://issues.redhat.com/browse/ISPN-13105
Return an empty segment set if the address is not a member.
> ISPN-13105 ConsistentHash.getPrimarySegmentsForOwner() throws an IAE

- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
https://issues.redhat.com/browse/ISPN-13165
> ISPN-13165 AsyncOfflineTest.testReset random failures

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13217
> ISPN-13217 Upgrade WildFly Elytron to 1.15.5.Final

- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/commands/batch/KeyPublisherResponse.java
https://issues.redhat.com/browse/ISPN-13134
* Retry if no remaining segment has an owner
(possible in a scattered cache)
* Batch size per target (targetBatchSize) should be never be greater
than the requested batch size
> ISPN-13134 ArithmeticException: / by zero in ClusterPublisherManagerImpl

- core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- tasks/scripting/src/test/java/org/infinispan/scripting/ScriptingDataStoresTest.java
https://issues.redhat.com/browse/ISPN-13169
* Increase the timeout
* Pre-start the cache
* Log the start of cache startup at debug level
> ISPN-13169 ScriptingDataStoresTest random failures

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13224
> ISPN-13224 Release Console 0.15.1.Final

- core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
- core/src/test/java/org/infinispan/topology/ClusterTopologyManagerImplTest.java
https://issues.redhat.com/browse/ISPN-13231
> ISPN-13231 Join command with older view id causes NullPointerException

- build-configuration/bom/pom.xml
- commons/all/pom.xml
- documentation/collect-logs.xml
- documentation/logging-report.xsl
- documentation/logs.html
- documentation/pom.xml
- logging/logging-annotations/pom.xml
- logging/logging-annotations/src/main/java/org/infinispan/logging/annotations/Description.java
- logging/logging-processor/pom.xml
- logging/logging-processor/src/main/java/org/infinispan/logging/processor/InfinispanLoggingProcessor.java
- logging/logging-processor/src/main/java/org/infinispan/logging/processor/report/IndentingXmlWriter.java
- logging/logging-processor/src/main/java/org/infinispan/logging/processor/report/XmlReportWriter.java
- pom.xml
https://issues.redhat.com/browse/ISPN-13059
> ISPN-13059: Add description annotations to logging utility

- build-configuration/bom/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13244
> ISPN-13244 Remove infinispan-logging-* modules from bom

- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/logging/Log.java
https://issues.redhat.com/browse/ISPN-13202
> ISPN-13202 Log SCI registration as debug

- server/runtime/src/main/java/org/infinispan/server/Extensions.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
https://issues.redhat.com/browse/ISPN-13246
> ISPN-13246 Log a warning of no script engines available

- commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReader.java
- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
- server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationParserTest.java
- server/runtime/src/test/java/org/infinispan/server/configuration/ServerOverlayConfigurationTest.java
- server/runtime/src/test/resources/configuration/Base.xml
- server/runtime/src/test/resources/configuration/Overlay.yml
https://issues.redhat.com/browse/ISPN-12931
> ISPN-12931 Server configuration overlay

- pom.xml
Resolves
https://issues.redhat.com/browse/ISPN-13256
> ISPN-13256 Upgrade JGroups kubernetes to 1.0.16.Final

- server/runtime/pom.xml
https://issues.redhat.com/browse/ISPN-13257
> ISPN-13257 Fix running server/runtime tests on JDK 8

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
The fix is already done, this just changes the debug message to a warning as suggested in https://github.com/infinispan/infinispan/pull/9474#discussion_r684257049
> ISPN-12598 Log warning when switching to initial server list

- integrationtests/security-it/pom.xml
- integrationtests/server-integration/third-party-server/pom.xml
https://issues.redhat.com/browse/ISPN-13263
> ISPN-13263 Galleon maven plugin should provision a fat installation

- cli/src/main/java/org/infinispan/cli/commands/rest/Migrate.java
- cli/src/main/resources/help/migrate.adoc
- client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
- core/src/main/java/org/infinispan/configuration/parsing/Attribute.java
- core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
- core/src/main/java/org/infinispan/upgrade/RollingUpgradeManager.java
- core/src/main/java/org/infinispan/upgrade/TargetMigrator.java
- documentation/src/main/asciidoc/topics/proc_upgrading_sync_data.adoc
- documentation/src/main/asciidoc/topics/ref_rest_rolling.adoc
- documentation/src/main/asciidoc/topics/upgrading.adoc
- persistence/remote/src/main/java/org/infinispan/persistence/remote/ExternalizerIds.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/LifecycleCallbacks.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/AddSourceRemoteStoreTask.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/CheckRemoteStoreTask.java
- persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/HotRodTargetMigrator.java
- persistence/remote/src/test/java/org/infinispan/persistence/remote/configuration/JsonRemoteStoreOnlyParsingTest.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeDynamicStoreCliIT.java
- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeDynamicStoreIT.java
https://issues.redhat.com/browse/ISPN-13258
> ISPN-13258 Add extra methods to inspect Rolling Upgrade configurations

- core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
https://issues.redhat.com/browse/ISPN-13259
> ISPN-13259 Avoid storing an index in InterceptorChainFactory

- remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/impl/QueryRequest.java
https://issues.redhat.com/browse/ISPN-13275
> ISPN-13275 Queries throw NPE with old client

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-13282
> ISPN-13282 Use ubi8/openjdk-11-runtime image as base for tests

- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- documentation/src/main/asciidoc/topics/json_examples/rest_cache_manager_response.json
- documentation/src/main/asciidoc/topics/json_examples/rest_caches_info_response.json
- documentation/src/main/asciidoc/topics/json_examples/rest_full_cache_detail.json
- documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
- server/rest/src/test/java/org/infinispan/rest/resources/ContainerResourceTest.java
https://issues.redhat.com/browse/ISPN-11729
> ISPN-11729 Expose rebalancing enabled values in the REST API

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13291
depends on https://github.com/infinispan/infinispan/pull/9519
> ISPN-13291 Upgrade to console 0.15.2.Final

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
https://issues.redhat.com/browse/ISPN-12974
> ISPN-12974 Add RemoteCacheImpl toString() implementation

- counter/src/main/resources/schema/infinispan-counters-config-13.0.xsd
https://issues.redhat.com/browse/ISPN-12937 Left over schema doc changes.
> ISPN-12937 counter schema docs

- persistence/sql/src/test/TESTME.md
- persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
- persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcStoreFunctionalTest.java
- persistence/sql/src/test/java/org/infinispan/persistence/sql/TableJdbcStoreFunctionalTest.java
- persistence/sql/src/test/java/util/JdbcConnection.java
https://issues.redhat.com/browse/ISPN-13274
> ISPN-13274 - Add environment variables to use into SQL store tests

- spring/spring-boot/embedded/src/main/java/org/infinispan/spring/starter/embedded/actuator/InfinispanCacheMeterBinder.java
https://issues.redhat.com/browse/ISPN-13294
> ISPN-13294 Adding nanoseconds average statistics in embedded actuator

- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/JwtConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/JwtConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/KeyStoreConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/OAuth2Configuration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/OAuth2ConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/RealmConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/RealmConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/SSLConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/TokenRealmConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
- server/runtime/src/main/resources/schema/infinispan-server-13.0.xsd
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
- server/tests/src/test/java/org/infinispan/server/security/AbstractAuthenticationKeyCloak.java
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationKeyCloakSSLIT.java
- server/tests/src/test/java/org/infinispan/server/test/core/KeyCloakServerRule.java
- server/tests/src/test/resources/configuration/AuthenticationKeyCloakSSLTest.xml
- server/tests/src/test/resources/configuration/security/keycloak-oauth2-ssl.xml
https://issues.redhat.com/browse/ISPN-13173
> ISPN-13173 Fix use of SSL context in token validation

- build-configuration/pom.xml
- cli/src/main/java/org/infinispan/cli/commands/kubernetes/Uninstall.java
* https://issues.redhat.com/browse/ISPN-13306 Fabric8 Kubernetes Client 5.7.3
* https://issues.redhat.com/browse/ISPN-13297 Mashona 1.0.0
* https://issues.redhat.com/browse/ISPN-13298 Hibernate Search 6.0.6.Final
* https://issues.redhat.com/browse/ISPN-13299 Hibernate ORM 5.3.22.Final
* https://issues.redhat.com/browse/ISPN-13300 Agroal 1.12
* https://issues.redhat.com/browse/ISPN-13301 JBoss Marshalling 2.0.12.Final
* https://issues.redhat.com/browse/ISPN-13302 Narayana 5.12.Final
* https://issues.redhat.com/browse/ISPN-13303 Spring Boot 2.5.4
* https://issues.redhat.com/browse/ISPN-13304 Spring Session 2.5.2
* https://issues.redhat.com/browse/ISPN-13305 Spring 5.3.10
and (no jiras for these since they are test/build only)
* Bouncycastle 1.69
* Byteman 4.0.9
> Upgrade circus

- persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
https://issues.redhat.com/browse/ISPN-13310
> ISPN-13310 RemoteStore alters configuration

- documentation/src/main/asciidoc/topics/code_examples/InfinispanContainer.java
- documentation/src/main/asciidoc/topics/code_examples/InfinispanContainerCredentials.java
- documentation/src/main/asciidoc/topics/infinispan_testcontainers.adoc
- pom.xml
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanContainer.java
- server/tests/src/test/java/org/infinispan/server/container/InfinispanContainerTest.java
https://issues.redhat.com/browse/ISPN-13196
@oraNod @karesti the PR contains an unreferenced doc topic, but we need to discuss how we should present this as well as any productization considerations.
> ISPN-13196 Infinispan Testcontainer

- server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeDynamicStoreCliIT.java
https://issues.redhat.com/browse/RollingUpgradeDynamicStoreCliIT_fix
> RollingUpgradeDynamicStoreCliIT failure fix

- persistence/sql/pom.xml
- pom.xml
- server/runtime/pom.xml
https://issues.redhat.com/browse/ISPN-13318
> ISPN-13318 Sql Store jar is not included in server distribution

- lock/src/main/java/org/infinispan/lock/configuration/ClusteredLockManagerConfiguration.java
- server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java
- server/tests/src/test/java/org/infinispan/server/functional/RestOperations.java
- server/tests/src/test/resources/configuration/cache-container/clustered.xml
Simplified counters configuration parser in rest resource
https://issues.redhat.com/browse/ISPN-13316
> ISPN-13316 Fix counter configuration parser in REST endpoint

- cli/src/main/java/org/infinispan/cli/commands/Batch.java
- cli/src/main/java/org/infinispan/cli/commands/CLI.java
- cli/src/main/java/org/infinispan/cli/impl/ContextImpl.java
https://issues.redhat.com/browse/ISPN-13322
https://issues.redhat.com/browse/ISPN-13323
(Also fix some command groups which break the native CLI)
> ISPN-13322 Fix null CLI prompt on authn connect error

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13329
> ISPN-13329 Upgrade Jakarta CDI API to 2.0.2

- distribution/src/main/resources/licenses/eclipse public license 2.0.txt
- server/runtime/build.xml
Added a copy of Eclipse Public License 2.0 to docs/licenses
https://issues.redhat.com/browse/ISPN-13328
> Add copy of EPL-2.0 to server.zip

- cli/src/main/java/org/infinispan/cli/commands/rest/Site.java
- cli/src/main/java/org/infinispan/cli/connection/Connection.java
- cli/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
- cli/src/main/resources/help/site.adoc
- core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
- core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
- core/src/main/java/org/infinispan/remoting/transport/AbstractDelegatingTransport.java
- core/src/main/java/org/infinispan/remoting/transport/Transport.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/test/java/org/infinispan/remoting/transport/MockTransport.java
- documentation/src/main/asciidoc/topics/json/rest_cache_manager_response.json
- documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
- server/rest/src/test/java/org/infinispan/rest/resources/ContainerResourceTest.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
- server/tests/src/test/java/org/infinispan/server/cli/XSiteCliOperations.java
* Expose cross-site information in JMX
* Renamed "site coordinator" to "relay node"
* Exposed relay nodes in CLI
https://issues.redhat.com/browse/ISPN-13337
> ISPN-13337 CLI: expose relay nodes

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java
- server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerRule.java
https://issues.redhat.com/browse/ISPN-13109
You can now run the test with the following VM args
```
-Dorg.infinispan.test.server.driver=FORKED  -Dinfinispan.server.root.path=/path/to/server_%d
```
> ISPN-13109 Server Root Directory support for ServerRunMode.FORKED

- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/cdi/GreetingCacheManagerIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/cdi/GreetingServiceIT.java
https://issues.redhat.com/browse/ISPN-12713
* Include all the test classes in the web archive
* Include the JCache dependency explicitly
> ISPN-12713 Fix GreetingServiceIT and GreetingCacheManagerIT

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ContinuousQueryObjectStorageTest.java
https://issues.redhat.com/browse/ISPN-13317
Wait only 100ms for unexpected events
> ISPN-13317 ContinuousQueryObjectStorageTest takes too long

- commons/all/src/main/java/org/infinispan/commons/dataconversion/internal/JsonArrayCollector.java
- commons/all/src/main/java/org/infinispan/commons/dataconversion/internal/JsonUtils.java
- core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
- documentation/src/main/asciidoc/topics/json/xsite_backup_status.json
- documentation/src/main/asciidoc/topics/ref_rest_xsite.adoc
- server/rest/pom.xml
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
- server/rest/src/test/java/org/infinispan/rest/TestModule.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
- server/tests/src/test/java/org/infinispan/server/functional/XSiteRestCacheOperations.java
* status now prints the nodes/caches that are online or offline and
caches with mixed status
https://issues.redhat.com/browse/ISPN-13276
> ISPN-13276 Improve XSite Rest Endpoint

- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-13313
> ISPN-13313 Expose key and value runtime storage type over REST

- core/src/test/java/org/infinispan/test/TestingUtil.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodFunctionalTest.java
https://issues.redhat.com/browse/ISPN-13342
Compute the lifespan/max-idle values just like the server would
> ISPN-13342 HotRodSslFunctionalTest.testLifespan2x random failure

- server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/CacheCreateTask.java
- server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/CacheGetOrCreateTask.java
- server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/TemplateCreateTask.java
- server/core/src/main/java/org/infinispan/server/core/logging/Log.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
- server/rest/src/test/resources/cache-fragment.xml
- server/runtime/src/main/java/org/infinispan/server/tasks/admin/CacheCreateTask.java
- server/runtime/src/main/java/org/infinispan/server/tasks/admin/CacheGetOrCreateTask.java
- server/tests/src/test/java/org/infinispan/server/functional/HotRodAdmin.java
https://issues.redhat.com/browse/ISPN-13333
> ISPN-13333 Fix creating caches from XML fragments over Hot Rod

- client/rest-client/src/main/java/org/infinispan/client/rest/RestRawClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestRawClientOkHttp.java
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- server/rest/pom.xml
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-13351
> ISPN-13351 REST multi-format config converter

- core/src/main/java/org/infinispan/configuration/cache/ExpirationConfigurationBuilder.java
- core/src/main/java/org/infinispan/container/impl/DefaultDataContainer.java
- core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/impl/InternalDataContainer.java
- core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java
- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
- core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/PassivationOptionsTest.java
- core/src/test/java/org/infinispan/reactive/publisher/impl/RehashClusterPublisherManagerTest.java
https://issues.redhat.com/browse/ISPN-11212
https://issues.redhat.com/browse/ISPN-11218
https://issues.redhat.com/browse/ISPN-13320
> ISPN-11212 Ensure Max idle works with passivation

- integrationtests/server-integration/README.md
- integrationtests/server-integration/server-integration-commons/pom.xml
- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/GenericDeploymentHelper.java
- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/store/AbstractInfinispanStoreRocksDBIT.java
- integrationtests/server-integration/third-party-server/pom.xml
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/DeploymentHelper.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/cdi/DuplicatedDomainsCdiIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/cdi/GreetingCacheManagerIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/cdi/GreetingServiceIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/embedded/InfinispanCoreIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/remote/HotRodClientIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/remote/HotRodQueryIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/remote/MemcachedClientIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/store/InfinispanStoreJdbcIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/store/InfinispanStoreJpaIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/store/InfinispanStoreRocksDBIT.java
- integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
- integrationtests/server-integration/wildfly-modules/src/test/java/org/infinispan/test/integration/as/store/InfinispanStoreRocksDBIT.java
- integrationtests/server-integration/wildfly-modules/src/test/resources/arquillian.xml
https://issues.redhat.com/browse/ISPN-12903
> ISPN-12910 Introduce clustered tests for third party servers

- server/runtime/src/test/java/org/infinispan/server/configuration/ServerOverlayConfigurationTest.java
- server/runtime/src/test/resources/configuration/Overlay-AsyncReplicatedCache.yml
- server/runtime/src/test/resources/configuration/OverlayJmx.yml
- server/runtime/src/test/resources/configuration/OverlayMetrics.xml
- server/runtime/src/test/resources/configuration/OverlayTwice.yml
https://issues.redhat.com/browse/ISPN-12931
> ISPN-12931 - Server configuration overlays

- core/src/main/java/org/infinispan/configuration/parsing/Attribute.java
- core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/resources/schema/infinispan-config-13.0.xsd
- core/src/test/resources/configs/named-cache-test.xml
https://issues.redhat.com/browse/ISPN-13350
> ISPN-13350 Use `capacity-factor` instead of `capacity`

- core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
- core/src/main/resources/schema/infinispan-config-14.0.xsd
https://issues.redhat.com/browse/ISPN-13429
> ISPN-13429 Be more lenient with parsing file-store.path for now

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/SyncModeTransactionTable.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/BaseMultiServerRemoteIteratorTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/multimap/RemoteMultimapStateTransferTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/stress/RemoteClientPutGetTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/transcoding/DataFormatTest.java
- client/infinispan-key-value-store-hotrod/src/test/java/org/infinispan/api/client/impl/SearchUtil.java
- commons/all/src/main/java/org/infinispan/commons/tx/TransactionManagerImpl.java
- commons/all/src/test/java/org/infinispan/commons/util/MarshallUtilTest.java
- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
- core/src/test/java/org/infinispan/commons/marshall/PojoWithAttributes.java
- core/src/test/java/org/infinispan/marshall/protostream/impl/ProtoStreamBackwardsCompatibilityTest.java
- core/src/test/java/org/infinispan/persistence/keymappers/DefaultTwoWayKey2StringMapperTest.java
- core/src/test/java/org/infinispan/tx/TransactionXaAdapterTmIntegrationTest.java
- query/src/test/java/org/infinispan/query/backend/KeyTransformationHandlerTest.java
- server/rest/src/test/java/org/infinispan/rest/profiling/BenchmarkHttpClient.java
- server/router/src/test/java/org/infinispan/server/router/profiling/PerfTestConfiguration.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedServer.java
- server/tests/src/test/java/org/infinispan/server/functional/XSiteHotRodCacheOperations.java
- spring/spring-boot/embedded/src/test/java/test/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfigurationCustomizerIntegrationTest.java
https://issues.redhat.com/browse/ISPN-11279
> ISPN-11279 Replace UUID.randomUUID() with Util.threadLocalRandomUUID()

- persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/sql/BaseTableOperations.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
https://issues.redhat.com/browse/ISPN-13439
> ISPN-13439 Result Set is not closed

- persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/sql/BaseTableOperations.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
https://issues.redhat.com/browse/ISPN-13439
> [13.0.x] ISPN-13439 Result Set is not closed

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
https://issues.redhat.com/browse/ISPN-13439
> [12.1.x] ISPN-13439 Result Set is not closed

- build-configuration/pom.xml
- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/store/AbstractInfinispanStoreRocksDBIT.java
- integrationtests/server-integration/third-party-server/pom.xml
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/DeploymentHelper.java
- integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
- persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
https://issues.redhat.com/browse/ISPN-13392
Backport: https://github.com/infinispan/infinispan/pull/9597
> [13.0] ISPN-13392 Fix Tomcat integration test setup

- core/src/main/java/org/infinispan/notifications/cachelistener/BaseQueueingSegmentListener.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/PartitionAwareClusterPublisherManager.java
- core/src/test/java/org/infinispan/notifications/cachelistener/BaseCacheNotifierImplInitialTransferTest.java
https://issues.redhat.com/browse/ISPN-13409
Fix notification for concurrent changes
Also fix expected value in BaseCacheNotifierImplInitialTransferTest
Do not wrap AvailabilityExceptions with CompletionExceptions
I just added the PR to ISPN-13409 since it wasn't integrated that long ago
> ISPN-13409 test fixes

- pom.xml
https://issues.redhat.com/browse/ISPN-13457
> [13.0.x] ISPN-13457 Upgrade javax.annotation-api to 1.3.2

- pom.xml
https://issues.redhat.com/browse/ISPN-13457
> ISPN-13457 Upgrade javax.annotation-api to 1.3.2

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/NearCacheConfiguration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/NearCacheConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfiguration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/DefaultNearCacheFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCacheFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCacheService.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedNearCacheTest.java
https://issues.redhat.com/browse/ISPN-13445
> ISPN-13445 NearCache factory

- documentation/src/main/asciidoc/stories/assembly_encrypting_cluster_traffic.adoc
- documentation/src/main/asciidoc/stories/assembly_setting_up_clusters.adoc
- documentation/src/main/asciidoc/topics/con_cluster_discovery_protocols.adoc
- documentation/src/main/asciidoc/topics/con_jgroups_encrypt.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_jgroups_asym_encrypt.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_jgroups_sym_encrypt.adoc
- documentation/src/main/asciidoc/topics/proc_customizing_jgroups_stacks.adoc
- documentation/src/main/asciidoc/topics/proc_securing_cluster_transport.adoc
- documentation/src/main/asciidoc/topics/proc_using_custom_jchannels.adoc
- documentation/src/main/asciidoc/topics/proc_using_jgroups_default.adoc
- documentation/src/main/asciidoc/topics/proc_using_jgroups_external.adoc
- documentation/src/main/asciidoc/topics/proc_using_jgroups_inline.adoc
- documentation/src/main/asciidoc/topics/proc_using_jgroups_system_properties.adoc
- documentation/src/main/asciidoc/topics/ref_discovery_cloud.adoc
- documentation/src/main/asciidoc/topics/ref_jgroups_default.adoc
- documentation/src/main/asciidoc/topics/ref_jgroups_extras_properties.adoc
- documentation/src/main/asciidoc/topics/ref_jgroups_inheritance_attributes.adoc
- documentation/src/main/asciidoc/topics/ref_jgroups_ports.adoc
- documentation/src/main/asciidoc/topics/ref_jgroups_system_properties.adoc
- documentation/src/main/asciidoc/topics/xml/server-transport-cache-container.xml
- documentation/src/main/asciidoc/topics/xml/server-transport-security.xml
https://issues.redhat.com/browse/ISPN-13460 
> ISPN-13460 server transport security docs

- server/runtime/src/main/server/server/conf/infinispan-xsite.xml
https://issues.redhat.com/browse/ISPN-13466
> ISPN-13466 Create valid cross-site configuration for server

- server/runtime/build.xml
https://issues.redhat.com/browse/ISPN-13464
> ISPN-13464 Add CDDL+GPL license to server zip

- server/runtime/build.xml
https://issues.redhat.com/browse/ISPN-13464
> [13.0.x] ISPN-13464 Add CDDL+GPL license to server zip

- documentation/src/main/asciidoc/topics/con_distributed_caches.adoc
- documentation/src/main/asciidoc/topics/con_expiration_overview.adoc
- documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc
- documentation/src/main/asciidoc/topics/con_scattered_caches.adoc
- documentation/src/main/asciidoc/topics/json/cache_template_inheritance.json
- documentation/src/main/asciidoc/topics/proc_creating_caches_console.adoc
- documentation/src/main/asciidoc/topics/protobuf/indexed_field.protobuf
- documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc
- documentation/src/main/asciidoc/topics/ref_query_ickle.adoc
- documentation/src/main/asciidoc/topics/ref_query_ickle_syntax.adoc
- documentation/src/main/asciidoc/topics/xml/cache_template_inheritance.xml
- documentation/src/main/asciidoc/topics/xml/persistence_cluster_loader.xml
- documentation/src/main/asciidoc/topics/yaml/cache_template_inheritance.yaml
https://issues.redhat.com/browse/ISPN-13458 
> ISPN-13458 query and config doc updates

- core/src/test/java/org/infinispan/xsite/irac/IracExponentialBackOffTest.java
Concurrency issue between ControlledExponentialBackOff asynBackOff() and
release()
- asyncBackOff() adds the event.BACK_OFF
- main thread is unblocked
- release() is invoked and creates a new CompletableFuture (CF)
- asyncBackOff() returns the new CF and IRAC gets stucks in there since
the CF is never completed
https://issues.redhat.com/browse/ISPN-13453
I think both failures are related since I'm unable to reproduce them locally. 
:crossed_fingers:
> ISPN-13453 IracExponentialBackOffTest random failures

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ByteBufUtil.java
- commons/all/src/main/java/org/infinispan/commons/util/Util.java
- server/core/src/main/java/org/infinispan/server/core/transport/ExtendedByteBuf.java
* hexDump() should respect the HEX_DUMP_LIMIT
https://issues.redhat.com/browse/ISPN-13482
> ISPN-13482 WrappedByteArray logging entire values

- server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java
https://issues.redhat.com/browse/ISPN-13484
> ISPN-13484 Hot Rod server should ignore IllegalLifecycleStateException from address cache

- documentation/src/main/asciidoc/topics/con_distributed_caches.adoc
- documentation/src/main/asciidoc/topics/con_expiration_overview.adoc
- documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc
- documentation/src/main/asciidoc/topics/con_scattered_caches.adoc
- documentation/src/main/asciidoc/topics/json/cache_template_inheritance.json
- documentation/src/main/asciidoc/topics/proc_creating_caches_console.adoc
- documentation/src/main/asciidoc/topics/protobuf/indexed_field.protobuf
- documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc
- documentation/src/main/asciidoc/topics/ref_query_ickle.adoc
- documentation/src/main/asciidoc/topics/ref_query_ickle_syntax.adoc
- documentation/src/main/asciidoc/topics/xml/cache_template_inheritance.xml
- documentation/src/main/asciidoc/topics/xml/persistence_cluster_loader.xml
- documentation/src/main/asciidoc/topics/yaml/cache_template_inheritance.yaml
Backport for https://issues.redhat.com/browse/ISPN-13458
> [13.0.x] ISPN-13458 query and config doc updates

- core/src/main/java/org/infinispan/util/logging/Log.java
- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointInteroperabilityTest.java
- server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java
- server/core/src/test/java/org/infinispan/server/core/dataconversion/JsonTranscoderTest.java
- server/rest/src/main/java/org/infinispan/rest/BaseHttpRequestHandler.java
- server/rest/src/main/java/org/infinispan/rest/CacheKeyInputStream.java
- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/BaseCacheResourceTest.java
- server/tests/src/test/java/org/infinispan/server/functional/ClusteredIT.java
https://issues.redhat.com/browse/ISPN-13345
> ISPN-13345 DataFormat MediaType.TEXT_PLAIN and UTF8Marshaller will change the content for JSON encoded cache

- core/src/main/java/org/infinispan/encoding/ProtostreamTranscoder.java
- server/rest/src/main/java/org/infinispan/rest/BaseHttpRequestHandler.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-13444
> ISPN-13444 Json to Protostream conversion does not show real error

- server/pom.xml
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/testdriver/pom.xml
https://issues.redhat.com/browse/ISPN-13498
Convert File to String when inserting in Properties
> ISPN-13498 ServerOverlayConfigurationTest NullPointerException on JDK17

- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/JDG-4943
Convert File to String when inserting in Properties
Backport of #9671
> [13.0.x] ISPN-13498 ServerOverlayConfigurationTest NullPointerException on JDK17

- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
- server/tests/src/test/java/org/infinispan/server/test/core/LdapServerListener.java
- server/tests/src/test/java/org/infinispan/server/test/core/ldap/AbstractLdapServer.java
- server/tests/src/test/java/org/infinispan/server/test/core/ldap/RemoteLdapServer.java
https://issues.redhat.com/browse/ISPN-13355
> ISPN-13355 Set LDAP server properties only in LdapServerListener

- server/runtime/src/main/java/org/infinispan/server/configuration/security/LdapUserPasswordMapperConfiguration.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
- server/tests/pom.xml
- server/tests/src/test/java/org/infinispan/server/security/AuthenticationKerberosIT.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationKerberosIT.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationLDAPIT.java
- server/tests/src/test/java/org/infinispan/server/test/core/LdapServerListener.java
- server/tests/src/test/java/org/infinispan/server/test/core/ldap/AbstractLdapServer.java
- server/tests/src/test/java/org/infinispan/server/test/core/ldap/ApacheLdapServer.java
- server/tests/src/test/java/org/infinispan/server/test/core/ldap/RemoteLdapServer.java
- server/tests/src/test/resources/configuration/security/ldap.xml
- server/tests/src/test/resources/ldif/infinispan-dn.ldif
- server/tests/src/test/resources/ldif/infinispan-kerberos.ldif
- server/tests/src/test/resources/ldif/infinispan.ldif
https://issues.redhat.com/browse/ISPN-13470
> ISPN-13470 Ldap UserPasswordCredentialLoaderBuilder shouldn't be added by default

- server/runtime/src/main/java/org/infinispan/server/security/realm/EncryptedPropertiesSecurityRealm.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/PropertiesSecurityRealm.java
https://issues.redhat.com/browse/ISPN-13507
> ISPN-13507 Lazily load user/groups properties

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheManagerAdminImpl.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminStandaloneTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/IndexedCacheNonIndexedEntityTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryRepeatedMappingTest.java
- commons/all/src/main/java/org/infinispan/commons/configuration/BasicConfiguration.java
- commons/all/src/main/java/org/infinispan/commons/configuration/StringConfiguration.java
- commons/all/src/main/java/org/infinispan/commons/configuration/XMLStringConfiguration.java
- core/src/main/java/org/infinispan/configuration/cache/Configuration.java
- server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/CacheCreateTask.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheConfigResource.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/api/BaseTestClientDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/api/RestTestClientDriver.java
- server/testdriver/junit5/src/test/java/org/infinispan/server/test/junit5/InfinispanXSiteServerTest.java
- server/tests/src/test/java/org/infinispan/server/functional/AnchoredKeysIT.java
- server/tests/src/test/java/org/infinispan/server/functional/HotRodAdmin.java
- server/tests/src/test/java/org/infinispan/server/functional/HotRodTransactionalCacheOperations.java
- server/tests/src/test/java/org/infinispan/server/functional/XSiteHotRodCacheOperations.java
- spring/spring-boot/remote/src/test/java/test/org/infinispan/spring/starter/remote/actuator/RemoteCacheMetricBinderTest.java
https://issues.redhat.com/browse/ISPN-13529
> ISPN-13529 Create caches over Hot Rod with XML, JSON and YAML

- documentation/src/main/asciidoc/topics/json/remote_store_minimal.json
- documentation/src/main/asciidoc/topics/proc_setting_up_target_clusters.adoc
https://issues.redhat.com/browse/ISPN-13459 
> ISPN-13459 rolling upgrade doc fixes

- documentation/src/main/asciidoc/topics/json/remote_store_minimal.json
- documentation/src/main/asciidoc/topics/proc_setting_up_target_clusters.adoc
https://issues.redhat.com/browse/ISPN-13459
> [13.0] ISPN-13459 rolling upgrade doc fixes

- core/src/main/java/org/infinispan/interceptors/impl/PrefetchInterceptor.java
- core/src/main/java/org/infinispan/stream/impl/local/EntryStreamSupplier.java
- core/src/main/java/org/infinispan/stream/impl/local/KeyStreamSupplier.java
- core/src/main/java/org/infinispan/stream/impl/local/SegmentedEntryStreamSupplier.java
- core/src/main/java/org/infinispan/stream/impl/local/SegmentedKeyStreamSupplier.java
- core/src/main/java/org/infinispan/util/CacheSetMapper.java
- core/src/test/java/org/infinispan/scattered/stream/ScatteredStreamIteratorExceptionTest.java
https://issues.redhat.com/browse/ISPN-13163
* Implement localPublisher in PrefetchInterceptor
* Filter tombstones in PrefetchInterceptor publishers
* Fix mock in ScatteredStreamIteratorExceptionTest
> ISPN-13163 Scattered cache key iteration is slow

- build-configuration/bom/pom.xml
- build-configuration/pom.xml
- pom.xml
Resolves
https://issues.redhat.com/browse/ISPN-13535
More details on the Jira.
> ISPN-13535 Fix maven-enforcer-plugin to require JDK 11

- core/src/main/java/org/infinispan/configuration/cache/BackupConfigurationBuilder.java
- core/src/main/java/org/infinispan/container/versioning/irac/DefaultIracTombstoneManager.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- core/src/main/java/org/infinispan/xsite/XSiteBackup.java
- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/main/java/org/infinispan/xsite/irac/IracResponseCollector.java
- core/src/main/java/org/infinispan/xsite/irac/IracXSiteBackup.java
- core/src/test/java/org/infinispan/xsite/XSiteCacheConfigurationTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
- core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
- documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/ISPN-13277
> ISPN-13277 Log exceptions for IRAC

- integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
https://issues.redhat.com/browse/ISPN-13469
> ISPN-13469 Tomcat Integration - Bind JGroups address to localhost

- cli/src/main/java/org/infinispan/cli/commands/rest/Site.java
- cli/src/main/java/org/infinispan/cli/resources/ContainerResource.java
- cli/src/main/resources/help/site.adoc
- client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheManagerClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheManagerClientOkHttp.java
- documentation/src/main/asciidoc/topics/proc_cli_xsite_push.adoc
- documentation/src/main/asciidoc/topics/proc_cli_xsite_sites.adoc
- documentation/src/main/asciidoc/topics/ref_rest_xsite_cache_managers.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
New option added: "--all-caches"
https://issues.redhat.com/browse/ISPN-13483
> ISPN-13483 Create global commands for site CLI command

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
readOnly
https://issues.redhat.com/browse/ISPN-13511
> [13.0.x] ISPN-13511 Stores gets cleared when the cache is deleted even if

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13519
> [13.0.x] ISPN-13519 upgrade console to 0.15.4.Final

- core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
- core/src/test/java/org/infinispan/test/data/Person.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/TwoWayPersonKey2StringMapper.java
- persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java
- persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
- persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcJoinTest.java
- persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcStoreFunctionalTest.java
https://issues.redhat.com/browse/ISPN-13515
> ISPN-13515 Jdbc Store Boolean does not work

- core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
https://issues.redhat.com/browse/ISPN-9161
> ISPN-9161 Incorrect description StateTransferManager attributes

- server/runtime/src/main/java/org/infinispan/server/configuration/security/CredentialStoreConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/security/ElytronPasswordProviderSupplier.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/CachingSecurityRealm.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/EncryptedPropertiesSecurityRealm.java
- server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationParserTest.java
https://issues.redhat.com/browse/ISPN-13546
> ISPN-13546 Fix caching realm to use explicit security providers

- server/runtime/src/main/java/org/infinispan/server/configuration/security/CredentialStoreConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/security/ElytronPasswordProviderSupplier.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/CachingSecurityRealm.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/EncryptedPropertiesSecurityRealm.java
- server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationParserTest.java
https://issues.redhat.com/browse/ISPN-13546
> [13.0] ISPN-13546 Fix caching realm to use explicit security providers

- cli/src/main/java/org/infinispan/cli/commands/Batch.java
https://issues.redhat.com/browse/ISPN-13500
> ISPN-13500 Allow install from batches

- persistence/jdbc-common/src/main/resources/schema/infinispan-cachestore-jdbc-common-config-14.0.xsd
- persistence/jdbc/src/main/resources/schema/infinispan-cachestore-jdbc-config-14.0.xsd
- persistence/sql/src/main/resources/schema/infinispan-cachestore-sql-config-14.0.xsd
- tools/src/main/java/org/infinispan/tools/xsd/XSDoc.java
- tools/src/main/resources/xsd/xsdoc.xslt
https://issues.redhat.com/browse/ISPN-13559
> ISPN-13559 Fix SQL cachestore schema

- persistence/jdbc-common/src/main/resources/schema/infinispan-cachestore-jdbc-common-config-13.0.xsd
- persistence/jdbc/src/main/resources/schema/infinispan-cachestore-jdbc-config-13.0.xsd
- persistence/sql/src/main/resources/schema/infinispan-cachestore-sql-config-13.0.xsd
- tools/src/main/java/org/infinispan/tools/xsd/XSDoc.java
- tools/src/main/resources/xsd/xsdoc.xslt
https://issues.redhat.com/browse/ISPN-13559
> [13.0] ISPN-13559 Fix SQL cachestore schema

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/NearCacheConfiguration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/NearCacheConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfiguration.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfigurationBuilder.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/DefaultNearCacheFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCacheFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCacheService.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedNearCacheTest.java
https://issues.redhat.com/browse/ISPN-13445
> [11.0.x] ISPN-13445 NearCache factory

- cli/src/main/java/org/infinispan/cli/commands/rest/Site.java
- cli/src/main/java/org/infinispan/cli/resources/ContainerResource.java
- cli/src/main/resources/help/site.adoc
- client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheManagerClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheManagerClientOkHttp.java
- documentation/src/main/asciidoc/topics/proc_cli_xsite_push.adoc
- documentation/src/main/asciidoc/topics/proc_cli_xsite_sites.adoc
- documentation/src/main/asciidoc/topics/ref_rest_xsite_cache_managers.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
New option added: "--all-caches"
https://issues.redhat.com/browse/ISPN-13483
> [13.0.x] ISPN-13483 Create global commands for site CLI command

- documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
- server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/ContainerResourceTest.java
https://issues.redhat.com/browse/ISPN-13491
https://issues.redhat.com/browse/ISPN-13514
> [13.0.x] ConfigurationListener Fixes

- build-configuration/pom.xml
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationCertIT.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationKerberosIT.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationPropertiesIT.java
https://issues.redhat.com/browse/ISPN-13562
> [13.0] ISPN-13562 Log4J 2.15.0

- build-configuration/pom.xml
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationLDAPIT.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationPropertiesIT.java
https://issues.redhat.com/browse/ISPN-13562
> [11.0] ISPN-13562 Log4J 2.15.0

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/JsonKeyValueRawEventsTest.java
- server/core/src/test/java/org/infinispan/server/core/dataconversion/JsonTranscoderTest.java
https://issues.redhat.com/browse/ISPN-13561
> ISPN-13561 Fix JsonTranscoderTest.testTranscoderTranscode failure

- core/src/main/java/org/infinispan/configuration/global/JGroupsConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/global/StackBuilder.java
- core/src/main/java/org/infinispan/configuration/global/StackConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/global/StackFileConfigurationBuilder.java
https://issues.redhat.com/browse/ISPN-13563
> ISPN-13563 JGroupsConfigurationBuilder should merge stacks on read()

- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
- core/src/test/java/org/infinispan/stream/DistributedStreamIteratorTest.java
https://issues.redhat.com/browse/ISPN-13560
> ISPN-13560 Local publisher handler not closed properly

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
readOnly
https://issues.redhat.com/browse/ISPN-13511
> [12.1.x] ISPN-13511 Stores gets cleared when the cache is deleted even if

- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
- core/src/test/java/org/infinispan/stream/DistributedStreamIteratorTest.java
https://issues.redhat.com/browse/ISPN-13560
> [13.0.x] ISPN-13560 Local publisher handler not closed properly

- server/runtime/src/main/java/org/infinispan/server/configuration/security/CredentialStoreConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/CredentialStoreConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/security/ElytronPasswordProviderSupplier.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/CachingSecurityRealm.java
- server/runtime/src/main/java/org/infinispan/server/security/realm/EncryptedPropertiesSecurityRealm.java
- server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationParserTest.java
https://issues.redhat.com/browse/ISPN-13546
> [12.1] ISPN-13546 Fix caching realm to use explicit security providers

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13553
> ISPN-13553 Netty 4.1.70

- server/runtime/src/main/java/org/infinispan/server/SecurityActions.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-13578
> [13.0] ISPN-13578 Workaround for Elytron not using supplied providers

- server/runtime/src/main/java/org/infinispan/server/SecurityActions.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-13578
> [12.1] ISPN-13578 Workaround for Elytron not using supplied providers

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13584
> ISPN-13584 Log4j 2.16.0

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13584
> [13.0] ISPN-13584 Log4j 2.16.0

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13584
> [12.1] ISPN-13584 Log4j 2.16.0

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13586
> ISPN-13586 Upgrade JGroups to 4.2.18.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13586
> [13.0.x] ISPN-13586 Upgrade JGroups to 4.2.18.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13584
> [11.0] ISPN-13584 Log4j 2.16.0

- core/src/main/java/org/infinispan/util/concurrent/CountDownRunnable.java
- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyChangedState.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyInfo.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyInfoImpl.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyState.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerStateTransferState.java
- core/src/main/java/org/infinispan/xsite/irac/IracResponseCollector.java
* Move the internal classes from DefaultIracManager to their own classes
https://issues.redhat.com/browse/ISPN-13589
> ISPN-13589 Move state from IracManager

- core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
https://issues.redhat.com/browse/ISPN-13588
> ISPN-13588 SIFS startup with a dirty index is really slow

- core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
https://issues.redhat.com/browse/ISPN-13588
> [13.0.x] ISPN-13588 SIFS startup with a dirty index is really slow

- server/runtime/src/main/java/org/infinispan/server/SecurityActions.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/security/ElytronHTTPAuthenticator.java
- server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationParserTest.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-13578
> ISPN-13578 Workaround for Elytron not using supplied providers

- server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java
https://issues.redhat.com/browse/ISPN-13594
> ISPN-13594 RequestTracingIT uses an invalid jaegertracing image

- documentation/src/main/asciidoc/titles/cli/cli.asciidoc
- documentation/src/main/asciidoc/titles/configuring/configuring.asciidoc
- documentation/src/main/asciidoc/titles/contributing/contributing.asciidoc
- documentation/src/main/asciidoc/titles/developing/developing.asciidoc
- documentation/src/main/asciidoc/titles/embedding/embedding.asciidoc
- documentation/src/main/asciidoc/titles/getting_started/getting_started.asciidoc
- documentation/src/main/asciidoc/titles/hotrod_java/hotrod_java.asciidoc
- documentation/src/main/asciidoc/titles/hotrod_protocol/hotrod_protocol.asciidoc
- documentation/src/main/asciidoc/titles/memcached/memcached.asciidoc
- documentation/src/main/asciidoc/titles/overview/overview.asciidoc
- documentation/src/main/asciidoc/titles/rest/rest.asciidoc
- documentation/src/main/asciidoc/titles/security/security.asciidoc
- documentation/src/main/asciidoc/titles/server/server.asciidoc
- documentation/src/main/asciidoc/titles/spring_boot/starter.asciidoc
- documentation/src/main/asciidoc/titles/tuning/tuning.asciidoc
- documentation/src/main/asciidoc/titles/upgrading/upgrading.asciidoc
- documentation/src/main/asciidoc/titles/xsite/xsite.asciidoc
https://issues.redhat.com/browse/ISPN-13595
> ISPN-13595 add sectanchors attribute to titles

- documentation/src/main/asciidoc/titles/cli/cli.asciidoc
- documentation/src/main/asciidoc/titles/configuring/configuring.asciidoc
- documentation/src/main/asciidoc/titles/contributing/contributing.asciidoc
- documentation/src/main/asciidoc/titles/developing/developing.asciidoc
- documentation/src/main/asciidoc/titles/embedding/embedding.asciidoc
- documentation/src/main/asciidoc/titles/getting_started/getting_started.asciidoc
- documentation/src/main/asciidoc/titles/hotrod_java/hotrod_java.asciidoc
- documentation/src/main/asciidoc/titles/hotrod_protocol/hotrod_protocol.asciidoc
- documentation/src/main/asciidoc/titles/memcached/memcached.asciidoc
- documentation/src/main/asciidoc/titles/overview/overview.asciidoc
- documentation/src/main/asciidoc/titles/rest/rest.asciidoc
- documentation/src/main/asciidoc/titles/security/security.asciidoc
- documentation/src/main/asciidoc/titles/server/server.asciidoc
- documentation/src/main/asciidoc/titles/spring_boot/starter.asciidoc
- documentation/src/main/asciidoc/titles/tuning/tuning.asciidoc
- documentation/src/main/asciidoc/titles/upgrading/upgrading.asciidoc
- documentation/src/main/asciidoc/titles/xsite/xsite.asciidoc
https://issues.redhat.com/browse/ISPN-13595
> [13.0.x] ISPN-13595 add sectanchors attribute to titles

- documentation/src/main/asciidoc/stories/assembly_migrating_data.adoc
- documentation/src/main/asciidoc/topics/attributes/store_migrator_source_versions.adoc
- documentation/src/main/asciidoc/topics/proc_configuring_store_migrator.adoc
- documentation/src/main/asciidoc/topics/ref_store_migrator_properties.adoc
Backport for https://issues.redhat.com/browse/ISPN-13590
> [13.0.x] ISPN-13590 include source.version field in migrator example

- commons/all/src/test/java/org/infinispan/commons/time/ControlledTimeService.java
- server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoder.java
- server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedFunctionalTest.java
- server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedSingleNodeTest.java
- server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedStatsTest.java
https://issues.redhat.com/browse/ISPN-13568
> ISPN-13568 MemcachedFunctionalTest.testTouchWithExpiryUnixTime fix

- core/src/main/java/org/infinispan/notifications/cachelistener/BaseQueueingSegmentListener.java
- core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
- core/src/main/java/org/infinispan/notifications/cachelistener/DistributedQueueingSegmentListener.java
- core/src/main/java/org/infinispan/notifications/cachelistener/EventWrapper.java
- core/src/main/java/org/infinispan/notifications/cachelistener/QueueingAllSegmentListener.java
- core/src/main/java/org/infinispan/notifications/cachelistener/QueueingSegmentListener.java
- core/src/test/java/org/infinispan/notifications/cachelistener/BaseCacheNotifierImplInitialTransferTest.java
- query-core/src/main/java/org/infinispan/query/core/impl/eventfilter/BaseIckleFilterIndexingServiceProvider.java
https://issues.redhat.com/browse/ISPN-13485
> ISPN-13485 Listener includeCurrentState memory improvements

- commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationWriter.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/xml/XmlConfigurationWriter.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationWriter.java
- core/src/main/java/org/infinispan/configuration/cache/ClusterLoaderConfigurationBuilder.java
- core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
- core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
- core/src/test/resources/configs/all/13.0.xml
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/JdbcStringBasedStoreConfigurationBuilder.java
* Make sure store properties case is not changed upon read or write
https://issues.redhat.com/browse/ISPN-13532
> [13.0.x] ISPN-13532 Cache store properties shouldn't be changed

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13597
> ISPN-13597 Log4J 2.17.0

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13597
> [13.0] ISPN-13597 Log4J 2.17.0

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13597
> [12.1] ISPN-13597 Log4J 2.17.0

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13597
> [11.0] ISPN-13597 Log4J 2.17.0

- core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
https://issues.redhat.com/browse/ISPN-13605
> ISPN-13605 SIFS write/delete/containsKey(...) exception handling does not conform to NonBlockingStore contract.

- commons/all/src/main/java/org/infinispan/commons/marshall/Ids.java
- core/src/main/java/org/infinispan/commands/CommandInvocationId.java
- core/src/main/java/org/infinispan/commands/CommandsFactory.java
- core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
- core/src/main/java/org/infinispan/commands/irac/IracStateResponseCommand.java
- core/src/main/java/org/infinispan/marshall/core/InternalExternalizers.java
- core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
- core/src/main/java/org/infinispan/xsite/irac/IracManager.java
- core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyInfoImpl.java
- core/src/main/java/org/infinispan/xsite/irac/NoOpIracManager.java
- core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
- core/src/test/java/org/infinispan/xsite/irac/ControlledIracManager.java
- core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java
When a topology changes, new owners request the "updates" keys from the
primary owner.
Batch multiple keys in a single command to send back to the requestor.
https://issues.redhat.com/browse/ISPN-13600
> ISPN-13600 Transfer IRAC state in batches

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13610
> ISPN-13610 Upgrade log4j to 2.17.1

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13610
> [13.0.x] ISPN-13610 Upgrade log4j to 2.17.1

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13610
> [12.1.x] ISPN-13610 Upgrade log4j to 2.17.1

- server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestServer.java
- server/tests/src/test/java/org/infinispan/server/resilience/ResilienceMaxRetryIT.java
https://issues.redhat.com/browse/ISPN-12598
> ISPN-12598 Hot Rod java client retries too many times

- core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java
- core/src/main/java/org/infinispan/expiration/ExpirationManager.java
- core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java
- core/src/main/java/org/infinispan/expiration/impl/InternalExpirationManager.java
- core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationMaxIdleTest.java
- core/src/test/java/org/infinispan/stress/DataContainerStressTest.java
https://issues.redhat.com/browse/ISPN-13549
> ISPN-13549 EntryWrappingInterceptor data race handling expired entries

- server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java
- server/tests/src/test/java/org/infinispan/server/extensions/PojoMarshalling.java
- server/tests/src/test/java/org/infinispan/server/persistence/CustomStoreOperationsIT.java
- server/tests/src/test/java/org/infinispan/server/persistence/ManagedConnectionOperations.java
- server/tests/src/test/java/org/infinispan/server/persistence/PooledConnectionOperations.java
- server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
https://issues.redhat.com/browse/ISPN-13620
> ISPN-13620 Server Test suite should use all servers configured by default

- core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
- core/src/test/java/org/infinispan/xsite/XSiteParsingTest.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-13623
https://issues.redhat.com/browse/ISPN-13624
> ISPN-13263 & ISPN-13624

- core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
- core/src/test/java/org/infinispan/xsite/XSiteParsingTest.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-13623
https://issues.redhat.com/browse/ISPN-13624
> [13.0.x] ISPN-13263 & ISPN-13624

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13629
> Netty 4.1.72.Final

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13629
> [13.0] Netty 4.1.72.Final

- core/src/main/java/org/infinispan/interceptors/distribution/NonTxDistributionInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java
- core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
- core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
- query/src/main/java/org/infinispan/query/backend/SegmentListener.java
https://issues.redhat.com/browse/ISPN-13604
> ISPN-13604 Should use IntSet.set whenever possible instead of IntSet.add

- distribution/src/main/resources/template/licenses-overwrite.xml
Temporary fix for the license report until we upgrade netty with the fix https://github.com/netty/netty-tcnative/pull/682
> Fix netty tcnative license report

- distribution/src/main/resources/template/licenses-overwrite.xml
Temporary fix for the license report until we upgrade netty with the fix https://github.com/netty/netty-tcnative/pull/682
> [13.x] Fix netty tcnative license report

- core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java
- core/src/main/java/org/infinispan/factories/ComponentRegistry.java
- core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
- core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java
- core/src/main/java/org/infinispan/util/logging/Log.java
- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
- server/tests/src/test/java/org/infinispan/server/functional/StartupFailureIT.java
https://issues.redhat.com/browse/ISPN-13634
https://issues.redhat.com/browse/ISPN-10910
> ISPN-13634+ISPN-10910 Log cache/manager/server startup errors immediately

- integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
https://issues.redhat.com/browse/ISPN-13469
Backport https://github.com/infinispan/infinispan/pull/9656
> ISPN-13469 Tomcat Integration - Bind JGroups address to

- persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
https://issues.redhat.com/browse/ISPN-13656
> ISPN-13656 Prevent NPE in RemoteStore:stop

- core/src/main/java/org/infinispan/configuration/cache/CacheMode.java
- core/src/main/java/org/infinispan/configuration/parsing/Element.java
- core/src/main/resources/schema/infinispan-config-14.0.xsd
- core/src/main/resources/schema/infinispan-config-fragment-14.0.xsd
- documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/ISPN-13644
> ISPN-13644 Deprecate scattered cache

- core/src/main/java/org/infinispan/container/impl/EntryFactory.java
- core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java
- core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java
- core/src/main/java/org/infinispan/interceptors/distribution/L1NonTxInterceptor.java
- core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java
- core/src/test/java/org/infinispan/api/ConditionalOperationPrimaryOwnerFailTest.java
- core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationMaxIdleTest.java
https://issues.redhat.com/browse/JDG-5028
Backport of https://github.com/infinispan/infinispan/pull/9805 for 13.0.x
> [13.0.x] ISPN-13549 EntryWrappingInterceptor data race handling expired entries

- core/src/main/java/org/infinispan/container/impl/EntryFactory.java
- core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java
- core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java
- core/src/main/java/org/infinispan/interceptors/distribution/L1NonTxInterceptor.java
- core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java
- core/src/test/java/org/infinispan/api/ConditionalOperationPrimaryOwnerFailTest.java
- core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationMaxIdleTest.java
https://issues.redhat.com/browse/ISPN-13549
https://issues.redhat.com/browse/JDG-5028
Backport of #9805 for 12.1.x.
> [12.1.x] ISPN-13549 EntryWrappingInterceptor data race handling expired entries

- core/src/main/java/org/infinispan/container/impl/EntryFactory.java
- core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java
- core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java
- core/src/main/java/org/infinispan/interceptors/distribution/L1NonTxInterceptor.java
- core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java
- core/src/test/java/org/infinispan/api/ConditionalOperationPrimaryOwnerFailTest.java
- core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationFunctionalTest.java
https://issues.redhat.com/browse/ISPN-13549
https://issues.redhat.com/browse/JDG-5080
Backport of https://github.com/infinispan/infinispan/pull/9805 for 11.0.x.
> [11.0.x] ISPN-13549 EntryWrappingInterceptor data race handling expired entries

- build-configuration/pom.xml
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/AbstractRemoteCacheIT.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/CustomPojoEventConverterFactory.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/CustomPojoEventFilterFactory.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/CustomPojoFilterConverterFactory.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/Id.java
- server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/Person.java
https://issues.redhat.com/browse/ISPN-13657
> [9.4.x] ISPN-13657 Upgrade jboss-marshalling to 2.0.12.Final

- documentation/src/main/asciidoc/server_guide/configuration.adoc
Remove JGroups SASL from downstream docs.
https://issues.redhat.com/browse/ISPN-13663
> [9.4.x] ISPN-13663 conditionalize docs for JGroups SASL

- server/core/src/main/java/org/infinispan/server/core/backup/BackupManagerImpl.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/InternalCacheResource.java
- server/tests/src/test/java/org/infinispan/server/functional/BackupManagerIT.java
https://issues.redhat.com/browse/ISPN-13591
> ISPN-13591 Backups fail if a proto schema key contains forward slashes

- documentation/src/main/asciidoc/topics/xml/local_cache.xml
https://issues.redhat.com/browse/ISPN-10603
> ISPN-10603 Fixing a typo in the docs

- documentation/src/main/asciidoc/topics/xml/local_cache.xml
https://issues.redhat.com/browse/ISPN-10603
> [13.0.x] ISPN-10603 Fixing a typo in the docs

- build-configuration/pom.xml
- pom.xml
- server/core/src/main/java/org/infinispan/server/core/dataconversion/XMLTranscoder.java
https://issues.redhat.com/browse/ISPN-13676
> ISPN-13676 XStream 1.4.19

- build-configuration/pom.xml
- pom.xml
- server/core/src/main/java/org/infinispan/server/core/dataconversion/XMLTranscoder.java
https://issues.redhat.com/browse/ISPN-13676
> [12.1] ISPN-13676 XStream 1.4.19

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13622
> Elytron 1.17.3

- build-configuration/pom.xml
Reverts infinispan/infinispan#9794
> Revert "Elytron 1.17.3"

- cli/src/test/java/org/infinispan/cli/user/UserToolTest.java
- commons/all/src/main/java/org/infinispan/commons/util/Util.java
https://issues.redhat.com/browse/ISPN-13683
> ISPN-13683 Close files in UserToolTest

- core/src/main/java/org/infinispan/stats/impl/CacheContainerStatsImpl.java
- core/src/main/java/org/infinispan/stats/impl/SecurityActions.java
- core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
- core/src/test/java/org/infinispan/test/SecurityActions.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- counter/src/main/java/org/infinispan/counter/impl/CounterModuleLifecycle.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStoreTxFunctionalTest.java
- persistence/rocksdb/src/test/java/org/infinispan/persistence/rocksdb/RocksDBStoreFunctionalTest.java
- persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java
- persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
- tasks/manager/src/main/java/org/infinispan/tasks/impl/SecurityActions.java
- tasks/manager/src/main/java/org/infinispan/tasks/impl/TaskManagerImpl.java
https://issues.redhat.com/browse/ISPN-13671
https://issues.redhat.com/browse/ISPN-13678
https://issues.redhat.com/browse/ISPN-13679
https://issues.redhat.com/browse/ISPN-13680
https://issues.redhat.com/browse/ISPN-13681
~~I've only tested `JdbcStringBasedStoreFunctionalTest` locally, let's see what else fails :slightly_smiling_face:~~
> ISPN-13671 JDBC store fails when authorization is enabled

- server/rest/src/main/java/org/infinispan/rest/HttpMessageUtil.java
- server/rest/src/main/java/org/infinispan/rest/ResponseWriter.java
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
https://issues.redhat.com/browse/ISPN-13602
> ISPN-13602 Add trace logs to show server http requests and responses

- server/rest/src/main/java/org/infinispan/rest/HttpMessageUtil.java
- server/rest/src/main/java/org/infinispan/rest/ResponseWriter.java
- server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
https://issues.redhat.com/browse/ISPN-13602-13_0
> [13.0.x] ISPN-13602 Add trace logs to show server http requests and responses

- server/hotrod/src/test/java/org/infinispan/server/hotrod/ServerHotRodTestBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-13697
> ISPN-13697 HotRodEventsTest random failures

- integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
https://issues.redhat.com/browse/ISPN-13698
> ISPN-13698 Wildfly integration test - module java.base does not "opens java.*"

- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/configuration/ConfigurationTest.java
https://issues.redhat.com/browse/ISPN-13700
> [13.0.x] ISPN-13700 ConfigurationTest fails on 13.0.x

- core/src/main/java/org/infinispan/functional/FunctionalMap.java
- core/src/main/java/org/infinispan/functional/impl/AbstractFunctionalMap.java
- core/src/main/java/org/infinispan/functional/impl/FunctionalMapImpl.java
- counter/src/main/java/org/infinispan/counter/impl/CounterModuleLifecycle.java
- counter/src/main/java/org/infinispan/counter/impl/listener/CounterManagerNotificationManager.java
- counter/src/main/java/org/infinispan/counter/impl/manager/EmbeddedCounterManager.java
- counter/src/main/java/org/infinispan/counter/impl/strong/AbstractStrongCounter.java
https://issues.redhat.com/browse/ISPN-13613
> ISPN-13613 Convert CounterManagerNotificationManager to component

- documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlQuery.java
- documentation/src/main/asciidoc/topics/json/persistence_sql_query.json
- documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
- documentation/src/main/asciidoc/topics/yaml/persistence_sql_query.yaml
https://issues.redhat.com/browse/ISPN-13677
> ISPN-13677 sql query config correction

- documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlQuery.java
- documentation/src/main/asciidoc/topics/json/persistence_sql_query.json
- documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
- documentation/src/main/asciidoc/topics/yaml/persistence_sql_query.yaml
https://issues.redhat.com/browse/ISPN-13677
> [13.0.x] ISPN-13677 sql query config correction

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/manager/PersistenceManagerTest.java
https://issues.redhat.com/browse/ISPN-13664
> ISPN-13664 Deadlock on closing of PersistenceManagerImpl

- server/runtime/src/main/java/org/infinispan/server/Server.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
- server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestServer.java
- server/tests/src/test/java/org/infinispan/server/resilience/ResilienceMaxRetryIT.java
- spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/ConfigurationPropertiesOverrides.java
https://issues.redhat.com/browse/ISPN-13640
Replacing https://github.com/infinispan/infinispan/pull/9814 and https://github.com/infinispan/infinispan/pull/9821
@diegolovison I opened my own PR in the end to add a high level description in the class javadoc and to also simplify the code a bit.
> ISPN-13640 ResilienceMaxRetryIT is failing randomly

- build-configuration/pom.xml
- pom.xml
- server/core/src/main/java/org/infinispan/server/core/dataconversion/XMLTranscoder.java
https://issues.redhat.com/browse/ISPN-13676
> [13.0] ISPN-13676 XStream 1.4.19

- core/src/main/java/org/infinispan/stats/impl/CacheContainerStatsImpl.java
- core/src/main/java/org/infinispan/stats/impl/SecurityActions.java
- core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
- core/src/test/java/org/infinispan/test/SecurityActions.java
- core/src/test/java/org/infinispan/test/TestingUtil.java
- counter/src/main/java/org/infinispan/counter/impl/CounterModuleLifecycle.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStoreTxFunctionalTest.java
- persistence/rocksdb/src/test/java/org/infinispan/persistence/rocksdb/RocksDBStoreFunctionalTest.java
- persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java
- persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
- tasks/manager/src/main/java/org/infinispan/tasks/impl/SecurityActions.java
- tasks/manager/src/main/java/org/infinispan/tasks/impl/TaskManagerImpl.java
https://issues.redhat.com/browse/ISPN-13671
https://issues.redhat.com/browse/ISPN-13678
https://issues.redhat.com/browse/ISPN-13679
https://issues.redhat.com/browse/ISPN-13680
https://issues.redhat.com/browse/ISPN-13681
> [13.0.x] Authorization fixes

- integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
https://issues.redhat.com/browse/JDG-4944
Backport of https://github.com/infinispan/infinispan/pull/9876
> [13.0.x] ISPN-13698 Wildfly integration test - module java.base does not "opens java.*" 

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
https://issues.redhat.com/browse/ISPN-13664
> ISPN-13664 NullPointerException in PersistenceManagerImpl.stop()

- core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
- core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/manager/PersistenceManagerTest.java
https://issues.redhat.com/browse/ISPN-13664
> [13.0.x] ISPN-13664 Deadlock on closing of PersistenceManagerImpl

- client/hotrod-client/pom.xml
- commons/all/pom.xml
- core/pom.xml
- extended-statistics/pom.xml
- persistence/jdbc-common/pom.xml
- persistence/jdbc/pom.xml
- persistence/sql/pom.xml
- pom.xml
- query/pom.xml
- server/hotrod/pom.xml
- server/tests/pom.xml
- tools/pom.xml
https://issues.redhat.com/browse/ISPN-13207
> ISPN-13207 Jakarta Jars

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/ServerStatistics.java
- core/src/main/java/org/infinispan/persistence/spi/NonBlockingStore.java
- core/src/main/java/org/infinispan/stats/Stats.java
- core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java
- core/src/main/java/org/infinispan/stats/impl/StatsCollector.java
https://issues.redhat.com/browse/ISPN-13421
> ISPN-13421 Address doc review comments

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/OracleTableManager.java
[ISPN-13670](https://issues.redhat.com/browse/ISPN-13670)
> ISPN-13670 Error When Use Schema in Oracle

- build-configuration/pom.xml
- cloudevents-integration/src/test/java/org/infinispan/cloudevents/MockKafkaEventSender.java
https://issues.redhat.com/browse/ISPN-13646
> ISPN-13646 Upgrade Kafka client to version 2.8.1

- client/hotrod-client/pom.xml
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/LargeTermTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/KeywordEntity.java
https://issues.redhat.com/browse/ISPN-13645
I already closed this issue because running the reproducer provided by the user, we discovered that it wasn't an issue related to Infinispan.
Anyway, it could be nice to have this test in our tests suite.
If the team agrees, let's merge it.
> ISPN-13645 Test persist immense term

- build-configuration/pom.xml
- query/src/main/java/org/infinispan/search/mapper/impl/InfinispanEntityTypeContributor.java
- query/src/main/java/org/infinispan/search/mapper/model/impl/InfinispanRuntimeIntrospector.java
https://issues.redhat.com/browse/ISPN-13713
> ISPN-13713 Update Hibernate Search to 6.0.8

- build-configuration/pom.xml
- query/src/main/java/org/infinispan/search/mapper/impl/InfinispanEntityTypeContributor.java
- query/src/main/java/org/infinispan/search/mapper/model/impl/InfinispanRuntimeIntrospector.java
https://issues.redhat.com/browse/ISPN-13713
Backport of #9898 to 13.0.x
> ISPN-13713 Update Hibernate Search to 6.0.8 (13.0.x)

- build-configuration/pom.xml
- query/src/main/java/org/infinispan/search/mapper/impl/InfinispanEntityTypeContributor.java
- query/src/main/java/org/infinispan/search/mapper/model/impl/InfinispanRuntimeIntrospector.java
https://issues.redhat.com/browse/ISPN-13713
Backport of #9898 to 13.0.x
> ISPN-13713 Update Hibernate Search to 6.0.8 (12.1.x)

- server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
- server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
https://issues.redhat.com/browse/ISPN-13719
> ISPN-13719 Register NettyTransport metrics

- documentation/src/main/asciidoc/stories/assembly_wildfly_modules.adoc
https://issues.redhat.com/browse/ISPN-13714
> ISPN-13714 downstream revision of WildFly modules content

- documentation/src/main/asciidoc/stories/assembly_wildfly_modules.adoc
https://issues.redhat.com/browse/ISPN-13714
> [13.0.x] ISPN-13714 downstream revision of WildFly modules content 

- server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
- server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
https://issues.redhat.com/browse/ISPN-13719
> [13.0.x] ISPN-13719 Register NettyTransport metrics

- server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SecurityActions.java
- server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
Register SinglePortEndpointRouter in GlobalComponentRegistry
https://issues.redhat.com/browse/ISPN-13730
> ISPN-13730 NullPointerException when computing Netty global connections

- server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SecurityActions.java
- server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
Register SinglePortEndpointRouter in GlobalComponentRegistry
https://issues.redhat.com/browse/ISPN-13730
> [13.0.x] ISPN-13730 NullPointerException when computing Netty global connections

- component-annotations/src/main/java/org/infinispan/external/JGroupsProtocolComponent.java
- component-processor/pom.xml
- component-processor/src/main/java/org/infinispan/component/processor/external/JGroupsComponentProcessor.java
- core/pom.xml
- core/src/main/java/org/infinispan/metrics/impl/AbstractMetricsRegistration.java
- core/src/main/java/org/infinispan/metrics/impl/CacheManagerMetricsRegistration.java
- core/src/main/java/org/infinispan/metrics/impl/CacheMetricsRegistration.java
- core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/AbstractJGroupsChannelConfigurator.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/FileJGroupsChannelConfigurator.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsChannelConfigurator.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
https://issues.redhat.com/browse/ISPN-13463
> [13.0] ISPN-13463 Expose JGroups metrics

- wildfly/feature-pack/pom.xml
- wildfly/feature-pack/src/main/resources/modules/org/infinispan/slot/module.xml
https://issues.redhat.com/browse/ISPN-13695
> ISPN-13695 Modules for Wildfly does not include all hibernate artifacts

- documentation/src/main/asciidoc/topics/json/cache_template_inheritance.json
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- documentation/src/main/asciidoc/topics/xml/cache_template_inheritance.xml
- documentation/src/main/asciidoc/topics/xml/server_authentication_mechanisms.xml
- documentation/src/main/asciidoc/topics/yaml/cache_template_inheritance.yaml
- documentation/src/main/asciidoc/topics/yaml/persistence_file_store.yaml
https://issues.redhat.com/browse/ISPN-13707
> ISPN-13707 minor doc updates

- documentation/src/main/asciidoc/topics/json/cache_template_inheritance.json
- documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
- documentation/src/main/asciidoc/topics/xml/cache_template_inheritance.xml
- documentation/src/main/asciidoc/topics/xml/server_authentication_mechanisms.xml
- documentation/src/main/asciidoc/topics/yaml/cache_template_inheritance.yaml
- documentation/src/main/asciidoc/topics/yaml/persistence_file_store.yaml
Backport for https://issues.redhat.com/browse/ISPN-13707
> [13.0.x] ISPN-13707 docs revision

- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManager.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/InnerPublisherSubscription.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java
- core/src/test/java/org/infinispan/reactive/publisher/impl/SimpleClusterPublisherManagerTest.java
https://issues.redhat.com/browse/ISPN-13616
https://issues.redhat.com/browse/ISPN-13628
> ISPN-13616 Stream pipeline blocks if filterKeys() gets an empty set

- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/persistence/jdbc/stringbased/PooledConnectionIT.java
- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/persistence/jdbc/util/JdbcConfigurationUtil.java
- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/persistence/jdbc/util/TableManipulation.java
- integrationtests/server-integration/third-party-server/pom.xml
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/persistence/jdbc/stringbased/PooledConnectionDeployIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/persistence/jdbc/util/BaseJdbcDeploy.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/store/InfinispanStoreJdbcIT.java
- integrationtests/server-integration/third-party-server/src/test/resources/connection.properties
- integrationtests/server-integration/third-party-server/src/test/resources/db2.properties
- integrationtests/server-integration/third-party-server/src/test/resources/h2.properties
- integrationtests/server-integration/third-party-server/src/test/resources/mariadb.properties
- integrationtests/server-integration/third-party-server/src/test/resources/mssql.properties
- integrationtests/server-integration/third-party-server/src/test/resources/mysql.properties
- integrationtests/server-integration/third-party-server/src/test/resources/oracle.properties
- integrationtests/server-integration/third-party-server/src/test/resources/postgresplus.properties
- integrationtests/server-integration/third-party-server/src/test/resources/postgresql.properties
- integrationtests/server-integration/third-party-server/src/test/resources/sybase.properties
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/TableManagerTest.java
- server/tests/src/test/java/org/infinispan/server/persistence/PooledConnectionOperations.java
https://issues.redhat.com/browse/ISPN-13606
> ISPN-13606 Add embedded jdbc tests into integrationtests/server-integration/third-party-server

- .github/workflows/sync_docs.yml
GitHub action to sync changes to documentation to the dev docs.
https://issues.redhat.com/browse/ISPN-13735
> ISPN-13735 Actions to keep docs in sync

- core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
- core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java
- core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
- core/src/test/java/org/infinispan/globalstate/GlobalStateRestartJoinWithZeroCapacityTest.java
https://issues.redhat.com/browse/ISPN-13729
https://issues.redhat.com/browse/ISPN-13734
> [13.0.x] ISPN-13729 Zero capacity node throws NPE on sendJoinRequest after upgrade

- documentation/src/main/asciidoc/stories/assembly_server_getting_started.adoc
- documentation/src/main/asciidoc/topics/con_platforms_automation_tooling.adoc
https://issues.redhat.com/browse/ISPN-13744
> Add Ansible Collection to server start

- .github/workflows/sync_docs.yml
https://issues.redhat.com/browse/ISPN-13735 
@ryanemerson Hey I think we need to add this to 13.0.x as well. The workflow needs to be on all branches where you want it to run. At the moment it's on `main` only.
> [13.0.x] Add action to sync dev and stable docs

- documentation/src/main/asciidoc/stories/assembly_architecture_use_cases.adoc
- documentation/src/main/asciidoc/topics/con_platforms_automation_tooling.adoc
Backport for https://issues.redhat.com/browse/ISPN-13672
> [13.0.x] ISPN-13672 minor doc change

- build/configuration/pom.xml
Latest Dev release
Track issue for 14 https://issues.redhat.com/browse/ISPN-13626
> Upgrade to next dev version of the Console: 14.0.0.Dev02

- core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
- core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationStateListener.java
- core/src/test/java/org/infinispan/globalstate/GlobalStateRestartWithCacheTest.java
https://issues.redhat.com/browse/ISPN-13740
> ISPN-13470 Unable to delete a cache after graceful shutdown

- core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
- core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationStateListener.java
- core/src/test/java/org/infinispan/globalstate/GlobalStateRestartWithCacheTest.java
https://issues.redhat.com/browse/ISPN-13740
> [13.0.x] ISPN-13470 Unable to delete a cache after graceful shutdown

- documentation/src/main/asciidoc/stories/assembly_server_encryption.adoc
- documentation/src/main/asciidoc/topics/json/server_ssl_identity_fips.json
- documentation/src/main/asciidoc/topics/proc_configuring_server_fips.adoc
- documentation/src/main/asciidoc/topics/xml/server_ssl_identity_fips.xml
- documentation/src/main/asciidoc/topics/yaml/server_ssl_identity_fips.yaml
- server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/KeyStoreConfiguration.java
- server/runtime/src/main/java/org/infinispan/server/configuration/security/KeyStoreConfigurationBuilder.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
- server/runtime/src/main/java/org/infinispan/server/security/KeyStoreUtils.java
- server/runtime/src/main/resources/schema/infinispan-server-13.0.xsd
https://issues.redhat.com/browse/ISPN-13737
> [13.0] ISPN-13737 Allow configuring file-less keystores

- server/core/src/main/java/org/infinispan/server/core/backup/BackupManagerImpl.java
- server/core/src/main/java/org/infinispan/server/core/backup/resources/InternalCacheResource.java
- server/tests/src/test/java/org/infinispan/server/functional/BackupManagerIT.java
https://issues.redhat.com/browse/ISPN-13591
> [13.0.x] ISPN-13591 Backups fail if a proto schema key contains forward slashes

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13760
> ISPN-13760 Elytron 1.18.3

- core/src/main/java/org/infinispan/util/logging/Log.java
- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/logging/Log.java
- server/runtime/src/main/server/server/conf/log4j2.xml
https://issues.redhat.com/browse/ISPN-13759
> ISPN-13759 Lower version log to DEBUG

- core/src/main/java/org/infinispan/configuration/global/JGroupsConfiguration.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
- core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java
- core/src/test/resources/configs/config-with-jgroups-stack.xml
https://issues.redhat.com/browse/ISPN-13765
> ISPN-13765 Unable to start full JGroups stacks

- core/src/main/java/org/infinispan/configuration/global/JGroupsConfiguration.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
- core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java
- core/src/test/resources/configs/config-with-jgroups-stack.xml
https://issues.redhat.com/browse/ISPN-13765
> [13.0.x] ISPN-13765 Unable to start full JGroups stacks

- core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
https://issues.redhat.com/browse/ISPN-13605
Original fix was accidentally reverted by https://github.com/infinispan/infinispan/pull/9753
> ISPN-13605 SIFS write/delete/containsKey(...) exception handling does not conform to NonBlockingStore contract

- core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
https://issues.redhat.com/browse/ISPN-13605
> [13.0.x] ISPN-13605 SIFS write/delete/containsKey(...) exception handling does not conform to NonBlockingStore contract

- documentation/src/main/asciidoc/topics/ref_executing_secure_caches.adoc
https://issues.redhat.com/browse/ISPN-13763 
Fix typo in the Security guide
> ISPN-13763 fix typo

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13773
> ISPN-13773 Upgrade Jackson to 2.13.1

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13776
> ISPN-13776 Upgrade Kubernetes Client to 5.7.4

- pom.xml
https://issues.redhat.com/browse/ISPN-13774
> ISPN-13774 Upgrade AWS java SDK to 1.12.180

- pom.xml
https://issues.redhat.com/browse/ISPN-13775
> ISPN-13775 Upgrade Jaeger to 1.6.0

- build/configuration/pom.xml
- build/infinispan-defaults-maven-plugin/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13772
> ISPN-13772 Upgrade mojo-executor to 2.4.0

- build-configuration/pom.xml
- plugins/infinispan-defaults-maven-plugin/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13772
https://issues.redhat.com/browse/ISPN-13773
https://issues.redhat.com/browse/ISPN-13774
https://issues.redhat.com/browse/ISPN-13775
https://issues.redhat.com/browse/ISPN-13776
> [13.0.x] ISPN-1377{2..6} Dependencies Upgrade

- cli/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13771
> ISPN-13771 Remove org.jboss.remotingjmx:remoting-jmx from CLI

- cli/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13771
> [13.0.x] ISPN-13771 Remove org.jboss.remotingjmx:remoting-jmx from CLI

- server/tests/src/test/java/org/infinispan/server/test/core/LdapServerListener.java
- server/tests/src/test/java/org/infinispan/server/test/core/ldap/AbstractLdapServer.java
- server/tests/src/test/java/org/infinispan/server/test/core/ldap/ApacheLdapServer.java
- server/tests/src/test/java/org/infinispan/server/test/core/ldap/RemoteLdapServer.java
https://issues.redhat.com/browse/ISPN-13752
> ISPN-13752 - Remote LDAP Kerberos support

- integrationtests/server-integration/third-party-server/pom.xml
- integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
- integrationtests/server-integration/wildfly-modules/pom.xml
https://issues.redhat.com/browse/ISPN-13762
> [13.0.x] ISPN-13762 Dynamic java8 arguments for server integration tests

- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/persistence/jdbc/util/BaseJdbcDeploy.java
https://issues.redhat.com/browse/ISPN-13606
> ISPN-13606 Fix NPE in PooledConnectionDeployIT

- core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
- core/src/main/java/org/infinispan/reactive/publisher/impl/LocalPublisherManagerImpl.java
- core/src/test/java/org/infinispan/reactive/publisher/impl/SimpleClusterPublisherManagerTest.java
https://issues.redhat.com/browse/ISPN-13736
> ISPN-13736 Stream pipeline blocks if filterKeys() gets a set where no key matches

- build/configuration/pom.xml
- cli/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13785
> ISPN-13785 Remove jboss-remoting and xnio

- core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
- core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
- core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
- core/src/main/java/org/infinispan/xsite/status/TakeOfflineManager.java
- server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java
- server/tests/src/test/java/org/infinispan/server/functional/XSiteRestMetricsOperations.java
https://issues.redhat.com/browse/ISPN-13723
> [13.0.x] ISPN-13723 Create metric for site status

- build-configuration/pom.xml
- cli/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13785
> [13.0.x] ISPN-13785 Remove jboss-remoting and xnio

- build-configuration/pom.xml
- cloudevents-integration/src/test/java/org/infinispan/cloudevents/MockKafkaEventSender.java
https://issues.redhat.com/browse/ISPN-13782
> [13.0.x] Upgrade Kafka client to version 2.7.2

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
https://issues.redhat.com/browse/ISPN-13781
> [13.0.x] ISPN-13781 Hot Rod client configuration values

- core/src/main/java/org/infinispan/persistence/sifs/Compactor.java
- core/src/main/java/org/infinispan/persistence/sifs/Index.java
- core/src/main/java/org/infinispan/persistence/sifs/Log.java
- core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFunctionalTest.java
https://issues.redhat.com/browse/ISPN-13747
> [13.0.x] ISPN-13747 Compactor throws null pointer exception and stops working

- commons/all/src/main/java/org/infinispan/commons/tx/TransactionImpl.java
https://issues.redhat.com/browse/ISPN-13789
> ISPN-13789 Avoid copying XaResource list when commit transactions

- core/src/main/java/org/infinispan/persistence/sifs/Compactor.java
- core/src/main/java/org/infinispan/persistence/sifs/Index.java
- core/src/main/java/org/infinispan/persistence/sifs/Log.java
- core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFunctionalTest.java
https://issues.redhat.com/browse/ISPN-13747
> ISPN-13747 Compactor throws null pointer exception and stops working

- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/event/impl/ContinuousQueryImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/DelegatingRemoteCache.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/QuerySerializer.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/query/RemoteQueryFactory.java
- client/hotrod-client/src/main/java/org/infinispan/client/hotrod/marshall/MarshallerUtil.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientCustomEventsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/stress/RemoteClientPutGetTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/HotRodClientTestingUtil.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/transcoding/DataFormatTest.java
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWithSyncListeners.java
- jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
- spring/spring-boot/remote/src/main/java/org/infinispan/spring/starter/remote/actuator/RemoteInfinispanCacheMeterBinder.java
https://issues.redhat.com/browse/ISPN-13790
> ISPN-13790 Replace RemoteCache#getRemoteCacheManager() with getRemoteCacheContainer()

- core/src/main/java/org/infinispan/commands/control/LockControlCommand.java
- core/src/main/java/org/infinispan/commands/tx/PrepareCommand.java
- core/src/main/java/org/infinispan/commands/tx/VersionedPrepareCommand.java
- core/src/main/java/org/infinispan/context/impl/AbstractTxInvocationContext.java
- core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/AbstractIracLocalSiteInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/InvalidationInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/PessimisticTxIracLocalInterceptor.java
- core/src/main/java/org/infinispan/interceptors/impl/TxInterceptor.java
- core/src/main/java/org/infinispan/interceptors/xsite/PessimisticBackupInterceptor.java
- core/src/main/java/org/infinispan/statetransfer/StateProviderImpl.java
- core/src/main/java/org/infinispan/statetransfer/TransactionInfo.java
- core/src/main/java/org/infinispan/transaction/impl/AbstractCacheTransaction.java
- core/src/main/java/org/infinispan/transaction/impl/LocalTransaction.java
- core/src/main/java/org/infinispan/transaction/impl/ModificationList.java
- core/src/main/java/org/infinispan/transaction/impl/RemoteTransaction.java
- core/src/main/java/org/infinispan/transaction/impl/TransactionTable.java
- core/src/main/java/org/infinispan/transaction/xa/CacheTransaction.java
- core/src/main/java/org/infinispan/transaction/xa/TransactionFactory.java
- core/src/main/java/org/infinispan/transaction/xa/recovery/RecoveryAwareRemoteTransaction.java
- core/src/test/java/org/infinispan/marshall/VersionAwareMarshallerTest.java
- core/src/test/java/org/infinispan/tx/ModificationListUnitTest.java
- hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/TxInvalidationInterceptor.java
https://issues.redhat.com/browse/ISPN-13788
> ISPN-13788 Create ModificationList for transactions

- core/src/main/java/org/infinispan/commands/CommandsFactory.java
- core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
- core/src/main/java/org/infinispan/commands/irac/IracTombstoneCleanupCommand.java
- core/src/main/java/org/infinispan/commands/irac/IracTombstonePrimaryCheckCommand.java
- core/src/main/java/org/infinispan/commands/irac/IracTombstoneRemoteSiteCheckCommand.java
- core/src/main/java/org/infinispan/container/versioning/irac/DefaultIracTombstoneManager.java
- core/src/main/java/org/infinispan/util/concurrent/BlockingManager.java
- core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
- core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
- core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
- core/src/test/java/org/infinispan/xsite/irac/IracTombstoneCleanupTest.java
- core/src/test/java/org/infinispan/xsite/irac/IracTombstoneUnitTest.java
https://issues.redhat.com/browse/ISPN-13496
ps. Added `BlockingManager#thenComposeBlocking` method
> [13.0.x] ISPN-13496 IRAC batch tombstone cleanup command

- commons/all/src/main/java/org/infinispan/commons/configuration/attributes/AttributeSerializer.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/AbstractConfigurationWriter.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationWriter.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/json/JsonConfigurationWriter.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/xml/XmlConfigurationWriter.java
- commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationWriter.java
- core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
- core/src/main/java/org/infinispan/configuration/parsing/Parser.java
- core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java
- core/src/test/resources/configs/all/10.0.xml
- core/src/test/resources/configs/all/10.1.xml
- core/src/test/resources/configs/all/11.0.xml
- core/src/test/resources/configs/all/12.0.xml
- core/src/test/resources/configs/all/12.1.xml
- core/src/test/resources/configs/all/13.0.xml
- server/rest/src/main/java/org/infinispan/rest/configuration/CorsRuleConfiguration.java
https://issues.redhat.com/browse/ISPN-13793
> [13.0] ISPN-13793 Fix parsing/serialization of authorization configs

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13797
> ISPN-13797 Upgrades latests Spring dependencies

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13797
> [13.0.x] ISPN-13797 Upgrades latests Spring dependencies

- server/runtime/src/test/java/org/infinispan/server/license/LicenseTest.java
https://issues.redhat.com/browse/ISPN-13802
> ISPN-13802 Add artifact information in LicenseTest assert error message

- server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
- server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
- server/tests/pom.xml
- server/tests/src/test/java/org/infinispan/server/functional/protobuf/Person.java
- server/tests/src/test/java/org/infinispan/server/functional/protobuf/ProtobufHotRodRestEntityIT.java
- server/tests/src/test/java/org/infinispan/server/functional/protobuf/QuerySchemaBuilder.java
- server/tests/src/test/resources/configuration/BasicServerTest.xml
- server/tests/src/test/resources/configuration/jgroups/none.xml
https://issues.redhat.com/browse/ISPN-13769
> ISPN-13769 Error transcoding Protobuf caches with REST

- query/src/test/java/org/infinispan/query/model/Book.java
- query/src/test/java/org/infinispan/query/parameter/SpecialCharTextTest.java
https://issues.redhat.com/browse/ISPN-13603
There is no issue on the main code base, I'm just adding a test to demonstrate that we support the user's use case.
> ISPN-13603 Special characters escaping for full-text search

- build-configuration/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13812
> [13.0] ISPN-13812 Jackson Databind 2.13.2.2

- build/configuration/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13812
> ISPN-13812 Jackson Databind 2.13.2.2

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13815
> ISPN-13815 Netty 4.1.75

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13817
> ISPN-13817 Protostream 4.4.2.Final

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13818
> ISPN-13818 Nexus Staging 1.6.12

- build/configuration/pom.xml
- core/src/main/resources/default-configs/default-jgroups-azure.xml
- core/src/main/resources/default-configs/default-jgroups-ec2.xml
- core/src/main/resources/default-configs/default-jgroups-google.xml
- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/main/resources/default-configs/default-jgroups-udp.xml
- core/src/test/resources/configs/all/10.0.xml
- core/src/test/resources/configs/all/10.1.xml
- core/src/test/resources/configs/all/11.0.xml
- core/src/test/resources/configs/all/12.0.xml
- core/src/test/resources/configs/all/12.1.xml
- core/src/test/resources/configs/all/13.0.xml
- core/src/test/resources/configs/all/14.0.xml
- documentation/src/main/asciidoc/topics/xml/jgroups_inline_stack.xml
- server/testdriver/junit5/src/test/resources/infinispan.xml
- server/testdriver/junit5/src/test/resources/jgroups/xsite-stacks.xml
- server/tests/src/test/resources/configuration/AuthorizationPropertiesTest.yaml
- server/tests/src/test/resources/configuration/jgroups/authz-stacks.xml
- server/tests/src/test/resources/configuration/jgroups/stacks.xml
- server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml
Replaced FD_ALL with FD_ALL3 in default stacks
https://issues.redhat.com/browse/ISPN-13819
> ISPN-13819 Upgrade JGroups to 4.2.21.Final

- documentation/src/main/asciidoc/stories/assembly_authorization.adoc
- documentation/src/main/asciidoc/stories/assembly_hotrod_clients.adoc
- documentation/src/main/asciidoc/stories/assembly_ports_protocols.adoc
- documentation/src/main/asciidoc/stories/assembly_server_endpoints.adoc
- documentation/src/main/asciidoc/stories/assembly_server_getting_started.adoc
- documentation/src/main/asciidoc/titles/configuring/stories.adoc
- documentation/src/main/asciidoc/titles/security/stories.adoc
- documentation/src/main/asciidoc/topics/con_hotrod_server_compatibility.adoc
- documentation/src/main/asciidoc/topics/con_platforms_automation_tooling.adoc
- documentation/src/main/asciidoc/topics/proc_cli_user_create.adoc
- documentation/src/main/asciidoc/topics/proc_creating_server_security_realms.adoc
- documentation/src/main/asciidoc/topics/ref_server_realm_ldap.adoc
https://issues.redhat.com/browse/ISPN-13795 
> ISPN-13795 docs revision

- server/hotrod/src/main/java/org/infinispan/server/hotrod/KeyValueVersionConverter.java
- spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanApplicationPublishedBridgeTCK.java
https://issues.redhat.com/browse/ISPN-13827
> ISPN-13827 NPE in KeyValueVersionConverter.convert on remove event

- server/hotrod/src/main/java/org/infinispan/server/hotrod/KeyValueVersionConverter.java
- spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanApplicationPublishedBridgeTCK.java
https://issues.redhat.com/browse/ISPN-13827
> [13.0.x] ISPN-13827 NPE in KeyValueVersionConverter.convert on remove event

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/LargeTermTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/QueryLimitTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/KeywordEntity.java
- query/src/main/java/org/infinispan/query/impl/QueryDefinition.java
https://issues.redhat.com/browse/ISPN-13702
> ISPN-13702 ArrayIndexOutOfBoundsException when using indexed field in a query with startOffset=n, maxResults=-1

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/IndexNormalizerTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Book.java
- documentation/src/main/asciidoc/topics/ref_query_default_analyzers.adoc
- query/src/main/java/org/infinispan/search/mapper/mapping/impl/DefaultAnalysisConfigurer.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/FieldReferenceProvider.java
https://issues.redhat.com/browse/ISPN-13816
> ISPN-13816 Allow HotRod client to use normalizers

- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/IndexedFieldProvider.java
- object-filter/src/test/java/org/infinispan/objectfilter/impl/syntax/BooleShannonExpansionTest.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelper.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java
- query/src/test/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelperTest.java
- query/src/test/java/org/infinispan/query/model/Book.java
- query/src/test/java/org/infinispan/query/sort/OrderByTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadata.java
https://issues.redhat.com/browse/ISPN-13820
> ISPN-13820 Hybrid query is performed even if the field is marked as sortable

- core/src/main/java/org/infinispan/persistence/sifs/Compactor.java
- core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
- core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFunctionalTest.java
- core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreStressTest.java
- core/src/test/java/org/infinispan/test/TestBlocking.java
* Clean up compactor issues
https://issues.redhat.com/browse/ISPN-13751
https://issues.redhat.com/browse/ISPN-13799
Note I was unable to reproduce the original issue. However, I have cleaned up the compactor a bit and added a stress test that seems to not fail in the attempts I have done.
> ISPN-13751 ISPN029019 caught when fetching a key from cache

- build/component-processor/src/main/java/org/infinispan/component/processor/external/JGroupsComponentProcessor.java
- core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.redhat.com/browse/ISPN-13836
needs backport to 13.0.x at some point :)
> ISPN-13836 NullPointerException in channelConnected callback

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13818
> [13.0.x] ISPN-13818 Nexus Staging 1.6.12

- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/IndexNoIndexedTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/MultipleIndexFieldAnnotationsTest.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Reviewer.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Revision.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/MessageReferenceProvider.java
https://issues.redhat.com/browse/ISPN-13821
> ISPN-13821 Wrong proto schema will cause put operation failure without clear error message

- server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
- server/rest/src/test/java/org/infinispan/rest/resources/ContainerResourceTest.java
https://issues.redhat.com/browse/ISPN-13791
> ISPN-13791 fixes bounded caches list information

- query/src/test/java/org/infinispan/query/model/Book.java
- query/src/test/java/org/infinispan/query/parameter/FullTextParameterTest.java
- query/src/test/java/org/infinispan/query/parameter/IndexFieldNameTest.java
- query/src/test/java/org/infinispan/query/sort/OrderByTest.java
https://issues.redhat.com/browse/ISPN-13809
basically cannot be reproduced, since it was solved by https://github.com/infinispan/infinispan/pull/10038.
If we want, we can merge this new test.
> ISPN-13809 Test indexed property name change

- core/src/main/resources/schema/infinispan-config-14.0.xsd
- documentation/src/main/asciidoc/topics/con_level_one_caches.adoc
- documentation/src/main/asciidoc/topics/con_server_hinting.adoc
https://issues.redhat.com/browse/ISPN-13746
> ISPN-13746 Server hinting

- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/persistence/jdbc/stringbased/PooledConnectionIT.java
- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/persistence/jdbc/util/JdbcConfigurationUtil.java
- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/persistence/jdbc/util/TableManipulation.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/DB2TableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/OracleTableManager.java
https://issues.redhat.com/browse/ISPN-13844
> ISPN-13844 ClassCastException with Oracle string-keyed-jdbc-store

- cli/src/main/java/org/infinispan/cli/commands/rest/Shutdown.java
- cli/src/main/resources/help/shutdown.adoc
https://issues.redhat.com/browse/ISPN-13849
> ISPN-13849 shutdown cli help text

- core/src/main/resources/schema/infinispan-config-13.0.xsd
- documentation/src/main/asciidoc/topics/con_level_one_caches.adoc
- documentation/src/main/asciidoc/topics/con_server_hinting.adoc
https://issues.redhat.com/browse/ISPN-13746
> [13.0.x] ISPN-13746 server hinting docs updates

- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/persistence/jdbc/stringbased/PooledConnectionIT.java
- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/persistence/jdbc/util/JdbcConfigurationUtil.java
- integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/persistence/jdbc/util/TableManipulation.java
- integrationtests/server-integration/third-party-server/pom.xml
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/persistence/jdbc/stringbased/PooledConnectionDeployIT.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/persistence/jdbc/util/BaseJdbcDeploy.java
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/store/InfinispanStoreJdbcIT.java
- integrationtests/server-integration/third-party-server/src/test/resources/connection.properties
- integrationtests/server-integration/third-party-server/src/test/resources/db2.properties
- integrationtests/server-integration/third-party-server/src/test/resources/h2.properties
- integrationtests/server-integration/third-party-server/src/test/resources/mariadb.properties
- integrationtests/server-integration/third-party-server/src/test/resources/mssql.properties
- integrationtests/server-integration/third-party-server/src/test/resources/mysql.properties
- integrationtests/server-integration/third-party-server/src/test/resources/oracle.properties
- integrationtests/server-integration/third-party-server/src/test/resources/postgresplus.properties
- integrationtests/server-integration/third-party-server/src/test/resources/postgresql.properties
- integrationtests/server-integration/third-party-server/src/test/resources/sybase.properties
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/DB2TableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/OracleTableManager.java
- persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/TableManagerTest.java
- server/tests/src/test/java/org/infinispan/server/persistence/PooledConnectionOperations.java
https://issues.redhat.com/browse/ISPN-13844
> [13.0x.] ISPN-13844 ClassCastException with Oracle string-keyed-jdbc-store

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13852
> [13.0] ISPN-13852 Protostream 4.4.3.Final

- documentation/src/main/asciidoc/topics/con_listening_all_addresses.adoc
- server/hotrod/src/main/java/org/infinispan/server/hotrod/MultiHomedServerAddress.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/InetAddressWithNetMaskTest.java
https://issues.redhat.com/browse/ISPN-13851
> ISPN-13851 Add 240.0.0.0/4 to reserved address in multihomed detection

- core/src/main/java/org/infinispan/persistence/sifs/Index.java
https://issues.redhat.com/browse/ISPN-13854
> ISPN-13854 SoftIndexFileStore may not update index when shutting down

- cli/src/main/java/org/infinispan/cli/commands/rest/Shutdown.java
- cli/src/main/resources/help/shutdown.adoc
Backport for https://issues.redhat.com/browse/ISPN-13849
> [13.0.x] ISPN-13849 shutdown cli help text

- core/src/test/java/org/infinispan/persistence/support/AsyncStoreTest.java
https://issues.redhat.com/browse/ISPN-13855
> ISPN-13855 AsyncStore random failures

- documentation/src/main/asciidoc/topics/con_listening_all_addresses.adoc
- server/hotrod/src/main/java/org/infinispan/server/hotrod/MultiHomedServerAddress.java
- server/hotrod/src/test/java/org/infinispan/server/hotrod/InetAddressWithNetMaskTest.java
https://issues.redhat.com/browse/ISPN-13851
> [13.0.x] ISPN-13851 Add 240.0.0.0/4 to reserved address in multihomed detection

- build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13865
> [13.0.x] SPN-13865 Upgrade Server Web Console to 0.15.5.Final

- core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
- core/src/main/java/org/infinispan/topology/EventLoggerViewListener.java
- core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
- core/src/main/java/org/infinispan/util/logging/events/Messages.java
- server/runtime/src/main/java/org/infinispan/server/logging/events/ServerEventLogger.java
- server/runtime/src/test/java/org/infinispan/server/configuration/ServerEventLoggerTest.java
https://issues.redhat.com/browse/ISPN-13828
Using the `EventLogger` in the `LocalPublisherManagerImpl` to log about
state transfer, when it starts and when it ends.
> ISPN-13828 EventLogger for finished rebalance

- distribution/pom.xml
- documentation/pom.xml
- javadoc/pom.xml
- pom.xml
* Added property rsync.failonerror to disable this behavior if necessary
> Fail build is rsync if unable to upload files

- documentation/src/main/asciidoc/js/js.js
@tristantarrant I forgot 13 was protected but here's the drop-down backport.
> [13.0.x] Add a docs index dropdown (#10083)

- integrationtests/server-integration/third-party-server/pom.xml
- integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/persistence/jdbc/util/BaseJdbcDeploy.java
https://issues.redhat.com/browse/ISPN-13606
> [13.0.x] ISPN-13606 Fix PooledConnectionDeployIT

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13868
> ISPN-13868 Lucene 8.11.1

- build/configuration/pom.xml
- core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java
- core/src/main/java/org/infinispan/container/impl/BoundedSegmentedDataContainer.java
- core/src/main/java/org/infinispan/container/impl/DefaultDataContainer.java
https://issues.redhat.com/browse/ISPN-13857
> ISPN-13857 Update Caffeine to 2.9.3

- core/src/test/java/org/infinispan/xsite/XSiteCacheConfigurationTest.java
* Fix failing tests
https://issues.redhat.com/browse/ISPN-13593
> ISPN-13593 Docs: Cross-site log messages

- commons/all/src/main/java/org/infinispan/counter/exception/CounterNotFoundException.java
- core/src/main/java/org/infinispan/util/concurrent/CompletionStages.java
- counter/src/main/java/org/infinispan/counter/impl/Util.java
- counter/src/main/java/org/infinispan/counter/impl/factory/CacheBasedStrongCounterFactory.java
- counter/src/main/java/org/infinispan/counter/impl/factory/CacheBasedWeakCounterFactory.java
- counter/src/main/java/org/infinispan/counter/impl/factory/StrongCounterFactory.java
- counter/src/main/java/org/infinispan/counter/impl/factory/WeakCounterFactory.java
- counter/src/main/java/org/infinispan/counter/impl/listener/CounterManagerNotificationManager.java
- counter/src/main/java/org/infinispan/counter/impl/manager/EmbeddedCounterManager.java
- counter/src/main/java/org/infinispan/counter/impl/manager/InternalCounterAdmin.java
- counter/src/main/java/org/infinispan/counter/impl/strong/AbstractStrongCounter.java
- counter/src/main/java/org/infinispan/counter/impl/weak/WeakCounterImpl.java
- counter/src/main/java/org/infinispan/counter/logging/Log.java
- server/hotrod/src/main/java/org/infinispan/server/hotrod/CounterRequestProcessor.java
- server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java
- server/rest/src/main/java/org/infinispan/rest/resources/ResourceUtil.java
https://issues.redhat.com/browse/ISPN-13835
> ISPN-13835 Non blocking methods for EmbeddedCounterManager

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13879
> ISPN-13879 Bump RocksDB 7.1.2

- build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13878
> ISPN-13878 Bump Maven Surefire 3.0.0-M6

- core/src/test/java/org/infinispan/partitionhandling/ScatteredCrashInSequenceTest.java
- core/src/test/java/org/infinispan/remoting/inboundhandler/BlockingInboundInvocationHandler.java
* Block RebalanceStartCommand only for default cache
* Do not block the thread in BlockingInboundInvocationHandler
https://issues.redhat.com/browse/ISPN-13876
> ISPN-13876 Fix ScatteredCrashInSequenceTest random failures

- cli/src/main/java/org/infinispan/cli/commands/rest/Server.java
- cli/src/main/resources/help/server.adoc
- client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java
- client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestServerClientOkHttp.java
- commons/all/src/main/java/org/infinispan/commons/util/JVMMemoryInfoInfo.java
- documentation/src/main/asciidoc/topics/ref_rest_servers.adoc
- server/core/src/main/java/org/infinispan/server/core/ServerManagement.java
- server/core/src/test/java/org/infinispan/server/core/DummyServerManagement.java
- server/rest/src/main/java/org/infinispan/rest/logging/Log.java
- server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-13794
> ISPN-13794 Heap Dump REST API

- documentation/src/main/asciidoc/titles/contributing/contributing.asciidoc
- documentation/src/main/asciidoc/titles/developing/developing.asciidoc
- documentation/src/main/asciidoc/titles/embedding/embedding.asciidoc
- documentation/src/main/asciidoc/titles/encoding/encoding.asciidoc
- documentation/src/main/asciidoc/titles/getting_started/getting_started.asciidoc
- documentation/src/main/asciidoc/titles/hibernate/hibernate.asciidoc
- documentation/src/main/asciidoc/titles/hotrod_java/hotrod_java.asciidoc
- documentation/src/main/asciidoc/titles/hotrod_protocol/hotrod_protocol.asciidoc
- documentation/src/main/asciidoc/titles/memcached/memcached.asciidoc
- documentation/src/main/asciidoc/titles/query/query.asciidoc
- documentation/src/main/asciidoc/titles/resp/resp-endpoint.asciidoc
- documentation/src/main/asciidoc/titles/rest/rest.asciidoc
- documentation/src/main/asciidoc/titles/security/security.asciidoc
- documentation/src/main/asciidoc/titles/spring/spring.asciidoc
- documentation/src/main/asciidoc/titles/spring_boot/starter.asciidoc
- documentation/src/main/asciidoc/titles/tuning/tuning.asciidoc
- documentation/src/main/asciidoc/titles/upgrading/upgrading.asciidoc
- documentation/src/main/asciidoc/titles/xsite/xsite.asciidoc
https://issues.redhat.com/browse/ISPN-13887
Needs backport to 13.0.x.
> ISPN-13887 add title context

- build/configuration/pom.xml
- hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/CacheKeySerializationTest.java
https://issues.redhat.com/browse/ISPN-13886
> ISPN-13886 Update Hibernate to 6.0.1

- documentation/src/main/asciidoc/titles/contributing/contributing.asciidoc
- documentation/src/main/asciidoc/titles/developing/developing.asciidoc
- documentation/src/main/asciidoc/titles/embedding/embedding.asciidoc
- documentation/src/main/asciidoc/titles/encoding/encoding.asciidoc
- documentation/src/main/asciidoc/titles/getting_started/getting_started.asciidoc
- documentation/src/main/asciidoc/titles/hibernate/hibernate.asciidoc
- documentation/src/main/asciidoc/titles/hotrod_java/hotrod_java.asciidoc
- documentation/src/main/asciidoc/titles/hotrod_protocol/hotrod_protocol.asciidoc
- documentation/src/main/asciidoc/titles/memcached/memcached.asciidoc
- documentation/src/main/asciidoc/titles/query/query.asciidoc
- documentation/src/main/asciidoc/titles/rest/rest.asciidoc
- documentation/src/main/asciidoc/titles/security/security.asciidoc
- documentation/src/main/asciidoc/titles/spring/spring.asciidoc
- documentation/src/main/asciidoc/titles/spring_boot/starter.asciidoc
- documentation/src/main/asciidoc/titles/tuning/tuning.asciidoc
- documentation/src/main/asciidoc/titles/upgrading/upgrading.asciidoc
- documentation/src/main/asciidoc/titles/xsite/xsite.asciidoc
https://issues.redhat.com/browse/ISPN-13887
> [13.0.x] ISPN-13887 add title context

- build/configuration/pom.xml
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Reviewer.java
- client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Revision.java
- documentation/src/main/asciidoc/topics/code_examples/AnalyzerDefinitions.java
- documentation/src/main/asciidoc/topics/code_examples/BookIndexed.java
- documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc
- documentation/src/main/asciidoc/topics/proc_query_querying_hot_rod.adoc
- documentation/src/main/asciidoc/topics/ref_protostream_annotations.adoc
- documentation/src/main/asciidoc/topics/upgrading.adoc
- integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/CryptoCurrency.java
- query/src/test/java/org/infinispan/query/dsl/embedded/testdomain/hsearch/TransactionHS.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadata.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadata.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadataCreator.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/GlobalReferenceHolder.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/MessageReferenceProvider.java
https://issues.redhat.com/browse/ISPN-13861
> ISPN-13861 Support bare protobuf annotations

- distribution/pom.xml
- tools/src/main/java/org/infinispan/tools/xsd/XSDoc.java
* Skip rendering jdbc-common to HTML
https://issues.redhat.com/browse/ISPN-13888
> ISPN-13888 configdocs: jdbc-common is empty

- distribution/pom.xml
- tools/src/main/java/org/infinispan/tools/xsd/XSDoc.java
* Skip rendering jdbc-common to HTML
https://issues.redhat.com/browse/ISPN-13888
> [13.0.x] ISPN-13888 configdocs: jdbc-common is empty

- integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/embedded/EmbeddedProtostreamSpringSessionTest.java
- integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/embedded/EmbeddedSpringSessionTest.java
- integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/remote/RemoteSpringSessionTest.java
- spring/spring-boot/tests/src/test/java/test/infinispan/autoconfigure/CacheDisabledTest.java
- spring/spring-boot/tests/src/test/java/test/infinispan/autoconfigure/CacheManagerTest.java
https://issues.redhat.com/browse/ISPN-13906
Other tests the banner is already disabled.
> ISPN-13906 Disable Spring banner in tests

- distribution/pom.xml
- documentation/pom.xml
- javadoc/pom.xml
- pom.xml
* Added property rsync.failonerror to disable this behavior if necessary
> [13.0.x] Fail build if rsync is unable to upload files

- documentation/src/main/asciidoc/stories/assembly_hotrod_client_api.adoc
- documentation/src/main/asciidoc/topics/code_examples/MultimapCacheManagerRemote.java
- documentation/src/main/asciidoc/topics/hotrod_protocol.adoc
- documentation/src/main/asciidoc/topics/ref_hotrod_multimapcachemanager.adoc
https://issues.jboss.org/browse/ISPN-8874
> ISPN-8874 Document multimap remote interface and protocol

- documentation/src/main/asciidoc/topics/json/infinispan_caches.json
- documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc
- documentation/src/main/asciidoc/topics/xml/infinispan_caches.xml
- documentation/src/main/asciidoc/topics/yaml/infinispan_caches.yaml
https://issues.redhat.com/browse/ISPN-13901
Add examples of custom configuration templates and multiple caches configuration to the Configuring Infinispan caches
> ISPN-13901 add cache config examples to the config guide

- persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/logging/Log.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
* Delete rows when updating metadata
https://issues.redhat.com/browse/ISPN-13440
> ISPN-13440 JDBC meta Data table is filled on every startup

- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/logging/Log.java
- persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
* Delete rows when updating metadata
https://issues.redhat.com/browse/ISPN-13440
> [12.1.x] ISPN-13440 JDBC meta Data table is filled on every startup

- documentation/src/main/asciidoc/topics/json/infinispan_caches.json
- documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc
- documentation/src/main/asciidoc/topics/xml/infinispan_caches.xml
- documentation/src/main/asciidoc/topics/yaml/infinispan_caches.yaml
https://issues.redhat.com/browse/ISPN-13901
backports https://github.com/infinispan/infinispan/pull/10132
> [13.0.x]ISPN-13901 add multiple caches config examples to configuring doc

- core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java
- core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java
- core/src/test/resources/configs/all/14.0.xml
https://issues.redhat.com/browse/ISPN-13902
> ISPN-13902 HashConfiguration not serialized for replicated caches

- object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/IndexedFieldProvider.java
- object-filter/src/test/java/org/infinispan/objectfilter/impl/syntax/BooleShannonExpansionTest.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelper.java
- query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java
- query/src/test/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelperTest.java
- query/src/test/java/org/infinispan/query/model/Book.java
- query/src/test/java/org/infinispan/query/sort/OrderByTest.java
- remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadata.java
https://issues.redhat.com/browse/ISPN-13820
Backport of https://github.com/infinispan/infinispan/pull/10038
> [13.0.x] ISPN-13820 Hybrid query is performed even if the field is marked as sortable

- core/src/main/resources/default-configs/default-jgroups-azure.xml
- core/src/main/resources/default-configs/default-jgroups-ec2.xml
- core/src/main/resources/default-configs/default-jgroups-google.xml
- core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
- core/src/main/resources/default-configs/default-jgroups-tcp.xml
- core/src/main/resources/default-configs/default-jgroups-udp.xml
- documentation/src/main/asciidoc/topics/ref_jgroups_system_properties.adoc
- server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
- server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-12531
> ISPN-12531 Set default FD_SOCK ports and apply offset to them

- build/configuration/pom.xml
- core/src/main/java/org/infinispan/container/impl/PeekableTouchableCaffeineMap.java
https://issues.redhat.com/browse/ISPN-13924
> ISPN-13924 Update Caffeine to 3.1

- core/src/main/resources/schema/infinispan-config-14.0.xsd
https://issues.redhat.com/browse/ISPN-13780
> ISPN-13780 Remove `fetch-state` from XSD

- api/pom.xml
https://issues.redhat.com/browse/ISPN-13927
> Deploy infinispan-api module

- javadoc/pom.xml
Fix javadoc
https://issues.redhat.com/browse/ISPN-13615
> ISPN-13615 Create RAFT abstraction

- api/src/main/java/org/infinispan/api/async/AsyncCache.java
- api/src/main/java/org/infinispan/api/common/CloseableIterable.java
- api/src/main/java/org/infinispan/api/common/process/CacheEntryProcessorResult.java
- api/src/main/java/org/infinispan/api/mutiny/MutinyCache.java
- api/src/main/java/org/infinispan/api/sync/SyncCache.java
- client/hotrod/src/main/java/org/infinispan/hotrod/HotRodAsyncCache.java
- client/hotrod/src/main/java/org/infinispan/hotrod/HotRodMutinyCache.java
- client/hotrod/src/main/java/org/infinispan/hotrod/HotRodSyncCache.java
- client/hotrod/src/main/java/org/infinispan/hotrod/MutinyToAsyncCacheEntryProcessor.java
- client/hotrod/src/main/java/org/infinispan/hotrod/SyncToAsyncEntryProcessor.java
- client/hotrod/src/main/java/org/infinispan/hotrod/impl/cache/DelegatingRemoteCache.java
- client/hotrod/src/main/java/org/infinispan/hotrod/impl/cache/RemoteCache.java
- client/hotrod/src/main/java/org/infinispan/hotrod/impl/cache/RemoteCacheImpl.java
* Ensure getAndRemoveAll present on all interfaces
* Rework process methods
* Modify CloseableIterable to not be Closeable itself
* Ensure remove operations use WriteOperations
* Make sure MutinyCache operations are all lazy
> ISPN-9893 API 2.0

- documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc
https://issues.redhat.com/browse/ISPN-13938
> ISPN-13938 remove JMX system props

- cli/src/main/java/org/infinispan/cli/commands/kubernetes/Create.java
https://issues.redhat.com/browse/ISPN-13936
> ISPN-13936 CLI Add version option when creating Infinispan cluster
