core/src/test/java/org/infinispan/statetransfer/ClusterTopologyManagerTest.java
https://issues.redhat.com/browse/ISPN-12537
=> ClusterTopologyManagerTest - ERROR Unable to format msg: Starting with topology %d

documentation/src/main/asciidoc/topics/con_xsite_expiration.adoc
https://issues.redhat.com/browse/ISPN-12437
=> ISPN-12437 xsite max idle

server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/testdriver/core/src/main/resources/testcontainers.properties
https://issues.redhat.com/browse/ISPN-12524
@tristantarrant Looks like I missed an image. `jboss/base-jdk` isn't available on quay.io, so this seems like a good opportunity to move to the ubi image.
=> ISPN-12524 Utilise ubi java image

core/src/main/java/org/infinispan/interceptors/locking/AbstractLockingInterceptor.java, core/src/main/java/org/infinispan/interceptors/locking/NonTransactionalLockingInterceptor.java, core/src/test/java/org/infinispan/invalidation/NonTxInvalidationLockingTest.java, core/src/test/java/org/infinispan/invalidation/TxInvalidationLockingTest.java
https://issues.redhat.com/browse/ISPN-12489
InvalidateCommand should not acquire the key lock on remote nodes.
=> ISPN-12489 Non-transactional INVALIDATION_SYNC cache deadlock

server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java, server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java, server/rest/src/test/java/org/infinispan/rest/resources/StaticResourceTest.java
https://issues.redhat.com/browse/ISPN-12558
Ignore the IllegalStateException from OpenSSLEngine
in RestRequestHandler and avoid the StackOverflowError.
=> ISPN-12558 StackOverflowError during REST connection shutdown

query/src/main/java/org/infinispan/query/internal/QueryBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-12559
Ignore file reads in NamedSPILoader, which is a re-implementation
of java.util.ServiceLoader.
=> ISPN-12559 SearchAdminResource.searchStats blocking call

server/rest/src/test/java/org/infinispan/rest/assertion/JsonAssertion.java, server/rest/src/test/java/org/infinispan/rest/assertion/ResponseAssertion.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-12561
Check the response body contents.
Reading the body automatically closes the response.
=> ISPN-12561 CacheV2ResourceTest does not close RestClient responses

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConnectionPoolConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/NearCacheConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/AvoidStaleNearCacheReadsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/ClusterInvalidatedNearCacheBloomTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/EvictInvalidatedNearCacheTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedFailoverNearCacheBloomTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedNearCacheBloomTest.java, documentation/src/main/asciidoc/topics/proc_configuring_hotrod_nearcaching.adoc
* Limit pool configuration to 1 per server when bloom filter is enabled
https://issues.redhat.com/browse/ISPN-10216
=> ISPN-10216 Implement bloom filter based near cache invalidations

core/src/main/java/org/infinispan/commands/remote/ClusteredGetCommand.java, core/src/main/java/org/infinispan/commands/triangle/BackupWriteCommand.java, core/src/main/java/org/infinispan/container/impl/EntryFactory.java, core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java, core/src/main/java/org/infinispan/context/Flag.java, core/src/main/java/org/infinispan/context/impl/FlagBitSets.java, core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java, core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationFunctionalTest.java
https://issues.redhat.com/browse/ISPN-12518
https://issues.redhat.com/browse/ISPN-12337
Also includes ISPN-12337 which prevents a deadlock with pessimistic tx with clustered expiration.
=> [11.0.x] ISPN-12518 Possible deadlock if an entry is replaced at the same time expiration take effect

server/core/src/main/java/org/infinispan/server/core/logging/Log.java, server/core/src/main/java/org/infinispan/server/core/transport/NettyTransport.java
https://issues.redhat.com/browse/ISPN-12570
Do not try to close channels explicitly.
Only check that shutting down the event loop groups
also closed the channels.
Might be superseded by https://github.com/infinispan/infinispan/pull/8885, but I opened it so I can trigger a build in CI and verify that the channels are indeed closed.
=> ISPN-12570 REST server stop hangs when channel is open

documentation/src/main/asciidoc/topics/con_server_directory_structure.adoc, server/runtime/src/main/server/README.adoc
https://issues.redhat.com/browse/ISPN-12599
=> [11.0.x] ISPN-12599 server home and root properties

documentation/src/main/asciidoc/topics/upgrading.adoc, query/src/main/java/org/infinispan/query/impl/LifecycleManager.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java, server/tests/src/test/java/org/infinispan/server/functional/ClusteredIT.java
https://issues.redhat.com/browse/ISPN-12564
Should fix ```HotRodCacheQueries``` failures.
=> ISPN-12564 Remove support for property "infinispan.query.lucene.max-boolean-clauses" from the index config

documentation/src/main/asciidoc/topics/ref_rest_logging.adoc
Backport of https://issues.redhat.com/browse/ISPN-12573
Examples for REST API Server logging configuration are wrong
Fixes confusing eamples
=> [11.0.x] ISPN-12573 small correction of REST API request in documentation

core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java, core/src/main/java/org/infinispan/reactive/publisher/impl/PartitionAwareClusterPublisherManager.java, core/src/test/java/org/infinispan/stream/DenyReadWritesStreamTest.java
https://issues.redhat.com/browse/ISPN-12594
Use UnicastProcessor instead of PublishProcessor,
as PublishProcessor starts emitting items too early
(before its subscribers call request()).
=> ISPN-12594 Exception in cache streams with DENY_READ_WRITES

core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java, core/src/main/java/org/infinispan/reactive/publisher/impl/PartitionAwareClusterPublisherManager.java, core/src/test/java/org/infinispan/stream/DenyReadWritesStreamTest.java
https://issues.redhat.com/browse/ISPN-12594
https://issues.redhat.com/browse/JDG-4262
Use UnicastProcessor instead of PublishProcessor,
as PublishProcessor starts emitting items too early
(before its subscribers call request()).
=> [11.0.x] ISPN-12594 Exception in cache streams with DENY_READ_WRITES

core/src/main/java/org/infinispan/configuration/cache/IndexMergeConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/IndexReaderConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/IndexWriterConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/IndexingConfigurationBuilder.java, core/src/main/java/org/infinispan/util/logging/Log.java, query/src/main/java/org/infinispan/query/impl/LifecycleManager.java, query/src/main/java/org/infinispan/query/impl/config/SearchPropertyExtractor.java, query/src/test/java/org/infinispan/query/config/EngineConfigTest.java, query/src/test/java/org/infinispan/query/config/IndexingConfigurationIgnoredTest.java, query/src/test/java/org/infinispan/query/config/ProgrammaticAutoConfigTest.java, query/src/test/java/org/infinispan/query/config/QueryParsingTest.java
https://issues.redhat.com/browse/ISPN-12535
Avoids adding properties to ```IndexingConfigurationBuilder``` since they are deprecated: all config should be done via schema based elements. This will silence multiple WARN when an indexed cache is created, even if the user hasn't explicitly used properties
=> ISPN-12535 Fix WARN messages org.hibernate.search

persistence/remote/pom.xml, persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java, persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/MigrationTask.java, persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/CustomObject.java, persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeEncodingsTest.java, persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradePojoTest.java, persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/SerializationCtx.java, persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/TestCluster.java, server/tests/src/test/java/org/infinispan/server/functional/RollingUpgradeIT.java
https://issues.redhat.com/browse/ISPN-12616
Forward port from 11.0.x
=> ISPN-12616 Rolling Upgrade fails for caches storing POJOs

core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java, core/src/main/java/org/infinispan/xsite/irac/IracManager.java, core/src/main/java/org/infinispan/xsite/irac/NoOpIracManager.java, core/src/main/java/org/infinispan/xsite/statetransfer/AsyncProviderState.java, core/src/main/java/org/infinispan/xsite/statetransfer/BaseXSiteStateProviderState.java, core/src/main/java/org/infinispan/xsite/statetransfer/NoOpXSiteStateProvider.java, core/src/main/java/org/infinispan/xsite/statetransfer/RemoteSiteStatus.java, core/src/main/java/org/infinispan/xsite/statetransfer/SyncProviderState.java, core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateProvider.java, core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateProviderImpl.java, core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateProviderState.java, core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferManagerImpl.java, core/src/test/java/org/infinispan/xsite/irac/ControlledIracManager.java, core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java, core/src/test/java/org/infinispan/xsite/irac/statetransfer/IracStateTransferTest.java, core/src/test/java/org/infinispan/xsite/statetransfer/XSiteProviderDelegator.java
depens on  https://github.com/infinispan/infinispan/pull/8940
https://issues.redhat.com/browse/ISPN-12476
=> ISPN-12476 Enable conflict resolution for IRAC state transfer

cloudevents-integration/pom.xml, cloudevents-integration/src/test/java/org/infinispan/cloudevents/MockKafkaEventSender.java
https://issues.redhat.com/browse/ISPN-12651
* Make jackson-core a required dependency of cloudevents-integration.
* Cache history list in test to avoid ConcurrentModificationException.
=> ISPN-12651 CacheEntryCloudEventsTest test failures

core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHash.java, core/src/test/java/org/infinispan/globalstate/GlobalStateBackwardsCompatibilityTest.java
https://issues.redhat.com/browse/ISPN-12667
Backport: https://github.com/infinispan/infinispan/pull/9020
=> ISPN-12667 GlobalState incompatibility between 11.x and 12.x

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/ReplicationIndexTest.java, core/src/main/java/org/infinispan/container/impl/AbstractDelegatingInternalDataContainer.java, core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java, core/src/main/java/org/infinispan/factories/InternalCacheFactory.java, core/src/main/java/org/infinispan/factories/TransactionManagerFactory.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ObjectRemoteQueryManager.java
https://issues.redhat.com/browse/ISPN-12666
Follows up on #9021 
Add a new AbstractComponentRegistry.wireDependencies() overload
to not start injected component.
Use the new overload in components, and keep using the old overload in
external classes like commands, converters, filters, etc.
=> ISPN-12666 ReplicationIndexTest random failures

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/tcp/RoundRobinBalancingStrategy.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/multimap/RemoteMultimapCacheAPITest.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/MultimapRequestProcessor.java
https://issues.redhat.com/browse/ISPN-12596
When the server sends a KeyDoesNotExist response, it also includes
an empty collection of values.
Also includes a partial fix for https://issues.redhat.com/browse/ISPN-12598
=> ISPN-12596 Incorrect Hotrod Multimap get KeyDoesNotExist response 

spring/spring-boot/embedded/src/main/java/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfiguration.java, spring/spring-boot/embedded/src/test/java/test/org/infinispan/spring/starter/embedded/InfinispanEmbeddedAutoConfigurationPropertiesTest.java
https://issues.redhat.com/browse/ISPN-12584
Make JavaSerializationMarshaller the default marshaller even when
the configXml property is present.
Users can still change it if they want protostream marshalling
and they aren't storing Spring sessions in the cache.
=> ISPN-12584 Protobuf serialization in library mode with spring starter

cli/src/main/java/org/infinispan/cli/commands/rest/Site.java, cli/src/main/java/org/infinispan/cli/connection/Connection.java, cli/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java, cli/src/main/resources/help/site.adoc, core/src/main/java/org/infinispan/manager/CacheManagerInfo.java, documentation/src/main/asciidoc/topics/json_examples/rest_cache_manager_response.json, documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc, server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java, server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java, server/tests/src/test/java/org/infinispan/server/cli/XSiteCliOperations.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java
https://issues.redhat.com/browse/ISPN-12622
=> ISPN-12622 Expose Cross-Site Views via CLI and REST endpoint

cloudevents-integration/pom.xml, cloudevents-integration/src/test/java/org/infinispan/cloudevents/MockKafkaEventSender.java
https://issues.redhat.com/browse/ISPN-12651
* Make jackson-core a required dependency of cloudevents-integration.
* Cache history list in test to avoid ConcurrentModificationException.
=> [12.0.x] ISPN-12651 CacheEntryCloudEventsTest test failures

core/src/test/java/org/infinispan/reactive/RxJavaPublisherTest.java, core/src/test/java/org/infinispan/util/CoreTestBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-11873
Reviving https://github.com/infinispan/infinispan/pull/8356, only without the `while` loop we were discussing in the comments.
=> ISPN-11873 Add report failure for RxJava Undelivered Errors

build-configuration/pom.xml, persistence/soft-index/pom.xml, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/FileProvider.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/SoftIndexFileStore.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/pmem/PmemUtilWrapper.java, pom.xml, tools/src/main/java/org/infinispan/tools/store/migrator/file/SoftIndexFileStoreIterator.java
https://issues.redhat.com/browse/ISPN-12728
This adds in support for persistent memory usage. The mashona library will only return a non null FileChannel if it was able to allocate it with persistent memory. In the case it is null we just fall back to the prior code as normal.
Unfortunately, there is no way to test this currently. However, Jonathan Halliday tested this before. We may need to discuss further with him how we can properly test this long term though.
=> ISPN-12728 Add Persistent Memory to Soft Index File Store

core/src/main/java/org/infinispan/stream/impl/DistributedCacheStream.java, core/src/test/java/org/infinispan/stream/DistributedStreamIteratorRepeatableReadTxTest.java
https://issues.redhat.com/browse/ISPN-12731
ClusterPublisherManager needs a reference to the invocation context
in order to iterate over the entries in it.
=> ISPN-12731 Cache collections and streams ignore values added in transaction

spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/session/AbstractInfinispanSessionRepository.java, spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/session/PrincipalNameResolver.java, spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanSessionRepositoryTCK.java, spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepository.java, spring/spring5/spring5-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepositoryTest.java, spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepository.java
https://issues.redhat.com/browse/ISPN-12739
https://issues.redhat.com/browse/ISPN-12751
Fixes `ConcurrentModificationException` during session serialization.
Includes fix for ISPN-12751 InfinispanEmbeddedSessionRepository.findByIndexNameAndIndexValue() fails in distributed cache
=> ISPN-12739 Spring Session Repository should copy the MapSession for each request

core/src/main/java/org/infinispan/conflict/impl/DefaultConflictManager.java, core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/conflict/impl/BaseMergePolicyTest.java, core/src/test/java/org/infinispan/conflict/impl/TxConflictResolutionTest.java, core/src/test/java/org/infinispan/partitionhandling/BasePartitionHandlingTest.java, query-core/src/main/java/org/infinispan/query/core/impl/eventfilter/IckleFilterAndConverter.java
https://issues.redhat.com/browse/ISPN-12725
https://issues.redhat.com/browse/ISPN-12715
https://issues.redhat.com/browse/ISPN-12717
ISPN-12725 Conflict resolution fails in transactional cache with auto-commit disabled
ISPN-12715 Conflict resolution failure logged at debug level
ISPN-12717 DefaultConflictManager.getAllVersions fails in tx caches
=> ISPN-12725 Conflict resolution fails in transactional cache with auto-commit disabled

documentation/src/main/asciidoc/topics/ref_cache_modes_comparison.adoc
https://issues.redhat.com/browse/ISPN-12769 
Needs backport to 12.0.x and 11.0.x.
=> ISPN-12769 no indexing with invalidation caches

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfigurationBuilder.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheCreateOnAccessTest.java, commons/all/pom.xml, commons/all/src/main/java/org/infinispan/commons/util/ClasspathURLStreamHandler.java, commons/jdk11/pom.xml, commons/jdk11/src/main/java/org/infinispan/commons/jdkspecific/ClasspathURLStreamHandlerProvider.java
https://issues.redhat.com/browse/ISPN-12763
=> ISPN-12763 Load configuration URIs from classpath

core/src/main/java/org/infinispan/conflict/impl/DefaultConflictManager.java, core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/conflict/impl/BaseMergePolicyTest.java, core/src/test/java/org/infinispan/conflict/impl/TxConflictResolutionTest.java, core/src/test/java/org/infinispan/partitionhandling/BasePartitionHandlingTest.java, query-core/src/main/java/org/infinispan/query/core/impl/eventfilter/IckleFilterAndConverter.java
Backport of https://github.com/infinispan/infinispan/pull/9051
https://issues.redhat.com/browse/ISPN-12725
https://issues.redhat.com/browse/ISPN-12715
https://issues.redhat.com/browse/ISPN-12717
ISPN-12725 Conflict resolution fails in transactional cache with auto-commit disabled
ISPN-12715 Conflict resolution failure logged at debug level
ISPN-12717 DefaultConflictManager.getAllVersions fails in tx caches
=> [11.0.x] ISPN-12725 Conflict resolution fails in transactional cache with auto-commit disabled

core/src/main/java/org/infinispan/eviction/impl/EvictionManagerImpl.java, core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java, core/src/main/java/org/infinispan/stats/impl/StatsCollector.java, core/src/test/java/org/infinispan/api/SimpleCacheTest.java
https://issues.redhat.com/browse/ISPN-12807
https://issues.redhat.com/browse/ISPN-9901
EvictionManagerImpl must work with both CacheMgmtInterceptor
(regular cache) and StatsCollector (simple cache).
Backport of #9103
=> [9.4.x] ISPN-12807 Simple cache does not update eviction statistics

core/src/main/java/org/infinispan/eviction/impl/EvictionManagerImpl.java, core/src/main/java/org/infinispan/stats/impl/StatsCollector.java, core/src/test/java/org/infinispan/api/SimpleCacheTest.java
https://issues.redhat.com/browse/ISPN-12807
EvictionManagerImpl must work with both CacheMgmtInterceptor
(regular cache) and StatsCollector (simple cache).
=> ISPN-12807 Simple cache does not update eviction statistics

core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
https://issues.redhat.com/browse/ISPN-12806
=> ISPN-128806 BlockingManagerImpl#thenRunBlocking doesn't join

build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-12682
Upgrade org.owasp:dependency-check-maven to version 6.1.0.
It should at least improve the error reporting.
=> ISPN-12682 dependency-check-maven plugin fails CI builds

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/DataFormat.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfiguration.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/DelegatingRemoteCache.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InternalRemoteCache.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemotePublisher.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/MarshallerPerCacheTest.java, client/hotrod-client/src/test/resources/hotrod-client-percache.properties
https://issues.redhat.com/browse/ISPN-12808
The implementation is simpler that what was proposed in the JIRA: it only allows a marshaller to be configured per cache, instead of the full ```DataFormat```. This is enough for the Spring use cases.
=> ISPN-12808 Per-cache Hot Rod client marshaller

core/src/main/java/org/infinispan/eviction/impl/EvictionManagerImpl.java, core/src/main/java/org/infinispan/stats/impl/StatsCollector.java, core/src/test/java/org/infinispan/api/SimpleCacheTest.java
https://issues.redhat.com/browse/ISPN-12807
EvictionManagerImpl must work with both CacheMgmtInterceptor
(regular cache) and StatsCollector (simple cache).
Backport of #9103, as requested by @pferraro
=> [11.0.x] ISPN-12807 Simple cache does not update eviction statistics

core/src/main/java/org/infinispan/container/entries/VersionedRepeatableReadEntry.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/main/java/org/infinispan/transaction/impl/WriteSkewHelper.java, persistence/remote/src/main/java/org/infinispan/persistence/remote/ExternalizerIds.java, persistence/remote/src/main/java/org/infinispan/persistence/remote/LifecycleCallbacks.java, persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/MigrationTask.java, persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradePojoTest.java, persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/TestCluster.java
https://issues.redhat.com/browse/ISPN-12646
Forward port from https://github.com/infinispan/infinispan/pull/9007
=> ISPN-12646 IllegalArgumentException when doing Rolling Upgrades on transactional caches

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/ExecuteOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ServerErrorTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
https://issues.redhat.com/browse/ISPN-12801
* Cancel the timeout future on completeExceptionally().
* Add a test for cache creation failure.
* Improve logging for admin and execute operations.
=> ISPN-12801 Hot Rod client logs a timeout error after every server error

persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/LogAppender.java, persistence/soft-index/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreParallelIterationTest.java
sync flush
https://issues.redhat.com/browse/ISPN-12847
The new changes are that when sync flush is enabled are as follows. When a write operation is performed it will write the value to "disk". After this completes the thread will then check if the log appender has written all requested values and if so will immediately flush the value to disk. If not then the log write will wait until it is eventually flushed. To prevent too many operations from waiting we will flush after 1000 unflushed entries. This provides some back pressure, to ensure previous tasks finish. This approach doesn't require a time out or anything and should provided the lowest latency while also not flushing per entry.
=> ISPN-12847 Performance regression in new SIFS write performance with

spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanSessionRepositoryTCK.java, spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/SpringEmbeddedModule.java, spring/spring5/spring5-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepositoryTest.java, spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManager.java, spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheTest.java, spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepositoryTest.java
https://issues.redhat.com/browse/ISPN-12690
https://issues.redhat.com/browse/ISPN-12689
* Register provider and session marshallers in ProtoStreamMarshaller's
serialization context
* Register a JavaSerializationMarshaller if it doesn't exist yet,
for session attributes that cannot be serialized with protostream
* Add NullValue, java.util, and org.springframework classes
to the allow list when wrapping a remote cache manager.
=> ISPN-12689 + ISPN-12690 Support spring caches and session in remote mode with protostream

persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/Compactor.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/Index.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/IndexNode.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/LogAppender.java
This PR doesn't increase throughput as the latency of the log appender is more important. This reduces CPU and disk usage with heavy replacements of values and compaction so it does more targeted replacements. In benchmark tests this completely removes the https://github.com/infinispan/infinispan/pull/9150#issuecomment-800821579 from the hotspot in JMC.
Also this fixes an issue with the compactor that it can run tasks from the indexer thread, which is not desired.
=> ISPN-12856 SoftIndexFileStore some index updates write too much to disk

core/src/main/java/org/infinispan/configuration/global/GlobalAuthorizationConfiguration.java, core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/main/java/org/infinispan/security/AuthorizationPermission.java, core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java, core/src/test/java/org/infinispan/security/CacheManagerAuthorizationTest.java, core/src/test/java/org/infinispan/security/SecureCacheTestDriver.java, core/src/test/java/org/infinispan/security/TestCachePermission.java, documentation/src/main/asciidoc/topics/ref_authz_default_roles.adoc, documentation/src/main/asciidoc/topics/ref_authz_permissions.adoc, server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestUser.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java, server/tests/src/test/resources/ldif/infinispan-kerberos.ldif, server/tests/src/test/resources/ldif/infinispan.ldif
https://issues.redhat.com/browse/ISPN-12874
=> ISPN-12874 MONITOR permission and "monitor" role

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HitsAwareCacheManagersTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/CompleteShutdownDistRetryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/StableControlledConsistentHashFactory.java, core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
https://issues.redhat.com/browse/ISPN-12598
https://issues.redhat.com/browse/ISPN-7159
Add back the reset to the initial server list (removed by the initial
ISPN-12598 fix).
Perform the reset when all the servers are marked as failed,
not after max_retries attempts.
Fixes `CompleteShutdownDistRetryTest.testRetryAfterCompleteShutdown` test failures.
An additional commit adds a controlled consistent hash factory to avoid the older random failures.
=> ISPN-12598 Hot Rod java client retries too many times

persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/Compactor.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/EntryHeader.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/EntryMetadata.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/EntryRecord.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/Index.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/IndexRequest.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/LogAppender.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/LogRequest.java, persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
* Reuse bytebuffer used by same thread
* Offload passing off index submission to non blocking CPU thread instead of log
thread
* Do not create a new file object when finishing a file
* Delay is held in a List instead of async stage
https://issues.redhat.com/browse/ISPN-12867
=> ISPN-12867 SoftIndexFileStore LogAppender optimizations

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/SslConfiguration.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/SslConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelInitializer.java, documentation/src/main/asciidoc/topics/performance.adoc, server/core/src/main/java/org/infinispan/server/core/utils/SslUtils.java, server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java, server/tests/pom.xml, server/tests/src/test/java/org/infinispan/server/functional/RestLoggingResource.java, server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java, server/tests/src/test/resources/configuration/security/tls.xml
https://issues.redhat.com/browse/ISPN-12882
=> ISPN-12882 Test for disabled ciphersuites

core/src/main/java/org/infinispan/interceptors/impl/BaseStateTransferInterceptor.java, core/src/main/java/org/infinispan/remoting/inboundhandler/BaseBlockingRunnable.java, core/src/main/java/org/infinispan/remoting/inboundhandler/DefaultTopologyRunnable.java, core/src/main/java/org/infinispan/scattered/ScatteredStateProvider.java, core/src/main/java/org/infinispan/scattered/impl/ScatteredStateProviderImpl.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/main/java/org/infinispan/statetransfer/StateProviderImpl.java, core/src/main/java/org/infinispan/statetransfer/StateTransferInterceptor.java, core/src/main/java/org/infinispan/statetransfer/StateTransferLock.java, core/src/main/java/org/infinispan/statetransfer/StateTransferLockImpl.java, core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java, core/src/main/java/org/infinispan/util/concurrent/ConditionFuture.java, core/src/test/java/org/infinispan/distribution/ZeroCapacityNodeTest.java, core/src/test/java/org/infinispan/distribution/rehash/StateTransferOverwritingValueTest.java, core/src/test/java/org/infinispan/partitionhandling/ScatteredDelayedAvailabilityUpdateTest.java, core/src/test/java/org/infinispan/statetransfer/DelegatingStateTransferLock.java, core/src/test/java/org/infinispan/statetransfer/ReadAfterLostDataTest.java, core/src/test/java/org/infinispan/statetransfer/RemoteGetDuringStateTransferTest.java, core/src/test/java/org/infinispan/util/concurrent/ConditionFutureTest.java
https://issues.redhat.com/browse/ISPN-4996
* Delay initial topology until there is at least one node
with capacityFactor>0
* Update ConditionFuture to allow duplicate predicates
* Add timeout to topologyFuture and transactionDataFuture
=> ISPN-4996 Problem with capacityFactor=0 and restart of all regular nodes

core/src/main/java/org/infinispan/commands/CommandsFactory.java, core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java, core/src/main/java/org/infinispan/commands/RemoteCommandsFactory.java, core/src/main/java/org/infinispan/commands/triangle/BackupNoopCommand.java, core/src/main/java/org/infinispan/commands/triangle/BackupWriteCommand.java, core/src/main/java/org/infinispan/distribution/TriangleOrderManager.java, core/src/main/java/org/infinispan/interceptors/distribution/TriangleDistributionInterceptor.java, core/src/main/java/org/infinispan/marshall/exts/CacheRpcCommandExternalizer.java, core/src/main/java/org/infinispan/remoting/inboundhandler/TrianglePerCacheInboundInvocationHandler.java, core/src/test/java/org/infinispan/distribution/TriangleExceptionDuringMarshallingTest.java, core/src/test/java/org/infinispan/remoting/rpc/RpcManagerTest.java, core/src/test/java/org/infinispan/test/fwk/MarshallingExceptionGenerator.java, core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
https://issues.redhat.com/browse/ISPN-12435
* JGroupsTransport: complete request exceptionally instead of
throwing an exception when marshalling fails.
* TriangleDistributionInterceptor: catch exception from JGroupsTransport
when there is no request (sendToX methods).
=> ISPN-12435 SingleKeyBackupWriteCommands run out of memory

core/src/main/java/org/infinispan/configuration/cache/ClusteringConfiguration.java, core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java, core/src/main/java/org/infinispan/interceptors/distribution/L1NonTxInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/BaseStateTransferInterceptor.java, core/src/main/java/org/infinispan/notifications/cachelistener/cluster/impl/BatchingClusterEventManagerImpl.java, core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java, core/src/main/java/org/infinispan/scattered/impl/BiasManagerImpl.java, core/src/main/java/org/infinispan/statetransfer/StateTransferLockImpl.java, core/src/main/java/org/infinispan/util/concurrent/CommandAckCollector.java, core/src/test/java/org/infinispan/distribution/ZeroCapacityNodeTest.java, query/src/main/java/org/infinispan/query/clustered/ClusteredQueryInvoker.java
https://issues.redhat.com/browse/ISPN-12905
Follow-up on #9161, as I realized there was yet another wait of 100ms in the final `cache.get()` and I couldn't lower it without without risking a GC to cause random failures earlier.
I added an attribute listener to `StateTransferLockImpl` and other components to pick up runtime updates to `remote-timeout`, and then I could change the test to lower the timeout to 10ms just for the `cache.get()` that needs to fail.
=> ISPN-12905 Many components ignore changes to remote-timeout at runtime

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManager.java, spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheTest.java
https://issues.redhat.com/browse/ISPN-12690
* Register a ProtoStreamMarshaller if necessary
* Test null values with per-cache marshaller
=> ISPN-12690 Support per-cache marshaller in Spring caches

build-configuration/bom/pom.xml, build-configuration/pom.xml, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java, commons/all/pom.xml, core/pom.xml, core/src/main/java/org/infinispan/marshall/protostream/impl/SerializationContextRegistryImpl.java, query-core/pom.xml, remote-query/remote-query-client/pom.xml, remote-query/remote-query-server/pom.xml, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java, server/hotrod/pom.xml, server/tests/src/test/java/org/infinispan/server/extensions/DistributedHelloServerTask.java, server/tests/src/test/java/org/infinispan/server/extensions/HelloServerTask.java, server/tests/src/test/java/org/infinispan/server/extensions/ServerTasks.java
https://issues.redhat.com/browse/ISPN-12895
Adds protostream-types module as a maven dependency and registers by default (in HR client and server) some schemas defined by it:
* for java collections
* for some java util/math: UUID, BigDecimal...
=> ISPN-12895 Upgrade to protostream 4.4.0.Beta3

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/TransportFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AbstractConfigurationChildBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/DefaultTransportFactory.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/TransportFactoryTest.java
https://issues.redhat.com/browse/ISPN-12879
=> ISPN-12879 Pluggable TransportFactory for the Hot Rod client

server/testdriver/core/src/main/resources/testcontainers.properties
https://issues.redhat.com/browse/ISPN-12911
Make the Ryuk container privileged
=> ISPN-12911 Testcontainers-based tests do not run on Fedora 33

server/rest/src/main/java/org/infinispan/rest/RestServer.java, server/rest/src/main/java/org/infinispan/rest/resources/MetricsResource.java
https://issues.redhat.com/browse/ISPN-12918
Process metrics endpoint requests on a blocking executor thread.
=> ISPN-12918 Rest stats requests block the Netty IO thread

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientEventsOOMTest.java, core/src/main/java/org/infinispan/configuration/cache/StateTransferConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/StateTransferConfigurationBuilder.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/main/resources/schema/infinispan-config-12.1.xsd, core/src/test/java/org/infinispan/configuration/JsonSerializationTest.java, core/src/test/java/org/infinispan/container/offheap/OffHeapMultiNodeTest.java, core/src/test/java/org/infinispan/container/versioning/DistL1WriteSkewTest.java, core/src/test/java/org/infinispan/globalstate/GlobalStateBackwardsCompatibilityTest.java, core/src/test/java/org/infinispan/invalidation/BaseInvalidationTest.java, core/src/test/java/org/infinispan/partitionhandling/PessimisticTxPartitionHandlingReleaseLockTest.java, core/src/test/java/org/infinispan/replication/ReplicatedAPITest.java, core/src/test/java/org/infinispan/scattered/BaseScatteredTest.java, core/src/test/java/org/infinispan/statetransfer/ConcurrentStartChanelLookupTest.java, core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java, core/src/test/java/org/infinispan/statetransfer/StateProviderTest.java
https://issues.redhat.com/browse/ISPN-12924
Require state transfer timeout >= remote timeout
and update tests that were using an invalid timeout.
=> ISPN-12924 State transfer timeout should be validated

persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/DB2TableManager.java
...in DB2TableManager
Currently the DB2 manager looks into all schemas to determine if caching
table exists when the schema is not specified.
https://issues.redhat.com/browse/ISPN-12930
https://issues.redhat.com/browse/JBEAP-21362
=> ISPN-12930 Try to determine current schema during table existence check

core/src/main/java/org/infinispan/partitionhandling/impl/PreferConsistencyStrategy.java, core/src/main/java/org/infinispan/statetransfer/StateTransferLockImpl.java, core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java, core/src/main/java/org/infinispan/util/concurrent/ConditionFuture.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/distribution/ZeroCapacityNodeTest.java, core/src/test/java/org/infinispan/test/TestingUtil.java
https://issues.redhat.com/browse/ISPN-12962
https://issues.redhat.com/browse/ISPN-4996
The fix itself was pretty simple: Remove nodes with no segments from stable members list before computing the majority.
Writing the test revealed a problem with `TestingUtil.installNewView()` and that ISPN-4996 had not been fixed completely (a non-zero-capacity node cannot join because the old non-zero-capacity node is still in the current CH).
=> ISPN-12962 PreferConsistencyStrategy should ignore zero-capacity nodes 

core/src/main/java/org/infinispan/globalstate/impl/CacheState.java, persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/SecurityActions.java, server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java, server/core/src/main/java/org/infinispan/server/core/backup/resources/SecurityActions.java, server/core/src/main/java/org/infinispan/server/core/transport/SecurityActions.java, server/runtime/src/main/java/org/infinispan/server/tasks/SecurityActions.java
https://issues.redhat.com/browse/ISPN-12953
The `DistributedServerTask` and `TaskParameter` had to be removed from `server/runtime/proto.lock` as these messages now exist in `server/core`. As these are internal types that are never persisted this should have no impact on the user.
=> ISPN-12953 Zero Capacity Node TopologyJoinCommand frequently timing out

build-configuration/pom.xml, pom.xml, server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java, server/tests/src/test/resources/configuration/security/tls.xml
https://issues.redhat.com/browse/ISPN-12951
This PR upgrades WildFly OpenSSL to 2.1.3.Final to be able to get native TLSv1.3 support
=> ISPN-12951 Test TLSv1.3

server/tests/src/test/java/org/infinispan/server/functional/CloudEventsIntegrationIT.java
https://issues.redhat.com/browse/JDG-4542
Use Kafka image mirror from quay.io/cloudservices
=> [12.1.x] ISPN-12946 CloudEventsIntegrationIT fails because of rate limit

server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseDecoder.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseRequestProcessor.java, server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
https://issues.redhat.com/browse/ISPN-12996
Ignore IllegalStateException("ssl is null") from SslHandler
if the channel is no longer active.
=> ISPN-12996 StackOverflowError during Hot Rod connection shutdown

core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java, core/src/main/java/org/infinispan/interceptors/impl/TransactionalExceptionEvictionInterceptor.java, core/src/test/java/org/infinispan/eviction/impl/ExceptionEvictionTest.java
https://issues.redhat.com/browse/ISPN-12971
* Always request a non-transactional CommandInvocationId
* Replace "increase" with "adjust" in
TransactionalExceptionEvictionInterceptor
* Manually trigger batch expiration in all configurations
in ExceptionEvictionTest
=> ISPN-12971 RemoveExpiredCommand should never have a dummy invocation id

server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedServer.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
https://issues.redhat.com/browse/ISPN-11914
The goal of this PR is not to fix all tests that are broken for `ServerRunMode.FORKED`
The goal is allow we run the FORKED mode using the server that was built
A simple test that is working is: `mvn clean install -DskipTests && mvn verify -pl server/tests -Dit.test=RestOperations -Dorg.infinispan.test.server.driver=FORKED`
I have a plan to introduce a new `Jenkinsfile` that will run the tests for all `ServerRunMode`. The job will be running daily.
=> ISPN-11914 ServerRunMode.FORKED should use by default the server folder

core/src/test/java/org/infinispan/distribution/BlockingInterceptor.java, core/src/test/java/org/infinispan/jmx/XSiteMBeanTest.java, core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java
Sometimes the conflict was not generated because of the async xsite
If the IRAC manager is delayed and sends the update later, it will send
the new value which generates "discard" events instead of "conflict".
Now we wait for the updates to arrive at the interceptor chain
https://issues.redhat.com/browse/ISPN-13081
=> ISPN-13081 XSiteMBeanTest fails randomly

core/src/main/java/org/infinispan/interceptors/locking/AbstractTxLockingInterceptor.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/main/java/org/infinispan/transaction/impl/TransactionTable.java, core/src/test/java/org/infinispan/tx/locking/NoConcurrentLockPessimistTxTest.java
The new primary owner was not checking the backup locks before acquiring
the "primary" lock
https://issues.redhat.com/browse/ISPN-7140
main PR: https://github.com/infinispan/infinispan/pull/9381
=> [12.1] ISPN-7140 Concurrent modifications succeed in pessimistic cache

core/src/main/java/org/infinispan/interceptors/locking/AbstractTxLockingInterceptor.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/main/java/org/infinispan/transaction/impl/TransactionTable.java, core/src/test/java/org/infinispan/tx/locking/NoConcurrentLockPessimistTxTest.java
The new primary owner was not checking the backup locks before acquiring
the "primary" lock
https://issues.redhat.com/browse/ISPN-7140
* needs backport to 12.1.x
=> ISPN-7140 Concurrent modifications succeed in pessimistic cache

client/infinispan-key-value-store-hotrod/src/main/java/org/infinispan/api/reactive/client/impl/QueryPublisherImpl.java, query-core/src/main/java/org/infinispan/query/core/impl/AggregatingQuery.java, query-core/src/main/java/org/infinispan/query/core/impl/BaseEmbeddedQuery.java, query-core/src/main/java/org/infinispan/query/core/impl/HybridQuery.java, query-core/src/main/java/org/infinispan/query/core/impl/MappingIterator.java, query-core/src/main/java/org/infinispan/query/core/impl/QueryEngine.java, query-core/src/main/java/org/infinispan/query/core/impl/QueryResultImpl.java, query-core/src/main/java/org/infinispan/query/core/impl/SlicingCollector.java, query-core/src/test/java/org/infinispan/query/core/impl/MappingIteratorTest.java, query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java, query/src/main/java/org/infinispan/query/clustered/NodeTopDocs.java, query/src/main/java/org/infinispan/query/clustered/QueryResponse.java, query/src/main/java/org/infinispan/query/clustered/commandworkers/CQCreateEagerQuery.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/EmbeddedLuceneQuery.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java, query/src/main/java/org/infinispan/query/impl/IndexedQuery.java, query/src/main/java/org/infinispan/query/impl/IndexedQueryImpl.java, query/src/main/java/org/infinispan/query/impl/QueryDefinition.java, query/src/main/java/org/infinispan/query/impl/ScrollerIteratorAdaptor.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/BaseRemoteQueryManager.java, server/rest/src/test/java/org/infinispan/rest/search/MultiNodeRestTest.java, server/rest/src/test/java/org/infinispan/rest/search/SearchCountClusteredTest.java, server/rest/src/test/java/org/infinispan/rest/search/SearchCountLocalTest.java, server/rest/src/test/resources/count.proto, server/runtime/src/main/java/org/infinispan/server/logging/events/ServerEventLogger.java
https://issues.redhat.com/browse/ISPN-11013
https://issues.redhat.com/browse/ISPN-11014
https://issues.redhat.com/browse/ISPN-12959
* Fix result size for all types of queries
* Avoid executing additional query to obtain the result size
* Avoid storing results in memory in the iterator()
* Remove internal usages of deprecate list() and resultSize()
=> [12.1] ISPN-11013 ISPN-11014 ISPN-12959 Fixes for query result count

commons/all/src/main/java/org/infinispan/commons/tx/TransactionManagerImpl.java, core/src/main/java/org/infinispan/interceptors/impl/TxInterceptor.java, core/src/main/java/org/infinispan/transaction/impl/AbstractCacheTransaction.java, core/src/main/java/org/infinispan/transaction/impl/LocalTransaction.java, core/src/main/java/org/infinispan/transaction/impl/RemoteTransaction.java, core/src/main/java/org/infinispan/transaction/impl/TransactionTable.java, core/src/main/java/org/infinispan/util/concurrent/locks/LockReleasedException.java, core/src/main/java/org/infinispan/util/concurrent/locks/impl/DefaultLockManager.java, core/src/main/java/org/infinispan/util/concurrent/locks/impl/InfinispanLock.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/tx/locking/LocalPessimisticTxTest.java, core/src/test/java/org/infinispan/tx/locking/RollbackDuringLockAcquisitionTest.java
Fix concurrency issue between the TM's reaper and lock acquisition which
can lead to unreleased lock
backport of https://github.com/infinispan/infinispan/pull/9309
https://issues.redhat.com/browse/ISPN-13024
=> [12.1] ISPN-13024 Implicit Cache Lock Release Failure

core/src/main/java/org/infinispan/globalstate/GlobalStateManager.java, core/src/main/java/org/infinispan/globalstate/impl/GlobalStateManagerImpl.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java, core/src/test/java/org/infinispan/globalstate/AbstractGlobalStateRestartTest.java, core/src/test/java/org/infinispan/globalstate/ThreeNodeDistGlobalStateRestartTest.java, core/src/test/java/org/infinispan/globalstate/ThreeNodeReplGlobalStateRestartTest.java, core/src/test/java/org/infinispan/globalstate/ThreeNodeScatteredGlobalStateRestartTest.java
https://issues.redhat.com/browse/ISPN-13121
=> ISPN-13121 Cache persistent state is not deleted after restart

core/src/test/java/org/infinispan/tx/ParticipantFailsAfterPrepareTest.java
https://issues.redhat.com/browse/ISPN-11076
=> ISPN-11076 ParticipantFailsAfterPrepareTest.testNonOriginatorFailsAfterPrepare random failures

documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/ISPN-13116
=> [12.1.x] ISPN-13116 Add upgrade note for SFS cache store

core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHash.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/test/java/org/infinispan/globalstate/GlobalStateBackwardsCompatibilityTest.java
https://issues.redhat.com/browse/JDG-4713
Backport of #9435 
* Set all capacity factors to 1f if the persisted CH doesn't have
the capacity factors properties
* Remove capacity factors in GlobalStateBackwardsCompatibilityTest
* Simplify handling of join errors in LocalTopologyManagerImpl
to improve error messages.
=> [12.1.x] ISPN-12667 GlobalState incompatibility between 11.x and 12.x

core/src/test/java/org/infinispan/tx/locking/RollbackDuringLockAcquisitionTest.java
* follow-up: use eventually to avoid concurrency issues
=> ISPN-13024 Implicit Cache Lock Release Failure

client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java, documentation/src/main/asciidoc/topics/ref_rest_caches.adoc, server/core/src/main/java/org/infinispan/server/core/dataconversion/XMLTranscoder.java, server/rest/src/main/java/org/infinispan/rest/CacheEntryInputStream.java, server/rest/src/main/java/org/infinispan/rest/ResponseHeader.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/rest/src/main/java/org/infinispan/rest/resources/MediaTypeUtils.java, server/rest/src/main/java/org/infinispan/rest/resources/SecurityActions.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceTest.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
https://issues.redhat.com/browse/ISPN-13030
Adds media type negotiation to the REST [entries](https://infinispan.org/docs/stable/titles/rest/rest.html#rest_v2_get_entries) operation to be able to display all kinds of key and value content, including binary. Returns extra pair of headers with the negotiated content.
~~Marking as preview as it depends on https://github.com/infinispan/infinispan/pull/9413~~
=> ISPN-13030 REST getEntries only supports JSON

commons/all/src/test/java/org/infinispan/commons/time/ControlledTimeService.java, core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationMaxIdleTest.java, core/src/test/java/org/infinispan/xsite/AsyncBackupExpirationTest.java, core/src/test/java/org/infinispan/xsite/irac/IracMaxIdleTest.java
https://issues.redhat.com/browse/ISPN-13161
In scattered caches, the touch command doesn't always
run synchronously on the get originator.
Updated to include fix for `testMaxIdleNodeDies` random failures.
=> ISPN-13161 ClusterExpirationMaxIdleTest.testMaxIdleAccessSuspectedExpiredEntryRefreshesProperly

core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java, core/src/main/java/org/infinispan/statetransfer/StateTransferLockImpl.java, core/src/test/java/org/infinispan/distribution/rehash/NonTxPrimaryOwnerBecomingNonOwnerTest.java
https://issues.redhat.com/browse/ISPN-13160
Remove duplicate state transfer lock in EntryWrappingInterceptor.
Acquiring a second state transfer read lock from the same
thread can now hang if another thread is waiting for
the state transfer write lock.
=> ISPN-13160 Write may block topology update forever

build-configuration/bom/pom.xml, client/marshaller/pom.xml
Kryo and Protostuff marshallers are deprecated and not supported
downstream. A profile will allow disabling the build of these modules
downstream with minimal changes required to the pom.xml files
https://issues.redhat.com/browse/ISPN-13208
=> ISPN-13208 Create profile to disable marshallers

core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/IndexRequest.java
* Also removed some extra unused fields from IndexRequest
https://issues.redhat.com/browse/ISPN-13130
Note that no tests has been added as this could intermittently occur before due to completing the Future from two different spots which has now been reduced to one.
=> ISPN-13130 SoftIndexFileStore index update concurrency issue

core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
ISPN-13138 ScatteredVersionManagerImpl can mark segments owned too soon
ISPN-13147 State transfer can lose entries when a node leaves
https://issues.redhat.com/browse/ISPN-13138
https://issues.redhat.com/browse/ISPN-13147
Both issues cause random failure in StateTransferRestart2Test
=> ISPN-13138 + ISPN-13147 State transfer can lose entries

Jenkinsfile, all/cli/pom.xml, client/hotrod-client/pom.xml, client/marshaller/kryo/kryo-marshaller-compatibility-bundle/pom.xml, client/marshaller/protostuff/protostuff-marshaller-compatibility-bundle/pom.xml, distribution/package.xml, distribution/pom.xml, documentation/pom.xml, javadoc/pom.xml, object-filter/pom.xml, persistence/remote/pom.xml, pom.xml, server/hotrod/pom.xml, server/rest/pom.xml, server/router/pom.xml, server/runtime/build.xml, server/runtime/src/main/ant/infinispan-server.xml
https://issues.redhat.com/browse/ISPN-13205
The main fix was in the Jenkins agent: https://issues.jenkins.io/browse/JENKINS-66268 was slowing down the warnings report by downloading the same 2 Xerces classes thousands of times. I worked around it by downloading xercesImpl-2.12.2.jar on the agents and adding it to the agent's classpath with `-Xbootclasspath/a:`. That removed almost 20 minutes from the build time.
I estimate the xz compression level change also reduced the build time by about 2 minutes.
=> ISPN-13205 Warnings Next Generation plugin slows down build

counter/src/main/java/org/infinispan/counter/impl/listener/CounterManagerNotificationManager.java, counter/src/main/java/org/infinispan/counter/impl/manager/EmbeddedCounterManager.java
Only register the clustered listener when it is required. The clustered
listener has an impact on add operation performance.
https://issues.redhat.com/browse/ISPN-10602
=> ISPN-10602 Lazily register clustered listener for counters

CONTRIBUTING.md, documentation/README.md, documentation/src/main/asciidoc/topics/proc_cli_registering_protobuf_schema.adoc
Just a slight update to documentation. 
If this needs a jira ticket I'm happy to create one.
=> update protobuf example

core/src/main/java/org/infinispan/persistence/async/AsyncNonBlockingStore.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/main/java/org/infinispan/persistence/spi/NonBlockingStore.java, core/src/test/java/org/infinispan/persistence/BaseNonBlockingStoreTest.java, core/src/test/java/org/infinispan/persistence/support/WaitNonBlockingStore.java, core/src/test/java/org/infinispan/stress/AsyncStoreStressTest.java, persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
https://issues.redhat.com/browse/ISPN-12638
Skip the previous lookup in RocksDBStore and RemoteStore
=> ISPN-12638 Make NonBlockingStore.delete() return value optional

build-configuration/pom.xml
https://issues.redhat.com/browse/ISPN-13182
This fixes builds on JDK 17 
(Splitting this to its own individual PR to ease integration)
=> ISPN-13182 BlockHound 1.0.6.FINAL

core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/locking/ClusteringDependentLogic.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
https://issues.redhat.com/browse/ISPN-13160
If the originator's topology changed after receiving acks from the
backups but before committing locally, and no owners have been added,
commit the entry without triggering a retry.
=> ISPN-13160 Allow backup to commit entry if it used to be primary

core/src/main/java/org/infinispan/persistence/async/AsyncNonBlockingStore.java, core/src/main/java/org/infinispan/persistence/async/PutModification.java, core/src/test/java/org/infinispan/persistence/BaseNonBlockingStoreTest.java, core/src/test/java/org/infinispan/persistence/FlushingAsyncStoreTest.java, core/src/test/java/org/infinispan/persistence/WriteBehindFaultToleranceTest.java, core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java, core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStoreConfigurationBuilder.java, core/src/test/java/org/infinispan/persistence/manager/PersistenceManagerTest.java, core/src/test/java/org/infinispan/persistence/support/AsyncStoreTest.java, core/src/test/java/org/infinispan/persistence/support/DelayStore.java, core/src/test/java/org/infinispan/persistence/support/ReplAsyncStoreTest.java
https://issues.redhat.com/browse/ISPN-11902
* Invoke the 3rd putAll (2nd putAll in fork thread) only after PersistenceManagerImpl
is available
* Clean up duplicate logging and add more batch ids
* Make test failures clearer
=> ISPN-11902 WriteBehindFaultToleranceTest.testBlockingOnStoreAvailabilityChange random failures

anchored-keys/src/main/java/org/infinispan/anchored/AnchoredKeysModule.java, core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java, core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java, core/src/main/java/org/infinispan/eviction/impl/PassivationManagerImpl.java, core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java, core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java, core/src/main/java/org/infinispan/expiration/impl/InternalExpirationManager.java, core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java, core/src/main/java/org/infinispan/interceptors/impl/PrefetchInterceptor.java, core/src/main/java/org/infinispan/remoting/inboundhandler/BasePerCacheInboundInvocationHandler.java, core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java, core/src/main/java/org/infinispan/scattered/impl/ScatteredStateProviderImpl.java, core/src/main/java/org/infinispan/statetransfer/StateProviderImpl.java, core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java, core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateProviderImpl.java, core/src/test/java/org/infinispan/container/SimpleDataContainerTest.java, core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationMaxIdleTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java, core/src/test/java/org/infinispan/notifications/cachelistener/cluster/ClusterListenerReplTest.java, core/src/test/java/org/infinispan/statetransfer/StateTransferExpiredStoreTest.java, core/src/test/java/org/infinispan/stress/DataContainerStressTest.java, core/src/test/java/org/infinispan/util/ControlledRpcManager.java
https://issues.redhat.com/browse/ISPN-13191
https://issues.redhat.com/browse/ISPN-5938
https://issues.redhat.com/browse/ISPN-13241
* Use peek() instead of containsKey() to skip the expiration check.
* Fix ClusterListenerReplInitialStateTest
* Remove InternalExpirationManager.entryExpiredInMemoryFromIteration
=> ISPN-13191 Deadlock: expiration blocks state transfer

core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
https://issues.redhat.com/browse/ISPN-13192
The initial fix replaced broke the calculation of the TCP bind port, because the thread counter index from 7900 instead of 0, and the base port was computed as 7900 + thread index * 200, getting over 65535 very quickly.
I missed it at the time because that code path is only used when running the tests with `-Dinfinispan.cluster.stack=test-tcp`
=> ISPN-13192 Fix TCP start port

core/src/main/java/org/infinispan/commands/tx/PrepareCommand.java, core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java, core/src/main/java/org/infinispan/interceptors/AsyncInterceptorChain.java, core/src/main/java/org/infinispan/interceptors/EmptyAsyncInterceptorChain.java, core/src/main/java/org/infinispan/interceptors/impl/AsyncInterceptorChainImpl.java, core/src/main/java/org/infinispan/util/KeyValuePair.java, core/src/test/java/org/infinispan/interceptors/impl/AsyncInterceptorChainInvocationTest.java, core/src/test/java/org/infinispan/interceptors/impl/AsyncInterceptorChainTest.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerInterceptor.java, remote-query/remote-query-server/src/test/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerInterceptorTest.java, server/core/src/main/java/org/infinispan/server/core/transport/NonRecursiveEventLoopGroup.java
https://issues.redhat.com/browse/ISPN-12923
Remove .errors keys sequentially, because invocation contexts
are not thread-safe.
Add AsyncInterceptorChain.invokeStage()
Simplify the code in ProtobufMetadataManagerInterceptor
that needs to invoke another command and return an
InvocationStage.
Reduce NonRecursiveEventLoopGroup graceful shutdown timeout
Match the timeout with the one in NettyTransport.
The lower timeout speeds up tests in the server-core module
and any modules that depend on it.
=> ISPN-12923 ProtobufMetadataManagerInterceptor IllegalStateException

commons/all/src/main/java/org/infinispan/counter/api/CounterConfiguration.java, core/src/main/java/org/infinispan/container/impl/InternalEntryFactoryImpl.java, core/src/main/java/org/infinispan/functional/MetaParam.java, core/src/main/java/org/infinispan/functional/impl/CounterConfigurationMetaParam.java, core/src/main/java/org/infinispan/functional/impl/MetaParamsInternalMetadata.java, core/src/main/java/org/infinispan/metadata/Metadata.java, core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java, counter/pom.xml, counter/src/main/java/org/infinispan/counter/configuration/Attribute.java, counter/src/main/java/org/infinispan/counter/configuration/ConvertUtil.java, counter/src/main/java/org/infinispan/counter/configuration/CounterConfigurationParser.java, counter/src/main/java/org/infinispan/counter/configuration/CounterParser.java, counter/src/main/java/org/infinispan/counter/configuration/StrongCounterConfiguration.java, counter/src/main/java/org/infinispan/counter/configuration/StrongCounterConfigurationBuilder.java, counter/src/main/java/org/infinispan/counter/impl/function/FunctionHelper.java, counter/src/main/resources/schema/infinispan-counters-config-13.0.xsd, counter/src/test/java/org/infinispan/counter/ConfigurationSerializerTest.java, counter/src/test/java/org/infinispan/counter/ConfigurationTest.java, counter/src/test/java/org/infinispan/counter/ExpirationStrongCounterTest.java, counter/src/test/resources/configs/all/counters.xml, documentation/src/main/asciidoc/topics/code_examples/ClusteredCounters.java, documentation/src/main/asciidoc/topics/code_examples/ClusteredCountersEmbeddedCacheManager.java, documentation/src/main/asciidoc/topics/code_examples/CounterRateLimiter.java, documentation/src/main/asciidoc/topics/config_examples/clustered_counters_config.xml, documentation/src/main/asciidoc/topics/counters.adoc
* Added an option to configure a lifespan for strong counters. When the
counter is expired, it is reset to its initial value.
https://issues.redhat.com/browse/ISPN-12937
=> ISPN-12937 Expiring counters

core/src/test/java/org/infinispan/marshall/core/ExternalizerConfigurationValidationTest.java, core/src/test/java/org/infinispan/util/ThreadLocalLeakTest.java, jboss-marshalling/src/test/java/org/infinispan/jboss/marshalling/JBossMarshallingThreadLocalLeakTest.java
https://issues.redhat.com/browse/ISPN-12650
* Make the main thread always stop the cache manager after
the forked thread finishes the put operation
* Add invocation batching, because BatchContainer and
BatchModeTransactionManager use thread-locals
* Duplicate the test in the jboss-marshalling module,
because AbstractJBossMarshaller also uses a thread-local
=> ISPN-12650 ThreadLocalLeakTest random failures (uncaught exception)

server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodConcurrentStartTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodConcurrentTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodDistributionTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodFunctionalTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodIdleTimeoutTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMergeTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiNodeTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodNoDefaultCacheTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSharedContainerTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleClusteredNonLoopbackTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleClusteredTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleNodeTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSniFunctionalTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSslFunctionalTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/counter/impl/TestCounterManager.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/counter/impl/TestCounterNotificationManager.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/counter/impl/TestStrongCounter.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/counter/impl/TestWeakCounter.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/event/AbstractHotRodClusterEventsTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodClient.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodTestingUtil.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/tx/ServerConfigurationTest.java
https://issues.redhat.com/browse/ISPN-13343
* Use CompletableFuture to receive responses without sleep(100)
* Verify the expiration metadata directly instead of
waiting for expiration
* Remove trace logging of generated test keys
* Wait for server to close connection in HotRodIdleTimeoutTest,
instead of waiting for a response that will never arrive
=> ISPN-13343 The test Hot Rod client in the server module is slow

core/src/test/java/org/infinispan/persistence/support/BatchAsyncStoreTest.java, core/src/test/java/org/infinispan/util/ThreadLocalLeakTest.java
Set alwaysRun=true for setup methods required by other setup/teardown
methods with alwaysRun=true.
=> ISPN-13436 Spurious failures when a test name is wrong

build-configuration/pom.xml, integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/store/AbstractInfinispanStoreRocksDBIT.java, integrationtests/server-integration/third-party-server/pom.xml, integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/DeploymentHelper.java, integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml, persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
https://issues.redhat.com/browse/ISPN-13392
- During the rebase of 32615d12727c1865bcce39fa5169bf62d8169ec3, for some reason, the code that uses a zip file instead of a folder was added back
- 4b831656a766644455d39a5f2bc1c785c426031c fixes CDI tests but there is no integration tests running upstream for Tomcat. Weld dependency was added to fix it.
- Fix NPE in RocksDB. The hanlder could be null if an issue occurs during the initialization
=> ISPN-13392 Fix Tomcat integration test setup

server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java, server/tests/pom.xml, server/tests/src/test/java/org/infinispan/server/security/AuthenticationImplicitIT.java, server/tests/src/test/java/org/infinispan/server/security/AuthenticationKerberosIT.java, server/tests/src/test/java/org/infinispan/server/security/AuthenticationMultiEndpointIT.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationKerberosIT.java, server/tests/src/test/java/org/infinispan/server/test/core/LdapServerListener.java, server/tests/src/test/java/org/infinispan/server/test/core/ldap/AbstractLdapServer.java, server/tests/src/test/java/org/infinispan/server/test/core/ldap/ApacheLdapServer.java, server/tests/src/test/java/org/infinispan/server/test/core/ldap/RemoteLdapServer.java, server/tests/src/test/resources/configuration/security/ldap.xml, server/tests/src/test/resources/ldif/infinispan-dn.ldif, server/tests/src/test/resources/ldif/infinispan-kerberos.ldif, server/tests/src/test/resources/ldif/infinispan.ldif
https://issues.redhat.com/browse/ISPN-13355
=> ISPN-13355 Support Remote LDAP Server for testing purposes

core/src/main/java/org/infinispan/CacheStream.java, core/src/main/java/org/infinispan/marshall/core/BytesObjectOutput.java, core/src/test/java/org/infinispan/marshall/core/PrimitivesTest.java, core/src/test/java/org/infinispan/stream/BaseStreamTest.java
https://issues.redhat.com/browse/ISPN-13428
https://issues.redhat.com/browse/ISPN-13438
BytesObjectOutput does not handle overflow correctly
Add warning to CacheStream collector operations javadoc
=> ISPN-13428 Distributed streams collectors ignore distributedBatchSize

core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
Problems:
* State.accept() and onSendingCompleted() were running concurrently.
* onSendingCompleted() triggers an IRAC round but the State.stateStatus
was not updated.
* The new round would not retry to send the key again making the test fail.
https://issues.redhat.com/browse/ISPN-13165
:crossed_fingers:
=> ISPN-13165 AsyncOfflineTest.testReset random failures (take 2)

core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java, core/src/main/java/org/infinispan/remoting/transport/impl/SiteUnreachableXSiteResponse.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/SingleSiteRequest.java
* Use only one thread to handle the event for each site.
* While a thread is handling the event, fail the new requests.
https://issues.redhat.com/browse/ISPN-13473
=> ISPN-13473 Improve SingleSiteRequest.sitesUnreachable()

core/src/main/java/org/infinispan/interceptors/xsite/BaseBackupInterceptor.java, core/src/main/java/org/infinispan/interceptors/xsite/NonTransactionalBackupInterceptor.java, core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java, core/src/main/java/org/infinispan/xsite/irac/IracManager.java, core/src/main/java/org/infinispan/xsite/irac/NoOpIracManager.java, core/src/test/java/org/infinispan/xsite/irac/ControlledIracManager.java
* Backup owners only track keys changed when the context is remote.
* Clear is now tracking the keys on backup owners.
* On topology change, trigger an IRAC round only when there are pending
updates to be sent.
https://issues.redhat.com/browse/ISPN-13431
=> ISPN-13431 IRAC: backup owners track keys twice

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryStringTest.java, query-core/src/main/java/org/infinispan/query/core/impl/EmbeddedQuery.java, query-core/src/main/java/org/infinispan/query/core/impl/EmptyResultQuery.java, query-core/src/main/java/org/infinispan/query/core/impl/HybridQuery.java, query-core/src/main/java/org/infinispan/query/core/impl/Log.java, query-core/src/main/java/org/infinispan/query/core/impl/QueryResultImpl.java, query-dsl/src/main/java/org/infinispan/query/dsl/Query.java, query-dsl/src/main/java/org/infinispan/query/dsl/QueryResult.java, query-dsl/src/main/java/org/infinispan/query/dsl/impl/BaseQuery.java, query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java, query/src/main/java/org/infinispan/query/clustered/commandworkers/CQCreateEagerQuery.java, query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryBuilder.java, query/src/main/java/org/infinispan/query/impl/IndexedQuery.java, query/src/main/java/org/infinispan/query/impl/IndexedQueryImpl.java, query/src/main/java/org/infinispan/query/logging/Log.java, query/src/test/java/org/infinispan/query/dsl/embedded/QueryStringTest.java
* also prevent use of projections with Query.entryIterator() because
projecting anything other than key and value would work against the
purpose of entryIterator
* use proper i18n for some newly added exceptions
* prefer throwing CacheException in case of api misusage instead of other less specific RuntimeExceptions
https://issues.redhat.com/browse/ISPN-13454
=> ISPN-13454 Ickle DELETE should not allow usage of Query.startOffset/maxResults

client/infinispan-key-value-store-hotrod/src/main/java/org/infinispan/api/reactive/client/impl/KeyValueStoreImpl.java, core/src/main/java/org/infinispan/stats/Stats.java, core/src/main/java/org/infinispan/stats/impl/AbstractClusterStats.java, core/src/main/java/org/infinispan/stats/impl/CacheContainerStatsImpl.java, core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java, core/src/main/java/org/infinispan/stats/impl/StatsCollector.java, core/src/main/java/org/infinispan/stats/impl/StatsImpl.java, core/src/test/java/org/infinispan/commands/module/TestGlobalConfigurationBuilder.java, core/src/test/java/org/infinispan/jmx/AbstractClusterMBeanTest.java, core/src/test/java/org/infinispan/jmx/ClusterCacheStatsMBeanTest.java, core/src/test/java/org/infinispan/jmx/RpcManagerMBeanTest.java, core/src/test/java/org/infinispan/remoting/transport/MockTransport.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodStatsClusterTest.java, server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
https://issues.redhat.com/browse/ISPN-12607
Please do not close the issue, I have not yet implemented the approximate size metrics that are supposed to always be available.
ISPN-12607 Only compute the accurate size when enabled
* In clustered cache stats
* In REST cache details
ISPN-12607 Only report client size in Micrometer integration
ISPN-12607 Use sizeAsync in KeyValueStoreImpl
ISPN-12607 Deprecate getTotalNumberOfEntries()
ISPN-12607 Use dynamic stats update threshold
=> ISPN-12607 Only compute the accurate size when enabled

core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java, core/src/main/java/org/infinispan/remoting/transport/impl/SiteUnreachableXSiteResponse.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/SingleSiteRequest.java
* Use only one thread to handle the event for each site.
* While a thread is handling the event, fail the new requests.
https://issues.redhat.com/browse/ISPN-13473
ps. on hold until 13.0.x branch is open!
=> [13.0.x] ISPN-13473 Improve SingleSiteRequest.sitesUnreachable()

component-processor/src/main/java/org/infinispan/component/processor/ComponentAnnotationProcessor.java, core/src/main/java/org/infinispan/util/concurrent/BlockingTaskAwareExecutorServiceImpl.java, core/src/test/java/org/infinispan/jmx/CacheManagerMBeanTest.java, core/src/test/java/org/infinispan/jmx/ClusteredCacheManagerMBeanTest.java, server/core/src/main/java/org/infinispan/server/core/transport/NonRecursiveEventLoopGroup.java
https://issues.redhat.com/browse/ISPN-13312
Add a @Stop method to BlockingTaskAwareExecutorServiceImpl
that only stops retrying tasks -- in the server, the underlying
executor is stopped later.
=> ISPN-13312 NonRecursiveEventLoopGroup shutdown deadlock

persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
https://issues.redhat.com/browse/ISPN-13479
=> ISPN-13479 NPE in RemoteStore when not properly initialized

build-configuration/pom.xml, server/runtime/src/main/java/org/infinispan/server/Server.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationCertIT.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationKerberosIT.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationLDAPIT.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationPropertiesIT.java
https://issues.redhat.com/browse/ISPN-13562
=> ISPN-13562 Log4J 2.15.0

component-processor/src/main/java/org/infinispan/component/processor/ComponentAnnotationProcessor.java, core/src/main/java/org/infinispan/util/concurrent/BlockingTaskAwareExecutorServiceImpl.java, core/src/test/java/org/infinispan/jmx/CacheManagerMBeanTest.java, core/src/test/java/org/infinispan/jmx/ClusteredCacheManagerMBeanTest.java, server/core/src/main/java/org/infinispan/server/core/transport/NonRecursiveEventLoopGroup.java
https://issues.redhat.com/browse/ISPN-13312
Add a @Stop method to BlockingTaskAwareExecutorServiceImpl
that only stops retrying tasks -- in the server, the underlying
executor is stopped later.
Backport of https://github.com/infinispan/infinispan/pull/9708
=> [13.0.x] ISPN-13312 NonRecursiveEventLoopGroup shutdown deadlock 

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
If a "site down" event is received, fail fast all cross-site requests to
that site until a "site up" event.
Includes ISPN-13443 "Non relay-nodes are reporting cross-site view
changes"
https://issues.redhat.com/browse/ISPN-13488
https://issues.redhat.com/browse/ISPN-13443
=> ISPN-13488 Fail fast if site connection is down

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryStringTest.java, query-core/src/main/java/org/infinispan/query/core/impl/EmbeddedQuery.java, query-core/src/main/java/org/infinispan/query/core/impl/EmptyResultQuery.java, query-core/src/main/java/org/infinispan/query/core/impl/HybridQuery.java, query-core/src/main/java/org/infinispan/query/core/impl/Log.java, query-core/src/main/java/org/infinispan/query/core/impl/QueryResultImpl.java, query-dsl/src/main/java/org/infinispan/query/dsl/Query.java, query-dsl/src/main/java/org/infinispan/query/dsl/QueryResult.java, query-dsl/src/main/java/org/infinispan/query/dsl/impl/BaseQuery.java, query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java, query/src/main/java/org/infinispan/query/clustered/commandworkers/CQCreateEagerQuery.java, query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryBuilder.java, query/src/main/java/org/infinispan/query/impl/IndexedQuery.java, query/src/main/java/org/infinispan/query/impl/IndexedQueryImpl.java, query/src/main/java/org/infinispan/query/logging/Log.java, query/src/test/java/org/infinispan/query/dsl/embedded/QueryStringTest.java
* also prevent use of projections with Query.entryIterator() because
projecting anything other than key and value would work against the
purpose of entryIterator
* use proper i18n for some newly added exceptions
* prefer throwing CacheException in case of api misusage instead of other less specific RuntimeExceptions
https://issues.redhat.com/browse/ISPN-13454
=> [13.0.x] ISPN-13454 Ickle DELETE should not allow usage of Query.startOffset/maxResults

documentation/pom.xml
https://issues.redhat.com/browse/ISPN-13585
=> ISPN-13585 Disable PDF generation

documentation/src/main/asciidoc/topics/con_calculate_size_data_set.adoc
Minor fix, remove redundant backslash from formulas in the tuning doc. (The characters aren't converted into symbols, escaping isn't necessary)
=> ISPN-13260 Docs - remove redundant backslash from formulas in the tuning guide

documentation/src/main/asciidoc/topics/con_calculate_size_data_set.adoc
Minor fix, remove redundant backslash from formulas in the tuning doc. (The characters aren't converted into symbols, escaping isn't necessary)
=> [13.0.x] ISPN-13260 Docs fix -remove redundant backslash from formulas

documentation/src/main/asciidoc/stories/assembly_migrating_data.adoc, documentation/src/main/asciidoc/topics/attributes/store_migrator_source_versions.adoc, documentation/src/main/asciidoc/topics/proc_configuring_store_migrator.adoc, documentation/src/main/asciidoc/topics/ref_store_migrator_properties.adoc
https://issues.redhat.com/browse/ISPN-13590
=> ISPN-13590 include source.version field in migrator example

core/src/main/java/org/infinispan/topology/CacheTopology.java, core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/test/java/org/infinispan/globalstate/AbstractGlobalStateRestartTest.java, core/src/test/java/org/infinispan/globalstate/ThreeNodeDistGlobalStateRestartTest.java
https://issues.redhat.com/browse/ISPN-13121
Validate the persistent state checksum only when a node tries to join.
Ignore the persistent state checksum when a node is replying to a
cluster recovery request (CacheStatusRequestCommand).
=> ISPN-13121 Cache persistent state is not deleted after successful restart

core/src/main/java/org/infinispan/topology/CacheTopology.java, core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/test/java/org/infinispan/globalstate/AbstractGlobalStateRestartTest.java, core/src/test/java/org/infinispan/globalstate/ThreeNodeDistGlobalStateRestartTest.java
https://issues.redhat.com/browse/ISPN-13121
Backport of #9716 
Validate the persistent state checksum only when a node tries to join.
Ignore the persistent state checksum when a node is replying to a
cluster recovery request (CacheStatusRequestCommand).
=> [13.0.x] ISPN-13121 Cache persistent state is not deleted after successful restart

core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
https://issues.redhat.com/browse/ISPN-13605
=> [13.0.x] ISPN-13605 SIFS write/delete/containsKey(...) exception handling does not conform to NonBlockingStore contract.

core/src/main/java/org/infinispan/util/MappedCacheStream.java
https://issues.redhat.com/browse/ISPN-13608
=> ISPN-13608 fix for NPE after stream.filterKeys(null) was used

core/src/main/java/org/infinispan/util/MappedCacheStream.java
https://issues.redhat.com/browse/ISPN-13608
=> [13.0.x] ISPN-13608 fix for NPE after stream.filterKeys(null) was used

core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
https://issues.redhat.com/browse/ISPN-13163
The scattered state retrieval is blocking, add an exemption in
BlockHound.
Used to be exempted through PrefetchIntereptor.
=> ISPN-13163 Allow blocking ScatteredStateConsumerImpl.blockingSubscribe()

core/src/main/resources/default-configs/default-jgroups-azure.xml, core/src/main/resources/default-configs/default-jgroups-ec2.xml, core/src/main/resources/default-configs/default-jgroups-google.xml, core/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/test/resources/configs/all/10.0.xml, core/src/test/resources/configs/all/10.1.xml, core/src/test/resources/configs/all/11.0.xml, core/src/test/resources/configs/all/12.0.xml, core/src/test/resources/configs/all/12.1.xml, core/src/test/resources/configs/all/13.0.xml, core/src/test/resources/configs/all/14.0.xml, core/src/test/resources/configs/config-with-jgroups-stack.xml, core/src/test/resources/configs/xsite/bridge.xml, core/src/test/resources/configs/xsite/xsite-inline-test.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/tcp_mping/tcp1.xml, core/src/test/resources/stacks/tcp_mping/tcp2.xml, documentation/src/main/asciidoc/topics/xml/jgroups_inline_stack.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
https://issues.redhat.com/browse/ISPN-13625
* Increase xmit_timeout in TCP stacks to 200ms
Increasing xmit_timeout reduces the number of attempts to resend
LEAVE_RSP when the destination is no longer reachable.
TCP already retransmits messages, so the UNICAST3 retransmission
is only needed when the connection is unstable or the destination's
thread pool is full.
* ISPN-13625 Reduce UNICAST3.conn_close_timeout to 5000ms
Reducing conn_close_timeout reduces the number of attempts to resend
LEAVE_RSP when the destination is no longer reachable.
=> ISPN-13625 Scaling up 8.3 cluster with payload is slower compared to 8.2

core/src/main/resources/default-configs/default-jgroups-azure.xml, core/src/main/resources/default-configs/default-jgroups-ec2.xml, core/src/main/resources/default-configs/default-jgroups-google.xml, core/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/test/resources/configs/all/10.0.xml, core/src/test/resources/configs/all/10.1.xml, core/src/test/resources/configs/all/11.0.xml, core/src/test/resources/configs/all/12.0.xml, core/src/test/resources/configs/all/12.1.xml, core/src/test/resources/configs/all/13.0.xml, core/src/test/resources/configs/config-with-jgroups-stack.xml, core/src/test/resources/configs/xsite/bridge.xml, core/src/test/resources/configs/xsite/xsite-inline-test.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/tcp_mping/tcp1.xml, core/src/test/resources/stacks/tcp_mping/tcp2.xml, documentation/src/main/asciidoc/topics/xml/jgroups_inline_stack.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml, integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
https://issues.redhat.com/browse/ISPN-13625
Increase xmit_timeout in TCP stacks to 200ms
Increasing xmit_timeout reduces the number of attempts to resend
LEAVE_RSP when the destination is no longer reachable.
TCP already retransmits messages, so the UNICAST3 retransmission
is only needed when the connection is unstable or the destination's
thread pool is full.
ISPN-13625 Reduce UNICAST3.conn_close_timeout to 5000ms
Reducing conn_close_timeout reduces the number of attempts to resend
LEAVE_RSP when the destination is no longer reachable.
=> [13.0.x] ISPN-13625 Scaling up 8.3 cluster with payload is slower compared to 8.2

core/src/main/java/org/infinispan/container/impl/EntryFactory.java, core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java, core/src/main/java/org/infinispan/interceptors/BaseAsyncInterceptor.java, core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/distribution/L1NonTxInterceptor.java, core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java, core/src/test/java/org/infinispan/api/ConditionalOperationPrimaryOwnerFailTest.java, core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationFunctionalTest.java
https://issues.redhat.com/browse/JDG-5069
JDG-5069 Data race in EntryWrappingInterceptor handling expired entries
Backport of https://github.com/infinispan/infinispan/pull/9788 + #9805 for 9.4.x.
Synchronize the invocation context access after the expiration.
The test reproduces the problem but only with a huge number of keys.
I've disabled the test when the cache is transactional (ISPN-13618) or scattered (ISPN-13619).
=> [9.4.x] ISPN-13549 EntryWrappingInterceptor data race handling expired entries

core/src/main/java/org/infinispan/container/impl/EntryFactory.java, core/src/main/java/org/infinispan/container/impl/EntryFactoryImpl.java, core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/distribution/L1NonTxInterceptor.java, core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java, core/src/test/java/org/infinispan/api/ConditionalOperationPrimaryOwnerFailTest.java, core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationMaxIdleTest.java
https://issues.redhat.com/browse/ISPN-13549
Synchronize the invocation context access when an async expiration
check is needed.
The test reproduces the problem but only with a huge number of keys.
Improves on #9788 by making sure that the sync part of entry wrapping is done before any entry wrapping that was delayed by an async expiration check. The code is much clunkier, though.
=> ISPN-13549 EntryWrappingInterceptor data race handling expired entries

core/src/main/java/org/infinispan/container/versioning/NumericVersionGenerator.java, core/src/main/java/org/infinispan/container/versioning/RankCalculator.java, core/src/main/java/org/infinispan/factories/EmptyConstructorFactory.java, core/src/test/java/org/infinispan/container/versioning/NumericVersionGeneratorTest.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoder.java
https://issues.redhat.com/browse/ISPN-6044
Make RankCalculator a global component and add it as a listener
only once.
=> ISPN-6044 NumericVersionGenerator stops removed caches from being GCed

core/src/main/java/org/infinispan/persistence/spi/NonBlockingStore.java
Fixed a one missing and one extra `}`, plus some spelling fixes suggested by IntelliJ.
=> NonBlockingStore javadoc fixes

core/src/main/java/org/infinispan/configuration/format/PropertyFormatter.java
This issue is similar to https://issues.redhat.com/browse/ISPN-13520, so I have reused the Jira ID.
`getParameters().length` creates an array clone, while `getParameterCount()` directly returns the length.
=> ISPN-13520 Replace usages of getParameters().length with getParameterCount()

core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
DefaultIracManager.trackClear() is not clearing the keys from the map.
After IracManagerKeyState.discard(), the key is never retried again and
then never removed.
https://issues.redhat.com/browse/ISPN-13693
=> ISPN-13693 Fix AsyncBackupTest.testClear test

cli/src/main/java/org/infinispan/cli/commands/rest/Schema.java, cli/src/main/resources/help/schema.adoc, server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
https://issues.redhat.com/browse/ISPN-13682
Unfortunately this introduces an incompatible change:
`schema -u /path/to/file.proto file.proto` 
must be replaced by
`schema upload -f /path/to/file.proto file.proto`
=> ISPN-13682 CLI Schema manipulation commands

core/src/main/java/org/infinispan/container/versioning/irac/DefaultIracTombstoneManager.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java, core/src/test/java/org/infinispan/xsite/AbstractTwoSitesTest.java
https://issues.redhat.com/browse/ISPN-13630
=> ISPN-13630 Do not send cross-site requests to local site

core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManager.java, core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java, core/src/main/java/org/infinispan/reactive/publisher/impl/InnerPublisherSubscription.java, core/src/test/java/org/infinispan/reactive/publisher/impl/SimpleClusterPublisherManagerTest.java
https://issues.redhat.com/browse/ISPN-13616
=> [13.0.x] ISPN-13616 Stream pipeline blocks if filterKeys() gets an empty set

documentation/src/main/asciidoc/stories/assembly_server_encryption.adoc, documentation/src/main/asciidoc/topics/json/server_ssl_identity_fips.json, documentation/src/main/asciidoc/topics/proc_configuring_server_fips.adoc, documentation/src/main/asciidoc/topics/xml/server_ssl_identity_fips.xml, documentation/src/main/asciidoc/topics/yaml/server_ssl_identity_fips.yaml, server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/KeyStoreConfiguration.java, server/runtime/src/main/java/org/infinispan/server/configuration/security/KeyStoreConfigurationBuilder.java, server/runtime/src/main/java/org/infinispan/server/logging/Log.java, server/runtime/src/main/java/org/infinispan/server/security/KeyStoreUtils.java, server/runtime/src/main/resources/schema/infinispan-server-14.0.xsd
https://issues.redhat.com/browse/ISPN-13737
=> ISPN-13737 Allow configuring file-less keystores

build/configuration/pom.xml, commons/all/src/main/java/org/infinispan/commons/io/ByteBufferImpl.java, commons/all/src/main/java/org/infinispan/commons/io/UnsignedNumeric.java, commons/all/src/main/java/org/infinispan/commons/util/Util.java, core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/EntryInfo.java, core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java, core/src/main/java/org/infinispan/persistence/sifs/IndexRequest.java, core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java, core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java, core/src/main/java/org/infinispan/persistence/sifs/TemporaryTable.java, core/src/main/java/org/infinispan/persistence/sifs/configuration/IndexConfiguration.java, core/src/main/java/org/infinispan/reactive/FlowableCreate.java, core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java, core/src/test/java/org/infinispan/persistence/BaseNonBlockingStoreTest.java
https://issues.redhat.com/browse/ISPN-13576
https://issues.redhat.com/browse/ISPN-13601
Biggest change is now the index is prefixed by the UnsignedNumeric bytes of the segment. This then stores all of the entries for the given segment in an easy way to iterate over and finding the head is O(logN) time. I have included an optimization for iterating over the data with multiple segments as well, which is used by reducer methods.
Iterating over 2 of 256 segments from 200_000_000 entries stored in 3 index segments took only 800 ms versus the current (main) implementation which took 11.5 seconds.
I also ran some tests to count all of the entries across all segments over the same 200 million entries and the old implementation could not do it and ran out of memory, where as the new one was able …
=> ISPN-13576 SoftIndexFileStore segmentation can be made more performant

bin/list_command_ids.py, bin/utils.py, core/src/main/java/org/infinispan/commands/CommandsFactory.java, core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java, core/src/main/java/org/infinispan/commands/RemoteCommandsFactory.java, core/src/main/java/org/infinispan/commands/irac/IracTombstoneCleanupCommand.java, core/src/main/java/org/infinispan/commands/irac/IracTombstonePrimaryCheckCommand.java, core/src/main/java/org/infinispan/commands/irac/IracTombstoneRemoteSiteCheckCommand.java, core/src/main/java/org/infinispan/commands/irac/IracTombstoneStateResponseCommand.java, core/src/main/java/org/infinispan/container/versioning/irac/DefaultIracTombstoneManager.java, core/src/main/java/org/infinispan/container/versioning/irac/IracTombstoneInfo.java, core/src/main/java/org/infinispan/container/versioning/irac/IracTombstoneManager.java, core/src/main/java/org/infinispan/container/versioning/irac/NoOpIracTombstoneManager.java, core/src/main/java/org/infinispan/factories/ComponentRegistry.java, core/src/main/java/org/infinispan/marshall/exts/CacheRpcCommandExternalizer.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java, core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java, core/src/test/java/org/infinispan/xsite/irac/IracTombstoneCleanupTest.java, core/src/test/java/org/infinispan/xsite/irac/IracTombstoneUnitTest.java, core/src/test/java/org/infinispan/xsite/statetransfer/XSiteAutoStateTransferTest.java
Two changes are made in the commit:
* all tombstones are sent to the new owner.
* backup owner ping primary owner if there is tombstone stored without any update in IracManager.
https://issues.redhat.com/browse/ISPN-13495
offtopic, updated python script to python3
=> ISPN-13495 IRAC send tombstones in state transfer

core/src/main/java/org/infinispan/configuration/parsing/ParserRegistry.java, core/src/main/java/org/infinispan/factories/threads/DefaultThreadFactory.java, core/src/main/java/org/infinispan/factories/threads/SecurityActions.java, server/runtime/src/main/java/org/infinispan/server/Server.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedServer.java
https://issues.redhat.com/browse/ISPN-13505
This avoids leaks when the application lifecycle is shorter
than the cache manager lifecycle.
=> ISPN-13505 Set context classloader for worker threads explicitly

core/src/main/java/org/infinispan/statetransfer/CommitManager.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/test/java/org/infinispan/statetransfer/CommitManagerTest.java
https://issues.redhat.com/browse/ISPN-10706
After applying the received cache entries, the `StateConsumerImpl`
removes the applied entries from the `CommitManager` tracker.
=> ISPN-10706 Remove transferred cache entries from CommitManager tracker

core/src/main/java/org/infinispan/commands/remote/recovery/TxCompletionNotificationCommand.java, core/src/main/java/org/infinispan/statetransfer/StateTransferManager.java, core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java
https://issues.redhat.com/browse/ISPN-13798
=> ISPN-13798 Make TxCompletionNotificationCommand non blocking

core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java, core/src/main/java/org/infinispan/statetransfer/StateConsumer.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/main/java/org/infinispan/statetransfer/StateTransferManager.java, core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java, core/src/test/java/org/infinispan/statetransfer/DelegatingStateConsumer.java, core/src/test/java/org/infinispan/statetransfer/ManyTxsDuringStateTransferTest.java, core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java, core/src/test/java/org/infinispan/statetransfer/StateTransferSegmentMetricsTest.java
https://issues.redhat.com/browse/ISPN-12335
An initial efftort to expose some metrics during cache rebalance.
Here we are exposing only the number of inflight requests for segments
during a rebalance. To count the number of current request we use the number
of current `InboundTransferTask`. This value is around a synchronized block,
so I am not quite sure if is the best approach.
The test for `StateConsumer` was changed to verify the counter and a new
test was added to verify the counter on the `StateTransferManagerImpl`.
=> ISPN-12335 Expose rebalacing progress.

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/IndexNormalizerTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/MultipleIndexFieldAnnotationsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Book.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/testdomain/protobuf/Color.java
Quick fix renaming the classes to avoid conflict in the generated code. Suppose it was introduced because the conflicting class (Schema) was added in different PRs #10037 and #10041.
https://issues.redhat.com/browse/ISPN-13816
=> Fix classes name for the code generation

core/src/main/java/org/infinispan/configuration/global/CacheContainerConfiguration.java, core/src/main/java/org/infinispan/configuration/global/CacheContainerConfigurationBuilder.java, core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java, core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/main/java/org/infinispan/util/ByteString.java, core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
https://issues.redhat.com/browse/ISPN-13846
A follow-up of #10068 to make clear that the limitation originates from `ByteString`.
=> ISPN-13846 Creating cache with name more than 256 characters long fails

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodServerStartStopTest.java, commons/all/src/main/java/org/infinispan/commons/util/ImmutableListCopy.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodVersion.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/SecurityActions.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodDistributionTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodReplicationTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodTestingUtil.java
Hot Rod client uses "greater than" for comparison but topology ID resets on full cluster restart
https://issues.redhat.com/browse/ISPN-13813
https://issues.redhat.com/browse/ISPN-13833
=> ISPN-13813 Hot Rod client uses "greater than" for comparison but topology ID resets on full cluster restart

component-processor/src/main/java/org/infinispan/component/processor/external/JGroupsComponentProcessor.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
https://issues.redhat.com/browse/ISPN-13836
=> [13.0.x] ISPN-13836 NullPointerException in channelConnected callback

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/SocketTimeoutFailureRetryTest.java
https://issues.redhat.com/browse/ISPN-13216
* Changing to not close the socket when handling a
`SocketTimeoutException`.
* To facilitate testing the property
`ChannelPool#connectionFailureListener` is now package-private, so we
can intercept the call in the test and verify the socket is not closed. Not sure
how I feel about this.
=> ISPN-13216 Client should not close server connection after timeout

core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java, server/tests/src/test/java/org/infinispan/server/functional/RestMetricsResource.java
https://issues.redhat.com/browse/ISPN-13871
Always using the cache name as label. Previously only one of the caches is exported, in this approach we have that metrics are exported:
```text
vendor_cache_manager_default_cache_some_name_statistics_stores{cache="some-name",node="jbolina-35119",} 0.0
vendor_cache_manager_default_cache_some_name_statistics_stores{cache="some/name",node="jbolina-35119",} 0.0
```
That would only happen in edge cases where the cache names differ only by non-alphanumerical characters. The [docs](https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels) states to not overuse labels, but I guess that is ok for our case.
=> ISPN-13871 Prometheus metrics exported incorrectly

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
ConcurrentModificationException happens when cross-site replication and
metrics are enabled because both channels start at the same time.
https://issues.redhat.com/browse/ISPN-13903
=> ISPN-13903 CME for a joining node with xsite

build/configuration/pom.xml, cli/src/main/java/org/infinispan/cli/commands/rest/Index.java, cli/src/main/resources/help/index.adoc, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdmin.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheManagerAdminImpl.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/SchemaIndexUpdateTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/Model.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/ModelA.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/ModelB.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/SchemaA.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/SchemaB.java, client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java, counter/src/main/java/org/infinispan/counter/EmbeddedCounterManagerFactory.java, counter/src/main/java/org/infinispan/counter/impl/CounterModuleLifecycle.java, query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java, query/src/main/java/org/infinispan/query/impl/LifecycleManager.java, query/src/main/java/org/infinispan/query/logging/Log.java, query/src/main/java/org/infinispan/search/mapper/mapping/SearchMapping.java, query/src/main/java/org/infinispan/search/mapper/mapping/SearchMappingBuilder.java, query/src/main/java/org/infinispan/search/mapper/mapping/impl/InfinispanMapping.java, query/src/test/java/org/infinispan/query/helper/SearchMappingHelper.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java, server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/CacheUpdateIndexSchemaTask.java, server/core/src/main/java/org/infinispan/server/core/admin/embeddedserver/EmbeddedServerAdminOperationHandler.java, server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java, server/runtime/src/main/java/org/infinispan/server/tasks/admin/ServerAdminOperationsHandler.java
https://issues.redhat.com/browse/ISPN-13648
I added [this commit](https://github.com/infinispan/infinispan/pull/10114/commits/5dd6f794a2646f8777e1039f9b0b2569b7069e8c), since with it I'm not still be able to run HotRod tests on indexes from the IDE.
=> ISPN-13648 Schema evolution with respect to indices without downtime

commons/all/src/main/java/org/infinispan/commons/io/ByteBuffer.java, commons/all/src/main/java/org/infinispan/commons/io/ByteBufferImpl.java, core/pom.xml, core/src/main/java/org/infinispan/configuration/global/TransportConfiguration.java, core/src/main/java/org/infinispan/configuration/global/TransportConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/parsing/Attribute.java, core/src/main/java/org/infinispan/configuration/parsing/Parser.java, core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java, core/src/main/java/org/infinispan/remoting/transport/AbstractDelegatingTransport.java, core/src/main/java/org/infinispan/remoting/transport/Transport.java, core/src/main/java/org/infinispan/remoting/transport/impl/EmptyRaftManager.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsRaftManager.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsStateMachineAdapter.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/RaftUtil.java, core/src/main/java/org/infinispan/remoting/transport/raft/RaftChannel.java, core/src/main/java/org/infinispan/remoting/transport/raft/RaftChannelConfiguration.java, core/src/main/java/org/infinispan/remoting/transport/raft/RaftManager.java, core/src/main/java/org/infinispan/remoting/transport/raft/RaftStateMachine.java, core/src/main/java/org/infinispan/remoting/transport/raft/package-info.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/main/resources/schema/infinispan-config-14.0.xsd, core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java, core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java, core/src/test/java/org/infinispan/remoting/RaftTest.java, core/src/test/java/org/infinispan/remoting/transport/MockTransport.java, core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java, core/src/test/resources/configs/all/14.0.xml, pom.xml
A very basic RAFT abstraction using jgroups-raft. Most of the features
are missing and they will be added later.
https://issues.redhat.com/browse/ISPN-13615
Review notes: the goal for this PR is the introduction of the APIs. I tried to keep them isolated from the "user space" but RAFT is highly coupled with the `Transport`. Open to suggestions here...
Missing features:
* Persistence
JGroups-raft uses LevelDB for persisted logs. Future work involves moving from LevelDB to RocksDB. Also, I'm thinking about adding a "file-based log" to be used when the RocksDB jar is not available (to avoid adding a new dependency).
* Dynamic membership
For the server, add to the REST endpoint a resource to add and remove RAFT members. Extend this work to CLI and Console.
=> ISPN-13615 Create RAFT abstraction

core/src/main/java/org/infinispan/cache/impl/CacheImpl.java, core/src/main/java/org/infinispan/commands/CommandsFactory.java, core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java, core/src/main/java/org/infinispan/commands/RemoteCommandsFactory.java, core/src/main/java/org/infinispan/commands/read/SizeCommand.java, core/src/main/java/org/infinispan/container/impl/AbstractDelegatingInternalDataContainer.java, core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java, core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java, core/src/main/java/org/infinispan/container/impl/InternalDataContainer.java, core/src/main/java/org/infinispan/factories/ComponentRegistry.java, core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/ClusteringInterceptor.java, core/src/main/java/org/infinispan/marshall/exts/CacheRpcCommandExternalizer.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManager.java, core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java, core/src/main/java/org/infinispan/persistence/support/DelegatingPersistenceManager.java, core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManager.java, core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java, core/src/main/java/org/infinispan/reactive/publisher/impl/LocalClusterPublisherManagerImpl.java, core/src/main/java/org/infinispan/reactive/publisher/impl/LocalPublisherManager.java, core/src/main/java/org/infinispan/reactive/publisher/impl/LocalPublisherManagerImpl.java, core/src/test/java/org/infinispan/api/SizeOptimizationTests.java, core/src/test/java/org/infinispan/container/SimpleDataContainerTest.java, core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
https://issues.redhat.com/browse/ISPN-9366
Optimizing for the cases where:
1. Store is shared
2. No store in use, no expired entries and `CACHE_MODE_LOCAL` is set
3. Store is private and `CACHE_MODE_LOCAL` is set
In such cases we can use the `size` method from the data container directly.
=> ISPN-9366 Cache.size optimizations

commons-test/src/main/java/org/infinispan/commons/lambda/NamedLambdas.java, core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java, core/src/main/java/org/infinispan/persistence/sifs/IndexRequest.java, core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java, core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java
https://issues.redhat.com/browse/ISPN-13931
Persist the file stats upon shutdown so upon restart we know what the previous free space was.
The test passes however there is still an issue with the case when the stats file is not present that the free space is not read in properly afaik. I am still trying to fix this last part, as it is required for migration of existing directories and should clean those up if they have old files lying around.
=> ISPN-13931 SoftIndexFileStore is increasing the size of the data folder

documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc
JIRA: https://issues.redhat.com/browse/ISPN-13981
=> ISPN-13981: Restore the Enabling JMX remote ports module on the 13.0.x branch

core/src/main/java/org/infinispan/security/actions/AddCacheManagerListenerAsyncAction.java, core/src/main/java/org/infinispan/security/actions/AddLoggerListenerAsyncAction.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/main/java/org/infinispan/util/logging/events/impl/BaseEventLog.java, core/src/main/java/org/infinispan/util/logging/events/impl/DecoratedEventLogger.java, documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc, server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java, server/rest/src/main/java/org/infinispan/rest/resources/SecurityActions.java, server/rest/src/test/java/org/infinispan/rest/resources/SSEListener.java, server/rest/src/test/java/org/infinispan/rest/resources/WeakSSEListener.java, server/runtime/src/main/java/org/infinispan/server/logging/events/ServerEventImpl.java, server/runtime/src/test/java/org/infinispan/server/configuration/ServerEventLoggerTest.java, server/tests/src/test/java/org/infinispan/server/functional/RestOperations.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
https://issues.redhat.com/browse/ISPN-13834
* Created an endpoint to listen for lifecycle events at
`/rest/v2/container?action=listen`. The old endpoint still exists. We
listen for logs produced with the `ServerEventLogger`.
* The current endpoint only publishes events logged with LIFECYCLE
category.
* Currently we only publish the event in the JSON format. We need more
work to handle properly the `Accept` HTTP header.
* Currently we publish all events received by the logger. There is room
for future improvement to listen only events for the node which is
serving the request.
=> ISPN-13834 Create single REST endpoint for all container events

server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java, server/rest/src/main/java/org/infinispan/rest/cachemanager/SecurityActions.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
https://issues.redhat.com/browse/ISPN-12192
Should have used the security action to retrieve the executor.
=> ISPN-12912 Data Distribution endpoint for caches

server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestClient.java, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestMethodRule.java, server/testdriver/junit4/src/test/java/org/infinispan/server/test/junit4/InfinispanRuleBasicTest.java
We don't need to force the client to use HotRod 3.1 anymore, a 4.0 client can work with a 3.1 server thanks to the version negotiation
=> ISPN-13725 Revert changes on InfinispanRuleBasicTest

commons/all/src/main/java/org/infinispan/commons/configuration/io/xml/XmlConfigurationWriter.java, commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationWriter.java, core/src/main/java/org/infinispan/configuration/parsing/ParserRegistry.java, core/src/main/java/org/infinispan/util/logging/events/EventLogSerializer.java, core/src/test/java/org/infinispan/util/EventLogSerializerTest.java, documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc, server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java, server/rest/src/test/java/org/infinispan/rest/resources/SSEListener.java, server/rest/src/test/java/org/infinispan/rest/resources/WeakSSEListener.java, server/tests/src/test/java/org/infinispan/server/functional/RestContainerListenerTest.java
https://issues.redhat.com/browse/ISPN-13873
* Created an `EventLog` serializer using the
`ConfigurationSerializer` interface.
I am using the stuff that we already have to serialize configuration, since that can handle the `EventLog` object, but pretty much all of the serialization classes have `Configuration` in the name.
Now we have:
```json
{
"log" : {
"instant" : "2022-07-26T11:33:08.666580Z",
"category" : "LIFECYCLE",
"content" : {
"level" : "INFO",
"message" : "ISPN100010: Finished rebalance with members [jbolina-34174, jbolina-58560], topology id 2"
},
"additional" : {
"context" : "caching-listen",
"scope" : "jbolina-58560",
"detail" : null,
"who" : null
}
}
}
```
```yaml
log: 
instant: "2022-07-26T11:11:22.912906Z"
category: "LIFECYCLE"
content: 
level: "INFO"
message: "ISPN100002: …
```
=> ISPN-13873 Handle Accept header to serialize the events

cli/src/main/java/org/infinispan/cli/Context.java, cli/src/main/java/org/infinispan/cli/commands/Config.java, cli/src/main/java/org/infinispan/cli/impl/ContextImpl.java, cli/src/main/resources/help/config.adoc
https://issues.redhat.com/browse/ISPN-14040
=> ISPN-14040 CLI config reset

core/src/main/java/org/infinispan/interceptors/distribution/ScatteredDistributionInterceptor.java, core/src/test/java/org/infinispan/distribution/DistSyncFuncTest.java, core/src/test/java/org/infinispan/scattered/ScatteredSyncFuncTest.java, core/src/test/java/org/infinispan/scattered/SingleNodeScatteredTest.java
https://issues.redhat.com/browse/ISPN-14035
* Fix NPE when using `putAll` with only a single node.
=> ISPN-14035 Scattered mode NPE with single address in CH

server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14010
~When manually changing the cluster availability we wait to everyone to handle the update before returning the response.~
The test uses an eventually to verify that the cluster availability changes.
=> ISPN-14010 Fix test failures on REST operations for availability

server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerRule.java, server/tests/src/test/java/org/infinispan/server/security/TransportTLSIT.java, server/tests/src/test/resources/configuration/TransportTLSTest.xml, server/tests/src/test/resources/configuration/cache-container/clustered-tls.xml, server/tests/src/test/resources/configuration/security/tls-transport.xml
https://issues.redhat.com/browse/ISPN-14050
=> ISPN-14050 Create test for TLS in transport

core/src/main/java/org/infinispan/conflict/impl/DefaultConflictManager.java, core/src/main/java/org/infinispan/conflict/impl/StateReceiverImpl.java, core/src/main/java/org/infinispan/statetransfer/InboundTransferTask.java, core/src/test/java/org/infinispan/conflict/impl/ConflictManagerTest.java
https://issues.redhat.com/browse/ISPN-14084
~An initial PR trying to debug the problem. At this point I am trying to use the CI to debug the problem.~
After some debugging, there are some cases when a rehash event is issued during the tests. The rehash listener will start canceling all current segment transfers and complete the future with a `CacheException`. Since the `InboundTransferTask`s are canceled before completing the future, the `InboundTransferTask`'s callback would invoke `cancel` again, which could lead the future completion with a `CancellationException` instead of the `CacheException`.
I only moved to first complete the future and only then cancel the tasks.
Also, includes a change to the `DefaultConflictManager`, because, in the scenario above, the `CancellationException` …
=> ISPN-14084 MergePolicyCustomTest - Inbound transfer was cancelled

server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/tests/src/test/java/org/infinispan/server/security/authentication/RespAuthentication.java
* ERR for any command arguments
https://issues.redhat.com/browse/ISPN-14064
=> ISPN-14064 RESP server should implement COMMAND command

query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java, query/src/test/java/org/infinispan/query/api/PutAllTest.java
https://issues.redhat.com/browse/ISPN-14115
Without the commit https://github.com/infinispan/infinispan/pull/10292/commits/ac8ab8491ee41ebd6780d05e72764d8f86fbbc58 the reproducer hangs running the script on my local machine:
``` sh
#!/bin/bash
mvn clean install -pl query -am -DskipTests
mvn clean install -pl query
```
let me know if it is the same for you.
=> ISPN-14115 Potential deadlock in index writer threads under heavy load

core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/EntryHeader.java, core/src/main/java/org/infinispan/persistence/sifs/EntryInfo.java, core/src/main/java/org/infinispan/persistence/sifs/EntryRecord.java, core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java, core/src/main/java/org/infinispan/persistence/sifs/IndexRequest.java, core/src/test/java/org/infinispan/persistence/AsyncStoreParallelIterationTest.java, core/src/test/java/org/infinispan/persistence/DummyStoreParallelIterationTest.java, core/src/test/java/org/infinispan/persistence/ParallelIterationTest.java, core/src/test/java/org/infinispan/persistence/SoftIndexFileStoreParallelIterationTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFunctionalTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreStressTest.java, core/src/test/java/org/infinispan/test/TestBlocking.java
https://issues.redhat.com/browse/ISPN-14104
https://issues.redhat.com/browse/ISPN-13751
https://issues.redhat.com/browse/ISPN-13387
=> [13.0.x] SIFS fixes

client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestMetricsClientOkHttp.java, core/src/main/java/org/infinispan/metrics/impl/BaseAdditionalMetrics.java, core/src/main/java/org/infinispan/metrics/impl/BaseMemoryAdditionalMetrics.java, core/src/main/java/org/infinispan/metrics/impl/BaseOperatingSystemAdditionalMetrics.java, core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java, core/src/main/java/org/infinispan/metrics/impl/VendorAdditionalMetrics.java, core/src/test/java/org/infinispan/metrics/ClusteredCacheManagerMetricsTest.java, server/rest/src/main/java/org/infinispan/rest/resources/MetricsResource.java, server/rest/src/test/java/org/infinispan/rest/metric/MetricsRestTest.java
https://issues.redhat.com/browse/ISPN-14164
https://issues.redhat.com/browse/JDG-5583
=> ISPN-14164 Fix metrics produced by the Infinispan server for Prometheus scraping

persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/QueriesJdbcStore.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/configuration/AbstractSchemaJdbcConfiguration.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/configuration/AbstractSchemaJdbcConfigurationBuilder.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/configuration/QueriesJdbcConfigurationBuilder.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/configuration/QueriesJdbcStoreConfigurationBuilder.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/configuration/SchemaJdbcConfigurationBuilder.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/configuration/SqlSerializerUtil.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/configuration/SqlStoreConfigurationParser.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/configuration/TableJdbcStoreConfigurationBuilder.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcJoinTest.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcStoreFunctionalTest.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/configuration/ConfigurationSerializerTest.java
https://issues.redhat.com/browse/ISPN-14163
=> ISPN-14163 Make SQL schema configuration builder fluent

documentation/src/main/asciidoc/topics/con_listening_all_addresses.adoc, server/hotrod/src/main/java/org/infinispan/server/hotrod/MultiHomedServerAddress.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/InetAddressWithNetMaskTest.java
https://issues.redhat.com/browse/ISPN-14171
=> ISPN-14171 Support RFC 6598 shared address space addresses

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/JsonKeyValueRawEventsTest.java, core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java, core/src/test/java/org/infinispan/test/data/Person.java, persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/TwoWayPersonKey2StringMapper.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/QueriesJdbcStore.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/TableJdbcStore.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcJoinTest.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcStoreFunctionalTest.java, server/core/src/test/java/org/infinispan/server/core/dataconversion/JsonTranscoderTest.java
https://issues.redhat.com/browse/ISPN-14138
=> ISPN-14138 SQL Store fail to persist numbers with fractional portion

documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc
JIRA: https://issues.redhat.com/browse/ISPN-14082
**Needs backport to 13.0.**
=> ISPN-14082: Document cache naming character limits

commons/all/src/main/java/org/infinispan/commons/util/ConcurrentSmallIntSet.java, commons/all/src/main/java/org/infinispan/commons/util/IntSets.java, core/src/main/java/org/infinispan/commands/irac/IracPutManyCommand.java, core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
* Includes change to ConcurrentSmallIntSet preventing wrong constructor argument
https://issues.redhat.com/browse/ISPN-14192
=> ISPN-14192 Do not send empty batches with IRAC

documentation/src/main/asciidoc/topics/json/rest_full_cache_data_distribution.json, documentation/src/main/asciidoc/topics/ref_rest_caches.adoc, server/rest/proto.lock, server/rest/src/main/java/org/infinispan/rest/distribution/CacheDistributionInfo.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14129
Using the same value exposed in the stats.
=> ISPN-14129 Memory used by a node and cache in the distribution endpoint

anchored-keys/src/main/java/org/infinispan/anchored/impl/AnchoredDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/distribution/NonTxDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/distribution/TriangleDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/AbstractIracLocalSiteInterceptor.java, core/src/main/java/org/infinispan/interceptors/impl/ClusteringInterceptor.java, core/src/main/java/org/infinispan/util/CacheTopologyUtil.java, core/src/test/java/org/infinispan/xsite/irac/IracOwnershipChangeTest.java
https://issues.redhat.com/browse/ISPN-14219
=> ISPN-14219 IRAC: NPE on topology change during write command

server/memcached/pom.xml, server/memcached/src/main/java/org/infinispan/server/memcached/LifecycleCallbacks.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoder.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoderState.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedMetadata.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedOperation.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedServer.java, server/memcached/src/main/java/org/infinispan/server/memcached/PersistenceContextInitializer.java, server/memcached/src/main/java/org/infinispan/server/memcached/TextProtocolUtil.java, server/memcached/src/main/java/org/infinispan/server/memcached/configuration/MemcachedServerConfiguration.java, server/memcached/src/main/java/org/infinispan/server/memcached/configuration/MemcachedServerConfigurationBuilder.java, server/memcached/src/main/java/org/infinispan/server/memcached/configuration/package-info.java, server/memcached/src/main/java/org/infinispan/server/memcached/logging/Log.java, server/memcached/src/test/java/org/infinispan/server/memcached/test/MemcachedBlockHoundIntegration.java, server/tests/src/test/java/org/infinispan/server/functional/MemcachedOperations.java
https://issues.redhat.com/browse/ISPN-14207
=> ISPN-14207 Make MemcachedDecoder non blocking

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/maxresult/RemoteDefaultMaxResultTest.java, core/src/main/java/org/infinispan/configuration/cache/AbstractConfigurationChildBuilder.java, core/src/main/java/org/infinispan/configuration/cache/Configuration.java, core/src/main/java/org/infinispan/configuration/cache/ConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/ConfigurationChildBuilder.java, core/src/main/java/org/infinispan/configuration/cache/QueryConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/QueryConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/parsing/Attribute.java, core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java, core/src/main/java/org/infinispan/configuration/parsing/Element.java, core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java, core/src/main/resources/schema/infinispan-config-14.0.xsd, core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java, core/src/test/resources/configs/all/14.0.xml, documentation/src/main/asciidoc/topics/ref_query_ickle.adoc, documentation/src/main/asciidoc/topics/upgrading.adoc, query-core/src/main/java/org/infinispan/query/core/impl/EmbeddedQuery.java, query-core/src/main/java/org/infinispan/query/core/impl/HybridQuery.java, query-core/src/main/java/org/infinispan/query/core/impl/QueryEngine.java, query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java, query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java, query/src/main/java/org/infinispan/query/impl/IndexedQueryImpl.java, query/src/main/java/org/infinispan/query/impl/QueryDefinition.java, query/src/test/java/org/infinispan/query/maxresult/CustomDefaultMaxResultTest.java, query/src/test/java/org/infinispan/query/maxresult/EmbeddedDefaultMaxResultTest.java, query/src/test/java/org/infinispan/query/model/NonIndexedGame.java, server/rest/src/test/java/org/infinispan/rest/search/SearchCountClusteredTest.java
https://issues.redhat.com/browse/ISPN-14194
~~Just the first step, that is adding the config property for it.~~ ready for the review
I'm writing the documentation
=> ISPN-14194 Add config property for default max result

core/src/main/java/org/infinispan/util/concurrent/CompletionStages.java, core/src/test/java/org/infinispan/distribution/DistributionTestHelper.java, server/resp/pom.xml, server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespLettuceHandler.java, server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespTwoNodeTest.java
https://issues.redhat.com/browse/ISPN-14242
https://issues.redhat.com/browse/ISPN-14245
https://issues.redhat.com/browse/ISPN-14250
=> [14.0.x] ISPN-14242 RESP server can send results in incorrect order

documentation/src/main/asciidoc/stories/assembly_deployment_planning.adoc, documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc, documentation/src/main/asciidoc/topics/con_performance_metrics_considerations.adoc
backports #10423 
https://issues.redhat.com/browse/ISPN-14213
=> [14.0.x] Add a statement why we provide no performance numbers

documentation/src/main/asciidoc/titles/embedding/stories.adoc, documentation/src/main/asciidoc/topics/proc_cli_statistics.adoc, documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc
Backports #10421
https://issues.redhat.com/browse/ISPN-14267 
fixes docs formatting
includes rbac content in the embedded guide
=> [14.0.x]ISPN-14267-14 fix docs formatting 

client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestServerClientOkHttp.java, documentation/src/main/asciidoc/topics/ref_rest_servers.adoc, server/core/src/main/java/org/infinispan/server/core/ServerStateManager.java, server/core/src/test/java/org/infinispan/server/core/DummyServerStateManager.java, server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java, server/runtime/src/main/java/org/infinispan/server/state/ServerStateManagerImpl.java, server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
https://issues.redhat.com/browse/ISPN-14233
~Returning something like:~
```json
[
{
"node_name":"ClusterResourceTest-NodeA",
"transport":{
"io-threads":6,
"receive-buffer-size":0,
"global-connections":1,
"total-bytes-read":707,
"port":38567,
"pending-tasks":0,
"total-bytes-written":1501,
"host":"localhost",
"send-buffer-size":0,
"local-connections":1
}
},
{
"node_name":"ClusterResourceTest-NodeB",
"transport":{
"io-threads":6,
"receive-buffer-size":0,
"global-connections":1,
"total-bytes-read":0,
"port":46363,
"pending-tasks":0,
"total-bytes-written":0,
"host":"localhost",
"send-buffer-size":0,
"local-connections":0
}
}
]
```
---
Updated:
Added an endpoint that receives a node name and downloads the referenced node's report.
=> ISPN-14233 REST API makes it possible to download any server report

documentation/src/main/asciidoc/topics/json/distributed_cache.json, documentation/src/main/asciidoc/topics/json/replicated_cache.json, documentation/src/main/asciidoc/topics/proc_creating_caches_cli.adoc, documentation/src/main/asciidoc/topics/ref_cli_resource_tree.adoc, documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc, documentation/src/main/asciidoc/topics/ref_listeners_synchronicity.adoc, documentation/src/main/asciidoc/topics/xml/distributed_cache.xml, documentation/src/main/asciidoc/topics/xml/replicated_cache.xml, documentation/src/main/asciidoc/topics/yaml/distributed_cache.yaml, documentation/src/main/asciidoc/topics/yaml/replicated_cache.yaml
https://issues.redhat.com/browse/ISPN-14273
backports #10427 
Fixes docs errors
updates config examples for distributed and replicated caches
=> [14.0.x]ISPN-14273 fixes docs errors and config examples in the CLI guide

documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_query.adoc, documentation/src/main/asciidoc/topics/protobuf/person-db-table.proto, documentation/src/main/asciidoc/topics/ref_sql_store_query_configuration.adoc, documentation/src/main/asciidoc/topics/sql/person.sql, documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
https://issues.redhat.com/browse/ISPN-14278
Updates examples in the sql store docs
Based on feedback from @gustavolira
=> ISPN-14278 fix erros in the SQL store examples

documentation/src/main/asciidoc/topics/yaml/server_ldap_realm.yaml
https://issues.redhat.com/browse/ISPN-14290
Remove apostrophe from the ldap config example
Needs backport to 14.0.x and 13.0.x
=> ISPN-14290 fix ldap yaml config example

documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
This originated downstream https://issues.redhat.com/browse/ISPN-14331
It's necessary to add a note that resp protocol endpoint is a tech preview feature
=> ISPN-14331 downstream: note that resp is a tech preview

cli/src/main/java/org/infinispan/cli/commands/CLI.java, cli/src/main/java/org/infinispan/cli/commands/Run.java, cli/src/main/java/org/infinispan/cli/commands/kubernetes/Shell.java, cli/src/main/java/org/infinispan/cli/impl/CliShell.java, cli/src/main/java/org/infinispan/cli/impl/KubeShell.java, cli/src/main/java/org/infinispan/cli/impl/StreamShell.java, cli/src/main/java/org/infinispan/cli/logging/Messages.java, cli/src/test/java/org/infinispan/cli/CliPipeTest.java, commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationWriter.java, server/rest/src/main/java/org/infinispan/rest/resources/BackupManagerResource.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java, server/runtime/src/main/java/org/infinispan/server/Server.java, server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointsConfigurationBuilder.java, server/runtime/src/main/java/org/infinispan/server/logging/Log.java, server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
https://issues.redhat.com/browse/ISPN-14256 Fix the CLI batch test
https://issues.redhat.com/browse/ISPN-14315 ConfigurationWriter should ignore media type parameters
https://issues.redhat.com/browse/ISPN-14316 Correctly pass arguments to report script
https://issues.redhat.com/browse/ISPN-14317 Server Backup creation should work even without JSON content
https://issues.redhat.com/browse/ISPN-14327 Allow overriding server endpoint
=> [14.0] Backport circus

core/src/main/java/org/infinispan/metrics/config/MicrometerMeterRegisterConfigurationBuilder.java, core/src/main/java/org/infinispan/metrics/config/MicrometerMeterRegistryConfiguration.java, core/src/main/java/org/infinispan/metrics/config/MicrometerMeterRegistryConfigurationSerializer.java, core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java, server/rest/src/main/java/org/infinispan/rest/resources/MetricsResource.java
https://issues.redhat.com/browse/ISPN-14341
main branch PR: https://github.com/infinispan/infinispan/pull/10482
=> [14.x] ISPN-14341 Allow injecting a MeterRegistry instance

core/src/main/java/org/infinispan/marshall/core/BytesObjectOutput.java
https://issues.redhat.com/browse/ISPN-14348
Created a benchmark specifically for this at https://github.com/infinispan/infinispan-benchmarks/blob/main/getputremovetest/src/main/java/org/infinispan/UtfBenchmark.java
Results can be found at https://docs.google.com/spreadsheets/d/1OqHPU1KFk1MEWsuunIB9qIGQyfOI9ZQ5GmSW1K7gKDE/edit#gid=1177069475
For latin based characters it is anywhere from 20% (1 byte) to 240% (~3MB) increase in performance compared to main.
For multi byte characters the test showed usually 15-40% improvement except one test which was 3% loss in performance. Overall it should be much better than before.
=> ISPN-14348 BytesObjectOutput.writeUTF performance improvements

query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
https://issues.redhat.com/browse/ISPN-14406
=> ISPN-14406 Synchronize the partial reindex with refresh and flush

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemotePublisher.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/SegmentKeyTracker.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/SegmentKeyTrackerTest.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/iteration/RemotePublisher.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/iteration/SegmentKeyTracker.java, commons/all/src/main/java/org/infinispan/commons/util/ConcurrentSmallIntSet.java
https://issues.redhat.com/browse/ISPN-14428
A couple of things here:
* Key tracker allows duplicates;
* The IntSet keeping track segments not completed;
The latter I guess is a visibility issue. We have only a single outstanding request for each target, but we have a concurrency of # of target servers. We update by removing the completed segments when a response is received, and the flowable uses the segment again to request the not completed. Not sure how to create a test for this, tough.
A log from a local execution:
```
18:18:42.200 INFO [org.jabolina.playground.TestHotRodClient] (1) SIZE: 10
18:18:42.200 INFO [org.infinispan.client.hotrod.impl.iteration.RemotePublisher] (15) [HotRod-client-async-pool-1-1] Segments left to process are {60-62 79-91 103-107 113-115 117-122 187-202 205 …
```
=> ISPN-14428 size() and keySet() are not reliable and return fuzzy results

.github/workflows/sync_docs.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/OpenTelemetryClient.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/TracingDisabledTest.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/HotRodConfiguration.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/HotRodConfigurationBuilder.java, client/hotrod/src/main/java/org/infinispan/hotrod/configuration/package-info.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/ConfigurationProperties.java
https://issues.redhat.com/browse/ISPN-14426
=> ISPN-14426 Allow to disable tracing propagation on HotRod client

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemotePublisher.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/SegmentKeyTracker.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/SegmentKeyTrackerTest.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/iteration/RemotePublisher.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/iteration/SegmentKeyTracker.java, commons/all/src/main/java/org/infinispan/commons/util/ConcurrentSmallIntSet.java
https://issues.redhat.com/browse/ISPN-14428
=> [14.0.x] ISPN-14428 size() and keySet() are not reliable and return fuzzy results

client/rest-client/src/main/java/org/infinispan/client/rest/RestTaskClient.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestTaskClientOkHttp.java, documentation/src/main/asciidoc/topics/ref_rest_server_tasks.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_tasks_download.adoc, documentation/src/main/asciidoc/topics/rest_examples/get_v2_tasks_exec.adoc, server/rest/src/main/java/org/infinispan/rest/logging/Log.java, server/rest/src/main/java/org/infinispan/rest/resources/TasksResource.java, server/rest/src/test/java/org/infinispan/rest/resources/TasksResourceTest.java, server/runtime/src/main/java/org/infinispan/server/tasks/DistributedServerTask.java, server/runtime/src/main/java/org/infinispan/server/tasks/DistributedServerTaskRunner.java, tasks/manager/src/test/java/org/infinispan/tasks/DummyTaskEngine.java, tasks/manager/src/test/java/org/infinispan/tasks/TaskManagerTest.java
https://issues.redhat.com/browse/ISPN-14488
https://issues.redhat.com/browse/ISPN-14489
=> ISPN-14488 REST Task execution with cache

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-14476
Backport of https://github.com/infinispan/infinispan/pull/10599
=> [14.x] ISPN-14476: Bump JGroups to 5.2.12.Final

spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/session/SessionUpdateRemappingFunctionProtoAdapter.java, spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanSessionRepositoryTCK.java, spring/spring5/spring5-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepositoryTest.java, spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepositoryTest.java, spring/spring6/spring6-common/src/main/java/org/infinispan/spring/common/session/SessionUpdateRemappingFunctionProtoAdapter.java, spring/spring6/spring6-common/src/test/java/org/infinispan/spring/common/session/InfinispanSessionRepositoryTCK.java, spring/spring6/spring6-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedProtostreamSessionRepositoryTest.java, spring/spring6/spring6-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepositoryTest.java, spring/spring6/spring6-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteProtostreamSessionRepositoryTest.java, spring/spring6/spring6-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepositoryTest.java
Added more tests to cover the change tracking in `InfinispanSession`. Specifically, ensure that the session attributes, max inactive duration and last accessed time are updated in the Infinispan cache if they are changed. Also, added tests for the various FlushMode and SaveMode settings.
Fixed a `NullPointerException` in `SessionUpdateRemappingFunctionProtoAdapter` which occurred when a session attribute was removed, i.e. the `SessionAttribute` value was null.
Fixed a serialisation issue `SessionUpdateRemappingFunctionProtoAdapter` which caused the last accessed time to be set to the epoch value if the session's last accessed time hadn't been changed.
=> ISPN-14477 Tests for concurrent Spring session access

spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/session/SessionUpdateRemappingFunctionProtoAdapter.java, spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanSessionRepositoryTCK.java, spring/spring5/spring5-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepositoryTest.java, spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepositoryTest.java, spring/spring6/spring6-common/src/main/java/org/infinispan/spring/common/session/SessionUpdateRemappingFunctionProtoAdapter.java, spring/spring6/spring6-common/src/test/java/org/infinispan/spring/common/session/InfinispanSessionRepositoryTCK.java, spring/spring6/spring6-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedProtostreamSessionRepositoryTest.java, spring/spring6/spring6-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepositoryTest.java, spring/spring6/spring6-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteProtostreamSessionRepositoryTest.java, spring/spring6/spring6-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepositoryTest.java
Added more tests to cover the change tracking in `InfinispanSession`. Specifically, ensure that the session attributes, max inactive duration and last accessed time are updated in the Infinispan cache if they are changed. Also, added tests for the various FlushMode and SaveMode settings.
Fixed a `NullPointerException` in `SessionUpdateRemappingFunctionProtoAdapter` which occurred when a session attribute was removed, i.e. the `SessionAttribute` value was null.
Fixed a serialisation issue `SessionUpdateRemappingFunctionProtoAdapter` which caused the last accessed time to be set to the epoch value if the session's last accessed time hadn't been changed.
=> [14.0] ISPN-14477 Tests for concurrent Spring session access

documentation/src/main/asciidoc/stories/assembly_migrating_data.adoc, documentation/src/main/asciidoc/titles/upgrading/upgrading.asciidoc, documentation/src/main/asciidoc/topics/con_store_migrator.adoc, documentation/src/main/asciidoc/topics/proc_configuring_store_migrator.adoc, documentation/src/main/asciidoc/topics/proc_migrating_cache_stores.adoc, documentation/src/main/asciidoc/topics/ref_store_migrator_properties.adoc
https://issues.redhat.com/browse/ISPN-14522
Docs revision for the store migrator
Add information about configuring the number of segments for segmented cache stores
=> ISPN-14522 store migrator docs updates

documentation/src/main/asciidoc/topics/con_protobuf_encoding.adoc, documentation/src/main/asciidoc/topics/json/off_heap_memory.json
https://issues.redhat.com/browse/ISPN-14541 & https://issues.redhat.com/browse/ISPN-14540
needs backport to 14.0.x
Docs:
Protobuf does not support circular objects
Fix config example
=> ISPN-14541 Note about marshalling circular objects

documentation/src/main/asciidoc/topics/con_protobuf_encoding.adoc, documentation/src/main/asciidoc/topics/json/off_heap_memory.json
Backports #10676 
https://issues.redhat.com/browse/ISPN-14541 & https://issues.redhat.com/browse/ISPN-14540
needs backport to 14.0.x
Docs:
Protobuf does not support circular objects
Fix config example
=> [14.0.x] ISPN-14541 Note about marshalling circular objects

server/core/src/main/java/org/infinispan/server/core/transport/NativeTransport.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespLettuceHandler.java, server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java
https://issues.redhat.com/browse/ISPN-14579
https://issues.redhat.com/browse/ISPN-14580
=> ISPN-14579 Various RESP commands are requesting wrong size for buffer

server/runtime/src/main/java/org/infinispan/server/Server.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
https://issues.redhat.com/browse/ISPN-14573
Backporting the changes to the container and report method, but 14.0.x doesn't seem to have the failing test.
=> [14.0.x] ISPN-14573 AbstractAuthorization.testRestServerNodeReport is failing

server/resp/src/main/java/org/infinispan/server/resp/BaseRespDecoder.java, server/resp/src/main/java/org/infinispan/server/resp/ByteBufPool.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java, server/resp/src/test/java/org/infinispan/server/resp/RespDecoderTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespTwoNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/test/CommonRespTests.java, server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/RespDetector.java
https://issues.redhat.com/browse/ISPN-14583
This change makes it so that the Handler itself never writes to the context or channel directly. Instead, the various handlers can request a ByteBuf from a "pool" that can be a cached buffer for the given channel. This allows for pipelined commands to write to the same buffer before flushing either when the end of the pipeline is found or if the channel outbound buffer would be too full.
To support backpressure and having a client may not keep up we check for channel writability and will disable auto read if it is full and resume as necessary when the outbound buffer can be written to again.
=> ISPN-14583 RESP endpoint should bundle flush calls to allow pipelining

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/evolution/IndexSchemaNoDowntimeUpgradeTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/evolution/model/BaseModelIndexAttributesChangedEntity.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/evolution/model/BaseModelIndexAttributesEntity.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/evolution/model/ModelUtils.java
This PR adds index attributes migration scenarios with regards of no-downtime into the testsuite. 
- changing `projectable`, `sortable`, `aggregable` from `true` to `false` and vice versa
- changing a normalizer/analyzer  
CC: @fax4ever @mhajas
=> Add no-downtime scenarios for index attributes migration

server/resp/src/main/java/org/infinispan/server/resp/BaseRespDecoder.java, server/resp/src/main/java/org/infinispan/server/resp/Intrinsics.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java, server/resp/src/main/resources/resp.gr, server/resp/src/test/java/org/infinispan/server/resp/RespDecoderTest.java
Changes command parsing from reading a byte[] that is then converted to a String to instead read the bytes directly and take assumptions since all these commands are ASCII characters a-zA-Z. Instead we now have a 2D indexing the outer array by the first character of the command, so that we only have to check for a subset of commands. Also we verify length of the array first to avoid doing any byte comparisons unless the command actually has the same number of bytes. This also prevents any allocations for the command and will allow us to put properties on the arguments such as minimum and maximum arguments, security and other things in the enum itself.
Results from benchmark with these changes in https://github.com/infinispan/infinispan-benchmarks/pull/15 ( average time per invocation in …
=> ISPN-14720 RESP endpoint should be able to parse commands as enum

core/src/main/java/org/infinispan/marshall/persistence/impl/MarshalledEntryFactoryImpl.java, core/src/main/java/org/infinispan/metadata/EmbeddedMetadata.java, core/src/test/java/org/infinispan/persistence/CacheLoaderFunctionalTest.java, core/src/test/java/org/infinispan/persistence/WriteSkewCacheLoaderFunctionalTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFileStatsTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java
* Add IGNORE_RETURN_VALUES flag as well
https://issues.redhat.com/browse/ISPN-14738
=> [14.0] ISPN-14738 RESP endpoint commands don't require previous value

api/src/main/java/org/infinispan/api/protostream/builder/FieldBuilder.java, api/src/main/java/org/infinispan/api/protostream/builder/IndexedFieldBuilder.java, api/src/main/java/org/infinispan/api/protostream/builder/MessageBuilder.java, api/src/main/java/org/infinispan/api/protostream/builder/ProtoBuf.java, api/src/test/java/org/infinispan/api/protostream/builder/ProtoBufBuilderTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/protostream/builder/ProtoBufBuilderTest.java, client/hotrod-client/src/test/resources/proto/ciao.proto
https://issues.redhat.com/browse/ISPN-14724
=> ISPN-14724 Create a simple DSL to build Protocol Buffers schema

client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestClientOkHttp.java, server/rest/src/main/java/org/infinispan/rest/stream/CacheChunkedStream.java, server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
https://issues.redhat.com/browse/ISPN-14571
It doesn't seem the nicest way. If an error happens midway through writing the chunked response (key and entries), we cancel the stream, write HTTP last content, and add a trailer header with the exception message.
=> ISPN-14571 Propagate errors in REST chunked response

documentation/src/main/asciidoc/topics/proc_configuring_jdbc_cache_stores.adoc
backports #10810 
https://issues.redhat.com/browse/ISPN-14249
KCS article link, downstream content only
=> [14.0.x]ISPN-14249 add link to kcs with tested column types

core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/test/java/org/infinispan/globalstate/AbstractGlobalStateRestartTest.java, core/src/test/java/org/infinispan/globalstate/NodeRestartPartitionHandlingTest.java, core/src/test/java/org/infinispan/globalstate/ThreeNodeDistGlobalStateRestartTest.java, core/src/test/java/org/infinispan/globalstate/ThreeNodeReplGlobalStateRestartTest.java, core/src/test/java/org/infinispan/partitionhandling/BasePartitionHandlingTest.java
https://issues.redhat.com/browse/ISPN-14782
https://issues.redhat.com/browse/ISPN-14793
We do not broadcast the topology as stable if it wasn't yet restored.
=> ISPN-14782 Unable to reenable rebalance after cluster scale up

.github/workflows/pull_request.yml
Windows GH action runners get 7GB of RAM, attempting to limit the amount of memory available to the windows build in order to avoid OOM.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
=> Explicitly set xmx for windows native builds to prevent OOM

documentation/src/main/asciidoc/topics/proc_indexing_update_index_schema.adoc
Small docs update. It's not possible to update index schema from the console.
fyi @andyuk1986
=> Docs fix, remove option to update index schema from the console

core/src/main/java/org/infinispan/configuration/global/GlobalMetricsConfiguration.java, core/src/main/java/org/infinispan/configuration/parsing/Attribute.java, core/src/main/resources/schema/infinispan-config-15.0.xsd, core/src/test/resources/configs/all/15.0.xml
This fixes https://issues.redhat.com/browse/ISPN-13053
As the tag name was broken for several versions, I opted to rename the tag to follow the usual XML naming convention of other attribute being "kebab-case". Please advise if you think differently. 
The test case which tests that the parsing of the XML works is `UnifiedXmlFileParsingTest#testParseAndConstructUnifiedXmlFile`. Once I added the "nameAsTags" to the "15.0.xml" file it turned red. After the changes it is now green again.
=> ISPN-13053 Enable XML configuration to support "name-as-tags" again

documentation/src/main/asciidoc/topics/con_performance_data_consistency.adoc, documentation/src/main/asciidoc/topics/con_restarting_clusters.adoc, documentation/src/main/asciidoc/topics/transactions.adoc
miscellaneous docs fixes
- fix asciidoc syntax
- typo
- remove warning about DummyTransactionManagerLookup deprecation
=> docs fixes, typos, grammar, asciidoc syntax

documentation/src/main/asciidoc/topics/con_performance_data_consistency.adoc, documentation/src/main/asciidoc/topics/con_restarting_clusters.adoc, documentation/src/main/asciidoc/topics/transactions.adoc
miscellaneous docs fixes
-     fix asciidoc syntax
-     typo
-     remove warning about DummyTransactionManagerLookup deprecation
backports #10887
=> [14.0.x]docs fixes, typos, grammar, asciidoc syntax

server/pom.xml, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/APPEND.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/StringMutators.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14646
=> ISPN-14646 APPEND command

server/resp/pom.xml, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/RPUSH.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/RPUSHX.java, server/resp/src/test/java/org/infinispan/server/resp/ClusteredOperationsTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespAuthSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespTwoNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/SingleNodeRespBaseTest.java, server/resp/src/test/java/org/infinispan/server/resp/test/RespTestingUtil.java
https://issues.redhat.com/browse/ISPN-14640
=> ISPN-14640  RPUSH and RPUSHX commands

core/src/test/java/org/infinispan/remoting/jgroups/ChannelLookupTest.java
https://issues.redhat.com/browse/ISPN-14849
Mockito originally had a `.getClass()` like `class org.jgroups.JChannel$MockitoMock$iXlEc4Js` and after the update, it is `class org.jgroups.JChannel`.
=> ISPN-14849 ChannelLookupTest is failing

server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14857
The issue is that the listeners are removed asynchronously. So when the next execution starts, we mistakenly count them.
=> ISPN-14857 RESP pub-sub test is flaky

server/hotrod/src/main/java/org/infinispan/server/hotrod/ServerAddress.java
https://issues.redhat.com/browse/ISPN-14854
=> ISPN-14854 Fix IPv6 wildcard address used when detecting multi homing

server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/GETDEL.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14648
=> ISPN-14648 GETDEL Command

core/src/main/java/org/infinispan/configuration/global/GlobalMetricsConfiguration.java, core/src/main/java/org/infinispan/configuration/parsing/Attribute.java, core/src/main/resources/schema/infinispan-config-14.0.xsd, core/src/test/resources/configs/all/14.0.xml
This avoids a ConfigurationReaderException as XML expects them in kebab-case.
This is a backport of #10881
=> [14.0] ISPN-13053 Update XML configuration to support "name-as-tags"

server/hotrod/src/main/java/org/infinispan/server/hotrod/ServerAddress.java
https://issues.redhat.com/browse/ISPN-14854
=> [14.0] ISPN-14854 Fix IPv6 wildcard address used when detecting multi homing

server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/STRLEN.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
STRLEN command
https://issues.redhat.com/browse/ISPN-14659
=> ISPN-14659 STRLEN command

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CloseBeforeEnqueuingTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CrashMidOperationTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/AbstractRetryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/ClientListenerFailoverBusyTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/DistributionRetryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/InternalRemoteCacheManager.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelPool.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/HeaderDecoder.java
https://issues.redhat.com/browse/ISPN-14831
https://issues.redhat.com/browse/ISPN-14832
https://issues.redhat.com/browse/ISPN-14846
The biggest issue here is that there is a narrow window in which an operation might be enqueued but never executed. Happening when before enqueueing the operation, the channel closes and finishes all pending operations, then this operation remains in the queue.
The fix retries acquiring a channel from the pool if available. I needed to move the code around to test that.
The second commit here is regarding the flaky DistributionRetryTest with retry=0. It might happen that after killing the server, the channel is still created successfully to become inactive later. The change in the test waits for the channel with the server to become inactive before …
=> ISPN-14832 Hot Rod client issues

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/TransactionalRemoteCacheImpl.java, server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheOperations.java
https://issues.redhat.com/browse/ISPN-12142
* Not implemented for the transactional cache.
=> ISPN-12142 Implement conditional methods for RemoteCache compute

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/DBSIZE.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-14880
=> ISPN-14880 RESP DBSIZE

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Resp3Command.java, server/resp/src/main/java/org/infinispan/server/resp/commands/list/LLEN.java, server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
https://issues.redhat.com/browse/ISPN-14628
=> ISPN-14628 LLEN command

core/src/main/java/org/infinispan/functional/impl/MetaParamsInternalMetadata.java, core/src/main/java/org/infinispan/marshall/persistence/impl/MarshalledEntryFactoryImpl.java, core/src/main/java/org/infinispan/metadata/EmbeddedMetadata.java, core/src/main/java/org/infinispan/metadata/Metadata.java, core/src/main/java/org/infinispan/metadata/impl/InternalMetadataImpl.java, core/src/main/java/org/infinispan/metadata/impl/L1Metadata.java, core/src/test/java/org/infinispan/persistence/CacheLoaderFunctionalTest.java, core/src/test/java/org/infinispan/persistence/WriteSkewCacheLoaderFunctionalTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedMetadata.java
* PersistenceManager won't pass metadata with no expiration or version
https://issues.redhat.com/browse/ISPN-14740
Reworked this to not change the in memory persistence and instead now we just ignore the metadata when passing to a store. 
This saves approximately 40 bytes per entry and avoids serializing the metadata to protostream. 
This change is the equivalent to https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/container/impl/InternalEntryFactoryImpl.java#L88 which avoids the allocation in memory.
=> ISPN-14740 Do not persist empty metadata

.github/workflows/sync_docs.yml
The action to sync core docs to the website is broken. This PR fixes that by using the following action: https://github.com/marketplace/actions/setup-maven-action
Tested here: https://github.com/oraNod/infinispan/actions/runs/5078958486/jobs/9124105364#step:4:36550
Requires backport to 14.0.x.
=> Docs: Use setup mvn action in docs sync workflow

documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc
@fax4ever adding [discrete] label to avoid having all the chapters showing in the table of content. It results into:
`1.1.1.1.1. Index path`. 
=> fix table of content in the query guide

server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedBaseDecoder.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedStats.java, server/memcached/src/main/java/org/infinispan/server/memcached/ParseUtil.java, server/memcached/src/main/java/org/infinispan/server/memcached/binary/BinaryDecoder.java, server/memcached/src/main/java/org/infinispan/server/memcached/binary/BinaryOpDecoder.java, server/memcached/src/main/java/org/infinispan/server/memcached/text/TextIntrinsics.java, server/memcached/src/main/java/org/infinispan/server/memcached/text/TextOpDecoder.java, server/resp/src/main/java/org/infinispan/server/resp/ByteBufferUtils.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java
https://issues.redhat.com/browse/ISPN-14897
Some numbers are available on https://github.com/infinispan/infinispan-benchmarks/pull/19 for the `byte[]` -> `long`.
=> ISPN-14897 Avoid allocating strings for parsing int/long in resp

server/hotrod/src/main/java/org/infinispan/server/hotrod/MultiHomedServerAddress.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/InetAddressWithNetMaskTest.java
https://issues.redhat.com/browse/ISPN-14854
=> ISPN-14854 Do not bother matching addresses with different sizes

core/src/main/java/org/infinispan/container/versioning/irac/DefaultIracTombstoneManager.java, core/src/main/java/org/infinispan/util/ExponentialBackOff.java, core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java, core/src/main/java/org/infinispan/xsite/irac/IracClearResponseCollector.java, core/src/main/java/org/infinispan/xsite/irac/IracExecutor.java, core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyChangedState.java, core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyInfoImpl.java, core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyState.java, core/src/main/java/org/infinispan/xsite/irac/IracResponseCollector.java, core/src/main/java/org/infinispan/xsite/irac/IracXSiteBackup.java, core/src/test/java/org/infinispan/xsite/irac/ControlledExponentialBackOff.java, core/src/test/java/org/infinispan/xsite/irac/ControlledTransport.java, core/src/test/java/org/infinispan/xsite/irac/Irac3SitesExponentialBackOffTest.java, core/src/test/java/org/infinispan/xsite/irac/IracExponentialBackOffTest.java, core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java, core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java, core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
https://issues.redhat.com/browse/ISPN-13489
I've created `CompletableFuture`, which can be retried multiple times. We have the back-off for the whole `DefaultIracManager#run` and a back-off per operation issued to the remote sites. Both follow the same retry policy.
At first, I was trying to use the same thread for the retries with the `WithinThreadExecutor`, but it started to block too much stuff. Because of the way I've created the `RetryableCompletionStage`, where the `onComplete` calls the `retry`, which calls the `onComplete`. So suggestions are really welcome.
=> ISPN-13489 Exponential back-off does not work with multiple sites

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/FamilyCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/CLUSTER.java, server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/SHARDS.java, server/resp/src/test/java/org/infinispan/server/resp/ClusteredOperationsTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/tests/src/test/java/org/infinispan/server/security/authorization/RESPAuthorizationTest.java
https://issues.redhat.com/browse/ISPN-14229
* Implements the `CLUSTER SHARDS` command.
This is part 1, do not close the JIRA yet.
=> ISPN-14907 Implement RESP "cluster shards" command

server/runtime/src/main/server/server/conf/infinispan-dev-mode.xml
=> Added more configs to dev ispn configuration for console test needs.

server/core/src/main/java/org/infinispan/server/iteration/DefaultIterationManager.java, server/core/src/main/java/org/infinispan/server/iteration/ExternalSourceIterationManager.java, server/core/src/main/java/org/infinispan/server/iteration/IterationInitializationContext.java, server/core/src/main/java/org/infinispan/server/iteration/IterationManager.java, server/core/src/main/java/org/infinispan/server/iteration/map/MapIterationInitializationContext.java, server/core/src/main/java/org/infinispan/server/iteration/map/MapStreamSupplier.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java, server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/SCAN.java, server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HSCAN.java, server/resp/src/main/java/org/infinispan/server/resp/commands/iteration/BaseIterationCommand.java, server/resp/src/main/java/org/infinispan/server/resp/commands/iteration/IterationArguments.java, server/resp/src/main/java/org/infinispan/server/resp/filter/GlobMatchFilterConverter.java, server/resp/src/main/java/org/infinispan/server/resp/filter/GlobMatchFilterConverterFactory.java, server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
https://issues.redhat.com/browse/ISPN-14671
Create an iterator manager that handles a `Map` source. The downside is we have the complete entry loaded in memory to iterate, and the entry could be huge.
=> ISPN-14671 HSCAN

commons/all/src/main/java/org/infinispan/commons/util/ConcurrentSmallIntSet.java, commons/all/src/main/java/org/infinispan/commons/util/EmptyIntSet.java, commons/all/src/main/java/org/infinispan/commons/util/ImmutableIntSet.java, commons/all/src/main/java/org/infinispan/commons/util/IntSet.java, commons/all/src/main/java/org/infinispan/commons/util/RangeSet.java, commons/all/src/main/java/org/infinispan/commons/util/SingletonIntSet.java, commons/all/src/main/java/org/infinispan/commons/util/SmallIntSet.java, documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/CLUSTER.java, server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/NODES.java, server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/SHARDS.java, server/resp/src/test/java/org/infinispan/server/resp/ClusteredOperationsTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/tests/src/test/java/org/infinispan/server/security/authorization/RESPAuthorizationTest.java
https://issues.redhat.com/browse/ISPN-14963
=> ISPN-14863 Implement RESP "cluster nodes" command

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/CountFunction.java, multimap/src/main/java/org/infinispan/multimap/impl/internal/MultimapObjectWrapper.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapSortedSetCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/MultimapTestUtils.java, server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZCOUNT.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-14610
=> ISPN-14610 ZCOUNT

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedSetCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/SetBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/function/set/SAddFunction.java, multimap/src/main/java/org/infinispan/multimap/impl/function/set/SGetFunction.java, multimap/src/main/java/org/infinispan/multimap/impl/function/set/SSetFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedSetTest.java, server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HGET.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SCARD.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SINTER.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SINTERCARD.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SINTERSTORE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SMEMBERS.java, server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java, server/resp/src/test/java/org/infinispan/server/resp/test/RespTestingUtil.java
A bunch of commands for sets.
Code was almost the same, so this PR refers to 3 jiras.
https://issues.redhat.com/browse/ISPN-14597
SINTER SINTERCARD SINTERSTORE
https://issues.redhat.com/browse/ISPN-14598
SMEMBERS
https://issues.redhat.com/browse/ISPN-14595
SCARD
=> ISPN-14597 SINTER resp command

documentation/src/main/asciidoc/stories/assembly_query_embedded.adoc
https://issues.redhat.com/browse/ISPN-15018 
Temporary removal of content that is not supported.
=> ISPN-15018 temporary remove programmatic mapping of entities docs

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCache.java, multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java, multimap/src/main/java/org/infinispan/multimap/impl/HashMapBucket.java, multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java, multimap/src/main/java/org/infinispan/multimap/impl/function/hmap/HashMapReplaceFunction.java, multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapPairCacheTest.java, multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapPairCacheTest.java, server/resp/src/main/java/org/infinispan/server/resp/ByteBufferUtils.java, server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java, server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HINCRBY.java, server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HINCRBYFLOAT.java, server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
https://issues.redhat.com/browse/ISPN-14665
This includes `HINCRBY` and `HINCRBYFLOAT`. I added a `compute(key, property, biConsumer)` to implement both incr methods.
=> ISPN-14665 HINCRBY commands

core/src/main/java/org/infinispan/stats/impl/AbstractClusterStats.java, core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java, core/src/main/java/org/infinispan/stats/impl/ClusterContainerStatsImpl.java
https://issues.redhat.com/browse/ISPN-15042
=> [14.0] ISPN-15042 Do not collect clustered stats in some conditions

server/memcached/src/main/java/org/infinispan/server/memcached/ByteBufPool.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedAutoDetector.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedBaseDecoder.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedChannelInitializer.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedInboundAdapter.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedResponse.java, server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedServer.java, server/memcached/src/main/java/org/infinispan/server/memcached/binary/BinaryAuthDecoder.java, server/memcached/src/main/java/org/infinispan/server/memcached/binary/BinaryDecoder.java, server/memcached/src/main/java/org/infinispan/server/memcached/binary/BinaryHeader.java, server/memcached/src/main/java/org/infinispan/server/memcached/binary/BinaryOpDecoder.java, server/memcached/src/main/java/org/infinispan/server/memcached/binary/BinaryResponse.java, server/memcached/src/main/java/org/infinispan/server/memcached/logging/Header.java, server/memcached/src/main/java/org/infinispan/server/memcached/logging/Log.java, server/memcached/src/main/java/org/infinispan/server/memcached/logging/MemcachedAccessLogging.java, server/memcached/src/main/java/org/infinispan/server/memcached/text/TextAuthDecoder.java, server/memcached/src/main/java/org/infinispan/server/memcached/text/TextCommand.java, server/memcached/src/main/java/org/infinispan/server/memcached/text/TextDecoder.java, server/memcached/src/main/java/org/infinispan/server/memcached/text/TextHeader.java, server/memcached/src/main/java/org/infinispan/server/memcached/text/TextIntrinsics.java, server/memcached/src/main/java/org/infinispan/server/memcached/text/TextOpDecoder.java, server/memcached/src/main/java/org/infinispan/server/memcached/text/TextResponse.java, server/memcached/src/main/java/org/infinispan/server/memcached/text/TokenReader.java, server/memcached/src/main/resources/memcache-binary-auth.gr, server/memcached/src/main/resources/memcache-binary-op.gr, server/memcached/src/main/resources/memcache-text-auth.gr, server/memcached/src/main/resources/memcache-text-op.gr, server/memcached/src/test/java/org/infinispan/server/memcached/binary/MemcachedBinaryReplicationTest.java, server/memcached/src/test/java/org/infinispan/server/memcached/test/MemcachedFunctionalTest.java, server/memcached/src/test/java/org/infinispan/server/memcached/text/MemcachedStatsTest.java
https://issues.redhat.com/browse/ISPN-14813
Most of the changes are based on #10934 and #11006.
I ran locally using the `memtier_benchmark`. If anyone is interested in running, I ran with the configuration `memtier_benchmark -p 11222 -4 -P memcache_binary -d 9000 -R --pipeline=10 --test-time=60`, varying the protocol with `memcache_binary` and `memcache_text`, and running one time to warm up and another to collect the info, additionally:
```
4         Threads
50        Connections per thread
60        Seconds
```
Comparison with `--pipeline=1`: https://gist.github.com/jabolina/99ea2e4d8317f36ad12d445bc57672a9
Comparison with `--pipeline=10`: https://gist.github.com/jabolina/6db34b4e1afce874ff7247a9ea9625d3
We can see that `pipeline=1` performs slightly worse but performs better with …
=> ISPN-14813 Memached backpressure support

server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespConstants.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/TransactionResp3Command.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/QUIT.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/EXEC.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/MULTI.java, server/resp/src/main/java/org/infinispan/server/resp/tx/RespTransactionHandler.java, server/resp/src/main/java/org/infinispan/server/resp/tx/TransactionCommand.java, server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java, server/tests/src/test/java/org/infinispan/server/functional/resp/RespTransactionTest.java
https://issues.redhat.com/browse/ISPN-14641
https://issues.redhat.com/browse/ISPN-14643
This was the easy part. Working fine in a single node/STANDALONE. This way, we have a few things already:
* The commands are in memory, not tolerating restarts;
* TX could be half-applied if crashing mid-way EXEC;
* Executing the queued commands has a read uncommitted isolation.
Going to CLUSTER mode becomes more difficult. We lose the transaction context, as it is bound to a channel. We can start a discussion about how we want to handle all this. But for now, we have at least the basics in.
=> ISPN-14641 MULTI + ISPN-14643 EXEC

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/Util.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/Util.java
This backports this fix from the main branch to 14.x
The original PR is #11111
(cherry picked from commit 8c0d352b46babc51c571b45b5770d23656b42ea5)
=> [14.0] ISPN-15041 Preserve stack traces to caller to simplify debugging

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientClusterFailoverEventsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/MultiServerDistRemoteIteratorTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/maxresult/RemoteHitCountAccuracyTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedFailoverNearCacheTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/MockNearCacheService.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/MultiServerStoreQueryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDslConditionsTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/ClientListenerFailoverBusyTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/SingleServerSocketTimeoutTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/SocketTimeoutFailureRetryTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/size/HugeProtobufMessageTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/OpenTelemetryClient.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/TracingDisabledTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/TracingPropagationTest.java, core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java, core/src/test/java/org/infinispan/statetransfer/ReadAfterLostDataTest.java, core/src/test/java/org/infinispan/util/ControlledTransport.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodTestingUtil.java, server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java
https://issues.redhat.com/browse/ISPN-15064
https://issues.redhat.com/browse/ISPN-15089
* Allowing retry of operation on the same channel;
* Concurrency fixes in some tests;
Opening as a draft to let CI run. There might still have some flaky because of the timeout configuration.
=> ISPN-15064 Hot Rod Client flaky tests on CI

core/src/main/java/org/infinispan/factories/ComponentRegistry.java, core/src/main/java/org/infinispan/factories/InternalCacheFactory.java, core/src/main/java/org/infinispan/functional/impl/ReadOnlyMapImpl.java, core/src/main/java/org/infinispan/functional/impl/ReadWriteMapImpl.java, core/src/main/java/org/infinispan/functional/impl/SimpleReadOnlyMapImpl.java, core/src/main/java/org/infinispan/functional/impl/SimpleReadWriteMapImpl.java, server/resp/src/main/java/org/infinispan/server/resp/operation/LCSOperation.java, server/resp/src/test/java/org/infinispan/server/resp/RespAuthSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespMediaTypesTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespSimpleCacheTest.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java, server/resp/src/test/java/org/infinispan/server/resp/SingleNodeRespBaseTest.java, server/resp/src/test/java/org/infinispan/server/resp/operation/OperationTest.java
https://issues.redhat.com/browse/ISPN-15070
https://issues.redhat.com/browse/ISPN-15094
Maybe not the correct name for the JIRA, but this adds an implementation for the functional map that works with a simple cache. We follow the same idea from `SimpleCacheImpl` to directly access the data container and execute the operations. This still lacks proper stats collection.
This allows configuring a simple cache for resp and using all the data structures, too.
=> ISPN-15070 RESP cache cannot be configured as a simple cache

server/resp/src/main/java/org/infinispan/server/resp/RespServer.java
* Handle case where key encoding is not defined
https://issues.redhat.com/browse/ISPN-15068
=> ISPN-15068 RESP Server should always use OCTET key media type storage

Jenkinsfile, build/configuration/pom.xml
* maven-javadoc-plugin is unable to find "target/generated-sources" when maven.main.skip is true
* test jars are not deployed because of maven.test.skip is interpreted by  maven-jar-plugin
=> Fix deploy without compiling sources

core/src/main/java/org/infinispan/factories/impl/MBeanMetadata.java, core/src/main/java/org/infinispan/metrics/Constants.java, core/src/main/java/org/infinispan/metrics/impl/AbstractMetricsRegistration.java, core/src/main/java/org/infinispan/metrics/impl/CustomMetricsSupplier.java, core/src/main/java/org/infinispan/metrics/impl/MetricUtils.java, core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java, core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java, core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java, core/src/main/java/org/infinispan/xsite/status/TakeOfflineManager.java, documentation/src/main/asciidoc/topics/upgrading.adoc
https://issues.redhat.com/browse/ISPN-15032
When `names-as-tags` is set to `false`, we got 2 different metrics with the channel name distinguishing between them.
```
vendor_jgroups_xsite_frag4_get_number_of_sent_fragments{cluster="xsite",node="_pedro-laptop-4-17826:site1"} 0.0
vendor_jgroups_cluster_frag4_get_number_of_sent_fragments{cluster="cluster",node="pedro-laptop-4-17826"} 2.0
```
When `names-as-tags` is set to `true`, we got a single metric:
```
vendor_jgroups_frag4_get_number_of_sent_fragments{cache_manager="default",cluster="xsite",node="_pedro-laptop-4-16213:site1"} 0.0
vendor_jgroups_frag4_get_number_of_sent_fragments{cache_manager="default",cluster="cluster",node="pedro-laptop-4-16213"} 2.0
```
=> ISPN-15032 Use site and channel names as tag for metrics

server/resp/src/main/java/org/infinispan/server/resp/CacheRespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java, server/resp/src/main/java/org/infinispan/server/resp/RespHandler.java, server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/MSET.java, server/resp/src/main/java/org/infinispan/server/resp/logging/AccessData.java, server/resp/src/main/java/org/infinispan/server/resp/logging/AccessLoggerManager.java, server/resp/src/main/java/org/infinispan/server/resp/logging/RespAccessLogger.java, server/resp/src/main/java/org/infinispan/server/resp/logging/Tracker.java, server/resp/src/test/java/org/infinispan/server/resp/RespDecoderTest.java, server/resp/src/test/java/org/infinispan/server/resp/logging/RespAccessLoggingTest.java, server/runtime/src/main/server/server/conf/log4j2.xml
https://issues.redhat.com/browse/ISPN-14566
I wanted to get this one out of the way already.
Running with memtier to compare the main and this branch with the access log disabled, the performance holds. A small snippet from the log:
```text
127.0.0.1 admin [25/Aug/2023:11:49:08 -0300] "GET /[[B0x6D656D746965722D393939] RESP" OK 27 9009 0
127.0.0.1 admin [25/Aug/2023:11:49:08 -0300] "SET /[[B0x6D656D746965722D343235] RESP" OK 9030 5 0
127.0.0.1 admin [25/Aug/2023:11:49:08 -0300] "GET /[[B0x6D656D746965722D343135] RESP" OK 27 5 0
```
GET with a hit, SET, and GET with a miss. Memtier is running with a 9K data size.
I think the time interval at the end is small and goes to 0.
=> ISPN-14566 Implement RESP access logging

server/runtime/src/main/java/org/infinispan/server/LifecycleCallbacks.java, server/runtime/src/main/java/org/infinispan/server/logging/events/ServerEventLogger.java
https://issues.redhat.com/browse/ISPN-14814
After a graceful shutdown, the node finishes recovering and logs the topology update. Since the event logger cache is created, it blocks the cache join, and it seems, also lead to a complete startup deadlock.
=> [14.0.x] ISPN-14814 ServerEventLogger blocks when creating a cache

core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
https://issues.redhat.com/browse/ISPN-15089
Otherwise, the `cacheManager#getCacheConfiguration(String)` does a check with the authorizer and throws a lack of permission. Since we already have the configuration we're trying to load, we don't need to reload it again.
=> ISPN-15089 Skip cache manager loading configuration

build/configuration/pom.xml
Contains only a single fix that may improve test suite stability (TCP_NIO2 is used by default)
* JGRP-2727 - TCP_NIO2: Discovery fails due to NoConnectionPendingException...
https://issues.redhat.com/browse/ISPN-15167
=> ISPN-15167 Upgrade JGroups to 5.2.19.Final

core/src/main/java/org/infinispan/configuration/global/TransportConfigurationBuilder.java
Fix javadoc that TransportConfigurationBuilder does not use object instance
=> Fix javadoc that TransportConfigurationBuilder does not use object instance

commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitTest.java, commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitXMLReporter.java
https://issues.redhat.com/browse/ISPN-15143
A slight amendment is required to the way we handle duplicate tests. I discovered the oversight when backporting the changes to the 14.0.x branch.
=> ISPN-15143 Handle rerunning of successful tests when failures present

Jenkinsfile
We can't use 2.5 hours as Jenkins rounds down to 2 hours.
=> Increase Jenkins timeout to 2.5 hours

object-filter/pom.xml
Issue: https://issues.redhat.com/browse/ISPN-15175
ISPN-15175 Don't filter out META-INF/MANIFEST.MF and META-INF/licenses.xml in object-filter pom.xml
(cherry picked from commit 4b876d5fb7e9faddb1bad8bd41a02809a820c5e7)
Upstream main branch PR: https://github.com/infinispan/infinispan/pull/11295
=> [14.0.x] ISPN-15175 Don't filter out META-INF/MANIFEST.MF and META-INF/licenses.xml in object-filter pom.xml

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/telemetry/impl/TelemetryService.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/logging/Log.java, client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/CacheOperationsFactory.java, client/hotrod/src/main/java/org/infinispan/hotrod/telemetry/impl/TelemetryService.java
https://issues.redhat.com/browse/ISPN-15156
=> ISPN-15156 Avoid to spam DEBUG log when OpenTelemetry is not found on the client

core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java
https://issues.redhat.com/browse/ISPN-14759
=> [14.0] ISPN-14759 SoftIndexFileStore Index can lag behind LogAppender under heavy load

server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TOUCH.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
https://issues.redhat.com/browse/ISPN-15212
=> ISPN-15212 TOUCH

Jenkinsfile
Test runs:
Timeout case: https://ci.infinispan.org/job/Infinispan/job/main/1258
Success case: https://ci.infinispan.org/job/Infinispan/job/main/1259
Waiting for ^ before marking as non-draft.
=> Increase Jenkins overall timeout. Add per test timeout of 2 hours

server/rest/src/test/java/org/infinispan/rest/search/BaseRestSearchTest.java, server/rest/src/test/java/org/infinispan/rest/search/EmbeddedRestSearchTest.java, server/rest/src/test/java/org/infinispan/rest/search/IndexedRestOffHeapSearchTest.java, server/rest/src/test/java/org/infinispan/rest/search/IndexedRestSearchTest.java, server/rest/src/test/java/org/infinispan/rest/search/NonIndexedPojoQueryTest.java, server/rest/src/test/java/org/infinispan/rest/search/NonIndexedRestOffHeapSearch.java, server/rest/src/test/java/org/infinispan/rest/search/NonIndexedRestSearchTest.java, server/rest/src/test/java/org/infinispan/rest/search/NonSharedIndexSearchTest.java, server/rest/src/test/java/org/infinispan/rest/search/SingleNodeLocalIndexTest.java
Some of these tests can be executed in parallel, resulting in possible clustered locks used for mass-indexing contention, that are based on cache name.
=> ISPN-TEST Use different cache names on RestSearchTest hierarchy

documentation/src/main/asciidoc/topics/ref_server_realm_ldap.adoc, server/runtime/src/main/resources/schema/infinispan-server-15.0.xsd
https://issues.redhat.com/browse/ISPN-15241 
Fix property name in the schema
@pruivo fixing an old bug. Could you elaborate about its implications?
=> ISPN-15241 fix property name to connection-pooling

integrationtests/security-manager-it/pom.xml, pom.xml
https://issues.redhat.com/browse/ISPN-14784
=> [14.0] ISPN-14784 Only use -Djava.security.manager=allow since JDK 17

.github/workflows/operator_upgrade.yaml
@tristantarrant There's some overlap here with the "Image required" logic in the Jenkinsfile which we could probably replace with a purely GH action implementation, but given that the Jenkins solution works and hasn't ever changed, it's probably not worth changing.
=> Run Operator Upgrade tests against branch server build

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/aggregation/RemoteQueryAggregationCountTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/maxresult/RemoteDefaultMaxResultTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/maxresult/RemoteHitCountAccuracyTest.java, object-filter/src/main/antlr3/org/infinispan/objectfilter/impl/ql/parse/QueryRenderer.g, object-filter/src/main/java/org/infinispan/objectfilter/impl/ql/QueryRendererDelegate.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/BooleShannonExpansion.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/IndexedFieldProvider.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/AggregationPropertyPath.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/CacheValueAggregationPropertyPath.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/QueryRendererDelegateImpl.java, object-filter/src/test/java/org/infinispan/objectfilter/impl/syntax/BooleShannonExpansionTest.java, query/src/main/java/org/infinispan/query/clustered/AggregationDistributedIterator.java, query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java, query/src/main/java/org/infinispan/query/clustered/commandworkers/CQCreateEagerQuery.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelper.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/InfinispanAggregation.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryAnalyzer.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryBuilder.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryMaker.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryParsingResult.java, query/src/main/java/org/infinispan/query/impl/IndexedQueryImpl.java, query/src/test/java/org/infinispan/query/aggregation/QueryAggregationBroadcastTest.java, query/src/test/java/org/infinispan/query/aggregation/QueryAggregationCountTest.java, query/src/test/java/org/infinispan/query/model/Sale.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadata.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadata.java, remote-query/remote-query-server/src/test/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadataTest.java
https://issues.redhat.com/browse/ISPN-15254
Backport of #11412
Based on #11434 that should merged first
=> [14.0.x] ISPN-15254 Support count(*) other than count(someField) on aggregation queries

commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java, commons/all/src/main/java/org/infinispan/commons/jdkspecific/ThreadCreator.java, commons/jdk21/src/main/java/org/infinispan/commons/jdk21/ThreadCreatorImpl.java, commons/spi/src/main/java/org/infinispan/commons/spi/ThreadCreator.java, core/src/main/java/org/infinispan/factories/threads/DefaultThreadFactory.java, core/src/main/java/org/infinispan/factories/threads/EnhancedQueueExecutorFactory.java, core/src/main/resources/default-configs/default-jgroups-azure.xml, core/src/main/resources/default-configs/default-jgroups-ec2.xml, core/src/main/resources/default-configs/default-jgroups-google.xml, core/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/main/resources/default-configs/default-jgroups-udp.xml, core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java, core/src/test/resources/configs/config-with-jgroups-stack.xml, core/src/test/resources/configs/xsite/bridge.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/tcp_mping/tcp1.xml, core/src/test/resources/stacks/tcp_mping/tcp2.xml, core/src/test/resources/stacks/udp.xml, hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml, pom.xml, quarkus/integration-tests/embedded/src/main/resources/embedded.xml, quarkus/integration-tests/embedded/src/main/resources/stacks/tcp.xml, quarkus/integration-tests/embedded/src/main/resources/stacks/tcp_mping/tcp1.xml, quarkus/integration-tests/embedded/src/main/resources/stacks/tcp_mping/tcp2.xml, quarkus/integration-tests/embedded/src/main/resources/stacks/udp.xml, server/core/src/main/java/org/infinispan/server/core/factories/NettyEventLoopFactory.java, server/testdriver/junit5/src/test/resources/jgroups/xsite-stacks.xml, server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml
* Enable JGroups virtual threads with org.infinispan.threads.virtual or jgroups.thread.virtual
* Create VirtualThreadPerTaskExecutor for blocking thread pool
* Do not use virtual threads in Netty event loop
@tristantarrant @wburns opened for later discussion :+1: 
https://issues.redhat.com/browse/ISPN-15304
=> ISPN-15304 Virtual Threads improvements

core/src/main/java/org/infinispan/functional/impl/SimpleFunctionalMap.java, core/src/main/java/org/infinispan/functional/impl/SimpleReadOnlyMapImpl.java, core/src/main/java/org/infinispan/functional/impl/SimpleReadWriteMapImpl.java, core/src/main/java/org/infinispan/functional/impl/SimpleWriteNotifierHelper.java, core/src/main/java/org/infinispan/functional/impl/SimpleWriteOnlyMapImpl.java, core/src/main/java/org/infinispan/functional/impl/WriteOnlyMapImpl.java, core/src/test/java/org/infinispan/functional/AbstractFunctionalOpTest.java, core/src/test/java/org/infinispan/functional/AbstractFunctionalTest.java, core/src/test/java/org/infinispan/functional/FunctionalConcurrentMapEventsTest.java, core/src/test/java/org/infinispan/functional/FunctionalConcurrentMapTest.java, core/src/test/java/org/infinispan/functional/FunctionalInMemoryTest.java, core/src/test/java/org/infinispan/functional/FunctionalListenersTest.java, core/src/test/java/org/infinispan/functional/FunctionalMapEventsTest.java, core/src/test/java/org/infinispan/functional/FunctionalMapTest.java
https://issues.redhat.com/browse/ISPN-15291
The first commit handles the notification part. The second commit adds a `WriteOnlyMap` implementation with a simple cache and tests for all the simple variants.
=> ISPN-15291 Functional map with simple cache

commons/all/src/main/java/org/infinispan/commons/jdkspecific/ThreadCreator.java, commons/jdk21/src/main/java/org/infinispan/commons/jdk21/ThreadCreatorImpl.java, commons/spi/src/main/java/org/infinispan/commons/spi/ThreadCreator.java, core/src/main/java/org/infinispan/factories/threads/DefaultThreadFactory.java, core/src/main/java/org/infinispan/factories/threads/EnhancedQueueExecutorFactory.java, core/src/main/resources/default-configs/default-jgroups-azure.xml, core/src/main/resources/default-configs/default-jgroups-ec2.xml, core/src/main/resources/default-configs/default-jgroups-google.xml, core/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/main/resources/default-configs/default-jgroups-udp.xml, core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java, core/src/test/resources/configs/config-with-jgroups-stack.xml, core/src/test/resources/configs/xsite/bridge.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/tcp_mping/tcp1.xml, core/src/test/resources/stacks/tcp_mping/tcp2.xml, core/src/test/resources/stacks/udp.xml, hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml, pom.xml, server/core/src/main/java/org/infinispan/server/core/factories/NettyEventLoopFactory.java, server/testdriver/junit5/src/test/resources/jgroups/xsite-stacks.xml, server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml
* Enable JGroups virtual threads with org.infinispan.threads.virtual or jgroups.thread.virtual
* Create VirtualThreadPerTaskExecutor for blocking thread pool
* Do not use virtual threads in Netty event loop
https://issues.redhat.com/browse/ISPN-15304
=> [14.0.x] ISPN-15304 Virtual Threads improvements

core/src/test/java/org/infinispan/test/TestDataSCI.java, core/src/test/java/org/infinispan/test/data/Numerics.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/QueriesJdbcStore.java, persistence/sql/src/main/java/org/infinispan/persistence/sql/TableJdbcStore.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java, persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcStoreFunctionalTest.java
https://issues.redhat.com/browse/ISPN-15282
Added a test for SQL store to check the different numeric types. But two notes:
SQLite has "flexible typing" or something like that, which makes it complicated [1]. We have only a few data types, and when an inconsistent behavior using the JDBC implementation. For example, a `simpleLong` column needs to be defined as `INTEGER`. Extracting the column information from the `DatabaseMetaData` yields `INTEGER (2000000000, 0)` but through the `ResultSetMetaData` and the query yields only `INTEGER` without precision or scale. That's why I skip the test for query + SQLite.
Second, the `Numerics` class does not include `byte` or `short` because Protostream seems unable to parse it right now to/from JSON.
[1]: https://www.sqlite.org/datatype3.html
=> ISPN-15282 Handle varying numeric precision in SQL store

server/tests/src/test/java/org/infinispan/server/test/core/KeyCloakServerExtension.java
https://issues.redhat.com/browse/ISPN-15342
The PR changes the server extension to wait on server startup rather then admin console.
Additional change to server extension is to copy the certificates to the container rather then mounting them through volume as original approach may result in inaccessible files from the container due to insufficient access rights.
=> ISPN-15342 Custom Keycloak images may not have admin console enabled

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/async/DefaultAsyncExecutorFactory.java, commons/all/src/main/java/org/infinispan/commons/ThreadGroups.java, core/src/main/java/org/infinispan/executors/DefaultExecutorFactory.java, core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java, core/src/main/java/org/infinispan/factories/threads/BlockingThreadFactory.java, core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadFactory.java, core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFileStatsTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreTestUtils.java, core/src/test/java/org/infinispan/stress/AsyncStoreStressTest.java, persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/MigrationTask.java, server/core/src/main/java/org/infinispan/server/core/factories/NettyEventLoopFactory.java
This backports:
ISPN-15184 SIFS can leave many data files left around
ISPN-15147 DefaultExecutorFactory can create multiple ThreadGroups
=> [13.0] Backport SIFS data files left around and multiple ThreadGroups

documentation/src/main/asciidoc/topics/json/server_ssl_identity_engine.json, documentation/src/main/asciidoc/topics/xml/server_ssl_identity_engine.xml
https://issues.redhat.com/browse/ISPN-15406
The TLS v1.3 ciphers should be separated by colon
The TLS v1.2 ciphers should be updated in the enabled-ciphers section
=> ISPN-15406-The TLS v1.2 and v1.3 supported ciphers Updated 

documentation/src/main/asciidoc/topics/ref_performance_tuning.adoc, documentation/src/main/asciidoc/topics/xml/hotrod_worker_threads.xml, server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/HotRodServerConfiguration.java
https://issues.redhat.com/browse/ISPN-15401
=> ISPN-15401 Remove worker-threads section from tuning guide

build/configuration/pom.xml
https://issues.redhat.com/browse/ISPN-15402
Supersedes #11604.
Bump org.jgroups:jgroups-raft from 1.0.11.Final to 1.0.12.Final
Bumps [org.jgroups:jgroups-raft](https://github.com/jgroups-extras/jgroups-raft) from 1.0.11.Final to 1.0.12.Final.
- [Commits](https://github.com/jgroups-extras/jgroups-raft/compare/jgroups-raft-1.0.11.Final...jgroups-raft-1.0.12.Final)
---
updated-dependencies:
- dependency-name: org.jgroups:jgroups-raft dependency-type: direct:production update-type: version-update:semver-patch ...
=> ISPN-15402 JGroups Raft 1.0.12.Final

.github/actions/create-jira/action.yaml, .github/workflows/dependabot_jira.yml
This will automatically create a Jira ticket for all dependabot PRs, link the PR to the ticket and then add the Jira URL as a comment on the PR itself.
Example Jira ticket: https://issues.redhat.com/browse/ISPN-15414
I'll create a different workflow for the backport branches, as we'll need to update an existing Jira instead of creating a new one.
=> Automatically create Jira tickets for dependabot upgrades

commons/all/src/main/java/org/infinispan/commons/reactive/RxJavaInterop.java, core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java, core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/EntryInfo.java, core/src/main/java/org/infinispan/persistence/sifs/FileProvider.java, core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java, core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java, core/src/main/java/org/infinispan/persistence/sifs/configuration/IndexConfiguration.java, core/src/main/java/org/infinispan/persistence/sifs/configuration/SoftIndexFileStoreConfiguration.java, core/src/main/resources/schema/infinispan-config-15.0.xsd, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFunctionalTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreTest.java
https://issues.redhat.com/browse/ISPN-15377
https://issues.redhat.com/browse/ISPN-15395
This PR changes SIFS to create an index file per cache segment instead of its own idea of a segment. This allows for iteration code to be simplified as well as no longer requiring every key to be prepended with the segment information. It also should reduce time complexity of looking up keys as the key space would be divided by the number of cache segments already.
This will also shave off 4 bytes off every entry in the index as well since we no longer have to store the segment information with the key itself.
=> ISPN-15377 SoftIndexFileStore index by cache segment

archetypes/server-task/src/main/resources/archetype-resources/pom.xml, archetypes/store/src/main/resources/archetype-resources/pom.xml, build/component-processor/pom.xml, build/configuration/pom.xml, client/hotrod/pom.xml, graalvm/client-hotrod/pom.xml, graalvm/core/pom.xml, pom.xml, quarkus/integration-tests/server/pom.xml, server/testdriver/junit5/pom.xml, server/tests/pom.xml
https://issues.redhat.com/browse/ISPN-15424
@pruivo I've only removed the `versionx` properties that inherited from another `version.*` property as I believe these are the only properties Dependabot has an issue with.
Let me know if there's an issue with this approach of if you want me to convert all of the remaining `versionx.*` properties.
=> ISPN-15424 Remove inherited versionx properties to facilitate Dependabot

core/src/main/java/org/infinispan/topology/CacheStatusResponse.java, core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/test/java/org/infinispan/globalstate/AbstractGlobalStateRestartTest.java, core/src/test/java/org/infinispan/globalstate/ThreeNodeDistGlobalStateRestartTest.java, core/src/test/java/org/infinispan/globalstate/ThreeNodeReplGlobalStateRestartTest.java, core/src/test/java/org/infinispan/topology/AbstractStatefulCluster.java, core/src/test/java/org/infinispan/topology/ClusterTopologyStatefulTest.java, core/src/test/java/org/infinispan/topology/StatefulShutdownDuringJoinTest.java, server/tests/src/test/java/org/infinispan/server/resilience/GracefulShutdownRestartIT.java
https://issues.redhat.com/browse/ISPN-15357
There are a few moving parts here that I can break into smaller PRs if you prefer.
The first thing is persisting the global rebalance status. Previously, we could disable rebalance, but if the complete cluster is shut down, that information is lost, and it would restart with it enabled. It could survive during a rolling upgrade, with nodes retrieving the status from the coordinator. Now, we save the information to the persistent state. The node first reads it from the local state and later retrieves it from the coordinator.
The second part handles the join requests when nodes have a persistent state.
The easy part, which makes more sense to include, is a stateless joiner with a stateful coordinator *before* the cluster is recovered. Currently, …
=> ISPN-15357 Unable to enable rebalancing after cluster scale up

core/src/main/java/org/infinispan/manager/EmbeddedCacheManager.java
Though already removed from main without proper notice. 
I am assuming here we don't need a Jira here, but let me know.
=> [14.0.x] Properly deprecate EmbeddedCacheManager#getTransport()

server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
https://issues.redhat.com/browse/ISPN-15467
Increasing the bound. Comparing the files we traverse in the tests, there is an addition of `micrometer-commons-1.12.2.jar` with size `47343` and `micrometer-observation-1.12.2.jar` with size `71751`. And the `micrometer-core-1.12.2.jar` has size `882586` (1.9.2 was 657113), and `micrometer-registry-prometheus-1.12.2.jar` has `43651` (1.9.2 was 40972).
We have other dependencies, including our code, increasing a few Kb or bytes.
=> ISPN-15467 FootprintIT failures

core/src/main/java/org/infinispan/util/concurrent/locks/impl/InfinispanLock.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/LifecycleCallbacks.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/PrepareCoordinator.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/BaseCompleteTransactionOperation.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/CommitTransactionOperation.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/RollbackTransactionOperation.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/TxState.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/ConditionalMarkAsRollbackFunction.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/CreateStateFunction.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/PreparingDecisionFunction.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetCompletedTransactionFunction.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetDecisionFunction.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetPreparedFunction.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/ServerHotRodTestBlockHoundIntegration.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/tx/TopologyChangeFunctionalTest.java
https://issues.redhat.com/browse/ISPN-15425
Unfortunately, it does not fix all flaky tests but should make them rare :)
=> ISPN-15425 TopologyChangeFunctionalTest random failures

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InvalidatedNearRemoteCache.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/ClusterNearCacheMarshallingTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/NearCacheMarshallingTest.java
https://issues.redhat.com/browse/ISPN-15494
Updated for the invalidated near cache instances. We check if the MANAGER marshaller handles the server type and only then proceed with the usual flow. Either we register the listener and set the data format or the inverse.
If the marshaller is compatible with the server type, we exchange the type information when installing the listener. See, this might hide bugs that bite back during runtime! During runtime, when executing some key-based operation against the server, an exception is thrown because it is not possible to convert between types, failing later instead of during start-up. We also log a warning message.
Note that it would be a similar behavior to before we added #11337.
Internal caches, where the user won't interact directly through …
=> ISPN-15494 Near cache with invalidation fails to start in Spring Boot

core/src/main/java/org/infinispan/statetransfer/InboundTransferTask.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/test/java/org/infinispan/globalstate/AbstractGlobalStateRestartTest.java, core/src/test/java/org/infinispan/globalstate/ThreeNodeTopologyReinstallTest.java
https://issues.redhat.com/browse/ISPN-15432
I suspect the issue is caused because the tests also invoke `LocalTopologyManager.stableTopologyCompletion` to wait, and that causes the store to be cleared twice. It was cleared once by the internal workings and another time by the test.
I updated it so the method can be invoked without clearing the stores every time.
=> ISPN-15432 Make stable topology recovery more robust

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/HeaderParams.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodIntegrationTest.java
https://issues.redhat.com/browse/ISPN-15659
=> ISPN-15659 Hot Rod Client RemoteCache#computeAsync() can lose the result of remapping processing when executed concurrently against a new entry

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/Consumers.java, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/GETRANGE.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/GETSET.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/PSETEX.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/SET.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/SETEX.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/SETNX.java, server/resp/src/main/java/org/infinispan/server/resp/commands/string/SUBSTR.java, server/resp/src/main/java/org/infinispan/server/resp/operation/RespExpiration.java, server/resp/src/main/java/org/infinispan/server/resp/operation/SetOperation.java, server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
https://issues.redhat.com/browse/ISPN-14656
https://issues.redhat.com/browse/ISPN-14657
https://issues.redhat.com/browse/ISPN-14651
https://issues.redhat.com/browse/ISPN-14655
https://issues.redhat.com/browse/ISPN-14660
This should close https://issues.redhat.com/browse/ISPN-14645.
Also, the `SUBSTR` is not covered in tests. Lettuce doesn't even have that command. Looking at the command documentation, they use `GETRANGE` instead of `SUBSTR` to show the examples.
=> ISPN-14645 Final string commands pending

core/src/main/resources/default-configs/default-jgroups-ec2.xml, distribution/pom.xml, documentation/src/main/asciidoc/topics/ref_discovery_cloud.adoc, pom.xml
Maven cleanup. jgroups-aws and jgroups-azure are not shipped or used anywhere in the code
https://issues.redhat.com/browse/ISPN-15719
=> ISPN-15719 Remove JGroups AWS and Azure

query/src/main/java/org/infinispan/query/clustered/ClusteredQueryInvoker.java, query/src/main/java/org/infinispan/query/clustered/DistributedEntryIterator.java, query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java, query/src/main/java/org/infinispan/query/clustered/DistributedIterator.java, query/src/test/java/org/infinispan/query/maxresult/DistributedMaxResultTest.java
Use getAll to fetch multiple keys in a single RPC request. The batch is the same as the chunk-size for state transfer.
https://issues.redhat.com/browse/ISPN-15738
=> ISPN-15738 Avoid individual GET by Key in distributed query aggregation

query/src/main/java/org/infinispan/query/clustered/ClusteredQueryInvoker.java, query/src/main/java/org/infinispan/query/clustered/DistributedEntryIterator.java, query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java, query/src/main/java/org/infinispan/query/clustered/DistributedIterator.java, query/src/test/java/org/infinispan/query/maxresult/DistributedMaxResultTest.java
Use getAll to fetch multiple keys in a single RPC request. The batch is the same as the chunk-size for state transfer.
https://issues.redhat.com/browse/ISPN-15738
=> [14.x] ISPN-15738 Avoid individual GET by Key in distributed query aggregation

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/AcquireChannelOperation.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CloseBeforeEnqueuingTest.java
https://issues.redhat.com/browse/ISPN-15626
Synchronization when trying to execute the operation _after_ it was enqueued. This takes a slow path to verify the operation is still pending in the queue and removes it before execution.
This should fix the `AvoidStaleNearCacheReadsTest` test. In the test, the problem appears with an active channel released to the pool. The problem could also happen with a new channel creation.
=> ISPN-15626 Hot Rod client tries to schedule operation twice

commons/all/src/main/java/org/infinispan/commons/util/EnumUtil.java, core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java, core/src/test/java/org/infinispan/persistence/SharedStoreTest.java
When SKIP_CACHE_LOAD flag is used with shared stores, the publisher should fetch the entries from the other nodes except for replicated caches
https://issues.redhat.com/browse/ISPN-15758
=> ISPN-15758 Publisher should fetch data from remote nodes

Jenkinsfile, bin/jira/add_comment.sh, bin/jira/add_fix_version.sh, bin/jira/add_pull_request.sh, bin/jira/assign_issue.sh, bin/jira/common.sh, bin/jira/track_flaky_tests.sh, bin/jira/transition.sh, bin/jira/upsert.sh
https://issues.redhat.com/browse/ISPN-15735
Example Run: https://ci.infinispan.org/job/Infinispan/job/PR-12026/36/, reports green as only one flaky test encountered and Jira created https://issues.redhat.com/browse/ISPN-15778
Every time a flaky test is encountered on a CI run a Jira will be created for the corresponding test method, or re-used if it already exists. A comment is then added to the Jira containing the test method and parameters (if any), a link to the offending CI job and the stacktrace reported by the test failure.
I would like to keep debug logging enabled for a little while as without it it's almost impossible to figure when things have gone wrong.
=> ISPN-15735 Report flaky infinispan tests to Jira

.github/workflows/dependabot_pull_request.yml, .github/workflows/pull_request_open.yml, bin/jira/get_milestone.sh
I have configured the GH rulesets so that PRs to the `main` and `14.0.x` branch require the relevant tests to pass before a PR can automatically be merged. Once this PR is is in, all we need to do is enable the "auto-merge" feature for this repository.
Once "auto-merge" is enabled, all Dependabot PRs will automatically be merged once the Jenkins and GH action CI has successfully run. A single test failure will prevent automatic merging and will require a manual review from a member of the team.
As part of this PR I have also added an automation so that PRs have a default milestone set. The rules for this are as follows:
- The maven version in the root pom is used to determine the major version of the release
- Jira is queried to return all unreleased releases for said major
- The oldest …
=> Dependabot auto merge

server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java, server/core/src/test/java/org/infinispan/server/core/backup/BackupManagerImplTest.java, server/tests/src/test/java/org/infinispan/server/functional/BackupManagerIT.java, server/tests/src/test/java/org/infinispan/server/functional/LargeBackupManagerIT.java
https://issues.redhat.com/browse/ISPN-15523
Batch requests while restoring the cache and using a Flowable so we have control more easily. For comparison, with the tests I did for the Jira:
14.0.7.Final takes around 1:30s.
```log
2024-01-23 18:30:20,102 INFO  (jgroups-13,node-0) [org.infinispan.server.core.backup.BackupManagerImpl] ISPN005045: Starting restore 'reproducer2' of 'backup.zip'
2024-01-23 18:31:48,750 INFO  (non-blocking-thread-node-0-p2-t11) [org.infinispan.server.core.backup.BackupManagerImpl] ISPN005046: Restore 'reproducer2' complete
```
14.0.22.Final takes around 4 min.
```log
2024-01-23 18:46:03,516 INFO  (jgroups-7,node-0) [org.infinispan.server.core.backup.BackupManagerImpl] ISPN005045: Starting restore 'reproducer2' of 'backup.zip'
2024-01-23 18:50:12,590 INFO …
```
=> ISPN-15523 Restore procedure performance regression

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemoteInnerPublisherHandler.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemotePublisher.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SslTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/BaseIterationFailOverTest.java
Issue: https://issues.redhat.com/browse/ISPN-15239
This is a backport of : https://github.com/infinispan/infinispan/pull/11422 to `11.0.x` branch for EAP 7.4.z
=> [11.0.x] ISPN-15239 HotRod client repeatedly retries iteration operation against failed server after removal from topology

core/src/main/resources/default-configs/default-jgroups-kubernetes.xml, documentation/src/main/asciidoc/topics/ref_jgroups_extras_properties.adoc
https://issues.redhat.com/browse/ISPN-15857
My setup is a set of Keycloak 18.0.2 clusters in an environment with nomad and consul. We're using DNS_PING with SRV records for a long time now and the JGroups setup is pretty simple:
```
JGROUPS_DISCOVERY_PROTOCOL=dns.DNS_PING
JGROUPS_DISCOVERY_PROPERTIES="dns_query="${dns_query}",dns_record_type="SRV""
JGROUPS_TRANSPORT_STACK="tcp"
```
When migrating this to Keycloak 23.0.7, I found that the dns_record_type separated with a comma is not supported anymore. After a lot of experimenting and a [PR on JGroups](https://github.com/belaban/JGroups/pull/776), I managed to use SRV records again with this infinispan configuration for jgroups:
```
<infinispan
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" …
```
=> ISPN-15857 Allow to configure DNS record type for DNS_PING with a Java property

core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java, core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreTest.java
https://issues.redhat.com/browse/ISPN-15943
I had to change the test to be a little flaky as it can't wait anymore as the fix now delays the stop until any log operation is fully completed.
=> ISPN-15943 SIFS during stop may not index puts that don't error

server/runtime/src/main/server/bin/gossip-router.sh, server/runtime/src/main/server/bin/gossiprouter.log4j2.xml, server/runtime/src/main/server/bin/probe.sh
https://issues.redhat.com/browse/ISPN-15942
Basic script to start the Gossip Router. Used by `TUNNEL` or `TCPGOSSIP` protocols.
```
$ ./bin/gossip-router.sh  -dump_msgs all
GossipRouter started in 335 ms listening on 0.0.0.0:12001
added pedro-desktop-31820 (127.0.0.1:58674) to group cluster
dst=null src=pedro-desktop-31820 (54 bytes): hdrs= PING: [GET_MBRS_REQ cluster=cluster initial_discovery=true], TP: [cluster=cluster]
dst=null src=pedro-desktop-31820 (54 bytes): hdrs= PING: [GET_MBRS_REQ cluster=cluster initial_discovery=true], TP: [cluster=cluster]
dst=null src=pedro-desktop-31820 (54 bytes): hdrs= PING: [GET_MBRS_REQ cluster=cluster initial_discovery=true], TP: [cluster=cluster]
```
And probe, if diagnostic is enabled
```
$ ./bin/probe.sh
#1 (90 bytes):
GossipRouter …
```
=> ISPN-15942 Add JGroups probe and gossip router scripts

commons/all/src/main/java/org/infinispan/commons/marshall/ProtoStreamTypeIds.java
* Add BitSetAdapter TypeId to prevent being reused.
https://issues.redhat.com/browse/ISPN-15963
=> ISPN-15963 Protostream 5.0.2.Final

.github/workflows/release.yml
With this change Images will automatically be created when tags for majors >= 15 are pushed. When we fork for 16, we'll need to adjust the logic slightly so that the correct image branch is checked out.
I also added the following commit to the infinispan-images repo: https://github.com/infinispan/infinispan-images/commit/b5697d5647c87bdfceeac0b41ff20fcee56f0447
=> Build images automatically on tag

server/resp/src/main/java/org/infinispan/server/resp/operation/SetOperation.java, server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
Fixes
https://issues.redhat.com/browse/ISPN-16008
GETSET now fails on non-string without changing the entry
=> ISPN-16008 fix GETSET

server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/internal/AGGCommand.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
Fixes https://issues.redhat.com/browse/ISPN-15993
args can be lowercase and "Inf" is handled
=> ISPN-15993 fix ZUNIONSTORE lowercase args and infinity

commons/all/src/main/java/org/infinispan/commons/util/concurrent/FileSystemLock.java, commons/all/src/test/java/org/infinispan/commons/util/FileSystemLockTest.java, core/src/main/java/org/infinispan/globalstate/impl/GlobalStateManagerImpl.java, core/src/main/java/org/infinispan/persistence/sifs/Log.java, core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreLockingTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreSplitInnerNodeTest.java, core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreStressTest.java
https://issues.redhat.com/browse/ISPN-16031
Create a global lock backed by the file system to control concurrent usage of files within and between virtual machines.
When creating the cache, an exception is thrown in case the current cache is not the unique owner of the cache data directory.
See, this change might mean a change in behavior for some applications. But it affects misconfigured embedded applications only.
=> ISPN-16031 Lock SIFS directories to avoid shared usage between instances

client/hotrod/pom.xml, server/hotrod/pom.xml, server/memcached/pom.xml, server/resp/pom.xml
* fix maven plugin name
Fixes
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.infinispan:infinispan-server-memcached:jar:15.0.4-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.infinispan.maven-plugins:protocol-parser-generator is missing. @ line 67, column 18
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.infinispan:infinispan-server-hotrod:jar:15.0.4-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.infinispan.maven-plugins:protocol-parser-generator is missing. @ line 89, column 18
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.infinispan:infinispan-server-resp:jar:15.0.4-SNAPSHOT
[WARNING] …
```
=> ISPN-16080 Use ProtoStream's ProtoLock

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/mode/EmbeddedIndexingModeTest.java, core/src/main/java/org/infinispan/configuration/cache/AbstractIndexingConfigurationChildBuilder.java, core/src/main/java/org/infinispan/configuration/cache/IndexingConfiguration.java, core/src/main/java/org/infinispan/configuration/cache/IndexingConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/cache/IndexingConfigurationChildBuilder.java, core/src/main/java/org/infinispan/configuration/parsing/Attribute.java, core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java, core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java, core/src/main/java/org/infinispan/encoding/DataConversion.java, core/src/main/resources/schema/infinispan-config-15.1.xsd, core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java, core/src/test/resources/configs/all/15.0.xml, core/src/test/resources/configs/all/15.1.xml, documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc, documentation/src/main/asciidoc/topics/xml/indexing_java_entities.xml, query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java, query/src/main/java/org/infinispan/query/impl/LifecycleManager.java, query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
https://issues.redhat.com/browse/ISPN-16069
=> ISPN-16069 Allow the indexes to start with embedded setup

documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc, documentation/src/main/asciidoc/titles/resp/resp-endpoint.asciidoc, documentation/src/main/asciidoc/topics/proc_server_configuring_resp.adoc
Docu has an unresolved ref that breaks part of the RESP docu, [see](https://infinispan.org/docs/15.0.x/titles/resp/resp-endpoint.html)
This is a fix.
Also some lines were replicated, I cleaned up a bit and made it similar to the REST docu structure.
fixes https://issues.redhat.com/browse/ISPN-16092
=> [DOC] ISPN-16092 Documenting RESP cache

integrationtests/server-integration/third-party-server/pom.xml
Related to PR #12447 . Missed second dependency of wildfly-galleon-pack.
=> Updated missed wildfly-galleon-pack dependency.

core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHash.java
1. Saving the hash code for the DefaultConsistentHash.
We calculate this value for *every* Hot Rod request to decide whether to send a new topology to the client. The CH is immutable so we can calculate this value only once.
=> ISPN-16178 Cache hashCode for DefaultConsistentHash

server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java, server/tests/src/test/java/org/infinispan/server/functional/rest/RestReinitializeCacheIT.java
https://issues.redhat.com/browse/ISPN-14418
Returns that an internal cache can't be initialized manually. This is an easier approach than making it work for internal caches. We can update it later so the lifecycle accepts asynchronous operations, so the DefaultCacheManager would initialize and handle requests, while the caches wouldn't accept requests.
At this point, if a user interacts with an internal cache after the graceful shutdown and it is missing members, it has some undefined behavior. We have an exception in transactional caches. The final result should not accept user requests but shouldn't fail to initialize the cache manager.
=> ISPN-14418 Return HTTP error when trying to initialize internal caches

query-core/src/main/java/org/infinispan/query/core/impl/EmbeddedQuery.java, server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheQueries.java
https://issues.redhat.com/browse/ISPN-16270
Use the storage media type to delete keys that match the delete statement.
I added a test that reproduces the issue.
=> ISPN-16270 Non indexed delete statement fails with MarshallingException

server/resp/src/main/java/org/infinispan/server/resp/commands/string/MSETNX.java, server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java, server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
fixes https://issues.redhat.com/browse/ISPN-16278
change map of bytes to map of wrappedbytearray so equals works and prevent entries with same key
=> ISPN-16278 [RESP] Fix msetnx behavior with same key

server/core/src/main/java/org/infinispan/server/iteration/IterationManager.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/iteration/BaseIterationCommand.java, server/resp/src/test/java/org/infinispan/server/resp/AbstractRespTest.java, server/resp/src/test/java/org/infinispan/server/resp/persistent/ClusteredPersistentStringCommandTest.java, server/resp/src/test/java/org/infinispan/server/resp/persistent/PersistentStringCommandTest.java
https://issues.redhat.com/browse/ISPN-16286
* Added single node and distributed tests with SIFS. The test executes the KEYS and SCAN commands;
* Updated the iteration to read the next batch on the BlockingManager and handed it to Netty's event loop to write the response.
=> ISPN-16286 RESP `KEYS *` hangs with persistence enabled

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/nested/ParentJoinNestedRemoteTest.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/predicateindex/be/BETreeMaker.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/BooleShannonExpansion.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/ExprVisitor.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/FullTextVisitor.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/NestedExpr.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/Visitor.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ExpressionBuilder.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ObjectPropertyHelper.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ProtobufPropertyHelper.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/QueryRendererDelegateImpl.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/VirtualExpressionBuilder.java, object-filter/src/test/java/org/infinispan/objectfilter/impl/syntax/parser/ExpressionBuilderTest.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/HibernateSearchPropertyHelper.java, query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryMaker.java, query/src/test/java/org/infinispan/query/config/EngineConfigTest.java, query/src/test/java/org/infinispan/query/dsl/embedded/impl/LuceneTransformationTest.java, query/src/test/java/org/infinispan/query/dsl/embedded/impl/model/Company.java, query/src/test/java/org/infinispan/query/dsl/embedded/impl/model/Employee.java, query/src/test/java/org/infinispan/query/model/Player.java, query/src/test/java/org/infinispan/query/model/Team.java, query/src/test/java/org/infinispan/query/nested/ParentJoinNestedTest.java
Initial implementation of Nested query support. Currently, only Indexed (EmbeddedLuceneQuery) queries are supported, Hybrid/Non-indexed queries will throw UnsupportedOperationException.
Introduced new NestedExpr visitable, which is similar to the AndExpr, that ensures that the correct nested predicate is created in HibernateSearch.
As this is only supported on fields that are embedded and in NESTED structure, in case of FLATTENED fields the original functionality is kept and a warning log will be shown.
=> ISPN-14457 - Support nested queries with Ickle - indexed implementation

commons/all/src/main/java/org/infinispan/commons/tx/TransactionImpl.java, core/src/main/java/org/infinispan/xsite/events/XSiteEventsManagerImpl.java
https://issues.redhat.com/browse/ISPN-16323
This PR corrects a misleading logging statement in the TransactionImpl class. The existing log message incorrectly states that the transaction’s commit method is invoked, whereas the surrounding code is actually performing a rollback operation.
Updated the log statement from `Transaction.commit() invoked in transaction with Xid=%s` to `Transaction.rollback() invoked in transaction with Xid=%s.`
The original log message could cause confusion during debugging or monitoring, as it suggests that a commit operation is being performed when, in fact, the transaction is being rolled back. This change ensures that the log accurately reflects the operation being performed, thereby improving clarity and maintainability of the code.
Verified that the log …
=> ISPN-16323 Correct Logging Statement for Transaction Rollback in TransactionImpl Class

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/QueryOperation.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/query/RemoteQuery.java
Add non blocking methods that can be used easily by the RemoteCache Query API
https://issues.redhat.com/browse/ISPN-16279
=> ISPN-16279 Non blocking methods for Query API

query/src/test/java/org/infinispan/query/model/Player.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufFieldIndexingMetadata.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadata.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/infinispan/IndexingMetadataHolder.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/infinispan/IndexingMetadataHolderFactory.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/infinispan/InfinispanAnnotations.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/search5/Search5MetadataCreator.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/GlobalReferenceHolder.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/reference/MessageReferenceProvider.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/mapping/typebridge/ProtobufMessageBinder.java
https://issues.redhat.com/browse/ISPN-16314
The implementation is a bit convoluted since with the current version of ProtoStream when we process the embedded annotations the embedded type descriptor is not filled. So my idea was to produce a wrapper and fill it later, when we discover that the type is actually used as embedded indexed.
=> ISPN-16314 Map embedded non-root-indexed types

.github/workflows/on_propen_push_do_test.yml, .github/workflows/on_run_create_jira_flaky_test.yml, .github/workflows/on_run_publish_surefire_report.yml
This moves surefire report in a separate workflow, for security reasons
=> ISPN-16253 publish suref report in separated workflow

.github/workflows/on_propen_push_do_test.yml
Use same flags as Jenkins for mvn verify: `-Dmaven.test.failure.ignore=true`
mvn verify will not fail with test errors.
=> Github action: don't fail on test error in mvn verify

server/insights/src/test/java/org/infinispan/server/insights/InsightsActivationTest.java
when applied at class level `dataProvider` input is not added to test name and leads to [ISPN-16501](https://issues.redhat.com/browse/ISPN-16501).
moved `dataProvider` annotation to method level
=> ISPN-16501 Remove test dup in report

core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyChangedState.java, core/src/test/java/org/infinispan/xsite/irac/ControlledExponentialBackOff.java, core/src/test/java/org/infinispan/xsite/irac/Irac3SitesExponentialBackOffTest.java, core/src/test/java/org/infinispan/xsite/irac/IracExponentialBackOffTest.java
This includes a few issues:
https://issues.redhat.com/browse/ISPN-16429
https://issues.redhat.com/browse/ISPN-16371
https://issues.redhat.com/browse/ISPN-16431
https://issues.redhat.com/browse/ISPN-16466
https://issues.redhat.com/browse/ISPN-16500
There were a couple of concurrency issues on the test side. After releasing the backoff CF, it could sometimes re-run, fail with an exception, and not see the new CF instance. Another issue is after seeing the BACKOFF event on the queue, we would release it for a retry, but the key didn't change the state to retry on time. Therefore, the key state was never sent.
=> ISPN-16500 Fix IRAC backoff flaky tests

bin/JfrParser.java, core/src/main/java/org/infinispan/configuration/global/GlobalTracingConfiguration.java, core/src/main/java/org/infinispan/configuration/global/TracingExporterProtocol.java, core/src/main/java/org/infinispan/telemetry/InfinispanSpanAttributes.java, server/core/src/main/java/org/infinispan/server/core/telemetry/OpenTelemetryService.java, server/core/src/main/java/org/infinispan/server/core/telemetry/OpenTelemetrySpan.java, server/core/src/main/java/org/infinispan/server/core/telemetry/TelemetryServiceFactory.java, server/core/src/main/java/org/infinispan/server/core/telemetry/jfr/JfrSpanProcessor.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
Just opening this as a draft so I can use it in the benchmarks.
FYI @fax4ever @pruivo 
It generates the events for JFR carrying the information from the span. For example:
This is to get an idea while running the benchmarks. Some information is still left out, like the category, node name, etc. The `Event` class of JFR accepts pretty much only primitives.
=> ISPN-16269 Export telemetry information with JFR

bin/jira/track_flaky_tests.sh
track_flaky_tests.sh fails to remove bad chars before querying jira
[ISPN-16515](https://issues.redhat.com/browse/ISPN-16515)
=> ISPN-16515 remove bad chars from testname for jira

persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/logging/Log.java, persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
As described in the Jira Task and demonstrated in a separate project, purgeExpired may lead to locking problems.
We fixed the problem in our keycloak installation by subclassing the StringBasedJdbcStore. But we would like the fix to be integrated into the standard. Therefore this pullrequest
I thought about integrating the reproduction scenario into the integration tests but was not able to completely understand their working.
Nevertheless the presented solution avoids several problems I see with the current implementation of purgeExpired:
1. concurrent read and delete on the same indices
2. unlimited transaction size
3. concurrent deletions on different connections in the same thread
=> ISPN-16215 - fix Locking problems during StringBaseJdbcStore#purgeExpired

.github/workflows/on_run_publish_surefire_report.yml
flaky tests are considered as failures by surefire report github action.
this PR removes flaky tests from xml report before publishing
=> ISPN-16592 Removing flaky test from failed report

Jenkinsfile, bin/jira/track_flaky_tests.sh
Only fail the post build stage  instead of the whole pipeline
also fixed test name extraction (some test with arguments contains `\[`)
=> ISPN-16638 Don't fail the pipeline if flaky jira fails

.github/dependabot.yml
https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
```quote
If you only require security updates and want to exclude version updates, you can set open-pull-requests-limit to 0 in order to prevent version updates for a given package-ecosystem.
```
=> Dependabot security only 14.0.x

client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemoteInnerPublisherHandler.java, client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemotePublisher.java, client/hotrod-client-new/src/main/java/org/infinispan/client/hotrod/impl/operations/IterationNextOperation.java, client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/impl/iteration/BaseIterationFailOverTest.java, client/hotrod-client-new/src/test/java/org/infinispan/client/hotrod/impl/iteration/Util.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemoteInnerPublisherHandler.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemotePublisher.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/IterationNextOperation.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/BaseIterationFailOverTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/Util.java
* Fix issue where an invalid iteration request would complete segments
https://issues.redhat.com/browse/ISPN-16597
=> ISPN-16597 Client iteration can miss segments due to invalid iteration response during shutdown

server/runtime/src/main/java/org/infinispan/server/SecurityActions.java, server/runtime/src/main/java/org/infinispan/server/Server.java
https://issues.redhat.com/browse/ISPN-12828
Fix for #12912. It should call postStart with a context to have permission to create the cache.
=> ISPN-12828 Post start from security action

server/resp/src/main/java/org/infinispan/server/resp/commands/tx/WATCH.java, server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java
https://issues.redhat.com/browse/ISPN-16748
The test is disabled because Lettuce can't properly parse the EXEC response in this case.
=> ISPN-16748 [RESP] WATCH within a MULTI should not fail

server/resp/src/main/java/org/infinispan/server/resp/commands/tx/WATCH.java, server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13027
https://issues.redhat.com/browse/ISPN-16748
The test is disabled because Lettuce can't properly parse the EXEC response in this case.
=> [15.0.x] ISPN-16748 [RESP] WATCH within a MULTI should not fail

server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZSCAN.java, server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/internal/POP.java, server/resp/src/main/java/org/infinispan/server/resp/serialization/DoubleSerializer.java, server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
https://issues.redhat.com/browse/ISPN-16329
* Pop in sorted set returns a list of lists when count is present;
* Fix DoubleSerializer conversion to byte array;
* Fix double parsing for ZSCAN;
=> ISPN-16329 RESP3 response serialization compliance

server/resp/src/main/java/org/infinispan/server/resp/commands/set/SINTER.java, server/resp/src/main/java/org/infinispan/server/resp/commands/set/SINTERSTORE.java, server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13072
Missing keys should be treated as empty set.
Fixes [ISPN-16771](https://issues.redhat.com/browse/ISPN-16771)
=> [15.0.x] ISPN-16771 [RESP] Fix sinterstore with missing keys

server/resp/src/main/java/org/infinispan/server/resp/CacheRespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespChannelInitializer.java, server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/AUTH.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/HELLO.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/QUIT.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/DISCARD.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/EXEC.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/MULTI.java, server/resp/src/main/java/org/infinispan/server/resp/tx/RespTransactionHandler.java, server/tests/src/test/java/org/infinispan/server/security/authorization/RESPAuthorizationTest.java, server/tests/src/test/resources/configuration/cache-container/clustered-authz-common-name.xml, server/tests/src/test/resources/configuration/cache-container/clustered-authz.xml
https://issues.redhat.com/browse/ISPN-16787
We authenticate and create the SecureCache with the correct subject. However, once we create a new handler, we invoke the cache manager to get the cache again instead of re-utilizing the SecureCache with the subject.
=> ISPN-16787 [RESP] Cache with authorization enabled fails to connect

documentation/src/main/asciidoc/topics/con_performance_partition_handling.adoc
**Backport:** https://github.com/infinispan/infinispan/pull/13062
https://issues.redhat.com/browse/ISPN-16765
=> [15.0.x] ISPN-16765: Incorrect note about GC pause in performance documentation

server/resp/src/main/java/org/infinispan/server/resp/CacheRespRequestHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespChannelInitializer.java, server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/AUTH.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/HELLO.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/QUIT.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/DISCARD.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/EXEC.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/MULTI.java, server/resp/src/main/java/org/infinispan/server/resp/tx/RespTransactionHandler.java, server/tests/src/test/java/org/infinispan/server/security/authorization/RESPAuthorizationTest.java, server/tests/src/test/resources/configuration/cache-container/clustered-authz-common-name.xml, server/tests/src/test/resources/configuration/cache-container/clustered-authz.xml
**Backport:** https://github.com/infinispan/infinispan/pull/13087
https://issues.redhat.com/browse/ISPN-16787
We authenticate and create the SecureCache with the correct subject. However, once we create a new handler, we invoke the cache manager to get the cache again instead of re-utilizing the SecureCache with the subject.
=> [15.0.x] ISPN-16787 [RESP] Cache with authorization enabled fails to connect

core/src/main/java/org/infinispan/cache/impl/DecoratedCache.java, core/src/main/java/org/infinispan/cache/impl/InternalCache.java, core/src/main/java/org/infinispan/configuration/cache/TransactionConfigurationBuilder.java, core/src/main/java/org/infinispan/functional/impl/AbstractFunctionalMap.java, core/src/main/java/org/infinispan/functional/impl/FunctionalMapImpl.java, core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/EXEC.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/TransactionDecorator.java, server/resp/src/main/java/org/infinispan/server/resp/logging/Log.java, server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java, server/resp/src/test/java/org/infinispan/server/resp/dist/TransactionClusteredTest.java, server/resp/src/test/java/org/infinispan/server/resp/types/TransactionMediaTypeTest.java
https://issues.redhat.com/browse/ISPN-16730
The core class is the `TransactionDecorator` which creates a `DecoratedCache` to propagate the transactional context in all commands. It is really tricky because it needs to keep working the `EncoderCache` in any combination.
I also changed the functional map to utilize the methods in the DecoderCache to create the invocation context.
=> ISPN-16730 Handle transactional context with many operations

core/src/main/java/org/infinispan/cache/impl/DecoratedCache.java, core/src/main/java/org/infinispan/cache/impl/InternalCache.java, core/src/main/java/org/infinispan/configuration/cache/TransactionConfigurationBuilder.java, core/src/main/java/org/infinispan/functional/impl/AbstractFunctionalMap.java, core/src/main/java/org/infinispan/functional/impl/FunctionalMapImpl.java, core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java, server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java, server/resp/src/main/java/org/infinispan/server/resp/RespServer.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/EXEC.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/TransactionDecorator.java, server/resp/src/main/java/org/infinispan/server/resp/logging/Log.java, server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java, server/resp/src/test/java/org/infinispan/server/resp/dist/TransactionClusteredTest.java, server/resp/src/test/java/org/infinispan/server/resp/types/TransactionMediaTypeTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13083
https://issues.redhat.com/browse/ISPN-16730
The core class is the `TransactionDecorator` which creates a `DecoratedCache` to propagate the transactional context in all commands. It is really tricky because it needs to keep working the `EncoderCache` in any combination.
I also changed the functional map to utilize the methods in the DecoderCache to create the invocation context.
=> [15.0.x] ISPN-16730 Handle transactional context with many operations

server/tests/src/test/java/org/infinispan/server/persistence/AsyncJdbcStringBasedCacheStore.java
**Backport:** https://github.com/infinispan/infinispan/pull/13146
Additional fix for https://issues.redhat.com/browse/ISPN-16587
=> [15.0.x] Forgotten Database tag on AsyncJdbcStringBasedCacheStore

query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java, query/src/test/java/org/infinispan/query/maxresult/DistributedMaxResultTest.java
https://issues.redhat.com/browse/ISPN-16808
Backport of https://github.com/infinispan/infinispan/pull/13134
To fix the test/CI we need also: https://github.com/infinispan/infinispan/pull/13156
That is must be backported to 15 and merged first!
=> [15.0] ISPN-16808 Do not limit delete cq command

commons/all/src/main/java/org/infinispan/commons/jdkspecific/ThreadCreator.java
Currently virtual threads can only be enabled by setting a system property. This change makes it possible to also configure programmatically.
=> ISPN-16848 Programmatic configuration of virtual threads

.mvn/extensions.xml
Closes #13236
Using the following command:
`mvn clean install -DskipTests -Dmaven.build.cache.enabled=true -am -pl commons/all`
1st run: ~18s
2nd run: ~3s
=> Add maven-build-cache-extension to speed up the build

server/runtime/pom.xml
change execution order to have all the files ready for testing.
Fixes #13217
=> Fix LicenseTest.testLicense. Fixes #13217

.github/workflows/pull_request_open.yml
use pagination when labels are more than 30.
Fixes #13311
=> Paginate gh get labels call. Fixes #13311

cli/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestRawClientJDK.java, client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestServerClientJDK.java, commons/all/src/main/java/org/infinispan/commons/dataconversion/MediaType.java, server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java, server/runtime/src/main/server/bin/report.sh, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java, server/tests/pom.xml, server/tests/src/test/java/org/infinispan/server/security/authorization/RESTAuthorizationTest.java
* Set the header and the correct handler to parse the body;
* Handle the stream as gzip in the CLI client;
* Updates the test to generate the report and validate the contents;
Closes #13210.
=> Fix REST client parsing for gzip content

client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/nested/ParentJoinNestedRemoteTest.java, object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ExpressionBuilder.java, query/src/test/java/org/infinispan/query/nested/ParentJoinNestedTest.java
Fixes #13405
Implemented proper handling of OR predicates when using it with nested objects in an ickle query. 
Problematic query example:
```
select t.name from org.infinispan.query.model.Team t 
join t.firstTeam p
where (p.color ='red' AND p.number=7) or (p.color='blue' AND p.number=7)
```
After the fix this returns correct results instead of an error
=> [#13405] - nested queries improvements - proper handling of OR predicates

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
* Collect the configurations to a concurrent map;
* Uniform usage of synchronized block to access remote caches.
Closes #13272.
=> [#13272] Collect remote cache configuration to concurrent map

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
**Backport:** https://github.com/infinispan/infinispan/pull/13375
* Collect the configurations to a concurrent map;
* Uniform usage of synchronized block to access remote caches.
Closes #13272.
=> [15.0.x] [#13272] Collect remote cache configuration to concurrent map

commons/all/src/main/java/org/infinispan/commons/jdkspecific/ThreadCreator.java, commons/all/src/main/java/org/infinispan/commons/tx/TransactionImpl.java, commons/jdk21/src/main/java/org/infinispan/commons/jdk21/ThreadCreatorImpl.java, commons/spi/src/main/java/org/infinispan/commons/spi/ThreadCreator.java, core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java, core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadPoolExecutorFactory.java, core/src/main/java/org/infinispan/notifications/cachelistener/cluster/ClusterListenerReplicateCallable.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/StaggeredRequest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationThreadCountTest.java, core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java, core/src/test/resources/configs/xsite/bridge.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/udp.xml, server/runtime/src/test/java/org/infinispan/server/task/ServerTaskEngineBlockingTest.java
* Replace synchronized block with lock
* Remove FD_SOCK2 - not required for our test suite
* Use platform threads in non-blocking thread pool
Closes #13609
=> [#13609] Reduce virtual thread pinned events

.github/workflows/operator_upgrade.yaml
**Backport:** https://github.com/infinispan/infinispan/pull/13607
Closes #13604
Closes #13645
=> [15.1.x] [#13604] Only test server upgrades on CI with the latest Operator release

.github/workflows/on_build_do_test.yml
archive logs file as artefact at the end of the GH Test workflow
=> [#13673] Archive log files as artefact

commons/all/src/main/java/org/infinispan/commons/jdkspecific/ThreadCreator.java, commons/all/src/main/java/org/infinispan/commons/tx/TransactionImpl.java, commons/jdk21/src/main/java/org/infinispan/commons/jdk21/ThreadCreatorImpl.java, commons/spi/src/main/java/org/infinispan/commons/spi/ThreadCreator.java, core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java, core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadPoolExecutorFactory.java, core/src/main/java/org/infinispan/notifications/cachelistener/cluster/ClusterListenerReplicateCallable.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/StaggeredRequest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationThreadCountTest.java, core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java, core/src/test/resources/configs/xsite/bridge.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/udp.xml, server/runtime/src/test/java/org/infinispan/server/task/ServerTaskEngineBlockingTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13610
* Replace synchronized block with lock
* Remove FD_SOCK2 - not required for our test suite
* Use platform threads in non-blocking thread pool
Closes #13609
=> [15.1.x] [#13609] Reduce virtual thread pinned events

commons/all/src/main/java/org/infinispan/commons/jdkspecific/ThreadCreator.java, commons/all/src/main/java/org/infinispan/commons/tx/TransactionImpl.java, commons/jdk21/src/main/java/org/infinispan/commons/jdk21/ThreadCreatorImpl.java, commons/spi/src/main/java/org/infinispan/commons/spi/ThreadCreator.java, core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java, core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadPoolExecutorFactory.java, core/src/main/java/org/infinispan/notifications/cachelistener/cluster/ClusterListenerReplicateCallable.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/StaggeredRequest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationThreadCountTest.java, core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java, core/src/test/resources/configs/xsite/bridge.xml, core/src/test/resources/stacks/tcp.xml, core/src/test/resources/stacks/udp.xml, server/runtime/src/test/java/org/infinispan/server/task/ServerTaskEngineBlockingTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13610
* Replace synchronized block with lock
* Remove FD_SOCK2 - not required for our test suite
* Use platform threads in non-blocking thread pool
Closes #13609
=> [15.0.x] [#13609] Reduce virtual thread pinned events

client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java, client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java, client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java, client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java, client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CloseBeforeEnqueuingTest.java
This happens in a very narrow case: the channel has received the `ChannelPoolCloseEvent`, it is still open and available on the pool, and the operation is already trying to write the bytes. In this case, the operation would hit the `HeaderDecoder` with the `closing` flag set and fail without retrying.
I'll open a backport manually.
Close #13648.
=> [#13648] Retry operations submitted to closing channel

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/AuthenticationTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13735
client to hang
Fixes #13734
=> [15.1.x] [#13734] Client topology installed during authentication can cause

client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/tracing/TracingSecurityTest.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/TracingSecurityTest.java, remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java
=> [#13740] ProtobufMetadataManagerImpl should utilise SecurityActions to retrieve the cache manager configuration

server/resp/src/main/java/org/infinispan/server/resp/commands/list/blocking/AbstractBlockingPop.java, server/resp/src/test/java/org/infinispan/server/resp/RespBxPOPTest.java
The only code change is for #13395. All the other fixes are changes in the test.
Basically, concurrency issues around the order of operation. In the tests, we needed to wait for push operations to complete before doing a range check.
Closes #13399.
Closes #13660.
Closes #13382.
Closes #13395.
=> [#13399] RESP batch of flaky fixes

.github/workflows/on_propen_push_do_build.yml, .github/workflows/operator_upgrade.yaml, .github/workflows/pull_request_native_cli.yml, .github/workflows/supported_jdks.yaml
replaced:
- `github.event.push.ref` with `github.event.ref`
-  `github.event.repository.full_name` with `github.repository` 
to attach git `repository` and `ref` correctly to concurrency group on push event.
=> [#13836] Fix concurrency group for push

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/PingOnStartupTest.java
Fixes #13834
This probably also fixes #13793, but would need to be confirmed.
=> [#13834] Install client topology only after a channel is fully connected

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/PingOnStartupTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13838
Fixes #13834
This probably also fixes #13793, but would need to be confirmed.
=> [15.1.x] [#13834] Install client topology only after a channel is fully connected

build/configuration/pom.xml, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
Fixes https://github.com/netty/netty/security/advisories/GHSA-xq3w-v528-46rv
Medium severity. 
We use Lettuce primarily on our tests. This warning comes from the CLI using Lettuce to submit get/set operations for the benchmark command.
=> [15.0.x] Bump io.lettuce:lettuce-core from 6.3.2.RELEASE to 6.5.2.RELEASE

core/src/main/java/org/infinispan/cache/impl/DecoratedCache.java, server/resp/src/main/java/org/infinispan/server/resp/commands/tx/TransactionDecorator.java, server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java, server/resp/src/test/java/org/infinispan/server/resp/dist/TransactionClusteredTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/13178
https://issues.redhat.com/browse/ISPN-16840
The `withFlags` was creating a new instance of the `DecoratedCache` instead of the instance holding the TX context for RESP. That would create a new transaction for the set operation.
I took the chance to increase coverage in the TX tests in RESP by operating over local and remote keys.
=> [15.0.x] ISPN-16840 [RESP] LPUSH + DEL + SET fails with unable to aquire a lock

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
**Backport:** https://github.com/infinispan/infinispan/pull/13830
Closes #13829
=> [15.1.x] [#13829] Don't include protocol stack in transport exceptions

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
**Backport:** https://github.com/infinispan/infinispan/pull/13830
Closes #13829
=> [15.0.x] [#13829] Don't include protocol stack in transport exceptions

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
**Backport:** https://github.com/infinispan/infinispan/pull/13830
Closes #13829
=> [14.0.x] [#13829] Don't include protocol stack in transport exceptions

documentation/src/main/asciidoc/stories/assembly_upgrading.adoc, documentation/src/main/asciidoc/topics/ref_indexing_configuration.adoc, documentation/src/main/asciidoc/topics/upgrading.adoc, query/src/main/java/org/infinispan/query/impl/IndexStartupRunner.java, query/src/test/java/org/infinispan/query/distributed/IndexWithSharedStoreTest.java
Closes #13284
Thanks again @pruivo for the reproducer. It will be a nice template for possible similar tests in the future.
It is very cool IMO since with it we simulate the classic node crash / recovery scenario, in this case used to
verify the index consistency when a node recovers.
The fix I'm proposing is quite simple. Since we always have the data and the indexes and the data is always the
source of truth, we can realign the indexes.
Other suggestions are more than welcome.
=> [#13284] shared storage index startup

.github/workflows/on_build_do_test.yml, .github/workflows/on_test_publish_surefire_report.yml, server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/RestTestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestClient.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/Database.java, server/tests/pom.xml, server/tests/src/test/java/org/infinispan/server/persistence/AsyncJdbcStringBasedCacheStore.java, server/tests/src/test/java/org/infinispan/server/persistence/JGroupsJdbcPing2IT.java, server/tests/src/test/java/org/infinispan/server/persistence/JdbcStringBasedCacheStoreIT.java, server/tests/src/test/java/org/infinispan/server/persistence/ManagedConnectionOperations.java, server/tests/src/test/java/org/infinispan/server/persistence/PooledConnectionOperations.java, server/tests/src/test/resources/configuration/datasources/default.xml, server/tests/src/test/resources/database/db2.properties, server/tests/src/test/resources/database/jdbc-drivers.txt
Enables '@database' test execution against DB2 and adds it to the matrix alongside MSSQL and OracleDB
Closes #13739
=> [#13739] Enable server database tests execution against DB2

.github/workflows/on_propen_push_do_test.yml, server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/RestTestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestClient.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/ContainerDatabase.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/Database.java, server/tests/pom.xml, server/tests/src/test/java/org/infinispan/server/persistence/AsyncJdbcStringBasedCacheStore.java, server/tests/src/test/java/org/infinispan/server/persistence/JGroupsJdbcPing2IT.java, server/tests/src/test/java/org/infinispan/server/persistence/JdbcStringBasedCacheStoreIT.java, server/tests/src/test/java/org/infinispan/server/persistence/ManagedConnectionOperations.java, server/tests/src/test/java/org/infinispan/server/persistence/PooledConnectionOperations.java, server/tests/src/test/resources/configuration/datasources/default.xml, server/tests/src/test/resources/database/db2.properties, server/tests/src/test/resources/database/jdbc-drivers.txt
**Backport:** https://github.com/infinispan/infinispan/pull/13792
Enables '@database' test execution against DB2 and adds it to the matrix alongside MSSQL and OracleDB
=> [15.0.x] [#13739] Enable server database tests execution against DB2

documentation/src/main/asciidoc/topics/ref_redis_commands.adoc, server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java, server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONDEL.java, server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONFORGET.java, server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java, server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
RESP JSON.FORGET implementation. (alias of json.del)
Fixed #13429
=> [#13429] RESP json.forget command

persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/JdbcStoreCompatibilityTest.java
Closes #14157
@tristantarrant It seems the failure was caused by https://github.com/infinispan/infinispan/pull/11731, but I have no idea why it took so long for us to see the failures on CI :upside_down_face:
=> [#14157] Fix recreation of DB in JdbcStoreCompatibilityTest to prevent table already exists exceptions

core/src/main/java/org/infinispan/topology/RebalanceConfirmationCollector.java, core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
**Backport:** https://github.com/infinispan/infinispan/pull/14152
Closes #14151
I backported the change to ISPN 15.0.x and used it in KC 26.2.x and didn't see any additional information about pinned threads, so I assume this is now sufficient.
=> [15.1.x] [#14151] Avoid thread pinning in RebalanceConfirmationCollector

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationChildBuilder.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelHandler.java, client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationDispatcher.java, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/TransportFactoryTest.java
=> [#14108] Only close client EventLoopGroup if default TransportFactory is

core/src/main/java/org/infinispan/topology/RebalanceConfirmationCollector.java, core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
**Backport:** https://github.com/infinispan/infinispan/pull/14152
Closes #14151
I backported the change to ISPN 15.0.x and used it in KC 26.2.x and didn't see any additional information about pinned threads, so I assume this is now sufficient.
=> [15.0.x] [#14151] Avoid thread pinning in RebalanceConfirmationCollector

build/configuration/pom.xml, pom.xml, server/resp/pom.xml, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MEMORY.java, server/resp/src/main/java/org/infinispan/server/resp/commands/connection/MemoryEntrySizeUtils.java, server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
~~Implemented using [jol library](https://github.com/openjdk/jol)~~
changed to use ehcache.sizeof which uses Unsafe to compute the size. it gives the same results as jol anyway.
=> ISPN-16285 Memory size for more resp types

core/src/main/java/org/infinispan/configuration/global/AbstractGlobalConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/global/AllowListConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/global/GlobalConfigurationBuilder.java, core/src/main/java/org/infinispan/configuration/global/GlobalConfigurationChildBuilder.java, core/src/main/java/org/infinispan/metrics/config/MicrometerMeterRegisterConfigurationBuilder.java
This change extends AbstractGlobalConfigurationBuilder with module configuration, and makes additional config builders extend AbstractGlobalConfigurationBuilder for easier fluent programmatic building.
=> [#14312] More complete global config builders

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemoteInnerPublisherHandler.java
* Don't retry publisher operation if server key is null
Fixes #14324
=> [#14324] Client can be inudated with large stack traces

core/src/main/java/org/infinispan/remoting/transport/ResponseCollector.java, core/src/main/java/org/infinispan/remoting/transport/impl/ExclusiveTargetRequest.java, core/src/main/java/org/infinispan/remoting/transport/impl/MultiTargetRequest.java, core/src/main/java/org/infinispan/remoting/transport/impl/Request.java, core/src/main/java/org/infinispan/remoting/transport/impl/SingleTargetRequest.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/SingleSiteRequest.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/StaggeredRequest.java
Fixes #14257 
I have updated all of the Requests to no longer use any locking on the actual Collectors. Instead it now uses exclusive access so that the collector can only be invoked on a single thread at a time without locking for a given instance of a Request. Note that if a collector is shared between requests this is no longer protected and honestly shouldn't be happening unless the collector was immutable already before.
=> [#14257] SingleResponseCollector excessive locking

core/src/main/java/org/infinispan/remoting/transport/jgroups/AbstractJGroupsChannelConfigurator.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsChannelConfigurator.java, core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Currently if a JGroups channel is created manually then no metrics will be registered for it since the metrics channel listener is not added. This change makes it so that the channel listener is added when the channel is initialized regardless of how it is created (it also contains some minor cleanup and fix for warnings).
Closes #14313
=> [#14313] Metrics with manually created JGroups channel

server/core/src/main/java/org/infinispan/server/core/factories/NettyEventLoopFactory.java
* Utilize a similar strategy to the non-blocking thread factory.
Closes #14468.
=> [#14468] Update server thread naming

.github/workflows/on_build_do_test.yml
The PR fixes the jacoco-report action uploading the Coverage related information under base commit/PR. I have tested this impl with different PR situations, and seems that it works properly. The correct PR is updated with the necessary data.
=> [#14132] Report jacoco coverage using GitHub actions - part2

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/topology/CacheInfo.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/Authentication.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/ServerHotRodBlockHoundIntegration.java, server/hotrod/src/main/java/org/infinispan/server/hotrod/TransactionRequestProcessor.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodAsymmetricClusterTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodDefaultCacheTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodFunctionalTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiNodeTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleClusteredNonLoopbackTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleClusteredTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSniFunctionalTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodStatsTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/counter/CounterManagerOperationTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/logging/HotRodAccessLoggingTest.java, server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodClient.java
* PING and AUTH_MECH commands offload cache initialization
* Rely on cache always invoking above commands
Fixes #14490
=> [#14490] Server new cache startup should not block

documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc
**Backport:** https://github.com/infinispan/infinispan/pull/14531
=> [15.0.x] [#14322] Document Vector Search as a not supported feature

server/core/src/main/java/org/infinispan/server/core/ServerCoreBlockHoundIntegration.java
**Backport:** https://github.com/infinispan/infinispan/pull/14601
Fixes #14600
=> [15.1.x] [#14600] Test can fail on shutdown due to netty thread blocking

core/src/main/java/org/infinispan/metrics/config/MicrometerMeterRegistryConfiguration.java
The GlobalConfigurationBuilder read(GlobalConfiguration template) method requires that classes registered as modules be annotated with @BuiltBy at runtime.
Without the required annotation, a NullPointerException is observed.
Caused by: java.lang.NullPointerException: Cannot invoke "org.infinispan.commons.configuration.BuiltBy.value()" because "builtBy" is null
The simple fix here is to add the missing annotation. I tested this locally and observed that the configured metrics registry is used.
=> [#14581] Missing BuiltBy annotation

core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
* Disabling test until we can fix it
This does not resolve the issue, just disables the test until we can fix it properly. It can hang CI runs though when it happens so we are disabling for now.
=> [#14618] DistSyncNonTxStateTransferTest can fail to complete

commons/all/src/main/java/org/infinispan/commons/internal/CommonsBlockHoundIntegration.java
=> [#14638] JVM GC ReferenceQueue should not be flagged as blocking

hibernate/cache-v62/pom.xml
* Utilize JUnit 5 BOM in the tests to align versions.
Closes #14643.
=> [#14643] Utilize JUnit BOM for dependency

core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHashFactory.java, core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHashFactory.java, core/src/main/java/org/infinispan/distribution/ch/impl/SyncConsistentHashFactory.java, core/src/main/java/org/infinispan/distribution/ch/impl/SyncReplicatedConsistentHashFactory.java, core/src/main/java/org/infinispan/distribution/ch/impl/TopologyAwareSyncConsistentHashFactory.java, core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java, core/src/test/java/org/infinispan/configuration/HashConfigurationBuilderTest.java, core/src/test/java/org/infinispan/conflict/impl/StateReceiverTest.java, core/src/test/java/org/infinispan/distribution/ConsistentHashPerfTest.java, core/src/test/java/org/infinispan/distribution/ZeroCapacityNodeTest.java, core/src/test/java/org/infinispan/distribution/ch/DefaultConsistentHashPersistenceTest.java, core/src/test/java/org/infinispan/distribution/ch/ReplicatedConsistentHashFactoryTest.java, core/src/test/java/org/infinispan/distribution/ch/ReplicatedConsistentHashPersistenceTest.java, core/src/test/java/org/infinispan/distribution/ch/SyncConsistentHashFactoryKeyDistributionTest.java, core/src/test/java/org/infinispan/distribution/ch/SyncConsistentHashPersistenceTest.java, core/src/test/java/org/infinispan/distribution/ch/TopologyAwareSyncConsistentHashFactoryKeyDistributionTest.java, core/src/test/java/org/infinispan/distribution/rehash/WorkDuringJoinTest.java, core/src/test/java/org/infinispan/distribution/topologyaware/TopologyAwareSyncConsistentHashFactoryTest.java, core/src/test/java/org/infinispan/partitionhandling/impl/PreferAvailabilityStrategyTest.java, core/src/test/java/org/infinispan/remoting/rpc/RpcManagerTest.java, core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java, core/src/test/java/org/infinispan/statetransfer/StateProviderTest.java, core/src/test/java/org/infinispan/stress/LargeCluster2StressTest.java, core/src/test/java/org/infinispan/topology/ClusterCacheStatusTest.java, core/src/test/java/org/infinispan/topology/ClusterTopologyManagerImplTest.java
CacheJoinInfo instances are not reused properly due to every ConsistentHashFactory being a separate instance that didn't implement equals. This changes it so these are singletons as they have no state and allows CacheJoinInfo to work properly with equals which means they are reused in the ManagerStatusResponse in ClusterTopologyManagerImpl
=> [#14133] Change consistent hash factories to be singletons

core/src/main/java/org/infinispan/commands/topology/CacheStatusRequestCommand.java, core/src/main/java/org/infinispan/commands/topology/TopologyUpdateCommand.java, core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java, core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/test/java/org/infinispan/topology/AbstractStatefulCluster.java, core/src/test/java/org/infinispan/topology/ClusterTopologyStatefulTest.java
* Remove dependency from LocalTopologyManagerImpl.
* Cached components ensure correct initialization order.
Closes #14630
Closes #13346 
Closes #13356
Closes #13397 
Closes #13362 
I am not sure if there is something else at play for these:
Closes #13353
Closes #13574 
Closes #13685
Closes #14605
=> [#14630] Break cycle between local and cluster topology manager

core/src/main/java/org/infinispan/metrics/config/MicrometerMeterRegistryConfiguration.java
**Backport:** https://github.com/infinispan/infinispan/pull/14612
The GlobalConfigurationBuilder read(GlobalConfiguration template) method requires that classes registered as modules be annotated with @BuiltBy at runtime.
Without the required annotation, a NullPointerException is observed.
Caused by: java.lang.NullPointerException: Cannot invoke "org.infinispan.commons.configuration.BuiltBy.value()" because "builtBy" is null
The simple fix here is to add the missing annotation. I tested this locally and observed that the configured metrics registry is used.
=> [15.0.x] [#14581] Missing BuiltBy annotation

.github/workflows/sync_docs.yml
Documentation pushed to 14.0.x branch must go under 14.0.x folder
fix for #14663
=> [#14663] [14.0.x] On 14.0.x docs go only to 14.0.x

.github/workflows/sync_docs.yml
Documentation pushed to 15.0.x branch must go under 15.0.x folder
fix for #14663
=> [#14663] On 15.0.x docs go only to 15.0.x

.github/workflows/sync_docs.yml
Documentation pushed to 15.1.x branch must go under 15.1.x folder
fix for #14663
=> [#14663] On 15.1.x docs go only to 15.1.x

.github/workflows/sync_docs.yml
Documentation pushed to 14.0.x branch must go under stable folder
fix for #14663
=> [#14663] On 15.2.x docs go to stable

server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java, server/tests/src/test/java/org/infinispan/server/rollingupgrade/DefaultRollingUpgradeTest.java
The downside is that the rest client connects to a specific server. This means we need to specify if it is connecting to the from or to driver.  For example, connecting to the driver in the from with state `REMOVED_OLD` could connect to one of the stopped servers, which will fail the test.
=> [#14562] Adding Rest client option

core/src/main/java/org/infinispan/commands/topology/CacheStatusRequestCommand.java, core/src/main/java/org/infinispan/commands/topology/TopologyUpdateCommand.java, core/src/main/java/org/infinispan/commands/topology/TopologyUpdateStableCommand.java, core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java, core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/test/java/org/infinispan/topology/AbstractStatefulCluster.java, core/src/test/java/org/infinispan/topology/ClusterTopologyStatefulTest.java
* Remove dependency from LocalTopologyManagerImpl.
* Cached components ensure correct initialization order.
Backport of #14631.
=> [15.0.x] [#14630] Break cycle between local and cluster topology manager

core/src/main/java/org/infinispan/commands/topology/CacheStatusRequestCommand.java, core/src/main/java/org/infinispan/commands/topology/TopologyUpdateCommand.java, core/src/main/java/org/infinispan/commands/topology/TopologyUpdateStableCommand.java, core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java, core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/test/java/org/infinispan/topology/AbstractStatefulCluster.java, core/src/test/java/org/infinispan/topology/ClusterTopologyStatefulTest.java
* Remove dependency from LocalTopologyManagerImpl.
* Cached components ensure correct initialization order.
Backport of #14631
=> [15.2.x] [#14630] Break cycle between local and cluster topology manager

core/src/main/resources/default-configs/default-jgroups-azure.xml, core/src/main/resources/default-configs/default-jgroups-ec2.xml, core/src/main/resources/default-configs/default-jgroups-google.xml, core/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/main/resources/default-configs/default-jgroups-tunnel.xml, core/src/main/resources/default-configs/default-jgroups-udp.xml
**Backport:** https://github.com/infinispan/infinispan/pull/14726
Closes #14725
=> [15.0.x] [#14725] Add port_range back to the default stacks

documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
**Backport:** https://github.com/infinispan/infinispan/pull/14816
Closes #14815.
=> [15.0.x] [#14815] RESP documentation page fix

documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
**Backport:** https://github.com/infinispan/infinispan/pull/14816
Closes #14815.
=> [15.2.x] [#14815] RESP documentation page fix

.github/workflows/sync_docs.yml
Documentation pushed to main branch must go under dev folder
fix for #14663
=> [#14663] On main docs go to dev

core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java, core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java, core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java, core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
**Backport:** https://github.com/infinispan/infinispan/pull/14823
Fixes #14820
=> [15.2.x] [#14820] Size method with a local cache and store is not optimized

commons/all/src/main/java/org/infinispan/commons/internal/CommonsBlockHoundIntegration.java, commons/all/src/main/java/org/infinispan/commons/logging/Log.java, commons/all/src/main/java/org/infinispan/commons/logging/LogFactory.java, commons/all/src/main/java/org/infinispan/commons/util/ProgressTracker.java, commons/all/src/test/java/org/infinispan/commons/util/ProgressTrackerTest.java, core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/FileProvider.java, core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java, query/src/main/java/org/infinispan/query/impl/ComponentRegistryUtils.java, query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java, query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerProgressState.java, tools/src/main/java/org/infinispan/tools/store/migrator/file/SoftIndexFileStoreIterator.java
The tracker will receive the expected number of operations still pending to perform and will gradually reach zero. The timeout executor will output how many tasks are still pending and whether it has progressed since the last check.
Currently, I am wrapping:
* State transfer: keep track of outstanding requests for segments. This is the same metric we expose.
* SIFS: the index rebuild, we track the number of files pending.
* Query indexer: tracks the number of keys still pending. This does a `.size()` operation with a LOCAL flag :(
Closes #14804
=> [#14804] Long running tasks progress tracker

core/src/main/java/org/infinispan/manager/CacheManagerInfo.java, core/src/main/java/org/infinispan/topology/LocalTopologyManager.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, server/tests/src/test/java/org/infinispan/server/resilience/GracefulShutdownRestartIT.java
* The ready endpoint allow caches waiting for the cluster shutdown procedure to complete as ready.
* The probe must return 200 to continue to the next pod.
=> [#14802] Recovering caches marked as ready

core/src/main/java/org/infinispan/manager/CacheManagerInfo.java, core/src/main/java/org/infinispan/topology/LocalTopologyManager.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, server/tests/src/test/java/org/infinispan/server/resilience/GracefulShutdownRestartIT.java
**Backport:** https://github.com/infinispan/infinispan/pull/14869
* The ready endpoint allow caches waiting for the cluster shutdown procedure to complete as ready.
* The probe must return 200 to continue to the next pod.
=> [15.2.x] [#14802] Recovering caches marked as ready

commons/all/src/main/java/org/infinispan/commons/internal/CommonsBlockHoundIntegration.java, commons/all/src/main/java/org/infinispan/commons/logging/Log.java, commons/all/src/main/java/org/infinispan/commons/logging/LogFactory.java, commons/all/src/main/java/org/infinispan/commons/util/ProgressTracker.java, commons/all/src/test/java/org/infinispan/commons/util/ProgressTrackerTest.java, core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/FileProvider.java, core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java, query/src/main/java/org/infinispan/query/impl/ComponentRegistryUtils.java, query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java, query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerProgressState.java, tools/src/main/java/org/infinispan/tools/store/migrator/file/SoftIndexFileStoreIterator.java
**Backport:** https://github.com/infinispan/infinispan/pull/14817
The tracker will receive the expected number of operations still pending to perform and will gradually reach zero. The timeout executor will output how many tasks are still pending and whether it has progressed since the last check.
Currently, I am wrapping:
* State transfer: keep track of outstanding requests for segments. This is the same metric we expose.
* SIFS: the index rebuild, we track the number of files pending.
* Query indexer: tracks the number of keys still pending. This does a `.size()` operation with a LOCAL flag :(
Closes #14804
=> [15.2.x] [#14804] Long running tasks progress tracker

commons/all/src/main/java/org/infinispan/commons/internal/CommonsBlockHoundIntegration.java, commons/all/src/main/java/org/infinispan/commons/logging/Log.java, commons/all/src/main/java/org/infinispan/commons/logging/LogFactory.java, commons/all/src/main/java/org/infinispan/commons/util/ProgressTracker.java, commons/all/src/test/java/org/infinispan/commons/util/ProgressTrackerTest.java, core/src/main/java/org/infinispan/persistence/sifs/Compactor.java, core/src/main/java/org/infinispan/persistence/sifs/FileProvider.java, core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java, core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java, core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java, query/src/main/java/org/infinispan/query/impl/ComponentRegistryUtils.java, query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java, query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerProgressState.java, tools/src/main/java/org/infinispan/tools/store/migrator/file/SoftIndexFileStoreIterator.java
**Backport:** https://github.com/infinispan/infinispan/pull/14817
The tracker will receive the expected number of operations still pending to perform and will gradually reach zero. The timeout executor will output how many tasks are still pending and whether it has progressed since the last check.
Currently, I am wrapping:
* State transfer: keep track of outstanding requests for segments. This is the same metric we expose.
* SIFS: the index rebuild, we track the number of files pending.
* Query indexer: tracks the number of keys still pending. This does a `.size()` operation with a LOCAL flag :(
Closes #14804
=> [15.0.x] [#14804] Long running tasks progress tracker

core/src/main/java/org/infinispan/distribution/ch/ConsistentHash.java, core/src/main/java/org/infinispan/distribution/ch/ConsistentHashFactory.java, core/src/main/java/org/infinispan/distribution/ch/PersistedConsistentHash.java, core/src/main/java/org/infinispan/distribution/ch/impl/AbstractConsistentHash.java, core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHash.java, core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHashFactory.java, core/src/main/java/org/infinispan/distribution/ch/impl/PersistedMembers.java, core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHash.java, core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHashFactory.java, core/src/main/java/org/infinispan/distribution/ch/impl/SyncConsistentHashFactory.java, core/src/main/java/org/infinispan/distribution/ch/impl/SyncReplicatedConsistentHashFactory.java, core/src/main/java/org/infinispan/partitionhandling/impl/PreferConsistencyStrategy.java, core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/main/java/org/infinispan/topology/PersistentUUIDManager.java, core/src/main/java/org/infinispan/topology/PersistentUUIDManagerImpl.java, core/src/test/java/org/infinispan/distribution/ch/BaseCHPersistenceTest.java, core/src/test/java/org/infinispan/notifications/cachelistener/OnlyPrimaryOwnerTest.java, core/src/test/java/org/infinispan/util/BaseControlledConsistentHashFactory.java
Closes #14806 
Not ready yet. I think this is the last place that forces `PersistentUUID` to implement `Address` :crossed_fingers:
=> [#14806] Add mapper to ConsistentHashFactory.fromPersistentState method

core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/main/java/org/infinispan/persistence/sifs/Index.java, core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java, core/src/main/java/org/infinispan/util/logging/Log.java
**Backport:** https://github.com/infinispan/infinispan/pull/14902
* Catching a Throwable for Index start.
Closes #14900
=> [15.2.x] [#14900] Update exception handling

core/src/main/resources/default-configs/default-jgroups-azure.xml, core/src/main/resources/default-configs/default-jgroups-ec2.xml, core/src/main/resources/default-configs/default-jgroups-google.xml, core/src/main/resources/default-configs/default-jgroups-kubernetes.xml, core/src/main/resources/default-configs/default-jgroups-tcp.xml, core/src/main/resources/default-configs/default-jgroups-tunnel.xml, core/src/main/resources/default-configs/default-jgroups-udp.xml
**Backport:** https://github.com/infinispan/infinispan/pull/14726
Closes #14725
=> [15.2.x] [#14725] Add port_range back to the default stacks

core/src/main/java/org/infinispan/persistence/sifs/Index.java
Fixes #14963
Make sure that when an index is not able to be loaded that all tertiary loaded things are also properly cleared out.
=> [#14963] SIFS may encounter negative size exception on restart

core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreTest.java, core/src/test/java/org/infinispan/test/Mocks.java
it didn't own all segments on shutdown
Fixes #14965
Adds a test to verify that reset is not invoked when segments are not owned during restart.
=> [#14965] SoftIndexFileStore on restart will report the index is dirty if

core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreTest.java, core/src/test/java/org/infinispan/test/Mocks.java
**Backport:** https://github.com/infinispan/infinispan/pull/14984
it didn't own all segments on shutdown
Fixes #14965
Adds a test to verify that reset is not invoked when segments are not owned during restart.
=> [15.0.x] [#14965] SoftIndexFileStore on restart will report the index is dirty if

core/src/main/java/org/infinispan/CoreModule.java, core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java, core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/test/java/org/infinispan/manager/CacheManagerTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/14919
* Terminate might hang until a cache has started.
* Terminate verifies if the cache has started, and completes exceptionally.
Closes #14917
=> [15.2.x] [#14917] Terminate completes pending cache start exceptionally

client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelCloseAndInactiveTest.java
* Increase operation timeout to avoid retries.
The failure happens because the timeout adds the operation to the queue again, and some of the validations don't expect that.
This is failing hard on 15.2.x. The test is only on the legacy HR client and doesn't exist in main.
Closes #14472
=> [15.2.x] [#14472] Fix ChannelCloseAndInactiveTest failure

commons-test/src/main/java/org/infinispan/commons/test/Combinations.java, server/tests/src/test/java/org/infinispan/server/functional/ClusteredIT.java, server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodFlagCacheOperations.java, server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodTransactionalCacheOperations.java
* Create simple tests with common APIs varying every combination of flags.
This is part of #13263. There are still some more tests to add with other functionalities:
* expiration/eviction
* invalidation/L1
* functional operations
Are still missing.
=> [#13263] Add IT tests mixing HR flags

.github/workflows/on_build_do_test.yml, anchored-keys/pom.xml, cdi/embedded/pom.xml, cdi/remote/pom.xml, client/hotrod-client/pom.xml, core/pom.xml, counter/pom.xml, gridfs/pom.xml, integrationtests/cdi-weld-se-it/pom.xml, integrationtests/endpoints-interop-it/pom.xml, integrationtests/jboss-marshalling-it/pom.xml, jcache/embedded/pom.xml, jcache/remote/pom.xml, lock/pom.xml, multimap/pom.xml, persistence/remote/pom.xml, persistence/rocksdb/pom.xml, query-core/pom.xml, query/pom.xml, remote-query/remote-query-server/pom.xml, server/core/pom.xml, server/hotrod/pom.xml, server/memcached/pom.xml, server/resp/pom.xml, server/rest/pom.xml, spring/spring6/spring6-embedded/pom.xml, spring/spring6/spring6-remote/pom.xml, tasks/manager/pom.xml, tasks/scripting/pom.xml, tools/pom.xml
Closes #14390 and replaces #14391.
Move default surefire report in an ignored folder so to avoid conflicts in modules with testng engine that generates polarion reports.
Needs to be merged to have effect
=> [#14390] Avoid file clash in surefire-reports

client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java, commons/all/src/main/java/org/infinispan/commons/api/BasicCacheContainer.java, core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java, core/src/main/java/org/infinispan/manager/DefaultCacheManager.java, core/src/main/java/org/infinispan/manager/impl/AbstractDelegatingEmbeddedCacheManager.java, core/src/main/java/org/infinispan/partitionhandling/AvailabilityMode.java, core/src/main/java/org/infinispan/partitionhandling/impl/PartitionHandlingManagerImpl.java, core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java, core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java, core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java, core/src/test/java/org/infinispan/globalstate/GracefulShutdownTest.java, core/src/test/java/org/infinispan/globalstate/TransactionalGracefulShutdownTest.java
We use the shutdown message that the coordinator broadcasts to stop the component registry. To handle the joiners after shutdown, I've added a new entry in the `AvailabilityMode` to `STOPPED`, and that value is returned in the join response.
I've included a `stopCache(String)` in the `BasicCacheContainer` API because we need a way to stop the cache when the join response is in the `STOPPED` state. We can't use `EmbeddedCacheManager#getCache(String).stop()` because that would block until the cache is completely initialized. With the new API to stop, we are sure that the caller of `getCache(String)`, which initiated the join, will receive an instance already stopped and won't be able to submit operations.
I'll add documentation next, but the main changes are ready. The backport would …
=> [#14879] Cluster-wide cache shutdown

core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java, core/src/main/java/org/infinispan/util/logging/Log.java, core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsTransportTest.java
**Backport:** https://github.com/infinispan/infinispan/pull/15096
Fixes #15070
=> [15.0.x] [#15070] Do not install outdated JGroups views

server/rollingupgradetests/pom.xml, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/PersistenceRollingUpgradeIT.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradePersistenceTest.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/AbstractTestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/CommonTestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestClientDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/persistence/DatabaseServerListener.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/CombinedInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfiguration.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestMethodRule.java, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerExtension.java, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/RollingUpgradeHandlerExtension.java, server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheOperations.java, server/tests/src/test/java/org/infinispan/server/persistence/AsyncJdbcStringBasedCacheStore.java, server/tests/src/test/java/org/infinispan/server/persistence/BaseJdbcStringBasedCacheStoreIT.java, server/tests/src/test/java/org/infinispan/server/persistence/BasePooledConnectionOperations.java, server/tests/src/test/java/org/infinispan/server/persistence/JdbcStringBasedCacheStoreIT.java, server/tests/src/test/java/org/infinispan/server/persistence/ManagedConnectionOperations.java, server/tests/src/test/java/org/infinispan/server/persistence/PersistenceIT.java, server/tests/src/test/java/org/infinispan/server/persistence/PooledConnectionOperations.java, server/tests/src/test/resources/database/mssql.properties, server/tests/src/test/resources/database/mysql.properties, server/tests/src/test/resources/database/oracle.properties, server/tests/src/test/resources/database/postgres.properties
* HotRod operations now use SIFS.
* Add listener support to rolling upgrade handler.
* Split PersistenceIT tests that don't change the driver lifecycle.
* Create extra tests for rolling upgrades with persistence configured.
Closes #15128.
=> [#15128] Rolling upgrades with persistence enabled

.github/workflows/operator_upgrade.yaml
This reverts commit b3568ce60504fb5c41ee7b8fabcf4eb7f5ebcace.
=> Revert "[#14712] Disable op upgrade test on main"

core/src/main/java/org/infinispan/manager/CacheManagerInfo.java, server/rest/src/main/java/org/infinispan/rest/resources/HealthCheckResource.java, server/rest/src/test/java/org/infinispan/rest/RestServerLifecycleTest.java, server/rest/src/test/java/org/infinispan/rest/resources/HealthCheckResourceTest.java
* Readiness will always be available if server and cache manager have started.
* Readiness will become unavailable if all caches are shutdown. This handle graceful shutdown.
Closes #15253.
=> [#15253] Update readiness probe

server/runtime/src/main/java/org/infinispan/server/Server.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
* Change server to running only after post start.
* Embedded driver wait until server is ready (or failed).
Closes #15295.
=> [#15295] Change server status after post start

server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java
* When creating the builder, it automatically verifies the system properties.
When using maven, we pass the properties:
```
-Dorg.infinispan.test.server.rolling.upgrade.from="image://quay.io/infinispan/server:15.2.0.Final" \
-Dorg.infinispan.test.server.rolling.upgrade.to="image://quay.io/infinispan/server:15.2.4.Final-1"
```
Closes #15264.
=> [#15264] Configurable version by system properties

core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/ClusteredRollingUpgradeIT.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradePersistenceTest.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeTaskTest.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeXSiteIT.java, server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestClientXSiteDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractServerConfigBuilder.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfiguration.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeXSiteHandler.java, server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanXSiteServerTestMethodRule.java, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/CustomInfinispanExtension.java, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanXSiteServerExtension.java, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanXSiteServerExtensionBuilder.java, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/RollingUpgradeHandlerExtension.java, server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/RollingUpgradeHandlerXSiteExtension.java, server/tests/src/test/java/org/infinispan/server/cli/XSiteCliOperations.java, server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java, server/tests/src/test/java/org/infinispan/server/functional/hotrod/XSiteHotRodCacheOperations.java, server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestCacheOperations.java, server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestMetricsOperations.java
Fixes #15272
Fixes #15340
The extension currently starts up the nodes in each configured site and migrates one server on each site. While this is not how a user would normally do this, I figured it was more strict having a "mixed" cluster for each site to catch various issues.
=> [#15272] Add RollingUpgrade support for XSite integration tests

server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/ClusteredRollingUpgradeIT.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/DefaultRollingUpgradeTest.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/PersistenceRollingUpgradeIT.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeAuthenticationIT.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradePersistenceTest.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeTaskTest.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeTestUtil.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeXSiteIT.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractServerConfigBuilder.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeHandler.java
Fixes #15305
Fixes #15341
This PR also fixes some issues with a container running off of a base image. That is that it uses JAVA_OPTIONS instead of JAVA_OPTS and also that we need to increase the max metaspace when using code coverage as 96MB was not enough.
=> [#15305] Rolling Upgrade tests versions are overridden by INFINISPAN_TEST_SERVER_DIR env var

server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/DefaultRollingUpgradeTestIT.java, server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradePersistenceTestIT.java, server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java
* Give preference to the environment variable.
* Fallback to the programmatic configuration (tcp).
Now, we can run with something like:
```
./mvnw clean verify -Dinfinispan.cluster.stack=test-udp -pl server/rollingupgradetests -Dit.test=ClusteredRollingUpgradeIT
```
And it picks up the correct configuration:
```
[o.i.s.r.C.0.0.Dev02#1]STDOUT: 12:26:23,295 INFO  [o.i.CLUSTER] ISPN000078: Starting JGroups channel `org.infinispan.server.rollingupgrade.ClusteredRollingUpgradeIT` with stack `test-udp`
```
Closes #15386.
=> [#15386] Rolling upgrade tests accept JGroups stack

build/configuration/pom.xml
=> [15.0] Blockhound 1.0.13

.github/workflows/ci-static-checker.yml
fixes #15659 
Addind static check for github workflow when changed in a PR.
Example of run : https://github.com/rigazilla/infinispan/actions/runs/17980771986/job/51145947747?pr=157
=> [#15659] Static check for Github workflow
